import {useEffect,useRef,useState,type PointerEvent,type KeyboardEvent} from 'react';
import {createPortal} from 'react-dom';
import type {OutlinePoint} from '../types';
import {centerInlaySketch,finishInlaySketch,inlaySketchArea,inlaySketchBounds,inlaySketchCorner,inlaySketchProblem,moveInlaySketchPoint,resizeInlaySketch,INLAY_SKETCH_LIMITS} from './inlaySketchGeometry';
import './inlaySketch.css';

export interface InlaySketchEditorProps{open:boolean;onClose:()=>void;onComplete:(points:OutlinePoint[],name?:string)=>void;initialPoints?:OutlinePoint[];initialName?:string}
type Draft={points:OutlinePoint[];closed:boolean};
type Pull={id:number;index:number;start:OutlinePoint;before:Draft};
const text=(points:OutlinePoint[])=>points.map(p=>`${p.x},${p.y}`).join(' ');
const same=(a:Draft,b:Draft)=>JSON.stringify(a)===JSON.stringify(b);
const copy=(d:Draft):Draft=>({points:d.points.map(p=>({...p})),closed:d.closed});
export default function InlaySketchEditor(props:InlaySketchEditorProps){return props.open?<Workspace {...props}/>:null;}
function Workspace({onClose,onComplete,initialPoints,initialName}:InlaySketchEditorProps){
 const [draft,setDraft]=useState<Draft>(()=>({points:initialPoints?.map(p=>({...p}))??[],closed:!!initialPoints?.length})),draftRef=useRef(draft);
 const [past,setPast]=useState<Draft[]>([]),[future,setFuture]=useState<Draft[]>([]),[square,setSquare]=useState(true),[cursor,setCursor]=useState<OutlinePoint|null>(null),[error,setError]=useState(''),[name,setName]=useState(initialName??'Custom inlay');
 const [selected,setSelected]=useState(0),[pull,setPull]=useState<Pull|null>(null),pullRef=useRef<Pull|null>(null),drawPointer=useRef<number|null>(null);
 const [wf,setWf]=useState(''),[wi,setWi]=useState(''),[df,setDf]=useState(''),[di,setDi]=useState('');
 const [unitsPerPixel,setUnitsPerPixel]=useState(1);
 const svg=useRef<SVGSVGElement>(null),dialog=useRef<HTMLDivElement>(null),cancel=useRef<HTMLButtonElement>(null);
 const assign=(d:Draft)=>{draftRef.current=d;setDraft(d);};
 const commit=(next:Draft,previous=draftRef.current)=>{if(same(next,previous))return;setPast(p=>[...p,copy(previous)].slice(-40));setFuture([]);assign(next);setError('');};
 const undo=()=>{if(!past.length)return;const next=past.at(-1)!,previous=copy(draftRef.current);setPast(p=>p.slice(0,-1));setFuture(f=>[previous,...f]);assign(copy(next));setError('');setCursor(null);};
 const redo=()=>{if(!future.length)return;const previous=copy(draftRef.current);setPast(p=>[...p,previous]);const next=future[0];setFuture(f=>f.slice(1));assign(copy(next));setError('');};
 const finish=()=>{const current=draftRef.current;if(current.closed)return;const points=finishInlaySketch(current.points,square),problem=inlaySketchProblem(points);if(problem){setError(problem);return;}commit({points:centerInlaySketch(points),closed:true});setCursor(null);};
 const actions=useRef({onClose,finish,undo,redo});actions.current={onClose,finish,undo,redo};
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';cancel.current?.focus();
  const key=(e:globalThis.KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();actions.current.onClose();return;}if(/INPUT|SELECT|TEXTAREA/.test((e.target as HTMLElement)?.tagName))return;
   if(e.key==='Backspace'||(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();e.shiftKey?actions.current.redo():actions.current.undo();}
   else if(e.key==='Enter'&&e.target===svg.current){e.preventDefault();e.stopPropagation();actions.current.finish();}
   if(e.key==='Tab'){const nodes=[...dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]')??[]].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}
  };document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus();};
 },[]);
 useEffect(()=>{if(!draft.points.length){setWf('');setWi('');setDf('');setDi('');return;}const b=inlaySketchBounds(draft.points),parts=(v:number)=>[String(Math.floor(v/12)),String(Math.round((v%12)*1000)/1000)];const w=parts(b.w),d=parts(b.h);setWf(w[0]);setWi(w[1]);setDf(d[0]);setDi(d[1]);},[draft]);
 useEffect(()=>{const el=svg.current;if(!el)return;const measure=()=>setUnitsPerPixel(1/(el.getScreenCTM()?.a||1)),observer=new ResizeObserver(measure);observer.observe(el);measure();return()=>observer.disconnect();},[]);
 const point=(e:{clientX:number;clientY:number}):OutlinePoint=>{const matrix=svg.current?.getScreenCTM()?.inverse();const p=matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix):{x:0,y:0};return {x:Math.max(-132,Math.min(132,p.x)),y:Math.max(-132,Math.min(132,p.y))};};
 const target=(e:PointerEvent<SVGSVGElement>)=>inlaySketchCorner(draftRef.current.points,point(e),square||e.shiftKey,2);
 const begin=(e:PointerEvent<SVGSVGElement>)=>{if(!e.isPrimary||e.pointerType==='mouse'&&e.button!==0||draftRef.current.closed)return;e.preventDefault();drawPointer.current=e.pointerId;svg.current?.setPointerCapture(e.pointerId);setCursor(target(e));};
 const move=(e:PointerEvent<SVGSVGElement>)=>{const active=pullRef.current;if(active&&active.id===e.pointerId){e.preventDefault();const p=point(e);assign({...active.before,points:moveInlaySketchPoint(active.before.points,active.index,p.x-active.start.x,p.y-active.start.y)});return;}if(!draftRef.current.closed)setCursor(target(e));};
 const up=(e:PointerEvent<SVGSVGElement>)=>{const active=pullRef.current;if(active&&active.id===e.pointerId){pullRef.current=null;setPull(null);commit(copy(draftRef.current),active.before);}else if(drawPointer.current===e.pointerId){drawPointer.current=null;const current=draftRef.current,p=target(e);if(current.points.length>=INLAY_SKETCH_LIMITS.points){setError('Use at most 64 corners.');return;}if(!current.points.length||Math.hypot(p.x-current.points.at(-1)!.x,p.y-current.points.at(-1)!.y)>.01)commit({points:[...current.points,p],closed:false});}
  if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);
 };
 const cancelPointer=(e:PointerEvent<SVGSVGElement>)=>{if(pullRef.current){assign(pullRef.current.before);pullRef.current=null;setPull(null);}drawPointer.current=null;if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);};
 const beginPull=(e:PointerEvent<SVGGElement>,index:number)=>{if(!e.isPrimary||e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.stopPropagation();setSelected(index);const active={id:e.pointerId,index,start:point(e),before:copy(draftRef.current)};pullRef.current=active;setPull(active);svg.current?.setPointerCapture(e.pointerId);};
 const pullKey=(e:KeyboardEvent<SVGGElement>,index:number)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete'].includes(e.key))return;e.preventDefault();e.stopPropagation();const current=draftRef.current;if(e.key==='Delete'){if(current.points.length<=3){setError('Keep at least three corners.');return;}commit({...current,points:current.points.filter((_,i)=>i!==index)});setSelected(Math.max(0,index-1));return;}const n=e.shiftKey?12:1;commit({...current,points:moveInlaySketchPoint(current.points,index,e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0,e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0)});};
 const applyDimensions=()=>{try{if(![wf,wi,df,di].every(v=>v.trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0))throw Error('Enter nonnegative feet and inches for both dimensions.');const points=centerInlaySketch(resizeInlaySketch(draftRef.current.points,Number(wf)*12+Number(wi),Number(df)*12+Number(di)));setError('');commit({...draftRef.current,points});}catch(e){setError((e as Error).message);}};
 const addCorner=()=>{const current=draftRef.current;if(current.points.length>=64){setError('Use at most 64 corners.');return;}const i=Math.min(selected,current.points.length-1),a=current.points[i],b=current.points[(i+1)%current.points.length];commit({...current,points:[...current.points.slice(0,i+1),{x:(a.x+b.x)/2,y:(a.y+b.y)/2},...current.points.slice(i+1)]});setSelected(i+1);};
 const complete=()=>{try{const points=centerInlaySketch(draftRef.current.points);if(!draftRef.current.closed)throw Error('Finish the shape before placing it.');onComplete(points,name.trim()||'Custom inlay');}catch(e){setError((e as Error).message);}};
 const b=draft.points.length?inlaySketchBounds(draft.points):{w:0,h:0},problem=draft.closed?inlaySketchProblem(draft.points):'';
 return createPortal(<div className="dd-inlay-sketch-backdrop"><section className="dd-inlay-sketch" ref={dialog} role="dialog" aria-modal="true" aria-label="Sketch an inlay">
  <header><div><span className="dd-inlay-eyebrow">DECKCRAFT · CUSTOM DETAILS</span><h2>Sketch an inlay</h2><p>Tap corners with a mouse, pen or finger. Right-click or Finish shape to close the outline.</p></div><button ref={cancel} type="button" onClick={onClose} aria-label="Cancel inlay sketch">Cancel</button></header>
  <div className="dd-inlay-sketch-body"><div className="dd-inlay-sketch-board"><div className="dd-inlay-sketch-toolbar"><label><input type="checkbox" checked={square} onChange={e=>setSquare(e.target.checked)}/>Keep lines square</label><button type="button" onClick={undo} disabled={!past.length}>Undo sketch</button><button type="button" onClick={redo} disabled={!future.length}>Redo sketch</button><button type="button" onClick={()=>{commit({points:[],closed:false});setCursor(null);}}>Clear drawing</button></div>
   <svg ref={svg} viewBox="-132 -132 264 264" role="application" aria-label="Inlay sketch drawing surface" tabIndex={0} onPointerDown={begin} onPointerMove={move} onPointerUp={up} onPointerCancel={cancelPointer} onContextMenu={e=>{e.preventDefault();finish();}} data-points={JSON.stringify(draft.points)} data-closed={String(draft.closed)}>
    <defs><pattern id="inlay-sketch-inch-grid" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M12 0H0V12" fill="none" stroke="#d5dace" strokeWidth=".25"/></pattern></defs><rect x="-132" y="-132" width="264" height="264" fill="url(#inlay-sketch-inch-grid)"/>
    <path d="M-132 0H132M0 -132V132" stroke="#a4afa0" strokeWidth=".35" strokeDasharray="2 2"/>
    {draft.closed?<polygon points={text(draft.points)} className={problem?'invalid':'shape'}/>:<polyline points={text(draft.points)} className="line"/>}
    {!draft.closed&&cursor&&draft.points.length>0&&<line x1={draft.points.at(-1)!.x} y1={draft.points.at(-1)!.y} x2={cursor.x} y2={cursor.y} className="guide"/>}
    {draft.points.map((p,i)=>draft.closed?<g key={i} role="button" tabIndex={0} aria-label={`Inlay sketch point ${i+1}`} onFocus={()=>setSelected(i)} onPointerDown={e=>beginPull(e,i)} onKeyDown={e=>pullKey(e,i)} className={`point ${selected===i?'selected':''} ${pull?.index===i?'pulling':''}`}><circle cx={p.x} cy={p.y} r={22*unitsPerPixel} fill="transparent"/><circle cx={p.x} cy={p.y} r="2.4"/><text x={p.x+4} y={p.y-4} style={{fontSize:10*unitsPerPixel}}>{i+1}</text></g>:<circle key={i} cx={p.x} cy={p.y} r="2" className="draft-point"/>)}
   </svg><div className="dd-inlay-sketch-scale">Each grid square is 1 foot · {draft.points.length} corners{draft.closed?` · ${(Math.abs(inlaySketchArea(draft.points))/144).toFixed(2)} sq ft`:''}</div><p className="dd-inlay-sketch-help">{draft.closed?'Pull a numbered point to reshape it. Arrow keys move 1 inch; Shift moves 1 foot. Delete removes a selected corner.':'Backspace or Undo removes the last corner. Turn off Keep lines square for diagonal edges.'}</p></div>
   <aside><label>Inlay name<input aria-label="Inlay sketch name" maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><h3>Measured size</h3><p>Measurements resize this shape. Placement and board finishes come next.</p>
    <fieldset disabled={!draft.closed}><legend>Width</legend><label>Feet<input aria-label="Inlay sketch width feet" type="number" min="0" max="20" step="any" value={wf} onChange={e=>setWf(e.target.value)}/></label><label>Inches<input aria-label="Inlay sketch width inches" type="number" min="0" step="any" value={wi} onChange={e=>setWi(e.target.value)}/></label></fieldset>
    <fieldset disabled={!draft.closed}><legend>Depth</legend><label>Feet<input aria-label="Inlay sketch depth feet" type="number" min="0" max="20" step="any" value={df} onChange={e=>setDf(e.target.value)}/></label><label>Inches<input aria-label="Inlay sketch depth inches" type="number" min="0" step="any" value={di} onChange={e=>setDi(e.target.value)}/></label></fieldset><button type="button" disabled={!draft.closed} onClick={applyDimensions}>Apply inlay measurements</button><p className="dd-inlay-sketch-size">{b.w.toFixed(1)} × {b.h.toFixed(1)} inches</p>
    {draft.closed&&<button type="button" onClick={addCorner}>Add corner after selected point</button>}{(error||problem)&&<p role="alert">{error||problem}</p>}<p className="dd-inlay-sketch-note">Your deck stays unchanged while you draw. A finished shape is ready to place on the plan.</p></aside></div>
  <footer><span>{draft.closed?'Shape ready for placement':'Draw at least three corners'}</span>{!draft.closed?<button type="button" className="primary" onClick={finish}>Finish shape</button>:<button type="button" className="primary" onClick={complete}>Place on deck</button>}</footer>
 </section></div>,document.body);
}
