type ProductShape={name:string;geometry:string;finish?:string;dimensionsIn:{height?:number;width?:number;length?:number;diameter?:number;mountingDepth?:number}};

/** Family envelopes use published dimensions where available. Unspecified
 * profile/cord/stem details are illustrative and disclosed in the catalogue. */
export default function CatalogueFixture({product,evening,enabled=true}:{product:ProductShape;evening:boolean;enabled?:boolean}){
 const {geometry:g,dimensionsIn:d}=product,finish=(product.finish||'').toLowerCase();
 const color=finish.includes('white')?'#e6e5df':finish.includes('rose')?'#a99084':finish.includes('silver')||finish.includes('steel')?'#a7afb1':'#272d2c';
 const dark=<meshStandardMaterial color={color} metalness={finish.includes('white')?.1:.6} roughness={.4}/>;
 const lit=<meshStandardMaterial color="#ffefd7" emissive="#ffd1a0" emissiveIntensity={enabled?(evening?4.5:.5):0} toneMapped={false}/>;
 const diameter=d.diameter??d.width??2.2,w=d.width??d.diameter??2.5,h=d.height??3,depth=d.length??1.5;
 if(g==='recessed'){const height=d.height??d.mountingDepth??1.4,r=diameter/2;return <group name="recessed-catalogue-housing"><mesh position={[0,-height/2,0]}><cylinderGeometry args={[r,r*.93,height,24]}/>{dark}</mesh><mesh position={[0,.08,0]}><cylinderGeometry args={[r*.83,r*.83,.12,24]}/>{lit}</mesh></group>;}
 if(g==='wall'){const faceH=d.diameter??h,bodyDepth=d.diameter?(d.height??d.length??1):depth;return <group name="wall-catalogue-housing"><mesh rotation={[d.diameter?Math.PI/2:0,0,0]}>{d.diameter?<cylinderGeometry args={[diameter/2,diameter/2,bodyDepth,24]}/>:<boxGeometry args={[w,faceH,bodyDepth]}/>}{dark}</mesh><mesh position={[0,-faceH/2-.02,bodyDepth*.23]}><boxGeometry args={[w*.72,.08,Math.min(bodyDepth*.55,1)]}/>{lit}</mesh></group>;}
 if(g==='undercap'){const length=d.length??12,height=d.height??.5,width=d.width??.7;return <group name="linear-catalogue-housing"><mesh><boxGeometry args={[length,height,width]}/>{dark}</mesh><mesh position={[0,-height/2-.025,0]}><boxGeometry args={[Math.max(.2,length-.25),.05,width*.7]}/>{lit}</mesh></group>;}
 if(g==='bollard'){const height=d.height??24,r=(d.diameter??d.width??2)/2;return <group name="bollard-catalogue-housing"><mesh position={[0,height/2,0]}><cylinderGeometry args={[r,r,height,20]}/>{dark}</mesh><mesh position={[0,height-1.5,0]}><cylinderGeometry args={[r*1.04,r*1.04,1.2,20]}/>{lit}</mesh><mesh position={[0,.12,0]}><cylinderGeometry args={[r*1.5,r*1.5,.25,20]}/>{dark}</mesh></group>;}
 if(g==='spot'){const height=d.height??5.5,r=diameter/2,length=d.length??3.5;return <group name="spot-catalogue-housing"><mesh position={[0,height*.25,0]}><cylinderGeometry args={[.18,.18,height*.5,10]}/>{dark}</mesh><group position={[0,height*.65,0]} rotation={[Math.PI/3,0,0]}><mesh><cylinderGeometry args={[r,r,length,24]}/>{dark}</mesh><mesh position={[0,length/2+.025,0]}><cylinderGeometry args={[r*.8,r*.8,.05,24]}/>{lit}</mesh></group></group>;}
 if(g==='pendant'){const height=d.height??5,r=diameter/2;return <group name="pendant-catalogue-housing"><mesh position={[0,-9,0]}><cylinderGeometry args={[.07,.07,18,8]}/>{dark}</mesh><mesh position={[0,-18-height/2,0]}><cylinderGeometry args={[r,r,height,24]}/>{dark}</mesh><mesh position={[0,-18-height-.03,0]}><cylinderGeometry args={[r*.82,r*.82,.06,24]}/>{lit}</mesh><mesh position={[0,-.1,0]}><cylinderGeometry args={[1,1,.2,16]}/>{dark}</mesh></group>;}
 if(g==='ceiling'){const height=d.height??2,r=diameter/2;return <group name="ceiling-catalogue-housing"><mesh position={[0,-height/2,0]}><cylinderGeometry args={[r,r,height,24]}/>{dark}</mesh><mesh position={[0,-height-.025,0]}><cylinderGeometry args={[r*.83,r*.83,.05,24]}/>{lit}</mesh></group>;}
 if(g==='transformer'){const width=d.width??6,height=d.height??9,length=d.length??3;return <group name="transformer-catalogue-housing"><mesh><boxGeometry args={[width,height,length]}/>{dark}</mesh><mesh position={[0,height*.18,length/2+.04]}><planeGeometry args={[width*.6,height*.23]}/><meshStandardMaterial color="#50645c" roughness={.7}/></mesh>{[-1,0,1].map(x=><mesh key={x} position={[x*width*.22,-height/2-.3,0]}><cylinderGeometry args={[.2,.2,.6,10]}/>{dark}</mesh>)}</group>;}
 if(g==='cable')return <group name="purchased-cable-coil">{[0,1,2,3].map(i=><mesh key={i} position={[0,i*.25,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[3+i*.18,.12,8,32]}/>{dark}</mesh>)}</group>;
 return <group name="accessory-catalogue-envelope"><mesh><boxGeometry args={[w,h,Math.min(depth,5)]}/>{dark}</mesh>{[-1,1].map(side=><mesh key={side} position={[side*(w/2+.22),0,0]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.22,.22,.44,10]}/>{dark}</mesh>)}</group>;
}
