import type {DeckData} from '../../types';
import type {Update} from '../../designer/fields';
import type {PergolaSelection} from '../../pergolaCatalog';
import {pergolaProduct,PERGOLA_PRODUCTS,newPergola} from '../../pergolaCatalog';
import {movedPergola,rotatedPergola} from '../../pergolaTransform';
import {pergolaLightingPatch} from '../../pergolaLighting';
import './PergolaTools.css';
export default function PergolaTools({data,selected,setSelected,mode,setMode,update}:{data:DeckData;selected:boolean;setSelected:(v:boolean)=>void;mode:'move'|'rotate';setMode:(v:'move'|'rotate')=>void;update:Update}){
 const s=data.pergola;
 const picker=<label className="dd-field"><span>Choose a pergola</span><select aria-label="3D pergola product" value={s?`${s.productId}|${s.variantId}`:''} onChange={e=>{const [product,variant]=e.target.value.split('|');if(!product)return;update({pergola:{...newPergola(product,variant),xFt:s?.xFt??data.width/2,zFt:s?.zFt??data.length/2,...(s?{target:s.target,rotationDeg:s.rotationDeg}:{})}});setSelected(true);}}><option value="">Select an aluminum pergola</option>{PERGOLA_PRODUCTS.flatMap(p=>p.variants.map(v=><option key={`${p.id}|${v.id}`} value={`${p.id}|${v.id}`}>{p.name} · {v.label} · {p.operation}</option>))}</select></label>;
 if(!s)return <section className="dd-pergola-tools" aria-label="Pergola preview controls">{picker}</section>;
 const change=(patch:Partial<PergolaSelection>)=>update({pergola:{...s,...patch}}),led=pergolaProduct(s)?.accessories.find(a=>a.kind==='led');
 return <section className="dd-pergola-tools" aria-label="Pergola preview controls"><details className="dd-pergola-product"><summary>Change pergola · {pergolaProduct(s)?.name}</summary>{picker}</details><div className="dd-pergola-tool-row"><strong>Pergola</strong><button type="button" className="dd-secondary" aria-label={selected?'Done editing pergola':'Select pergola'} aria-pressed={selected} onClick={()=>setSelected(!selected)}>{selected?'Done':'Select'}</button>{selected&&<><div role="group" aria-label="Pergola drag action">{(['move','rotate'] as const).map(action=><button type="button" key={action} className="dd-secondary" aria-label={action==='move'?'Move pergola':'Rotate pergola'} aria-pressed={mode===action} onClick={()=>setMode(action)}>{action==='move'?'Move':'Rotate'}</button>)}</div></>}</div>
 {selected&&<><p className="dd-pergola-help" role="status">{s.xFt} × {s.zFt} ft · {s.rotationDeg}° · {mode==='move'?'Drag to move.':'Drag around centre to rotate.'}</p><span id="dd-pergola-keyboard-help" className="sr-only">Arrow keys move half a foot; Shift + arrows rotate 15 degrees. Escape cancels a drag. Drag elsewhere to orbit.</span><div className="dd-pergola-tool-row" role="group" aria-label="Pergola position and rotation" aria-describedby="dd-pergola-keyboard-help" tabIndex={0} onKeyDown={e=>{if((e.target as HTMLElement).tagName==='INPUT')return;const direction=({ArrowLeft:[-.5,0],ArrowRight:[.5,0],ArrowUp:[0,-.5],ArrowDown:[0,.5]} as Record<string,number[]>)[e.key];if(!direction)return;e.preventDefault();change(e.shiftKey?rotatedPergola(s,(e.key==='ArrowLeft'||e.key==='ArrowUp')?-15:15):movedPergola(s,direction[0],direction[1]));}}>
 {([['←',-.5,0,'left'],['→',.5,0,'right'],['↑',0,-.5,'toward house'],['↓',0,.5,'away from house']] as const).map(([icon,x,z,label])=><button key={label} type="button" className="dd-secondary" aria-label={`Move pergola ${label} half a foot`} onClick={()=>change(movedPergola(s,x,z))}>{icon}</button>)}<button type="button" className="dd-secondary" aria-label="Rotate −15°" onClick={()=>change(rotatedPergola(s,-15))}>−15°</button><button type="button" className="dd-secondary" aria-label="Rotate +15°" onClick={()=>change(rotatedPergola(s,15))}>+15°</button></div></>}
 <label className="dd-check"><input type="checkbox" aria-label="Pergola LED lighting" checked={!!s.lighting||s.accessories.includes('led')} onChange={e=>change(pergolaLightingPatch(s,e.target.checked))}/><span>Warm white LEDs</span></label><small>{led?'Factory LEDs · cost in Extras.':'Planned perimeter LEDs · quote and compatibility required.'} Night shows illumination.</small></section>;
}
