import {useEffect,useRef} from 'react';
import {useFrame,useThree,type ThreeEvent} from '@react-three/fiber';
import * as THREE from 'three';
import type {DeckData} from '../../types';
import type {DeckTakeoff} from '../../deckTakeoff';
import type {SelectionState} from '../../designer/selectionState';
import type {SceneDragTarget,SceneDragValue,SceneEditInteraction} from '../../designer/sceneEditTypes';
import {sceneEditTarget} from '../../designer/sceneEditCommands';
import {convertLandscapeOutline,landscapeWorld} from '../../landscapeOutline';
import {sampleSiteHeight} from '../../siteSurface';
import {landscapeSurfaceDepth,puttingCupWorld} from '../../landscapeSurfaces';
import {yardWallStationPath} from '../../yardPathGeometry';
import {sceneSnapGeometry,snapScenePoint} from '../../designer/sceneSnapping';
import {patioTopPlane} from '../../yardElevationGeometry';
export default function SceneEditHandles({data,model,selection,interaction}:{data:DeckData;model:DeckTakeoff;selection:SelectionState;interaction:SceneEditInteraction}){
 const {controls,camera,gl,invalidate}=useThree(),target=sceneEditTarget(data,model,selection),latest=useRef(interaction);latest.current=interaction;
 const active=useRef(new Set<number>());
 const drag=useRef<{id:number;target:SceneDragTarget;plane:THREE.Plane;start:THREE.Vector3;origin:THREE.Vector3;last:SceneDragValue;capture:{releasePointerCapture?:(id:number)=>void};controlsEnabled:boolean;snapGeometry:ReturnType<typeof sceneSnapGeometry>;anchor:{x:number;z:number}}|null>(null),handles=useRef<THREE.Group>(null);
 const end=(cancel:boolean)=>{const d=drag.current;if(!d)return;drag.current=null;gl.domElement.style.cursor='';setTimeout(()=>{if(!drag.current)delete gl.domElement.dataset.editGesture;},0);if(controls&&'enabled'in controls)controls.enabled=d.controlsEnabled;try{d.capture.releasePointerCapture?.(d.id);}catch{}if(cancel)latest.current.onCancel();else latest.current.onFinish(d.target,d.last);invalidate();};
 useEffect(()=>{
  const down=(e:PointerEvent)=>{active.current.add(e.pointerId);if(active.current.size>1)end(true);},up=(e:PointerEvent)=>active.current.delete(e.pointerId);
  const cancel=()=>end(true),reset=()=>{active.current.clear();cancel();},hidden=()=>{if(document.hidden)reset();},key=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();},lost=(e:PointerEvent)=>{if(drag.current?.id===e.pointerId)cancel();};
  window.addEventListener('pointerdown',down,true);window.addEventListener('pointerup',up,true);window.addEventListener('pointercancel',cancel,true);window.addEventListener('pointercancel',up,true);window.addEventListener('keydown',key);window.addEventListener('blur',reset);document.addEventListener('visibilitychange',hidden);gl.domElement.addEventListener('webglcontextlost',reset);gl.domElement.addEventListener('lostpointercapture',lost);
  return()=>{reset();window.removeEventListener('pointerdown',down,true);window.removeEventListener('pointerup',up,true);window.removeEventListener('pointercancel',cancel,true);window.removeEventListener('pointercancel',up,true);window.removeEventListener('keydown',key);window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',hidden);gl.domElement.removeEventListener('webglcontextlost',reset);gl.domElement.removeEventListener('lostpointercapture',lost);};
 },[controls,gl]);
 useEffect(()=>{end(true);},[JSON.stringify(selection),interaction.mode]);
 useFrame(()=>{handles.current?.children.forEach(child=>{if(child.userData.editHandle){const mesh=child as THREE.Mesh,world=mesh.getWorldPosition(new THREE.Vector3()),scale=Math.max(.22,Math.min(2.5,camera.position.distanceTo(world)*.022));mesh.scale.setScalar(scale);}});});
 if(!target.modes.length||!selection.hardscape&&!selection.partIds.length&&!selection.objectIds?.length)return null;
 const origin=new THREE.Vector3(target.x/12,target.y/12,target.z/12);
 const start=(h:SceneDragTarget)=>(e:ThreeEvent<PointerEvent>)=>{if(e.button!==0||drag.current||active.current.size>1)return;e.stopPropagation();const plane=h.part==='elevation'?new THREE.Plane().setFromNormalAndCoplanarPoint(new THREE.Vector3(camera.position.x-e.point.x,0,camera.position.z-e.point.z).normalize(),e.point):new THREE.Plane(new THREE.Vector3(0,1,0),-e.point.y),hit=new THREE.Vector3();if(!e.ray.intersectPlane(plane,hit))return;latest.current.onCancel();const enabled=controls&&'enabled'in controls?Boolean(controls.enabled):true;if(controls&&'enabled'in controls)controls.enabled=false;const capture=e.target as unknown as {setPointerCapture:(id:number)=>void;releasePointerCapture:(id:number)=>void};capture.setPointerCapture(e.pointerId);gl.domElement.dataset.editGesture='true';drag.current={id:e.pointerId,target:h,plane,start:hit,origin,last:{dxIn:0,dzIn:0,dyIn:0,angleDeg:0,world:{x:e.point.x*12,z:e.point.z*12}},capture,controlsEnabled:enabled,snapGeometry:sceneSnapGeometry(data,model,selection),anchor:{x:target.x,z:target.z}};invalidate();};
 const move=(e:ThreeEvent<PointerEvent>)=>{const d=drag.current;if(!d||e.pointerId!==d.id)return;e.stopPropagation();const p=new THREE.Vector3();if(!e.ray.intersectPlane(d.plane,p))return;const snap=(n:number)=>latest.current.snapIn?Math.round(n/latest.current.snapIn)*latest.current.snapIn:n,angle=(Math.atan2(p.z-d.origin.z,p.x-d.origin.x)-Math.atan2(d.start.z-d.origin.z,d.start.x-d.origin.x))*180/Math.PI,value={dxIn:snap((p.x-d.start.x)*12),dzIn:snap((p.z-d.start.z)*12),dyIn:snap((p.y-d.start.y)*12),angleDeg:((angle+540)%360)-180,world:{x:snap(p.x*12),z:snap(p.z*12)}};if(latest.current.snapIn&&['move','point','bend','c1','c2','cup'].includes(d.target.part)){const anchor=d.target.part==='move'?{x:d.anchor.x+value.dxIn,z:d.anchor.z+value.dzIn}:value.world,q=snapScenePoint(anchor,d.snapGeometry,Math.max(2,Math.min(6,latest.current.snapIn)));if(d.target.part==='move'){value.dxIn+=q.x-anchor.x;value.dzIn+=q.z-anchor.z;}else value.world=q;}d.last=value;latest.current.onDraft(d.target,value);invalidate();};
 const height=(x:number,z:number)=>{if(target.o)return (sampleSiteHeight(data,x,z)??0)+(target.o.kind==='bed'?landscapeSurfaceDepth(target.o):0)+2;if(target.pool)return target.pool.copingTopElevationIn+2;if(target.f?.kind==='patio'){const p=patioTopPlane(target.f,sampleSiteHeight(data,target.f.xFt*12,target.f.zFt*12)??0);return p.x*x+p.z*z+p.constant+2;}if(target.f?.kind==='retaining-wall'){const path=yardWallStationPath(target.f);let closest=Infinity,station=0;for(let i=1;i<path.points.length;i++){const a=path.points[i-1],b=path.points[i],dx=b.x-a.x,dz=b.y-a.y,t=Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.y)*dz)/(dx*dx+dz*dz))),distance=Math.hypot(x-a.x-t*dx,z-a.y-t*dz);if(distance<closest){closest=distance;station=path.stations[i-1]+t*(path.stations[i]-path.stations[i-1]);}}return ([...(target.f.wallTopSteps??[])].reverse().find(s=>s.stationIn<=station+1e-6)?.elevationIn??target.y)+2;}return target.y+2;};
 const handle=(h:SceneDragTarget,x:number,z:number,y:number,color:string)=><mesh key={`${h.part}-${h.ring??0}-${h.index??0}`} position={[x/12,y/12,z/12]} renderOrder={110} userData={{editHandle:true,selectionPassthrough:true}} onPointerDown={start(h)} onPointerMove={move} onPointerUp={e=>{if(drag.current?.id!==e.pointerId)return;e.stopPropagation();end(false);}} onPointerCancel={()=>end(true)} onPointerOver={()=>{gl.domElement.style.cursor='grab';}} onPointerOut={()=>{gl.domElement.style.cursor='';}}><sphereGeometry args={[1,16,10]}/><meshBasicMaterial color={color} depthTest={false} transparent opacity={.95}/></mesh>;
 const items=[];
 if(interaction.mode==='move')items.push(handle({part:'move'},target.x,target.z,target.y+8,'#ebb249'));
 if(interaction.mode==='rotate')items.push(handle({part:'rotate'},target.x+Math.max(36,target.width*.6),target.z,target.y+8,'#80bbe0'));
 if(interaction.mode==='resize'){const a=(target.o?.rotationDeg??target.f?.rotationDeg??0)*Math.PI/180,x=target.x+Math.cos(a)*target.width/2-Math.sin(a)*target.depth/2,z=target.z+Math.sin(a)*target.width/2+Math.cos(a)*target.depth/2;items.push(handle({part:'resize'},x,z,height(x,z),'#d296dc'));}
 if(interaction.mode==='elevation')items.push(handle({part:'elevation'},target.x,target.z,target.y+24,'#de7975'));
 if(interaction.mode==='shape'){
  if(target.o?.kind==='bed'){const o=convertLandscapeOutline(target.o);[o.outline!.outer,...o.outline!.holes].forEach((r,ring)=>r.points.forEach((p,index)=>{const a=landscapeWorld(o,p),b=landscapeWorld(o,r.points[(index+1)%r.points.length]),s=r.segments[index];items.push(handle({part:'point',ring,index},a.x,a.z,height(a.x,a.z),'#ebb249'));if(s.kind==='cubic'){for(const part of ['c1','c2'] as const){const q=landscapeWorld(o,s[part]);items.push(handle({part,ring,index},q.x,q.z,height(q.x,q.z),'#80bbe0'));}}else{const len=Math.hypot(b.x-a.x,b.z-a.z),bend=s.kind==='arc'?s.bulgeIn:0,x=(a.x+b.x)/2-(b.z-a.z)/len*bend,z=(a.z+b.z)/2+(b.x-a.x)/len*bend;items.push(handle({part:'bend',ring,index},x,z,height(x,z),'#f4ddac'));}}));o.puttingCups?.forEach((p,index)=>{const q=puttingCupWorld(o,p);items.push(handle({part:'cup',index},q.x,q.z,height(q.x,q.z)+3,'#fff'));});}
  else target.points.forEach((p,index)=>{items.push(handle({part:'point',index},p.x,p.z,height(p.x,p.z),'#ebb249'));if(target.f&&!target.f.stepAssembly&&!target.f.stoneSteps&&(target.f.kind==='patio'||index<target.points.length-1)){const b=target.points[(index+1)%target.points.length],curve=target.f.curves?.find(c=>c.edge===index),len=Math.hypot(b.x-p.x,b.z-p.z),x=(p.x+b.x)/2-(b.z-p.z)/len*(curve?.bulgeIn??0),z=(p.z+b.z)/2+(b.x-p.x)/len*(curve?.bulgeIn??0);items.push(handle({part:'bend',index},x,z,height(x,z),'#f4ddac'));}});
 }
 return <group ref={handles} name="scene-edit-handles">{items}</group>;
}
