import {useEffect,useMemo,useState} from 'react';
import type {DeckData} from './types';
import type {DeckTakeoff} from './deckTakeoff';
import {boardFinishStatus,FINISH_GROUP_LABELS,MAX_BOARD_FINISHES,type BoardFinishOverride,type BoardInteraction,type FinishBoardGroup} from './boardFinishes';

type Props={data:DeckData;model:DeckTakeoff;onChange:(patch:Partial<DeckData>)=>void}&BoardInteraction;
export default function BoardFinishEditor({data,model,onChange,selectedBoardId,onSelectBoard}:Props){
  const status=useMemo(()=>boardFinishStatus(data,model),[data,model]),[scope,setScope]=useState<FinishBoardGroup|'all'>('all'),[search,setSearch]=useState(''),[localId,setLocalId]=useState(''),[color,setColor]=useState('#725846'),[history,setHistory]=useState<BoardFinishOverride[][]>([]),[error,setError]=useState('');
  const selectedId=selectedBoardId??localId,selected=status.boards.find(b=>b.id===selectedId),override=status.overrides.find(o=>o.id===selectedId);
  const available=status.boards.filter(b=>(scope==='all'||b.group===scope)&&(!search||`${b.label} ${b.id}`.toLowerCase().includes(search.toLowerCase())));
  const currentIndex=available.findIndex(b=>b.id===selectedId);
  useEffect(()=>{if(override)setColor(override.color);},[selectedId,override?.color]);
  function select(id:string){setLocalId(id);onSelectBoard?.(id);setError('');}
  function change(next:BoardFinishOverride[]){setHistory(h=>[...h.slice(-19),status.overrides]);onChange({boardFinishes:next});setError('');}
  function apply(){if(!selected)return;if(!/^#[a-fA-F0-9]{6}$/.test(color)){setError('Enter a six-digit colour such as #725846.');return;}const kept=status.overrides.filter(o=>o.id!==selected.id);if(kept.length>=MAX_BOARD_FINISHES){setError('Up to 512 individual board colours are supported. Reset another board first.');return;}change([...kept,{id:selected.id,color:color.toUpperCase()}]);}
  return <section className="dd-board-finish-editor space-y-4" aria-label="Individual board colours">
    <div><h3 className="font-semibold">Colour any finish board</h3><p className="text-sm text-slate-600">Click a board in the 3D view or choose a piece below. Dragging still orbits the model. Deck boards, borders, stair treads, risers, manufacturer fascia and skirting can be selected separately.</p></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Board group<select className="mt-1 w-full rounded border p-2" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="all">All finish boards</option>{Object.entries(FINISH_GROUP_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="text-sm">Find board<input className="mt-1 w-full rounded border p-2" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Field, border, riser…"/></label></div>
    <label className="block text-sm">Installed piece<select aria-label="Select finish board" className="mt-1 w-full rounded border p-2" value={available.some(b=>b.id===selectedId)?selectedId:''} onChange={e=>select(e.target.value)}><option value="">Choose a board ({available.length} available)</option>{available.map(b=><option key={b.id} value={b.id}>{b.label}{status.overrides.some(o=>o.id===b.id)?' · custom colour':''}</option>)}</select></label>
    <div className="flex flex-wrap gap-2"><button type="button" className="rounded border px-3 py-2 text-sm disabled:opacity-40" disabled={!available.length||currentIndex<=0} onClick={()=>select(available[currentIndex-1].id)}>Previous board</button><button type="button" className="rounded border px-3 py-2 text-sm disabled:opacity-40" disabled={!available.length||currentIndex>=available.length-1} onClick={()=>select(available[Math.max(0,currentIndex+1)].id)}>Next board</button></div>
    {selected?<div className="rounded-lg border bg-slate-50 p-3 space-y-3"><p className="text-sm font-medium">{selected.label}</p><p className="text-xs text-slate-600">{selected.w.toFixed(2)} × {selected.d.toFixed(2)} × {selected.h.toFixed(2)} in · centre {selected.x.toFixed(1)}, {selected.z.toFixed(1)} in · elevation {selected.y.toFixed(1)} in{selected.polygon?' · cut profile retained':''}</p>{scope!=='all'&&scope!==selected.group&&<p className="text-xs">The board selected in 3D is outside the current list filter.</p>}<div className="flex flex-wrap items-end gap-3"><label className="text-sm">Preview colour<input aria-label="Board colour picker" className="block h-10 w-16 cursor-pointer" type="color" value={/^#[a-fA-F0-9]{6}$/.test(color)?color:'#725846'} onChange={e=>setColor(e.target.value)}/></label><label className="text-sm">Hex colour<input aria-label="Board hex colour" className="block w-32 rounded border p-2" value={color} maxLength={7} onChange={e=>setColor(e.target.value)} /></label><span aria-label="Selected colour preview" className="h-10 w-12 rounded border" style={{backgroundColor:/^#[a-fA-F0-9]{6}$/.test(color)?color:'transparent'}}/></div><p className="text-xs text-slate-600">{override?`Applied override: ${override.color}`:'Using the selected product / group finish.'}</p><div className="flex flex-wrap gap-2"><button type="button" className="rounded bg-[#264c3b] px-3 py-2 text-sm text-white" onClick={apply}>Apply to this board</button><button type="button" className="rounded border px-3 py-2 text-sm disabled:opacity-40" disabled={!override} onClick={()=>change(status.overrides.filter(o=>o.id!==selected.id))}>Reset this board</button></div></div>:<p className="rounded border border-dashed p-4 text-sm">Select a visible finish board to highlight and recolour it. Turn on its view layer if it is hidden.</p>}
    {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
    <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-600">{status.matched.length} custom colours applied · {status.boards.length} installed pieces</p><button type="button" className="rounded border px-3 py-2 text-sm disabled:opacity-40" disabled={!history.length} onClick={()=>{const previous=history.at(-1)!;setHistory(h=>h.slice(0,-1));onChange({boardFinishes:previous});setError('');}}>Undo board colour</button></div>
    {!!status.unmatched.length&&<div className="rounded border border-amber-300 bg-amber-50 p-3 text-sm"><p>{status.unmatched.length} saved board colours no longer match an installed piece after a geometry change. They are retained but not applied to another board.</p><button type="button" className="mt-2 rounded border px-3 py-2" onClick={()=>change(status.matched)}>Remove unmatched colours</button></div>}
    <p className="text-xs text-slate-600">Custom RGB is a design preview, not a new supplier SKU or a coating instruction. Confirm manufacturer colour availability, material compatibility and the final order schedule. Colour changes do not change board geometry or authorize field painting of composite boards.</p>
  </section>;
}
