import {type DeckData, MATERIAL_TIERS, CREW_DAY_RATES, PERMIT_FEES, DEFAULT_ENGINEERING_FEE, RAILING_COSTS, STAIR_TREAD_COSTS, WASTE_FACTORS} from './types';
export const DEFAULT_DECK: DeckData = {
    houseVisible: true,
    houseWallHeightIn: 120,
    houseDoorOffset: 50,
    houseDoorWidthIn: 72,
    sceneLighting: 'Daylight',
    level2Position: 'Front',
    level2Offset: 50,
    stairTurn: 'Right',
    landingDepthIn: 48,
    deckType: 'Attached',
    municipality: 'Barrie',
    materialMarkup: 35,
    siteType: 'Standard',
    soilCondition: 'Unknown',
    buildSeason: 'Spring-Summer',
    intendedLoad: 'Standard',
    foundation: 'Concrete Piers',
    width: 16,
    length: 12,
    height: 36,
    cutoutWidth: 8,
    cutoutLength: 6,
    width2: 12,
    length2: 10,
    height2: 12,
    cutoutWidth2: 6,
    cutoutLength2: 5,
    shape: 'Rectangle',
    levels: 1,
    pattern: 'Straight',
    deckingMaterial: 'tt_prime_plus',
    deckingColor: 'Coconut Husk',
    framingSize: '2x10',
    boardWidth: 5.5,
    joistSpacing: 16,
    fasteningSystem: 'Face',
    pictureFrameRows: 0,
    hasInlay: false,
    inlayLf: 0,
    railingType: 'Aluminum',
    railingLf: 0,
    stairFlights: 1,
    stairWidth: 48,
    stairType: 'Straight',
    stairPosition: 'Front',
    stairOffset: 50,
    lightingSystem: {
      selectedItems: [],
      wireDistance: 20
    },
    benchLf: 0,
    privacySqft: 0,
    hasDrainage: false,
    hasDemo: false,
    pergolaSqft: 0,
    customerName: '',
    projectAddress: '',
    scopeOfWork: 'Professional installation of a custom outdoor deck system including framing, decking, and finishing as per selected specifications. All work to be completed to local building codes and industry best practices.'};
export const DECK_SETTINGS={materials:MATERIAL_TIERS,crewRates:CREW_DAY_RATES,permitFees:PERMIT_FEES,engineeringFee:DEFAULT_ENGINEERING_FEE,railingCosts:RAILING_COSTS,stairTreadCosts:STAIR_TREAD_COSTS,wasteFactors:WASTE_FACTORS};
