import type {SiteGradingTransition,TransitionBoundary,SiteBoundaryPoint} from './siteModel';
import type {CircularArc} from './circularArcs';
import {arcGeometry} from './circularArcs';
import {transitionBoundaryFractions,transitionBoundaryLength,transitionBoundaryPoint,transitionStripFootprint,transitionArea} from './gradingTransitionGeometry';
type PlanPoint=SiteBoundaryPoint;
function exactPathCheck(points:PlanPoint[],arcs:CircularArc[]|undefined,closed:boolean){const count=points.length-(closed?0:1);
  const tau=Math.PI*2,eps=1e-7;
  const primitives=Array.from({length:count},(_,i)=>{const a=points[i],b=points[(i+1)%points.length],arc=(arcs??[]).find(c=>c.edge===i);return {a,b,arc,g:arc?arcGeometry(a,b,arc.bulgeIn):undefined};});
  type Segment=typeof primitives[number];
  const on=(p:PlanPoint,s:Segment)=>{if(s.g){if(Math.abs(Math.hypot(p.x-s.g.center.x,p.y-s.g.center.y)-s.g.radius)>eps)return false;const start=Math.atan2(s.a.y-s.g.center.y,s.a.x-s.g.center.x),angle=Math.atan2(p.y-s.g.center.y,p.x-s.g.center.x),delta=((Math.sign(s.arc!.bulgeIn)*(start-angle))%tau+tau)%tau;return delta<=s.g.sweep+eps||tau-delta<eps;}const dx=s.b.x-s.a.x,dy=s.b.y-s.a.y,cross=(p.x-s.a.x)*dy-(p.y-s.a.y)*dx;return Math.abs(cross)<eps*Math.max(1,Math.hypot(dx,dy))&&p.x>=Math.min(s.a.x,s.b.x)-eps&&p.x<=Math.max(s.a.x,s.b.x)+eps&&p.y>=Math.min(s.a.y,s.b.y)-eps&&p.y<=Math.max(s.a.y,s.b.y)+eps;};
  const contacts=(s:Segment,t:Segment):PlanPoint[]=>{
   if(!s.g&&!t.g){const dx=s.b.x-s.a.x,dy=s.b.y-s.a.y,ex=t.b.x-t.a.x,ey=t.b.y-t.a.y,den=dx*ey-dy*ex;if(Math.abs(den)<eps)return [s.a,s.b,t.a,t.b].filter(p=>on(p,s)&&on(p,t));const u=((t.a.x-s.a.x)*ey-(t.a.y-s.a.y)*ex)/den,p={x:s.a.x+u*dx,y:s.a.y+u*dy};return on(p,s)&&on(p,t)?[p]:[];}
   if(s.g&&t.g){const a=s.g,b=t.g,d=Math.hypot(b.center.x-a.center.x,b.center.y-a.center.y);if(d<eps)return Math.abs(a.radius-b.radius)<eps?[s.a,s.b,t.a,t.b].filter(p=>on(p,s)&&on(p,t)):[];if(d>a.radius+b.radius+eps||d<Math.abs(a.radius-b.radius)-eps)return [];const u=(a.radius*a.radius-b.radius*b.radius+d*d)/(2*d),h=Math.sqrt(Math.max(0,a.radius*a.radius-u*u)),dx=(b.center.x-a.center.x)/d,dy=(b.center.y-a.center.y)/d;return [-1,1].map(sign=>({x:a.center.x+u*dx-sign*h*dy,y:a.center.y+u*dy+sign*h*dx})).filter(p=>on(p,s)&&on(p,t));}
   const circle=s.g?s:t,line=s.g?t:s,g=circle.g!,dx=line.b.x-line.a.x,dy=line.b.y-line.a.y,px=line.a.x-g.center.x,py=line.a.y-g.center.y,A=dx*dx+dy*dy,B=2*(px*dx+py*dy),C=px*px+py*py-g.radius*g.radius,rawDisc=B*B-4*A*C,roundoff=Number.EPSILON*128*Math.max(1,B*B,4*A*(px*px+py*py+g.radius*g.radius)),disc=Math.abs(rawDisc)<=roundoff?0:rawDisc;if(disc<-eps)return [];return [-1,1].map(sign=>{const u=(-B+sign*Math.sqrt(Math.max(0,disc)))/(2*A);return {x:line.a.x+u*dx,y:line.a.y+u*dy};}).filter(p=>on(p,circle)&&on(p,line));
  };
  for(let i=0;i<count;i++)for(let j=i+1;j<count;j++){
   const adjacent=j===i+1||closed&&i===0&&j===count-1,shared=j===i+1?primitives[i].b:primitives[i].a;
   if(contacts(primitives[i],primitives[j]).some(p=>!adjacent||Math.hypot(p.x-shared.x,p.y-shared.y)>eps))throw Error('Circular segments cannot cross or touch another boundary.');
  }
}

function fail(message:string):never{throw Error(message);}
function plain(value:unknown,keys:string[],required:string[],label:string){if(!value||typeof value!=='object'||Array.isArray(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value))||Object.getOwnPropertySymbols(value).length)fail(`${label} must use plain data.`);const d=Object.getOwnPropertyDescriptors(value);if(Object.keys(d).some(k=>!keys.includes(k)||!d[k].enumerable||!('value'in d[k]))||required.some(k=>!Object.hasOwn(d,k)))fail(`${label} has invalid fields.`);return value as Record<string,unknown>;}
function list(value:unknown,min:number,max:number,label:string):unknown[]{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length<min||value.length>max||Object.getOwnPropertySymbols(value).length)fail(`${label} requires ${min}–${max} entries.`);const d=Object.getOwnPropertyDescriptors(value);if(Object.keys(d).some(k=>k!=='length'&&(!/^(0|[1-9]\d*)$/.test(k)||Number(k)>=value.length||!d[k].enumerable||!('value'in d[k])))||Array.from({length:value.length},(_,i)=>i).some(i=>!Object.hasOwn(d,String(i))))fail(`${label} must be a dense plain array.`);return value;}
function number(v:unknown,max:number,label:string,min=-max){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)fail(`${label} is out of range.`);return v;}
function text(v:unknown,label:string){if(typeof v!=='string'||!v.trim()||v.length>120||/[\u0000-\u001f]/.test(v))fail(`${label} is invalid.`);return v;}
function boundary(v:unknown,label:string):TransitionBoundary{const r=plain(v,['points','curves','elevationSource','levels'],['points','elevationSource'],label),points=list(r.points,2,64,label+' points').map(v=>{const p=plain(v,['x','y'],['x','y'],label+' point');return {x:number(p.x,1200000,'Boundary X'),y:number(p.y,1200000,'Boundary Z')};});for(let i=0;i+1<points.length;i++)if(Math.hypot(points[i+1].x-points[i].x,points[i+1].y-points[i].y)<1)fail('Transition path edges must be at least one inch.');
 if(!['existing','proposed','specified'].includes(r.elevationSource as string))fail('Transition elevation source is invalid.');const out:TransitionBoundary={points,elevationSource:r.elevationSource as TransitionBoundary['elevationSource']};
 if(r.curves!==undefined){const edges=new Set<number>();out.curves=list(r.curves,0,63,'Transition arcs').map(v=>{const c=plain(v,['edge','bulgeIn'],['edge','bulgeIn'],'Transition arc'),edge=number(c.edge,points.length-2,'Arc edge',0),bulgeIn=number(c.bulgeIn,1200000,'Arc bulge');if(!Number.isInteger(edge)||edges.has(edge)||Math.abs(bulgeIn)<1e-8)fail('Transition arc is invalid.');edges.add(edge);const g=arcGeometry(points[edge],points[edge+1],bulgeIn);if(g.radius>1200000||g.lengthIn>2400000)fail('Transition arc exceeds the site coordinate limits.');const start=Math.atan2(points[edge].y-g.center.y,points[edge].x-g.center.x),tau=2*Math.PI;for(const angle of [0,Math.PI/2,Math.PI,3*Math.PI/2]){const delta=((Math.sign(bulgeIn)*(start-angle))%tau+tau)%tau;if(delta<=g.sweep+1e-8){number(g.center.x+g.radius*Math.cos(angle),1200000,'Arc extreme X');number(g.center.y+g.radius*Math.sin(angle),1200000,'Arc extreme Z');}}return {edge,bulgeIn};});}
 exactPathCheck(points,out.curves,false);for(const f of transitionBoundaryFractions(out)){const p=transitionBoundaryPoint(out,f);number(p.x,1200000,'Curved boundary X');number(p.y,1200000,'Curved boundary Z');}const length=transitionBoundaryLength(out);if(out.elevationSource==='specified'){out.levels=list(r.levels,2,128,'Transition elevation stations').map(v=>{const p=plain(v,['stationIn','elevationIn'],['stationIn','elevationIn'],'Transition station');return {stationIn:number(p.stationIn,length+1e-5,'Elevation station',0),elevationIn:number(p.elevationIn,120000,'Boundary elevation')};});if(Math.abs(out.levels[0].stationIn)>1e-6||Math.abs(out.levels.at(-1)!.stationIn-length)>1e-5||out.levels.some((l,i)=>i>0&&l.stationIn<=out.levels![i-1].stationIn+1e-6))fail('Specified levels must increase from zero to the full analytic boundary length.');out.levels[0].stationIn=0;out.levels.at(-1)!.stationIn=length;}else if(r.levels!==undefined)fail('Measured elevation sources cannot carry specified levels.');return out;
}
export function validateGradingTransitions(value:unknown):SiteGradingTransition[]{const ids=new Set<string>();return list(value,0,32,'Grading transitions').map(v=>{const r=plain(v,['id','name','enabled','a','b'],['id','name','enabled','a','b'],'Grading transition'),id=text(r.id,'Transition ID');if(ids.has(id))fail('Duplicate grading transition ID.');ids.add(id);if(typeof r.enabled!=='boolean')fail('Transition enabled must be boolean.');const t:SiteGradingTransition={id,name:text(r.name,'Transition name'),enabled:r.enabled,a:boundary(r.a,'Boundary A'),b:boundary(r.b,'Boundary B')};
 // A closed exact envelope rejects touching/crossing paths and cap crossings.
 const ap=t.a.points,bp=t.b.points,points=[...ap,...[...bp].reverse()],arcs=[...(t.a.curves??[]),...(t.b.curves??[]).map(c=>({edge:ap.length+bp.length-2-c.edge,bulgeIn:-c.bulgeIn}))];exactPathCheck(points,arcs,true);
 const fractions=[...new Set([...transitionBoundaryFractions(t.a),...transitionBoundaryFractions(t.b)])].sort((a,b)=>a-b);if(fractions.length>2048)fail('Transition curved path exceeds the 2048-station geometry budget.');let orientation=0;const cross=(a:PlanPoint,b:PlanPoint,c:PlanPoint)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);for(let i=0;i+1<fractions.length;i++){const a=transitionBoundaryPoint(t.a,fractions[i]),b=transitionBoundaryPoint(t.a,fractions[i+1]),c=transitionBoundaryPoint(t.b,fractions[i+1]),d=transitionBoundaryPoint(t.b,fractions[i]);for(const q of [cross(a,b,c),cross(a,c,d)]){if(Math.abs(q)<1e-7)fail('Transition strips cannot collapse or fold over; separate paired endpoints.');if(orientation&&Math.sign(q)!==orientation)fail('Paired boundary direction folds the transition strip.');orientation=Math.sign(q);}}
 if(transitionArea(transitionStripFootprint(t))<.01)fail('Transition strip has no usable area.');return t;
 });}
