import type {SiteBoundaryPoint as Point,TransitionBoundary,SiteGradingTransition} from './siteModel';
import type {SiteSurface,SiteVertex,SitePlane} from './siteSurface';
import {arcGeometry} from './circularArcs';
import {localPolygonClip} from './lib/localPolygonClip';
export interface GradingTransitionFace {vertices:[SiteVertex,SiteVertex,SiteVertex];plane:SitePlane}
export interface GradingTransitionModel {id:string;name:string;status:'ready'|'pending';footprint:Point[][];triangles:GradingTransitionFace[];warnings:string[];areaSqft:number;maxSlopePct:number|null;missingAreaSqft:number;minElevationIn:number|null;maxElevationIn:number|null}
const cross=(a:Point,b:Point,c:Point)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
const area=(p:Point[])=>p.reduce((n,a,i)=>{const b=p[(i+1)%p.length];return n+a.x*b.y-b.x*a.y;},0)/2;
export const transitionClip=(a:Point[][],b:Point[][]=[],op:'union'|'difference'|'intersection'='union')=>localPolygonClip(a,b,op,100000);
export const transitionArea=(p:Point[][])=>Math.abs(p.reduce((n,q)=>n+area(q),0))/144;
function primitives(boundary:TransitionBoundary){let stationIn=0;return boundary.points.slice(0,-1).map((a,i)=>{const b=boundary.points[i+1],arc=boundary.curves?.find(c=>c.edge===i),g=arc?arcGeometry(a,b,arc.bulgeIn):undefined,lengthIn=g?.lengthIn??Math.hypot(b.x-a.x,b.y-a.y),out={a,b,arc,g,startIn:stationIn,lengthIn};stationIn+=lengthIn;return out;});}
export function transitionBoundaryLength(boundary:TransitionBoundary){return primitives(boundary).reduce((n,p)=>n+p.lengthIn,0);}
export function transitionBoundaryPoint(boundary:TransitionBoundary,fraction:number):Point{const segments=primitives(boundary),distance=Math.max(0,Math.min(1,fraction))*segments.reduce((n,p)=>n+p.lengthIn,0),segment=segments.find(p=>distance<=p.startIn+p.lengthIn+1e-8)??segments.at(-1)!,t=Math.max(0,Math.min(1,(distance-segment.startIn)/segment.lengthIn));if(t<=1e-12)return {...segment.a};if(t>=1-1e-12)return {...segment.b};if(!segment.g)return {x:segment.a.x+(segment.b.x-segment.a.x)*t,y:segment.a.y+(segment.b.y-segment.a.y)*t};const angle=Math.atan2(segment.a.y-segment.g.center.y,segment.a.x-segment.g.center.x)-Math.sign(segment.arc!.bulgeIn)*segment.g.sweep*t;return {x:segment.g.center.x+segment.g.radius*Math.cos(angle),y:segment.g.center.y+segment.g.radius*Math.sin(angle)};}
export function transitionBoundaryFractions(boundary:TransitionBoundary){const segments=primitives(boundary),length=segments.reduce((n,p)=>n+p.lengthIn,0),out=[0,1,...(boundary.levels??[]).map(l=>l.stationIn/length)];for(const p of segments){out.push(p.startIn/length,(p.startIn+p.lengthIn)/length);if(p.g){const count=Math.min(256,Math.max(2,Math.ceil(p.g.sweep/Math.min(Math.PI/72,2*Math.acos(Math.max(-1,1-.005/p.g.radius))))));for(let i=1;i<count;i++)out.push((p.startIn+p.lengthIn*i/count)/length);}}return [...new Set(out.map(v=>Math.round(Math.max(0,Math.min(1,v))*1e12)/1e12))];}
/** Exact boundary/triangle intersections supplement adaptive circular facets. */
function terrainFractions(boundary:TransitionBoundary,surface:SiteSurface){if(boundary.elevationSource==='specified')return [];const triangles=boundary.elevationSource==='existing'?surface.existingTriangles:surface.proposedTriangles,edges=new Map<string,[Point,Point]>();for(const t of triangles)for(let i=0;i<3;i++){const a={x:t.vertices[i].xIn,y:t.vertices[i].zIn},b={x:t.vertices[(i+1)%3].xIn,y:t.vertices[(i+1)%3].zIn},u=`${Math.round(a.x*1e5)}/${Math.round(a.y*1e5)}`,v=`${Math.round(b.x*1e5)}/${Math.round(b.y*1e5)}`;edges.set(u<v?`${u}:${v}`:`${v}:${u}`,[a,b]);}const segments=primitives(boundary),length=transitionBoundaryLength(boundary),out:number[]=[];for(const p of segments)for(const [a,b] of edges.values()){
 const ex=b.x-a.x,ey=b.y-a.y;
 if(!p.g){const dx=p.b.x-p.a.x,dy=p.b.y-p.a.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-10)continue;const t=((a.x-p.a.x)*ey-(a.y-p.a.y)*ex)/den,u=((a.x-p.a.x)*dy-(a.y-p.a.y)*dx)/den;if(t>1e-10&&t<1-1e-10&&u>=-1e-10&&u<=1+1e-10)out.push((p.startIn+t*p.lengthIn)/length);}
 else{const g=p.g,px=a.x-g.center.x,py=a.y-g.center.y,A=ex*ex+ey*ey,B=2*(px*ex+py*ey),C=px*px+py*py-g.radius*g.radius,raw=B*B-4*A*C,roundoff=Number.EPSILON*128*Math.max(1,B*B,4*A*(px*px+py*py+g.radius*g.radius)),disc=Math.abs(raw)<=roundoff?0:raw;if(A<1e-12||disc<0)continue;for(const sign of [-1,1]){const u=(-B+sign*Math.sqrt(disc))/(2*A);if(u<-1e-10||u>1+1e-10)continue;const x=a.x+ex*u,y=a.y+ey*u,start=Math.atan2(p.a.y-g.center.y,p.a.x-g.center.x),angle=Math.atan2(y-g.center.y,x-g.center.x),delta=((Math.sign(p.arc!.bulgeIn)*(start-angle))%(2*Math.PI)+2*Math.PI)%(2*Math.PI);if(delta<=g.sweep+1e-8)out.push((p.startIn+g.radius*delta)/length);}}
 }return out;}
function elevation(boundary:TransitionBoundary,fraction:number,point:Point,surface:SiteSurface){if(boundary.elevationSource!=='specified')return surface.sample(point.x,point.y,boundary.elevationSource);const station=fraction*transitionBoundaryLength(boundary),levels=boundary.levels!;let i=levels.findIndex((l,j)=>j>0&&station<=l.stationIn+1e-8);if(i<0)i=levels.length-1;const a=levels[i-1],b=levels[i];return a.elevationIn+(b.elevationIn-a.elevationIn)*(station-a.stationIn)/(b.stationIn-a.stationIn);}
function face(a:Point,b:Point,c:Point,ha:number,hb:number,hc:number):GradingTransitionFace|undefined{let den=cross(a,b,c);if(Math.abs(den)<1e-8)return undefined;if(den<0)return face(a,c,b,ha,hc,hb);const x=((hb-ha)*(c.y-a.y)-(hc-ha)*(b.y-a.y))/den,z=((b.x-a.x)*(hc-ha)-(c.x-a.x)*(hb-ha))/den,plane={x,z,constant:ha-x*a.x-z*a.y};return {vertices:[{xIn:a.x,zIn:a.y,elevationIn:ha},{xIn:b.x,zIn:b.y,elevationIn:hb},{xIn:c.x,zIn:c.y,elevationIn:hc}],plane};}
function footprintAt(t:SiteGradingTransition,fractions:number[]){return transitionClip(fractions.slice(0,-1).flatMap((u,i)=>{const v=fractions[i+1],polygon=[transitionBoundaryPoint(t.a,u),transitionBoundaryPoint(t.a,v),transitionBoundaryPoint(t.b,v),transitionBoundaryPoint(t.b,u)];return Math.abs(area(polygon))>1e-8?[area(polygon)>0?polygon:polygon.reverse()]:[]}));}
export function transitionStripFootprint(t:SiteGradingTransition){return footprintAt(t,[...new Set([...transitionBoundaryFractions(t.a),...transitionBoundaryFractions(t.b)].map(v=>Math.round(v*1e12)/1e12))].sort((a,b)=>a-b));}
/** Source heights are captured from the pre-transition proposed surface. */
export function buildGradingTransitions(surface:SiteSurface,transitions:SiteGradingTransition[]):GradingTransitionModel[]{const models=transitions.filter(t=>t.enabled).map(t=>{
 const fractions=[...new Set([...transitionBoundaryFractions(t.a),...transitionBoundaryFractions(t.b),...terrainFractions(t.a,surface),...terrainFractions(t.b,surface)].map(v=>Math.round(v*1e12)/1e12))].sort((a,b)=>a-b),triangles:GradingTransitionFace[]=[],warnings:string[]=[],footprint=footprintAt(t,fractions),areaSqft=transitionArea(footprint),missingAreaSqft=transitionArea(transitionClip(footprint,surface.coverage,'difference'));let missingBoundary=false;
 if(fractions.length>4096)return {id:t.id,name:t.name,status:'pending' as const,footprint,triangles:[],warnings:['Source terrain intersections exceed the 4096-station geometry budget. Split the transition into simpler strips; no surface is applied.'],areaSqft,missingAreaSqft,maxSlopePct:null,minElevationIn:null,maxElevationIn:null};
 for(let i=0;i+1<fractions.length;i++){const u=fractions[i],v=fractions[i+1],a=transitionBoundaryPoint(t.a,u),b=transitionBoundaryPoint(t.a,v),c=transitionBoundaryPoint(t.b,v),d=transitionBoundaryPoint(t.b,u),ha=elevation(t.a,u,a,surface),hb=elevation(t.a,v,b,surface),hc=elevation(t.b,v,c,surface),hd=elevation(t.b,u,d,surface),mid=(u+v)/2,pa=transitionBoundaryPoint(t.a,mid),pb=transitionBoundaryPoint(t.b,mid);if([ha,hb,hc,hd,elevation(t.a,mid,pa,surface),elevation(t.b,mid,pb,surface)].some(h=>h===undefined||!Number.isFinite(h))){missingBoundary=true;continue;}for(const f of [face(a,b,c,ha!,hb!,hc!),face(a,c,d,ha!,hc!,hd!)])if(f)triangles.push(f);}
 // An abrupt source-grade jump cannot be smoothed into an invented boundary.
 for(const boundary of [t.a,t.b])if(boundary.elevationSource!=='specified')for(let i=1;i+1<fractions.length;i++){const u=fractions[i],du=Math.min((u-fractions[i-1])/4,(fractions[i+1]-u)/4,.01/transitionBoundaryLength(boundary)),height=(f:number)=>{const p=transitionBoundaryPoint(boundary,f);return elevation(boundary,f,p,surface);},left=height(u-du),farLeft=height(u-2*du),right=height(u+du),farRight=height(u+2*du);if([left,farLeft,right,farRight].every(h=>h!==undefined&&Number.isFinite(h))&&Math.abs(2*left!-farLeft!-(2*right!-farRight!))>.01){warnings.push('A measured source boundary crosses a proposed elevation discontinuity. Enter a continuous explicit boundary or resolve the grading step; no transition surface is applied.');break;}}
 if(missingBoundary||missingAreaSqft>.00001)warnings.push(`Boundary or strip coverage is incomplete (${missingAreaSqft.toFixed(2)} sq ft uncovered). Extend the measured survey; no transition surface is applied.`);
 const pending=warnings.length>0,values=triangles.flatMap(t=>t.vertices.map(v=>v.elevationIn)),slopes=triangles.map(t=>Math.hypot(t.plane.x,t.plane.z)*100);return {id:t.id,name:t.name,status:pending?'pending' as const:'ready' as const,footprint,triangles:pending?[]:triangles,warnings,areaSqft,missingAreaSqft,maxSlopePct:pending||!slopes.length?null:Math.max(...slopes),minElevationIn:pending||!values.length?null:Math.min(...values),maxElevationIn:pending||!values.length?null:Math.max(...values)};
 });
 for(let i=0;i<models.length;i++)for(let j=i+1;j<models.length;j++)if(transitionArea(transitionClip(models[i].footprint,models[j].footprint,'intersection'))>.00001){for(const m of [models[i],models[j]]){m.status='pending';m.triangles=[];m.minElevationIn=null;m.maxElevationIn=null;m.maxSlopePct=null;m.warnings.push(`Transition strip overlaps ${m===models[i]?models[j].name:models[i].name}. Separate or merge the strips; neither surface is applied.`);}}
 return models;
}
