import {LANDSCAPE_SURFACES,landscapeSurface} from './landscapeSurfaces';
import type {LandscapeAssetId,LandscapeKind,LandscapeObject,LandscapeSpeciesRecord} from './landscapeTypes';
export interface LandscapeAsset {id:LandscapeAssetId;name:string;kind:LandscapeKind;category:string;heightIn:number;widthIn:number;depthIn:number;sourceURL?:string;modelURL?:string;lowModelURL?:string;farModelURL?:string;triangleCounts?:[number,number,number];visualNote:string}
const model=(id:string)=>'/deckcraft/landscape/'+id;
export const LANDSCAPE_ASSETS:LandscapeAsset[]=[
 {id:'deciduous-tree',name:'Deciduous tree',kind:'plant',category:'Trees',heightIn:180,widthIn:108,depthIn:108,sourceURL:'https://polyhaven.com/a/tree_small_02',modelURL:model('deciduous-tree-lod0.glb'),lowModelURL:model('deciduous-tree-lod1.glb'),visualNote:'Generic broadleaf visual proxy. Source mesh is Tree Small 02; a species record is selected separately.'},
 {id:'conifer-tree',name:'Conifer tree',kind:'plant',category:'Trees',heightIn:144,widthIn:72,depthIn:72,sourceURL:'https://polyhaven.com/a/fir_tree_01',modelURL:model('conifer-tree-lod0.glb'),lowModelURL:model('conifer-tree-lod1.glb'),visualNote:'Generic evergreen visual proxy from Fir Tree 01. It does not identify a planting species or nursery SKU.'},
 {id:'rounded-shrub',name:'Natural shrub',kind:'plant',category:'Shrubs and hedges',heightIn:36,widthIn:40,depthIn:40,sourceURL:'https://polyhaven.com/a/tree_small_02',modelURL:model('rounded-shrub-lod0.glb'),lowModelURL:model('rounded-shrub-lod1.glb'),visualNote:'Summer broadleaf mound from Tree Small 02 leaf cards. A species record names the planting; this mesh is not a nursery photograph.'},
 {id:'hedge-shrub',name:'Hedge shrub',kind:'plant',category:'Shrubs and hedges',heightIn:72,widthIn:36,depthIn:30,sourceURL:'https://polyhaven.com/a/fir_tree_01',modelURL:model('hedge-shrub-lod0.glb'),lowModelURL:model('hedge-shrub-lod1.glb'),visualNote:'Dense columnar hedge from Fir Tree 01 needle cards, with its own model at every level of detail. Each placement is one shrub. Not a nursery SKU.'},
 {id:'evergreen-shrub',name:'Evergreen shrub',kind:'plant',category:'Shrubs and hedges',heightIn:24,widthIn:28,depthIn:28,sourceURL:'https://polyhaven.com/a/fir_tree_01',modelURL:model('evergreen-shrub-lod0.glb'),lowModelURL:model('evergreen-shrub-lod1.glb'),visualNote:'Rounded summer evergreen from Fir Tree 01 needle cards. Species and nursery stock are a separate record.'},
 {id:'pine-tree',name:'Pine tree',kind:'plant',category:'Trees',heightIn:168,widthIn:96,depthIn:96,sourceURL:'https://polyhaven.com/a/fir_tree_01',modelURL:model('pine-tree-lod0.glb'),lowModelURL:model('pine-tree-lod1.glb'),visualNote:'Open summer pine from Fir Tree 01 needle cards and a trunk. Not a measured eastern white pine specimen.'},
 {id:'hosta-clump',name:'Hosta clump',kind:'plant',category:'Perennials',heightIn:16,widthIn:28,depthIn:28,sourceURL:'https://polyhaven.com/a/tree_small_02',modelURL:model('hosta-clump-lod0.glb'),lowModelURL:model('hosta-clump-lod1.glb'),visualNote:'Low summer leaf mound from Tree Small 02 leaf cards. Not a named hosta photograph.'},
 {id:'reed-grass',name:'Feather reed grass',kind:'plant',category:'Grasses',heightIn:48,widthIn:24,depthIn:24,sourceURL:'https://polyhaven.com/a/grass_medium_01',modelURL:model('reed-grass-lod0.glb'),lowModelURL:model('reed-grass-lod1.glb'),visualNote:'Upright summer grass from Grass Medium 01. Cultivar and nursery size are a separate record.'},
 {id:'fern-clump',name:'Fern clump',kind:'plant',category:'Perennials',heightIn:36,widthIn:28,depthIn:28,sourceURL:'https://polyhaven.com/a/fern_02',modelURL:model('fern-clump-lod0.glb'),lowModelURL:model('fern-clump-lod1.glb'),visualNote:'Summer fern from Poly Haven Fern 02. Solid fronds, not a nursery SKU.'},
 {id:'perennial-bloom',name:'Flowering perennial',kind:'plant',category:'Perennials',heightIn:24,widthIn:18,depthIn:18,sourceURL:'https://polyhaven.com/a/periwinkle_plant',modelURL:model('perennial-bloom-lod0.glb'),lowModelURL:model('perennial-bloom-lod1.glb'),visualNote:'Summer flowering perennial from Poly Haven periwinkle, drawn with alpha-tested cards. Tint and the species record distinguish plantings.'},
 {id:'perennial-gold',name:'Gold flowering perennial',kind:'plant',category:'Perennials',heightIn:28,widthIn:18,depthIn:18,sourceURL:'https://polyhaven.com/a/celandine_01',modelURL:model('perennial-gold-lod0.glb'),lowModelURL:model('perennial-gold-lod1.glb'),visualNote:'Summer gold-flowering perennial from Poly Haven celandine, drawn with alpha-tested cards. Not a nursery SKU.'},
 {id:'grass-clump',name:'Ornamental grass clump',kind:'plant',category:'Grasses',heightIn:30,widthIn:24,depthIn:24,sourceURL:'https://polyhaven.com/a/grass_medium_01',modelURL:model('grass-clump-lod0.glb'),lowModelURL:model('grass-clump-lod1.glb'),visualNote:'Generic grass visual proxy; planting species and mature size are separate records.'},
 {id:'natural-boulder',name:'Natural boulder',kind:'boulder',category:'Stone',heightIn:24,widthIn:42,depthIn:30,sourceURL:'https://polyhaven.com/a/namaqualand_boulder_03',modelURL:model('natural-boulder-lod0.glb'),lowModelURL:model('natural-boulder-lod1.glb'),visualNote:'CC0 rock scan scaled to the chosen envelope. Stone type, weight, supply and placement require a quote.'},
 {id:'outdoor-table',name:'Outdoor folding table',kind:'furniture',category:'Furniture',heightIn:30,widthIn:36,depthIn:36,sourceURL:'https://polyhaven.com/a/outdoor_table_chair_set_01',modelURL:model('outdoor-table-lod0.glb'),lowModelURL:model('outdoor-table-lod1.glb'),visualNote:'Generic outdoor furniture, not a priced manufacturer product.'},
 {id:'outdoor-chair',name:'Outdoor folding chair',kind:'furniture',category:'Furniture',heightIn:34,widthIn:20,depthIn:22,sourceURL:'https://polyhaven.com/a/outdoor_table_chair_set_01',modelURL:model('outdoor-chair-lod0.glb'),lowModelURL:model('outdoor-chair-lod1.glb'),visualNote:'Generic outdoor furniture, not a priced manufacturer product.'},
 {id:'mulch-bed',name:'Planting bed',kind:'bed',category:'Beds',heightIn:1,widthIn:120,depthIn:72,visualNote:'Measured polygon area, mulch volume and optional edging. Plant placements are counted separately.'},
 {id:'lounge-chair',name:'Cushioned chaise lounge',kind:'furniture',category:'Furniture',heightIn:32,widthIn:30,depthIn:80,modelURL:model('lounge-chair-lod0.glb'),lowModelURL:model('lounge-chair-lod1.glb'),visualNote:'Original project-owned teak-frame and fabric-cushion visual proxy. Actual product, dimensions and price require selection.'},
 {id:'outdoor-sofa',name:'Outdoor three-seat sofa',kind:'furniture',category:'Furniture',heightIn:32,widthIn:84,depthIn:36,modelURL:model('outdoor-sofa-lod0.glb'),lowModelURL:model('outdoor-sofa-lod1.glb'),visualNote:'Original project-owned upholstered outdoor seating proxy. Not a built-in bench or verified manufacturer SKU.'},
 {id:'outdoor-coffee-table',name:'Outdoor low coffee table',kind:'furniture',category:'Furniture',heightIn:16,widthIn:48,depthIn:26,modelURL:model('outdoor-coffee-table-lod0.glb'),lowModelURL:model('outdoor-coffee-table-lod1.glb'),visualNote:'Original project-owned low slatted-table visual proxy. Supply and installation remain unpriced.'},
];
for(const s of LANDSCAPE_SURFACES.filter(s=>s.id!=='mulch-bed'))LANDSCAPE_ASSETS.push({id:s.id,name:s.name,kind:'bed',category:s.type==='turf'?'Turf and greens':'Decorative ground covers',heightIn:1,widthIn:s.type==='turf'?180:120,depthIn:s.type==='turf'?240:72,visualNote:'Editable planning finish. Original visual proxy; confirm actual product, depth, base, drainage and installation. No supplier price is assumed.'});
const triangleCounts:Partial<Record<LandscapeAssetId,[number,number,number]>>={'deciduous-tree':[65256,31663,8499],'conifer-tree':[14364,5799,2012],'rounded-shrub':[2080,880,360],'hedge-shrub':[3120,1200,480],'evergreen-shrub':[2560,960,400],'pine-tree':[2832,1072,400],'hosta-clump':[192,88,40],'reed-grass':[880,320,128],'fern-clump':[2384,2239,950],'perennial-bloom':[11252,2146,393],'perennial-gold':[4301,771,277],'grass-clump':[2287,2287,2287],'natural-boulder':[10370,3240,810],'outdoor-table':[2324,1592,1472],'outdoor-chair':[3752,1876,1592],'lounge-chair':[1396,948,724],'outdoor-sofa':[3876,2532,1860],'outdoor-coffee-table':[216,216,216]};
for(const a of LANDSCAPE_ASSETS)if(a.lowModelURL){a.farModelURL=a.lowModelURL.replace('-lod1.glb','-lod2.glb');a.triangleCounts=triangleCounts[a.id];}
/** These records describe mature planning envelopes, not the identity of the
 * visual mesh or an Ontario nursery quotation. Site/cultivar suitability still
 * needs selection; no planting spacing is inferred from mature spread. */
export const LANDSCAPE_SPECIES:LandscapeSpeciesRecord[]=[
 {id:'acer-saccharum',commonName:'Sugar maple',botanicalName:'Acer saccharum',matureHeightIn:[480,1440],matureSpreadIn:[360,720],sourceURL:'https://plants.ces.ncsu.edu/plants/acer-saccharum/',sourceNote:'NC State Extension: height 40–120 ft, spread 30–60 ft. Barrie zone 4–5 site and nursery stock need local confirmation. No price is assumed.'},
 {id:'acer-rubrum',commonName:'Red maple',botanicalName:'Acer rubrum',matureHeightIn:[480,1440],matureSpreadIn:[360,600],sourceURL:'https://plants.ces.ncsu.edu/plants/acer-rubrum/',sourceNote:'NC State Extension: height 40–120 ft, spread 30–50 ft. Site and nursery stock need local confirmation. No price is assumed.'},
 {id:'pinus-strobus',commonName:'Eastern white pine',botanicalName:'Pinus strobus',matureHeightIn:[600,960],matureSpreadIn:[240,480],sourceURL:'https://plants.ces.ncsu.edu/plants/pinus-strobus/',sourceNote:'NC State Extension: height 50–80 ft, spread 20–40 ft. The pine mesh is a summer needle-card proxy, not a measured specimen.'},
 {id:'amelanchier-canadensis',commonName:'Serviceberry',botanicalName:'Amelanchier canadensis',matureHeightIn:[180,300],matureSpreadIn:[180,240],sourceURL:'https://plants.ces.ncsu.edu/plants/amelanchier-canadensis/',sourceNote:'NC State Extension dimensions: height 15–25 ft; spread 15–20 ft. Climate and nursery stock suitability require local confirmation.'},
 {id:'cercis-canadensis',commonName:'Eastern redbud',botanicalName:'Cercis canadensis',matureHeightIn:[240,360],matureSpreadIn:[300,420],sourceURL:'https://plants.ces.ncsu.edu/plants/cercis-canadensis/',sourceNote:'NC State Extension: height 20–30 ft, spread 25–35 ft. Northern stock and site need local confirmation. No price is assumed.'},
 {id:'picea-pungens',commonName:'Colorado blue spruce',botanicalName:'Picea pungens',matureHeightIn:[360,720],matureSpreadIn:[120,240],sourceURL:'https://plants.ces.ncsu.edu/plants/picea-pungens/',sourceNote:'NC State Extension: height 30–60 ft, spread 10–20 ft. The conifer mesh is a summer proxy, not a measured blue spruce.'},
 {id:'thuja-occidentalis-smaragd',commonName:"'Smaragd' emerald cedar",botanicalName:"Thuja occidentalis 'Smaragd'",matureHeightIn:[144,168],matureSpreadIn:[36,48],sourceURL:'https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=254004',sourceNote:'Missouri Botanical Garden Plant Finder lists Smaragd at 12–14 ft tall and 3–4 ft wide. Use the cultivar size, not the species 40–60 ft. Nursery stock needs local confirmation.'},
 {id:'buxus-microphylla',commonName:'Boxwood',botanicalName:'Buxus microphylla',matureHeightIn:[36,48],matureSpreadIn:[24,48],sourceURL:'https://plants.ces.ncsu.edu/plants/buxus-microphylla/',sourceNote:'NC State Extension: height 3–4 ft, spread 2–4 ft. Zone 4–5 cultivar hardiness needs local confirmation. No price is assumed.'},
 {id:'taxus-media',commonName:'Yew',botanicalName:'Taxus × media',matureHeightIn:[24,240],matureSpreadIn:[24,144],sourceURL:'https://plants.ces.ncsu.edu/plants/taxus-x-media/',sourceNote:'NC State Extension: height 2–20 ft, spread 2–12 ft. Cultivar size varies widely; confirm the nursery plant. No price is assumed.'},
 {id:'physocarpus-opulifolius',commonName:'Ninebark',botanicalName:'Physocarpus opulifolius',matureHeightIn:[60,96],matureSpreadIn:[48,72],sourceURL:'https://plants.ces.ncsu.edu/plants/physocarpus-opulifolius/',sourceNote:'NC State Extension: height 5–8 ft, spread 4–6 ft. Cultivar foliage colour varies. No price is assumed.'},
 {id:'cornus-sericea',commonName:'Red-osier dogwood',botanicalName:'Cornus sericea',matureHeightIn:[60,108],matureSpreadIn:[60,120],sourceURL:'https://plants.ces.ncsu.edu/plants/cornus-sericea/',sourceNote:'NC State Extension dimensions: height 5–9 ft; spread 5–10 ft. Cultivar sizes vary.'},
 {id:'hydrangea-arborescens-annabelle',commonName:"'Annabelle' hydrangea",botanicalName:"Hydrangea arborescens 'Annabelle'",matureHeightIn:[36,60],matureSpreadIn:[36,60],sourceURL:'https://plants.ces.ncsu.edu/plants/hydrangea-arborescens/',sourceNote:'NC State Extension species page: height 3–5 ft, spread 3–5 ft. Annabelle is the common white cultivar in that range. Confirm the nursery plant. No price is assumed.'},
 {id:'hydrangea-paniculata',commonName:'Panicle hydrangea',botanicalName:'Hydrangea paniculata',matureHeightIn:[96,300],matureSpreadIn:[72,300],sourceURL:'https://plants.ces.ncsu.edu/plants/hydrangea-paniculata/',sourceNote:'NC State Extension: height 8–25 ft, spread 6–25 ft. Cultivar size varies. No price is assumed.'},
 {id:'spiraea-japonica',commonName:'Spirea',botanicalName:'Spiraea japonica',matureHeightIn:[48,72],matureSpreadIn:[48,84],sourceURL:'https://plants.ces.ncsu.edu/plants/spiraea-japonica/',sourceNote:'NC State Extension: height 4–6 ft, spread 4–7 ft. Cultivar size varies. No price is assumed.'},
 {id:'syringa-vulgaris',commonName:'Lilac',botanicalName:'Syringa vulgaris',matureHeightIn:[96,192],matureSpreadIn:[72,144],sourceURL:'https://plants.ces.ncsu.edu/plants/syringa-vulgaris/',sourceNote:'NC State Extension: height 8–16 ft, spread 6–12 ft. Cultivar size varies. No price is assumed.'},
 {id:'echinacea-purpurea',commonName:'Purple coneflower',botanicalName:'Echinacea purpurea',matureHeightIn:[36,48],matureSpreadIn:[12,24],sourceURL:'https://plants.ces.ncsu.edu/plants/echinacea-purpurea/',sourceNote:'NC State Extension: height 3–4 ft, spread 1–2 ft. No price is assumed.'},
 {id:'rudbeckia-hirta',commonName:'Black-eyed Susan',botanicalName:'Rudbeckia hirta',matureHeightIn:[24,48],matureSpreadIn:[12,24],sourceURL:'https://plants.ces.ncsu.edu/plants/rudbeckia-hirta/',sourceNote:'NC State Extension: height 2–4 ft, spread 1–2 ft. No price is assumed.'},
 {id:'monarda-fistulosa',commonName:'Wild bergamot',botanicalName:'Monarda fistulosa',matureHeightIn:[24,48],matureSpreadIn:[24,36],sourceURL:'https://plants.ces.ncsu.edu/plants/monarda-fistulosa/',sourceNote:'NC State Extension: height 2–4 ft, spread 2–3 ft. No price is assumed.'},
 {id:'hosta',commonName:'Hosta',botanicalName:'Hosta',matureHeightIn:[4,30],matureSpreadIn:[6,36],sourceURL:'https://plants.ces.ncsu.edu/plants/hosta/',sourceNote:'NC State Extension genus page: height 4 in–2.5 ft, spread 6 in–3 ft. Cultivar size varies; confirm the nursery plant. No price is assumed.'},
 {id:'matteuccia-struthiopteris',commonName:'Ostrich fern',botanicalName:'Matteuccia struthiopteris',matureHeightIn:[36,60],matureSpreadIn:[24,48],sourceURL:'https://plants.ces.ncsu.edu/plants/matteuccia-struthiopteris/',sourceNote:'NC State Extension: height 3–5 ft, spread 2–4 ft. No price is assumed.'},
 {id:'hemerocallis',commonName:'Daylily',botanicalName:'Hemerocallis',matureHeightIn:[12,36],matureSpreadIn:[12,36],sourceURL:'https://plants.ces.ncsu.edu/plants/hemerocallis/',sourceNote:'NC State Extension: height 1–3 ft, spread 1–3 ft. Cultivar colour and size vary. No price is assumed.'},
 {id:'nepeta-faassenii',commonName:'Catmint',botanicalName:'Nepeta × faassenii',matureHeightIn:[18,24],matureSpreadIn:[24,36],sourceURL:'https://plants.ces.ncsu.edu/plants/nepeta-x-faassenii/',sourceNote:'NC State Extension: height 1.5–2 ft, spread 2–3 ft. Confirm the cultivar for zone 4–5. No price is assumed.'},
 {id:'salvia-nemorosa',commonName:'Salvia',botanicalName:'Salvia nemorosa',matureHeightIn:[18,36],matureSpreadIn:[6,24],sourceURL:'https://plants.ces.ncsu.edu/plants/salvia-nemorosa/',sourceNote:'NC State Extension: height 1.5–3 ft, spread 0.5–2 ft. Cultivar hardiness needs local confirmation. No price is assumed.'},
 {id:'calamagrostis-karl-foerster',commonName:'Karl Foerster feather reed grass',botanicalName:"Calamagrostis × acutiflora 'Karl Foerster'",matureHeightIn:[60,60],matureSpreadIn:[24,24],sourceURL:'https://plantsearch.extension.umn.edu/searchplants/view?editid1=1551',sourceNote:'University of Minnesota profile lists height 5 ft and spread 2 ft. The grass mesh is a summer proxy, not a measured cultivar.'},
 {id:'schizachyrium-scoparium',commonName:'Little bluestem',botanicalName:'Schizachyrium scoparium',matureHeightIn:[24,48],matureSpreadIn:[18,36],sourceURL:'https://plants.ces.ncsu.edu/plants/schizachyrium-scoparium/',sourceNote:'NC State Extension: height 2–4 ft, spread 1.5–3 ft. No price is assumed.'},
 {id:'panicum-virgatum',commonName:'Switchgrass',botanicalName:'Panicum virgatum',matureHeightIn:[36,84],matureSpreadIn:[24,36],sourceURL:'https://plants.ces.ncsu.edu/plants/panicum-virgatum/',sourceNote:'NC State Extension: height 3–7 ft, spread 2–3 ft. Cultivar size varies. No price is assumed.'},
];
/** Visual family for a species. Kept off the persisted species record, which rejects unknown keys. */
export interface PlantVisual {speciesId:string;assetId:LandscapeAssetId;tint:string;heightIn:number;widthIn:number;depthIn:number;group:'Trees'|'Hedges and evergreens'|'Shrubs'|'Perennials'|'Grasses'}
export const PLANT_LIBRARY:PlantVisual[]=[
 {speciesId:'acer-saccharum',assetId:'deciduous-tree',tint:'#e7f0d4',heightIn:180,widthIn:108,depthIn:108,group:'Trees'},
 {speciesId:'acer-rubrum',assetId:'deciduous-tree',tint:'#f3efe6',heightIn:180,widthIn:108,depthIn:108,group:'Trees'},
 {speciesId:'pinus-strobus',assetId:'pine-tree',tint:'#d5e0c8',heightIn:168,widthIn:96,depthIn:96,group:'Trees'},
 {speciesId:'amelanchier-canadensis',assetId:'deciduous-tree',tint:'#f7f3ea',heightIn:120,widthIn:84,depthIn:84,group:'Trees'},
 {speciesId:'cercis-canadensis',assetId:'deciduous-tree',tint:'#f6efe8',heightIn:132,widthIn:108,depthIn:108,group:'Trees'},
 {speciesId:'picea-pungens',assetId:'conifer-tree',tint:'#9eb8b4',heightIn:144,widthIn:72,depthIn:72,group:'Trees'},
 {speciesId:'thuja-occidentalis-smaragd',assetId:'hedge-shrub',tint:'#8fd18a',heightIn:96,widthIn:36,depthIn:36,group:'Hedges and evergreens'},
 {speciesId:'buxus-microphylla',assetId:'evergreen-shrub',tint:'#6d8f62',heightIn:24,widthIn:28,depthIn:28,group:'Hedges and evergreens'},
 {speciesId:'taxus-media',assetId:'hedge-shrub',tint:'#3f5c40',heightIn:48,widthIn:36,depthIn:36,group:'Hedges and evergreens'},
 {speciesId:'physocarpus-opulifolius',assetId:'rounded-shrub',tint:'#8a9a6a',heightIn:48,widthIn:48,depthIn:48,group:'Shrubs'},
 {speciesId:'cornus-sericea',assetId:'rounded-shrub',tint:'#c4d4a8',heightIn:42,widthIn:42,depthIn:42,group:'Shrubs'},
 {speciesId:'hydrangea-arborescens-annabelle',assetId:'rounded-shrub',tint:'#e8f0dc',heightIn:36,widthIn:40,depthIn:40,group:'Shrubs'},
 {speciesId:'hydrangea-paniculata',assetId:'rounded-shrub',tint:'#dfe8d4',heightIn:48,widthIn:42,depthIn:42,group:'Shrubs'},
 {speciesId:'spiraea-japonica',assetId:'rounded-shrub',tint:'#c9d6a4',heightIn:30,widthIn:36,depthIn:36,group:'Shrubs'},
 {speciesId:'syringa-vulgaris',assetId:'rounded-shrub',tint:'#d5e0c0',heightIn:48,widthIn:40,depthIn:40,group:'Shrubs'},
 {speciesId:'echinacea-purpurea',assetId:'perennial-bloom',tint:'#f0e4f2',heightIn:30,widthIn:18,depthIn:18,group:'Perennials'},
 {speciesId:'rudbeckia-hirta',assetId:'perennial-gold',tint:'#f3e2a0',heightIn:28,widthIn:16,depthIn:16,group:'Perennials'},
 {speciesId:'monarda-fistulosa',assetId:'perennial-bloom',tint:'#e4d0ea',heightIn:30,widthIn:24,depthIn:24,group:'Perennials'},
 {speciesId:'hosta',assetId:'hosta-clump',tint:'#b7d0a4',heightIn:16,widthIn:28,depthIn:28,group:'Perennials'},
 {speciesId:'matteuccia-struthiopteris',assetId:'fern-clump',tint:'#8fb56a',heightIn:36,widthIn:28,depthIn:28,group:'Perennials'},
 {speciesId:'hemerocallis',assetId:'perennial-gold',tint:'#f0d090',heightIn:24,widthIn:20,depthIn:20,group:'Perennials'},
 {speciesId:'nepeta-faassenii',assetId:'perennial-bloom',tint:'#d5d8f0',heightIn:18,widthIn:24,depthIn:24,group:'Perennials'},
 {speciesId:'salvia-nemorosa',assetId:'perennial-bloom',tint:'#c5cce8',heightIn:24,widthIn:16,depthIn:16,group:'Perennials'},
 {speciesId:'calamagrostis-karl-foerster',assetId:'reed-grass',tint:'#d7c98a',heightIn:48,widthIn:24,depthIn:24,group:'Grasses'},
 {speciesId:'schizachyrium-scoparium',assetId:'grass-clump',tint:'#8a9a9a',heightIn:30,widthIn:18,depthIn:18,group:'Grasses'},
 {speciesId:'panicum-virgatum',assetId:'grass-clump',tint:'#b7c48a',heightIn:42,widthIn:24,depthIn:24,group:'Grasses'},
];
export const plantLibraryEntry=(speciesId?:string)=>PLANT_LIBRARY.find(p=>p.speciesId===speciesId);
/** Instance tint for a named planting. Unspecified plants stay the source colour. */
export const plantFoliageTint=(speciesId?:string)=>plantLibraryEntry(speciesId)?.tint??'#ffffff';
export const landscapeAsset=(id:LandscapeAssetId)=>LANDSCAPE_ASSETS.find(a=>a.id===id)!;
export function newLandscapeObject(assetId:LandscapeAssetId,id:string,xIn=0,zIn=240):LandscapeObject {
 const a=landscapeAsset(assetId);return {id,name:a.name,enabled:true,kind:a.kind,assetId,xIn,zIn,rotationDeg:0,heightIn:a.heightIn,widthIn:a.widthIn,depthIn:a.depthIn,...a.kind==='bed'?(assetId==='mulch-bed'?{mulchDepthIn:3,edging:false}:{surfaceDepthIn:landscapeSurface(assetId)!.defaultDepthIn,edging:false,...assetId==='putting-green'?{puttingCups:[{x:0,z:0}]}:{}}):{} };
}
/** A named Ontario planting at an installed size. Supply stays unpriced; spacing is not inferred. */
export function newLandscapePlant(speciesId:string,id:string,xIn=0,zIn=240):LandscapeObject {
 const species=LANDSCAPE_SPECIES.find(s=>s.id===speciesId),visual=plantLibraryEntry(speciesId);
 if(!species||!visual)throw Error('Unknown planting species.');
 return {...newLandscapeObject(visual.assetId,id,xIn,zIn),name:species.commonName,heightIn:visual.heightIn,widthIn:visual.widthIn,depthIn:visual.depthIn,speciesRecord:species};
}
