import {LANDSCAPE_SURFACES,landscapeSurface} from './landscapeSurfaces';
import type {LandscapeAssetId,LandscapeKind,LandscapeObject,LandscapeSpeciesRecord} from './landscapeTypes';
export interface LandscapeAsset {id:LandscapeAssetId;name:string;kind:LandscapeKind;category:string;heightIn:number;widthIn:number;depthIn:number;sourceURL?:string;modelURL?:string;lowModelURL?:string;farModelURL?:string;triangleCounts?:[number,number,number];visualNote:string}
const model=(id:string)=>'/deckcraft/landscape/'+id;
export const LANDSCAPE_ASSETS:LandscapeAsset[]=[
 {id:'deciduous-tree',name:'Deciduous tree',kind:'plant',category:'Trees',heightIn:180,widthIn:108,depthIn:108,sourceURL:'https://polyhaven.com/a/tree_small_02',modelURL:model('deciduous-tree-lod0.glb'),lowModelURL:model('deciduous-tree-lod1.glb'),visualNote:'Generic broadleaf visual proxy. Source mesh is Tree Small 02; a species record is selected separately.'},
 {id:'conifer-tree',name:'Conifer tree',kind:'plant',category:'Trees',heightIn:144,widthIn:72,depthIn:72,sourceURL:'https://polyhaven.com/a/fir_tree_01',modelURL:model('conifer-tree-lod0.glb'),lowModelURL:model('conifer-tree-lod1.glb'),visualNote:'Generic evergreen visual proxy from Fir Tree 01. It does not identify a planting species or nursery SKU.'},
 {id:'rounded-shrub',name:'Natural shrub',kind:'plant',category:'Shrubs and hedges',heightIn:36,widthIn:40,depthIn:40,sourceURL:'https://polyhaven.com/a/shrub_02',modelURL:model('rounded-shrub-lod0.glb'),lowModelURL:model('rounded-shrub-lod1.glb'),visualNote:'Generic photographed shrub foliage; not a botanical species match.'},
 {id:'hedge-shrub',name:'Hedge shrub',kind:'plant',category:'Shrubs and hedges',heightIn:48,widthIn:36,depthIn:30,sourceURL:'https://polyhaven.com/a/shrub_02',modelURL:model('rounded-shrub-lod0.glb'),lowModelURL:model('rounded-shrub-lod1.glb'),visualNote:'One shrub placement, with the same generic foliage proxy as Natural shrub. A hedge is built from individually counted shrubs.'},
 {id:'grass-clump',name:'Ornamental grass clump',kind:'plant',category:'Grasses',heightIn:30,widthIn:24,depthIn:24,sourceURL:'https://polyhaven.com/a/grass_medium_01',modelURL:model('grass-clump-lod0.glb'),lowModelURL:model('grass-clump-lod1.glb'),visualNote:'Generic grass visual proxy; planting species and mature size are separate records.'},
 {id:'natural-boulder',name:'Natural boulder',kind:'boulder',category:'Stone',heightIn:24,widthIn:42,depthIn:30,sourceURL:'https://polyhaven.com/a/namaqualand_boulder_03',modelURL:model('natural-boulder-lod0.glb'),lowModelURL:model('natural-boulder-lod1.glb'),visualNote:'CC0 rock scan scaled to the chosen envelope. Stone type, weight, supply and placement require a quote.'},
 {id:'outdoor-table',name:'Outdoor folding table',kind:'furniture',category:'Furniture',heightIn:30,widthIn:36,depthIn:36,sourceURL:'https://polyhaven.com/a/outdoor_table_chair_set_01',modelURL:model('outdoor-table-lod0.glb'),lowModelURL:model('outdoor-table-lod1.glb'),visualNote:'Generic outdoor furniture, not a priced manufacturer product.'},
 {id:'outdoor-chair',name:'Outdoor folding chair',kind:'furniture',category:'Furniture',heightIn:34,widthIn:20,depthIn:22,sourceURL:'https://polyhaven.com/a/outdoor_table_chair_set_01',modelURL:model('outdoor-chair-lod0.glb'),lowModelURL:model('outdoor-chair-lod1.glb'),visualNote:'Generic outdoor furniture, not a priced manufacturer product.'},
 {id:'mulch-bed',name:'Planting bed',kind:'bed',category:'Beds',heightIn:1,widthIn:120,depthIn:72,visualNote:'Measured polygon area, mulch volume and optional edging. Plant placements are counted separately.'},
 {id:'lounge-chair',name:'Cushioned chaise lounge',kind:'furniture',category:'Furniture',heightIn:32,widthIn:30,depthIn:80,modelURL:model('lounge-chair-lod0.glb'),lowModelURL:model('lounge-chair-lod1.glb'),visualNote:'Original project-owned teak-frame and fabric-cushion visual proxy. Actual product, dimensions and price require selection.'},
 {id:'outdoor-sofa',name:'Outdoor three-seat sofa',kind:'furniture',category:'Furniture',heightIn:32,widthIn:84,depthIn:36,modelURL:model('outdoor-sofa-lod0.glb'),lowModelURL:model('outdoor-sofa-lod1.glb'),visualNote:'Original project-owned upholstered outdoor seating proxy. Not a built-in bench or verified manufacturer SKU.'},
 {id:'outdoor-coffee-table',name:'Outdoor low coffee table',kind:'furniture',category:'Furniture',heightIn:16,widthIn:48,depthIn:26,modelURL:model('outdoor-coffee-table-lod0.glb'),lowModelURL:model('outdoor-coffee-table-lod1.glb'),visualNote:'Original project-owned low slatted-table visual proxy. Supply and installation remain unpriced.'},
];
for(const s of LANDSCAPE_SURFACES.filter(s=>s.id!=='mulch-bed'))LANDSCAPE_ASSETS.push({id:s.id,name:s.name,kind:'bed',category:s.type==='turf'?'Turf and greens':'Decorative ground covers',heightIn:1,widthIn:s.type==='turf'?180:120,depthIn:s.type==='turf'?240:72,visualNote:'Editable planning finish. Original visual proxy; confirm actual product, depth, base, drainage and installation. No supplier price is assumed.'});
const triangleCounts:Partial<Record<LandscapeAssetId,[number,number,number]>>={'deciduous-tree':[65256,31663,8499],'conifer-tree':[14364,5799,2012],'rounded-shrub':[7590,7590,7590],'hedge-shrub':[7590,7590,7590],'grass-clump':[2287,2287,2287],'natural-boulder':[10370,3240,810],'outdoor-table':[2324,1592,1472],'outdoor-chair':[3752,1876,1592],'lounge-chair':[1396,948,724],'outdoor-sofa':[3876,2532,1860],'outdoor-coffee-table':[216,216,216]};
for(const a of LANDSCAPE_ASSETS)if(a.lowModelURL){a.farModelURL=a.lowModelURL.replace('-lod1.glb','-lod2.glb');a.triangleCounts=triangleCounts[a.id];}
/** These records describe mature planning envelopes, not the identity of the
 * visual mesh or an Ontario nursery quotation. Site/cultivar suitability still
 * needs selection; no planting spacing is inferred from mature spread. */
export const LANDSCAPE_SPECIES:LandscapeSpeciesRecord[]=[
 {id:'amelanchier-canadensis',commonName:'Canadian serviceberry',botanicalName:'Amelanchier canadensis',matureHeightIn:[180,300],matureSpreadIn:[180,240],sourceURL:'https://plants.ces.ncsu.edu/plants/amelanchier-canadensis/',sourceNote:'NC State Extension dimensions: height 15–25 ft; spread 15–20 ft. Climate and nursery stock suitability require local confirmation.'},
 {id:'pinus-strobus',commonName:'Eastern white pine',botanicalName:'Pinus strobus',matureHeightIn:[600,960],matureSpreadIn:[240,480],sourceURL:'https://plants.ces.ncsu.edu/plants/pinus-strobus/',sourceNote:'NC State Extension: height 50–80 ft; spread 20–40 ft. The generic fir mesh is not a species-accurate white pine.'},
 {id:'cornus-sericea',commonName:'Red-osier dogwood',botanicalName:'Cornus sericea',matureHeightIn:[60,108],matureSpreadIn:[60,120],sourceURL:'https://plants.ces.ncsu.edu/plants/cornus-sericea/',sourceNote:'NC State Extension dimensions: height 5–9 ft; spread 5–10 ft. Cultivar sizes vary.'},
 {id:'calamagrostis-karl-foerster',commonName:'Karl Foerster feather reed grass',botanicalName:"Calamagrostis × acutiflora 'Karl Foerster'",matureHeightIn:[60,60],matureSpreadIn:[24,24],sourceURL:'https://plantsearch.extension.umn.edu/searchplants/view?editid1=1551',sourceNote:'University of Minnesota profile lists height 5 ft and spread 2 ft. The generic grass mesh is not a species-accurate cultivar model.'},
];
export const landscapeAsset=(id:LandscapeAssetId)=>LANDSCAPE_ASSETS.find(a=>a.id===id)!;
export function newLandscapeObject(assetId:LandscapeAssetId,id:string,xIn=0,zIn=240):LandscapeObject {
 const a=landscapeAsset(assetId);return {id,name:a.name,enabled:true,kind:a.kind,assetId,xIn,zIn,rotationDeg:0,heightIn:a.heightIn,widthIn:a.widthIn,depthIn:a.depthIn,...a.kind==='bed'?(assetId==='mulch-bed'?{mulchDepthIn:3,edging:false}:{surfaceDepthIn:landscapeSurface(assetId)!.defaultDepthIn,edging:false,...assetId==='putting-green'?{puttingCups:[{x:0,z:0}]}:{}}):{} };
}
/**
 * Where a library add lands. This list has no plan cursor, so the first object sits just past the deck
 * (deck centre, 8 ft into the yard) and each later one steps aside instead of sharing that point.
 */
export function landscapeLibraryPoint(deck:{width:number;length:number},asset:{widthIn:number;depthIn:number},existing:readonly {xIn:number;zIn:number;widthIn?:number}[]):{xIn:number;zIn:number}{
 const anchorX=deck.width*6,anchorZ=(deck.length+8)*12,stepX=Math.max(36,Math.round(asset.widthIn)+12),stepZ=Math.max(36,Math.round(asset.depthIn)+12);
 const crowded=(x:number,z:number)=>existing.some(o=>Math.hypot(o.xIn-x,o.zIn-z)<Math.max(18,((o.widthIn??36)+asset.widthIn)/4));
 for(let row=0;row<40;row++)for(let col=0;col<8;col++){const xIn=anchorX+col*stepX,zIn=anchorZ+row*stepZ;if(!crowded(xIn,zIn))return {xIn,zIn};}
 return {xIn:anchorX+existing.length*stepX,zIn:anchorZ};
}
