import {useId,useRef,useState,type PointerEvent} from 'react';
import type {DeckData,DeckShape} from './types';
import type {DeckTakeoff} from './deckTakeoff';
import {getFootprint,type EdgeName} from './lib/deckGeometry';
import {landingSplit,layoutEdges,layoutExitDeck,layoutOpening,shapePatch,stairOffsetAtPoint,stairTurnForDirection} from './layoutControls';

const layoutKeys=['shape','cutoutCorner','width','length','height','cutoutWidth','cutoutLength','cutoutWidth2','cutoutLength2','levels','width2','length2','height2','level2Position','level2Offset','stairFlights','stairPosition','stairOffset','stairWidth','stairType','stairTurn','landingDepthIn','landingStraight','landingAfterRisers'] as const;
const shapeOptions:[string,DeckShape,'Left'|'Right'][]=[['Rectangle','Rectangle','Right'],['L · cut-out left','L-Shape','Left'],['L · cut-out right','L-Shape','Right'],['Two cut-outs','Multi-corner','Right'],['Curved front','Curved','Right']];
export default function LayoutEditor({data,model,onChange}:{data:DeckData;model:DeckTakeoff;onChange:(patch:Partial<DeckData>)=>void}){
  const [tab,setTab]=useState<'deck'|'stairs'|'second'>('deck'),[history,setHistory]=useState<Partial<DeckData>[]>([]),[dragOffset,setDragOffset]=useState<number|null>(null);
  const drag=useRef<{edge:EdgeName;offset:number}|null>(null),arrowId=useId();
  const change=(patch:Partial<DeckData>)=>{setHistory(h=>[...h.slice(-19),Object.fromEntries(layoutKeys.map(k=>[k,data[k]]))]);onChange(patch);};
  const exitDeck=layoutExitDeck(data,model),edges=layoutEdges(data,model),edge=edges.includes(data.stairPosition)?data.stairPosition:edges[0];
  const opening=edge?layoutOpening(data,model,edge,dragOffset??data.stairOffset):null;
  const totalRisers=Math.max(1,Math.ceil(exitDeck.top/7.75)),split=landingSplit(totalRisers,data.landingAfterRisers);
  const polygons=model.levels.map(l=>({level:l,points:l.footprint.outline.map(p=>({x:p.x+l.offset.x,y:p.y+l.offset.z}))}));
  const points=[...polygons.flatMap(p=>p.points),...model.flights.flatMap(f=>[{x:f.start.x,y:f.start.z},{x:f.end.x,y:f.end.z}])];
  const minX=Math.min(0,...points.map(p=>p.x)),maxX=Math.max(12,...points.map(p=>p.x)),minY=Math.min(0,...points.map(p=>p.y)),maxY=Math.max(12,...points.map(p=>p.y));
  const scale=Math.max(maxX-minX,maxY-minY)/360,pad=28*scale;
  const localPoint=(e:PointerEvent<SVGElement>|React.MouseEvent<SVGElement>)=>{const svg=e.currentTarget.ownerSVGElement;const matrix=svg?.getScreenCTM();return matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):null;};
  const chooseEdge=(edge:EdgeName,offset=50)=>{setTab('stairs');change({stairPosition:edge,stairOffset:offset,stairFlights:Math.max(1,data.stairFlights)});};
  const number=(label:string,key:keyof DeckData,value:number,min:number,max:number,unit:string,step=1)=><label className="dd-field"><span>{label}</span><span className="dd-number"><input key={`${key}:${value}`} aria-label={label} type="number" min={min} max={max} step={step} defaultValue={value} onBlur={e=>{const n=Number(e.target.value);if(e.target.value.trim()&&Number.isFinite(n)){const next=Math.min(max,Math.max(min,n));if(next!==value)change({[key]:next});}else e.target.value=String(value);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>{unit}</span></span></label>;
  const slider=(label:string,key:'stairOffset'|'level2Offset'|'landingAfterRisers',value:number,min=0,max=100,step=5)=><label className="dd-field dd-layout-slider"><span>{label} <strong>{value}{key==='landingAfterRisers'?' risers':'%'}</strong></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>change({[key]:Number(e.target.value)})}/></label>;
  const route=(direction:'Straight'|'Left'|'Right')=>{if(!opening)return;change({stairFlights:Math.max(1,data.stairFlights),stairType:'Landing',landingStraight:direction==='Straight',...(direction!=='Straight'?{stairTurn:stairTurnForDirection(opening,direction)}:{})});};
  const activeDirection=data.landingStraight?'Straight':opening&&data.stairTurn===stairTurnForDirection(opening,'Left')?'Left':'Right';
  return <section className="dd-layout-editor" aria-label="Visual deck and stair layout editor">
    <p className="dd-note">Choose a shape, tap a highlighted edge for stairs, or drag the round stair handle along its edge. Arrows show the actual route down. Deck sizes are in feet; heights and stair sizes are in inches.</p>
    <svg className="dd-layout-map" viewBox={`${minX-pad} ${minY-pad} ${maxX-minX+pad*2} ${maxY-minY+pad*2}`} aria-label="Deck, stairs and landings top-view layout">
      <defs><marker id={arrowId} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#994b2e"/></marker></defs>
      {polygons.map(({level:l,points},i)=><g key={i} role="button" tabIndex={0} aria-label={l.kind==='deck'?(i===0?'Edit main deck footprint':'Edit second deck section'):'Edit stair landing'} onClick={()=>setTab(l.kind==='deck'?(i===0?'deck':'second'):'stairs')} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setTab(l.kind==='deck'?(i===0?'deck':'second'):'stairs');}}}><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={l.kind==='deck'?(i===0?'#e6d7bb':'#c7ddd5'):'#f0bf88'} stroke="#746247" strokeWidth={scale}/><text x={l.offset.x+l.footprint.bounds.w/2} y={l.offset.z+l.footprint.bounds.h/2} textAnchor="middle" fontSize={11*scale} fill="#322f27">{l.kind==='deck'?(i===0?'Main deck':'Section 2'):l.kind==='winder'?'Winder':'Landing'}</text></g>)}
      {model.flights.map((f,i)=><line key={i} x1={f.start.x} y1={f.start.z} x2={f.end.x} y2={f.end.z} stroke="#994b2e" strokeWidth={2*scale} markerEnd={`url(#${arrowId})`}><title>{f.kind==='connection'?'Between deck sections':'Stairs to ground'} · {f.risers} risers</title></line>)}
      {edges.map(e=>{const a=layoutOpening(data,model,e,0),b=layoutOpening(data,model,e,100);return <g key={e} role="button" tabIndex={0} aria-label={`Place stairs on ${e.toLowerCase()} edge`} onClick={event=>{const p=localPoint(event);chooseEdge(e,p?stairOffsetAtPoint(data,model,e,p):50);}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();chooseEdge(e);}}}><line x1={a.origin.x+exitDeck.offset.x} y1={a.origin.y+exitDeck.offset.z} x2={b.origin.x+b.along.x*b.width+exitDeck.offset.x} y2={b.origin.y+b.along.y*b.width+exitDeck.offset.z} stroke="transparent" strokeWidth={18*scale}/><line x1={a.origin.x+exitDeck.offset.x} y1={a.origin.y+exitDeck.offset.z} x2={b.origin.x+b.along.x*b.width+exitDeck.offset.x} y2={b.origin.y+b.along.y*b.width+exitDeck.offset.z} stroke={e===edge&&data.stairFlights>0?'#176454':'#639b8c'} strokeWidth={4*scale} strokeDasharray={e===edge&&data.stairFlights>0?undefined:`${5*scale} ${3*scale}`}/></g>;})}
      {opening&&data.stairFlights>0&&<g className="dd-layout-handle" role="button" tabIndex={0} aria-label="Move primary stair attachment" onPointerDown={e=>{e.stopPropagation();e.preventDefault();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);drag.current={edge,offset:data.stairOffset};setTab('stairs');}} onPointerMove={e=>{if(drag.current){const p=localPoint(e);if(p){const offset=stairOffsetAtPoint(data,model,drag.current.edge,p);drag.current.offset=offset;setDragOffset(offset);}}}} onPointerUp={e=>{if(drag.current){const next=drag.current;drag.current=null;setDragOffset(null);e.currentTarget.releasePointerCapture(e.pointerId);if(next.offset!==data.stairOffset)change({stairOffset:next.offset});}}} onPointerCancel={()=>{drag.current=null;setDragOffset(null);}} onKeyDown={e=>{if(['ArrowLeft','ArrowUp','ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();change({stairOffset:Math.max(0,Math.min(100,data.stairOffset+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)*(e.shiftKey?10:5)))});}}}>
        <circle cx={opening.origin.x+opening.along.x*opening.width/2+exitDeck.offset.x} cy={opening.origin.y+opening.along.y*opening.width/2+exitDeck.offset.z} r={20*scale} fill="transparent"/>
        <circle cx={opening.origin.x+opening.along.x*opening.width/2+exitDeck.offset.x} cy={opening.origin.y+opening.along.y*opening.width/2+exitDeck.offset.z} r={9*scale} fill="#176454" stroke="white" strokeWidth={2*scale}/>
      </g>}
    </svg>
    <p className="dd-note">Top view · back / house side is at the top. Green = stair attachment options; orange = stair path / landing. {data.levels>1?'Ground stairs leave the lower deck section. ':''}For notched shapes, each side uses its longest eligible edge.</p>
    <div className="dd-layout-tabs" role="group" aria-label="Layout part">{([['deck','Deck shape & size'],['stairs','Stairs & landing'],['second','Second section']] as const).map(([id,label])=><button className="dd-secondary" key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='deck'&&<>
      <h3>Choose the footprint</h3><div className="dd-shape-options">{shapeOptions.map(([label,shape,corner])=>{const fp=getFootprint({...data,width:12,length:9,stairFlights:0,shape,cutoutCorner:corner,cutoutWidth:4,cutoutLength:4,cutoutWidth2:3,cutoutLength2:3});return <button type="button" className="dd-shape-choice" key={label} aria-pressed={data.shape===shape&&(shape!=='L-Shape'||(data.cutoutCorner??'Right')===corner)} onClick={()=>change(shapePatch(data,shape,corner))}><svg viewBox="-5 -5 154 140" aria-hidden="true"><polygon points={fp.outline.map(p=>`${p.x},${p.y}`).join(' ')}/></svg><span>{label}</span></button>;})}</div>
      <div className="dd-fields two">{number('Main deck width','width',data.width,4,60,'ft',.5)}{number('Main deck depth','length',data.length,4,60,'ft',.5)}{number('Main deck height','height',data.height,8,144,'in')}</div>
      {(data.shape==='L-Shape'||data.shape==='Multi-corner')&&<><h3>{data.shape==='L-Shape'?`${data.cutoutCorner??'Right'} cut-out`:'Right cut-out'}</h3><div className="dd-fields two">{number('Cut-out width','cutoutWidth',data.cutoutWidth,0,data.width*.8,'ft',.5)}{number('Cut-out depth','cutoutLength',data.cutoutLength,0,data.length*.8,'ft',.5)}</div></>}
      {data.shape==='Multi-corner'&&<><h3>Left cut-out</h3><div className="dd-fields two">{number('Left cut-out width','cutoutWidth2',data.cutoutWidth2,0,Math.max(0,data.width-data.cutoutWidth)*.8,'ft',.5)}{number('Left cut-out depth','cutoutLength2',data.cutoutLength2,0,data.length*.8,'ft',.5)}</div></>}
    </>}
    {tab==='stairs'&&<>
      <h3>Where do the stairs start?</h3><div className="dd-layout-tabs" role="group" aria-label="Stair side"><button className="dd-secondary" aria-pressed={data.stairFlights===0} onClick={()=>change({stairFlights:0})}>No ground stairs</button>{edges.map(e=><button className="dd-secondary" key={e} aria-pressed={data.stairFlights>0&&edge===e} onClick={()=>chooseEdge(e,data.stairOffset)}>{e}</button>)}</div>
      {data.stairFlights>0&&<>{slider('Position along selected edge','stairOffset',data.stairOffset)}<div className="dd-summary-actions"><button className="dd-secondary" onClick={()=>change({stairOffset:0})}>Start of edge</button><button className="dd-secondary" onClick={()=>change({stairOffset:50})}>Centre</button><button className="dd-secondary" onClick={()=>change({stairOffset:100})}>End of edge</button></div>
        <p className="dd-note">Position runs left → right on front/back edges, and back → front on side edges.</p>
        {number('Stair width','stairWidth',data.stairWidth,36,120,'in',6)}
        <h3>Choose the route down</h3><div className="dd-layout-tabs" role="group" aria-label="Stair route"><button className="dd-secondary" aria-pressed={data.stairType==='Straight'} onClick={()=>change({stairType:'Straight'})}>↓ Straight out</button>{(['Straight','Left','Right'] as const).map(dir=><button className="dd-secondary" key={dir} disabled={totalRisers<4} aria-pressed={data.stairType==='Landing'&&activeDirection===dir} onClick={()=>route(dir)}>{dir==='Straight'?'↓ Landing · continue':dir==='Left'?'↶ Landing · turn left':'↷ Landing · turn right'}</button>)}</div>
        <p className="dd-note">Left/right turns are described while walking down the stairs. {totalRisers<4?'This short stair has fewer than four risers; the current model uses a straight run.':''}</p>
        {(data.stairType==='Landing'&&totalRisers>=4||data.stairType==='Straight'&&totalRisers>14)&&<><h3>Move and size the landing</h3>{slider('Landing after','landingAfterRisers',split.upper,split.min,split.max,1)}<div className="dd-summary-actions"><button className="dd-secondary" onClick={()=>change({landingAfterRisers:split.min})}>Near the deck</button><button className="dd-secondary" onClick={()=>change({landingAfterRisers:landingSplit(totalRisers).upper})}>Midway</button><button className="dd-secondary" onClick={()=>change({landingAfterRisers:split.max})}>Near the ground</button></div><p className="dd-note">{split.upper} risers to the landing · {split.lower} to ground. Its elevation and framing follow the stair geometry.</p>{number('Landing length','landingDepthIn',Math.max(data.stairWidth,data.landingDepthIn??48),data.stairWidth,120,'in',6)}<p className="dd-note">Landing width follows stair width. The modeled landing length cannot be shorter than that width.</p></>}
        <details className="dd-advanced"><summary>More stair options</summary><label className="dd-field"><span>Ground stair exits</span><select aria-label="Ground stair exits" value={data.stairFlights} onChange={e=>change({stairFlights:Number(e.target.value)})}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label><p className="dd-note">These controls position the primary exit. Extra exits are automatically centred on other available edges and share the same route and landing settings.</p><button className="dd-secondary" aria-pressed={data.stairType==='Winder'} onClick={()=>change({stairType:'Winder'})}>Use winder treads</button>{data.stairType==='Winder'&&opening&&<div className="dd-summary-actions">{(['Left','Right'] as const).map(dir=><button key={dir} className="dd-secondary" onClick={()=>change({stairTurn:stairTurnForDirection(opening,dir)})}>Winder turn {dir.toLowerCase()}</button>)}</div>}<p className="dd-note">Winders and all stair/landing connections require project-specific review before construction.</p></details>
      </>}
    </>}
    {tab==='second'&&<>
      <h3>Connect another deck section</h3><label className="dd-check"><input type="checkbox" checked={data.levels>1} onChange={e=>change({levels:e.target.checked?2:1})}/><span>Include a second section</span></label>
      {data.levels>1&&<><div className="dd-layout-tabs" role="group" aria-label="Second section side">{(['Front','Left','Right'] as const).map(side=><button className="dd-secondary" key={side} aria-pressed={(data.level2Position??'Front')===side} onClick={()=>change({level2Position:side})}>{side}</button>)}</div>{slider('Second section position','level2Offset',data.level2Offset??50)}<div className="dd-fields two">{number('Second section width','width2',data.width2,4,40,'ft',.5)}{number('Second section depth','length2',data.length2,4,40,'ft',.5)}{number('Second section height','height2',data.height2,8,144,'in')}</div><button className="dd-secondary" onClick={()=>change({height2:data.height})}>Match main deck height</button><p className="dd-note">Sections join automatically. Different heights generate connecting stairs; ground exits move to the lower section. This editor supports two connected deck sections, not detached/freehand platforms.</p></>}
    </>}
    <div className="dd-summary-actions"><button className="dd-secondary" disabled={!history.length} onClick={()=>{const previous=history.at(-1);if(previous){onChange(previous);setHistory(h=>h.slice(0,-1));}}}>Undo layout change</button></div>
    <p className="dd-note">Layout changes update your saved design, 3D/photo model, plans and quantities. This is design coordination, not a structural or permit approval.</p>
  </section>;
}
