/** Discovery references checked 2026-09-21, not SKU stock, pricing or engineered assemblies. */
export interface OntarioComponentFamily {
  id:string;
  brand:string;
  category:'Decking & trim'|'Railings & gates'|'Framing & connections'|'Fasteners & protection'|'Drainage'|'Lighting systems'|'Privacy screens';
  name:string;
  components:string;
  availability:string;
  caution:string;
  sourceUrl:string;
  availabilityUrl?:string;
}

export const ONTARIO_COMPONENT_FAMILIES:OntarioComponentFamily[]=[
  {id:'trex-lighting',brand:'Trex',category:'Lighting systems',name:'Deck, rail, riser and post-cap lighting',components:'Recessed, riser, post and rail fixtures; matching control, wiring and power components.',availability:'Canadian lighting catalogue; confirm Ontario stock and product generation.',caution:'Trex pages include different lighting generations, including a newer 24V system. Verify exact voltage and matched power/control parts; never assume compatibility with in-lite.',sourceUrl:'https://www.trex.com/products/deck-lighting/',availabilityUrl:'https://ca.trex.com/products/deck-lighting/'},
  {id:'timbertech-lighting',brand:'TimberTech',category:'Lighting systems',name:'Deck and railing lighting',components:'Accent, in-deck, island cap, post cap, riser and under-rail fixtures.',availability:'Canadian product catalogue; confirm Ontario variants and stock.',caution:'Canadian FAQ requires the TimberTech Transformer or PowerPack for its stated lighting warranty. Check current kit instructions, circuit limits and mounting compatibility.',sourceUrl:'https://www.timbertech.ca/products/lighting',availabilityUrl:'https://www.timbertech.ca/resources/faqs'},
  {id:'regal-led',brand:'Regal ideas',category:'Lighting systems',name:'Integrated railing LED system',components:'LED strips, controller, clear picket spacers and glass-lighting gasket details.',availability:'Canadian product resources and UL/CSA certification stated by manufacturer; confirm local kit supply.',caution:'Designed for specified Regal picket/glass assemblies. Follow its controller and strip limits; not generic tape or a substitute in-lite circuit.',sourceUrl:'https://regalideas.com/products/led_system/',availabilityUrl:'https://regalideas.com/resources/downloads/'},
  {id:'dekor-lighting',brand:'DEKOR',category:'Lighting systems',name:'Deck, post, stair and accent lighting',components:'DEK-DOT recessed lights, stair lights, post caps/lamps, rail and strip-lighting families.',availability:'Manufacturer ships to Canada; confirm Ontario stock, import costs and exact product approvals.',caution:'Use the selected family’s specified power supply, connectors and controls. Canadian shipping does not prove every variant’s local approval or compatibility.',sourceUrl:'https://www.dekorlighting.com/pages/installation-instructions',availabilityUrl:'https://www.dekorlighting.com/pages/shipping'},
  {id:'sunbelly-privacy',brand:'Sunbelly',category:'Privacy screens',name:'Aluminum privacy screen systems',components:'Standard and Shorty panels, posts, brackets, U-channel options and gates.',availability:'Ontario supplier advertises delivery; confirm current pattern, finish and stock.',caution:'Different brand and mounting geometry from HIDEAWAY. Require panel/post drawings, wind/anchor review and guard clearances; no guard-replacement approval assumed.',sourceUrl:'https://www.sunbelly.com/',availabilityUrl:'https://sunbelly.ca/'},
  {id:'hoft-privacy',brand:'HOFT',category:'Privacy screens',name:'Post-and-board privacy screen kits',components:'End, line and corner post kits, board spacers and screen accessories.',availability:'Canadian retail references on manufacturer site; confirm Ontario kit and stock.',caution:'The 72in screen instructions restrict installation above 60cm (23.62in) from ground and prohibit guard use. Research-only for elevated decks; verify the exact current kit manual.',sourceUrl:'https://www.hoftsolutions.com/sites/default/files/product/instructionshoft2020_72in_3.pdf',availabilityUrl:'https://www.hoftsolutions.com/'},
  {id:'trex-decking',brand:'Trex',category:'Decking & trim',name:'Composite decking and fascia',components:'Signature, Transcend Lineage, Transcend, Select, Enhance; fascia and compatible fastening.',availability:'Canadian catalogue; confirm Ontario collection, colour, length and stock.',caution:'Select thickness differs from several other collections. Check actual profiles before mixing walking surfaces.',sourceUrl:'https://www.trex.com/products/decking/',availabilityUrl:'https://ca.trex.com/find-trex/'},
  {id:'timbertech-decking',brand:'TimberTech / AZEK',category:'Decking & trim',name:'Advanced PVC and composite decking',components:'Vintage, Landmark, Harvest; Legacy, Reserve, Terrain+, Terrain, Prime, Prime+; fascia.',availability:'Canadian catalogue; local stock and special-order lead times vary.',caution:'PVC, composite and scalloped profiles require their own spans, gapping and fastening rules.',sourceUrl:'https://www.timbertech.ca/products/timbertech-composite-decking'},
  {id:'deckorators-decking',brand:'Deckorators',category:'Decking & trim',name:'Surestone and wood-plastic decking',components:'Voyage, Summit, Picture Frame; Vista, Altitude, Venture; fascia and risers.',availability:'Ontario project evidence; confirm current regional profiles and stock.',caution:'Surestone and wood-plastic collections are different installation systems; do not transfer one collection’s limits to another.',sourceUrl:'https://www.deckorators.com/pages/brochures',availabilityUrl:'https://www.deckorators.com/pages/in-the-news'},
  {id:'fiberon-decking',brand:'Fiberon',category:'Decking & trim',name:'Composite and PVC decking, fascia and risers',components:'Concordia, Sanctuary, Good Life, Paramount; associated trim and fastening.',availability:'US and Canada product guide; Ontario SKU supply requires confirmation.',caution:'Thin fascia and risers are non-structural. Check fascia-specific fasteners rather than ordinary decking plugs.',sourceUrl:'https://www.fiberondecking.com/pages/literature-library',availabilityUrl:'https://www.fiberondecking.com/pages/general-faqs'},
  {id:'trunorth-clubhouse',brand:'TruNorth / Clubhouse',category:'Decking & trim',name:'Ontario composite and PVC decking',components:'TruNorth composite decking; Clubhouse PVC decking and trim families.',availability:'Manufacturer in Brantford, Ontario; confirm exact variants and dealer stock.',caution:'Composite and PVC profiles need separate support and fastening rules. A material rating is not complete-assembly approval.',sourceUrl:'https://trunorthdecking.com/'},
  {id:'tiva-decking',brand:'TIVA',category:'Decking & trim',name:'TIVADEK PVC series and fascia',components:'Architectural, Reserve, Designer and Modern series; TIVADEK fascia.',availability:'Manufacturer Canadian office in Mississauga; confirm collection and stock.',caution:'Use actual fascia and board dimensions, not generic composite assumptions; obtain the current installation guide.',sourceUrl:'https://tivabp.com/tivadek/'},
  {id:'evalast-decking',brand:'Eva-Last',category:'Decking & trim',name:'Decking profiles and matching fastening',components:'Pioneer, Apex, Apex PLUS, Infinity; compatible trim, HULK and CHAIN systems.',availability:'Canadian catalogue and Ontario supplier delivery evidence; confirm each profile.',caution:'Span and clip compatibility are profile-specific. A wide Apex PLUS board’s limits do not apply to every collection.',sourceUrl:'https://www.eva-last.ca/information-centre/installation/',availabilityUrl:'https://www.deckmasters.ca/decking_eva-last_infinity.html'},
  {id:'craftbilt-decking',brand:'Craft-Bilt',category:'Decking & trim',name:'Interlocking aluminum decking',components:'Aluminum boards, edge and starter details, integral water-management channels.',availability:'Manufacturer states decking is made in Ontario; confirm order lengths and finish.',caution:'Board direction and drainage details matter. Not a standalone roofing solution over living space.',sourceUrl:'https://craft-bilt.com/products/aluminum-decking/'},
  {id:'duradek-membrane',brand:'Duradek / Durarail',category:'Drainage',name:'Vinyl waterproof deck surface',components:'Membrane, substrate and flashing assembly; companion aluminum railing systems.',availability:'Southern Ontario applicator network identified by manufacturer.',caution:'Requires trained authorized installation and coordinated substrate, wall and post-penetration details; not spaced deck boards.',sourceUrl:'https://duradek.com/southontario/'},
  {id:'micropro-lumber',brand:'MicroPro Sienna',category:'Framing & connections',name:'Pressure-treated wood system',components:'Treated decking, framing and posts from independent treating producers; field-cut protection.',availability:'Canadian treatment system and retailer network; confirm local lumber grade and treatment.',caution:'Store species, grade and treatment use category separately. Above-ground treatment is not ground-contact treatment.',sourceUrl:'https://microprosienna.com/advanced-treating-technology/',availabilityUrl:'https://microprosienna.com/'},
  {id:'regal-railing',brand:'Regal ideas',category:'Railings & gates',name:'Aluminum and glass guard systems',components:'Picket and tempered-glass systems, CrystalRail, posts, gates, mounting brackets and handrails.',availability:'Canadian product options documented; confirm Ontario supplier and exact kit.',caution:'Use the selected system’s spacing, glass sizes, stair-angle and anchor details. Generic Canada claims are not site approval.',sourceUrl:'https://regalideas.com/products/',availabilityUrl:'https://regalideas.com/resources/faq/'},
  {id:'vista-railing',brand:'Vista Railings',category:'Railings & gates',name:'Picket, glass, cable and gate systems',components:'Posts, deck/stair rails, drink-rail adapters, handrails and matched gates.',availability:'Manufacturer names a stocking dealer in Cookstown, Ontario; exact stock varies.',caution:'Accessories are system-specific. Match gate size, infill and swing; local guard and pool-enclosure requirements still need review.',sourceUrl:'https://www.vistarailings.com/railing-products/',availabilityUrl:'https://www.vistarailings.com/product/gates/'},
  {id:'century-railing',brand:'Century Aluminum Railings',category:'Railings & gates',name:'Aluminum, glass and pipe rails',components:'Picket and framed-glass guards, pipe rails, posts and associated hardware.',availability:'Canadian dealer network; confirm Ontario product and stock.',caution:'Use system-specific glass, anchors, post spacing and mounting details. Matching colours do not imply compatible parts.',sourceUrl:'https://www.centuryrailings.com/'},
  {id:'peak-railblazers',brand:'Peak RailBlazers',category:'Railings & gates',name:'Modular aluminum railing',components:'Line/corner/end/stair posts; pickets, glass, stair kits, continuous handrail and fascia brackets.',availability:'Canadian product and assembly documents; confirm Ontario retailer stock.',caution:'Level and stair infill differ. Obtain current assembly documentation rather than treating a dated report as blanket approval.',sourceUrl:'https://peakproducts.com/en-ca/faq/'},
  {id:'centennial-custom',brand:'Centennial Railings',category:'Railings & gates',name:'Custom exterior aluminum railing',components:'Custom-order exterior posts, handrails and railing assemblies.',availability:'Richmond Hill manufacturer serving Southern Ontario.',caution:'Quote-required custom assembly. Supplier drawings and attachment review are needed; no standardized retail kit assumed.',sourceUrl:'https://centennialrailings.ca/'},
  {id:'fortress-evolution',brand:'Fortress',category:'Framing & connections',name:'Evolution steel framing',components:'Steel joists, beams, posts, blocking, brackets and stair framing.',availability:'Ontario builder evidence and Ontario technical resources; confirm supplier stock.',caution:'Use current OBC-specific report and project loads. Older OBC 2012 letters do not establish current blanket approval.',sourceUrl:'https://www.fortressbp.com/resources?ProductTypeFilter=3',availabilityUrl:'https://fortressbp.com/blog/637/wood-versus-steel-deck-framing'},
  {id:'simpson-connections',brand:'Simpson Strong-Tie',category:'Framing & connections',name:'Deck connectors and decorative hardware',components:'Hangers, bases, caps, ledger/lateral connections, guard-post hardware and Outdoor Accents.',availability:'Canadian operations include Ontario; verify the exact connector and fastener supply.',caution:'Connector model, coating, substrate and specified fasteners form one assembly. Generic deck screws are not a substitute.',sourceUrl:'https://www.strongtie.com/solutions/deckcenter/index',availabilityUrl:'https://www.strongtie.com/international/canada'},
  {id:'pylex-components',brand:'Pylex',category:'Framing & connections',name:'Stair and deck hardware',components:'Steel/aluminum stringers and treads, deck supports, post bases, caps and gate hardware.',availability:'Canadian manufacturer catalogue; exact Ontario stock not checked.',caution:'Prefab stringers have fixed geometry and support conditions. Consumer supports/piles are not automatically suitable frost foundations.',sourceUrl:'https://pylex.com/en/products/'},
  {id:'fastenmaster-systems',brand:'FastenMaster',category:'Fasteners & protection',name:'Cortex and structural fastening',components:'Deck/trim/fascia plug systems, structural screws and frame-protection products.',availability:'Confirm Ontario distributor and the exact board-compatible kit.',caution:'Match board profile, thickness and colour. Deck, trim and fascia kits differ; check decking-maker approval as well.',sourceUrl:'https://www.fastenmaster.com/technical-documents'},
  {id:'starborn-systems',brand:'Starborn',category:'Fasteners & protection',name:'Deck, fascia and metal-framing fasteners',components:'CAP-TOR xd, Clip&Rip, PRO PLUG, Deckfast and structural screw families.',availability:'Ontario supplier advertises delivery; confirm each kit and finish.',caution:'Use the specified screw, setting tool and plug together. Metal framing and scalloped/fascia profiles need the appropriate system.',sourceUrl:'https://starbornindustries.com/resources/',availabilityUrl:'https://www.deckmasters.ca/fasteners_DF-metal.html'},
  {id:'camo-systems',brand:'CAMO',category:'Fasteners & protection',name:'Hidden clips, screws and protection',components:'EDGE, WEDGECLIP, WEDGEMETAL, starter clips, edge/structural screws and joist/ledger tape.',availability:'Canadian catalogue; Ontario stock requires confirmation.',caution:'Match clip to joist material and board angle. EDGE’s wood/90-degree application is not a universal metal/diagonal rule.',sourceUrl:'https://www.camofasteners.ca/products/clips/edge-clips/'},
  {id:'trex-rainescape',brand:'Trex RainEscape',category:'Drainage',name:'Above-joist water management',components:'Water-collection system and associated drainage/sealing components.',availability:'Canadian product page; confirm Ontario supplier and component stock.',caution:'Needs discharge, gutter, wall-flashing and penetration coordination. Separate from decking and below-joist ceilings.',sourceUrl:'https://ca.trex.com/products/rainescape/'},
  {id:'timbertech-dryspace',brand:'TimberTech',category:'Drainage',name:'DrySpace under-deck water management',components:'Under-deck panels, receivers and associated trim/drainage details.',availability:'Manufacturer installation resources available; confirm Ontario supply.',caution:'Check joist bays, beams, run limits, ventilation and outlets. Not an interchangeable RainEscape or roof-membrane assembly.',sourceUrl:'https://www.timbertech.com/resources/installation-guides/'},
];
