import {lazy,Suspense,useEffect,useLayoutEffect,useRef,useState,type PointerEvent,type RefObject} from 'react';
import {createPortal} from 'react-dom';
import type {PatioInlay,YardFeature} from './types';
import type {PlanPoint} from './lib/deckGeometry';
import type {PlanFrame} from './ConstructionPlan';
import {patioInlayFeature,patioInlayPlans,patioInlayProblem,PATIO_INLAY_LIMITS} from './patioInlays';
import {HARDSCAPE_PRODUCTS,hardscapeBody,hardscapeProduct} from './hardscapeCatalogue';
import {PATIO_PRODUCTS} from './yardSettings';
import './PatioInlayEditor.css';
const HardscapePicker=lazy(()=>import('./HardscapePicker'));
const SHAPES:[PatioInlay['shape'],string][]=[['rectangle','Rectangle'],['diamond','Diamond'],['circle','Circle'],['compass','Compass rose'],['band','Accent band'],['custom','Sketch my own']];
const norm=(n:number)=>(n%360+360)%360;
const transform=(p:PlanPoint,angle:number)=>{const a=angle*Math.PI/180;return{x:p.x*Math.cos(a)-p.y*Math.sin(a),y:p.x*Math.sin(a)+p.y*Math.cos(a)};};
const local=(f:YardFeature,p:PlanPoint)=>transform({x:p.x-f.xFt*12,y:p.y-f.zFt*12},-f.rotationDeg);
const world=(f:YardFeature,p:PlanPoint)=>{const q=transform(p,f.rotationDeg);return{x:q.x+f.xFt*12,y:q.y+f.zFt*12};};
const xy=(p:PlanPoint[])=>p.map(q=>`${q.x},${q.y}`).join(' ');
function ExactNumber({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void}){
 const [draft,setDraft]=useState(String(Math.round(value*1000)/1000));useEffect(()=>setDraft(String(Math.round(value*1000)/1000)),[value]);
 return <label><span>{label}</span><input aria-label={label} type="number" step="0.1" min={min} max={max} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft);if(draft.trim()&&Number.isFinite(n)&&n>=min&&n<=max)onChange(n);else setDraft(String(value));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
interface Props {feature:YardFeature;onChange:(next:YardFeature)=>void;frame?:PlanFrame;viewZoom?:number;controlHost?:RefObject<HTMLDivElement|null>;disabled?:boolean;onStatus?:(s:string)=>void;onActiveChange?:(active:boolean)=>void}
interface Drag {pointer:number;inlay:PatioInlay;start:PlanPoint;point?:number;next?:PatioInlay}

/** Shapes are patio-local; all canvas gestures commit once on release, matching the deck editor. */
export default function PatioInlayEditor({feature,onChange,frame,viewZoom=1,controlHost,disabled=false,onStatus,onActiveChange}:Props){
 const inlays=feature.inlays??[],[selectedId,setSelectedId]=useState(''),[shape,setShape]=useState<PatioInlay['shape']>('rectangle'),[armed,setArmed]=useState(false),[sketch,setSketch]=useState<PlanPoint[]|null>(null),[cursor,setCursor]=useState<PlanPoint|null>(null),[preview,setPreview]=useState<PatioInlay|null>(null),[message,setMessage]=useState(''),[materials,setMaterials]=useState(false),[rotation,setRotation]=useState(0),[host,setHost]=useState<HTMLDivElement|null>(null);
 const moveHandle=useRef<HTMLButtonElement>(null),box=useRef<HTMLDivElement>(null),svg=useRef<SVGSVGElement>(null),drag=useRef<Drag|null>(null),tap=useRef<{pointer:number;x:number;y:number}|null>(null),active=useRef(new Set<number>()),[size,setSize]=useState({w:0,h:0});
 const selected=inlays.find(i=>i.id===selectedId),displayFeature=preview?{...feature,inlays:inlays.map(i=>i.id===preview.id?preview:i)}:feature,plans=patioInlayPlans(displayFeature);
 const announce=(s:string)=>{setMessage(s);onStatus?.(s);};
 const cancel=()=>{drag.current=null;tap.current=null;setPreview(null);setArmed(false);setSketch(null);setCursor(null);};
 useLayoutEffect(()=>setHost(controlHost?.current??null),[controlHost]);
 useLayoutEffect(()=>{const el=box.current;if(!el)return;const measure=()=>setSize({w:el.clientWidth,h:el.clientHeight});measure();const ro=new ResizeObserver(measure);ro.observe(el);return()=>ro.disconnect();},[frame?.viewBox]);
 useEffect(()=>{cancel();setSelectedId('');setMaterials(false);setMessage('');},[feature.id]);
 useEffect(()=>{cancel();},[feature]);
 useEffect(()=>{if(disabled){cancel();setSelectedId('');}},[disabled]);
 useEffect(()=>onActiveChange?.(armed||sketch!==null||!!selected),[armed,sketch!==null,selected?.id,onActiveChange]);
 useEffect(()=>()=>onActiveChange?.(false),[onActiveChange]);
 useEffect(()=>setRotation(selected?.rotationDeg??0),[selected?.id,selected?.rotationDeg]);
 useLayoutEffect(()=>{if(selectedId&&frame)moveHandle.current?.focus({preventScroll:true});},[selectedId]);
 useEffect(()=>{const down=(e:globalThis.PointerEvent)=>{active.current.add(e.pointerId);if(active.current.size>1){drag.current=null;tap.current=null;setPreview(null);}};const up=(e:globalThis.PointerEvent)=>active.current.delete(e.pointerId);document.addEventListener('pointerdown',down,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',up,true);return()=>{document.removeEventListener('pointerdown',down,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',up,true);};},[]);
 const save=(next:PatioInlay[])=>{onChange({...feature,inlays:next.length?next:undefined});};
 const patch=(i:PatioInlay,p:Partial<PatioInlay>)=>{const next={...i,...p},problem=patioInlayProblem(next);if(problem){announce(problem);return;}save(inlays.map(q=>q.id===i.id?next:q));announce(`${i.name} updated. Undo restores the previous detail.`);};
 const remove=(i:PatioInlay)=>{save(inlays.filter(q=>q.id!==i.id));setSelectedId('');setMaterials(false);announce(`${i.name} removed. Undo restores it.`);};
 const id=()=>{let n=1;while(inlays.some(i=>i.id===`patio-inlay-${n}`))n++;return `patio-inlay-${n}`;};
 const defaultStock=()=>{const thick=PATIO_PRODUCTS.find(p=>p.id===feature.productId)?.thicknessMm??60,preferred=hardscapeProduct('permacon-melville-60-slab'),compatible=(p:typeof HARDSCAPE_PRODUCTS[number])=>p.category!=='wall'&&p.finishes.some(f=>f.colors.length&&f.units.some(u=>hardscapeBody(u.role)&&u.heightMm===thick));const p=preferred&&compatible(preferred)?preferred:HARDSCAPE_PRODUCTS.find(compatible)!;const f=p.finishes.find(f=>f.colors.length&&f.units.some(u=>hardscapeBody(u.role)&&u.heightMm===thick))!,color=f.colors.find(c=>f.units.some(u=>hardscapeBody(u.role)&&u.heightMm===thick&&(!u.colorIds||u.colorIds.includes(c.id))))!,unit=f.units.find(u=>hardscapeBody(u.role)&&u.heightMm===thick&&(!u.colorIds||u.colorIds.includes(color.id)))!,recipe=f.patterns.find(r=>r.layout.cells.every(cell=>{const u=f.units.find(u=>u.id===cell.unitId);return u&&u.heightMm===thick&&(!u.colorIds||u.colorIds.includes(color.id));}));return {productId:p.id,color:color.hex??'#777777',hardscape:{finishId:f.id,colorId:color.id,unitId:recipe?.layout.cells[0].unitId??unit.id,patternId:recipe?.id??'running-bond',angleDeg:0,jointMm:recipe?(recipe.layout.jointMm??0):3}};};
 const create=(at:PlanPoint,kind=shape):PatioInlay=>({id:id(),name:SHAPES.find(s=>s[0]===kind)![1],shape:kind,xIn:at.x,yIn:at.y,widthIn:Math.min(kind==='band'?96:48,feature.widthFt*8),depthIn:Math.min(kind==='band'?12:48,feature.depthFt*8),rotationDeg:0,...(feature.hardscape?{productId:feature.productId,color:feature.color,hardscape:{...feature.hardscape}}:defaultStock())});
 const add=(i:PatioInlay)=>{const problem=patioInlayProblem(i);if(problem){announce(problem);return;}const plan=patioInlayPlans({...feature,inlays:[...inlays,i]}).at(-1);if(plan?.status!=='ok'){announce(plan?.message??'Place the inlay inside the patio, away from another inlay.');return;}save([...inlays,i]);setSelectedId(i.id);setMaterials(false);cancel();announce(`${i.name} placed. Drag it, choose its stone, or press Delete to remove it.`);};
 const start=()=>{if(inlays.length>=PATIO_INLAY_LIMITS.count){announce('A patio supports up to twelve inlays.');return;}if(!frame){announce('Open Plan → Patios & walls, select this patio, then choose Add patio inlay to place or sketch it.');return;}cancel();if(shape==='custom')setSketch([]);else setArmed(true);announce(shape==='custom'?'Click or tap straight segments. Right-click or Finish to close your inlay.':'Click or tap anywhere inside this patio to place the inlay. Escape cancels.');};
 const finish=()=>{if(!sketch||sketch.length<3){announce('Draw at least three corners to finish an inlay.');return;}const minX=Math.min(...sketch.map(p=>p.x)),maxX=Math.max(...sketch.map(p=>p.x)),minY=Math.min(...sketch.map(p=>p.y)),maxY=Math.max(...sketch.map(p=>p.y)),centre={x:(minX+maxX)/2,y:(minY+maxY)/2};add({...create(centre,'custom'),widthIn:maxX-minX,depthIn:maxY-minY,points:sketch.map(p=>({x:p.x-centre.x,y:p.y-centre.y}))});};
 const pointer=(e:{clientX:number;clientY:number})=>{const m=svg.current?.getScreenCTM();if(!m)throw Error('Wait for the plan to load.');const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return local(feature,{x:p.x,y:p.y});};
 const pointWorld=(i:PatioInlay,p:PlanPoint)=>world(feature,{x:i.xIn+transform(p,i.rotationDeg).x,y:i.yIn+transform(p,i.rotationDeg).y});
 const begin=(i:PatioInlay,e:PointerEvent,point?:number)=>{if(disabled||armed||sketch||active.current.size>1||e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);setSelectedId(i.id);drag.current={pointer:e.pointerId,inlay:i,start:pointer(e),point};};
 const move=(e:PointerEvent)=>{if(armed||sketch){setCursor(pointer(e));return;}const g=drag.current;if(!g||g.pointer!==e.pointerId)return;e.preventDefault();const p=pointer(e),delta={x:p.x-g.start.x,y:p.y-g.start.y};let next={...g.inlay,xIn:g.inlay.xIn+delta.x,yIn:g.inlay.yIn+delta.y};if(g.point!==undefined&&g.inlay.points){const d=transform(delta,-g.inlay.rotationDeg),points=g.inlay.points.map((p,n)=>n===g.point?{x:p.x+d.x,y:p.y+d.y}:p);const xs=points.map(p=>p.x),ys=points.map(p=>p.y);next={...g.inlay,points,widthIn:Math.max(...xs)-Math.min(...xs),depthIn:Math.max(...ys)-Math.min(...ys)};}g.next=next;setPreview(next);};
 const end=(e:PointerEvent)=>{const g=drag.current;if(!g||g.pointer!==e.pointerId)return;move(e);drag.current=null;setPreview(null);if(g.next&&JSON.stringify(g.next)!==JSON.stringify(g.inlay))patch(g.inlay,g.next);};
 const placing=armed||sketch!==null,scale=frame?Math.min(size.w/frame.w,size.h/frame.h):0,ox=frame?(size.w-frame.w*scale)/2:0,oy=frame?(size.h-frame.h*scale)/2:0;
 const at=(p:PlanPoint)=>({left:ox+(p.x-(frame?.x??0))*scale,top:oy+(p.y-(frame?.y??0))*scale,transform:`translate(-50%,-50%) scale(${1/viewZoom})`});
 const resize=(i:PatioInlay,key:'widthIn'|'depthIn',n:number)=>{const before=i[key],axis=key==='widthIn'?'x':'y';patch(i,{[key]:n,...(i.points?{points:i.points.map(p=>({...p,[axis]:p[axis]*n/before}))}:{})});};
 const controls=<section className="dd-patio-inlays" aria-label="Patio inlays" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancel();setSelectedId('');setMaterials(false);}}}>
  <div className="dd-patio-inlays-title"><h4>Patio inlays</h4><span>{inlays.length}/12</span></div><p>{frame?'Place an accent anywhere, with its own stone, size, pattern and direction. Choose a preset or sketch your own outline.':'To add or sketch an inlay, open Plan → Patios & walls and select this patio. Edit existing inlays below.'}</p>
  <div className="dd-patio-inlay-add" data-inspector={!frame||undefined}>{frame&&<label>Inlay shape<select aria-label="Patio inlay shape" value={shape} disabled={placing||disabled} onChange={e=>setShape(e.target.value as PatioInlay['shape'])}>{SHAPES.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}<button type="button" className="dd-patio-inlay-primary" disabled={disabled||inlays.length>=PATIO_INLAY_LIMITS.count||placing} onClick={start}>{frame?'Add patio inlay':'Place inlay on the plan'}</button></div>
  {placing&&<div className="dd-patio-inlay-pending"><strong>{sketch?`Sketch inlay · ${sketch.length} corners`:'Tap the patio to place it'}</strong>{sketch&&<><button type="button" disabled={sketch.length<3} onClick={finish}>Finish patio inlay</button><button type="button" disabled={!sketch.length} onClick={()=>setSketch(sketch.slice(0,-1))}>Undo last corner</button></>}<button type="button" onClick={cancel}>Cancel inlay</button></div>}
  {!!inlays.length&&<label className="dd-patio-inlay-select">Selected patio inlay<select aria-label="Selected patio inlay" value={selected?.id??''} onChange={e=>{setSelectedId(e.target.value);setMaterials(false);setMessage('');}}><option value="">Choose an inlay…</option>{inlays.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}
  {selected&&<><div className="dd-patio-inlay-fields"><ExactNumber label="Patio inlay width (in)" value={selected.widthIn} min={1} max={240} onChange={n=>resize(selected,'widthIn',n)}/><ExactNumber label="Patio inlay depth (in)" value={selected.depthIn} min={1} max={240} onChange={n=>resize(selected,'depthIn',n)}/><ExactNumber label="Patio inlay across (in)" value={selected.xIn} min={-1200} max={1200} onChange={xIn=>patch(selected,{xIn})}/><ExactNumber label="Patio inlay out (in)" value={selected.yIn} min={-1200} max={1200} onChange={yIn=>patch(selected,{yIn})}/><ExactNumber label="Patio inlay rotation (°)" value={selected.rotationDeg} min={0} max={360} onChange={n=>patch(selected,{rotationDeg:norm(n)})}/></div>
   <label className="dd-patio-inlay-rotate">Turn the inlay · {rotation}°<input aria-label="Rotate patio inlay" type="range" min="0" max="360" value={rotation} onChange={e=>{const n=Number(e.target.value);setRotation(n);setPreview({...selected,rotationDeg:norm(n)});}} onPointerUp={()=>{setPreview(null);patch(selected,{rotationDeg:norm(rotation)});}} onPointerCancel={()=>{setPreview(null);setRotation(selected.rotationDeg);}} onKeyUp={()=>{setPreview(null);patch(selected,{rotationDeg:norm(rotation)});}}/></label><div className="dd-patio-inlay-actions"><button type="button" onClick={()=>patch(selected,{rotationDeg:norm(selected.rotationDeg+45)})}>Turn +45°</button><button type="button" onClick={()=>patch(selected,{rotationDeg:norm(selected.rotationDeg+90)})}>Turn +90°</button><button type="button" onClick={()=>setMaterials(!materials)} aria-expanded={materials}>Choose inlay stone &amp; pattern</button><button type="button" onClick={()=>remove(selected)}>Delete patio inlay</button><button type="button" onClick={()=>{cancel();setSelectedId('' );setMaterials(false);}}>Finish inlay editing</button></div>
   {materials&&<Suspense fallback={<p role="status">Loading inlay materials…</p>}><HardscapePicker feature={patioInlayFeature(feature,selected)} onChange={p=>patch(selected,{...(p.productId?{productId:p.productId}:{}),...(p.color?{color:p.color}:{}),...(p.hardscape?{hardscape:p.hardscape}:{})})}/></Suspense>}
   <p className="dd-patio-inlay-state" data-invalid={plans.find(p=>p.inlay.id===selected.id)?.status!=='ok'||undefined}>{plans.find(p=>p.inlay.id===selected.id)?.message}</p><p>Drag the shape to move it. Select it and press Delete to remove it. Arrows move 1 inch; Shift moves 1 foot. Custom corners can be pulled separately.</p>
  </>}
  {message&&<p role="status">{message}</p>}<p className="dd-patio-inlay-quote">Accent stones, cuts and installation remain visible in the quantity takeoff and quote scope.</p>
 </section>;
 if(!frame)return controls;
 const previewInlay=armed&&cursor?create(cursor):null,previewPlan=previewInlay?patioInlayPlans({...feature,inlays:[...inlays,previewInlay]}).at(-1):null;
 return <><div ref={box} className="dd-patio-inlay-overlay" data-placing={placing||undefined} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancel();setSelectedId('');setMaterials(false);}else if(e.key==='Enter'&&sketch){e.preventDefault();finish();}}}>
  <svg ref={svg} viewBox={frame.viewBox} data-plan-editor-ui aria-label={placing?'Patio inlay placement surface':undefined} aria-hidden={!placing} tabIndex={placing?0:undefined} onPointerMove={move} onPointerDown={e=>{if(!placing||disabled||active.current.size>1||e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);tap.current={pointer:e.pointerId,x:e.clientX,y:e.clientY};}} onPointerUp={e=>{const t=tap.current;tap.current=null;if(!t||t.pointer!==e.pointerId||Math.hypot(e.clientX-t.x,e.clientY-t.y)>8||active.current.size>1)return;const p=pointer(e);if(sketch){if(sketch.length>=64){announce('Finish your shape before adding more than 64 corners.');return;}setSketch([...sketch,p]);}else if(armed)add(create(p));}} onContextMenu={e=>{if(placing){e.preventDefault();e.stopPropagation();if(sketch)finish();}}} onPointerCancel={()=>{tap.current=null;setCursor(null);}}>
   {plans.map(p=><polygon key={p.inlay.id} className="dd-patio-inlay-outline" data-selected={p.inlay.id===selectedId||undefined} data-invalid={p.status!=='ok'||undefined} points={xy(p.outline)} onPointerDown={e=>begin(p.inlay,e)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setPreview(null);}} onLostPointerCapture={()=>{drag.current=null;setPreview(null);}}/>)}
   {previewPlan&&<polygon className="dd-patio-inlay-preview" data-invalid={previewPlan.status!=='ok'||undefined} points={xy(previewPlan.outline)}/>}
   {sketch&&<polyline className="dd-patio-inlay-preview" points={xy([...sketch,...(cursor?[cursor]:[])].map(p=>world(feature,p)))}/>}
  </svg>
  {selected&&!placing&&scale>0&&<button ref={moveHandle} type="button" className="dd-patio-inlay-handle" data-plan-editor-ui style={at(world(feature,{x:preview?.xIn??selected.xIn,y:preview?.yIn??selected.yIn}))} aria-label={`Move patio inlay ${selected.name}`} onPointerDown={e=>begin(selected,e)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setPreview(null);}} onLostPointerCapture={()=>{drag.current=null;setPreview(null);}} onKeyDown={e=>{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();e.stopPropagation();remove(selected);}else{const delta=({ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]} as Record<string,number[]>)[e.key];if(delta){e.preventDefault();e.stopPropagation();const n=e.shiftKey?12:1;patch(selected,{xIn:selected.xIn+delta[0]*n,yIn:selected.yIn+delta[1]*n});}}}}>Inlay</button>}
  {selected?.points&&!placing&&scale>0&&selected.points.map((p,n)=><button key={n} type="button" className="dd-patio-inlay-point" data-plan-editor-ui aria-label={`Patio inlay corner ${n+1}`} style={at(pointWorld(preview??selected,(preview??selected).points?.[n]??p))} onPointerDown={e=>begin(selected,e,n)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setPreview(null);}} onLostPointerCapture={()=>{drag.current=null;setPreview(null);}}/>)}
 </div>{host?createPortal(controls,host):null}</>;
}
