import type {DeckData} from './types';
import type {DeckTakeoff} from './deckTakeoff';
import type {PlanPoint} from './lib/deckGeometry';
import type {SitePlane,SiteSurface} from './siteSurface';
import type {PoolFeature} from './poolTypes';
import {poolValidationProblem} from './poolTypesRuntime';
import {registerPoolModelRuntime,type PoolFeatureModel,type PoolSolid,type PoolFormation} from './poolModel';
import {poolOutline,poolLocalBounds,poolWorldPoint,poolClip,poolArea,poolOffset,poolFloorPlane,poolFloorElevation,poolLocalPoint,poolPerimeterIn,poolWaterElevation,poolSignedArea,poolPermanentExclusion} from './poolGeometry';
import {arcGeometry} from './circularArcs';
import {yardSolidCells,yardRectangle,type YardFeatureModel,type YardBox} from './yardModel';
import {abovePlane,subtractPlanes,planeVolume,planeAt,belowPlane,planeNormalScale,applyPlaneFormation,patioTopPlane} from './yardElevationGeometry';
import {getTerrainConfig} from './yardSettings';
import {createSiteSurface,integrateSiteExcavation} from './siteSurface';
import {yardPathEnvelope,yardWallPath,yardFeatureOutline} from './yardPathGeometry';
import {hardscapeSelection} from './hardscapeCatalogue';
import {PAVER_BRANDS} from '../../data/carrPrices';
import baseline from '../../data/engine-baseline.json';
import {getHousePlacement} from './housePlacement';
import {hasHouseBlocks,houseOutline} from './houseFootprint';
const flat=(h:number):SitePlane=>({x:0,z:0,constant:h});
const volume=(ps:PlanPoint[][],top:SitePlane,bottom:SitePlane)=>yardSolidCells(ps).reduce((n,p)=>n+Math.max(0,planeVolume(abovePlane(p,subtractPlanes(top,bottom)),subtractPlanes(top,bottom)))/46656,0);
const strip=(p:PoolFeature,lo:number,hi:number)=>{const b=poolLocalBounds(p);return [poolWorldPoint(p,{x:b.minX-1000,y:lo}),poolWorldPoint(p,{x:b.maxX+1000,y:lo}),poolWorldPoint(p,{x:b.maxX+1000,y:hi}),poolWorldPoint(p,{x:b.minX-1000,y:hi})];};
const solidWhenHoled=(polys:PlanPoint[][])=>polys.some(p=>poolSignedArea(p)<0)?yardSolidCells(polys):polys;
function floorSections(p:PoolFeature,footprints:PlanPoint[][]){const b=poolLocalBounds(p);return p.depthProfile.slice(0,-1).flatMap((station,i)=>solidWhenHoled(poolClip(footprints,[strip(p,i?b.minZ+station.stationIn:b.minZ-1000,i===p.depthProfile.length-2?b.maxZ+1000:b.minZ+p.depthProfile[i+1].stationIn)],'intersection')).map(polygon=>({polygon,plane:poolFloorPlane(p,i)})));}
function groundSections(data:DeckData,site:SiteSurface|undefined,footprints:PlanPoint[][],kind:'existing'|'proposed'='proposed'){const t=getTerrainConfig(data);return site?(kind==='existing'?site.existingTriangles:site.proposedTriangles).flatMap(f=>yardSolidCells(poolClip(footprints,[f.vertices.map(v=>({x:v.xIn,y:v.zIn}))],'intersection')).map(polygon=>({polygon,plane:f.plane}))):yardSolidCells(footprints).map(polygon=>({polygon,plane:{x:0,z:t.slopePct/100,constant:t.elevationIn}}));}
/** Shared authoritative patio formations are independent of individual paver
 * tessellation. A pool's working-zone backfill finishes below future paving. */
function patioFormations(data:DeckData,site:SiteSurface|undefined){const terrain=getTerrainConfig(data),holes=poolClip((data.pools??[]).filter(p=>p.enabled).flatMap(poolPermanentExclusion)),house=getHousePlacement(data);let occupied=data.houseVisible===false?[]:hasHouseBlocks(data)?houseOutline(data):[yardRectangle((house.x0+house.x1)/2,-house.depthIn/2,house.widthIn,house.depthIn)];const out:{polys:PlanPoint[][];plane:SitePlane}[]=[];for(const f of data.yardFeatures??[]){if(!f.enabled||f.kind!=='patio'||f.stoneSteps||f.stepAssembly)continue;const grade=site?site.sample(f.xFt*12,f.zFt*12):terrain.elevationIn+f.zFt*12*terrain.slopePct/100;if(grade===undefined)continue;const footprints=poolClip(yardFeatureOutline(f),[...occupied,...holes],'difference'),top=patioTopPlane(f,grade),scale=planeNormalScale(top),thickness=(hardscapeSelection(f)?.unit.heightMm??PAVER_BRANDS.find(p=>p.id===f.productId)?.thicknessMm??60)/25.4,depth=thickness+1+baseline.facts.baseDepthIn;occupied=poolClip([...occupied,...footprints]);out.push({polys:poolClip(footprints.map(p=>p.map(v=>({x:v.x+top.x*depth/scale,y:v.y+top.z*depth/scale}))),holes,'difference'),plane:belowPlane(top,depth)});}return out;}
function excavate(data:DeckData,site:SiteSurface|undefined,formations:PoolFormation[]){if(site){const owners=new Set(formations.map(f=>f.featureId));return integrateSiteExcavation(site,formations.map(f=>({featureId:f.featureId,polygons:[f.polygon],bottomIn:f.bottomIn,formationPlane:f.formationPlane}))).regions.filter(r=>owners.has(r.featureId));}const t=getTerrainConfig(data),ground={x:0,z:t.slopePct/100,constant:t.elevationIn};let cells:Parameters<typeof applyPlaneFormation>[0]=[];for(const f of formations)cells=applyPlaneFormation(cells,[f.polygon],f.formationPlane,f.featureId,poolClip,yardSolidCells);return cells.flatMap(c=>{const delta=subtractPlanes(ground,c.plane),polygon=abovePlane(c.polygon,delta),volumeYd3=Math.max(0,planeVolume(polygon,delta))/46656;return volumeYd3>1e-9?[{featureId:c.featureId,polygon,bottomIn:planeAt(c.plane,polygon[0].x,polygon[0].y),formationPlane:c.plane,volumeYd3}]:[];});}
/** Build only derived construction; saved outlines are never modified. */
function buildPool(data:DeckData,p:PoolFeature,deck:DeckTakeoff|undefined,site:SiteSurface|undefined):PoolFeatureModel{
 const pending:string[]=[],warnings:string[]=[],solids:PoolSolid[]=[],formationRegions:PoolFormation[]=[],copingStock:PoolFeatureModel['copingStock']=[],problem=poolValidationProblem(p);
 if(problem)throw Error(`${p.name}: ${problem}`);
 const assembly=p.assembly,wall=assembly?.wallThicknessIn??0,floorThickness=assembly?.floorThicknessIn??0,baseDepth=assembly?.baseDepthIn??0,clearance=assembly?.workingClearanceIn??0,collarWidth=assembly?.collarWidthIn??0,collarDepth=assembly?.collarDepthIn??0,coping=p.coping;
 const openingFootprints=poolClip([poolOutline(p)]),structureFootprints=poolOffset(openingFootprints,wall),structureRing=poolClip(structureFootprints,openingFootprints,'difference'),copingOuter=poolOffset(openingFootprints,coping?coping.widthIn-coping.overhangIn:wall),copingInner=poolOffset(openingFootprints,-(coping?.overhangIn??0)),copingFootprints=coping?poolClip(copingOuter,copingInner,'difference'):[],permanentExclusionFootprints=poolOffset(poolClip([...structureFootprints,...copingOuter]),coping?.transitionJointIn??0),deepExcavationFootprints=poolOffset(structureFootprints,clearance),floorRegions=floorSections(p,openingFootprints),waterElevationIn=poolWaterElevation(p),floorTopRegions=floorSections(p,structureFootprints),collarOuter=poolOffset(structureFootprints,collarWidth),collarFootprints=poolClip(collarOuter,structureFootprints,'difference'),excavationFootprints=poolClip([...deepExcavationFootprints,...collarFootprints,...copingOuter]),backfillFootprints=poolClip(deepExcavationFootprints,structureFootprints,'difference');
 const planning=assembly?.status!=='recorded';let coverageComplete=!site||site.extrema(excavationFootprints,'existing').complete&&site.extrema(excavationFootprints,'proposed').complete;
 if(planning)pending.push('Pool assembly is a generic planning envelope. Manufacturer installation dimensions and site engineering remain unverified.');
 if(!assembly||['wallThicknessIn','floorThicknessIn','baseDepthIn','workingClearanceIn','backfillMaterial','collarWidthIn','collarDepthIn'].some(k=>assembly[k as keyof typeof assembly]===undefined))pending.push('Pool structure, base, working clearance, backfill and collar inputs are incomplete; quantities are minimum/planning values.');
 if(assembly?.backfillMaterial==='supplier-specified')pending.push('Backfill material and compaction specification require the selected pool supplier.');
 if(!coping)pending.push('Coping product and dimensions are missing.');else if(!coping.verifiedForPool||coping.status==='planning')pending.push('Coping stock is a visual/planning proxy; manufacturer pool suitability and corner fabrication are unverified.');
 if(coping&&(coping.settingBedThicknessIn===undefined||!coping.settingBedMaterial||coping.settingBedMaterial==='supplier-specified'||!coping.supportSourceUrl&&!coping.supportNote))pending.push('Coping support, adhesive/mortar setting bed and bonding details require recorded supplier inputs. Transition backer rod/sealant supply and installation remain an explicit quote scope.');
 if(!coverageComplete)pending.push('Pool construction envelope extends beyond measured survey coverage. Excavation and backfill quantities are incomplete.');
 const add=(role:PoolSolid['role'],polygons:PlanPoint[][],top:SitePlane,bottom:SitePlane,color:string,stockId?:string)=>{for(const polygon of yardSolidCells(polygons)){const clipped=abovePlane(polygon,subtractPlanes(top,bottom));if(clipped.length)solids.push({id:`pool:${p.id}:${role}:${solids.length}`,role,polygon:clipped,topPlane:top,bottomPlane:bottom,color,planning:planning||role==='coping'&&(!coping?.verifiedForPool||coping.status==='planning'||!!p.curves?.length),...(stockId?{stockId}:{})});}};
 const quantities:Record<string,number>={openingAreaSqft:poolArea(openingFootprints),perimeterLf:poolPerimeterIn(p)/12,waterVolumeGal:0,waterVolumeYd3:0,floorAreaSqft:0,finishSqft:0,settingBedYd3:0,transitionJointLf:0,copingJointLf:0,structureYd3:0,baseYd3:0,collarYd3:0,backfillYd3:0,copingAreaSqft:poolArea(copingFootprints),copingPieces:0,copingCutPieces:0,excavationYd3:0,trenchExcavationYd3:0,plumbingLf:0,electricalLf:0,drainageLf:0};
 for(const section of floorRegions){const q=volume([section.polygon],flat(waterElevationIn),section.plane);quantities.waterVolumeYd3+=q;quantities.floorAreaSqft+=poolArea([section.polygon])*planeNormalScale(section.plane);add('water',[section.polygon],flat(waterElevationIn),section.plane,'#3b94ac');}
 quantities.waterVolumeGal=quantities.waterVolumeYd3*201.974;
 for(const section of floorTopRegions){const bottom=belowPlane(section.plane,floorThickness),baseBottom=belowPlane(bottom,baseDepth);if(floorThickness){add('floor',[section.polygon],section.plane,bottom,p.type==='concrete'?'#a4aaa7':p.type==='vinyl-liner'?'#4b94ad':'#70b2bd');quantities.structureYd3+=volume([section.polygon],section.plane,bottom);}if(baseDepth){add('base',[section.polygon],bottom,baseBottom,'#8a8b80');quantities.baseYd3+=volume([section.polygon],bottom,baseBottom);}const wallMask=poolClip([section.polygon],structureRing,'intersection');add('wall',wallMask,flat(p.copingTopElevationIn-(coping?.thicknessIn??0)-(coping?.settingBedThicknessIn??0)),section.plane,p.type==='concrete'?'#b6bfbd':'#73aaba');quantities.structureYd3+=volume(wallMask,flat(p.copingTopElevationIn-(coping?.thicknessIn??0)-(coping?.settingBedThicknessIn??0)),section.plane);}
 // The opening profile also defines excavation below the external structure and
 // working envelope. End-station planes extend only into their adjacent margin.
 for(const section of floorSections(p,deepExcavationFootprints)){const bottom=belowPlane(section.plane,floorThickness+baseDepth);formationRegions.push({featureId:`pool:${p.id}`,polygon:section.polygon,bottomIn:Math.min(...section.polygon.map(v=>planeAt(bottom,v.x,v.y))),formationPlane:bottom});}
 const collarTop=flat(p.copingTopElevationIn-(coping?.thicknessIn??0)-(coping?.settingBedThicknessIn??0)),collarBottom=flat(collarTop.constant-collarDepth),deepMaximum=Math.max(...formationRegions.flatMap(f=>f.polygon.map(v=>planeAt(f.formationPlane,v.x,v.y)))),shallowMask=(polys:PlanPoint[][],bottom:number)=>bottom>=deepMaximum-1e-8?poolClip(polys,deepExcavationFootprints,'difference'):polys;for(const polygon of yardSolidCells(shallowMask(collarFootprints,collarBottom.constant)))if(collarDepth)formationRegions.push({featureId:`pool:${p.id}`,polygon,bottomIn:collarBottom.constant,formationPlane:collarBottom});if(coping)for(const polygon of yardSolidCells(shallowMask(poolClip(copingFootprints,openingFootprints,'difference'),collarTop.constant)))formationRegions.push({featureId:`pool:${p.id}`,polygon,bottomIn:collarTop.constant,formationPlane:collarTop});if(floorRegions.some(f=>f.polygon.some(v=>planeAt(f.plane,v.x,v.y)>=collarTop.constant-1e-8)))pending.push('Coping/setting-bed underside meets or falls below a pool floor. Revise the depth or assembly connection; this interface is unresolved.');if(collarDepth&&collarWidth){add('collar',collarFootprints,collarTop,collarBottom,'#a4a7a0');quantities.collarYd3=volume(collarFootprints,collarTop,collarBottom);}
 for(const bottomSection of floorSections(p,backfillFootprints)){const bottom=belowPlane(bottomSection.plane,floorThickness+baseDepth);for(const topSection of groundSections(data,site,[bottomSection.polygon])){const masked=poolClip([topSection.polygon],collarFootprints,'intersection'),rest=poolClip([topSection.polygon],collarFootprints,'difference');add('backfill',rest,topSection.plane,bottom,'#b2a08b');quantities.backfillYd3+=volume(rest,topSection.plane,bottom);for(const cell of yardSolidCells(masked)){const top=abovePlane(cell,subtractPlanes(topSection.plane,collarBottom)),low=abovePlane(cell,subtractPlanes(collarBottom,topSection.plane)),above=abovePlane(cell,subtractPlanes(topSection.plane,collarTop));add('backfill',[top],collarBottom,bottom,'#b2a08b');add('backfill',[low],topSection.plane,bottom,'#b2a08b');add('backfill',[above],topSection.plane,collarTop,'#b2a08b');quantities.backfillYd3+=volume([top],collarBottom,bottom)+volume([low],topSection.plane,bottom)+volume([above],topSection.plane,collarTop);}}}
 for(const section of groundSections(data,site,poolClip(collarFootprints,deepExcavationFootprints,'difference'))){add('backfill',[section.polygon],section.plane,collarTop,'#b2a08b');}
 if(coping){const supported=poolClip(copingFootprints,openingFootprints,'difference'),settingTop=flat(p.copingTopElevationIn-coping.thicknessIn),settingBottom=flat(settingTop.constant-(coping.settingBedThicknessIn??0));if(coping.settingBedThicknessIn){add('setting-bed',supported,settingTop,settingBottom,'#a5a497');quantities.settingBedYd3=volume(supported,settingTop,settingBottom);}const transition=poolOffset(copingOuter,coping.transitionJointIn/2);quantities.transitionJointLf=transition.reduce((n,p)=>n+p.reduce((q,a,i)=>{const b=p[(i+1)%p.length];return q+Math.hypot(b.x-a.x,b.y-a.y);},0),0)/12;}
 // Finish area includes the complete basin floor and vertical wall perimeter.
 quantities.finishSqft=quantities.floorAreaSqft+openingFootprints.reduce((n,poly)=>n+poly.reduce((sum,a,i)=>{const b=poly[(i+1)%poly.length],u=poolLocalPoint(p,a).y-poolLocalBounds(p).minZ,v=poolLocalPoint(p,b).y-poolLocalBounds(p).minZ,cuts=[0,1];if(Math.abs(v-u)>1e-10)for(const d of p.depthProfile){const t=(d.stationIn-u)/(v-u);if(t>1e-8&&t<1-1e-8)cuts.push(t);}cuts.sort((a,b)=>a-b);for(let j=0;j+1<cuts.length;j++){const q=(t:number)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}),height=(t:number)=>p.copingTopElevationIn-(coping?.thicknessIn??0)-(coping?.settingBedThicknessIn??0)-poolFloorElevation(p,q(t));sum+=Math.hypot(b.x-a.x,b.y-a.y)*(cuts[j+1]-cuts[j])*(height(cuts[j])+height(cuts[j+1]))/288;}return sum;},0),0);
 if(coping){const length=coping.stockLengthIn;if(!length)pending.push('Coping stock length is missing; ordering count is pending.');else{
  let claimed:PlanPoint[][]=[];
  for(let edge=0;edge<p.outline.length;edge++){
   const a=p.outline[edge],b=p.outline[(edge+1)%p.outline.length],arc=p.curves?.find(c=>c.edge===edge),g=arc?arcGeometry(a,b,arc.bulgeIn):undefined,run=g?.lengthIn??Math.hypot(b.x-a.x,b.y-a.y);
   for(let station=-coping.widthIn;station<run+coping.widthIn;station+=length+coping.jointIn){
    const centre=station+length/2,t=Math.max(0,Math.min(1,centre/run));let local:PlanPoint,angle:number;
    if(g){const theta=Math.atan2(a.y-g.center.y,a.x-g.center.x)-Math.sign(arc!.bulgeIn)*g.sweep*t;local={x:g.center.x+g.radius*Math.cos(theta),y:g.center.y+g.radius*Math.sin(theta)};angle=theta-Math.sign(arc!.bulgeIn)*Math.PI/2;}else{local={x:a.x+(b.x-a.x)*centre/run,y:a.y+(b.y-a.y)*centre/run};angle=Math.atan2(b.y-a.y,b.x-a.x);}
    const world=poolWorldPoint(p,local),worldAngle=angle+p.rotationDeg*Math.PI/180,ux=Math.cos(worldAngle),uy=Math.sin(worldAngle),offset=coping.widthIn/2-coping.overhangIn,blank=yardRectangle(world.x+uy*offset,world.y-ux*offset,length,coping.widthIn,worldAngle),pieces=poolClip(poolClip([blank],copingFootprints,'intersection'),claimed,'difference');if(poolArea(pieces)<.00001)continue;
    const id=`pool:${p.id}:coping:${copingStock.length}`,cut=Math.abs(poolArea(pieces)-length*coping.widthIn/144)>.001;copingStock.push({id,pieces:1,lengthIn:length,widthIn:coping.widthIn,thicknessIn:coping.thicknessIn,cut,unsupported:!!arc,polygons:pieces});add('coping',pieces,flat(p.copingTopElevationIn),flat(p.copingTopElevationIn-coping.thicknessIn),coping.color??'#b6ad99',id);claimed=poolClip([...claimed,...pieces]);
   }
  }
  const remainder=poolClip(copingFootprints,claimed,'difference');if(poolArea(remainder)>.02){pending.push('Coping corners or curved transitions cannot be filled by the selected rigid stock layout; special cuts/corner pieces remain pending.');add('coping',remainder,flat(p.copingTopElevationIn),flat(p.copingTopElevationIn-coping.thicknessIn),coping.color??'#b6ad99');}if(p.curves?.length)pending.push('Curved coping requires supplier-approved cut templates; displayed pieces are planning cuts.');quantities.copingPieces=copingStock.length;quantities.copingJointLf=copingStock.length*coping.widthIn/12;quantities.copingCutPieces=copingStock.filter(s=>s.cut).length;
 }}
 // Resolve the loose backfill before returning any public model. Render-first,
 // estimate-first and export-first consumers therefore see identical geometry.
 const pavingFloors=patioFormations(data,site),backfill=solids.filter(s=>s.role==='backfill'),other=solids.filter(s=>s.role!=='backfill');
 for(const solid of backfill){let parts:Prism[]=[solid];if(coping)parts=subtractBand(parts,copingFootprints,flat(p.copingTopElevationIn),flat(p.copingTopElevationIn-coping.thicknessIn));if(coping?.settingBedThicknessIn)parts=subtractBand(parts,poolClip(copingFootprints,openingFootprints,'difference'),flat(p.copingTopElevationIn-coping.thicknessIn),flat(p.copingTopElevationIn-coping.thicknessIn-coping.settingBedThicknessIn));for(const f of pavingFloors)parts=lowerPrisms(parts,f.polys,f.plane);other.push(...parts.map((part,i)=>({...solid,...part,id:`${solid.id}:paving:${i}`})));}solids.splice(0,solids.length,...other);quantities.backfillYd3=solids.filter(s=>s.role==='backfill').reduce((n,s)=>n+prismVolume(s),0);
 const poolOnly=excavate(data,site,formationRegions);quantities.excavationYd3=poolOnly.reduce((n,r)=>n+r.volumeYd3,0);
 for(const trench of p.serviceTrenches??[]){const footprints=poolClip(yardPathEnvelope(trench.points,trench.widthIn));if(site&&(!site.extrema(footprints).complete||!site.extrema(footprints,'existing').complete)){coverageComplete=false;pending.push(`${trench.id}: service trench survey coverage is incomplete.`);}for(const region of groundSections(data,site,footprints)){const bottom={...region.plane,constant:region.plane.constant-trench.depthIn};formationRegions.push({featureId:`pool:${p.id}:trench:${trench.id}`,polygon:region.polygon,bottomIn:Math.min(...region.polygon.map(v=>planeAt(bottom,v.x,v.y))),formationPlane:bottom});}quantities[`${trench.service}Lf`]+=trench.points.slice(1).reduce((n,b,i)=>n+Math.hypot(b.x-trench.points[i].x,b.y-trench.points[i].y),0)/12;}
 const combined=p.serviceTrenches?.length?excavate(data,site,formationRegions):poolOnly;quantities.trenchExcavationYd3=Math.max(0,combined.reduce((n,r)=>n+r.volumeYd3,0)-quantities.excavationYd3);quantities.excavationYd3=combined.reduce((n,r)=>n+r.volumeYd3,0);
 const house=getHousePlacement(data),housePolys=data.houseVisible===false?[]:hasHouseBlocks(data)?houseOutline(data):[yardRectangle((house.x0+house.x1)/2,-house.depthIn/2,house.widthIn,house.depthIn)];if(poolArea(poolClip(excavationFootprints,housePolys,'intersection'))>.001)pending.push('Pool excavation overlaps the house footprint; building/foundation separation and engineering are unresolved.');
 for(const feature of data.yardFeatures??[]){if(!feature.enabled||feature.kind!=='retaining-wall')continue;if(poolArea(poolClip(excavationFootprints,yardPathEnvelope(yardWallPath(feature),feature.depthFt*12),'intersection'))>.001)pending.push(`${feature.name}: pool excavation intersects a retaining-wall body; foundation, reinforcement and excavation separation remain unresolved.`);}
 for(const object of data.landscapeObjects??[]){if(!object.enabled)continue;const footprint=object.kind==='bed'&&object.polygon?[object.polygon.map(p=>({x:p.x,y:p.z}))]:[yardRectangle(object.xIn,object.zIn,object.widthIn,object.depthIn,object.rotationDeg*Math.PI/180)];if(poolArea(poolClip(permanentExclusionFootprints,footprint,'intersection'))>.001)pending.push(`${object.name}: landscape placement overlaps the pool opening, coping or transition; reposition the object or specify a supported connection.`);}
 if(deck){if(deck.foundationSupports.some(f=>poolArea(poolClip(excavationFootprints,[yardRectangle(f.x,f.z,24,24)],'intersection'))>.001))pending.push('Pool excavation intersects a deck foundation planning envelope. Structural separation is unresolved.');if(deck.treads.some(t=>poolArea(poolClip(permanentExclusionFootprints,[t.polygon??yardRectangle(t.x,t.z,t.w,t.d,-(t.angle??0))],'intersection'))>.001))pending.push('Pool opening/coping intersects a deck stair tread or landing. Refit or reposition the design.');}
 const exposedRim=poolClip(poolClip(poolOffset(permanentExclusionFootprints,1),permanentExclusionFootprints,'difference'),(data.yardFeatures??[]).filter(f=>f.enabled&&f.kind==='patio').flatMap(yardFeatureOutline),'difference');if(exposedRim.length){const heights=groundSections(data,site,exposedRim).flatMap(s=>s.polygon.map(v=>planeAt(s.plane,v.x,v.y)));if(heights.some(h=>Math.abs(h-p.copingTopElevationIn)>.25))pending.push('Proposed ground differs from the fixed pool rim outside adjacent paving. Define an explicit grading or retaining transition; no automatic soil bank is included.');}
 if(!data.siteModel)warnings.push('Excavation is measured against the project terrain plane; a surveyed site and soil/groundwater conditions are still required.');
 warnings.push(...pending);
 return {config:p,openingFootprints,structureFootprints,copingFootprints,permanentExclusionFootprints,excavationFootprints,formationRegions,solids,copingStock,quantities,warnings,pending,status:pending.length?'pending':planning?'planning':'ready',coverageComplete,floorRegions,waterElevationIn,copingTopElevationIn:p.copingTopElevationIn};
}
const cache=new WeakMap<DeckData,{models:PoolFeatureModel[];decks:WeakMap<DeckTakeoff,PoolFeatureModel[]>}>();
export function getPoolModels(data:DeckData,deck?:DeckTakeoff){
 let saved=cache.get(data);
 if(!saved){const site=data.siteModel?createSiteSurface(data.siteModel,getTerrainConfig(data)):undefined,models=(data.pools??[]).filter(p=>p.enabled).map(p=>buildPool(data,p,undefined,site));for(let i=0;i<models.length;i++)for(let j=i+1;j<models.length;j++)if(poolArea(poolClip(models[i].excavationFootprints,models[j].excavationFootprints,'intersection'))>.001){for(const m of [models[i],models[j]]){const message='Pool construction envelopes overlap another pool; assemblies and shared working space remain unresolved.';m.pending.push(message);m.warnings.push(message);m.status='pending';}}saved={models,decks:new WeakMap()};cache.set(data,saved);}
 if(!deck)return saved.models;
 const previous=saved.decks.get(deck);if(previous)return previous;
 const models=saved.models.map(m=>{const pending=[...m.pending],warnings=[...m.warnings];if(deck.foundationSupports.some(f=>poolArea(poolClip(m.excavationFootprints,[yardRectangle(f.x,f.z,24,24)],'intersection'))>.001))pending.push('Pool excavation intersects a deck foundation planning envelope. Structural separation is unresolved.');if(deck.treads.some(t=>poolArea(poolClip(m.permanentExclusionFootprints,[t.polygon??yardRectangle(t.x,t.z,t.w,t.d,-(t.angle??0))],'intersection'))>.001))pending.push('Pool opening/coping intersects a deck stair tread or landing. Refit or reposition the design.');warnings.push(...pending.slice(m.pending.length));return {...m,pending,warnings,status:pending.length?'pending' as const:m.status};});saved.decks.set(deck,models);return models;
}
/** Whole material prisms are partitioned at every crossing affine plane. */
export function reconcilePoolMaterials(pools:PoolFeatureModel[],features:YardFeatureModel[],boxes:YardBox[],formations:{featureId:string;polys:PlanPoint[][];bottom:number;formationPlane?:SitePlane}[]){
 const patios=features.filter(f=>!f.excluded&&f.config.kind==='patio'),patioIds=new Set(patios.map(f=>f.config.id)),patioFloors=formations.filter(f=>patioIds.has(f.featureId)),collars=pools.flatMap(p=>p.solids.filter(s=>s.role==='collar'));
 for(const feature of patios){const replaced:YardBox[]=[];for(const b of feature.boxes){if(!['base','bedding'].includes(b.role)||!b.polygon){replaced.push(b);continue;}const top=b.topPlane??flat(b.y+b.h/2),bottom=b.bottomPlane??(b.normalThicknessIn!==undefined?belowPlane(top,b.normalThicknessIn):flat(b.bottomIn??b.y-b.h/2));let parts:Prism[]=[{polygon:b.polygon,topPlane:top,bottomPlane:bottom}];for(const collar of collars)parts=subtractPrism(parts,collar);if(parts.length===1&&parts[0].polygon===b.polygon){replaced.push(b);continue;}for(const [i,part] of parts.entries()){const xs=part.polygon.map(p=>p.x),zs=part.polygon.map(p=>p.y),x=(Math.min(...xs)+Math.max(...xs))/2,z=(Math.min(...zs)+Math.max(...zs))/2,topY=Math.max(...part.polygon.map(p=>planeAt(part.topPlane,p.x,p.y))),bottomY=Math.min(...part.polygon.map(p=>planeAt(part.bottomPlane,p.x,p.y)));replaced.push({...b,id:`${b.id}:pool:${i}`,polygon:part.polygon,topPlane:part.topPlane,bottomPlane:part.bottomPlane,normalThicknessIn:undefined,bottomIn:undefined,x,z,y:(topY+bottomY)/2,h:topY-bottomY,w:Math.max(...xs)-Math.min(...xs),d:Math.max(...zs)-Math.min(...zs)});}}
  feature.boxes.splice(0,feature.boxes.length,...replaced);for(const role of ['base','bedding'] as const)feature.quantities[role==='base'?'baseYd3':'beddingYd3']=feature.boxes.filter(b=>b.role===role).reduce((n,b)=>{const top=b.topPlane??flat(b.y+b.h/2),bottom=b.bottomPlane??(b.normalThicknessIn!==undefined?belowPlane(top,b.normalThicknessIn):flat(b.bottomIn??b.y-b.h/2));return n+(b.polygon?prismVolume({polygon:b.polygon,topPlane:top,bottomPlane:bottom}):b.w*b.d*b.h/46656);},0);
  for(const m of pools){const adjacent=poolClip(feature.footprints,poolClip(poolOffset(m.permanentExclusionFootprints,1),m.permanentExclusionFootprints,'difference'),'intersection');if(adjacent.length){const finish=feature.topPlane??flat(feature.topIn),values=adjacent.flat().map(v=>planeAt(finish,v.x,v.y)-m.copingTopElevationIn);if(values.some(v=>Math.abs(v)>.25)){const message=`${feature.config.name}: patio finished level differs from the fixed pool coping rim (${Math.min(...values).toFixed(2)} to ${Math.max(...values).toFixed(2)} in). An explicit transition or revised slope is required.`;if(!m.pending.includes(message)){m.pending.push(message);m.warnings.push(message);m.status='pending';}feature.quoteRequired=true;feature.warnings.push(message);}}const formation=patioFloors.filter(f=>f.featureId===feature.config.id),conflicting=m.solids.filter(s=>s.role==='collar').some(s=>formation.some(f=>volume(poolClip([s.polygon],f.polys,'intersection'),s.topPlane,f.formationPlane??flat(f.bottom))>.001));const pavers=feature.boxes.filter(b=>b.role==='paver'&&b.polygon).some(b=>m.solids.filter(s=>s.role==='collar').some(s=>{const top=b.topPlane??flat(b.y+b.h/2),bottom=b.normalThicknessIn!==undefined?belowPlane(top,b.normalThicknessIn):flat(b.y-b.h/2);const ps:Prism[]=[{polygon:b.polygon!,topPlane:top,bottomPlane:bottom}],difference=subtractPrism(ps,s);return ps.reduce((n,p)=>n+prismVolume(p),0)-difference.reduce((n,p)=>n+prismVolume(p),0)>.00001;}));if(conflicting||pavers){const message=`${feature.config.name}: pool collar and patio construction layers share a support zone; aggregate/bedding is partitioned, but support, paver clearance and connection details require confirmation.`;if(!m.pending.includes(message)){m.pending.push(message);m.warnings.push(message);m.status='pending';}feature.quoteRequired=true;if(!feature.warnings.includes(message))feature.warnings.push(message);}}
 }
 const all=new Set(patios.map(f=>f.config.id));boxes.splice(0,boxes.length,...boxes.filter(b=>!all.has(b.featureId)),...patios.flatMap(f=>f.boxes));
}
registerPoolModelRuntime({getPoolModels,reconcilePoolMaterials});

import {prismVolume,subtractBand,subtractPrism,lowerPrisms,type Prism} from './materialPrisms';
