import {POOL_SCOPES} from './poolTypes';
import {registerPoolQuoteTypesRuntime,type PoolQuoteInputs,type PoolBudgetBook} from './poolQuoteTypes';
const money=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=10_000_000&&Math.abs(v*100-Math.round(v*100))<1e-6;
const str=(v:unknown,max=200)=>typeof v==='string'&&v.trim().length>0&&v.length<=max&&!/[\u0000-\u001f]/.test(v);
const date=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
function plain(v:unknown):v is Record<string,any>{return !!v&&typeof v==='object'&&!Array.isArray(v)&&[Object.prototype,null].includes(Object.getPrototypeOf(v))&&Reflect.ownKeys(v).every(k=>typeof k==='string'&&Object.getOwnPropertyDescriptor(v,k)?.enumerable&&'value'in Object.getOwnPropertyDescriptor(v,k)!);}
function list(v:unknown,max:number):v is any[]{return Array.isArray(v)&&Object.getPrototypeOf(v)===Array.prototype&&v.length<=max&&Reflect.ownKeys(v).every(k=>k==='length'||typeof k==='string'&&/^(0|[1-9]\d*)$/.test(k)&&Number(k)<v.length&&'value'in Object.getOwnPropertyDescriptor(v,k)!)&&Object.keys(v).length===v.length;}
function fields(v:Record<string,any>,required:string[],optional:string[]=[]){return required.every(k=>Object.hasOwn(v,k))&&Object.keys(v).every(k=>required.includes(k)||optional.includes(k));}
const scope=(v:any)=>typeof v==='string'&&(POOL_SCOPES as readonly string[]).includes(v);
const amounts=(v:Record<string,any>)=>money(v.supply)&&money(v.labour)&&money(v.equipment);
const shared=(v:Record<string,any>)=>amounts(v)&&date(v.effectiveDate)&&str(v.source,500)&&(!Object.hasOwn(v,'deliveryKey')||str(v.deliveryKey,120));
const units=['ea','sqft','lf','m2','m','yd3','m3','tonne','hour','day','load','bin','roll','assembly'];
function price(v:any,privateRecord=true){return plain(v)&&fields(v,['scope','basis','unit','effectiveDate','source','supply','labour','equipment',...(privateRecord?['poolId','quantityKey']:[])],['packQuantity','deliveryKey'])&&shared(v)&&scope(v.scope)&&['allowance','quote','unit-rate'].includes(v.basis)&&units.includes(v.unit)&&(!privateRecord||str(v.poolId,80)&&str(v.quantityKey,100))&&(!Object.hasOwn(v,'packQuantity')||typeof v.packQuantity==='number'&&Number.isFinite(v.packQuantity)&&v.packQuantity>0&&v.packQuantity<=1_000_000)&&(!(v.basis==='unit-rate')||v.unit!=='assembly');}
export function validatePoolQuoteInputs(v:unknown):v is PoolQuoteInputs {if(v===undefined)return true;if(!plain(v)||!fields(v,['version','scopes','packages'])||v.version!==1||!list(v.scopes,1300)||!list(v.packages,100))return false;const seen=new Set<string>();for(const r of v.scopes){if(!price(r))return false;const key=r.poolId+':'+r.scope;if(seen.has(key))return false;seen.add(key);}const ids=new Set<string>();for(const r of v.packages){if(!plain(r)||!fields(r,['id','poolId','name','includedScopes','quantityKey','effectiveDate','source','supply','labour','equipment'],['deliveryKey'])||!shared(r)||!str(r.id,80)||!str(r.poolId,80)||!str(r.name,120)||!str(r.quantityKey,100)||!list(r.includedScopes,13)||!r.includedScopes.length||!r.includedScopes.every(scope)||new Set(r.includedScopes).size!==r.includedScopes.length||ids.has(r.id))return false;ids.add(r.id);}return true;}
export function validatePoolBudgetBook(v:unknown):v is PoolBudgetBook {return plain(v)&&fields(v,['version','revision','updatedAt','presets'])&&v.version===1&&Number.isSafeInteger(v.revision)&&v.revision>=0&&typeof v.updatedAt==='string'&&(v.revision===0?v.updatedAt==='':Number.isFinite(Date.parse(v.updatedAt)))&&list(v.presets,100)&&v.presets.every(p=>plain(p)&&fields(p,['id','name','type','scopes'])&&str(p.id,80)&&str(p.name,120)&&['fiberglass','vinyl-liner','concrete'].includes(p.type)&&list(p.scopes,13)&&p.scopes.every((s:any)=>price(s,false))&&new Set(p.scopes.map((s:any)=>s.scope)).size===p.scopes.length)&&new Set(v.presets.map(p=>p.id)).size===v.presets.length;}
registerPoolQuoteTypesRuntime({validatePoolQuoteInputs});
