'use client';
import {useEffect,useMemo,useState} from 'react';
import type {DeckData} from './types';
import {POOL_SCOPES,poolScopeOwner,type PoolFeature,type PoolScopeId} from './poolTypes';
import type {PoolQuoteInputs,PoolScopePrice,PoolPackagePrice,PoolBudgetBook} from './poolQuoteTypes';
import {validatePoolQuoteInputs} from './poolQuoteTypesRuntime';
import {POOL_SCOPE_LABELS,poolQuantityKey,poolScopeMeasurement,readPoolBudgetBook,emptyPoolBudgetBook,savePoolBudgetPreset,applyPoolBudgetPreset} from './poolQuoteRuntime';
import {getPoolModels} from './poolModel';
import {calculateEstimate} from './calculations';
import {readSupplierRateBook,emptySupplierRateBook,SUPPLIER_UNITS,type SupplierRateBook} from './supplierRateBook';
const money=(n:number)=>n.toLocaleString('en-CA',{style:'currency',currency:'CAD'});
const field={width:'100%',maxWidth:'100%',padding:6,border:'1px solid #ccd3cf',borderRadius:5};
interface CostDraft {scope:PoolScopeId;basis:PoolScopePrice['basis'];unit:PoolScopePrice['unit'];supply:string;labour:string;equipment:string;packQuantity:string;source:string;effectiveDate:string;deliveryKey:string}
const blank=():CostDraft=>({scope:'structure',basis:'allowance',unit:'assembly',supply:'',labour:'',equipment:'',packQuantity:'1',source:'',effectiveDate:new Date().toISOString().slice(0,10),deliveryKey:''});
export default function PoolQuoteEditor({data,pool,onChange}:{data:DeckData;pool:PoolFeature;onChange:(patch:Partial<DeckData>)=>void}){
 const [draft,setDraft]=useState<CostDraft>(blank),[book,setBook]=useState<PoolBudgetBook>(emptyPoolBudgetBook),[rates,setRates]=useState<SupplierRateBook>(emptySupplierRateBook),[error,setError]=useState(''),[packageName,setPackageName]=useState(''),[included,setIncluded]=useState<PoolScopeId[]>([]),[preview,setPreview]=useState<{inputs:PoolQuoteInputs;revision:number;source:DeckData;estimate:ReturnType<typeof calculateEstimate>}|null>(null);
 useEffect(()=>{let live=true;void Promise.all([readPoolBudgetBook(),readSupplierRateBook()]).then(([b,r])=>{if(live){setBook(b);setRates(r);}},e=>{if(live)setError(String(e instanceof Error?e.message:e));});return ()=>{live=false;};},[]);
 useEffect(()=>{setDraft(blank());setPreview(null);setIncluded([]);setError('');},[pool.id]);
 const result=useMemo(()=>calculateEstimate(data),[data]),poolModel=(result.yardModel as typeof result.yardModel&{pools?:ReturnType<typeof getPoolModels>}).pools?.find(p=>p.config.id===pool.id)??getPoolModels(data,result.model).find(p=>p.config.id===pool.id),key=poolQuantityKey(data,result.yardModel,pool);
 const before=useMemo(()=>{const base={...data};delete base.pools;delete base.poolQuoteInputs;return calculateEstimate(base);},[data]);
 const change=<K extends keyof CostDraft>(k:K,v:CostDraft[K])=>{setDraft(d=>({...d,[k]:v}));setPreview(null);};
 const guard=()=>{const api=window.deckcraft;if(!api)throw Error('Wait for the project controller before previewing private pool prices.');const live=api.read();if(!live.ready)throw Error('The project is still preparing geometry.');return live.revision;};
 const prepare=(inputs:PoolQuoteInputs)=>{try{if(!validatePoolQuoteInputs(inputs))throw Error('Enter source, date, scope and explicit nonnegative supply/labour/equipment amounts. CAD before HST.');const revision=guard();setPreview({inputs,revision,source:data,estimate:calculateEstimate({...data,poolQuoteInputs:inputs})});setError('');}catch(e){setError(e instanceof Error?e.message:'Pool price preview failed.');}};
 const amounts=()=>{const n=(s:string)=>s.trim()?Number(s):NaN;return {supply:n(draft.supply),labour:n(draft.labour),equipment:n(draft.equipment)};};
 const record=():PoolScopePrice=>({...amounts(),poolId:pool.id,scope:draft.scope,basis:draft.basis,unit:draft.unit,quantityKey:key,effectiveDate:draft.effectiveDate,source:draft.source,...(draft.basis==='unit-rate'?{packQuantity:Number(draft.packQuantity)}:{}),...(draft.deliveryKey.trim()?{deliveryKey:draft.deliveryKey.trim()}: {})});
 const old=data.poolQuoteInputs??{version:1 as const,scopes:[],packages:[]},measure=poolModel?poolScopeMeasurement(data,result.yardModel,poolModel,draft.scope,draft.unit):null;
 const fillSaved=(scope:PoolScopeId)=>{const r=old.scopes.find(r=>r.poolId===pool.id&&r.scope===scope);setDraft(r?{scope,basis:r.basis,unit:r.unit,supply:String(r.supply),labour:String(r.labour),equipment:String(r.equipment),packQuantity:String(r.packQuantity??1),source:r.source,effectiveDate:r.effectiveDate,deliveryKey:r.deliveryKey??''}:{...blank(),scope,unit:poolModel?poolScopeMeasurement(data,result.yardModel,poolModel,scope).unit:'assembly'});setPreview(null);};
 return <details className="mt-3 rounded-lg border p-3" data-testid="pool-quote-editor"><summary className="cursor-pointer font-semibold">Pool budgets and project change</summary>
  <p className="my-2 text-sm">Private Golden Maple inputs · CAD before HST. Missing costs remain pending. Physical quantities stay in the project for work by either contractor.</p>
  <dl className="grid grid-cols-2 gap-2 text-sm"><dt>Paving removed</dt><dd>{Math.max(0,before.yardModel.quantities.patioAreaSqft-result.yardModel.quantities.patioAreaSqft).toFixed(2)} sq ft</dd><dt>Excavation change</dt><dd>{((result.yardModel.quantities.sharedExcavationYd3??result.yardModel.quantities.excavationYd3)-(before.yardModel.quantities.sharedExcavationYd3??before.yardModel.quantities.excavationYd3)).toFixed(3)} cu yd</dd><dt>Disposal change</dt><dd>{result.yardTakeoff.earthwork.bins-before.yardTakeoff.earthwork.bins} planning bins</dd><dt>Paving / site cost change</dt><dd>{money(result.yardTakeoff.knownSubtotalCents/100-before.yardTakeoff.knownSubtotalCents/100)}</dd><dt>Pool work added</dt><dd>{money(result.poolQuoteReview?.total??0)}</dd><dt>Net priced project change</dt><dd>{money(result.total-before.total)} including HST</dd></dl>
  <p className="my-2 text-sm">{result.quoteRequired.length?'Priced portion only; outstanding prices and construction inputs prevent a complete quotation.':'All selected cost scopes priced.'} HST is applied once at project level.</p>
  <div className="my-2 text-sm">{POOL_SCOPES.map(scope=><div key={scope} className="flex justify-between gap-2 border-b py-1"><span>{POOL_SCOPE_LABELS[scope]}</span><span>{poolScopeOwner(pool,scope)==='pool-contractor'?'Pool contractor':result.poolQuoteReview?.pendingScopes.some(s=>s.poolId===pool.id&&s.scope===scope)?'Pending':'Priced / packaged'}</span></div>)}</div>
  <label className="block text-sm">Saved allowance for this pool type<select style={field} value="" onChange={e=>{const p=book.presets.find(p=>p.id===e.target.value);if(p)prepare(applyPoolBudgetPreset(data,result.yardModel,pool,p));}}><option value="">Choose a private preset</option>{book.presets.filter(p=>p.type===pool.type).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
  {!book.presets.some(p=>p.type===pool.type)&&<p className="my-2 text-sm">No saved allowance for {pool.type}. Enter your costs below; no default dollars have been invented.</p>}
  <label className="block text-sm">Scope<select aria-label="Pool price scope" style={field} value={draft.scope} onChange={e=>fillSaved(e.target.value as PoolScopeId)}>{POOL_SCOPES.map(s=><option key={s} value={s}>{POOL_SCOPE_LABELS[s]}</option>)}</select></label>
  <label className="block text-sm">Price basis<select style={field} value={draft.basis} onChange={e=>change('basis',e.target.value as CostDraft['basis'])}><option value="allowance">Planning allowance total</option><option value="quote">Supplier / contractor quote total</option><option value="unit-rate">Supply per pack; labour/equipment per installed unit</option></select></label>
  <label className="block text-sm">Measured unit<select style={field} value={draft.unit} onChange={e=>change('unit',e.target.value as CostDraft['unit'])}><option value="assembly">assembly</option>{SUPPLIER_UNITS.map(u=><option key={u}>{u}</option>)}</select></label>
  {measure&&<p className="my-2 text-sm">{measure.known?`${measure.quantity.toFixed(3)} ${measure.unit}`:'Physical input / conversion pending'}. {measure.note}</p>}
  <label className="block text-sm">Private supplier rate<select style={field} value="" onChange={e=>{if(e.target.value==='')return;const r=rates.rates[Number(e.target.value)];if(r)setDraft(d=>({...d,basis:'unit-rate',unit:r.unit,packQuantity:String(r.packQuantity),supply:String(r.price),labour:String(r.labour),equipment:String(r.equipment),source:`${r.manufacturer} / ${r.sku}; delivery excluded`,effectiveDate:r.effectiveDate}));setPreview(null);}}><option value="">Choose recorded SKU (delivery separate)</option>{rates.rates.map((r,i)=><option key={`${r.manufacturer}/${r.sku}`} value={i}>{r.manufacturer} / {r.sku} · {r.unit}</option>)}</select></label>
  <div className="grid grid-cols-3 gap-2">{(['supply','labour','equipment'] as const).map(k=><label key={k} className="block text-sm">{k}<input aria-label={`Pool ${k} CAD`} style={field} inputMode="decimal" type="number" min="0" step="0.01" value={draft[k]} onChange={e=>change(k,e.target.value)}/></label>)}</div>
  {draft.basis==='unit-rate'&&<label className="block text-sm">Supply pack quantity<input style={field} type="number" min="0.000001" value={draft.packQuantity} onChange={e=>change('packQuantity',e.target.value)}/></label>}
  <label className="block text-sm">Source / included work<input style={field} value={draft.source} maxLength={500} onChange={e=>change('source',e.target.value)}/></label><label className="block text-sm">Effective date<input style={field} type="date" value={draft.effectiveDate} onChange={e=>change('effectiveDate',e.target.value)}/></label><label className="block text-sm">Shared delivery / mobilization ID (when applicable)<input style={field} value={draft.deliveryKey} maxLength={120} onChange={e=>change('deliveryKey',e.target.value)}/></label>
  <button className="my-2 rounded border px-3 py-2" type="button" onClick={()=>prepare({...old,scopes:[...old.scopes.filter(r=>r.poolId!==pool.id||r.scope!==draft.scope),record()]})}>Preview pool scope price</button>
  <details className="my-2"><summary>Supplier package inclusions</summary><p className="text-sm">The package replaces every checked scope. Its separated amounts use the fields above. All included work must belong to Golden Maple; overlapping packages stay inactive.</p><label className="block text-sm">Package name<input style={field} value={packageName} onChange={e=>{setPackageName(e.target.value);setPreview(null);}}/></label>{POOL_SCOPES.map(s=><label key={s} className="block text-sm"><input type="checkbox" checked={included.includes(s)} onChange={e=>{setIncluded(v=>e.target.checked?[...v,s]:v.filter(x=>x!==s));setPreview(null);}}/>{POOL_SCOPE_LABELS[s]}</label>)}<button className="my-2 rounded border px-3 py-2" type="button" onClick={()=>{const r:PoolPackagePrice={...amounts(),id:`package-${pool.id}-${packageName.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,poolId:pool.id,name:packageName.trim(),includedScopes:included,quantityKey:key,effectiveDate:draft.effectiveDate,source:draft.source,...(draft.deliveryKey.trim()?{deliveryKey:draft.deliveryKey.trim()}: {})};prepare({...old,packages:[...old.packages.filter(p=>p.id!==r.id),r]});}}>Preview package replacement</button>{old.packages.filter(p=>p.poolId===pool.id).map(p=><div key={p.id} className="text-sm">{p.name}<button type="button" className="ml-2 underline" onClick={()=>prepare({...old,packages:old.packages.filter(r=>r.id!==p.id)})}>Preview removal</button></div>)}</details>
  {old.scopes.some(r=>r.poolId===pool.id)&&<button type="button" className="my-2 rounded border px-3 py-2" onClick={()=>void (async()=>{try{const scopes=old.scopes.filter(r=>r.poolId===pool.id).map(({poolId,quantityKey,...r})=>r);const next=await savePoolBudgetPreset({id:`pool-budget-${pool.type}`,name:`Golden Maple ${pool.type} planning budget`,type:pool.type,scopes},book.revision);setBook(next);setError('');}catch(e){setError(e instanceof Error?e.message:'Private budget save failed.');}})()}>Save entered scopes as private {pool.type} preset</button>}
  {preview&&<div className="my-2 rounded border p-2" role="status"><p>Preview: {money(preview.estimate.total-result.total)} project change including HST. {preview.estimate.poolQuoteReview?.pendingScopes.length??0} pool cost scope(s) pending; {preview.estimate.poolQuoteReview?.inactive??0} saved records inactive.</p><button type="button" className="mr-2 rounded border px-3 py-2" onClick={()=>{try{if(data!==preview.source||guard()!==preview.revision)throw Error('The design changed after preview. Preview the price again.');onChange({poolQuoteInputs:preview.inputs});setPreview(null);setError('');}catch(e){setError(e instanceof Error?e.message:'Price apply failed.');}}}>Apply private pool price</button><button type="button" className="underline" onClick={()=>setPreview(null)}>Cancel</button></div>}
  {error&&<p role="alert" className="my-2 text-sm">{error}</p>}
 </details>;
}
