import type {DeckData} from './types';
import type {YardModel} from './yardModel';
import type {EstimateResult} from './calculations';
import {POOL_SCOPES,poolScopeOwner,type PoolFeature,type PoolScopeId} from './poolTypes';
import {getPoolModels,type PoolFeatureModel} from './poolModel';
import {yardEarthworkPlan} from './yardEarthwork';
import {registerPoolQuoteRuntime} from './poolQuoteRegistry';
import {validatePoolQuoteInputs,validatePoolBudgetBook} from './poolQuoteTypesRuntime';
import type {PoolQuoteInputs,PoolBudgetBook,PoolBudgetPreset,PoolScopePrice,PoolPackagePrice} from './poolQuoteTypes';
import {readProjectValue,updateProjectValue} from './projectStorage';
const cents=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export const POOL_SCOPE_LABELS:Record<PoolScopeId,string>={structure:'Structure / shell / liner / finish',excavation:'Excavation and access',disposal:'Soil hauling and disposal',aggregate:'Pool base aggregate',backfill:'Backfill and collar / bond beam',coping:'Coping supply and setting',plumbing:'Plumbing and pressure tests',equipment:'Pump, filter and equipment',installation:'Installation labour',delivery:'Delivery / crane / mobilization',electrical:'Electrical and bonding',drainage:'Drainage and groundwater management','site-requirements':'Site requirements and permits'};
export const poolBank=(model:YardModel,id?:string)=>model.excavationRegions.filter(r=>id?r.featureId===`pool:${id}`||r.featureId.startsWith(`pool:${id}:`):r.featureId.startsWith('pool:')).reduce((n,r)=>n+r.volumeYd3,0);
/** Pool disposal is priced by its explicit scope. The existing yard benchmark
 * retains only non-pool excavation; physical quantities still include every dig. */
export function poolPricedEarthwork(data:DeckData,model:YardModel){
 const bank=Math.max(0,model.quantities.excavationYd3-poolBank(model)),allBank=model.quantities.sharedExcavationYd3??model.quantities.excavationYd3,fill=model.quantities.backfillYd3+model.quantities.raisedFillYd3+(model.quantities.siteEarthworkFillYd3??0),physical=yardEarthworkPlan(allBank,fill,data.yardEarthwork);
 // One physical reuse allocation is shared by pool, priced yard and pier scope.
 // Recalculating the entire fill demand per owner would reuse the same soil twice.
 const ownedReuse=allBank>0?physical.reusedYd3*bank/allBank:0;
 const work=yardEarthworkPlan(bank,ownedReuse,data.yardEarthwork);
 return {...work,haulingSection:work.exportBankYd3>.001?{id:'yard-hauling-cost',label:'Hauling and disposal price adjustments',amountCents:null,quantity:work.bins,unit:'planning bins',note:'Non-pool yard residual only. Pool spoil/disposal and deck-foundation reconciliation are separate owned scopes; quote only adjustments above this residual yard benchmark.'}:undefined};
}
function canonical(v:any):string {if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).filter(k=>v[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';}
function hash(s:string){let a=2166136261,b=3339675911;for(let i=0;i<s.length;i++){a=Math.imul(a^s.charCodeAt(i),16777619);b=Math.imul(b^s.charCodeAt(i),2246822519);}return 'pool-v1-'+(a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0');}
export function poolQuantityKey(data:DeckData,model:YardModel,pool:PoolFeature){const derived=(model as YardModel&{pools?:PoolFeatureModel[]}).pools?.find(m=>m.config.id===pool.id)??getPoolModels(data).find(m=>m.config.id===pool.id);return hash(canonical({pool,site:data.siteModel,terrain:data.terrainConfig,earthwork:data.yardEarthwork,yard:data.yardFeatures,quantities:derived?.quantities,pending:derived?.pending,bank:poolBank(model,pool.id)}));}
export interface PoolScopeMeasurement {quantity:number;unit:PoolScopePrice['unit'];known:boolean;note:string}
export function poolScopeMeasurement(data:DeckData,model:YardModel,p:PoolFeatureModel,scope:PoolScopeId,unit?:PoolScopePrice['unit']):PoolScopeMeasurement {
 const q=p.quantities,bank=poolBank(model,p.config.id),allBank=model.quantities.sharedExcavationYd3??model.quantities.excavationYd3,fill=model.quantities.backfillYd3+model.quantities.raisedFillYd3+(model.quantities.siteEarthworkFillYd3??0),earth=yardEarthworkPlan(allBank,fill,data.yardEarthwork),exportBank=allBank>0?bank*earth.exportBankYd3/allBank:0;
 const trench=(service:string)=>(p.config.serviceTrenches??[]).filter(t=>t.service===service).reduce((n,t)=>n+t.points.slice(1).reduce((s,v,i)=>s+Math.hypot(v.x-t.points[i].x,v.y-t.points[i].y)/12,0),0);
 const values:Record<PoolScopeId,PoolScopeMeasurement>={structure:{quantity:1,unit:'assembly',known:true,note:`${p.config.type}; finish ${q.finishSqft?.toFixed(2)??'pending'} sq ft; structure ${q.structureYd3?.toFixed(3)??'pending'} cu yd`},excavation:{quantity:bank,unit:'yd3',known:p.coverageComplete,note:'Attributed deepest union excavation, including entered service trenches.'},disposal:{quantity:exportBank,unit:'yd3',known:p.coverageComplete&&earth.haulingInputsComplete,note:'Bank soil exported after one shared reuse allocation; swell, density and payload remain explicit.'},aggregate:{quantity:q.baseYd3??0,unit:'yd3',known:p.config.assembly?.baseDepthIn!==undefined,note:'Pool base material only; patio aggregate is separate.'},backfill:{quantity:(q.backfillYd3??0)+(q.collarYd3??0),unit:'yd3',known:p.config.assembly?.workingClearanceIn!==undefined&&!!p.config.assembly?.backfillMaterial,note:`Separate backfill ${q.backfillYd3?.toFixed(3)??'pending'} and collar ${q.collarYd3?.toFixed(3)??'pending'} cu yd; confirm distinct material prices.`},coping:{quantity:q.copingPieces??0,unit:'ea',known:!!p.config.coping?.stockLengthIn&&!p.copingStock.some(s=>s.unsupported),note:'Stock pieces including recorded cuts; recorded support/bonding, adhesive or mortar, and transition backer rod/sealant must be included in the price scope.'},plumbing:{quantity:trench('plumbing'),unit:'lf',known:trench('plumbing')>0,note:'Entered service run only; fittings, pressure tests and equipment connections must be specified.'},equipment:{quantity:1,unit:'assembly',known:true,note:'Record pump, filter and included accessories.'},installation:{quantity:1,unit:'assembly',known:true,note:'Only labour not already included in other scope prices/packages.'},delivery:{quantity:1,unit:'load',known:true,note:'Use one shared delivery/mobilization identifier when included in a package or another pool.'},electrical:{quantity:1,unit:'assembly',known:true,note:'Electrical/bonding contractor scope, site route and inspection inputs required.'},drainage:{quantity:trench('drainage'),unit:'lf',known:trench('drainage')>0,note:'Entered drain route; outlet, fall, groundwater and hydrostatic details require recorded inputs.'},'site-requirements':{quantity:1,unit:'assembly',known:true,note:'Applicable enclosure, utility locates, permits, inspections and site-specific scope.'}};
 const v=values[scope];if(!unit||unit===v.unit)return v;if(unit==='assembly')return {...v,quantity:1,unit};
 if(scope==='coping'&&unit==='lf')return {quantity:q.perimeterLf??0,unit,known:!!p.config.coping,note:v.note};
 if(scope==='coping'&&unit==='sqft')return {quantity:q.copingAreaSqft??0,unit,known:!!p.config.coping,note:v.note};
 if(scope==='structure'&&unit==='sqft')return {quantity:q.finishSqft??0,unit,known:Number.isFinite(q.finishSqft),note:v.note};
 if(v.unit==='yd3'&&unit==='m3')return {...v,quantity:v.quantity*.764554858,unit};
 if(scope==='disposal'&&unit==='tonne')return {...v,quantity:allBank>0&&earth.spoilTonnes!==null?bank/allBank*earth.spoilTonnes:0,unit,known:v.known};
 return {quantity:0,unit,known:false,note:`No verified conversion from ${v.unit} to ${unit}; enter an assembly allowance or a matching measured unit.`};
}
export interface PoolQuoteReview {active:number;inactive:number;pendingScopes:{poolId:string;scope:PoolScopeId;reason:string}[];externalScopes:{poolId:string;scope:PoolScopeId}[];supply:number;labour:number;equipment:number;total:number}
export function buildPoolQuote(data:DeckData,model:YardModel,markup:number){
 const inputs=data.poolQuoteInputs;if(inputs&&!validatePoolQuoteInputs(inputs))throw Error('Invalid private pool quote inputs.');const models=(model as YardModel&{pools?:PoolFeatureModel[]}).pools??getPoolModels(data),sections:EstimateResult['sections']=[],pending:string[]=[],flags:string[]=[],review:PoolQuoteReview={active:0,inactive:0,pendingScopes:[],externalScopes:[],supply:0,labour:0,equipment:0,total:0},delivery=new Set<string>();
 const add=(p:PoolFeatureModel,name:string,r:PoolScopePrice|PoolPackagePrice,mult=1,installedMult=mult)=>{const supply=cents(r.supply*mult*markup),labour=cents(r.labour*installedMult),equipment=cents(r.equipment*installedMult),total=cents(supply+labour+equipment);sections.push({title:`Pool · ${p.config.name} · ${name}`,icon:'🏊',total,description:`CAD before HST. ${'basis'in r&&r.basis==='allowance'?'Planning allowance; supplier confirmation pending.':'Recorded price.'}`,items:[{name:'Supply',spec:'Pool supply for the selected scope.',qty:1,unit:'CAD',cost:supply},{name:'Labour',spec:'Separate labour, excluding labour covered by other scopes.',qty:1,unit:'CAD',cost:labour,laborCost:labour},{name:'Equipment',spec:'Separate equipment cost.',qty:1,unit:'CAD',cost:equipment}]});review.supply+=supply;review.labour+=labour;review.equipment+=equipment;review.total+=total;review.active++;if(r.deliveryKey)delivery.add(r.deliveryKey);};
 const unresolved=(p:PoolFeatureModel,scope:PoolScopeId,reason:string)=>{review.pendingScopes.push({poolId:p.config.id,scope,reason});const label=`Pool · ${p.config.name}: ${POOL_SCOPE_LABELS[scope]}`;pending.push(label);const m=poolScopeMeasurement(data,model,p,scope);sections.push({title:label,icon:'🏊',quoteRequired:true,total:0,items:[{name:label,spec:reason+' '+m.note,qty:m.known?m.quantity||1:1,unit:m.known?m.unit:'input pending',cost:null}]});};
 for(const p of models){const key=poolQuantityKey(data,model,p.config),packages=(inputs?.packages??[]).filter(r=>r.poolId===p.config.id),covered=new Set<PoolScopeId>(),overlap=new Set<PoolScopeId>();for(const r of packages.filter(r=>r.quantityKey===key))for(const scope of r.includedScopes){if(covered.has(scope))overlap.add(scope);covered.add(scope);}covered.clear();
  for(const r of packages){const active=r.quantityKey===key&&r.includedScopes.every(s=>poolScopeOwner(p.config,s)==='golden-maple'&&!overlap.has(s))&&(!r.deliveryKey||!delivery.has(r.deliveryKey));if(!active){review.inactive++;flags.push(`${p.config.name}: package ${r.name} is inactive after design, ownership, inclusion overlap or shared-delivery changes.`);continue;}add(p,`Package: ${r.name} (replaces ${r.includedScopes.map(s=>POOL_SCOPE_LABELS[s]).join(', ')})`,r);r.includedScopes.forEach(s=>covered.add(s));}
  for(const scope of POOL_SCOPES){if(poolScopeOwner(p.config,scope)!=='golden-maple'){review.externalScopes.push({poolId:p.config.id,scope});continue;}const r=inputs?.scopes.find(v=>v.poolId===p.config.id&&v.scope===scope);if(covered.has(scope)){if(r)review.inactive++;continue;}if(!r){unresolved(p,scope,'No private allowance or supplier quote entered.');continue;}if(r.quantityKey!==key){review.inactive++;unresolved(p,scope,'Saved price is stale after geometry, quantities or scope ownership changed; preview and reconfirm.');continue;}if(r.deliveryKey&&delivery.has(r.deliveryKey)){review.inactive++;unresolved(p,scope,'Shared delivery/mobilization is already included elsewhere; remove duplicate scope or explicitly enter zero.');continue;}
   const m=poolScopeMeasurement(data,model,p,scope,r.unit);if(r.basis==='unit-rate'&&!m.known){review.inactive++;unresolved(p,scope,m.note);continue;}const mult=r.basis==='unit-rate'?Math.ceil(m.quantity/(r.packQuantity??1)-1e-10):1;add(p,POOL_SCOPE_LABELS[scope],r,mult,r.basis==='unit-rate'?m.quantity:1);
  }
  if(p.pending.length||p.status!=='ready'){const label=`Pool · ${p.config.name}: construction inputs and geometry confirmation`;pending.push(label);sections.push({title:label,icon:'📐',quoteRequired:true,total:0,items:[{name:label,spec:p.pending.join(' ')||'Planning assembly dimensions require manufacturer/site confirmation before execution.',qty:1,unit:'physical review',cost:null}]});}flags.push(...p.warnings);
 }
 const live=new Set(models.map(p=>p.config.id));review.inactive+=(inputs?.scopes.filter(r=>!live.has(r.poolId)).length??0)+(inputs?.packages.filter(r=>!live.has(r.poolId)).length??0);review.supply=cents(review.supply);review.labour=cents(review.labour);review.equipment=cents(review.equipment);review.total=cents(review.total);return {sections,pending,flags,review};
}
export const emptyPoolBudgetBook=():PoolBudgetBook=>({version:1,revision:0,updatedAt:'',presets:[]});
export async function readPoolBudgetBook(){const raw=await readProjectValue<PoolBudgetBook>('privateRates','pool-budget-presets');if(raw===undefined)return emptyPoolBudgetBook();if(!validatePoolBudgetBook(raw))throw Error('Private pool allowances could not be restored.');return raw;}
export async function savePoolBudgetPreset(preset:PoolBudgetPreset,expectedRevision:number){return updateProjectValue<PoolBudgetBook>('privateRates','pool-budget-presets',raw=>{const current=raw??emptyPoolBudgetBook();if(!validatePoolBudgetBook(current)||current.revision!==expectedRevision)throw Error('Private pool allowances changed. Reload before saving.');const next={version:1 as const,revision:current.revision+1,updatedAt:new Date().toISOString(),presets:[...current.presets.filter(p=>p.id!==preset.id),preset]};if(!validatePoolBudgetBook(next))throw Error('Invalid pool allowance preset.');return next;});}
export function applyPoolBudgetPreset(data:DeckData,model:YardModel,pool:PoolFeature,preset:PoolBudgetPreset):PoolQuoteInputs {if(preset.type!==pool.type)throw Error('Choose an allowance preset for this pool type.');const key=poolQuantityKey(data,model,pool),old=data.poolQuoteInputs??{version:1 as const,scopes:[],packages:[]},scopes=preset.scopes.map(s=>({...s,poolId:pool.id,quantityKey:key})),next={...old,scopes:[...old.scopes.filter(s=>s.poolId!==pool.id||!scopes.some(r=>r.scope===s.scope)),...scopes]};if(!validatePoolQuoteInputs(next))throw Error('Invalid private pool allowance preset.');return next;}
registerPoolQuoteRuntime({buildPoolQuote,poolPricedEarthwork});
