import {registerPoolTypesRuntime,POOL_SCOPES,type PoolFeature} from './poolTypes';
import {validateCircularArcs,inspectArcShape} from './circularArcs';
import {yardShapeProblem} from './yardShapeGeometry';
import {poolLocalBounds,poolShapeSignature} from './poolGeometry';
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)&&[Object.prototype,null].includes(Object.getPrototypeOf(v))&&!Object.getOwnPropertySymbols(v).length&&Object.values(Object.getOwnPropertyDescriptors(v)).every(d=>d.enumerable&&'value'in d);
const list=(v:unknown,min:number,max:number):v is unknown[]=>Array.isArray(v)&&Object.getPrototypeOf(v)===Array.prototype&&!Object.getOwnPropertySymbols(v).length&&v.length>=min&&v.length<=max&&Object.entries(Object.getOwnPropertyDescriptors(v)).every(([k,d])=>k==='length'||String(Number(k))===k&&Number(k)>=0&&Number(k)<v.length&&d.enumerable&&'value'in d)&&Array.from({length:v.length},(_,i)=>i).every(i=>Object.hasOwn(v,String(i)));
const text=(v:unknown,max=160):v is string=>typeof v==='string'&&!!v.trim()&&v.length<=max&&!/[\u0000-\u001f]/.test(v);
const num=(v:unknown,min:number,max:number):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
const url=(v:unknown)=>{if(!text(v,1000))return false;try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}};
const keys=(v:Record<string,unknown>,s:string[])=>Object.keys(v).every(k=>s.includes(k));
const optional=(v:Record<string,unknown>,k:string,f:(x:unknown)=>boolean)=>v[k]===undefined||f(v[k]);
const point=(v:unknown)=>record(v)&&keys(v,['x','y'])&&num(v.x,-120000,120000)&&num(v.y,-120000,120000);
export function poolValidationProblem(v:unknown):string{
 if(!record(v)||!keys(v,['id','name','enabled','type','xIn','zIn','rotationDeg','outline','curves','copingTopElevationIn','waterOffsetIn','depthProfile','assembly','coping','product','scopeMode','scopeOwners','serviceTrenches']))return 'Pool fields must be plain recorded values without unknown fields or accessors.';
 if(!text(v.id,80)||!text(v.name)||typeof v.enabled!=='boolean'||!['fiberglass','vinyl-liner','concrete'].includes(v.type as string)||!['complete','supplied-by-others'].includes(v.scopeMode as string))return 'Choose a pool name, type and installation scope.';
 if(!num(v.xIn,-120000,120000)||!num(v.zIn,-120000,120000)||!num(v.rotationDeg,-360,360)||!num(v.copingTopElevationIn,-120000,120000)||!num(v.waterOffsetIn,0,48))return 'Enter finite pool position, rotation, fixed coping elevation and water offset.';
 const shape=yardShapeProblem('patio',v.outline);if(shape)return shape.replaceAll('patio','pool');
 const p=v as unknown as PoolFeature;try{if(v.curves!==undefined)validateCircularArcs(v.curves,p.outline,true);inspectArcShape(p.outline,p.curves,true);}catch(e){return e instanceof Error?e.message:'Invalid circular pool outline.';}
 const b=poolLocalBounds(p);if(!list(v.depthProfile,2,32))return 'Define at least start and end water-depth stations.';
 let previous=-1;for(const d of v.depthProfile){if(!record(d)||!keys(d,['stationIn','depthIn'])||!num(d.stationIn,0,b.lengthIn+.01)||!num(d.depthIn,6,240)||d.stationIn<=previous+.01)return 'Water depths must be positive and stations ordered along the pool length.';previous=d.stationIn;}
 if(Math.abs(p.depthProfile[0].stationIn)>.001||Math.abs(p.depthProfile.at(-1)!.stationIn-b.lengthIn)>.01)return 'Depth stations must begin at zero and end at the complete pool length.';
 if(v.assembly!==undefined){const a=v.assembly;if(!record(a)||!keys(a,['status','wallThicknessIn','floorThicknessIn','baseDepthIn','workingClearanceIn','backfillMaterial','collarWidthIn','collarDepthIn','sourceUrl','sourceNote'])||!['planning','recorded'].includes(a.status as string)||!['wallThicknessIn','floorThicknessIn','baseDepthIn','workingClearanceIn','collarWidthIn','collarDepthIn'].every(k=>optional(a,k,n=>num(n,0,120)))||!optional(a,'backfillMaterial',x=>['aggregate','engineered-fill','concrete','supplier-specified'].includes(x as string))||!optional(a,'sourceUrl',url)||!optional(a,'sourceNote',x=>text(x,1000)))return 'Invalid pool assembly measurements or source record.';if(a.status==='recorded'&&!a.sourceUrl&&!a.sourceNote)return 'Recorded assemblies need a supplier or engineering source.';}
 if(v.coping!==undefined){const c=v.coping;if(!record(c)||!keys(c,['status','widthIn','thicknessIn','overhangIn','jointIn','transitionJointIn','stockLengthIn','settingBedThicknessIn','settingBedMaterial','supportSourceUrl','supportNote','manufacturer','productId','sourceUrl','verifiedForPool','color'])||!num(c.widthIn,.1,120)||!num(c.thicknessIn,.1,24)||!num(c.overhangIn,0,24)||c.overhangIn>=c.widthIn||!num(c.jointIn,0,2)||!num(c.transitionJointIn,0,6)||typeof c.verifiedForPool!=='boolean'||!optional(c,'stockLengthIn',x=>num(x,1,120))||!optional(c,'status',x=>['planning','recorded'].includes(x as string))||!optional(c,'settingBedThicknessIn',x=>num(x,0,6))||!optional(c,'settingBedMaterial',x=>['mortar','adhesive','supplier-specified'].includes(x as string))||!optional(c,'supportSourceUrl',url)||!optional(c,'supportNote',x=>text(x,1000))||!optional(c,'manufacturer',text)||!optional(c,'productId',text)||!optional(c,'sourceUrl',url)||!optional(c,'color',x=>typeof x==='string'&&/^#[0-9a-f]{6}$/i.test(x)))return 'Invalid pool coping dimensions or product fields.';if(c.verifiedForPool&&(!c.sourceUrl||!c.manufacturer||!c.productId))return 'Pool-suitable coping requires a manufacturer product and recorded source.';}
 if(v.product!==undefined){const m=v.product;if(!record(m)||!keys(m,['manufacturer','model','sourceUrl','shapeSignature','sourceNote'])||!text(m.manufacturer)||!text(m.model)||!url(m.sourceUrl)||!text(m.shapeSignature,20000)||!optional(m,'sourceNote',x=>text(x,1000)))return 'Invalid manufacturer pool model record.';if(m.shapeSignature!==poolShapeSignature(p))return 'The pool shape or depth no longer matches its manufacturer model. Remove the match or restore its dimensions.';}
 if(v.scopeOwners!==undefined&&(!record(v.scopeOwners)||!Object.entries(v.scopeOwners).every(([k,o])=>(POOL_SCOPES as readonly string[]).includes(k)&&['golden-maple','pool-contractor'].includes(o as string))))return 'Invalid contractor scope ownership.';
 if(v.serviceTrenches!==undefined){if(!list(v.serviceTrenches,0,16))return 'Use at most 16 recorded pool service trenches.';const ids=new Set<string>();for(const t of v.serviceTrenches){if(!record(t)||!keys(t,['id','service','points','widthIn','depthIn'])||!text(t.id,80)||ids.has(t.id)||!['plumbing','electrical','drainage'].includes(t.service as string)||!num(t.widthIn,1,120)||!num(t.depthIn,1,240)||!list(t.points,2,64)||!t.points.every(point))return 'Invalid service trench dimensions or path.';ids.add(t.id);const points=t.points as {x:number;y:number}[];if(points.slice(1).some((b,i)=>Math.hypot(b.x-points[i].x,b.y-points[i].y)<1))return 'Service trenches need distinct path points at least one inch apart.';}}
 return '';
}
export function validatePoolFeature(v:unknown):v is PoolFeature{return !poolValidationProblem(v);}
export function validatePools(v:unknown):v is PoolFeature[]{if(!list(v,0,16))return false;const ids=new Set<string>();return v.every(p=>validatePoolFeature(p)&&!ids.has(p.id)&&!!ids.add(p.id));}
registerPoolTypesRuntime({validatePools,validatePoolFeature,poolValidationProblem});
