import {validateLandscapeObjects} from './landscapeTypes';
import {landscapePlacement,landscapeBedAreas,activePuttingCups} from './landscapeModelRuntime';
import {validateYardFinishedSettings} from './yardFinishedSettings';
import type {DeckData,YardFeature} from './types';
import type {PlanPoint} from './lib/deckGeometry';
import {yardShapeWorldPoints,yardShapeEdit,yardShapeMove,yardShapeLocalPoints} from './yardShapeEditing';
import {arcGeometry,bulgeForRadius} from './circularArcs';
import {curveYardEdge} from './yardDesignTools';
import {assertUnlockedChanges,assertUniqueObjectIds,emptyOrganization,validateEditorOrganization,type EditorOrganization} from './editorOrganization';
export type ObjectEdit={action:'move';dxIn:number;dzIn:number}|{action:'rotate';angleDeg:number;pivotXIn:number;pivotZIn:number}|{action:'align';axis:'x'|'z'}|{action:'snap';gridIn:number}|{action:'distribute';axis:'x'|'z'}|{action:'lock';locked:boolean}|{action:'layer';layerId:string}|{action:'group';name:string};
export function editObjects(data:DeckData,ids:string[],edit:ObjectEdit):Partial<DeckData>{
 if(!edit||!['move','rotate','align','snap','distribute','lock','layer','group'].includes(edit.action))throw Error('Choose a supported object operation.');if(('axis' in edit)&&!['x','z'].includes(edit.axis))throw Error('Choose the across or out axis.');if(edit.action==='lock'&&typeof edit.locked!=='boolean')throw Error('Lock state must be explicit.');
 if(!Array.isArray(ids)||!ids.length||ids.length>100||new Set(ids).size!==ids.length)throw Error('Select 1–100 different objects.');
 assertUniqueObjectIds(data);
 const all=[...(data.yardFeatures??[]).map(f=>({id:f.id,x:f.xFt*12,z:f.zFt*12})),...(data.landscapeObjects??[]).map(f=>({id:f.id,x:f.xIn,z:f.zIn})),...(data.pools??[]).map(f=>({id:f.id,x:f.xIn,z:f.zIn})),...(data.siteModel?.transitions??[]).map(t=>({id:t.id,x:t.a.points[0].x,z:t.a.points[0].y}))];
 const selected=ids.map(id=>all.find(f=>f.id===id));if(selected.some(f=>!f))throw Error('A selected object is no longer present.');const objects=selected as typeof all;
 if(['lock','layer','group'].includes(edit.action)){const o=structuredClone(data.editorOrganization??emptyOrganization());if(edit.action==='group'){if(!edit.name.trim()||edit.name.length>80)throw Error('Enter a group name up to 80 characters.');o.groups.push({id:`group-${Date.now()}`,name:edit.name,objectIds:ids});}else for(const id of ids){let entry=o.objects.find(f=>f.id===id);if(!entry){entry={id,layerId:o.layers[0].id,locked:false};o.objects.push(entry);}if(edit.action==='lock')entry.locked=edit.locked;else if(edit.action==='layer'){if(!o.layers.some(l=>l.id===edit.layerId))throw Error('Choose an existing layer.');entry.layerId=edit.layerId;}}return {editorOrganization:validateEditorOrganization(o)};}
 const positions=new Map(objects.map(f=>[f.id,{x:f.x,z:f.z}]));
 if(edit.action==='move'){if(![edit.dxIn,edit.dzIn].every(Number.isFinite))throw Error('Enter finite offsets.');for(const p of positions.values()){p.x+=edit.dxIn;p.z+=edit.dzIn;}}
 else if(edit.action==='rotate'){if(![edit.angleDeg,edit.pivotXIn,edit.pivotZIn].every(Number.isFinite)||Math.abs(edit.angleDeg)>360)throw Error('Enter finite rotation and pivot values.');const a=edit.angleDeg*Math.PI/180,c=Math.cos(a),s=Math.sin(a);for(const p of positions.values()){const x=p.x-edit.pivotXIn,z=p.z-edit.pivotZIn;p.x=edit.pivotXIn+c*x-s*z;p.z=edit.pivotZIn+s*x+c*z;}}
 else if(edit.action==='snap'){if(!Number.isFinite(edit.gridIn)||edit.gridIn<.125||edit.gridIn>120)throw Error('Grid must be between ⅛ and 120 inches.');for(const p of positions.values()){p.x=Math.round(p.x/edit.gridIn)*edit.gridIn;p.z=Math.round(p.z/edit.gridIn)*edit.gridIn;}}
 else if(edit.action==='align'){const value=objects.reduce((n,o)=>n+o[edit.axis],0)/objects.length;for(const p of positions.values())p[edit.axis]=value;}
 else if(edit.action==='distribute'){if(objects.length<3)throw Error('Select at least three objects to distribute.');const sorted=[...objects].sort((a,b)=>a[edit.axis]-b[edit.axis]),lo=sorted[0][edit.axis],hi=sorted.at(-1)![edit.axis];sorted.forEach((o,i)=>positions.get(o.id)![edit.axis]=lo+(hi-lo)*i/(sorted.length-1));}
 const angle=edit.action==='rotate'?edit.angleDeg:0,rotation=(a:number)=>((a+angle+540)%360)-180;
 const patch={...(data.siteModel?{siteModel:{...data.siteModel,...(data.siteModel.transitions?{transitions:data.siteModel.transitions.map(t=>{const p=positions.get(t.id);if(!p)return t;const dx=p.x-t.a.points[0].x,dz=p.z-t.a.points[0].y,move=(v:PlanPoint)=>{if(edit.action!=='rotate')return {x:v.x+dx,y:v.y+dz};const a=angle*Math.PI/180,c=Math.cos(a),s=Math.sin(a),x=v.x-edit.pivotXIn,z=v.y-edit.pivotZIn;return {x:edit.pivotXIn+c*x-s*z,y:edit.pivotZIn+s*x+c*z};};return {...t,a:{...t.a,points:t.a.points.map(move)},b:{...t.b,points:t.b.points.map(move)}};})}:{})}}:{}),pools:data.pools?.map(f=>{const p=positions.get(f.id);return p?{...f,xIn:p.x,zIn:p.z,rotationDeg:rotation(f.rotationDeg)}:f;}),yardFeatures:data.yardFeatures?.map(f=>{const p=positions.get(f.id);return p?{...yardShapeMove(f,p.x-f.xFt*12,p.z-f.zFt*12),rotationDeg:rotation(f.rotationDeg)}:f;}),landscapeObjects:data.landscapeObjects?.map(f=>{const p=positions.get(f.id);return p?{...f,xIn:p.x,zIn:p.z,rotationDeg:rotation(f.rotationDeg),...(f.polygon?{polygon:f.polygon.map(v=>{const a=angle*Math.PI/180,c=Math.cos(a),s=Math.sin(a),x=v.x-f.xIn,z=v.z-f.zIn;return {x:p.x+c*x-s*z,z:p.z+s*x+c*z};})}:{})}:f;})};assertUnlockedChanges(data,{...data,...patch});if(patch.landscapeObjects){if(!validateLandscapeObjects(patch.landscapeObjects))throw Error('Transform produces an invalid landscape outline or cup position.');const candidate={...data,...patch};for(const o of patch.landscapeObjects.filter(o=>ids.includes(o.id)&&o.enabled)){if(o.kind==='bed'){if(activePuttingCups(o,landscapeBedAreas(patch.landscapeObjects,candidate).get(o.id)??[]).length!==(o.puttingCups??[]).length)throw Error('A cup intersects an excluded surface. Adjust it explicitly.');}else{const placement=landscapePlacement(candidate,o);if(placement.pendingReason)throw Error(placement.pendingReason);}}}return patch;
}
type Primitive={a:PlanPoint;b:PlanPoint;center?:PlanPoint;radius?:number;sign?:number;major?:boolean};
const dist=(a:PlanPoint,b:PlanPoint)=>Math.hypot(a.x-b.x,a.y-b.y);
function intersections(a:Primitive,b:Primitive):PlanPoint[]{
 if(!a.center&&!b.center){const dx=a.b.x-a.a.x,dy=a.b.y-a.a.y,ex=b.b.x-b.a.x,ey=b.b.y-b.a.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-8)return [{x:(a.b.x+b.a.x)/2,y:(a.b.y+b.a.y)/2}];const t=((b.a.x-a.a.x)*ey-(b.a.y-a.a.y)*ex)/den;return [{x:a.a.x+t*dx,y:a.a.y+t*dy}];}
 if(a.center&&b.center){const d=dist(a.center,b.center),r=a.radius!,s=b.radius!;if(d<1e-8||d>r+s+1e-7||d<Math.abs(r-s)-1e-7)return [];const along=(r*r-s*s+d*d)/(2*d),h=Math.sqrt(Math.max(0,r*r-along*along)),ux=(b.center.x-a.center.x)/d,uy=(b.center.y-a.center.y)/d;return [-1,1].map(side=>({x:a.center!.x+ux*along-uy*h*side,y:a.center!.y+uy*along+ux*h*side}));}
 const circle=a.center?a:b,line=a.center?b:a,c=circle.center!,r=circle.radius!,dx=line.b.x-line.a.x,dy=line.b.y-line.a.y,px=line.a.x-c.x,py=line.a.y-c.y,A=dx*dx+dy*dy,B=2*(px*dx+py*dy),C=px*px+py*py-r*r,det=B*B-4*A*C;if(det< -1e-6)return [];return [-1,1].map(sign=>{const t=(-B+sign*Math.sqrt(Math.max(0,det)))/(2*A);return {x:line.a.x+t*dx,y:line.a.y+t*dy};});
}
/** Parallel lines and circles remain analytic; ambiguous or collapsing joins reject atomically. */
export function offsetYardFeature(f:YardFeature,distanceIn:number):YardFeature{
 if(!Number.isFinite(distanceIn)||Math.abs(distanceIn)>120)throw Error('Enter a parallel offset within 10 feet.');if(!distanceIn)return f;const points=yardShapeWorldPoints(f),closed=f.kind==='patio',n=points.length-(closed?0:1);
 const primitives:Primitive[]=Array.from({length:n},(_,i)=>{const a=points[i],b=points[(i+1)%points.length],curve=f.curves?.find(c=>c.edge===i);if(curve){const g=arcGeometry(a,b,curve.bulgeIn),sign=Math.sign(curve.bulgeIn),radius=g.radius+sign*distanceIn;if(radius<1)throw Error('Offset collapses a circular segment.');const radial=(p:PlanPoint)=>({x:g.center.x+(p.x-g.center.x)*radius/g.radius,y:g.center.y+(p.y-g.center.y)*radius/g.radius});return {a:radial(a),b:radial(b),center:g.center,radius,sign,major:Math.abs(curve.bulgeIn)>dist(a,b)/2};}const len=dist(a,b),nx=-(b.y-a.y)/len,ny=(b.x-a.x)/len;return {a:{x:a.x+nx*distanceIn,y:a.y+ny*distanceIn},b:{x:b.x+nx*distanceIn,y:b.y+ny*distanceIn}};});
 const next=points.map((p,i)=>{if(!closed&&i===0)return primitives[0].a;if(!closed&&i===points.length-1)return primitives.at(-1)!.b;const candidates=intersections(primitives[(i+n-1)%n],primitives[i]).sort((a,b)=>dist(a,p)-dist(b,p));if(!candidates.length||dist(candidates[0],p)>Math.abs(distanceIn)*8+1)throw Error('Parallel offset has an unresolved join. Reduce the offset.');return candidates[0];});
 let result=yardShapeEdit({...f,curves:undefined,wallTopSteps:undefined},next);const curves=primitives.flatMap((p,i)=>{if(!p.center)return [];const a=next[i],b=next[(i+1)%next.length],half=dist(a,b)/2;if(half>p.radius!+1e-6)throw Error('Offset arc endpoints cannot fit its radius.');const s=Math.sqrt(Math.max(0,p.radius!**2-half**2));return [{edge:i,bulgeIn:p.sign!*(p.radius!+(p.major?s:-s))}];});for(const c of curves)result=curveYardEdge(result,c.edge,c.bulgeIn);return validateYardFinishedSettings({...result,wallTopSteps:f.wallTopSteps});
}
export function setYardRadius(f:YardFeature,edge:number,radiusIn:number,side=1){const points=yardShapeLocalPoints(f);if(!points[edge]||!points[(edge+1)%points.length])throw Error('Choose an existing edge.');return curveYardEdge(f,edge,bulgeForRadius(points[edge],points[(edge+1)%points.length],radiusIn,side));}
