import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import type {DeckData} from './types';
import {DEFAULT_DECK} from './defaults';
import {prepareDesignUpdate} from './designer/designUpdate';
import {applyShowcaseSearch,getShowcaseFlags,getShowcaseServerFlags,setShowcaseFlags,subscribeShowcase} from './showcaseMode';
export function portableReplacement(current:DeckData,next:DeckData):Partial<DeckData>{
 const keys=new Set([...Object.keys(current),...Object.keys(DEFAULT_DECK),...Object.keys(next)]),privateKeys=new Set(['quoteResolutions','pergolaQuoteCosts','materialMarkup','customLaborCost','customOverrides','featureLabour','addOnTransitionLabor','addOnHardwareCost','addOnFlashingLf','customerName','projectAddress','scopeOfWork','generatedImageUrl','isGeneratingImage']);
 return Object.fromEntries([...keys].filter(k=>!privateKeys.has(k)).map(k=>[k,(next as unknown as Record<string,unknown>)[k]])) as Partial<DeckData>;
}
export default function ProjectFileTools({data,onChange}:{data:DeckData;onChange:(patch:Partial<DeckData>)=>void}){
 const input=useRef<HTMLInputElement>(null),latest=useRef(data);latest.current=data;const [includeSurvey,setIncludeSurvey]=useState(false),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[stillBusy,setStillBusy]=useState(false),pending=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const presentation=useSyncExternalStore(subscribeShowcase,getShowcaseFlags,getShowcaseServerFlags);
 useEffect(()=>{applyShowcaseSearch();},[]);
 useEffect(()=>{const listener=(e:Event)=>{const d=(e as CustomEvent<{busy:boolean;error?:string;filename?:string}>).detail;if(pending.current)clearTimeout(pending.current);setStillBusy(d.busy);setStatus(d.error??(d.busy?'Rendering the current design…':d.filename?`Exported ${d.filename}.`:'Scene export ready.'));};window.addEventListener('deckcraft:export-still-status',listener);return()=>{window.removeEventListener('deckcraft:export-still-status',listener);if(pending.current)clearTimeout(pending.current);};},[]);
 const save=async()=>{setBusy(true);try{const {exportProjectBundle}=await import('./projectBundle'),blob=await exportProjectBundle(latest.current,{includeSurvey}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Golden-Maple.deckcraft.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Project exported. Customer fields and private prices are excluded; custom labels remain.');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}};
 const open=async(file:File)=>{setBusy(true);const before=latest.current;try{const {importProjectBundle}=await import('./projectBundle'),next=await importProjectBundle(file);if(next.siteModel)await (await import('./siteSurface')).loadSiteEngine();if(latest.current!==before)throw Error('The design changed during import. Import again against the current design.');const patch=portableReplacement(before,next);prepareDesignUpdate(before,patch);onChange(patch);setStatus('Project imported as one undoable change. Current private inputs are retained.');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}};
 const still=(width:number)=>{setStatus('Preparing the current 3D scene…');pending.current=setTimeout(()=>setStatus('Open a 3D view, then export its current camera.'),1000);window.dispatchEvent(new CustomEvent('deckcraft:export-still',{detail:{width}}));};
 return <details className="dd-advanced"><summary>Portable site project &amp; presentation</summary><label className="dd-check"><input type="checkbox" checked={includeSurvey} onChange={e=>setIncludeSurvey(e.target.checked)}/>Include survey attachment in the exported file</label><label className="dd-check"><input type="checkbox" checked={presentation.quality} onChange={e=>setShowcaseFlags({quality:e.target.checked})}/>Showcase quality for this view and stills</label><label className="dd-check"><input type="checkbox" checked={presentation.context} onChange={e=>setShowcaseFlags({context:e.target.checked})}/>Neighbourhood around the yard</label><div className="dd-summary-actions"><button type="button" className="dd-secondary" disabled={busy} onClick={()=>void save()}>Export project ZIP</button><button type="button" className="dd-secondary" disabled={busy} onClick={()=>input.current?.click()}>Import project ZIP</button>{[2048,4096].map(width=><button type="button" key={width} className="dd-secondary" disabled={stillBusy} onClick={()=>still(width)}>Export {width===2048?'2K':'4K'} still (long edge)</button>)}</div><input ref={input} type="file" hidden accept=".zip,application/zip" aria-label="Import portable project ZIP" onChange={e=>{const file=e.target.files?.[0];if(file)void open(file);}}/><p>Use the Daylight or Evening scene setting for consistent presentation. Showcase quality and the neighbourhood are for the 3D view, stills and fly-throughs only: they are not saved, and they do not change colours, quantities or prices. The same switches are <code>?deck-quality=showcase</code> and <code>?deck-context=1</code>. Survey files can contain addresses; include them only when needed.</p>{status&&<p role="status">{status}</p>}</details>;
}
