import type {QuoteResolution} from './types';
import type {QuoteScope} from './quoteResolutions';
export const QUOTE_RESOLUTION_LIMITS={count:100,bytes:100_000,amount:1_000_000,source:160,note:1000} as const;
const fail=(s:string):never=>{throw Error(s);};
function safe(v:unknown,depth=0):void {if(depth>5)fail('Quote records are nested too deeply.');if(v===null||typeof v==='string'||typeof v==='boolean')return;if(typeof v==='number'){if(!Number.isFinite(v))fail('Quote amounts must be finite.');return;}if(!v||typeof v!=='object'||Object.getPrototypeOf(v)!==(Array.isArray(v)?Array.prototype:Object.prototype))fail('Use plain JSON quote records.');if(Object.getOwnPropertySymbols(v).length)fail('Unsupported quote symbol.');const d=Object.getOwnPropertyDescriptors(v);if(Array.isArray(v)){if(v.length>100)fail('Keep at most 100 quote records.');for(let i=0;i<v.length;i++)if(!Object.hasOwn(d,String(i)))fail('Sparse quote records are not supported.');}for(const [k,p] of Object.entries(d)){if(Array.isArray(v)&&k==='length')continue;if(!('value'in p)||!p.enumerable||['__proto__','constructor','prototype'].includes(k)||Array.isArray(v)&&(!/^(0|[1-9]\d*)$/.test(k)||Number(k)>=(v as unknown[]).length))fail('Unsupported quote field or accessor.');safe(p.value,depth+1);}}
export function validateQuoteResolutions(value:unknown):QuoteResolution[]{
 safe(value);if(!Array.isArray(value))fail('Quote records must be an array.');const seen=new Set<string>();
 const out=(value as unknown[]).map(v=>{if(!v||typeof v!=='object'||Array.isArray(v))fail('Invalid quote record.');const r=v as Record<string,unknown>,keys=['scopeKey','fingerprint','supplyCost','installationCost','confirmedOn','source','note','additionalScope'];if(Object.keys(r).length!==keys.length||keys.some(k=>!Object.hasOwn(r,k)))fail('Quote record has missing or unsupported fields.');if(typeof r.scopeKey!=='string'||!/^quote-[a-f0-9]{16}$/.test(r.scopeKey)||typeof r.fingerprint!=='string'||!/^scope-[a-f0-9]{16}$/.test(r.fingerprint))fail('Invalid quote scope identifier.');for(const k of ['supplyCost','installationCost'])if(typeof r[k]!=='number'||!Number.isFinite(r[k])||Number(r[k])<0||Number(r[k])>QUOTE_RESOLUTION_LIMITS.amount||Math.abs(Number(r[k])*100-Math.round(Number(r[k])*100))>1e-6)fail('Use nonnegative CAD amounts with at most two decimals.');if(Number(r.supplyCost)+Number(r.installationCost)<=0)fail('Enter a confirmed additional cost; blank or zero totals cannot resolve a quote.');if(typeof r.confirmedOn!=='string'||!/^\d{4}-\d\d-\d\d$/.test(r.confirmedOn)||!Number.isFinite(Date.parse(r.confirmedOn))||new Date(r.confirmedOn).toISOString().slice(0,10)!==r.confirmedOn)fail('Use a valid confirmation date.');if(typeof r.source!=='string'||!r.source.trim()||r.source.length>160||/[\u0000-\u001f]/.test(r.source)||typeof r.note!=='string'||!r.note.trim()||r.note.length>1000||/[\u0000-\u001f]/.test(r.note)||r.additionalScope!==true)fail('Identify the source and covered additional scope.');const key=`${r.scopeKey}:${r.fingerprint}`;if(seen.has(key))fail('This scope has already been confirmed for this design.');seen.add(key);return {...r,source:(r.source as string).trim(),note:(r.note as string).trim()} as unknown as QuoteResolution;});if(new TextEncoder().encode(JSON.stringify(out)).length>QUOTE_RESOLUTION_LIMITS.bytes)fail('Quote records exceed 100 KB.');return out;
}
export function confirmQuoteScope(scope:QuoteScope,input:Omit<QuoteResolution,'scopeKey'|'fingerprint'|'additionalScope'>):QuoteResolution {return validateQuoteResolutions([{...input,scopeKey:scope.key,fingerprint:scope.fingerprint,additionalScope:true}])[0];}
