/** Presentation only. Camera coordinates use project inches and never feed takeoffs. */
export interface SavedSceneCamera {id:string;name:string;positionIn:[number,number,number];targetIn:[number,number,number];fov:number}
export interface ScenePresentation {viewMode?:'finished'|'inspection';cameraPreset?:'terrace'|'pool'|'wall';activeCameraId?:string;cameras?:SavedSceneCamera[]}
export function validateScenePresentation(value:unknown):ScenePresentation{
 const dense=(v:unknown,max:number):unknown[]=>{if(!Array.isArray(v)||Object.getPrototypeOf(v)!==Array.prototype||v.length>max||Object.getOwnPropertySymbols(v).length)throw Error('Camera lists must use plain arrays.');const ds=Object.getOwnPropertyDescriptors(v);if(Object.entries(ds).some(([k,d])=>k!=='length'&&(!/^\d+$/.test(k)||Number(k)>=v.length||!d.enumerable||!('value'in d)))||Array.from({length:v.length},(_,i)=>i).some(i=>!Object.hasOwn(ds,String(i))))throw Error('Camera lists must contain plain entries.');return v;};
 const plain=(v:unknown,keys:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v))||Object.getOwnPropertySymbols(v).length)throw Error('Scene settings must be plain data.');const ds=Object.getOwnPropertyDescriptors(v);if(Object.entries(ds).some(([k,d])=>!keys.includes(k)||!d.enumerable||!('value'in d)))throw Error('Unsupported scene settings.');return v as Record<string,unknown>;};
 const r=plain(value,['viewMode','cameraPreset','activeCameraId','cameras']),out:ScenePresentation={};
 if(r.viewMode!==undefined){if(r.viewMode!=='finished'&&r.viewMode!=='inspection')throw Error('Choose finished or inspection view.');out.viewMode=r.viewMode;}
 if(r.cameraPreset!==undefined){if(!['terrace','pool','wall'].includes(r.cameraPreset as string))throw Error('Unsupported scene camera preset.');out.cameraPreset=r.cameraPreset as ScenePresentation['cameraPreset'];}
 const label=(v:unknown)=>{if(typeof v!=='string'||!v.trim()||v.length>100||/[\u0000-\u001f]/.test(v))throw Error('Invalid camera label.');return v;};
 if(r.cameras!==undefined){const ids=new Set<string>();out.cameras=dense(r.cameras,12).map(c=>{const p=plain(c,['id','name','positionIn','targetIn','fov']),id=label(p.id);if(ids.has(id))throw Error('Camera IDs must be unique.');ids.add(id);const vec=(v:unknown):[number,number,number]=>{const a=dense(v,3);if(a.length!==3||!a.every(n=>typeof n==='number'&&Number.isFinite(n)&&Math.abs(n)<=1_200_000))throw Error('Invalid camera coordinates.');return [...a] as [number,number,number];};const positionIn=vec(p.positionIn),targetIn=vec(p.targetIn);if(Math.hypot(...positionIn.map((n,i)=>n-targetIn[i]))<1)throw Error('Camera must be separated from its target.');if(typeof p.fov!=='number'||!Number.isFinite(p.fov)||p.fov<15||p.fov>80)throw Error('Camera field of view must be 15–80 degrees.');return {id,name:label(p.name),positionIn,targetIn,fov:p.fov};});}
 if(r.activeCameraId!==undefined){out.activeCameraId=label(r.activeCameraId);if(!out.cameras?.some(c=>c.id===out.activeCameraId))throw Error('The active scene camera is missing.');}
 return out;
}
