import type {YardFeature} from './types';
import {plainAssembly,validateStoneSteps} from './stoneSteps';

export interface StepStock {name:string;widthIn:number;depthIn:number;thicknessIn:number;jointIn:number;color:string;productId?:string;finishId?:string;unitId?:string;sourceURL?:string;installationNote?:string}
export type StepPart='tread'|'riser'|'support'|'landing';
export interface StepRowOverride {row:number;widthIn?:number;tread?:StepStock;riser?:StepStock;support?:StepStock;courses?:number;riserCourses?:number;setbackIn?:number;overhangIn?:number}
export interface StepFlight {id:string;name:string;layout:'straight'|'flared'|'curved'|'wraparound';xIn:number;zIn:number;rotationDeg:number;lowerElevationIn:number;upperElevationIn:number;rows:number;widthIn:number;runIn:number;wideningIn:number;radiusIn:number;sweepDeg:number;wrapDepthIn:number;wrapSides:('front'|'left'|'right'|'back')[];courses:number[];riserCourses:number[];rowOverrides:StepRowOverride[];tread?:StepStock;riser?:StepStock;support?:StepStock;lowerLandingId?:string;upperLandingId?:string}
export interface StepLanding {id:string;name:string;xIn:number;zIn:number;rotationDeg:number;widthIn:number;depthIn:number;elevationIn:number;courses:number;tread?:StepStock;support?:StepStock}
export interface StepAssembly {version:1;family:'manufactured'|'cap-block'|'natural-stone';tread:StepStock;riser?:StepStock;support?:StepStock;supportMode:'full-step'|'wall-block'|'filler'|'aggregate';baseDepthIn:number;settingBedIn:number;overhangIn:number;setbackIn:number;installationNote:string;retainsGround:boolean;retainingDesignNote:string;flights:StepFlight[];landings:StepLanding[]}
const numeric=(v:unknown,min:number,max:number,label:string)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error(`${label} must be between ${min} and ${max}.`);return v;};
const text=(v:unknown,label:string,empty=false)=>{if(typeof v!=='string'||(!empty&&!v.trim())||v.length>800||/[\u0000-\u001f]/.test(v))throw Error(`Record a plain ${label}.`);return v;};
function list(v:unknown,max:number,label:string):unknown[]{if(!Array.isArray(v)||Object.getPrototypeOf(v)!==Array.prototype||v.length>max)throw Error(`Invalid ${label}.`);const d=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(v).length!==v.length+1||Array.from({length:v.length},(_,i)=>d[i]).some(x=>!x||!x.enumerable||!('value'in x)))throw Error(`${label} must be a dense array of plain values.`);return v;}
const integers=(v:unknown,rows:number,label:string)=>{const a=list(v,20,label);if(a.length!==rows)throw Error(`${label} needs one count per row.`);return a.map(n=>{numeric(n,0,20,label);if(!Number.isInteger(n))throw Error(`${label} must use whole courses.`);return n as number;});};
export function validateStepStock(raw:unknown):StepStock{const s=plainAssembly(raw,['name','widthIn','depthIn','thicknessIn','jointIn','color'],['name','widthIn','depthIn','thicknessIn','jointIn','color','productId','finishId','unitId','sourceURL','installationNote']);text(s.name,'stock name');for(const k of ['widthIn','depthIn'] as const)numeric(s[k],1,120,`Stock ${k}`);numeric(s.thicknessIn,.25,24,'Stock thickness');numeric(s.jointIn,0,2,'Stock joint');if(typeof s.color!=='string'||!/^#[0-9a-f]{6}$/i.test(s.color))throw Error('Choose a stock colour.');for(const k of ['productId','finishId','unitId','installationNote'] as const)if(s[k]!==undefined)text(s[k],k);if(s.sourceURL!==undefined){const u=new URL(text(s.sourceURL,'source URL'));if(u.protocol!=='https:'||u.username||u.password)throw Error('Stock sources require HTTPS without credentials.');}return s as unknown as StepStock;}
export function validateStepAssembly(f:YardFeature,raw:unknown):StepAssembly{
 if(f.kind!=='patio'||f.stoneSteps||f.outline||f.curves?.length||f.inlays?.length||f.patioSlope&&(f.patioSlope.xPct!==0||f.patioSlope.zPct!==0)||f.finishedElevationIn===undefined)throw Error('Advanced steps need fixed levels and their own assembly layout; remove the legacy representation only through conversion.');
 const a=plainAssembly(raw,['version','family','tread','supportMode','baseDepthIn','settingBedIn','overhangIn','setbackIn','installationNote','retainsGround','retainingDesignNote','flights','landings'],['version','family','tread','riser','support','supportMode','baseDepthIn','settingBedIn','overhangIn','setbackIn','installationNote','retainsGround','retainingDesignNote','flights','landings']);
 if(a.version!==1||!['manufactured','cap-block','natural-stone'].includes(String(a.family))||!['full-step','wall-block','filler','aggregate'].includes(String(a.supportMode))||typeof a.retainsGround!=='boolean')throw Error('Choose a supported step assembly.');
 const tread=validateStepStock(a.tread),riser=a.riser===undefined?undefined:validateStepStock(a.riser),support=a.support===undefined?undefined:validateStepStock(a.support);if(a.family==='cap-block'&&!riser)throw Error('Cap-on-block steps need separately recorded riser stock.');if(a.supportMode!=='aggregate'&&a.supportMode!=='full-step'&&!support)throw Error('Record support stock separately.');
 numeric(a.baseDepthIn,1,48,'Base depth');numeric(a.settingBedIn,0,6,'Setting bed');numeric(a.overhangIn,0,12,'Overhang');numeric(a.setbackIn,0,24,'Support setback');text(a.installationNote,'installation note',true);text(a.retainingDesignNote,'retaining design note',true);
 const ids=new Set<string>(),identity=(v:Record<string,unknown>)=>{const id=text(v.id,'identifier');if(ids.has(id))throw Error('Flight and landing IDs must be unique.');ids.add(id);text(v.name,'name');};
 const flights=list(a.flights,8,'flights').map(raw=>{const p=plainAssembly(raw,['id','name','layout','xIn','zIn','rotationDeg','lowerElevationIn','upperElevationIn','rows','widthIn','runIn','wideningIn','radiusIn','sweepDeg','wrapDepthIn','wrapSides','courses','riserCourses','rowOverrides'],['id','name','layout','xIn','zIn','rotationDeg','lowerElevationIn','upperElevationIn','rows','widthIn','runIn','wideningIn','radiusIn','sweepDeg','wrapDepthIn','wrapSides','courses','riserCourses','rowOverrides','tread','riser','support','lowerLandingId','upperLandingId']);identity(p);for(const k of ['tread','riser','support'] as const)if(p[k]!==undefined)p[k]=validateStepStock(p[k]);if(!['straight','flared','curved','wraparound'].includes(String(p.layout)))throw Error('Choose a flight layout.');for(const k of ['xIn','zIn'] as const)numeric(p[k],-3600,3600,k);numeric(p.rotationDeg,-360,360,'Flight rotation');for(const k of ['lowerElevationIn','upperElevationIn'] as const)numeric(p[k],-120000,120000,k);const rows=numeric(p.rows,1,20,'Risers');if(!Number.isInteger(rows)||Number(p.upperElevationIn)<=Number(p.lowerElevationIn))throw Error('Flights need ascending fixed levels and whole risers.');numeric(p.widthIn,12,720,'Flight width');numeric(p.runIn,4,60,'Tread run');numeric(p.wideningIn,-24,60,'Row widening');if(Number(p.widthIn)+(rows-1)*Number(p.wideningIn)<12)throw Error('Every row needs at least 12 inches of width.');numeric(p.radiusIn,12,720,'Retained radius');numeric(p.sweepDeg,5,360,'Retained sweep');numeric(p.wrapDepthIn,12,720,'Wrap landing depth');const sides=list(p.wrapSides,4,'wrap sides');if(!sides.length||new Set(sides).size!==sides.length||sides.some(x=>!['front','left','right','back'].includes(String(x))))throw Error('Choose distinct wrap sides.');
  const courses=integers(p.courses,rows,'Supporting courses'),riserCourses=integers(p.riserCourses,rows,'Riser courses'),seen=new Set<number>();const rowOverrides=list(p.rowOverrides,20,'row overrides').map(raw=>{const r=plainAssembly(raw,['row'],['row','widthIn','tread','riser','support','courses','riserCourses','setbackIn','overhangIn']);const row=numeric(r.row,0,rows-1,'Row');if(!Number.isInteger(row)||seen.has(row))throw Error('Row overrides must identify distinct present rows.');seen.add(row);if(r.widthIn!==undefined)numeric(r.widthIn,12,720,'Row width');for(const k of ['tread','riser','support'] as const)if(r[k]!==undefined)r[k]=validateStepStock(r[k]);for(const k of ['courses','riserCourses'] as const)if(r[k]!==undefined){numeric(r[k],0,20,k);if(!Number.isInteger(r[k]))throw Error('Use whole courses.');}for(const k of ['overhangIn','setbackIn'] as const)if(r[k]!==undefined)numeric(r[k],0,k==='overhangIn'?12:24,k);return r as unknown as StepRowOverride;});for(const k of ['lowerLandingId','upperLandingId'] as const)if(p[k]!==undefined)text(p[k],k);return {...p,courses,riserCourses,rowOverrides} as unknown as StepFlight;});
 if(!flights.length)throw Error('Add at least one flight.');
 const landings=list(a.landings,16,'landings').map(raw=>{const p=plainAssembly(raw,['id','name','xIn','zIn','rotationDeg','widthIn','depthIn','elevationIn','courses'],['id','name','xIn','zIn','rotationDeg','widthIn','depthIn','elevationIn','courses','tread','support']);identity(p);for(const k of ['xIn','zIn'] as const)numeric(p[k],-3600,3600,k);numeric(p.rotationDeg,-360,360,'Landing rotation');for(const k of ['widthIn','depthIn'] as const)numeric(p[k],12,720,k);numeric(p.elevationIn,-120000,120000,'Landing elevation');numeric(p.courses,0,20,'Landing courses');if(!Number.isInteger(p.courses))throw Error('Use whole landing courses.');for(const k of ['tread','support'] as const)if(p[k]!==undefined)p[k]=validateStepStock(p[k]);return p as unknown as StepLanding;});
 for(const p of flights)for(const [k,level] of [['lowerLandingId',p.lowerElevationIn],['upperLandingId',p.upperElevationIn]] as const)if(p[k]){const l=landings.find(l=>l.id===p[k]);if(!l||Math.abs(l.elevationIn-level)>1e-6)throw Error(`Landing ${p[k]} must exist at its connected flight elevation; adjust explicitly.`);}
 const upper=Math.max(...flights.map(p=>p.upperElevationIn),...landings.map(l=>l.elevationIn));if(Math.abs(f.finishedElevationIn-upper)>1e-6)throw Error('Feature finished top must match its highest flight or landing.');
 return {...a,tread,...(riser?{riser}:{}),...(support?{support}:{}),flights,landings} as unknown as StepAssembly;
}
export function convertStoneSteps(f:YardFeature):YardFeature{const s=validateStoneSteps(f,f.stoneSteps),stock:StepStock={name:s.productName,widthIn:s.stockWidthIn,depthIn:s.stockDepthIn,thicknessIn:s.stockThicknessIn,jointIn:s.jointIn,color:f.color,...(s.sourceURL?{sourceURL:s.sourceURL}:{})};const filler=s.support?.kind==='filler'?{name:s.support.productName,widthIn:s.support.stockWidthIn,depthIn:s.support.stockDepthIn,thicknessIn:s.support.stockThicknessIn,jointIn:s.support.jointIn,color:f.color,...(s.support.sourceURL?{sourceURL:s.support.sourceURL}:{})}:undefined;const next={...f};delete next.stoneSteps;next.stepAssembly={version:1,family:'manufactured',tread:stock,...(filler?{support:filler}:{}),supportMode:s.support?.kind??'aggregate',baseDepthIn:s.baseDepthIn,settingBedIn:s.settingBedIn,overhangIn:0,setbackIn:0,installationNote:s.supportNote??'',retainsGround:false,retainingDesignNote:'',flights:[{id:'flight-1',name:'Flight 1',layout:'straight',xIn:0,zIn:0,rotationDeg:0,lowerElevationIn:s.lowerElevationIn,upperElevationIn:f.finishedElevationIn!,rows:s.riserCount,widthIn:f.widthFt*12,runIn:s.treadRunIn,wideningIn:0,radiusIn:96,sweepDeg:90,wrapDepthIn:48,wrapSides:['front','left','right'],courses:s.support?.courses??Array(s.riserCount).fill(0),riserCourses:Array(s.riserCount).fill(0),rowOverrides:[]}],landings:[]};return {...next,stepAssembly:validateStepAssembly(next,next.stepAssembly)};}
