import type {YardFeature} from './types';
import type {PlanPoint} from './lib/deckGeometry';
import type {SiteSurface} from './siteSurface';
import {integrateSiteFeatureFill,sitePolygonsBelowGround} from './siteSurface';
import {yardArea,yardClip,yardSolidCells,yardRectangle,type YardBox,type YardFeatureModel} from './yardModel';
import {yardToWorld} from './yardPathGeometry';
import {abovePlane,planeVolume,subtractPlanes} from './yardElevationGeometry';
import {validateStepAssembly as parseAssembly,convertStoneSteps,type StepAssembly,type StepStock,type StepFlight,type StepLanding,type StepRowOverride} from './stepAssembly';
import {registerStepAssemblyRuntime} from './stepAssemblyRegistry';
import {HARDSCAPE_PRODUCTS,rectangularUnit} from './hardscapeCatalogue';
export {convertStoneSteps};
const EPS=1e-6;
interface Row {flightId:string;row:number;landing:boolean;top:number;stock:StepStock;support:StepStock;riser?:StepStock;courses:number;riserCourses:number;overhang:number;setback:number;polys:PlanPoint[][];flight?:StepFlight;landingSpec?:StepLanding}
const transform=(polys:PlanPoint[][],x:number,z:number,angle:number)=>polys.map(p=>p.map(v=>{const a=angle*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return {x:x+c*v.x-s*v.y,y:z+s*v.x+c*v.y};}));
function ring(inner:number,outer:number,sweep:number){const n=Math.max(8,Math.ceil(sweep/1.5)),at=(r:number,i:number)=>{const a=(-sweep/2+sweep*i/n)*Math.PI/180;return {x:r*Math.sin(a),y:r*Math.cos(a)};};return [[...Array.from({length:n+1},(_,i)=>at(outer,i)),...Array.from({length:n+1},(_,i)=>at(inner,n-i))]];}
function rowFootprint(a:StepAssembly,p:StepFlight,row:number,stock:StepStock,overhang:number):PlanPoint[][]{
 if(p.layout==='curved'){if(p.sweepDeg<5||p.sweepDeg>360)throw Error('Row width must fit a circular sweep from 5 to 360 degrees.');return ring(p.radiusIn+(p.rows-row-1)*p.runIn,p.radiusIn+(p.rows-row)*p.runIn+overhang,p.sweepDeg);}
 if(p.layout==='wraparound'){
  const d=(p.rows-row)*p.runIn,outer=yardRectangle(0,0,p.widthIn+2*d+2*overhang,p.wrapDepthIn+2*d+2*overhang),inner=yardRectangle(0,0,p.widthIn+2*(d-p.runIn),p.wrapDepthIn+2*(d-p.runIn));let polys=yardClip([outer],[inner],'difference');
  const sideMasks=p.wrapSides.map(side=>{const w=p.widthIn/2+d+overhang,h=p.wrapDepthIn/2+d+overhang;return side==='front'?yardRectangle(0,h-(p.runIn+overhang)/2,2*w,p.runIn+overhang):side==='back'?yardRectangle(0,-h+(p.runIn+overhang)/2,2*w,p.runIn+overhang):side==='left'?yardRectangle(-w+(p.runIn+overhang)/2,0,p.runIn+overhang,2*h):yardRectangle(w-(p.runIn+overhang)/2,0,p.runIn+overhang,2*h);});return yardClip(polys,sideMasks,'intersection');
 }
 const width=p.widthIn+(p.layout==='flared'?row*p.wideningIn:0),depth=(p.rows-1)*p.runIn+(p.tread??a.tread).depthIn,front=-depth/2+row*p.runIn-overhang;
 return [yardRectangle(0,front+stock.depthIn/2,width,stock.depthIn)];
}
function rows(a:StepAssembly):Row[]{const out:Row[]=[];for(const p of a.flights)for(let row=0;row<p.rows;row++){const o=p.rowOverrides.find(o=>o.row===row),stock=o?.tread??p.tread??a.tread,support=o?.support??p.support??a.support??stock,riser=o?.riser??p.riser??a.riser,overhang=o?.overhangIn??a.overhangIn,setback=o?.setbackIn??a.setbackIn;out.push({flightId:p.id,row,landing:false,top:p.lowerElevationIn+(row+1)*(p.upperElevationIn-p.lowerElevationIn)/p.rows,stock,support,riser,courses:o?.courses??p.courses[row],riserCourses:o?.riserCourses??p.riserCourses[row],overhang,setback,polys:rowFootprint(a,o?.widthIn===undefined?p:{...p,widthIn:o.widthIn,wideningIn:0,sweepDeg:p.layout==='curved'?o.widthIn/(p.radiusIn+(p.rows-row-.5)*p.runIn)*180/Math.PI:p.sweepDeg},row,stock,overhang),flight:p});}for(const p of a.landings)out.push({flightId:p.id,row:0,landing:true,top:p.elevationIn,stock:p.tread??a.tread,support:p.support??a.support??a.tread,courses:p.courses,riserCourses:0,overhang:0,setback:0,polys:[yardRectangle(0,0,p.widthIn,p.depthIn)],landingSpec:p});return out;}
function worldPolys(f:YardFeature,r:Row,polys=r.polys){const p=r.flight??r.landingSpec!;return transform(polys,p.xIn,p.zIn,p.rotationDeg).map(poly=>poly.map(v=>yardToWorld(f,v)));}
export function stepAssemblyFootprints(f:YardFeature){if(!f.stepAssembly)return [];return yardClip(rows(parseAssembly(f,f.stepAssembly)).flatMap(r=>worldPolys(f,r)));}
export function buildStepAssemblyModel(f:YardFeature,site:SiteSurface|undefined,ground:{x:number;z:number;constant:number}){
 const a=parseAssembly(f,f.stepAssembly);
 for(const stock of [a.tread,a.riser,a.support,...a.flights.flatMap(p=>[p.tread,p.riser,p.support,...p.rowOverrides.flatMap(o=>[o.tread,o.riser,o.support])]),...a.landings.flatMap(p=>[p.tread,p.support])].filter((s):s is StepStock=>!!s))if(stock.productId){const p=HARDSCAPE_PRODUCTS.find(p=>p.id===stock.productId),finish=p?.finishes.find(s=>s.id===stock.finishId),unit=finish?.units.find(u=>u.id===stock.unitId);if(!unit||!rectangularUnit(unit)||Math.abs(unit.widthMm/25.4-stock.widthIn)>.00001||Math.abs(unit.lengthMm/25.4-stock.depthIn)>.00001||Math.abs(unit.heightMm/25.4-stock.thicknessIn)>.00001)throw Error('Referenced stock must retain its catalogue dimensions. Choose custom stock for an explicit dimensional change.');}
 const boxes:YardBox[]=[],formations:{featureId:string;polys:PlanPoint[][];bottom:number}[]=[],warnings:string[]=[],conflicts:string[]=[],schedule:NonNullable<YardFeatureModel['stockSchedule']>=[],allRows=rows(a);
 const q:Record<string,number>={stoneStepPieces:0,stoneStepCuts:0,stoneStepAreaSqft:0,stoneStepRisers:a.flights.reduce((n,p)=>n+p.rows,0),stoneStepRiseIn:0,stoneSupportStepPieces:0,stoneSupportStepCuts:0,stoneFillerPieces:0,stoneFillerCuts:0,stepRiserBlocks:0,stepRiserCuts:0,stepSupportBlocks:0,stepSupportBlockCuts:0,stepLandingPieces:0,stepLandingCuts:0,stoneSupportVolumeYd3:0,unsupportedBearingAreaSqft:0,buriedTreadAreaSqft:0,baseYd3:0,beddingYd3:0,raisedFillYd3:0,stepEngineeredFillYd3:0,paverPieces:0,paverAreaSqft:0};
 const add=(r:Row,polys:PlanPoint[][],top:number,height:number,role:YardBox['role'],part:YardBox['stonePart'],stock?:StepStock,slot=0,course=0)=>{for(const [i,p] of polys.entries()){if(yardArea([p])<EPS||height<=0)continue;if(boxes.length>=20000)throw Error('Step assembly exceeds the shared 20,000-solid geometry budget.');const world=worldPolys(f,r,[p])[0],xs=world.map(p=>p.x),zs=world.map(p=>p.y);boxes.push({id:`${f.id}:${r.flightId}:${r.row}:${part??role}:${course}:${slot}:${i}:${boxes.length}`,featureId:f.id,role,stonePart:part,stepFlightId:r.flightId,stepRow:r.row,color:stock?.color??(role==='base'?'#92958e':'#b0a489'),polygon:world,x:(Math.min(...xs)+Math.max(...xs))/2,z:(Math.min(...zs)+Math.max(...zs))/2,y:top-height/2,w:Math.max(...xs)-Math.min(...xs),d:Math.max(...zs)-Math.min(...zs),h:height});}}
 const tile=(r:Row,mask:PlanPoint[][],stock:StepStock,top:number,part:NonNullable<YardBox['stonePart']>,course=0)=>{
  if(!mask.length)return [];const pts=mask.flat(),minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minZ=Math.min(...pts.map(p=>p.y)),maxZ=Math.max(...pts.map(p=>p.y)),nx=Math.ceil((maxX-minX)/(stock.widthIn+stock.jointIn)),nz=Math.ceil((maxZ-minZ)/(stock.depthIn+stock.jointIn));if(nx*nz+boxes.length>20000)throw Error('Step assembly exceeds the shared 20,000-unit geometry budget. Choose larger stock or a smaller layout.');
  const laid:PlanPoint[][]=[];let slot=0;for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const x=minX+i*(stock.widthIn+stock.jointIn),z=minZ+j*(stock.depthIn+stock.jointIn),blank=yardRectangle(x+stock.widthIn/2,z+stock.depthIn/2,stock.widthIn,stock.depthIn),polys=yardSolidCells(yardClip([blank],mask,'intersection'));if(!polys.length)continue;const cut=Math.abs(yardArea(polys)*144-stock.widthIn*stock.depthIn)>1e-4;laid.push(...polys);add(r,polys,top,stock.thicknessIn,'stone-step',part,stock,slot++,course);
   const key=part==='tread'?'stoneStep':part==='landing'?'stepLanding':part==='support-step'?'stoneSupportStep':part==='filler'?'stoneFiller':part==='riser-block'?'stepRiser':'stepSupportBlock';q[part==='support-block'?'stepSupportBlocks':key+(part==='riser-block'?'Blocks':'Pieces')]++;if(cut)q[part==='support-block'?'stepSupportBlockCuts':key+'Cuts']++;
   let order=schedule.find(o=>o.unitId===stock.name&&o.assemblyPart===part&&o.widthMm===stock.widthIn*25.4&&o.lengthMm===stock.depthIn*25.4&&o.heightMm===stock.thicknessIn*25.4);if(!order){order={unitId:stock.name,productId:stock.productId,widthMm:stock.widthIn*25.4,lengthMm:stock.depthIn*25.4,heightMm:stock.thicknessIn*25.4,pieces:0,cuts:0,assemblyPart:part};schedule.push(order);}order.pieces++;if(cut)order.cuts!++;
  }return laid;
 };
 let claimed:PlanPoint[][]=[];
 for(const r of allRows){
  const bodyWorld=worldPolys(f,r),baseWorld=yardClip(bodyWorld,claimed,'difference');claimed=yardClip([...claimed,...bodyWorld]);
  const others=allRows.filter(o=>o!==r&&Math.abs(o.top-r.top)<EPS).flatMap(o=>worldPolys(f,o));if(others.length&&yardArea(yardClip(bodyWorld,others,'intersection'))>.001)warnings.push('Coincident walking surfaces need explicit shared landing boundaries; overlapping stock is not silently merged.');
  const treadPolys=tile(r,r.polys,r.stock,r.top,r.landing?'landing':'tread'),under=r.top-r.stock.thicknessIn;
  q.stoneStepAreaSqft+=yardArea(bodyWorld);const upperPolys=allRows.filter(o=>o.top>r.top+EPS).flatMap(o=>worldPolys(f,o)),exposed=yardClip(worldPolys(f,r,treadPolys),upperPolys,'difference');q.buriedTreadAreaSqft+=site?yardArea(sitePolygonsBelowGround(site,exposed,r.top+.075)):yardSolidCells(exposed).reduce((n,p)=>n+yardArea([abovePlane(p,subtractPlanes(ground,{x:0,z:0,constant:r.top+.075}))]),0);
  let supportMask=r.polys,riserMask:PlanPoint[][]=[];
  const radialMask=(depth:number,offset:number)=>{const flight=r.flight!;if(flight.layout==='curved'){const inner=flight.radiusIn+(flight.rows-r.row-1)*flight.runIn,outer=flight.radiusIn+(flight.rows-r.row)*flight.runIn+r.overhang-offset;return outer>inner?ring(Math.max(inner,outer-depth),outer,flight.sweepDeg):[];}const d=(flight.rows-r.row)*flight.runIn,ow=flight.widthIn+2*d+2*r.overhang-2*offset,od=flight.wrapDepthIn+2*d+2*r.overhang-2*offset;return ow>0&&od>0?yardClip([yardRectangle(0,0,ow,od)],[yardRectangle(0,0,Math.max(0,ow-2*depth),Math.max(0,od-2*depth))],'difference'):[];};
  const radial=r.flight&&['curved','wraparound'].includes(r.flight.layout);
  if(r.riser&&r.riserCourses){if(radial)riserMask=yardClip(r.polys,radialMask(r.riser.depthIn,r.setback+r.overhang),'intersection');else{const pts=r.polys.flat(),front=Math.min(...pts.map(p=>p.y)),w=Math.max(...pts.map(p=>p.x))-Math.min(...pts.map(p=>p.x)),center=(Math.max(...pts.map(p=>p.x))+Math.min(...pts.map(p=>p.x)))/2;riserMask=yardClip(r.polys,[yardRectangle(center,front+r.setback+r.overhang+r.riser.depthIn/2,w,r.riser.depthIn)],'intersection');}supportMask=yardClip(r.polys,riserMask,'difference');}
  if(r.setback+r.overhang>EPS){if(radial)supportMask=yardClip(supportMask,radialMask(r.flight!.runIn,r.setback+r.overhang),'intersection');else{const shifted=r.polys.map(p=>p.map(v=>({x:v.x,y:v.y+r.setback+r.overhang})));supportMask=yardClip(supportMask,shifted,'intersection');}}
  const solidBefore=boxes.length,part=a.supportMode==='full-step'?'support-step':a.supportMode==='filler'?'filler':'support-block';let bearingPolys:PlanPoint[][]=[];
  for(let course=0;course<r.riserCourses;course++)if(r.riser){const laid=tile(r,riserMask,r.riser,under-course*r.riser.thicknessIn,'riser-block',course);if(course===0)bearingPolys.push(...laid);}
  if(a.supportMode!=='aggregate')for(let course=0;course<r.courses;course++){const laid=tile(r,supportMask,r.support,under-course*r.support.thicknessIn,part,course);if(course===0)bearingPolys.push(...laid);}
  const solidHeight=Math.max(a.supportMode==='aggregate'?0:r.courses*r.support.thicknessIn,(r.riser?.thicknessIn??0)*r.riserCourses),bearing=under-solidHeight;
  if(solidHeight){q.unsupportedBearingAreaSqft+=yardArea(yardClip(treadPolys,bearingPolys,'difference'));q.stoneSupportVolumeYd3+=boxes.slice(solidBefore).reduce((n,b)=>n+yardArea([b.polygon!])*b.h/324,0);}
  const p=r.flight??r.landingSpec!,inverse=(world:PlanPoint[][])=>world.map(poly=>poly.map(v=>{const angle=(f.rotationDeg+p.rotationDeg)*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),origin=yardToWorld(f,{x:p.xIn,y:p.zIn}),dx=v.x-origin.x,dz=v.y-origin.y;return {x:c*dx+s*dz,y:-s*dx+c*dz};}));
  const bearingRegions=[{mask:riserMask,height:(r.riser?.thicknessIn??0)*r.riserCourses},{mask:a.supportMode==='aggregate'?[]:supportMask,height:a.supportMode==='aggregate'?0:r.courses*r.support.thicknessIn}].filter(p=>p.height>0).sort((x,y)=>y.height-x.height);let founded:PlanPoint[][]=[];
  bearingRegions.push({mask:r.polys,height:0});
  for(const region of bearingRegions){const footprint=yardClip(yardClip(baseWorld,worldPolys(f,r,region.mask),'intersection'),founded,'difference');if(!footprint.length)continue;founded=yardClip([...founded,...footprint]);const level=under-region.height,formationBottom=level-a.settingBedIn-a.baseDepthIn;for(const poly of yardSolidCells(inverse(footprint))){add(r,[poly],level,a.settingBedIn,'bedding',undefined);add(r,[poly],level-a.settingBedIn,a.baseDepthIn,'base',undefined);}q.baseYd3+=yardArea(footprint)*a.baseDepthIn/324;q.beddingYd3+=yardArea(footprint)*a.settingBedIn/324;q.raisedFillYd3+=site?integrateSiteFeatureFill(site,footprint,formationBottom):yardSolidCells(footprint).reduce((n,p)=>{const delta=subtractPlanes({x:0,z:0,constant:formationBottom},ground);return n+Math.max(0,planeVolume(abovePlane(p,delta),delta))/46656;},0);formations.push({featureId:f.id,polys:footprint,bottom:formationBottom});}
  if(a.family==='cap-block'&&solidHeight){const rowSolids=boxes.slice(solidBefore),levels=[...new Set([bearing,under,...rowSolids.flatMap(b=>[b.y-b.h/2,b.y+b.h/2])])].filter(y=>y>=bearing-EPS&&y<=under+EPS).sort((x,y)=>x-y);for(let j=0;j+1<levels.length;j++){const lo=levels[j],hi=levels[j+1],mask=yardClip(baseWorld,rowSolids.filter(b=>b.y-b.h/2<hi-EPS&&b.y+b.h/2>lo+EPS).map(b=>b.polygon!),'difference');q.stepEngineeredFillYd3+=yardArea(mask)*(hi-lo)/324;for(const poly of yardSolidCells(inverse(mask)))add(r,[poly],hi,hi-lo,'backfill',undefined);}}

  if(r.flight){if(!r.landing&&r.row<r.flight.rows-1&&['straight','flared'].includes(r.flight.layout)&&r.flight.runIn+r.overhang-(r.flight.rowOverrides.find(o=>o.row===r.row+1)?.overhangIn??a.overhangIn)>r.stock.depthIn+EPS)warnings.push(`${r.flight.name} row ${r.row+1}: the tread run leaves an open walking gap. Adjust the run or record a separate closure/landing assembly.`);const rise=(r.flight.upperElevationIn-r.flight.lowerElevationIn)/r.flight.rows;q.stoneStepRiseIn=rise;if(rise>r.stock.thicknessIn+(r.riser?.thicknessIn??0)*r.riserCourses+EPS&&a.family==='cap-block')warnings.push(`${r.flight.name} row ${r.row+1}: finished rise exceeds the recorded cap/riser height. Foundation stepping and face closure need an entered detail.`);}
  if(!r.stock.installationNote||!a.installationNote)warnings.push(`${r.flight?.name??r.landingSpec?.name} row ${r.row+1}: stock, bearing, nosing, anchoring, frost, drainage and lifting remain planning inputs until recorded.`);
 }
 const solid=boxes.filter(b=>b.role==='stone-step'),bins=new Map<string,number[]>();
 outer:for(let i=0;i<solid.length;i++){const b=solid[i],keys:string[]=[],neighbors=new Set<number>();for(let x=Math.floor((b.x-b.w/2)/48);x<=Math.floor((b.x+b.w/2)/48);x++)for(let z=Math.floor((b.z-b.d/2)/48);z<=Math.floor((b.z+b.d/2)/48);z++){const key=x+':'+z;keys.push(key);for(const j of bins.get(key)??[])neighbors.add(j);}for(const j of neighbors){const c=solid[j];if(b.stepFlightId===c.stepFlightId&&b.stepRow===c.stepRow)continue;if(Math.min(b.y+b.h/2,c.y+c.h/2)-Math.max(b.y-b.h/2,c.y-c.h/2)<EPS||Math.abs(b.x-c.x)>(b.w+c.w)/2||Math.abs(b.z-c.z)>(b.d+c.d)/2)continue;if(yardArea(yardClip([b.polygon!],[c.polygon!],'intersection'))>.0001){conflicts.push(`Stock collision between ${b.stepFlightId} row ${Number(b.stepRow)+1} and ${c.stepFlightId} row ${Number(c.stepRow)+1}. Adjust overlap, setback or landing boundaries explicitly.`);break outer;}}for(const key of keys){const list=bins.get(key)??[];list.push(i);bins.set(key,list);}}
 const segmentDistance=(v:PlanPoint,a:PlanPoint,b:PlanPoint)=>{const dx=b.x-a.x,dz=b.y-a.y,t=Math.max(0,Math.min(1,((v.x-a.x)*dx+(v.y-a.y)*dz)/(dx*dx+dz*dz||1)));return Math.hypot(v.x-a.x-t*dx,v.y-a.y-t*dz);};
 const boundariesDistance=(a:PlanPoint[][],b:PlanPoint[][])=>{let distance=Infinity;for(const [points,segments] of [[a,b],[b,a]])for(const p of points)for(const v of p)for(const q of segments)for(let i=0;i<q.length;i++)distance=Math.min(distance,segmentDistance(v,q[i],q[(i+1)%q.length]));return distance;};
 for(const p of a.flights)for(const [id,row] of [[p.lowerLandingId,0],[p.upperLandingId,p.rows-1]] as const){if(!id)continue;const landing=allRows.find(r=>r.landing&&r.flightId===id)!,endpoint=allRows.find(r=>r.flightId===p.id&&r.row===row)!;if(boundariesDistance(worldPolys(f,landing),worldPolys(f,endpoint))>.25)warnings.push(`${p.name}: connected landing ${id} does not meet the flight endpoint. Adjust its position explicitly.`);}

 if(a.retainsGround)warnings.push('Retaining duty is unresolved: record wall burial, reinforcement, drainage, outlets and engineering inputs; no structural wall quantities are inferred from stair blocks.');if(q.unsupportedBearingAreaSqft>.001)warnings.push(`${q.unsupportedBearingAreaSqft.toFixed(3)} sq ft of tread stock lies outside modeled solid contact. Record permitted overhang/joints and bearing details; no mortar or bridging is assumed.`);
 return {boxes,formations,quantities:q,warnings:[...new Set(warnings)],conflicts,stockSchedule:schedule};
}
export function validateStepAssembly(f:YardFeature,v:unknown){const a=parseAssembly(f,v),model=buildStepAssemblyModel({...f,stepAssembly:a},undefined,{x:0,z:0,constant:0});if(model.conflicts.length)throw Error(model.conflicts[0]);return a;}
export function stepAssemblyPatch(f:YardFeature,a:StepAssembly):YardFeature{const next={...f,finishedElevationIn:Math.max(...a.flights.map(p=>p.upperElevationIn),...a.landings.map(p=>p.elevationIn)),stepAssembly:a};delete next.stoneSteps;delete next.outline;delete next.curves;delete next.inlays;delete next.patioSlope;return {...next,stepAssembly:validateStepAssembly(next,a)};}
export function stepPresets(){
 const make=(name:string,widthIn:number,depthIn:number,thicknessIn:number,sourceURL:string):StepStock=>({name,widthIn,depthIn,thicknessIn,jointIn:.125,color:'#b8b5ae',sourceURL});
 const step=make('Raffinato Step — nominal stock',1067/25.4,368/25.4,180/25.4,'https://www.techo-bloc.com/shop/steps/raffinato-step'),cap=make('Raffinato smooth cap — verify stair detail',14,28,60/25.4,'https://www.techo-bloc.com/shop/caps/raffinato-smooth-cap'),block=make('Raffinato wall block — nominal 90 mm',397/25.4,249/25.4,90/25.4,'https://www.techo-bloc.com/assets/1c/4a/1c4aed24-6f26-4b1e-b146-52b958de92ed/TB2025_Installation-guide_WALLS_EN_V2.pdf');
 for(const stock of [step,cap,block])for(const product of HARDSCAPE_PRODUCTS)for(const finish of product.finishes)for(const unit of finish.units)if(product.name.toLowerCase().includes('raffinato')&&Math.abs(unit.widthMm/25.4-stock.widthIn)<.1&&Math.abs(unit.lengthMm/25.4-stock.depthIn)<.1&&Math.abs(unit.heightMm/25.4-stock.thicknessIn)<.1)Object.assign(stock,{productId:product.id,finishId:finish.id,unitId:unit.id});
 const natural=make('Oakville natural stone step — 48 × 16 × 7 in',48,16,7,'https://www.oakvillestone.com/resources/steps-and-fillers-installation/'),filler=make('Oakville filler — verify chosen stock',31,6,7,natural.sourceURL!);
 return [{id:'manufactured',name:'Manufactured solid steps',family:'manufactured',tread:step,supportMode:'full-step',overhangIn:0,setbackIn:0,note:'Nominal stock is documented; stacking, bearing and site installation need a recorded detail.'},{id:'cap-block',name:'Cap treads on wall blocks',family:'cap-block',tread:cap,riser:block,support:block,supportMode:'wall-block',overhangIn:0,setbackIn:0,note:'Cap suitability as a tread and the wall-block stair detail require product-specific confirmation.'},{id:'natural-stone',name:'Oakville natural stone steps and fillers',family:'natural-stone',tread:natural,support:filler,supportMode:'filler',overhangIn:.75,setbackIn:0,note:'Reference Oakville steps/fillers guide. Confirm the selected stock and its filler positioning, overlap, bearing, frost and drainage detail.'}] as const;
}
registerStepAssemblyRuntime({validateStepAssembly,buildStepAssemblyModel,stepAssemblyFootprints,convertStoneSteps,stepPresets,stepAssemblyPatch});
