const numbers=(names:string)=>Object.fromEntries(names.split(' ').map(k=>[k,{type:'number'}]));
const strings=(names:string)=>Object.fromEntries(names.split(' ').map(k=>[k,{type:'string',maxLength:800}]));
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,properties,required});
const array=(items:unknown,maxItems:number)=>({type:'array',items,maxItems});
export const stepStockSchema=object({...strings('name color productId finishId unitId sourceURL installationNote'),...numbers('widthIn depthIn thicknessIn jointIn')},['name','color','widthIn','depthIn','thicknessIn','jointIn']);
export const stepRowEditSchema=object({tread:stepStockSchema,riser:stepStockSchema,support:stepStockSchema,...numbers('widthIn courses riserCourses setbackIn overhangIn')},[]);
const flightProperties={tread:stepStockSchema,riser:stepStockSchema,support:stepStockSchema,...strings('id name lowerLandingId upperLandingId'),layout:{enum:['straight','flared','curved','wraparound']},...numbers('xIn zIn rotationDeg lowerElevationIn upperElevationIn rows widthIn runIn wideningIn radiusIn sweepDeg wrapDepthIn'),wrapSides:array({enum:['front','left','right','back']},4),courses:array({type:'integer',minimum:0,maximum:20},20),riserCourses:array({type:'integer',minimum:0,maximum:20},20),rowOverrides:array(object({row:{type:'integer',minimum:0,maximum:19},...stepRowEditSchema.properties},['row']),20)};
export const stepAssemblySchema=object({version:{const:1},family:{enum:['manufactured','cap-block','natural-stone']},tread:stepStockSchema,riser:stepStockSchema,support:stepStockSchema,supportMode:{enum:['full-step','wall-block','filler','aggregate']},...numbers('baseDepthIn settingBedIn overhangIn setbackIn'),...strings('installationNote retainingDesignNote'),retainsGround:{type:'boolean'},flights:array(object(flightProperties,Object.keys(flightProperties).filter(k=>!['tread','riser','support','lowerLandingId','upperLandingId'].includes(k))),8),landings:array(object({...strings('id name'),...numbers('xIn zIn rotationDeg widthIn depthIn elevationIn courses'),tread:stepStockSchema,support:stepStockSchema},['id','name','xIn','zIn','rotationDeg','widthIn','depthIn','elevationIn','courses']),16)},['version','family','tread','supportMode','baseDepthIn','settingBedIn','overhangIn','setbackIn','installationNote','retainingDesignNote','retainsGround','flights','landings']);
/** The controller's structural filter uses the same fields as the assistant JSON schema. */
export function stepControllerSchema(schema:unknown):any{const s=schema as {type?:string;properties?:Record<string,unknown>;items?:unknown};return s.properties?Object.fromEntries(Object.entries(s.properties).map(([k,v])=>[k,stepControllerSchema(v)])):s.type==='array'?[stepControllerSchema(s.items)]:true;}
