import {useEffect,useRef,useState} from 'react';
import type {DeckData} from './types';
import {putSurveyAttachment} from './surveyAttachments';
type ImageDraft={blob:Blob;url:string;width:number;height:number;name:string};
export default function SurveyWizard({data,onChange}:{data:DeckData;onChange:(patch:Partial<DeckData>)=>void}){
 const current=useRef(data);current.current=data;
 const [image,setImage]=useState<ImageDraft>(),[line,setLine]=useState<{x:number;y:number}[]>([]),[distance,setDistance]=useState('20'),[unit,setUnit]=useState('ft'),[rotation,setRotation]=useState('0'),[across,setAcross]=useState('0'),[out,setOut]=useState('0'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[pageCount,setPageCount]=useState(0);
 const pdf=useRef<any>(null),generation=useRef(0);
 useEffect(()=>()=>{generation.current++;void pdf.current?.destroy();},[]);
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image.url);},[image]);
 const showImage=async(blob:Blob,name:string,token:number)=>{let bitmap=await createImageBitmap(blob);if(bitmap.width*bitmap.height>40_000_000){bitmap.close();throw Error('Survey raster exceeds 40 megapixels. Resize it before import.');}if(Math.max(bitmap.width,bitmap.height)>4096){const scale=4096/Math.max(bitmap.width,bitmap.height),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Survey raster could not be resized.')),'image/png'));bitmap=await createImageBitmap(blob);}if(token!==generation.current){bitmap.close();return;}const next={blob,name,url:URL.createObjectURL(blob),width:bitmap.width,height:bitmap.height};bitmap.close();setImage(next);setLine([]);};
 const renderPage=async(n:number,token=generation.current)=>{try{setBusy(true);setError('');const p=await pdf.current.getPage(n),view=p.getViewport({scale:1}),scale=Math.min(2,4096/Math.max(view.width,view.height)),v=p.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);await p.render({canvasContext:canvas.getContext('2d')!,viewport:v,canvas}).promise;const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('PDF page could not be rendered.')),'image/png'));await showImage(blob,`Survey page ${n}`,token);}catch(e){if(token===generation.current)setError((e as Error).message);}finally{if(token===generation.current)setBusy(false);}};
 const choose=async(file:File)=>{const token=++generation.current;setBusy(true);setError('');try{if(file.size>25*1024*1024)throw Error('Choose a survey file smaller than 25 MB.');await pdf.current?.destroy();pdf.current=null;setPageCount(0);if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){const lib=await import('pdfjs-dist/build/pdf.mjs');const worker=await import('pdfjs-dist/build/pdf.worker.min.mjs?url');lib.GlobalWorkerOptions.workerSrc=worker.default;const doc=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(token!==generation.current){await doc.destroy();return;}pdf.current=doc;setPageCount(doc.numPages);setPage(1);await renderPage(1,token);}else{if(!/^image\/(png|jpeg|webp)$/.test(file.type))throw Error('Choose a PDF, PNG, JPEG or WebP survey.');await showImage(file,file.name,token);}}catch(e){if(token===generation.current)setError((e as Error).message);}finally{if(token===generation.current)setBusy(false);}};
 const apply=async()=>{try{setError('');if(!image||line.length!==2)throw Error('Mark two points on a known distance first.');const known=Number(distance)*(unit==='ft'?12:unit==='m'?1000/25.4:1),pixels=Math.hypot(line[1].x-line[0].x,line[1].y-line[0].y),r=Number(rotation),x=Number(across)*12,z=Number(out)*12;if(![known,pixels,r,x,z].every(Number.isFinite)||known<=0||pixels<2)throw Error('Enter a positive known distance and finite placement.');const before=current.current,site=before.siteModel;if(!site)throw Error('Create or import elevation points before applying the survey.');setBusy(true);const attachmentId=await putSurveyAttachment(image.blob,image.name);if(current.current!==before)throw Error('The design changed during attachment storage. Apply the calibration again.');onChange({siteModel:{...site,overlay:{attachmentId,name:'Survey overlay',widthPx:image.width,heightPx:image.height,scaleInPerPx:known/pixels,rotationDeg:r,originXIn:x,originZIn:z}}});setError('Survey applied. Use the site plan to check its alignment.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="dd-site-survey" aria-label="Survey import and calibration"><h4>Survey PDF or photo</h4><input aria-label="Survey file" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void choose(file);e.target.value='';}}/>{pageCount>0&&<label>PDF page<select aria-label="PDF survey page" value={page} disabled={busy} onChange={e=>{const n=Number(e.target.value);setPage(n);void renderPage(n,++generation.current);}}>{Array.from({length:Math.min(500,pageCount)},(_,i)=><option key={i} value={i+1}>{i+1} of {pageCount}</option>)}</select></label>}{image&&<><p>Click the two ends of a dimension printed on the survey. Its upper-left corner is placed at the across/out coordinates below.</p><svg aria-label="Survey calibration image" role="img" viewBox={`0 0 ${image.width} ${image.height}`} style={{width:'100%',maxHeight:400,background:'#f0f1ee',touchAction:'manipulation'}} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(),svg=e.currentTarget,point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const p=point.matrixTransform(svg.getScreenCTM()!.inverse());if(p.x>=0&&p.y>=0&&p.x<=image.width&&p.y<=image.height)setLine(old=>old.length>=2?[{x:p.x,y:p.y}]:[...old,{x:p.x,y:p.y}]);}}><image href={image.url} width={image.width} height={image.height}/>{line.length===2&&<line x1={line[0].x} y1={line[0].y} x2={line[1].x} y2={line[1].y} stroke="#b43d24" strokeWidth={Math.max(image.width/300,2)}/ >}{line.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={Math.max(image.width/100,4)} fill="#b43d24"/>)}</svg><div className="dd-fields"><label>Known distance<input aria-label="Survey known distance" type="number" min="0.001" value={distance} onChange={e=>setDistance(e.target.value)}/></label><label>Distance unit<select value={unit} aria-label="Survey distance unit" onChange={e=>setUnit(e.target.value)}><option value="ft">Feet</option><option value="m">Metres</option><option value="in">Inches</option></select></label><label>Rotation °<input aria-label="Survey rotation" type="number" value={rotation} onChange={e=>setRotation(e.target.value)}/></label><label>Upper-left across · ft<input aria-label="Survey across origin" type="number" value={across} onChange={e=>setAcross(e.target.value)}/></label><label>Upper-left out · ft<input aria-label="Survey out origin" type="number" value={out} onChange={e=>setOut(e.target.value)}/></label></div><button type="button" className="dd-secondary" disabled={busy||line.length!==2} onClick={()=>void apply()}>Apply calibrated survey</button></>}{busy&&<p role="status">Preparing survey…</p>}{error&&<p role="status">{error}</p>}</section>;
}
