import stockEvidence from '../../data/wall-cap-stock.json';
import type {HardscapeProduct,HardscapeUnit,HardscapeVariant} from './hardscapeCatalogue';
export interface WallCap extends HardscapeUnit {name:string;sourceUrl:string;compatibilityUrl:string;swatchKey?:string;colorHex?:string;sourceProductId:string;sourceFinishId:string;sourceColorId:string;stockUnitId:string}
const techoGuide='https://www.techo-bloc.com/assets/be/bf/bebfd17a-dd58-4c9d-8131-c798c7c4c9cd/STEPS_CAPS_Installation-guide-EN.pdf';
const raffinatoSpecs='https://www.techo-bloc.com/assets/0b/03/0b03e4b8-494b-4fe0-b32f-5bdf3c10c23a/Raffinato-Caps-EN.pdf';
// Explicit rows in the manufacturer's cap compatibility chart. The two
// fascia products are not promoted: single/double-sided use needs selection.
const raffinatoWalls=['techo-brandon-wall','techo-g-force-wall','techo-graphix-wall','techo-mini-cretaarchitectural75-wall','techo-mini-cretaarchitectural150-wall','techo-prescott-wall','techo-raffinato-wall','techo-semma-wall','techo-skyscraper-wall','techo-systema-wall','techo-travertinaraw-wall'];
const colours=['chestnut-brown','beige-cream','champlain-grey','greyed-nickel','shale-grey','onyx-black'];
const hdColours=[...colours,'caff-crema','silver-granite'];
const capRole=(u:HardscapeUnit)=>/(^|[- ])(cap|coping)([- ]|$)/.test(u.role);
const capId=(p:string,f:string,c:string,u:string)=>`cap:${p}:${f}:${c}:${u}`;
/** Manufacturer cap stock, with independently selectable cap colour and
 * finish. Legacy finish-local unit IDs continue to resolve exactly. */
export function wallCapOptions(products:HardscapeProduct[],product:HardscapeProduct,finish:HardscapeVariant,wallColorId:string,body:HardscapeUnit,heightIn:number):WallCap[]{
 const all:WallCap[]=[];
 const append=(p:HardscapeProduct,f:HardscapeVariant,compatibilityUrl=p.sourceUrl,external=false)=>{for(const u of f.units.filter(capRole))for(const color of f.colors){const evidence=stockEvidence[`${p.id}/${f.id}/${u.id}` as keyof typeof stockEvidence];if(u.colorIds&&!u.colorIds.includes(color.id)||evidence&&!evidence.colors.includes(color.id))continue;all.push({...u,id:!external&&f.id===finish.id&&color.id===wallColorId?u.id:capId(p.id,f.id,color.id,u.id),stockUnitId:u.id,name:`${p.brand} ${p.name} · ${evidence?.name??u.id.replaceAll('-',' ')} · ${color.id.replaceAll('-',' ')}`,sourceProductId:p.id,sourceFinishId:f.id,sourceColorId:color.id,sourceUrl:evidence?.sourceUrl??p.sourceUrl,compatibilityUrl,colorHex:color.hex,swatchKey:color.swatch?`${p.id}/${f.id}/${color.id}`:undefined});}};
 // Same-system caps include the separately documented compatible-cap
 // finishes. No wall-body stock is manufactured from a cap-only finish.
 for(const f of product.finishes)if(f.id===finish.id||f.id.startsWith('compatible-cap-'))append(product,f);
 if(raffinatoWalls.includes(product.id))for(const [length,height,capFinish,colors] of [[711,60,'smooth',colours],[711,90,'smooth',colours],[812,60,'hd2-smooth',hdColours]] as const)for(const color of colors){const stock=`raffinato-${length}-356-${height}`;all.push({id:capId('techo-raffinato-cap',capFinish,color,stock),stockUnitId:stock,widthMm:length,lengthMm:356,heightMm:height,role:'cap',shape:'rectangular-nominal',name:`Techo-Bloc Raffinato ${capFinish==='smooth'?'Smooth':'HD² Smooth'} · ${color.replaceAll('-',' ')}`,sourceProductId:'techo-raffinato-cap',sourceFinishId:capFinish,sourceColorId:color,swatchKey:`techo-raffinato-cap/${capFinish}/${color}`,sourceUrl:raffinatoSpecs,compatibilityUrl:techoGuide});}
 if(['oaks-nueva-75-wall','oaks-nueva-150-wall','oaks-rialto-wall'].includes(product.id))for(const color of ['champagne','cloudburst','marble-grey','milano'])all.push({id:capId('oaks-nueva-coping','smooth',color,'coping-600-340-75'),stockUnitId:'coping-600-340-75',widthMm:600,lengthMm:340,heightMm:75,role:'coping',shape:'rectangular-nominal',name:`Oaks Nueva Coping · ${color.replaceAll('-',' ')}`,sourceProductId:'oaks-nueva-coping',sourceFinishId:'smooth',sourceColorId:color,swatchKey:`oaks-nueva-coping/smooth/${color}`,sourceUrl:'https://bramptonbrick.com/sites/default/files/resource_file/Nueva-Coping_Product%20Sheets_Eng_26.pdf',compatibilityUrl:'https://bramptonbrick.com/en/landscape-products-products/nuevar-coping-copings-caps'});
 // Ontario's Lineo catalogue explicitly names Ledgestone as a coping.
 if(['unilock-lineo-dimensional-stone','unilock-brussels-dimensional-stone','unilock-rivercrest-wall','unilock-u-cara','unilock-u-cara-backer'].includes(product.id)){const ledge=products.find(p=>p.id==='unilock-ledgestone');if(ledge)for(const f of ledge.finishes)append(ledge,f,'https://builder.unilock.com/wp-content/uploads/sites/15/2021/02/2021-Product-Resource-Guide-FINAL-02-11-HR_No-bleeds-rev.pdf',true);}
 if(['permacon-vario-wall','permacon-urbano-wall'].includes(product.id)){const melville=products.find(p=>p.id==='permacon-melville-tandem-wall');if(melville)for(const f of melville.finishes.filter(f=>f.id.startsWith('compatible-cap-')))append(melville,f,product.id==='permacon-urbano-wall'?'https://permacon.ca/wp-content/uploads/2025/01/installation-guide-urbano-wall-728-1736403788.pdf':'https://permacon.ca/wp-content/uploads/2023/04/vario-wall-installation-guide-1.pdf',true);}
 if(['oaks-modan','oaks-gardenia-linear','oaks-laredo'].includes(product.id))for(const color of ['champagne','cloudburst','marble-grey','milano','twilight'])all.push({id:capId('oaks-modan-coping','smooth',color,'coping-600-305-60'),stockUnitId:'coping-600-305-60',widthMm:600,lengthMm:305,heightMm:60,role:'coping',shape:'rectangular-nominal',name:`Oaks Modan Coping · ${color.replaceAll('-',' ')}`,sourceProductId:'oaks-modan-coping',sourceFinishId:'smooth',sourceColorId:color,swatchKey:`oaks-modan-coping/smooth/${color}`,sourceUrl:'https://bramptonbrick.com/sites/default/files/resource_file/Modan-Coping_Product%20Sheets_Eng_26.pdf',compatibilityUrl:'https://bramptonbrick.com/en/landscape-products-products/modan-coping-copings-caps'});
 // Portofino D is explicitly a regular unit as well as an end/corner unit,
 // and is compatible with both single- and double-sided Fascia walls.
 if(['techo-iconic-wall','techo-rosemont-wall'].includes(product.id))for(const color of ['rock-garden-brown','riviera','azzurro','onyx-black'])all.push({id:capId('techo-portofino-cap','fossil-stone',color,'portofino-d'),stockUnitId:'portofino-d',widthMm:483,lengthMm:368,heightMm:57,role:'cap',shape:'rectangular-nominal',name:`Techo-Bloc Portofino D regular/end · ${color.replaceAll('-',' ')}`,sourceProductId:'techo-portofino-cap',sourceFinishId:'fossil-stone',sourceColorId:color,swatchKey:`techo-portofino-cap/fossil-stone/${color}`,sourceUrl:'https://www.techo-bloc.com/assets/52/fb/52fb3c32-6120-4d70-b8f5-1419c2fcf7cd/Portofino-Caps-EN.pdf',compatibilityUrl:techoGuide});
 // Factory caps can be shallower than a block (e.g. Keystone). A generic
 // depth rule must not silently reject the manufacturer's own cap unit.
 return all.filter(u=>u.heightMm/25.4<=heightIn&&(u.sourceProductId===product.id||u.lengthMm>=body.lengthMm)).map(u=>({...u,colorHex:u.colorHex??products.filter(p=>p.brand===product.brand).flatMap(p=>p.finishes).flatMap(f=>f.colors).find(c=>c.id===u.sourceColorId&&c.hex)?.hex}));
}
export function wallCapNote(productId:string){if(productId==='techo-skyscraper-wall')return 'Select a compatible top-course depth before capping the wider gravity wall; a narrow cap does not cover every body depth.';if(productId==='techo-sandstonethinsetveneer-wall')return 'Sandstone is an overlay assembly: verify its structural substrate and the cap overlay profile (600 × 305 × 22 mm with 50 mm edge) before specifying the finish.';if(productId==='oaks-modeco-one')return 'Manufacturer garden-wall guide finishes Modeco One with its native wall units; use concrete adhesive on every course. The ordinary garden-wall assembly is limited to 445 mm total height including burial; taller walls need a documented alternative system.';return ['techo-borealis-wall','techo-rocka-wall','permacon-orion-wall'].includes(productId)?'This manufacturer wall system does not require a separate cap.':'Choose a documented cap for this wall system. Unlisted pairings need manufacturer confirmation.';}
