#!/usr/bin/env node
// scripts/blog-publisher/cli.cjs
// Single orchestration entry. Used by .github/workflows/blog-publisher.yml.
// Uses .cjs extension because root package.json declares "type": "module".
//
// Commands:
//   workflow-run         End-to-end: pick topic → Gemini → inject → branch → push → gh PR → Telegram.
//                        Honors env FORCE_TOPIC_ID (set by workflow_dispatch input).
//   generate-only        Generate + write draft; does NOT touch the repo or open a PR.
//   inject-only --slug   Re-runs the injector against an existing draft (for manual recovery).

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const { generateDraft } = require('./generate.cjs');
const { injectDraft, slugToComponent } = require('./inject.cjs');
const { reviewDraft } = require('./adversarial-review.cjs');
const telegram = require('./telegram.cjs');

const SCRIPT_DIR = __dirname;
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..');
const STATE_PATH = path.join(SCRIPT_DIR, 'state.json');
const DRAFTS_DIR = path.join(SCRIPT_DIR, 'drafts');

function git(args) {
  return execSync(`git ${args}`, { cwd: REPO_ROOT, encoding: 'utf8' });
}
function sh(cmd) {
  return execSync(cmd, { cwd: REPO_ROOT, encoding: 'utf8' });
}

function todayStamp() {
  return new Date().toISOString().slice(0, 10);
}

function buildPrBody(draft, injection) {
  const v = draft.validation || {};
  const filesList = injection.filesChanged.map(f => `- \`${f}\``).join('\n');
  const sectionsList = (draft.sections || []).map(s => `  - ${s.heading}`).join('\n');
  const faqList = (draft.faqs || []).slice(0, 5).map(f => `  - ${f.question}`).join('\n');
  const issues = v.errors?.length ? `\n## ⚠️ Validation Warnings\n${v.errors.map(e => `- ${e}`).join('\n')}\n` : '';
  const queueRemaining = typeof draft.queueRemaining === 'number' ? draft.queueRemaining : null;
  const queueWarning = (queueRemaining !== null && queueRemaining <= 4)
    ? `\n## 🟡 Topic queue running low\n**Only ${queueRemaining} unused topic${queueRemaining === 1 ? '' : 's'} remaining** in \`scripts/blog-publisher/topics.json\`. Refill before the queue empties (workflow will fail with "No unused topics remaining" otherwise).\n`
    : '';

  // Adversarial reviewer block — only render if a review was performed and verdict isn't pass
  const r = draft.review;
  let reviewBlock = '';
  if (r) {
    if (r.verdict === 'warn' && r.issues?.length) {
      const issueList = r.issues
        .filter((i) => i.severity === 'high' || i.severity === 'medium')
        .slice(0, 5)
        .map((i) => `- **[${i.severity}]** ${i.axis}: ${i.problem}${i.fix ? ` → _${i.fix}_` : ''}`)
        .join('\n');
      const axesLine = r.axes ? Object.entries(r.axes).map(([k, v]) => `${k}:${v}`).join(' · ') : '';
      reviewBlock = `\n## 🟡 Adversarial Review — verdict: WARN (score ${r.score}/10)\n${r.summary}\n\n${axesLine ? `Axes: \`${axesLine}\`\n\n` : ''}${issueList ? `Flagged:\n${issueList}\n` : ''}_The review caught issues worth reading before you merge._\n`;
    } else if (r.verdict === 'pass') {
      reviewBlock = `\n## ✅ Adversarial Review — verdict: PASS (score ${r.score}/10)\n${r.summary}\n`;
    }
    // 'block' verdict never lands in a PR — workflow halted before PR creation
  }

  return `## ${draft.title}

**Auto-generated by [gm-blog-publisher](./scripts/blog-publisher/README.md) — review & merge to publish.**
${queueWarning}${reviewBlock}

### Will publish at
**[https://goldenmaplelandscaping.ca${injection.route}](https://goldenmaplelandscaping.ca${injection.route})**

### Stats
- **Words:** ${v.wordCount ?? '?'}
- **Internal links:** ${v.linkCount ?? '?'}
- **Sections:** ${(draft.sections || []).length}
- **FAQs:** ${(draft.faqs || []).length}
- **Validation:** ${v.ok ? '✅ pass' : '⚠️ warnings'}
- **Hero image:** \`${draft.heroImage}\`
- **Category:** ${draft.category}
${issues}
### Structure
${sectionsList}

### FAQ preview (first 5)
${faqList}

### SEO
- **Title (${draft.seoTitle?.length || 0}c):** ${draft.seoTitle}
- **Description (${draft.seoDescription?.length || 0}c):** ${draft.seoDescription}

### Files changed
${filesList}

---
*To reject: close this PR without merging. Next Monday will pick a fresh topic.*
`;
}

async function cmdWorkflowRun() {
  const forced = process.env.FORCE_TOPIC_ID || null;
  const skipReview = process.env.SKIP_ADVERSARIAL_REVIEW === 'true';
  let draft, review, injection, branch, prUrl;

  // 1) Generate
  try {
    draft = await generateDraft({ topicId: forced || null });
  } catch (e) {
    try { await telegram.sendErrorAlert('generate', e); } catch {}
    throw e;
  }

  // 2) Adversarial review — second Gemini pass that critiques the draft.
  //    Verdict 'block' halts the workflow; 'warn' continues with warning in PR body.
  //
  //    Safety net: the reviewer is an LLM and CAN hallucinate. Slug uniqueness
  //    is upstream-guaranteed by generate.cjs, so any "block" verdict whose
  //    stated reasons are *only* dedup/originality concerns gets downgraded to
  //    "warn". Caught 2026-06-08 incident: reviewer blocked auto-003 claiming
  //    "directly duplicates the slug of a prior article" — but state.json + the
  //    live sitemap both confirmed the slug was unique.
  if (!skipReview) {
    try {
      review = await reviewDraft(draft);
      draft.review = review;
      console.log(`[workflow] adversarial review: ${review.verdict} (score ${review.score})`);

      if (review.verdict === 'block') {
        // Cross-check: if all blocking-severity issues are dedup/originality
        // related, downgrade to warn. Slug uniqueness is hard-guaranteed by
        // generate.cjs's usedTopicIds check.
        const blockingIssues = (review.issues || []).filter((i) => i.severity === 'high');
        const allBlockingAreDedup = blockingIssues.length > 0 &&
          blockingIssues.every((i) =>
            (i.axis === 'originality') ||
            /duplicat/i.test(i.problem || '') ||
            /duplicat/i.test(i.quote || '') ||
            /\bslug\b/i.test(i.problem || '')
          );
        const summaryClaimsDedup =
          /duplicat/i.test(review.summary || '') ||
          /already (publish|exist)/i.test(review.summary || '');

        if (allBlockingAreDedup || (summaryClaimsDedup && blockingIssues.length === 0)) {
          console.warn(`[workflow] reviewer blocked on dedup but slug is upstream-unique — downgrading verdict block → warn`);
          review.verdict = 'warn';
          review.downgradedFromBlock = true;
          review.downgradeReason = 'dedup-only block; slug uniqueness is upstream-guaranteed by generate.cjs';
          // Continue to inject — fall through, don't throw.
        } else {
          const blockMsg =
            `🚫 Adversarial review BLOCKED draft "${draft.slug}".\n\n` +
            `Score: ${review.score}/10\n` +
            `Summary: ${review.summary}\n\n` +
            `Top issues:\n` +
            review.issues.slice(0, 5).map((i) => `  • [${i.severity}] ${i.axis}: ${i.problem}`).join('\n') +
            `\n\nDraft NOT submitted. Topic will be retried next cycle.`;
          try { await telegram.sendMessage(blockMsg, { parseMode: undefined }); } catch {}
          throw new Error(`adversarial review blocked: ${review.summary}`);
        }
      }
    } catch (e) {
      if (e.message.startsWith('adversarial review blocked')) throw e;
      // Reviewer itself crashed — fail open with warning. Don't halt the pipeline.
      console.warn('[workflow] reviewer crashed (failing open):', e.message);
      draft.review = { verdict: 'warn', score: null, issues: [], summary: `Reviewer crashed: ${e.message}` };
    }
  }

  // 3) Inject
  try {
    injection = injectDraft(draft);
  } catch (e) {
    try { await telegram.sendErrorAlert('inject:' + draft.slug, e); } catch {}
    throw e;
  }

  // 3) Branch + commit + push
  try {
    git('config user.name "gm-blog-publisher[bot]"');
    git('config user.email "noreply@goldenmaplelandscaping.ca"');

    branch = `auto/blog-${todayStamp()}-${draft.slug}`;
    git(`checkout -b "${branch}"`);

    // Stage state + draft + the 4 user-facing files (by name, never -A).
    const stateRel = path.relative(REPO_ROOT, STATE_PATH).replace(/\\/g, '/');
    const draftRel = path.relative(REPO_ROOT, path.join(DRAFTS_DIR, `${draft.slug}.json`)).replace(/\\/g, '/');
    const files = [stateRel, draftRel, ...injection.filesChanged].map(f => `"${f}"`).join(' ');
    sh(`git add ${files}`);

    const commitMsg = `blog: ${draft.title}\n\nSlug: ${draft.slug}\nTopic: ${draft.topicId}\nGenerated: ${draft.generatedAt}\nWord count: ${draft.validation?.wordCount}\n`;
    sh(`git commit -m ${JSON.stringify(commitMsg)}`);

    git(`push origin "${branch}"`);
    console.log(`[workflow-run] pushed ${branch}`);
  } catch (e) {
    try { await telegram.sendErrorAlert('git-push:' + draft.slug, e); } catch {}
    throw e;
  }

  // 4) Open PR via gh CLI
  try {
    const prTitle = `[blog] ${draft.title}`.slice(0, 100);
    const prBody = buildPrBody(draft, injection);
    const bodyFile = path.join(SCRIPT_DIR, '_pr-body.tmp.md');
    fs.writeFileSync(bodyFile, prBody);

    prUrl = sh(`gh pr create --base main --head "${branch}" --title ${JSON.stringify(prTitle)} --body-file "${bodyFile}"`).trim();
    fs.unlinkSync(bodyFile);
    console.log(`[workflow-run] PR opened: ${prUrl}`);
  } catch (e) {
    try { await telegram.sendErrorAlert('gh-pr:' + draft.slug, e); } catch {}
    throw e;
  }

  // 5) Telegram preview
  try {
    await telegram.sendPrPreview(draft, prUrl);
    console.log('[workflow-run] Telegram preview sent');
  } catch (e) {
    console.warn('[workflow-run] Telegram preview failed (non-fatal):', e.message);
  }

  return { slug: draft.slug, branch, prUrl, validation: draft.validation };
}

async function cmdGenerateOnly() {
  const forced = process.env.FORCE_TOPIC_ID || null;
  const draft = await generateDraft({ topicId: forced || null });
  console.log(`\nGenerated draft for slug=${draft.slug} valid=${draft.validation.ok}`);
}

// Exported so scripts/blog-publisher/watchdog.cjs can reuse the PR body
// format when opening recovery PRs for orphan branches.
module.exports = { buildPrBody };

async function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  try {
    switch (cmd) {
      case 'workflow-run': {
        const r = await cmdWorkflowRun();
        console.log(JSON.stringify(r, null, 2));
        break;
      }
      case 'generate-only': await cmdGenerateOnly(); break;
      default:
        console.error('Usage: cli.cjs {workflow-run|generate-only}');
        process.exit(2);
    }
  } catch (e) {
    console.error('FAIL:', e.message);
    process.exit(1);
  }
}

// Only run main() when invoked directly, not when require()'d from watchdog.cjs
if (require.main === module) main();
