#!/usr/bin/env node
// scripts/blog-publisher/cli.cjs
// Single orchestration entry. Used by .github/workflows/blog-publisher.yml.
// Uses .cjs extension because root package.json declares "type": "module".
//
// Commands:
//   workflow-run         End-to-end: pick topic → Gemini → inject → branch → push → gh PR → Telegram.
//                        Honors env FORCE_TOPIC_ID (set by workflow_dispatch input).
//   generate-only        Generate + write draft; does NOT touch the repo or open a PR.
//   inject-only --slug   Re-runs the injector against an existing draft (for manual recovery).

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const { generateDraft } = require('./generate.cjs');
const { injectDraft, slugToComponent } = require('./inject.cjs');
const telegram = require('./telegram.cjs');

const SCRIPT_DIR = __dirname;
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..');
const STATE_PATH = path.join(SCRIPT_DIR, 'state.json');
const DRAFTS_DIR = path.join(SCRIPT_DIR, 'drafts');

function git(args) {
  return execSync(`git ${args}`, { cwd: REPO_ROOT, encoding: 'utf8' });
}
function sh(cmd) {
  return execSync(cmd, { cwd: REPO_ROOT, encoding: 'utf8' });
}

function todayStamp() {
  return new Date().toISOString().slice(0, 10);
}

function buildPrBody(draft, injection) {
  const v = draft.validation || {};
  const filesList = injection.filesChanged.map(f => `- \`${f}\``).join('\n');
  const sectionsList = (draft.sections || []).map(s => `  - ${s.heading}`).join('\n');
  const faqList = (draft.faqs || []).slice(0, 5).map(f => `  - ${f.question}`).join('\n');
  const issues = v.errors?.length ? `\n## ⚠️ Validation Warnings\n${v.errors.map(e => `- ${e}`).join('\n')}\n` : '';

  return `## ${draft.title}

**Auto-generated by [gm-blog-publisher](./scripts/blog-publisher/README.md) — review & merge to publish.**

### Will publish at
**[https://goldenmaplelandscaping.ca${injection.route}](https://goldenmaplelandscaping.ca${injection.route})**

### Stats
- **Words:** ${v.wordCount ?? '?'}
- **Internal links:** ${v.linkCount ?? '?'}
- **Sections:** ${(draft.sections || []).length}
- **FAQs:** ${(draft.faqs || []).length}
- **Validation:** ${v.ok ? '✅ pass' : '⚠️ warnings'}
- **Hero image:** \`${draft.heroImage}\`
- **Category:** ${draft.category}
${issues}
### Structure
${sectionsList}

### FAQ preview (first 5)
${faqList}

### SEO
- **Title (${draft.seoTitle?.length || 0}c):** ${draft.seoTitle}
- **Description (${draft.seoDescription?.length || 0}c):** ${draft.seoDescription}

### Files changed
${filesList}

---
*To reject: close this PR without merging. Next Monday will pick a fresh topic.*
`;
}

async function cmdWorkflowRun() {
  const forced = process.env.FORCE_TOPIC_ID || null;
  let draft, injection, branch, prUrl;

  // 1) Generate
  try {
    draft = await generateDraft({ topicId: forced || null });
  } catch (e) {
    try { await telegram.sendErrorAlert('generate', e); } catch {}
    throw e;
  }

  // 2) Inject
  try {
    injection = injectDraft(draft);
  } catch (e) {
    try { await telegram.sendErrorAlert('inject:' + draft.slug, e); } catch {}
    throw e;
  }

  // 3) Branch + commit + push
  try {
    git('config user.name "gm-blog-publisher[bot]"');
    git('config user.email "noreply@goldenmaplelandscaping.ca"');

    branch = `auto/blog-${todayStamp()}-${draft.slug}`;
    git(`checkout -b "${branch}"`);

    // Stage state + draft + the 4 user-facing files (by name, never -A).
    const stateRel = path.relative(REPO_ROOT, STATE_PATH).replace(/\\/g, '/');
    const draftRel = path.relative(REPO_ROOT, path.join(DRAFTS_DIR, `${draft.slug}.json`)).replace(/\\/g, '/');
    const files = [stateRel, draftRel, ...injection.filesChanged].map(f => `"${f}"`).join(' ');
    sh(`git add ${files}`);

    const commitMsg = `blog: ${draft.title}\n\nSlug: ${draft.slug}\nTopic: ${draft.topicId}\nGenerated: ${draft.generatedAt}\nWord count: ${draft.validation?.wordCount}\n`;
    sh(`git commit -m ${JSON.stringify(commitMsg)}`);

    git(`push origin "${branch}"`);
    console.log(`[workflow-run] pushed ${branch}`);
  } catch (e) {
    try { await telegram.sendErrorAlert('git-push:' + draft.slug, e); } catch {}
    throw e;
  }

  // 4) Open PR via gh CLI
  try {
    const prTitle = `[blog] ${draft.title}`.slice(0, 100);
    const prBody = buildPrBody(draft, injection);
    const bodyFile = path.join(SCRIPT_DIR, '_pr-body.tmp.md');
    fs.writeFileSync(bodyFile, prBody);

    prUrl = sh(`gh pr create --base main --head "${branch}" --title ${JSON.stringify(prTitle)} --body-file "${bodyFile}"`).trim();
    fs.unlinkSync(bodyFile);
    console.log(`[workflow-run] PR opened: ${prUrl}`);
  } catch (e) {
    try { await telegram.sendErrorAlert('gh-pr:' + draft.slug, e); } catch {}
    throw e;
  }

  // 5) Telegram preview
  try {
    await telegram.sendPrPreview(draft, prUrl);
    console.log('[workflow-run] Telegram preview sent');
  } catch (e) {
    console.warn('[workflow-run] Telegram preview failed (non-fatal):', e.message);
  }

  return { slug: draft.slug, branch, prUrl, validation: draft.validation };
}

async function cmdGenerateOnly() {
  const forced = process.env.FORCE_TOPIC_ID || null;
  const draft = await generateDraft({ topicId: forced || null });
  console.log(`\nGenerated draft for slug=${draft.slug} valid=${draft.validation.ok}`);
}

async function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  try {
    switch (cmd) {
      case 'workflow-run': {
        const r = await cmdWorkflowRun();
        console.log(JSON.stringify(r, null, 2));
        break;
      }
      case 'generate-only': await cmdGenerateOnly(); break;
      default:
        console.error('Usage: cli.cjs {workflow-run|generate-only}');
        process.exit(2);
    }
  } catch (e) {
    console.error('FAIL:', e.message);
    process.exit(1);
  }
}

main();
