import {test,expect} from '@playwright/test';
test.beforeEach(async({page,context})=>{await context.addInitScript('window.__name=(target,value)=>target;');await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())?r.continue():r.fulfill({body:''}));await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft?.read().ready??false)).toBe(true);});
test('Architect help, file save, point editing and fit navigation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await expect(page.getByRole('button',{name:'Show project controls',exact:true})).toBeVisible();await page.keyboard.press('F1');const help=page.getByRole('dialog',{name:'Keyboard shortcuts',exact:true});await expect(help).toBeVisible();await expect(help).toContainText('Ctrl+A');await page.keyboard.press('Escape');await expect(help).not.toBeVisible();
 await page.keyboard.press('e');await expect(page.getByRole('radio',{name:'Shape & points',exact:true})).toHaveAttribute('aria-checked','true');await page.keyboard.press('e');await expect(page.getByRole('radio',{name:'Deck size',exact:true})).toHaveAttribute('aria-checked','true');
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.keyboard.press('z');await expect(page.getByLabel('Drawing zoom',{exact:true})).toHaveText('100%');
 const download=page.waitForEvent('download');await page.keyboard.press('Control+s');expect((await download).suggestedFilename()).toBe('golden-maple-deck-design.json');
 await page.keyboard.press('j');await expect(page.locator('.dd-selection-inspector')).toHaveAttribute('open');expect(errors).toEqual([]);
});
for(const tool of ['patio','designer','sketch'])test(`Architect drawing keys protect text entry in ${tool}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let name='Yard shape drawing surface',dots='.dd-yard-shape-draft-point',length='Exact drawing length',angle='Exact drawing angle';
 if(tool==='sketch'){await page.getByRole('button',{name:'Sketch a design',exact:true}).click();const modal=page.getByRole('dialog',{name:'Sketch a design',exact:true});await modal.getByRole('button',{name:'Draw patio',exact:true}).click();await modal.getByRole('button',{name:'Straight lines',exact:true}).click();name='Sketch canvas';dots='.dd-sketch-line-draft>circle:not(.dd-sketch-line-cursor,.dd-sketch-join)';}
 else{await page.getByRole('radio',{name:'Patios & walls',exact:true}).click();if(tool==='designer'){await page.getByLabel('Designer tools',{exact:true}).check();await page.getByRole('button',{name:'Patio outline',exact:true}).click();name='Patio outline drawing surface';dots='.dd-shape-draw-point';length='Typed edge length';angle='Typed edge direction in degrees';}else await page.getByRole('button',{name:'Draw patio',exact:true}).click();}
 const canvas=page.getByLabel(name,{exact:true});await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!;await page.mouse.click(b.x+b.width*.45,b.y+b.height*.4);await canvas.focus();
 await page.keyboard.press('Enter');const input=page.getByLabel(length,{exact:true});await expect(input).toBeFocused();await input.fill("5'");await page.keyboard.press('Control+a');await expect(input).toHaveValue("5'");await page.getByLabel(angle,{exact:true}).fill('27');await input.press('Enter');await expect(canvas.locator(dots)).toHaveCount(2);
 await canvas.focus();await page.keyboard.press('Backspace');await expect(canvas.locator(dots)).toHaveCount(1);
 if(tool==='designer'){await page.keyboard.press('Control+a');await expect(page.getByLabel('Snap to 15° directions',{exact:true})).not.toBeChecked();await page.keyboard.press('Control+g');await expect(page.getByLabel('Snap grid',{exact:true})).toHaveValue('0');await page.keyboard.press('g');await expect(page.getByLabel('Snap grid',{exact:true})).toBeFocused();}
 if(tool==='sketch'){await page.keyboard.press('Control+a');await expect(page.getByRole('button',{name:'Snap to 90°',exact:true})).toHaveAttribute('aria-pressed','false');await page.keyboard.press('F1');await expect(page.getByRole('dialog',{name:'Keyboard shortcuts',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Sketch a design',exact:true})).toBeVisible();await expect(canvas.locator(dots)).toHaveCount(1);}
 if(tool==='patio'){await page.keyboard.press('Control+a');await expect(page.getByText('Angle snap: on · Point snap: on',{exact:true})).toBeVisible();}
 expect(errors).toEqual([]);
});
test('A L N select parts without changing geometry',async({page})=>{
 const before=await page.evaluate(()=>(window as any).deckcraft.read().design);await page.getByRole('radio',{name:'Select parts',exact:true}).click();await expect(page.getByRole('button',{name:'Select all matching parts',exact:true})).toBeVisible();await page.keyboard.press('a');await expect(page.locator('.dd-component-selection-actions span')).not.toHaveText('0 selected');await page.keyboard.press('n');await expect(page.locator('.dd-component-selection-actions span')).toHaveText('0 selected');
 await page.getByLabel('Select plan part',{exact:true}).selectOption('deck:1');await page.getByLabel('Deck drawing canvas',{exact:true}).focus();await page.keyboard.press('l');await expect(page.locator('.dd-component-selection-actions span')).not.toHaveText('0 selected');expect(await page.evaluate(()=>(window as any).deckcraft.read().design)).toEqual(before);
});
test('Architect transform keys and help in 3D',async({page,context})=>{
 const configuration=await page.evaluate(()=>(window as any).deckcraft.read().design);configuration.yardFeatures=[{id:'keys-patio',name:'Keyboard patio',kind:'patio',enabled:true,xFt:30,zFt:10,widthFt:8,depthFt:8,heightIn:0,rotationDeg:0,productId:'permacon-melville',color:'#aaa69b'}];await context.addInitScript(configuration=>localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration})),configuration);
 await page.reload();await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft?.read().ready??false)).toBe(true);await page.locator('.dd-hardscape-plan-picks polygon').first().click();await page.getByRole('tab',{name:'3D',exact:true}).click();const bar=page.getByLabel('3D edit controls',{exact:true});await expect(bar).toBeVisible();
 for(const [key,label] of [['r','Rotate'],['s','Resize'],['t','Move'],['e','Shape'],['m','Move']]){await page.keyboard.press(key);await expect(bar.getByRole('button',{name:label,exact:true})).toHaveAttribute('aria-pressed','true');}
 await page.keyboard.press('r');await page.keyboard.press('F1');const help=page.getByRole('dialog',{name:'Keyboard shortcuts',exact:true});await expect(help).toBeVisible();await page.keyboard.press('t');await expect(bar.getByRole('button',{name:'Rotate',exact:true})).toHaveAttribute('aria-pressed','true');await page.keyboard.press('Escape');await expect(help).not.toBeVisible();
});
