import {test,expect} from '@playwright/test';
test.beforeEach(async({page,context})=>{await context.addInitScript('window.__name=(target,value)=>target;');await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())?r.continue():r.fulfill({body:''}));await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft?.read().ready??false)).toBe(true);});
test('right-click deck selects object, opens properties and preserves geometry',async({page})=>{
 const before=await page.evaluate(()=>(window as any).deckcraft.read().design);const surface=page.locator('.dd-plan-stage .dd-site-plan');await page.getByRole('button',{name:'Show project controls',exact:true}).waitFor();await surface.scrollIntoViewIfNeeded();
 const point=await surface.evaluate((svg:SVGSVGElement)=>{const p=new DOMPoint(96,72).matrixTransform(svg.getScreenCTM()!);return{x:p.x,y:p.y};});await page.mouse.click(point.x,point.y,{button:'right'});
 const menu=page.getByRole('menu',{name:'Object edit menu'});await expect(menu).toBeVisible();await expect(menu).toContainText('Deck level 1');await page.screenshot({path:'../outputs/context-menu/deck-menu.png'});await expect(menu.getByRole('menuitem',{name:'Properties…'})).toBeFocused();
 await page.keyboard.press('Escape');await expect(menu).not.toBeVisible();expect(await page.evaluate(()=>(window as any).deckcraft.read().design)).toEqual(before);
 await page.mouse.click(point.x,point.y,{button:'right'});await menu.getByRole('menuitem',{name:'Properties…'}).click();await expect(page.getByRole('dialog',{name:'Design inspector'})).toBeVisible();await page.keyboard.press('Escape');
 await page.getByLabel('Deck drawing canvas',{exact:true}).focus();await page.keyboard.press('Shift+F10');await expect(menu).toContainText('Deck level 1');await menu.getByRole('menuitem',{name:'Edit points / shape'}).click();await expect(page.getByRole('radio',{name:'Shape & points',exact:true})).toHaveAttribute('aria-checked','true');
});
test('context duplicate is undoable and right-click drawing still closes the patio',async({page})=>{
 await page.getByRole('radio',{name:'Select parts',exact:true}).click();const opening=page.locator('.dd-component-handle[data-kind=opening]').first();await opening.click({button:'right'});const menu=page.getByRole('menu',{name:'Object edit menu'});await expect(menu).toBeVisible();const before=await page.evaluate(()=>(window as any).deckcraft.read().design);await menu.getByRole('menuitem',{name:'Duplicate',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft.read().design)).not.toEqual(before);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft.read().design)).toEqual(before);
 await page.getByRole('tab',{name:'Building',exact:true}).click();await page.getByRole('radio',{name:'Patios & walls',exact:true}).click();await page.getByRole('button',{name:'Draw patio',exact:true}).click();const surface=page.getByLabel('Yard shape drawing surface',{exact:true});await surface.scrollIntoViewIfNeeded();const b=(await surface.boundingBox())!;for(const [x,y] of [[.4,.4],[.6,.4],[.6,.6]])await page.mouse.click(b.x+b.width*x,b.y+b.height*y);await surface.click({button:'right'});await expect(menu).not.toBeVisible();await expect(surface).not.toBeVisible();
});
test('patio right-click chooses the clicked item and menu stays inside viewport',async({page,context})=>{
 const config=await page.evaluate(()=>(window as any).deckcraft.read().design);config.yardFeatures=[{id:'menu-patio',name:'Menu patio',kind:'patio',enabled:true,xFt:25,zFt:8,widthFt:8,depthFt:8,heightIn:0,rotationDeg:0,productId:'permacon-melville',color:'#aaa69b'}];await context.addInitScript(configuration=>localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration})),config);await page.reload();await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft?.read().ready??false)).toBe(true);
 await page.locator('.dd-hardscape-plan-picks polygon').first().click({button:'right'});const menu=page.getByRole('menu',{name:'Object edit menu'});await expect(menu).toContainText('Menu patio');const box=(await menu.boundingBox())!,vp=page.viewportSize()!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(vp.width);expect(box.y+box.height).toBeLessThanOrEqual(vp.height);await menu.getByRole('menuitem',{name:'Properties…'}).click();await expect(page.getByRole('region',{name:'Landscape object inspector'})).toContainText('Menu patio');
 await page.getByRole('tab',{name:'3D',exact:true}).click();const canvas=page.locator('.dd-canvas canvas');await expect(canvas).toBeVisible();await expect(canvas).toHaveAttribute('data-object-context-ready','true');for(const [x,y] of [[.5,.2],[.5,.28],[.5,.38],[.45,.28]]){const b=(await canvas.boundingBox())!;await canvas.click({button:'right',position:{x:b.width*x,y:b.height*y}});await expect(menu).toBeVisible();if(await menu.getByRole('menuitem',{name:'Properties…'}).count())break;await page.keyboard.press('Escape');}await expect(menu.getByRole('menuitem',{name:'Properties…'})).toBeVisible();await page.screenshot({path:'../outputs/context-menu/3d-menu.png'});await page.keyboard.press('Escape');await expect(menu).not.toBeVisible();
});
