import {test,expect,type Page,type Locator} from '@playwright/test';
import {mkdirSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
import type {SketchDocument} from '../src/features/deckcraft/sketch/sketchTypes';
import {yardShapeWorldPoints,yardShapeRunIn} from '../src/features/deckcraft/yardShapeEditing';

const proof=resolve(process.cwd(),'../../outputs/deckcraft-yard-shape-review');mkdirSync(proof,{recursive:true});
const patio:YardFeature={id:'qa-patio',kind:'patio',name:'QA patio',enabled:true,xFt:6,zFt:26,widthFt:12,depthFt:10,heightIn:0,rotationDeg:20,productId:'permacon-melville',color:'#aaa69b',outline:[{x:-72,y:-60},{x:0,y:-60},{x:72,y:-60},{x:72,y:60},{x:-72,y:60}]};
const wall:YardFeature={id:'qa-wall',kind:'retaining-wall',name:'QA wall',enabled:false,xFt:22,zFt:36,widthFt:16,depthFt:.25,heightIn:24,rotationDeg:0,productId:'segmental-concrete',color:'#aaa69b',wallPath:[{x:-72,y:-24},{x:72,y:-24},{x:72,y:24}]};
const fixture:DeckData={...DEFAULT_DECK,houseVisible:false,deckType:'Freestanding',stairFlights:0,railingType:'None',yardFeatures:[patio,wall],customerName:'Shared yard QA'};
const modal=(page:Page)=>page.getByRole('dialog',{name:'Sketch a design',exact:true});
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
async function ready(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);return state(page);}
async function activate(page:Page,control:Locator,touch=false){await control.scrollIntoViewIfNeeded();if(touch){const b=(await control.boundingBox())!;expect(b.width).toBeGreaterThanOrEqual(44);expect(b.height).toBeGreaterThanOrEqual(44);await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);}else await control.click();}
async function open(page:Page,touch=false){await activate(page,page.getByRole('button',{name:'Sketch a design',exact:true}),touch);await expect(modal(page)).toBeVisible();await expect(modal(page).getByRole('button',{name:'Draw patio',exact:true})).toBeVisible();}
async function exportSketch(page:Page){const files=modal(page).locator('details').filter({has:page.locator('summary').filter({hasText:'Sketch files & reset'})});if(!await files.evaluate(el=>(el as HTMLDetailsElement).open))await files.locator('summary').click();const event=page.waitForEvent('download');await modal(page).getByRole('button',{name:'Export sketch JSON',exact:true}).click();return JSON.parse(readFileSync((await (await event).path())!,'utf8')) as SketchDocument;}
async function apply(page:Page,touch=false){await activate(page,modal(page).getByRole('button',{name:'Edit on plan',exact:true}),touch);await expect(modal(page)).toBeHidden();return ready(page);}
async function select(page:Page,name:string,touch=false){await activate(page,modal(page).getByRole('button').filter({hasText:name}).filter({has:page.locator('.dd-sketch-shape-number')}),touch);}
async function corners(page:Page,points:{x:number;y:number}[],touch=false){const canvas=modal(page).getByRole('group',{name:'Sketch canvas',exact:true});await canvas.scrollIntoViewIfNeeded();for(const p of points){const at=await canvas.evaluate((el,p)=>{const q=new DOMPoint(p.x,p.y).matrixTransform((el as SVGSVGElement).getScreenCTM()!);return {x:q.x,y:q.y};},p);if(touch)await page.touchscreen.tap(at.x,at.y);else await page.mouse.click(at.x,at.y);}}
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page,context})=>{const found:string[]=[];errors.set(page,found);page.on('pageerror',e=>found.push(e.message));await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{const key='golden-maple.deck-studio.deck-only.v1';if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},fixture);await context.route('**/*',route=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(route.request().url())&&['GET','HEAD'].includes(route.request().method())?route.continue():route.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await ready(page);});
test.afterEach(async({page})=>{expect(errors.get(page)??[]).toEqual([]);});

for(const touch of [false,true])test(`${touch?'@phone ':''}sketch and plan share rotated patio pulls, wall length, excluded status and one Undo`,async({page})=>{
 const initial=await state(page);await open(page,touch);const seeded=await exportSketch(page);expect(seeded.shapes.find(s=>s.id==='plan-yard-qa-patio')?.points).toHaveLength(5);expect(seeded.shapes.find(s=>s.id==='plan-yard-qa-wall')?.drawing).toBe('edge-path');const noop=await apply(page,touch);expect(noop.design).toEqual(initial.design);expect(noop.pricing).toEqual(initial.pricing);expect(noop.history).toEqual(initial.history);
 await open(page,touch);await select(page,'QA patio',touch);await modal(page).getByRole('spinbutton',{name:/^Measured width/}).fill('18');const point=modal(page).getByRole('button',{name:'QA patio sketch point 4',exact:true});await point.focus();await point.press('ArrowRight');await select(page,'QA wall',touch);await modal(page).getByRole('spinbutton',{name:/^Measured wall run/}).fill('20');await modal(page).getByRole('spinbutton',{name:/^Wall thickness/}).fill('0.125');const draft=await exportSketch(page);expect((await state(page)).design).toEqual(initial.design);const changed=await apply(page,touch),p=changed.design.yardFeatures!.find(f=>f.id===patio.id)!,w=changed.design.yardFeatures!.find(f=>f.id===wall.id)!;expect(p.outline).toHaveLength(5);expect(p.rotationDeg).toBe(patio.rotationDeg);expect(p.productId).toBe(patio.productId);expect(w.enabled).toBe(false);expect(w.depthFt).toBe(.125);expect(w.widthFt).toBeCloseTo(20,6);expect(yardShapeRunIn(w.wallPath!)/12).toBeCloseTo(20,6);expect(changed.design.deckOutlines).toEqual(initial.design.deckOutlines);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await state(page)).design).toEqual(initial.design);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect.poll(async()=>(await state(page)).design).toEqual(changed.design);
 await activate(page,page.getByRole('radio',{name:'Patios & walls',exact:true}),touch);const planPoint=page.getByRole('button',{name:'QA patio point 4',exact:true});await planPoint.focus();await planPoint.press('ArrowDown');const pulled=await ready(page);expect(yardShapeWorldPoints(pulled.design.yardFeatures![0])[3].y).toBeCloseTo(yardShapeWorldPoints(p)[3].y+1,6);
 await open(page,touch);const reopened=await exportSketch(page),deck=reopened.shapes.find(s=>s.id==='plan-deck-1')!,origin=deck.points[0],actual=reopened.shapes.find(s=>s.id==='plan-yard-qa-patio')!.points,world=yardShapeWorldPoints(pulled.design.yardFeatures![0]);for(let i=0;i<world.length;i++){expect(actual[i].x-origin.x).toBeCloseTo(world[i].x,6);expect(actual[i].y-origin.y).toBeCloseTo(world[i].y,6);}expect(draft.shapes.find(s=>s.id==='plan-yard-qa-wall')?.points).toHaveLength(3);await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-shared-yard-sketch.png`)});const reopenedNoop=await apply(page,touch);expect(reopenedNoop.design).toEqual(pulled.design);expect(reopenedNoop.history).toEqual(pulled.history);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

for(const touch of [false,true])test(`${touch?'@phone ':''}current-plan sketch draws closed patio and open L wall with right click or touch Finish`,async({page})=>{
 const initial=await state(page);await open(page,touch);const base=await exportSketch(page),origin=base.shapes.find(s=>s.id==='plan-deck-1')!.points[0],offset=(points:{x:number;y:number}[])=>points.map(p=>({x:p.x+origin.x,y:p.y+origin.y}));await activate(page,modal(page).getByRole('button',{name:'Draw patio',exact:true}),touch);await activate(page,modal(page).getByRole('button',{name:'Straight lines',exact:true}),touch);await corners(page,offset([{x:192,y:216},{x:300,y:216},{x:300,y:336},{x:192,y:336}]),touch);await activate(page,modal(page).getByRole('button',{name:'Finish outline',exact:true}),touch);
 await activate(page,modal(page).getByRole('button',{name:'Draw retaining wall',exact:true}),touch);await corners(page,offset([{x:192,y:348},{x:300,y:348},{x:300,y:408}]),touch);if(touch)await activate(page,modal(page).getByRole('button',{name:'Finish path',exact:true}),true);else{const canvas=modal(page).getByRole('group',{name:'Sketch canvas',exact:true}),b=(await canvas.boundingBox())!;await page.mouse.click(b.x+b.width/2,b.y+b.height/2,{button:'right'});}await modal(page).getByRole('spinbutton',{name:/^Wall thickness/}).fill('0.25');await modal(page).getByRole('spinbutton',{name:/^Height above grade/}).fill('18');const doc=await exportSketch(page),newPatio=doc.shapes.find(s=>s.kind==='patio'&&s.id!=='plan-yard-qa-patio')!,newWall=doc.shapes.find(s=>s.kind==='retaining-wall'&&s.id!=='plan-yard-qa-wall')!;expect(newPatio.points).toHaveLength(4);expect(newWall.points).toHaveLength(3);expect(newWall.drawing).toBe('edge-path');expect((await state(page)).design).toEqual(initial.design);const applied=await apply(page,touch);expect(applied.design.yardFeatures).toHaveLength(4);expect(applied.design.yardFeatures!.slice(0,2)).toEqual(initial.design.yardFeatures);const added=applied.design.yardFeatures!.at(-1)!;expect(added.wallPath).toHaveLength(3);expect(added.widthFt).toBeCloseTo(14,4);expect(added.depthFt).toBe(.25);expect(added.heightIn).toBe(18);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await state(page)).design).toEqual(initial.design);
 await open(page,touch);await activate(page,modal(page).getByRole('button',{name:'New sketch',exact:true}),touch);await expect(modal(page).getByRole('button',{name:'Draw retaining wall',exact:true})).toHaveCount(0);await modal(page).getByRole('button',{name:'Close sketch designer',exact:true}).click();expect((await state(page)).design).toEqual(initial.design);
});
