import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
test.beforeEach(async({context})=>{await context.route('**/*',route=>{const request=route.request(),u=new URL(request.url());if(!['GET','HEAD'].includes(request.method()))return route.abort();if(['127.0.0.1','localhost','[::1]'].includes(u.hostname))return route.fallback();return route.fulfill({status:200,body:'',contentType:request.resourceType()==='script'?'text/javascript':request.resourceType()==='stylesheet'?'text/css':'text/plain'});});});
const read=(page:Page)=>page.evaluate(()=>window.deckcraft!.read());
async function open(page:Page){await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>window.deckcraft?.read().ready??false)).toBe(true);const seeded=await page.evaluate(()=>window.deckcraft!.execute({id:'pull-point-seed',commands:[{type:'design.patch',patch:{deckType:'Freestanding',houseVisible:false,stairFlights:0,levels:1}},{type:'boundary.set',level:1,points:[{x:0,y:0},{x:192,y:0},{x:192,y:144},{x:0,y:144}]}]}));expect(seeded.ok,JSON.stringify(seeded)).toBe(true);await page.locator('#dd-tool-outline').click();}
async function edgePosition(page:Page,index:number,t=.27){await page.locator('.dd-plan-viewport').scrollIntoViewIfNeeded();return page.locator(`.dd-boundary-insert-target[data-level="1"][data-edge="${index}"]`).evaluate((el,t)=>{const line=el as SVGLineElement,m=line.getScreenCTM()!;const p=new DOMPoint(line.x1.baseVal.value+(line.x2.baseVal.value-line.x1.baseVal.value)*t,line.y1.baseVal.value+(line.y2.baseVal.value-line.y1.baseVal.value)*t).matrixTransform(m);return {x:p.x,y:p.y};},t);}
async function arm(page:Page){const button=page.getByRole('button',{name:'Add pull point',exact:true});await button.click();await expect(button).toHaveAttribute('aria-pressed','true');}
async function proof(page:Page,name:string){if(process.env.DECK_PULL_POINTS_PROOF==='1'){const folder=resolve('../../outputs/deckcraft-delete-pull-review/points');mkdirSync(folder,{recursive:true});await page.locator('#deck-live-preview').screenshot({path:resolve(folder,name)});}}
async function dragMouse(page:Page,dx:number,dy:number){const handle=page.getByRole('button',{name:'Main deck point 3',exact:true});await handle.scrollIntoViewIfNeeded();const b=(await handle.boundingBox())!,scale=await page.locator('.dd-boundary-editor').evaluate(el=>{const r=el.getBoundingClientRect(),v=el.querySelector('svg')!.viewBox.baseVal;return Math.min(r.width/v.width,r.height/v.height);});await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+dx*scale,b.y+b.height/2+dy*scale,{steps:4});await page.mouse.up();}

test('tap or pen an actual off-midpoint edge, focus and pull its new handle; each edit cancels and undoes independently',async({page,context})=>{
 await open(page);await page.getByRole('switch',{name:/^Free movement/}).check();const original=await read(page);await page.getByRole('button',{name:'Pan drawing',exact:true}).click();await arm(page);const position=await edgePosition(page,1),cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',buttons:1,pointerType:'pen',...position});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',buttons:0,pointerType:'pen',...position});await cdp.detach();
 await expect.poll(async()=>((await read(page)).boundaries[0].points.length)).toBe(5);await expect(page.getByRole('button',{name:'Add pull point',exact:true})).toHaveAttribute('aria-pressed','false');await expect(page.getByRole('button',{name:'Pan drawing',exact:true})).toHaveAttribute('aria-pressed','false');await expect(page.getByRole('button',{name:'Main deck point 3',exact:true})).toBeFocused();
 const inserted=await read(page);expect(inserted.boundaries[0].points[2].x).toBeCloseTo(192,4);expect(inserted.boundaries[0].points[2].y).toBeCloseTo(144*.27,3);expect(inserted.quantities).toEqual(original.quantities);await proof(page,'desktop-added-pull-point.png');
 await dragMouse(page,24,12);await expect.poll(async()=>((await read(page)).boundaries[0].points[2].x)).toBeCloseTo(216,2);await expect.poll(async()=>((await read(page)).boundaries[0].points[2].y)).toBeCloseTo(144*.27+12,2);await proof(page,'desktop-diagonal-pull.png');
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>((await read(page)).boundaries)).toEqual(inserted.boundaries);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>((await read(page)).boundaries)).toEqual(original.boundaries);
 await arm(page);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Add pull point',exact:true})).toHaveAttribute('aria-pressed','false');expect((await read(page)).design).toEqual(original.design);
});

test('custom and fixed directions move real points; invalid angle, locked topology and cancelled tap preserve design',async({page})=>{
 await open(page);await arm(page);const p=await edgePosition(page,1);await page.mouse.click(p.x,p.y);await expect.poll(async()=>((await read(page)).boundaries[0].points.length)).toBe(5);
 await page.getByLabel('Pull direction',{exact:true}).selectOption('custom');await page.getByLabel('Custom pull angle in degrees').fill('45');const before=await read(page);await dragMouse(page,12,0);const after=await read(page);expect(after.boundaries[0].points[2].x-before.boundaries[0].points[2].x).toBeCloseTo(6,2);expect(after.boundaries[0].points[2].y-before.boundaries[0].points[2].y).toBeCloseTo(6,2);await expect(page.locator('.dd-boundary-snap-guide')).toHaveCount(0);await proof(page,'desktop-custom-direction.png');
 const point=page.getByRole('button',{name:'Main deck point 3',exact:true});await point.press('Shift+ArrowRight');const keyboard=await read(page);expect(Math.hypot(keyboard.boundaries[0].points[2].x-after.boundaries[0].points[2].x,keyboard.boundaries[0].points[2].y-after.boundaries[0].points[2].y)).toBeCloseTo(12,6);
 await page.getByLabel('Custom pull angle in degrees').fill('361');await point.press('ArrowRight');await expect(page.locator('.dd-boundary-notice')).toContainText('360');expect((await read(page)).design).toEqual(keyboard.design);
 await page.getByLabel('Pull direction',{exact:true}).selectOption('x');await point.press('Shift+ArrowDown');expect((await read(page)).design).toEqual(keyboard.design);await point.press('ArrowRight');expect((await read(page)).boundaries[0].points[2].y).toBe(keyboard.boundaries[0].points[2].y);
 const lock=await page.evaluate(()=>window.deckcraft!.execute({id:'pull-point-lock',commands:[{type:'boundary.lock',level:1,index:3,locked:true}]}));expect(lock.ok,JSON.stringify(lock)).toBe(true);const locked=await read(page);await arm(page);const lockedPosition=await edgePosition(page,3,.27);await page.mouse.click(lockedPosition.x,lockedPosition.y);await expect(page.locator('.dd-boundary-notice')).toContainText('locked');expect((await read(page)).design).toEqual(locked.design);await page.keyboard.press('Escape');
 await arm(page);const cancelPosition=await edgePosition(page,0,.73);await page.mouse.move(cancelPosition.x,cancelPosition.y);await page.mouse.down();await page.locator('.dd-boundary-insert-target[data-level="1"][data-edge="0"]').dispatchEvent('pointercancel',{pointerId:1,pointerType:'mouse'});await page.mouse.up();expect((await read(page)).design).toEqual(locked.design);await page.keyboard.press('Escape');
});

for(const variant of ['phone','tablet'] as const)test(`@phone ${variant} touch inserts exactly on the edge; second finger cancels; fixed direction and controls remain usable`,async({page,context})=>{
 if(variant==='tablet')await page.setViewportSize({width:820,height:1180});await open(page);const original=await read(page);await arm(page);const tap=await edgePosition(page,1,.27),cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...tap,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(async()=>((await read(page)).boundaries[0].points.length)).toBe(5);const inserted=await read(page);expect(inserted.boundaries[0].points[2].y).toBeCloseTo(144*.27,2);expect(inserted.quantities).toEqual(original.quantities);
 await page.getByLabel('Pull direction',{exact:true}).selectOption('custom');await page.getByLabel('Custom pull angle in degrees').fill('90');const handle=page.getByRole('button',{name:'Main deck point 3',exact:true});await handle.scrollIntoViewIfNeeded();const bounds=(await handle.boundingBox())!,start={x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2},scale=await page.locator('.dd-boundary-editor').evaluate(el=>{const b=el.getBoundingClientRect(),v=el.querySelector('svg')!.viewBox.baseVal;return Math.min(b.width/v.width,b.height/v.height);});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...start,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+8*scale,y:start.y+18*scale,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const moved=await read(page);expect(moved.boundaries[0].points[2].x).toBe(inserted.boundaries[0].points[2].x);expect(moved.boundaries[0].points[2].y-inserted.boundaries[0].points[2].y).toBeCloseTo(18,2);
 await page.getByLabel('Custom pull angle in degrees').scrollIntoViewIfNeeded();for(const control of [page.getByRole('button',{name:'Add pull point',exact:true}),page.getByLabel('Pull direction',{exact:true}),page.getByLabel('Custom pull angle in degrees')]){const b=(await control.boundingBox())!;expect(b.height).toBeGreaterThanOrEqual(44);expect(b.width).toBeGreaterThanOrEqual(44);}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await proof(page,`${variant}-direction-controls.png`);
 await arm(page);const edge=await edgePosition(page,0,.27);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...edge,id:3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...edge,id:3},{x:edge.x+35,y:edge.y+40,id:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});expect((await read(page)).design).toEqual(moved.design);await page.keyboard.press('Escape');await cdp.detach();
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>((await read(page)).boundaries)).toEqual(inserted.boundaries);
});
