import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
import type {YardFeature} from '../src/features/deckcraft/types';
import {GROUP_MS} from '../src/features/deckcraft/designer/designHistory';
const patio:YardFeature={id:'qa-patio',kind:'patio',name:'QA patio',enabled:true,xFt:6,zFt:26,widthFt:12,depthFt:10,heightIn:0,rotationDeg:0,productId:'permacon-melville',color:'#aaa69b',outline:[{x:-72,y:-60},{x:72,y:-60},{x:72,y:60},{x:-72,y:60}]};
const fixture={...DEFAULT_DECK,houseVisible:false,deckType:'Freestanding',stairFlights:0,railingType:'None',yardFeatures:[patio]};
const proof=resolve(process.cwd(),'../../outputs/deckcraft-patio-inlay-review');mkdirSync(proof,{recursive:true});
const read=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
async function ready(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);return read(page);}
const controls=(page:Page)=>page.getByLabel('Patio and wall shape controls',{exact:true});
const inlays=(page:Page)=>controls(page).getByRole('region',{name:'Patio inlays',exact:true});
async function spot(page:Page,x:number,y:number){const svg=page.locator('.dd-patio-inlay-overlay>svg');await svg.scrollIntoViewIfNeeded();return svg.evaluate((el,p)=>{const m=(el as SVGSVGElement).getScreenCTM()!;const q=new DOMPoint(p.x,p.y).matrixTransform(m);return{x:q.x,y:q.y};},{x:patio.xFt*12+x,y:patio.zFt*12+y});}
async function place(page:Page,x:number,y:number,touch=false){const p=await spot(page,x,y);if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
async function focusPatio(page:Page){
 const canvas=page.getByLabel('Deck drawing canvas',{exact:true});await canvas.scrollIntoViewIfNeeded();const before=(await read(page)).design;
 expect((await canvas.boundingBox())!.height).toBeGreaterThanOrEqual(page.viewportSize()!.width<800?239.9:359.9);
 const p=await canvas.locator('.dd-plan-stage svg').first().evaluate(el=>{const m=(el as SVGSVGElement).getScreenCTM()!,q=new DOMPoint(72,312).matrixTransform(m);return{x:q.x,y:q.y};}),b=(await canvas.locator('.dd-plan-stage').boundingBox())!;
 const origin={x:b.x+24,y:b.y+40};await page.mouse.move(origin.x,origin.y);await page.mouse.down({button:'middle'});await page.mouse.move(origin.x+b.x+b.width/2-p.x,origin.y+b.y+b.height*.5-p.y,{steps:8});await page.mouse.up({button:'middle'});
 for(let n=0;n<5;n++)await page.getByRole('button',{name:'Zoom in',exact:true}).click();expect((await read(page)).design).toEqual(before);
 const dimensions=await canvas.evaluate(el=>{const ancestors=[];for(let e:Element|null=el;e;e=e.parentElement){const c=getComputedStyle(e),b=e.getBoundingClientRect();ancestors.push({tag:e.tagName,class:e.className,rect:{x:b.x,y:b.y,w:b.width,h:b.height},height:c.height,maxHeight:c.maxHeight,overflow:c.overflow,overflowY:c.overflowY});}return {viewport:{w:innerWidth,h:innerHeight},ancestors};});writeFileSync(resolve(proof,`${page.viewportSize()!.width<800?'phone':'desktop'}-canvas-bounds.json`),JSON.stringify(dimensions,null,2));
}
test.beforeEach(async({page,context})=>{await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{const key='golden-maple.deck-studio.deck-only.v1';if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},fixture);await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&['GET','HEAD'].includes(r.request().method())?r.continue():r.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await ready(page);await page.getByRole('radio',{name:'Patios & walls',exact:true}).click();await expect(inlays(page)).toBeVisible();});

for(const touch of [false,true])test(`${touch?'@phone ':''}patio inlays place rotate edit material delete Undo and persist`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const ui=inlays(page);
 await ui.getByLabel('Patio inlay shape',{exact:true}).selectOption('compass');await ui.getByRole('button',{name:'Add patio inlay',exact:true}).click();await place(page,0,0,touch);
 await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays?.length??0).toBe(1);const added=(await ready(page)).design.yardFeatures![0];expect(added.inlays![0].shape).toBe('compass');expect(added.inlays![0].hardscape).toBeTruthy();expect(added.outline).toEqual(patio.outline);
 await expect(page.locator('.dd-yard-shape-handle')).toHaveCount(0);await ui.getByRole('button',{name:'Finish inlay editing',exact:true}).click();await expect(page.locator('.dd-yard-shape-handle')).toHaveCount(9);await ui.getByLabel('Selected patio inlay',{exact:true}).selectOption(added.inlays![0].id);await expect(page.locator('.dd-yard-shape-handle')).toHaveCount(0);
 const move=page.getByRole('button',{name:'Move patio inlay Compass rose',exact:true});await move.focus();await move.press('ArrowRight');await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays![0].xIn).toBeCloseTo(added.inlays![0].xIn+1,8);
 await ui.getByLabel('Patio inlay rotation (°)',{exact:true}).fill('137.5');await ui.getByLabel('Patio inlay rotation (°)',{exact:true}).press('Enter');await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays![0].rotationDeg).toBe(137.5);
 await ui.getByRole('button',{name:'Choose inlay stone & pattern',exact:true}).click();const library=ui.getByRole('region',{name:'Ontario supplier library',exact:true});await expect(library).toBeVisible();const colours=library.getByRole('group',{name:'Supplier stone colours',exact:true}).getByRole('button');if(await colours.count()>1)await colours.last().click();await library.getByLabel('Hardscape laying direction',{exact:true}).fill('275.5');await library.getByLabel('Hardscape laying direction',{exact:true}).press('Enter');await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays![0].hardscape!.angleDeg).toBe(275.5);
 await library.getByLabel('Hardscape laying direction',{exact:true}).fill('360');await library.getByLabel('Hardscape laying direction',{exact:true}).press('Enter');await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays![0].hardscape!.angleDeg).toBe(0);await ui.getByRole('button',{name:'Choose inlay stone & pattern',exact:true}).click();
 const kept=(await ready(page)).design.yardFeatures![0];await page.waitForTimeout(GROUP_MS+75);await move.focus();await move.press('Delete');await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays?.length??0).toBe(0);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await read(page)).design.yardFeatures![0]).toEqual(kept);
 await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.deck-only.v1')??'{}').configuration?.yardFeatures?.[0])).toEqual(kept);
 await ui.getByLabel('Selected patio inlay',{exact:true}).selectOption(kept.inlays![0].id);await ui.locator('.dd-patio-inlay-fields').screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-inlay-controls.png`)});await ui.locator('.dd-patio-inlay-actions').screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-inlay-actions.png`)});await page.getByRole('radio',{name:'Select parts',exact:true}).click();await focusPatio(page);await page.getByLabel('Deck drawing canvas',{exact:true}).screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-compass-plan.png`)});
 if(!touch){await page.getByRole('tab',{name:'3D',exact:true}).click();await page.getByRole('group',{name:'Camera',exact:true}).getByRole('button',{name:'Overview',exact:true}).click();const viewer=page.getByRole('region',{name:'Interactive deck construction model',exact:true});await expect(viewer.locator('canvas')).toBeVisible();await page.waitForLoadState('networkidle');await page.waitForTimeout(1500);await viewer.screenshot({path:resolve(proof,'desktop-compass-physical-3d.png')});expect((await read(page)).design.yardFeatures![0]).toEqual(kept);}
 await page.reload();await ready(page);expect((await read(page)).design.yardFeatures![0]).toEqual(kept);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
});

test('custom patio inlay closes on right-click and corner pulls commit once',async({page})=>{
 const ui=inlays(page);await ui.getByLabel('Patio inlay shape',{exact:true}).selectOption('custom');await ui.getByRole('button',{name:'Add patio inlay',exact:true}).click();await place(page,-18,-18);await place(page,18,-18);await place(page,18,18);await place(page,-18,18);const p=await spot(page,-18,18);await page.mouse.click(p.x,p.y,{button:'right'});
 await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays?.length??0).toBe(1);const initial=(await ready(page)).design.yardFeatures![0];expect(initial.inlays![0].shape).toBe('custom');expect(initial.inlays![0].widthIn).toBeCloseTo(36,3);expect(initial.inlays![0].depthIn).toBeCloseTo(36,3);expect(initial.inlays![0].points).toHaveLength(4);
 await page.waitForTimeout(GROUP_MS+75);const corner=page.getByRole('button',{name:'Patio inlay corner 3',exact:true});await corner.scrollIntoViewIfNeeded();const b=(await corner.boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+18,b.y+b.height/2+12,{steps:5});await page.mouse.up();await expect.poll(async()=>(await read(page)).design.yardFeatures![0].inlays![0].points).not.toEqual(initial.inlays![0].points);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await read(page)).design.yardFeatures![0]).toEqual(initial);await page.getByLabel('Deck drawing canvas',{exact:true}).screenshot({path:resolve(proof,'desktop-custom-sketch.png')});
});

test('full pattern rotation keeps the patio footprint fixed and slider release is one Undo',async({page})=>{
 const c=controls(page);await c.getByRole('button',{name:'Choose patio material',exact:true}).click();const library=c.getByRole('region',{name:'Ontario supplier library',exact:true});await library.getByLabel('Supplier hardscape product',{exact:true}).selectOption('techo-aberdeen-slab');await ready(page);
 await library.getByLabel('Hardscape laying direction',{exact:true}).fill('319.5');await library.getByLabel('Hardscape laying direction',{exact:true}).press('Enter');await expect.poll(async()=>(await read(page)).design.yardFeatures![0].hardscape!.angleDeg).toBe(319.5);const before=(await ready(page)).design.yardFeatures![0];expect(before.outline).toEqual(patio.outline);expect(before.rotationDeg).toBe(0);
 await page.waitForTimeout(GROUP_MS+75);const slider=library.getByLabel('Rotate hardscape pattern',{exact:true});await slider.scrollIntoViewIfNeeded();const b=(await slider.boundingBox())!;await page.mouse.move(b.x+b.width*.25,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width*.7,b.y+b.height/2,{steps:8});await page.mouse.up();await expect.poll(async()=>(await read(page)).design.yardFeatures![0].hardscape!.angleDeg).not.toBe(319.5);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await read(page)).design.yardFeatures![0]).toEqual(before);await library.locator('.dd-hardscape-rotation').screenshot({path:resolve(proof,'desktop-aberdeen-full-rotation.png')});await library.getByRole('group',{name:'Original manufacturer patterns',exact:true}).screenshot({path:resolve(proof,'desktop-aberdeen-source-pattern.png')});await c.getByRole('button',{name:'Choose patio material',exact:true}).click();await page.getByRole('radio',{name:'Select parts',exact:true}).click();await focusPatio(page);await page.getByLabel('Deck drawing canvas',{exact:true}).screenshot({path:resolve(proof,'desktop-aberdeen-rotated-plan.png')});
});
