import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import sharp from 'sharp';
import type {DeckAgentApi,AgentCommand,AgentResponse} from '../src/features/deckcraft/designer/deckAgentController';
import type {SketchDocument} from '../src/features/deckcraft/sketch/sketchTypes';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';

const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const pageErrors=new WeakMap<Page,string[]>();
let sequence=0;
async function request(page:Page,commands:AgentCommand[],preview=false,revision?:number){
 return page.evaluate(async({commands,preview,id,revision})=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;return api[preview?'preview':'execute']({commands,id,expectedRevision:revision??api.read().revision});},{commands,preview,id:`sketch-independent-${++sequence}`,revision});
}
function success(response:AgentResponse){if('error' in response)throw new Error(`${response.error.code}: ${response.error.message}`);return response;}
const house={id:'house',kind:'house' as const,label:'House',points:[{x:100,y:100},{x:460,y:100},{x:460,y:300},{x:100,y:300}]};
const rectangle:SketchDocument={version:1,shapes:[house,{id:'deck',kind:'deck',label:'Main deck',widthFt:20,depthFt:12,heightIn:30,points:[{x:100,y:300},{x:340,y:300},{x:340,y:444},{x:100,y:444}]}]};
const stepped:SketchDocument={version:1,shapes:[house,{...rectangle.shapes[1],points:[{x:100,y:300},{x:340,y:300},{x:340,y:444},{x:220,y:444},{x:220,y:420},{x:100,y:420}]}]};
const connected:SketchDocument={version:1,shapes:[...rectangle.shapes,{id:'landing',kind:'landing',label:'Lower landing',widthFt:10,depthFt:6,heightIn:12,points:[{x:160,y:444},{x:280,y:444},{x:280,y:516},{x:160,y:516}]},{id:'stairs',kind:'stairs',label:'Grade stairs',widthFt:4,depthFt:1,heightIn:12,points:[{x:196,y:516},{x:244,y:516},{x:244,y:528},{x:196,y:528}]}]};
const area=(points:{x:number;y:number}[])=>Math.abs(points.reduce((sum,p,i)=>{const next=points[(i+1)%points.length];return sum+p.x*next.y-next.x*p.y;},0))/2;
const proof=resolve(process.cwd(),'../../outputs/deckcraft-sketch-review');mkdirSync(proof,{recursive:true});
const draft=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.sketch-draft.v1')??'{"version":1,"shapes":[]}') as SketchDocument);
const modal=(page:Page)=>page.getByRole('dialog',{name:'Sketch a design',exact:true});
async function openSketch(page:Page,resume=false){await page.getByRole('button',{name:'Sketch a design',exact:true}).click();await expect(modal(page)).toBeVisible();await expect(modal(page).getByRole('button',{name:'Close sketch designer'})).toBeFocused();if(resume){await modal(page).locator('summary').filter({hasText:'Sketch files & reset'}).click();await modal(page).getByRole('button',{name:'Resume saved sketch',exact:true}).click();}else await modal(page).getByRole('button',{name:'New sketch',exact:true}).click();}
async function screenPoints(page:Page,points:{x:number;y:number}[]){const canvas=modal(page).getByRole('group',{name:'Sketch canvas',exact:true});await canvas.scrollIntoViewIfNeeded();return canvas.evaluate((el,points)=>{const matrix=(el as SVGSVGElement).getScreenCTM()!;return points.map(p=>{const v=new DOMPoint(p.x,p.y).matrixTransform(matrix);return {x:v.x,y:v.y};});},points);}
async function trace(page:Page,context:BrowserContext,shape:SketchDocument['shapes'][number],touch=false){
 await modal(page).getByRole('button',{name:`Draw ${shape.kind}`,exact:true}).click();await modal(page).getByRole('button',{name:'Freehand',exact:true}).click();const points=await screenPoints(page,[...shape.points,shape.points[0]]);
 if(touch){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...points[0],id:1}]});for(const point of points.slice(1))await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...point,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}
 else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const point of points.slice(1))await page.mouse.move(point.x,point.y,{steps:5});await page.mouse.up();}
 await modal(page).getByRole('textbox',{name:'Shape label or description',exact:true}).fill(shape.label);
 if(shape.widthFt!==undefined)await modal(page).getByRole('spinbutton',{name:/^Measured width/}).fill(String(shape.widthFt));
 if(shape.depthFt!==undefined)await modal(page).getByRole('spinbutton',{name:/^Measured depth/}).fill(String(shape.depthFt));
 if(shape.heightIn!==undefined)await modal(page).getByRole('spinbutton',{name:/^Height above grade/}).fill(String(shape.heightIn));
}

test.beforeEach(async({context,page})=>{
 const errors:string[]=[];pageErrors.set(page,errors);page.on('pageerror',error=>errors.push(error.message));
 await context.addInitScript('window.__name=(target,value)=>target;');
 await context.addInitScript(({key,configuration})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},{key:'golden-maple.deck-studio.deck-only.v1',configuration:{...DEFAULT_DECK,deckingColor:'Sea Salt Gray',customerName:'QA Sketch Customer',projectAddress:'QA fixture address'}});
 await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&r.request().method()==='GET'?r.continue():r.fulfill({status:200,body:''}));
 await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);
});
test.afterEach(async({page})=>{expect(pageErrors.get(page)??[],'Sketch flows must not produce an uncaught browser exception').toEqual([]);});

for(const configuration of [{name:'desktop',width:1440,height:1000,touch:false},{name:'phone',width:390,height:844,touch:true},{name:'tablet',width:768,height:1024,touch:true}])test.describe(`${configuration.name} complete sketch`,()=>{
 test.use({viewport:{width:configuration.width,height:configuration.height},hasTouch:configuration.touch,isMobile:configuration.name==='phone'});
 test(`${configuration.touch?'@phone ':''}real house/deck/landing/stair drawing generates editable geometry and one Apply undo`,async({page,context})=>{
  const original=await state(page),initialScripts=await page.evaluate(()=>performance.getEntriesByType('resource').filter(p=>(p as PerformanceResourceTiming).initiatorType==='script').map(p=>p.name));await openSketch(page);
  const openedScripts=await page.evaluate(()=>performance.getEntriesByType('resource').filter(p=>(p as PerformanceResourceTiming).initiatorType==='script').map(p=>p.name)),introduced=openedScripts.filter(url=>!initialScripts.includes(url));
  const loaded=await Promise.all(introduced.map(async url=>{const response=await page.request.get(url),source=await response.text();return {url,bytes:Buffer.byteLength(source),sketchUi:source.includes('Sketch canvas'),sketchEngine:source.includes('Labels and handwriting are not read as measurements')};}));expect(loaded.some(p=>p.sketchUi)).toBe(true);writeFileSync(resolve(proof,`${configuration.name}-lazy-loading.json`),JSON.stringify({initialScriptCount:initialScripts.length,loadedAfterOpen:loaded},null,2));
  const main=configuration.name==='phone'?stepped.shapes[1]:rectangle.shapes[1];const landingX=configuration.name==='phone'?220:160;
  const shapes:SketchDocument['shapes']=[house,main,{id:'landing',kind:'landing',label:'Measured landing',widthFt:10,depthFt:6,heightIn:24,points:[{x:landingX,y:444},{x:landingX+120,y:444},{x:landingX+120,y:516},{x:landingX,y:516}]},{id:'stairs',kind:'stairs',label:'Four-riser grade stairs',widthFt:4,depthFt:2.7,heightIn:24,points:[{x:landingX+36,y:516},{x:landingX+84,y:516},{x:landingX+84,y:548.4},{x:landingX+36,y:548.4}]}];
  for(const shape of shapes)await trace(page,context,configuration.name==='phone'&&shape.kind!=='house'?{...shape,points:shape.points.map(p=>({...p,y:p.y+3}))}:shape,configuration.touch);
  expect((await draft(page)).shapes).toHaveLength(4);expect((await state(page)).design).toEqual(original.design);expect((await state(page)).pricing).toEqual(original.pricing);
  await modal(page).getByRole('group',{name:'Sketch canvas'}).scrollIntoViewIfNeeded();await page.screenshot({path:resolve(proof,`${configuration.name}-measured-sketch.png`)});
  for(const name of ['Draw house','Draw deck','Draw landing','Draw stairs','Generate design','Close sketch designer']){const rect=await modal(page).getByRole('button',{name,exact:true}).boundingBox();expect(rect!.width).toBeGreaterThanOrEqual(44);expect(rect!.height).toBeGreaterThanOrEqual(44);}
  await modal(page).getByRole('button',{name:'Generate design',exact:true}).click();await expect(modal(page).getByRole('tabpanel',{name:'Plan sketch preview'})).toBeVisible();const expectedArea=configuration.name==='phone'?280:300;
  await expect(modal(page).getByRole('status',{name:'Sketch preview price'})).toContainText(`${expectedArea} sq ft`);await expect(modal(page).locator('.dd-sketch-generated svg')).toBeVisible();expect((await state(page)).design).toEqual(original.design);expect((await state(page)).history).toEqual(original.history);expect((await state(page)).pricing).toEqual(original.pricing);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);expect(await modal(page).evaluate(el=>el.scrollWidth-el.clientWidth)).toBe(0);await page.screenshot({path:resolve(proof,`${configuration.name}-plan-preview.png`)});
  await modal(page).getByRole('tab',{name:'3D',exact:true}).click();const previewCanvas=modal(page).getByRole('tabpanel',{name:'3D sketch preview'}).locator('canvas');await expect(previewCanvas).toBeVisible({timeout:30000});await expect.poll(async()=>{const stats=await sharp(await previewCanvas.screenshot()).stats();return Math.max(...stats.channels.slice(0,3).map(channel=>channel.stdev));},{timeout:30000,message:'3D sketch preview must render actual scene pixels before capture or Apply'}).toBeGreaterThan(10);await page.screenshot({path:resolve(proof,`${configuration.name}-3d-preview.png`)});
  await modal(page).getByRole('button',{name:'Apply design',exact:true}).click();await expect(modal(page)).toBeHidden();const applied=await state(page);expect(applied.design.levels).toBe(2);expect(applied.design.width).toBeCloseTo(20,6);expect(applied.design.length).toBeCloseTo(12,6);expect(applied.design.height2).toBe(24);expect(applied.design.stairFlights).toBe(1);expect(applied.design.stairWidth).toBeCloseTo(48,6);expect(applied.pricing.areaSqft).toBeCloseTo(expectedArea,3);expect(applied.design.deckingColor).toBe('Sea Salt Gray');expect(applied.pricing.priceBook).toEqual(original.pricing.priceBook);
  success(await request(page,[{type:'history.undo'}]));expect((await state(page)).design).toEqual(original.design);expect((await state(page)).pricing).toEqual(original.pricing);success(await request(page,[{type:'history.redo'}]));expect((await state(page)).design).toEqual(applied.design);await expect(page.getByRole('region',{name:'Live price'})).toBeVisible();await page.screenshot({path:resolve(proof,`${configuration.name}-applied-design.png`)});
 });
});

test('keyboard rectangle, draft retention, stale preview and reset never apply old geometry',async({page})=>{
 const original=await state(page);await openSketch(page);const add=modal(page).getByRole('button',{name:'Add measured rectangle',exact:true}).first();await add.focus();await page.keyboard.press('Enter');await modal(page).getByRole('textbox',{name:'Rectangle label',exact:true}).fill('Keyboard measured deck');await modal(page).getByRole('spinbutton',{name:/^Rectangle width/}).fill('20');await modal(page).getByRole('spinbutton',{name:/^Rectangle depth/}).fill('12');await modal(page).getByRole('spinbutton',{name:/^Rectangle height/}).fill('30');await modal(page).getByRole('button',{name:'Add rectangle',exact:true}).focus();await page.keyboard.press('Enter');expect((await draft(page)).shapes).toHaveLength(1);
 const saved=await draft(page);await page.keyboard.press('Escape');await expect(modal(page)).toBeHidden();await expect(page.getByRole('button',{name:'Sketch a design',exact:true})).toBeFocused();expect((await state(page)).design).toEqual(original.design);await openSketch(page,true);expect(await draft(page)).toEqual(saved);
 await modal(page).getByRole('button',{name:'Generate design',exact:true}).click();await expect(modal(page).getByRole('button',{name:'Apply design',exact:true})).toBeEnabled();expect((await state(page)).design).toEqual(original.design);
 success(await request(page,[{type:'design.patch',patch:{height:34}}]));const changed=await state(page);await expect(modal(page).getByRole('alert')).toContainText('current design changed');await expect(modal(page).getByRole('button',{name:'Apply design',exact:true})).toBeDisabled();await page.screenshot({path:resolve(proof,'desktop-stale-preview.png')});
 await modal(page).getByRole('button',{name:'Keep sketching',exact:true}).click();await modal(page).locator('summary').filter({hasText:'Sketch files & reset'}).click();await modal(page).getByRole('button',{name:'Clear sketch',exact:true}).click();await expect(modal(page).getByRole('button',{name:'Generate design',exact:true})).toBeDisabled();await expect(modal(page).getByRole('button',{name:'Apply design',exact:true})).toHaveCount(0);expect((await state(page)).design).toEqual(changed.design);
 await modal(page).getByRole('button',{name:'Undo sketch',exact:true}).click();expect(await draft(page)).toEqual(saved);await modal(page).getByRole('spinbutton',{name:/^Measured width/}).fill('');await modal(page).getByRole('spinbutton',{name:/^Measured depth/}).fill('');await modal(page).getByRole('textbox',{name:'Shape label or description',exact:true}).fill('Deck 20 × 12 handwritten label');await modal(page).getByRole('button',{name:'Generate design',exact:true}).click();await expect(modal(page).getByRole('alert')).toContainText('Labels and handwriting are not read');expect((await state(page)).design).toEqual(changed.design);expect((await state(page)).pricing).toEqual(changed.pricing);await page.screenshot({path:resolve(proof,'desktop-unmeasured-error.png')});
});

test.describe('phone sketch cancellation',()=>{test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});test('@phone cancelled touch and a second finger cannot create an extra shape',async({page,context})=>{
 const original=await state(page);await openSketch(page);await modal(page).getByRole('button',{name:'Draw deck',exact:true}).click();const p=await screenPoints(page,[{x:200,y:180},{x:600,y:180},{x:600,y:420},{x:200,y:420},{x:200,y:180}]),cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p[0],id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...p[1],id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});expect((await draft(page)).shapes).toHaveLength(0);await expect(modal(page).getByRole('status').last()).toContainText('cancelled');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p[0],id:1}]});const secondary={x:p[0].x+25,y:p[0].y+30,id:2};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p[0],id:1},secondary]});for(const point of p.slice(1))await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...point,id:1},secondary]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[secondary]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});expect((await draft(page)).shapes).toHaveLength(1);
 await modal(page).getByRole('button',{name:'Draw house',exact:true}).click();const pen=await screenPoints(page,[{x:700,y:100},{x:950,y:100},{x:950,y:300},{x:700,y:300},{x:700,y:100}]);await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',...pen[0],button:'left',buttons:1,clickCount:1,pointerType:'pen'});for(const point of pen.slice(1))await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',...point,button:'left',buttons:1,pointerType:'pen'});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',...pen.at(-1)!,button:'left',buttons:0,clickCount:1,pointerType:'pen'});expect((await draft(page)).shapes).toHaveLength(2);expect((await draft(page)).shapes[1].kind).toBe('house');
 const retained=await draft(page);await modal(page).getByRole('button',{name:'Draw deck',exact:true}).click();const cross=await screenPoints(page,[{x:400,y:200},{x:700,y:420},{x:700,y:200},{x:400,y:420},{x:400,y:200}]);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...cross[0],id:1}]});for(const point of cross.slice(1))await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...point,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();expect(await draft(page)).toEqual(retained);await expect(modal(page).getByRole('status').last()).toContainText('cross');await modal(page).getByRole('button',{name:'Close sketch designer'}).click();await openSketch(page,true);expect(await draft(page)).toEqual(retained);expect((await state(page)).design).toEqual(original.design);expect((await state(page)).history).toEqual(original.history);expect((await state(page)).pricing).toEqual(original.pricing);await page.screenshot({path:resolve(proof,'phone-cancel-secondary-pointer.png')});
});});

test('structured sketch preview retains products, preserves an arbitrary measured outline, and applies as one undo step',async({page})=>{
 const original=await state(page),dry=success(await request(page,[{type:'sketch.generate',document:rectangle}],true));
 expect((await state(page)).design).toEqual(original.design);expect((await state(page)).history).toEqual(original.history);expect((await state(page)).pricing).toEqual(original.pricing);
 expect(dry.snapshot.design.width).toBe(20);expect(dry.snapshot.design.length).toBe(12);expect(dry.snapshot.design.height).toBe(30);expect(dry.snapshot.pricing.areaSqft).toBeCloseTo(240,3);
 const custom=success(await request(page,[{type:'sketch.generate',document:stepped}],true));
 expect(custom.snapshot.design.deckOutlines?.main).toBeTruthy();expect(area(custom.snapshot.design.deckOutlines!.main!)).toBeCloseTo(220,3);expect(custom.snapshot.pricing.areaSqft).toBeCloseTo(220,3);
 for(const key of ['deckingMaterial','deckingColor','railingType','municipality','foundation','joistSpacing'] as const)expect(custom.snapshot.design[key]).toEqual(original.design[key]);
 expect(custom.snapshot.pricing.priceBook).toEqual(original.pricing.priceBook);expect(custom.interpretation?.summary.length).toBeGreaterThan(0);
 const nearWall:SketchDocument={version:1,shapes:rectangle.shapes.map(s=>s.kind==='house'?s:{...s,points:s.points.map(p=>({...p,y:p.y+3}))})};const aligned=success(await request(page,[{type:'sketch.generate',document:nearWall}],true));expect(Math.min(...aligned.snapshot.design.deckOutlines!.main!.map(p=>p.y))).toBeCloseTo(0,3);expect(aligned.interpretation?.warnings.join(' ')).toMatch(/3(?:\.0+)?\s*(?:in|inch)/i);
 const tooFar:SketchDocument={version:1,shapes:rectangle.shapes.map(s=>s.kind==='house'?s:{...s,points:s.points.map(p=>({...p,y:p.y+8}))})};expect((await request(page,[{type:'sketch.generate',document:tooFar}],true)).ok).toBe(false);expect((await state(page)).design).toEqual(original.design);
 const landing=success(await request(page,[{type:'sketch.generate',document:connected}],true));expect(landing.snapshot.design.levels).toBe(2);expect(landing.snapshot.design.width2).toBe(10);expect(landing.snapshot.design.length2).toBe(6);expect(landing.snapshot.design.height2).toBe(12);expect(landing.snapshot.design.stairFlights).toBe(1);expect(landing.snapshot.design.stairWidth).toBe(48);expect(landing.snapshot.pricing.areaSqft).toBeCloseTo(300,3);expect((await state(page)).design).toEqual(original.design);
 const applied=success(await request(page,[{type:'sketch.generate',document:stepped}]));expect(applied.snapshot.design).toEqual(custom.snapshot.design);expect(applied.snapshot.pricing).toEqual(custom.snapshot.pricing);
 await expect.poll(()=>page.evaluate(()=>{const c=JSON.parse(localStorage.getItem('golden-maple.deck-studio.deck-only.v1')??'{}').configuration;return {name:c?.customerName,address:c?.projectAddress,width:c?.width,outline:c?.deckOutlines?.main};})).toEqual({name:'QA Sketch Customer',address:'QA fixture address',width:20,outline:applied.snapshot.design.deckOutlines?.main});
 success(await request(page,[{type:'history.undo'}]));expect((await state(page)).design).toEqual(original.design);expect((await state(page)).pricing).toEqual(original.pricing);
 success(await request(page,[{type:'history.redo'}]));expect((await state(page)).design).toEqual(applied.snapshot.design);
 const crossing:SketchDocument={version:1,shapes:[house,{...rectangle.shapes[1],points:[{x:100,y:300},{x:340,y:444},{x:340,y:300},{x:100,y:444}]}]};
 const beforeInvalid=await state(page),invalid=await request(page,[{type:'sketch.generate',document:crossing}]);expect(invalid.ok).toBe(false);expect((await state(page)).design).toEqual(beforeInvalid.design);expect((await state(page)).history).toEqual(beforeInvalid.history);expect((await state(page)).pricing).toEqual(beforeInvalid.pricing);
 const revision=beforeInvalid.revision;success(await request(page,[{type:'design.patch',patch:{height:32}}]));const fresh=await state(page),stale=await request(page,[{type:'sketch.generate',document:rectangle}],false,revision);expect(stale.ok).toBe(false);expect((await state(page)).design).toEqual(fresh.design);
});
