import {test,expect,type Page} from '@playwright/test';
import {pickPlanTool} from './nav';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import * as THREE from 'three';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {getHouseConfig} from '../src/features/deckcraft/houseSettings';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {sceneBounds} from '../src/features/deckcraft/components/viewer3d/sceneBounds';
import {cameraSetback} from '../src/features/deckcraft/components/viewer3d/cameraFraming';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
import type {DeckData} from '../src/features/deckcraft/types';
const proof=resolve(process.cwd(),'../../outputs/deckcraft-easy-edit-review/selection');mkdirSync(proof,{recursive:true});
const projection=JSON.parse(readFileSync(resolve(process.cwd(),'e2e/fixtures/easy-selection-projection.json'),'utf8')) as {screen:{x:number;y:number;z:number}};
const fixture:DeckData={...DEFAULT_DECK,width:20,length:20,height:48,stairFlights:0,houseConfig:{...getHouseConfig(DEFAULT_DECK),widthFt:30,depthFt:20,storeys:2,openings:[{id:'selection-a',type:'Window',facade:'Front',widthIn:48,heightIn:36,bottomIn:100,offsetPct:25},{id:'selection-b',type:'Window',facade:'Front',widthIn:48,heightIn:36,bottomIn:100,offsetPct:75}]},privacyScreens:[{id:'screen-a',side:'Left',lengthFt:4,heightFt:6,offsetPct:20,lights:false},{id:'screen-b',side:'Left',lengthFt:4,heightFt:6,offsetPct:60,lights:false}],customerName:'Selection QA'};
const read=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
async function tool(page:Page,name:string){const show=page.getByRole('button',{name:'Show canvas',exact:true});if(await show.isVisible())await show.click();await pickPlanTool(page,name);}
async function undo(page:Page){await page.getByRole('region',{name:'Save and restore design',exact:true}).getByRole('button',{name:'Undo',exact:true}).click();}
test.beforeEach(async({context,page})=>{
 await context.addInitScript('window.__name=(target,value)=>target;');
 await context.addInitScript(configuration=>localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration})),fixture);
 await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&r.request().method()==='GET'?r.continue():r.fulfill({status:200,body:''}));
 await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready)).toBe(true);
});
for(const v of [{name:'desktop',width:1440,height:1000,touch:false},{name:'phone',width:390,height:844,touch:true},{name:'tablet',width:768,height:1024,touch:true}])test.describe(`${v.name} shared selection`,()=>{
 test.use({viewport:{width:v.width,height:v.height},hasTouch:v.touch,isMobile:v.name==='phone'});
 test(`${v.touch?'@phone ':''}stages one screen and board batch with real review, rejection and undo`,async({page})=>{
  const checkpoints:string[]=[],mark=(text:string)=>checkpoints.push(text);await tool(page,'Select parts');const before=await read(page);
  await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('screen');await page.getByRole('checkbox',{name:'Select multiple parts',exact:true}).check();await page.getByRole('button',{name:'Select all matching parts',exact:true}).click();
  expect((await read(page)).design).toEqual(before.design);expect((await read(page)).history).toEqual(before.history);mark('Filtered touch/keyboard multiselect makes no design or history write');
  await page.getByRole('combobox',{name:'Batch part operation',exact:true}).selectOption('move');await page.getByRole('spinbutton',{name:'Batch part value',exact:true}).fill('70');await page.getByRole('button',{name:'Review selected part changes',exact:true}).click();await expect(page.locator('.dd-component-notice')).toContainText('between 0 and 100');expect((await read(page)).design).toEqual(before.design);mark('Out-of-range member rejects all changes and retains selection');
  await page.getByRole('combobox',{name:'Batch part operation',exact:true}).selectOption('distribute');await page.getByRole('button',{name:'Review selected part changes',exact:true}).click();await expect(page.locator('.dd-component-batch')).toContainText('Priced portion including HST');expect((await read(page)).design).toEqual(before.design);mark('Exact batch price and outstanding quote review precedes any write');
  await page.screenshot({path:resolve(proof,`${v.name}-screen-batch.png`),fullPage:true});await page.getByRole('button',{name:'Apply to selected parts',exact:true}).click();await expect.poll(async()=>JSON.stringify((await read(page)).design.privacyScreens)).not.toBe(JSON.stringify(before.design.privacyScreens));const moved=await read(page);expect(moved.design.privacyScreens?.map(s=>s.offsetPct)).toEqual([0,100]);mark('One Apply distributes the actual saved screens');
  await undo(page);await expect.poll(async()=>JSON.stringify((await read(page)).design.privacyScreens)).toBe(JSON.stringify(before.design.privacyScreens));mark('One Undo restores both screen positions');
  await page.getByRole('checkbox',{name:'Select multiple parts',exact:true}).uncheck();await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('opening');await page.getByRole('combobox',{name:'Select plan part',exact:true}).selectOption('opening:selection-a');
  const near=page.getByRole('toolbar',{name:'Selected object actions',exact:true});await expect(near).toBeVisible();const nearRect=await near.boundingBox(),canvasRect=await page.locator('.dd-component-editor').boundingBox();expect(nearRect!.x).toBeGreaterThanOrEqual(canvasRect!.x-1);expect(nearRect!.x+nearRect!.width).toBeLessThanOrEqual(canvasRect!.x+canvasRect!.width+1);const targetSizes=await near.getByRole('button').evaluateAll(buttons=>buttons.map(b=>({w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})));expect(targetSizes.every(r=>r.w>=44&&r.h>=44)).toBe(true);mark('Near-object toolbar stays inside the actual drawing with 44px actions');
  await tool(page,'Board layout');await page.getByRole('checkbox',{name:'Select multiple boards',exact:true}).check();const rows=page.getByRole('group',{name:'Toggle boards in selection',exact:true}).getByRole('checkbox');await rows.nth(4).check();await rows.nth(8).check();const boardBefore=await read(page);await page.getByRole('combobox',{name:'Batch board operation',exact:true}).selectOption('both');const colour=page.getByRole('combobox',{name:'Layout board colour',exact:true}),current=await colour.inputValue(),alternate=await colour.locator('option').evaluateAll((options,current)=>(options as HTMLOptionElement[]).find(o=>o.value&&o.value!==current&&o.value.split(':')[0]===current.split(':')[0])?.value,current);expect(alternate).toBeTruthy();await colour.selectOption(alternate!);await page.getByRole('spinbutton',{name:'Board direction',exact:true}).fill('33');await page.getByRole('button',{name:'Review selected board changes',exact:true}).click();await expect(page.locator('.dd-board-batch')).toContainText('Outstanding quotes:');expect((await read(page)).design).toEqual(boardBefore.design);mark('Two original physical boards have a priced direction and alternate-product-colour preview');
  await page.getByRole('button',{name:'Apply layout',exact:true}).click();await expect.poll(async()=>(await read(page)).design.boardLayout?.pieces.length).toBe(2);const applied=await read(page);expect(applied.design.boardLayout?.pieces.every(p=>p.angleDeg===33&&p.colour===alternate)).toBe(true);expect(applied.quotes.join(' ')).toContain('support');mark('Both boards rotate and recolour physically in one saved patch with construction quote retained');
  await undo(page);await expect.poll(async()=>(await read(page)).design.boardLayout?.pieces.length??0).toBe(0);mark('One Undo restores both board geometries');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);mark('No horizontal overflow at the measured viewport');await page.screenshot({path:resolve(proof,`${v.name}-selection.png`),fullPage:true});writeFileSync(resolve(proof,`${v.name}-proof.json`),JSON.stringify({viewport:v,checkpoints},null,2));
 });
});

test('real 3D mesh picking mirrors plan and distinguishes click, orbit, cancel and pinch',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('tab',{name:'3D',exact:false}).click();await page.getByRole('button',{name:'Above',exact:true}).click();await page.getByRole('button',{name:'Select objects in 3D',exact:true}).click();const canvas=page.getByRole('region',{name:'Interactive deck construction model',exact:true}).locator('canvas');await expect(canvas).toBeVisible();await page.waitForTimeout(1200);
 const before=await read(page),model=buildDeckTakeoff({...fixture,...before.design}),bounds=sceneBounds(model),rect=(await canvas.boundingBox())!,w=(bounds.maxX-bounds.minX)/12,d=(bounds.maxZ-bounds.minZ)/12,cx=(bounds.maxX+bounds.minX)/24,cz=(bounds.maxZ+bounds.minZ)/24,r=Math.max(w,d),h=bounds.top/12;
 // Above is the orthographic top camera (Deck3DViewer CameraView, view "top"). A perspective stand-in
 // still hits a board near the middle and misses a tall screen at the edge.
 const above=(aspect:number)=>{const cam=new THREE.OrthographicCamera(-1,1,1,-1,.25,2400),half=Math.max(w,d)*.55/Math.max(.5,cameraSetback(aspect)*.85);cam.position.set(cx,Math.max(r*2,h+8),cz);cam.left=-half*aspect;cam.right=half*aspect;cam.top=half;cam.bottom=-half;cam.lookAt(cx,h*.5,cz);cam.updateProjectionMatrix();cam.updateMatrixWorld();return cam;};
 const board=before.boards.filter(b=>b.modelLevel===0&&b.lengthIn>36&&b.cy>80&&b.cy<190)[4];expect(board).toBeTruthy();const camera=above(rect.width/rect.height);const p=new THREE.Vector3((board.cx+board.offset.x)/12,(model.levels[0].top-.5)/12,(board.cy+board.offset.y)/12).project(camera),point={x:rect.x+(p.x+1)*rect.width/2,y:rect.y+(1-p.y)*rect.height/2};
 await page.mouse.click(point.x,point.y);await expect(page.locator('.dd-3d-selection-card')).toBeVisible();await expect(page.getByRole('combobox',{name:'Select deck board',exact:true})).toHaveValue(String(board.index));expect((await read(page)).design).toEqual(before.design);await page.screenshot({path:resolve(proof,'desktop-real-3d-selection.png'),fullPage:true});
 // Opening the real editor card can resize the canvas. Reproject the same actual mesh
 // using its current renderer aspect and measured canvas rect, rather than a stale click map.
 await page.getByRole('button',{name:'Add to selection',exact:true}).click();
 const screenRect=(await canvas.boundingBox())!,screenCamera=above(screenRect.width/screenRect.height);
 const actualScreen=projection.screen,sp=new THREE.Vector3(actualScreen.x/12,actualScreen.y/12,actualScreen.z/12).project(screenCamera),screenPoint={x:screenRect.x+(sp.x+1)*screenRect.width/2,y:screenRect.y+(1-sp.y)*screenRect.height/2};
 await page.mouse.click(screenPoint.x,screenPoint.y);await expect(page.getByRole('alert')).toContainText('Mixed part and board selection');expect(await page.getByRole('button',{name:'Apply layout',exact:true}).count()).toBe(0);expect(await page.getByRole('button',{name:'Apply part changes',exact:true}).count()).toBe(0);expect((await read(page)).design).toEqual(before.design);await page.screenshot({path:resolve(proof,'desktop-mixed-selection.png'),fullPage:true});await page.getByRole('button',{name:'Edit selected boards only',exact:true}).click();await expect(page.getByRole('combobox',{name:'Select deck board',exact:true})).toHaveValue(String(board.index));
 await page.getByRole('button',{name:'Show selection on plan',exact:true}).click();await expect(page.locator(`[data-board-index="${board.index}"][data-selected]`)).toBeVisible();
 await page.getByRole('tab',{name:'3D',exact:false}).click();await page.getByRole('button',{name:'Above',exact:true}).click();await page.getByRole('button',{name:'Clear selection',exact:true}).click();await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+45,point.y+25,{steps:6});await page.mouse.up();await expect(page.locator('.dd-3d-selection-card')).toContainText('0 selected');expect(await page.getByRole('combobox',{name:'Select plan part',exact:true}).inputValue()).toBe('');expect((await read(page)).design).toEqual(before.design);
 const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:point.x,y:point.y,id:90}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});expect(await page.getByRole('combobox',{name:'Select plan part',exact:true}).inputValue()).toBe('');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:point.x,y:point.y,id:91},{x:point.x+20,y:point.y,id:92}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x-8,y:point.y,id:91},{x:point.x+28,y:point.y,id:92}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();expect(await page.getByRole('combobox',{name:'Select plan part',exact:true}).inputValue()).toBe('');expect((await read(page)).design).toEqual(before.design);expect(errors).toEqual([]);
 writeFileSync(resolve(proof,'real-3d-proof.json'),JSON.stringify({board:{modelLevel:board.modelLevel,index:board.index},point,screenPoint,checkpoints:['Actual rendered board click resolves exact inventory index','Selected object remains editable while viewing 3D','Actual rendered screen additive click creates a mixed selection','Mixed selection offers no Apply until explicit group choice','Plan highlights same board','Orbit drag makes no selection or write','Cancelled pointer makes no selection','Two-pointer gesture makes no selection','Selection makes no design/price/history write']},null,2));
});
