import {test,expect,type Page,type Locator} from '@playwright/test';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {GROUP_MS} from '../src/features/deckcraft/designer/designHistory';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
import type {HardscapeProduct} from '../src/features/deckcraft/hardscapeCatalogue';
const catalogue=JSON.parse(readFileSync(resolve(process.cwd(),'public/deckcraft/hardscape-catalogue.json'),'utf8')) as {products:HardscapeProduct[]};
const hardscapeProduct=(id:string)=>catalogue.products.find(p=>p.id===id);
const proof=resolve(process.cwd(),'../../outputs/deckcraft-yard-shape-review');mkdirSync(proof,{recursive:true});
const patio:YardFeature={id:'qa-patio',kind:'patio',name:'QA patio',enabled:true,xFt:6,zFt:26,widthFt:12,depthFt:10,heightIn:0,rotationDeg:0,productId:'permacon-melville',color:'#aaa69b',outline:[{x:-72,y:-60},{x:72,y:-60},{x:72,y:60},{x:-72,y:60}]};
const wall:YardFeature={...patio,id:'qa-wall',kind:'retaining-wall',name:'QA wall',xFt:22,zFt:36,widthFt:16,depthFt:1,heightIn:24,productId:'segmental-concrete',outline:undefined,wallPath:[{x:-72,y:-24},{x:72,y:-24},{x:72,y:24}]};
const fixture:DeckData={...DEFAULT_DECK,houseVisible:false,deckType:'Freestanding',stairFlights:0,railingType:'None',yardFeatures:[patio,wall]};
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const picker=(page:Page)=>page.getByRole('region',{name:'Ontario supplier library',exact:true});
async function ready(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);return state(page);}
async function activate(control:Locator,touch=false){await control.scrollIntoViewIfNeeded();if(touch){const b=(await control.boundingBox())!;expect(b.width).toBeGreaterThanOrEqual(44);expect(b.height).toBeGreaterThanOrEqual(44);await control.tap();}else await control.click();}
async function open(page:Page,touch=false){await activate(page.getByRole('button',{name:'Backyard',exact:true}),touch);await expect(picker(page).getByLabel('Hardscape supplier',{exact:true})).toBeVisible();}
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page,context})=>{const found:string[]=[];errors.set(page,found);page.on('pageerror',e=>found.push(e.message));await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{const key='golden-maple.deck-studio.deck-only.v1';if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},fixture);await context.route('**/*',route=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(route.request().url())&&['GET','HEAD'].includes(route.request().method())?route.continue():route.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await ready(page);});
test.afterEach(async({page})=>expect(errors.get(page)??[]).toEqual([]));

for(const touch of [false,true])test(`${touch?'@phone ':''}supplier brands finishes colours stock units and patterns persist and Undo exact product selection`,async({page})=>{
 await open(page,touch);const initial=await state(page);
 for(const [brand,id] of [['Techo-Bloc','techo-aberdeen-slab'],['Unilock','unilock-arcana'],['Permacon','permacon-cassara-large-rectangle-slab'],['Oaks','oaks-bonaire']]){
  await picker(page).getByLabel('Hardscape supplier',{exact:true}).selectOption(brand);await picker(page).getByLabel('Supplier hardscape product',{exact:true}).selectOption(id);await expect.poll(async()=>(await state(page)).design.yardFeatures![0].productId).toBe(id);await ready(page);const p=hardscapeProduct(id)!;expect(p.brand).toBe(brand);const finish=picker(page).getByLabel('Hardscape finish',{exact:true});expect(await finish.inputValue()).toBe(p.finishes[0].id);const photo=picker(page).getByRole('group',{name:'Supplier stone colours',exact:true}).locator('img[src^="/deckcraft/"]').first();await photo.scrollIntoViewIfNeeded();await expect.poll(()=>photo.evaluate(el=>(el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);if(p.finishes.length>1){await finish.selectOption(p.finishes.at(-1)!.id);await expect.poll(async()=>(await state(page)).design.yardFeatures![0].hardscape!.finishId).toBe(p.finishes.at(-1)!.id);await finish.selectOption(p.finishes[0].id);await expect.poll(async()=>(await state(page)).design.yardFeatures![0].hardscape!.finishId).toBe(p.finishes[0].id);}const colors=picker(page).getByRole('group',{name:'Supplier stone colours',exact:true}).getByRole('button').filter({has:page.locator('span')});const buttons=await colors.count();expect(buttons).toBeGreaterThan(0);const chosen=colors.nth(Math.min(1,buttons-1));await activate(chosen,touch);await expect(chosen).toHaveAttribute('aria-pressed','true');if(id==='oaks-bonaire')await expect(chosen).toContainText('Photo pending');const colored=await ready(page),selection=colored.design.yardFeatures![0].hardscape!;expect(p.finishes.find(f=>f.id===selection.finishId)!.colors.some(c=>c.id===selection.colorId)).toBe(true);
  const units=picker(page).getByLabel('Hardscape unit size',{exact:true}),options=units.locator('option');const count=await options.count(),unitId=await options.nth(Math.min(1,count-1)).getAttribute('value');await units.selectOption(unitId!);await expect.poll(async()=>(await state(page)).design.yardFeatures![0].hardscape!.unitId).toBe(unitId);const unit=hardscapeProduct(id)!.finishes.find(f=>f.id===selection.finishId)!.units.find(u=>u.id===unitId)!;await expect(units.locator('option:checked')).toContainText(`${unit.widthMm} × ${unit.lengthMm} × ${unit.heightMm} mm`);
  const patterns=picker(page).getByLabel('Hardscape laying pattern',{exact:true}),recipes=patterns.locator('optgroup option:not(:disabled)');if(await recipes.count()){const recipeId=(await recipes.first().getAttribute('value'))!;await patterns.selectOption(recipeId);await expect.poll(async()=>(await state(page)).design.yardFeatures![0].hardscape!.patternId).toBe(recipeId);const recipe=p.finishes.find(f=>f.id===selection.finishId)!.patterns.find(p=>p.id===recipeId)!.layout;expect((await state(page)).design.yardFeatures![0].hardscape!.unitId).toBe(recipe.cells[0].unitId);await expect(picker(page).getByLabel('Hardscape joint width',{exact:true})).toBeDisabled();expect(await picker(page).getByLabel('Hardscape joint width',{exact:true}).inputValue()).toBe(String(recipe.jointMm??0));}await patterns.selectOption('herringbone');await picker(page).getByLabel('Hardscape laying direction',{exact:true}).fill('45');await picker(page).getByLabel('Hardscape joint width',{exact:true}).fill('4');await ready(page);const edited=(await state(page)).design.yardFeatures![0];expect(edited.hardscape).toMatchObject({patternId:'herringbone',angleDeg:45,jointMm:4});expect(edited.outline).toEqual(initial.design.yardFeatures![0].outline);expect(edited.rotationDeg).toBe(initial.design.yardFeatures![0].rotationDeg);expect((await state(page)).quotes.some(q=>/supply|installation/i.test(q))).toBe(true);
 }
 await page.waitForTimeout(GROUP_MS+75);const beforeAngle=await state(page);await picker(page).getByLabel('Hardscape laying direction',{exact:true}).fill('75');await expect.poll(async()=>(await state(page)).design.yardFeatures![0].hardscape!.angleDeg).toBe(75);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await state(page)).design).toEqual(beforeAngle.design);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect.poll(async()=>(await state(page)).design.yardFeatures![0].hardscape!.angleDeg).toBe(75);const saved=await ready(page);await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.deck-only.v1')??'{}').configuration?.yardFeatures?.[0]?.hardscape?.angleDeg)).toBe(75);await page.reload();await ready(page);expect((await state(page)).design.yardFeatures![0]).toEqual(saved.design.yardFeatures![0]);await open(page,touch);await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-supplier-library.png`),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

for(const touch of [false,true])test(`${touch?'@phone ':''}wall stock thickness and matching cap survive pulls and sketch without changing supplier identity`,async({page})=>{
 await open(page,touch);await page.getByLabel('Selected yard feature',{exact:true}).selectOption('qa-wall');await picker(page).getByLabel('Hardscape supplier',{exact:true}).selectOption('Permacon');await picker(page).getByLabel('Supplier hardscape product',{exact:true}).selectOption('permacon-grande-wall');await expect.poll(async()=>(await state(page)).design.yardFeatures![1].productId).toBe('permacon-grande-wall');await picker(page).getByLabel('Hardscape wall cap',{exact:true}).selectOption('cap');await expect(picker(page).getByLabel('Hardscape wall cap',{exact:true}).locator('option:checked')).toContainText('1000 × 438 × 200 mm');const selected=await ready(page);expect(selected.design.yardFeatures![1].hardscape?.capUnitId).toBe('cap');expect(selected.design.yardFeatures![1].depthFt).toBeCloseTo(375/304.8,6);
 const showCanvas=page.getByRole('button',{name:'Show canvas',exact:true});if(await showCanvas.isVisible())await activate(showCanvas,touch);await activate(page.getByRole('radio',{name:'Patios & walls',exact:true}),touch);const controls=page.getByLabel('Patio and wall shape controls',{exact:true});await controls.getByLabel('Selected patio or wall',{exact:true}).selectOption('qa-wall');await controls.locator('summary').filter({hasText:'Overall dimensions'}).click();await expect(controls.getByLabel('Wall shape thickness',{exact:true})).toBeDisabled();const point=page.getByRole('button',{name:'QA wall point 3',exact:true});await point.focus();await point.press('ArrowRight');const pulled=await ready(page);expect(pulled.design.yardFeatures![1].hardscape).toEqual(selected.design.yardFeatures![1].hardscape);expect(pulled.design.yardFeatures![1].depthFt).toBe(selected.design.yardFeatures![1].depthFt);
 await activate(page.getByRole('button',{name:'Sketch a design',exact:true}),touch);const modal=page.getByRole('dialog',{name:'Sketch a design',exact:true});await activate(modal.getByRole('button').filter({hasText:'QA wall'}).filter({has:page.locator('.dd-sketch-shape-number')}),touch);await expect(modal.getByRole('spinbutton',{name:/^Wall thickness/})).toBeDisabled();await activate(modal.getByRole('button',{name:'Edit on plan',exact:true}),touch);await expect(modal).toBeHidden();expect((await state(page)).design).toEqual(pulled.design);await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-supplier-wall-cap.png`),fullPage:true});
});


test('cached supplier stone and exact wall cap render in the 3D overview',async({page})=>{
 const loaded=new Set<string>();page.on('response',r=>{if(r.ok())loaded.add(new URL(r.url()).pathname);});
 await open(page);await picker(page).getByLabel('Hardscape supplier',{exact:true}).selectOption('Unilock');await picker(page).getByLabel('Supplier hardscape product',{exact:true}).selectOption('unilock-arcana');
 await picker(page).getByLabel('Hardscape laying pattern',{exact:true}).selectOption('lp-arcana-12x24-rb-i');
 const colour=hardscapeProduct('unilock-arcana')!.finishes[0].colors[0] as {id:string;localImageUrl?:string};expect(colour.localImageUrl).toBeTruthy();
 await page.getByLabel('Selected yard feature',{exact:true}).selectOption('qa-wall');await picker(page).getByLabel('Hardscape supplier',{exact:true}).selectOption('Permacon');await picker(page).getByLabel('Supplier hardscape product',{exact:true}).selectOption('permacon-grande-wall');await picker(page).getByLabel('Hardscape wall cap',{exact:true}).selectOption('cap');const selected=await ready(page);writeFileSync(resolve(proof,'supplier-3d-fixture.json'),JSON.stringify(selected.design,null,2));const plan=selected.yardBoundaries.find(f=>f.id==='qa-patio')!.points;expect(Math.abs(plan.reduce((sum,p,i)=>{const q=plan[(i+1)%plan.length];return sum+p.x*q.y-q.x*p.y;},0))/288).toBe(120);expect(selected.design.yardFeatures![1]).toMatchObject({xFt:22,zFt:36});
 await expect.poll(()=>loaded.has(colour.localImageUrl!)).toBe(true);
 const showCanvas=page.getByRole('button',{name:'Show canvas',exact:true});if(await showCanvas.isVisible())await showCanvas.click();await page.getByRole('tab',{name:'3D',exact:true}).click();await page.getByRole('group',{name:'Camera',exact:true}).getByRole('button',{name:'Overview',exact:true}).click();
 const region=page.getByRole('region',{name:'Interactive deck construction model',exact:true}),canvas=region.locator('canvas');await expect(canvas).toBeVisible();await expect.poll(()=>canvas.evaluate(el=>(el as HTMLCanvasElement).width)).toBeGreaterThan(0);await expect.poll(()=>canvas.evaluate(el=>(el as HTMLCanvasElement).height)).toBeGreaterThan(0);await expect(page.getByText('Showing the plan view because 3D graphics are unavailable on this device.',{exact:false})).toBeHidden();
 await page.waitForLoadState('networkidle');await page.waitForTimeout(1500);await region.screenshot({path:resolve(proof,'desktop-supplier-3d-overview.png')});expect((await state(page)).design.yardFeatures).toEqual(selected.design.yardFeatures);
 await page.getByRole('tab',{name:'Plan',exact:true}).click();await page.getByRole('radio',{name:'Patios & walls',exact:true}).click();await page.getByLabel('Patio and wall shape controls',{exact:true}).getByLabel('Selected patio or wall',{exact:true}).selectOption('qa-patio');await page.getByRole('radio',{name:'Select parts',exact:true}).click();await page.getByLabel('Deck drawing canvas',{exact:true}).screenshot({path:resolve(proof,'desktop-source-pattern-plan.png')});await open(page);await page.getByLabel('Selected yard feature',{exact:true}).selectOption('qa-patio');await picker(page).getByLabel('Hardscape laying pattern',{exact:true}).selectOption('running-bond');await ready(page);await page.getByRole('tab',{name:'3D',exact:true}).click();await page.getByRole('group',{name:'Camera',exact:true}).getByRole('button',{name:'Overview',exact:true}).click();await expect(region.locator('canvas')).toBeVisible();await page.waitForLoadState('networkidle');await page.waitForTimeout(1500);await region.screenshot({path:resolve(proof,'desktop-supplier-3d-generic-pattern.png')});await page.getByRole('group',{name:'Camera',exact:true}).getByRole('button',{name:'Above',exact:true}).click();await canvas.hover();await page.mouse.wheel(0,600);await page.waitForTimeout(1000);await region.screenshot({path:resolve(proof,'desktop-supplier-3d-above.png')});
});
