import {test,expect,type Page} from '@playwright/test';
import {pickPlanTool,showProjectControls} from './nav';
import {mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
const out=resolve(process.cwd(),'../../outputs/deckcraft-contractor-ready-review/assistant');mkdirSync(out,{recursive:true});
const read=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const panel=(page:Page)=>page.getByRole('region',{name:'Design assistant',exact:true});
const input=(page:Page)=>panel(page).getByRole('textbox',{name:'What would you like to change?',exact:true});
test.beforeEach(async({context,page})=>{
 await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(()=>localStorage.clear());
 await context.route('**/*',r=>{const request=r.request();if(!/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(request.url()))return r.fulfill({status:200,body:''});if(request.url().includes('/.netlify/functions/deck-assistant'))return r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'AI is unavailable in this controlled UI test.'}})});return ['GET','HEAD'].includes(request.method())?r.continue():r.fulfill({status:403,body:'Blocked test write'});});
 await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);
});
async function ask(page:Page){await showProjectControls(page);await page.getByRole('button',{name:'Describe a change',exact:true}).click();await expect(panel(page)).toBeVisible();expect(await page.locator('dialog[open]').count()).toBe(0);}
async function physicalBoard(page:Page,index:number,touch:boolean){const hit=page.locator(`.dd-board-hit[data-board-index="${index}"]`).first();const p=await hit.evaluate(async el=>{el.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));const poly=el as SVGPolygonElement,points=Array.from({length:poly.points.numberOfItems},(_,i)=>poly.points.getItem(i)),point=new DOMPoint(points.reduce((n,p)=>n+p.x,0)/points.length,points.reduce((n,p)=>n+p.y,0)/points.length).matrixTransform(poly.getScreenCTM()!);const actual=document.elementFromPoint(point.x,point.y)?.closest('.dd-board-hit');return {x:point.x,y:point.y,index:actual?.getAttribute('data-board-index')};});expect(p.index).toBe(String(index));if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
for(const viewport of [{width:1440,height:1000,touch:false},{width:768,height:1024,touch:true},{width:390,height:844,touch:true}])test.describe(`assistant dock ${viewport.width}`,()=>{
 test.use({viewport:{width:viewport.width,height:viewport.height},hasTouch:viewport.touch,isMobile:viewport.width===390});
 test(`${viewport.width===390?'@phone ':''}drawing remains selectable beside conversation, physical board targets preview, panel Undo/Redo and collapse retain draft`,async({page})=>{
  await pickPlanTool(page,'Board layout');await ask(page);await input(page).fill('Rotate selected boards to 33 degrees');const before=await read(page),board=before.boards.find(b=>b.modelLevel===0&&b.role==='field'&&b.lengthIn>100&&b.cy>40&&b.cy<100)!;expect(board).toBeTruthy();await physicalBoard(page,board.index,viewport.touch);await expect(panel(page).locator('.dd-instruction-selection')).toContainText('1 board');await expect(input(page)).toHaveValue('Rotate selected boards to 33 degrees');expect((await read(page)).design).toEqual(before.design);await page.getByRole('group',{name:'Board layout selection canvas',exact:true}).press('Escape');await expect(panel(page)).toBeVisible();await expect(input(page)).toHaveValue('Rotate selected boards to 33 degrees');await physicalBoard(page,board.index,viewport.touch);await expect(panel(page).locator('.dd-instruction-selection')).toContainText('1 board');
  const d=panel(page),preview=d.getByRole('button',{name:'Preview edit',exact:true});if(viewport.touch)await preview.tap();else await preview.click();await expect(d.getByRole('region',{name:'Instruction preview'})).toBeVisible();await expect(page.getByRole('img',{name:'Reviewed edit targets',exact:true})).toBeVisible();await expect(page.locator(`[data-assistant-target="board:0:${board.index}"]`)).toBeVisible();expect((await read(page)).design).toEqual(before.design);
  const apply=d.getByRole('button',{name:'Apply reviewed edit',exact:true});if(viewport.touch)await apply.tap();else await apply.click();await expect.poll(async()=>(await read(page)).design.boardLayout?.pieces.length).toBe(1);const applied=await read(page);expect(applied.design.boardLayout!.pieces[0].angleDeg).toBe(33);await expect(page.getByRole('img',{name:'Reviewed edit targets',exact:true})).toHaveCount(0);
  const undo=d.getByRole('button',{name:'Undo design edit',exact:true});if(viewport.touch)await undo.tap();else await undo.click();await expect.poll(async()=>JSON.stringify((await read(page)).design)).toBe(JSON.stringify(before.design));expect((await read(page)).pricing.total).toBe(before.pricing.total);await expect(input(page)).toHaveValue('Rotate selected boards to 33 degrees');const redo=d.getByRole('button',{name:'Redo design edit',exact:true});if(viewport.touch)await redo.tap();else await redo.press('Enter');await expect.poll(async()=>JSON.stringify((await read(page)).design)).toBe(JSON.stringify(applied.design));
  await d.locator('.dd-assistant-history summary').click();await expect(d.getByRole('list',{name:'Assistant activity'}).locator(':scope>li')).toHaveCount(3);await expect(d.getByRole('list',{name:'Assistant activity'})).toContainText('Undid the last design edit');
  const collapse=d.getByRole('button',{name:'Collapse assistant',exact:true});if(viewport.touch)await collapse.tap();else await collapse.click();await expect(d.locator('#dd-assistant-body')).toBeHidden();await pickPlanTool(page,'Shape & points');const expand=d.getByRole('button',{name:'Expand assistant',exact:true});if(viewport.touch)await expand.tap();else await expand.click();await expect(input(page)).toHaveValue('Rotate selected boards to 33 degrees');await expect(d.getByRole('list',{name:'Assistant activity'}).locator(':scope>li')).toHaveCount(3);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);const heights=await d.getByRole('button').evaluateAll(buttons=>buttons.filter(b=>b.getBoundingClientRect().height>0).map(b=>b.getBoundingClientRect().height));expect(heights.every(h=>h>=43.99)).toBe(true);if(viewport.touch){await d.evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}));await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}await page.screenshot({path:resolve(out,`dock-board-${viewport.width}.png`)});const last=await read(page);const close=d.getByRole('button',{name:'Close instruction assistant',exact:true});if(viewport.touch)await close.tap();else await close.click();await expect(panel(page)).toHaveCount(0);expect((await read(page)).design).toEqual(last.design);
 });
});
test('reviewed whole-deck targets clear on actual drawing edit, draft survives and dock Undo restores the manual edit',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await ask(page);await input(page).fill('Make the deck 20 by 14 feet');await panel(page).getByRole('button',{name:'Preview edit',exact:true}).click();await expect(page.locator('[data-assistant-target="deck:1"]')).toBeVisible();const before=await read(page);await page.getByRole('radio',{name:'Shape & points',exact:true}).click();await page.getByRole('switch',{name:/^Free movement/}).check();const point=page.getByRole('button',{name:'Main deck point 3',exact:true});await point.scrollIntoViewIfNeeded();const box=(await point.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+15,box.y+box.height/2-12,{steps:6});await page.mouse.up();await expect.poll(async()=>JSON.stringify((await read(page)).boundaries)).not.toBe(JSON.stringify(before.boundaries));await expect(panel(page).getByRole('region',{name:'Instruction preview'})).toHaveCount(0);await expect(page.getByRole('img',{name:'Reviewed edit targets',exact:true})).toHaveCount(0);await expect(input(page)).toHaveValue('Make the deck 20 by 14 feet');await expect(panel(page).getByRole('button',{name:'Apply reviewed edit',exact:true})).toHaveCount(0);await panel(page).getByRole('button',{name:'Undo design edit',exact:true}).click();await expect.poll(async()=>JSON.stringify((await read(page)).design)).toBe(JSON.stringify(before.design));expect((await read(page)).pricing.total).toBe(before.pricing.total);await expect(input(page)).toHaveValue('Make the deck 20 by 14 feet');await page.screenshot({path:resolve(out,'dock-manual-drawing-undo.png')});
});
