import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {savedConfiguration} from './nav';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {AgentSnapshot,AgentRequest} from '../src/features/deckcraft/designer/deckAgentController';
const proof=resolve('../../outputs/deckcraft-edge-sections-review');mkdirSync(proof,{recursive:true});
const fixture={...DEFAULT_DECK,width:20,length:12,height:48,deckingMaterial:'tt_prime_plus',railingType:'None',stairFlights:1,stairPosition:'Front',privacySqft:0,autoLighting:{posts:true},customerName:'Local screen review',projectAddress:'Local review address'};
const read=(page:Page)=>page.evaluate(()=>window.deckcraft!.read());
const controls=(page:Page)=>page.getByRole('region',{name:'Railing and privacy screen controls',exact:true});
async function open(page:Page){await page.getByRole('radio',{name:'Rails & screens',exact:true}).click();await expect(page.locator('.dd-edge-section-editor svg')).toBeVisible();}
async function choose(page:Page,level=1){const state=await read(page),edge=state.edgeSections.find(e=>e.level===level&&e.label.includes('Left')&&e.eligible.some(r=>r.startPct<=25&&r.endPct>=75))??state.edgeSections.find(e=>e.level===level&&e.eligible.some(r=>r.endPct-r.startPct>=50));expect(edge).toBeTruthy();if(!edge)throw Error('No supported exposed edge');await controls(page).getByLabel('Railing and screen level',{exact:true}).selectOption(String(level));await controls(page).getByLabel('Select deck edge',{exact:true}).selectOption(edge.id);return edge;}
async function range(page:Page,start:number,end:number){await controls(page).getByRole('spinbutton',{name:'Section start (ft)',exact:true}).fill(String(start));await controls(page).getByRole('spinbutton',{name:'Section end (ft)',exact:true}).fill(String(end));}
async function undo(page:Page){await page.getByRole('region',{name:'Save and restore design',exact:true}).getByRole('button',{name:'Undo',exact:true}).click();}
async function redo(page:Page){await page.getByRole('region',{name:'Save and restore design',exact:true}).getByRole('button',{name:'Redo',exact:true}).click();}
async function execute(page:Page,request:AgentRequest){const result=await page.evaluate(request=>window.deckcraft!.execute(request),request);expect(result.ok).toBe(true);if('error'in result)throw Error(result.error.message);return result;}
async function svgPoint(page:Page,p:{x:number;y:number}){const svg=page.locator('.dd-edge-section-editor svg');await svg.evaluate(el=>el.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'}));return svg.evaluate((el,p)=>{const pt=new DOMPoint(p.x,p.y).matrixTransform((el as SVGSVGElement).getScreenCTM()!);return {x:pt.x,y:pt.y};},p);}
async function dragRange(page:Page,context:BrowserContext,edge:AgentSnapshot['edgeSections'][number],startPct:number,endPct:number,touch:boolean){const along=(pct:number)=>({x:edge.a.x+(edge.b.x-edge.a.x)*pct/100,y:edge.a.y+(edge.b.y-edge.a.y)*pct/100}),a=await svgPoint(page,along(startPct)),b=await svgPoint(page,along(endPct));for(const p of [a,b])expect(await page.evaluate(p=>!!document.elementFromPoint(p.x,p.y)?.closest('[data-edge-section-id]'),p)).toBe(true);if(touch){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...b,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:5});await page.mouse.up();}}
async function cancelNativeRange(page:Page,context:BrowserContext,edge:AgentSnapshot['edgeSections'][number]){const at=(pct:number)=>({x:edge.a.x+(edge.b.x-edge.a.x)*pct/100,y:edge.a.y+(edge.b.y-edge.a.y)*pct/100}),a=await svgPoint(page,at(20)),b=await svgPoint(page,at(60)),second={x:b.x+24,y:b.y+12},before=await read(page),saved=JSON.stringify(await savedConfiguration(page));const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...b,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...b,id:1},{...second,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();expect((await read(page)).revision).toBe(before.revision);expect((await read(page)).design).toEqual(before.design);expect(JSON.stringify(await savedConfiguration(page))).toBe(saved);await expect(controls(page).getByRole('spinbutton',{name:'Section start (ft)',exact:true})).toHaveValue('0');expect(Number(await controls(page).getByRole('spinbutton',{name:'Section end (ft)',exact:true}).inputValue())).toBeCloseTo(edge.lengthIn/12,4);}
async function screenMarkerSize(page:Page){const marker=page.locator('.dd-edge-section-screen-marker circle').first();await marker.evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}));const fit=page.getByRole('button',{name:'Fit drawing',exact:true});await fit.click();await expect(page.getByLabel('Drawing zoom',{exact:true})).toHaveText('100%');let rect=(await marker.boundingBox())!;expect(rect.width).toBeGreaterThanOrEqual(43.99);expect(rect.height).toBeGreaterThanOrEqual(43.99);await page.getByRole('button',{name:'Zoom in',exact:true}).click();await expect(page.getByLabel('Drawing zoom',{exact:true})).toHaveText('125%');rect=(await marker.boundingBox())!;expect(rect.width).toBeGreaterThanOrEqual(43.99);expect(rect.height).toBeGreaterThanOrEqual(43.99);await fit.click();return rect;}
test.beforeEach(async({page,context})=>{await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{if(!localStorage.getItem('golden-maple.deck-studio.deck-only.v1'))localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},fixture);await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)&&['GET','HEAD'].includes(route.request().method())?route.continue():route.fulfill({body:''}));await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>window.deckcraft?.read().ready)).toBe(true);await open(page);});

test('selected partial edge adds only its own railing from None, then screen toggles and exact Undo/save/share remain coherent',async({page,context})=>{
 await page.setViewportSize({width:1440,height:1000});const initial=await read(page),edge=await choose(page);await range(page,edge.lengthIn*.25/12,edge.lengthIn*.75/12);expect((await read(page)).design).toEqual(initial.design);
 await controls(page).getByRole('button',{name:'Add railing here',exact:true}).click();await expect.poll(async()=>(await read(page)).quantities.railingLf).toBeCloseTo(edge.lengthIn*.5/12,5);const railing=await read(page);expect(railing.design.railDefault).toBe(false);expect(railing.design.railingType).toBe('Aluminum');expect(railing.quantities.stairRailingLf).toBe(0);expect(railing.design.lightingSystem.selectedItems.find(i=>i.auto&&i.zone==='posts')?.qty).toBe(railing.quantities.railingPosts);expect(railing.edgeSections.filter(e=>e.railings.length)).toHaveLength(1);await undo(page);expect((await read(page)).design).toEqual(initial.design);await redo(page);expect((await read(page)).design).toEqual(railing.design);await expect(controls(page).getByRole('spinbutton',{name:'Section start (ft)',exact:true})).toHaveValue('0');expect(Number(await controls(page).getByRole('spinbutton',{name:'Section end (ft)',exact:true}).inputValue())).toBeCloseTo(edge.lengthIn/12,6);await choose(page);await range(page,edge.lengthIn*.25/12,edge.lengthIn*.75/12);expect((await read(page)).design).toEqual(railing.design);
 await controls(page).getByRole('button',{name:'Add privacy screen here',exact:true}).click();await expect.poll(async()=>(await read(page)).design.privacyScreens?.length).toBe(1);const unlit=await read(page);await execute(page,{id:'edge-screen-lights',commands:[{type:'design.patch',patch:{privacyScreens:unlit.design.privacyScreens!.map(s=>({...s,lights:true}))}}]});const screenState=await read(page),screen=screenState.design.privacyScreens![0];expect(screenState.design.lightingSystem.selectedItems.some(i=>i.auto&&i.zone==='privacy'&&i.qty>0)).toBe(true);expect(screen.edgeId).toBe(edge.edgeId);expect(screen.lengthFt).toBeCloseTo(edge.lengthIn*.5/12,6);expect(screenState.design.privacySqft).toBeCloseTo(screen.lengthFt*6,6);expect(screenState.pricing.total).toBeGreaterThan(railing.pricing.total);await expect.poll(async()=>(await savedConfiguration(page))?.customerName).toBe(fixture.customerName);expect((await savedConfiguration(page))?.projectAddress).toBe(fixture.projectAddress);
 await controls(page).getByRole('switch',{name:'Privacy screen 1 on',exact:true}).uncheck();await expect.poll(async()=>(await read(page)).design.privacySqft).toBe(0);expect((await read(page)).pricing.total).toBe(railing.pricing.total);expect((await read(page)).design.lightingSystem.selectedItems.some(i=>i.auto&&i.zone==='privacy')).toBe(false);await undo(page);expect((await read(page)).design).toEqual(screenState.design);expect((await read(page)).pricing.total).toBe(screenState.pricing.total);await redo(page);await expect.poll(async()=>(await read(page)).design.privacySqft).toBe(0);await controls(page).getByRole('switch',{name:'Privacy screen 1 on',exact:true}).check();await expect.poll(async()=>(await read(page)).design.privacyScreens?.[0].enabled).toBe(true);expect((await read(page)).design.privacyScreens).toEqual(screenState.design.privacyScreens);
 await expect.poll(async()=>(await savedConfiguration(page))?.privacyScreens?.[0]?.edgeId).toBe(edge.edgeId);await page.reload();await expect.poll(()=>page.evaluate(()=>window.deckcraft?.read().ready)).toBe(true);expect((await read(page)).design).toEqual(screenState.design);expect((await read(page)).pricing.total).toBe(screenState.pricing.total);
 const shared=await execute(page,{id:'edge-share',commands:[{type:'action',action:'share.create'}]});const visitor=await context.newPage();await visitor.goto(shared.result!.url);await expect.poll(()=>visitor.evaluate(()=>window.deckcraft?.read().ready)).toBe(true);expect((await read(visitor)).design).toEqual(screenState.design);expect((await read(visitor)).pricing.total).toBe(screenState.pricing.total);await visitor.close();await open(page);await choose(page);await page.screenshot({path:resolve(proof,'desktop-exact-edge-screen.png'),fullPage:true});writeFileSync(resolve(proof,'desktop-accounting.json'),JSON.stringify({initial:initial.pricing,rail:railing.pricing,screenPricing:screenState.pricing,quantities:screenState.quantities,screen},null,2));
});

test('stair-blocked and overlapping screens fail without writes; agent previews and one-step history share exact edge semantics',async({page})=>{
 const initial=await read(page),front=initial.edgeSections.find(e=>e.label.includes('Front')&&e.eligible.length===2)!;expect(front).toBeTruthy();await controls(page).getByLabel('Select deck edge',{exact:true}).selectOption(front.id);await range(page,0,front.lengthIn/12);await controls(page).getByRole('button',{name:'Add privacy screen here',exact:true}).click();await expect(controls(page).getByRole('status')).toContainText(/clear exposed section/i);expect((await read(page)).design).toEqual(initial.design);
 const edge=await choose(page),command={type:'edge.edit' as const,edit:{action:'screen-add' as const,level:edge.level,edgeId:edge.edgeId,startPct:25,endPct:75,heightFt:5 as const}},preview=await page.evaluate(command=>window.deckcraft!.preview({id:'edge-preview',commands:[command]}),command);expect(preview.ok).toBe(true);expect((await read(page)).design).toEqual(initial.design);await execute(page,{id:'edge-screen',expectedRevision:initial.revision,commands:[command]});const added=await read(page);if(preview.ok){expect(added.design).toEqual(preview.snapshot.design);expect(added.pricing.total).toBe(preview.snapshot.pricing.total);}await undo(page);expect((await read(page)).design).toEqual(initial.design);await redo(page);expect((await read(page)).design).toEqual(added.design);
 await choose(page);await range(page,edge.lengthIn*.5/12,edge.lengthIn*.9/12);await controls(page).getByRole('button',{name:'Add privacy screen here',exact:true}).click();await expect(controls(page).getByRole('status')).toContainText(/overlap/i);expect((await read(page)).design).toEqual(added.design);await controls(page).getByRole('spinbutton',{name:'Section start (ft)',exact:true}).press('Delete');expect((await read(page)).design).toEqual(added.design);
 const id=added.design.privacyScreens![0].id;await execute(page,{id:'edge-screen-select-safe',commands:[{type:'edge.edit',edit:{action:'screen-toggle',id,enabled:false}}]});const disabled=await read(page);expect(disabled.design.privacyScreens![0].heightFt).toBe(5);await execute(page,{id:'edge-screen-restore',commands:[{type:'edge.edit',edit:{action:'screen-toggle',id,enabled:true}}]});expect((await read(page)).design.privacyScreens).toEqual(added.design.privacyScreens);
 const stale=await page.evaluate(({command,revision})=>window.deckcraft!.execute({id:'edge-stale',expectedRevision:revision,commands:[command]}),{command,revision:initial.revision});expect(stale.ok).toBe(false);expect((await read(page)).design.privacyScreens).toEqual(added.design.privacyScreens);await page.getByRole('button',{name:'Select privacy screen 1',exact:true}).click();await page.locator('.dd-edge-section-editor svg').press('Delete');await expect.poll(async()=>(await read(page)).design.privacyScreens?.length).toBe(0);await undo(page);expect((await read(page)).design.privacyScreens).toEqual(added.design.privacyScreens);expect((await read(page)).pricing.total).toBe(added.pricing.total);
});

for(const viewport of [{name:'phone',width:390,height:844},{name:'tablet',width:768,height:1024}])test.describe(`${viewport.name} physical edge controls`,()=>{test.use({viewport:{width:viewport.width,height:viewport.height},hasTouch:true,isMobile:viewport.name==='phone'});test('@phone native edge range and screen controls retain exact edits, accessibility targets, Undo and Delete',async({page,context})=>{
 const initial=await read(page),edge=initial.edgeSections.find(e=>e.label.includes('Left')&&e.eligible.some(r=>r.startPct<=25&&r.endPct>=75))!;await expect(page.locator('[data-autosave-state="saved"]')).toContainText(/saved/i);await cancelNativeRange(page,context,edge);await dragRange(page,context,edge,25,75,true);expect((await read(page)).design).toEqual(initial.design);await expect(controls(page).getByLabel('Select deck edge',{exact:true})).toHaveValue(edge.id);expect(Number(await controls(page).getByRole('spinbutton',{name:'Section start (ft)',exact:true}).inputValue())).toBeCloseTo(edge.lengthIn*.25/12,2);expect(Number(await controls(page).getByRole('spinbutton',{name:'Section end (ft)',exact:true}).inputValue())).toBeCloseTo(edge.lengthIn*.75/12,2);
 await controls(page).getByRole('button',{name:'Add railing here',exact:true}).tap();await expect.poll(async()=>(await read(page)).quantities.railingLf).toBeCloseTo(edge.lengthIn*.5/12,2);const rail=await read(page);expect(rail.quantities.stairRailingLf).toBe(0);await controls(page).getByRole('button',{name:'Add privacy screen here',exact:true}).tap();await expect.poll(async()=>(await read(page)).design.privacyScreens?.length).toBe(1);const added=await read(page),markerRect=await screenMarkerSize(page);await controls(page).getByRole('switch',{name:'Privacy screen 1 on',exact:true}).tap();await expect.poll(async()=>(await read(page)).design.privacySqft).toBe(0);await controls(page).getByRole('switch',{name:'Privacy screen 1 on',exact:true}).tap();await expect.poll(async()=>(await read(page)).design.privacyScreens?.[0].enabled).toBe(true);expect((await read(page)).pricing.total).toBe(added.pricing.total);
 const sizes=await controls(page).getByRole('button').evaluateAll(buttons=>buttons.map(b=>({name:b.textContent,height:b.getBoundingClientRect().height,width:b.getBoundingClientRect().width})));expect(sizes.every(s=>s.height>=44&&s.width>=44)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:resolve(proof,`${viewport.name}-native-edge-controls.png`),fullPage:true});await controls(page).getByRole('button',{name:'Delete privacy screen 1',exact:true}).tap();await expect.poll(async()=>(await read(page)).design.privacyScreens?.length).toBe(0);expect((await read(page)).pricing.total).toBe(rail.pricing.total);await undo(page);expect((await read(page)).design.privacyScreens).toEqual(added.design.privacyScreens);
 writeFileSync(resolve(proof,`${viewport.name}-exact-range.json`),JSON.stringify({viewport,edge,rail:rail.quantities,screen:added.design.privacyScreens,targetSizes:sizes,markerRect},null,2));
});});
