import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckAgentApi,AgentCommand} from '../src/features/deckcraft/designer/deckAgentController';
const proof=resolve(process.cwd(),'../../outputs/deckcraft-easy-edit-review/jobs-commands');mkdirSync(proof,{recursive:true});
const jobs=(page:Page)=>page.getByRole('dialog',{name:'Jobs & options',exact:true}),assistant=(page:Page)=>page.getByRole('region',{name:'Design assistant',exact:true});
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());let sequence=0;
async function command(page:Page,commands:AgentCommand[]){const r=await page.evaluate(async({commands,id})=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;return api.execute({id,expectedRevision:api.read().revision,commands});},{commands,id:`job-qa-${++sequence}`});if('error'in r)throw Error(JSON.stringify(r));return r;}
async function openJobs(page:Page){await page.getByRole('button',{name:'Jobs & versions',exact:true}).click();await expect(jobs(page)).toBeVisible();}
async function openAssistant(page:Page){await page.getByRole('button',{name:'Describe a change',exact:true}).click();await expect(assistant(page)).toBeVisible();}
async function assertComparisonFlow(page:Page,name:'jobs'|'instructions'){
 const dialog=name==='jobs'?jobs(page):assistant(page),cards=dialog.locator('.dd-jobs-comparison article'),delta=dialog.locator('.dd-jobs-delta');const deltaBox=await delta.boundingBox();
 for(let i=0;i<await cards.count();i++){const card=cards.nth(i),cardBox=await card.boundingBox(),planBox=await card.locator('.dd-comparison-plan').boundingBox(),svgBox=await card.locator('svg').boundingBox(),priceBox=await card.locator(':scope > strong').boundingBox();expect(planBox!.height).toBeLessThanOrEqual(241);expect(svgBox!.height).toBeLessThanOrEqual(planBox!.height+.5);expect(priceBox!.y).toBeGreaterThanOrEqual(planBox!.y+planBox!.height);expect(priceBox!.y+priceBox!.height).toBeLessThanOrEqual(cardBox!.y+cardBox!.height);expect(deltaBox!.y).toBeGreaterThanOrEqual(cardBox!.y+cardBox!.height);}
}
test.beforeEach(async({context,page})=>{await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration})),{...DEFAULT_DECK,customerName:'Job private client',projectAddress:'Job private address',scopeOfWork:'Job private scope'});await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&r.request().method()==='GET'?r.continue():r.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);});
for(const phone of [false,true])test.describe(phone?'phone jobs and instructions':'desktop jobs and instructions',()=>{if(phone)test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
test(`${phone?'@phone ':''}saved irregular options compare exact plans and restore in one Undo`,async({page})=>{
 await command(page,[{type:'design.patch',patch:{width:20,length:14,stairFlights:0,deckOutlines:{main:[{x:0,y:0},{x:20,y:0},{x:20,y:8},{x:14,y:8},{x:14,y:14},{x:0,y:14}]}}}]);const original=await state(page);expect(original.pricing.areaSqft).toBe(244);await openJobs(page);await jobs(page).getByRole('textbox',{name:'Job name',exact:true}).fill('Maple job');await jobs(page).getByRole('textbox',{name:'Revision name',exact:true}).fill('Original option');await jobs(page).getByRole('button',{name:'Save revision',exact:true}).click();await expect(jobs(page).getByRole('heading',{name:'Original option',exact:true})).toBeVisible();await jobs(page).getByRole('button',{name:'Duplicate as Option B',exact:true}).click();expect((await state(page)).design).toEqual(original.design);await jobs(page).getByRole('button',{name:'Close',exact:true}).click();
 await command(page,[{type:'design.patch',patch:{width:24,framingSize:'2x12',height:36}}]);const changed=await state(page);await openJobs(page);await jobs(page).getByRole('textbox',{name:'Revision name',exact:true}).fill('Wider option');await jobs(page).getByRole('button',{name:'Save revision',exact:true}).click();await jobs(page).getByRole('button',{name:/^Original option/}).click();await jobs(page).getByRole('combobox',{name:'Compare against',exact:true}).selectOption({label:'Wider option'});await jobs(page).getByRole('button',{name:'Compare designs and prices',exact:true}).click();await expect(jobs(page).getByLabel('Exact revision price comparison')).toBeVisible();const cards=jobs(page).locator('.dd-jobs-comparison article');expect(await cards.count()).toBe(2);expect(Number(await cards.nth(0).getAttribute('data-exact-total'))).toBe(changed.pricing.total);expect(Number(await cards.nth(1).getAttribute('data-exact-total'))).toBe(original.pricing.total);expect(await cards.nth(1).locator('svg').count()).toBe(1);expect((await state(page)).design).toEqual(changed.design);await jobs(page).locator('.dd-jobs-comparison').scrollIntoViewIfNeeded();await assertComparisonFlow(page,'jobs');await page.screenshot({path:resolve(proof,`${phone?'phone':'desktop'}-job-comparison.png`)});await jobs(page).getByRole('button',{name:'Restore revision',exact:true}).click();await expect(jobs(page)).toBeHidden();const restored=await state(page);expect(restored.design.deckOutlines).toEqual(original.design.deckOutlines);expect(restored.pricing.total).toBe(original.pricing.total);expect(restored.quotes).toEqual(original.quotes);await command(page,[{type:'history.undo'}]);expect((await state(page)).design).toEqual(changed.design);expect((await state(page)).pricing).toEqual(changed.pricing);writeFileSync(resolve(proof,`${phone?'phone':'desktop'}-job-exact-price.json`),JSON.stringify({original:original.pricing,changed:changed.pricing,restored:restored.pricing},null,2));await page.reload();await expect(page.getByRole('region',{name:'Contractor job tools'})).toContainText('Maple job · Original option');
});
test(`${phone?'@phone ':''}plain instructions clarify unsupported requests and preview exact price before one Apply`,async({page})=>{
 const before=await state(page);await openAssistant(page);const input=assistant(page).getByRole('textbox',{name:'What would you like to change?',exact:true});await input.fill('Make it nicer and send the quote');await assistant(page).getByRole('button',{name:'Preview edit',exact:true}).click();await expect(assistant(page).getByRole('alert')).toContainText(/not connected|unavailable|not configured/i);expect(await input.inputValue()).toBe('Make it nicer and send the quote');expect((await state(page)).design).toEqual(before.design);await input.fill('Make the deck 20 by 14 feet');await assistant(page).getByRole('button',{name:'Preview edit',exact:true}).click();await expect(assistant(page).getByRole('heading',{name:'Review this edit',exact:true})).toBeVisible();expect((await state(page)).design).toEqual(before.design);const expected=Number(await assistant(page).locator('.dd-jobs-comparison article').nth(1).getAttribute('data-exact-total'));await assertComparisonFlow(page,'instructions');await page.screenshot({path:resolve(proof,`${phone?'phone':'desktop'}-instruction-preview.png`)});await assistant(page).getByRole('button',{name:'Apply reviewed edit',exact:true}).click();await expect(assistant(page).locator('footer').getByRole('status')).toContainText('one undoable edit');const after=await state(page);expect(after.design.width).toBe(20);expect(after.design.length).toBe(14);expect(after.pricing.total).toBe(expected);await assistant(page).getByRole('button',{name:'Close instruction assistant',exact:true}).click();await command(page,[{type:'history.undo'}]);expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);await openAssistant(page);await assistant(page).getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Make these stairs six feet wide');await assistant(page).getByRole('button',{name:'Preview edit',exact:true}).click();await expect(assistant(page).getByRole('heading',{name:'Review this edit'})).toBeVisible();await command(page,[{type:'design.patch',patch:{framingSize:'2x12'}}]);await expect(assistant(page).getByRole('button',{name:'Apply reviewed edit',exact:true})).toBeDisabled();await expect(assistant(page).getByRole('alert')).toContainText('changed');expect((await state(page)).design.stairWidth).toBe(before.design.stairWidth);await assistant(page).getByRole('textbox',{name:'What would you like to change?',exact:true}).focus();await page.keyboard.press('Escape');await expect(assistant(page)).toBeHidden();await expect(page.getByRole('button',{name:'Describe a change',exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);writeFileSync(resolve(proof,`${phone?'phone':'desktop'}-instruction-exact-price.json`),JSON.stringify({before:before.pricing,expected,after:after.pricing},null,2));
});});
test('job library portable privacy, strict import rejection, rename and delete leave open design unchanged',async({page})=>{const before=await state(page);await openJobs(page);await jobs(page).getByRole('textbox',{name:'Job name',exact:true}).fill('Private local job');await jobs(page).getByRole('textbox',{name:'Revision name',exact:true}).fill('Original');await jobs(page).getByRole('button',{name:'Save revision',exact:true}).click();await jobs(page).locator('summary').filter({hasText:'Portable job files'}).click();const downloading=page.waitForEvent('download');await jobs(page).getByRole('button',{name:'Export selected job'}).click();const stream=await(await downloading).createReadStream();let text='';for await(const b of stream!)text+=b.toString();for(const key of ['customerName','projectAddress','scopeOfWork','materialMarkup','customLaborCost','customOverrides'])expect(text).not.toContain(`"${key}"`);const portable=JSON.parse(text);await jobs(page).getByLabel('Import job library file').setInputFiles({name:'duplicate.json',mimeType:'application/json',buffer:Buffer.from(text)});await expect(jobs(page).getByRole('alert')).toContainText('unique');const unknown=structuredClone(portable);unknown.jobs[0].id='import-job';unknown.jobs[0].name='Imported';unknown.jobs[0].revisions[0].id='import-revision';unknown.jobs[0].revisions[0].data.customerName='Leak';await jobs(page).getByLabel('Import job library file').setInputFiles({name:'private.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(unknown))});await expect(jobs(page).getByRole('alert')).toContainText('customer details');delete unknown.jobs[0].revisions[0].data.customerName;await jobs(page).getByLabel('Import job library file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(unknown))});await expect(jobs(page).getByRole('combobox',{name:'Saved job',exact:true})).toHaveValue('import-job');await jobs(page).getByRole('button',{name:/^Original/}).click();await jobs(page).locator('summary').filter({hasText:'Rename or remove revision'}).click();await jobs(page).getByRole('textbox',{name:'New revision name'}).fill('Renamed revision');await jobs(page).getByRole('button',{name:'Rename revision',exact:true}).click();await expect(jobs(page).getByRole('heading',{name:'Renamed revision'})).toBeVisible();await jobs(page).getByRole('button',{name:'Delete revision',exact:true}).click();expect((await state(page)).design).toEqual(before.design);await jobs(page).getByRole('button',{name:'Close',exact:true}).click();await page.reload();await openJobs(page);await expect(jobs(page).getByRole('combobox',{name:'Saved job',exact:true})).toContainText('Private local job');});

test('nondefault private current pricing and explicit saved pricing exactly match reviewed restores',async({page})=>{
 const {library:fixture,ratesA,ratesB,firstExpected,expectedCurrent,expectedSaved}=JSON.parse(readFileSync(resolve(process.cwd(),'e2e/fixtures/job-private-pricing.json'),'utf8'));await page.evaluate(v=>localStorage.setItem('golden-maple.deck-studio.jobs.v1',JSON.stringify(v)),fixture);
 const a=fixture.jobs[0].revisions[0],b=fixture.jobs[0].revisions[1];await openJobs(page);await jobs(page).getByRole('button',{name:/^Rate A/}).click();await jobs(page).getByRole('checkbox',{name:/^Use saved contractor pricing/}).check();await jobs(page).getByRole('button',{name:'Compare designs and prices'}).click();expect(Number(await jobs(page).locator('.dd-jobs-comparison article').nth(1).getAttribute('data-exact-total'))).toBe(firstExpected);await jobs(page).getByRole('button',{name:'Restore revision'}).click();await expect(jobs(page)).toBeHidden();expect((await state(page)).pricing.total).toBe(firstExpected);
 expect(expectedSaved).not.toBe(expectedCurrent);await openJobs(page);await jobs(page).getByRole('button',{name:/^Rate B/}).click();await expect(jobs(page).getByRole('checkbox',{name:/^Use saved contractor pricing/})).not.toBeChecked();await jobs(page).getByRole('button',{name:'Compare designs and prices'}).click();expect(Number(await jobs(page).locator('.dd-jobs-comparison article').nth(1).getAttribute('data-exact-total'))).toBe(expectedCurrent);await jobs(page).getByRole('button',{name:'Restore revision'}).click();await expect(jobs(page)).toBeHidden();expect((await state(page)).pricing.total).toBe(expectedCurrent);
 await openJobs(page);await jobs(page).getByRole('textbox',{name:'Revision name',exact:true}).fill('Audit current prices');await jobs(page).getByRole('button',{name:'Save revision'}).click();const capturedA=await page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.jobs.v1')!).jobs[0].revisions.at(-1).data);for(const [key,value] of Object.entries(ratesA))expect(capturedA[key]).toEqual(value);
 await jobs(page).getByRole('button',{name:/^Rate B/}).click();await jobs(page).getByRole('checkbox',{name:/^Use saved contractor pricing/}).check();await jobs(page).getByRole('button',{name:'Compare designs and prices'}).click();expect(Number(await jobs(page).locator('.dd-jobs-comparison article').nth(1).getAttribute('data-exact-total'))).toBe(expectedSaved);await jobs(page).locator('.dd-jobs-comparison').scrollIntoViewIfNeeded();await assertComparisonFlow(page,'jobs');await page.screenshot({path:resolve(proof,'desktop-private-price-comparison.png')});await jobs(page).getByRole('button',{name:'Restore revision'}).click();await expect(jobs(page)).toBeHidden();expect((await state(page)).pricing.total).toBe(expectedSaved);await openJobs(page);await jobs(page).getByRole('textbox',{name:'Revision name',exact:true}).fill('Audit saved prices');await jobs(page).getByRole('button',{name:'Save revision'}).click();const capturedB=await page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.jobs.v1')!).jobs[0].revisions.at(-1).data);for(const [key,value] of Object.entries(ratesB))expect(capturedB[key]).toEqual(value);await jobs(page).getByRole('button',{name:'Close',exact:true}).click();await command(page,[{type:'history.undo'}]);expect((await state(page)).pricing.total).toBe(expectedCurrent);writeFileSync(resolve(proof,'private-pricing-exact-restores.json'),JSON.stringify({expectedCurrent,expectedSaved,capturedA,capturedB},null,2));
});
