import {test,expect,type Page,type Locator} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import sharp from 'sharp';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {planInlays} from '../src/features/deckcraft/lib/inlayGeometry';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
import type {DeckData,DeckInlay} from '../src/features/deckcraft/types';
const proof=resolve(process.cwd(),'../../outputs/deckcraft-inlay-review');mkdirSync(proof,{recursive:true});
const fixture:DeckData={...DEFAULT_DECK,width:24,length:20,houseVisible:false,deckType:'Freestanding',stairFlights:0,railingType:'None'};
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const controls=(page:Page)=>page.getByLabel('Inlay plan controls',{exact:true});
async function ready(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);return state(page);}
async function activate(el:Locator,touch:boolean){if(touch)await el.tap();else await el.click();}
async function open(page:Page,touch:boolean){await activate(page.getByRole('radio',{name:'Inlays',exact:true}),touch);await expect(controls(page)).toBeVisible();}
async function point(page:Page,p:{x:number;y:number},touch:boolean){
 const surface=page.getByLabel('Inlay placement surface',{exact:true});
 // Native scrolling can move the canvas after the button's actionability scroll. Let that layout settle before CTM.
 const beforeLayout=await surface.evaluate(async el=>{el.scrollIntoView({block:'center'});const m=(el as SVGSVGElement).getScreenCTM()!,initial={a:m.a,d:m.d,e:m.e,f:m.f,scrollY};await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return initial;});
 const q=await surface.evaluate((el,p)=>{const m=(el as SVGSVGElement).getScreenCTM()!,q=new DOMPoint(p.x,p.y).matrixTransform(m),hit=document.elementFromPoint(q.x,q.y);return {x:q.x,y:q.y,hit:hit===el,hitLabel:hit?.getAttribute('aria-label'),scrollY,matrix:{a:m.a,d:m.d,e:m.e,f:m.f}};},p);
 expect(q.hit,'The native input must hit the actual placement SVG, clear of sticky controls').toBe(true);
 writeFileSync(resolve(proof,`${touch?'phone':'desktop'}-preset-tap-${p.x}-${p.y}.json`),JSON.stringify({target:p,beforeLayout,beforeNativeInput:q},null,2));
 if(touch)await page.touchscreen.tap(q.x,q.y);else await page.mouse.click(q.x,q.y);
}
async function drag(page:Page,handle:Locator,dx:number,dy:number,touch:boolean){const before=await state(page);await handle.evaluate(el=>el.scrollIntoView({block:'center'}));const b=(await handle.boundingBox())!,start={x:b.x+b.width/2,y:b.y+b.height/2},m=await page.locator('.dd-inlay-plan-editor>svg').evaluate(el=>{const m=(el as SVGSVGElement).getScreenCTM()!;return {a:m.a,d:m.d};}),end={x:start.x+dx*m.a,y:start.y+dy*m.d};
 expect(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('button')?.getAttribute('aria-label'),start)).toBe(await handle.getAttribute('aria-label'));
 if(touch){const session=await page.context().newCDPSession(page);try{await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...start,id:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:(start.x+end.x)/2,y:(start.y+end.y)/2,id:1}]});expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);expect((await state(page)).history).toEqual(before.history);await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...end,id:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}finally{await session.detach();}}
 else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:5});expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);expect((await state(page)).history).toEqual(before.history);await page.mouse.up();}}
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page,context})=>{const found:string[]=[];errors.set(page,found);page.on('pageerror',e=>found.push(e.message));await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{const key='golden-maple.deck-studio.deck-only.v1';if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},fixture);await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&['GET','HEAD'].includes(r.request().method())?r.continue():r.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await ready(page);});
test.afterEach(async({page},info)=>{expect(errors.get(page)??[]).toEqual([]);writeFileSync(resolve(proof,`${info.project.name}-${info.title.replace(/[^a-z0-9]+/gi,'-')}.json`),JSON.stringify({status:info.status,errors:errors.get(page)??[]},null,2));});
for(const touch of [false,true])test(`${touch?'@phone ':''}inlay placement is explicit, invalid targets stay pending, drag edits commit once and Delete has Undo`,async({page})=>{
 await open(page,touch);const initial=await state(page);await activate(controls(page).getByRole('button',{name:'Add rectangle',exact:true}),touch);await expect(page.getByText('Choose a position on the deck',{exact:true})).toBeVisible();expect((await state(page)).design).toEqual(initial.design);expect((await state(page)).pricing).toEqual(initial.pricing);expect((await state(page)).history).toEqual(initial.history);
 await point(page,{x:12,y:12},touch);await expect(controls(page).getByRole('status').last()).toContainText(/Placement is still active/);await expect(page.locator('.dd-inlay-placement-preview[data-invalid]')).toBeVisible();expect((await state(page)).design).toEqual(initial.design);await activate(controls(page).getByRole('button',{name:'Cancel placement',exact:true}),touch);expect((await state(page)).history).toEqual(initial.history);
 await activate(controls(page).getByRole('button',{name:'Add rectangle',exact:true}),touch);await point(page,{x:90.25,y:110.5},touch);await expect.poll(async()=>(await state(page)).design.inlays?.length).toBe(1);const placed=await ready(page),i=placed.design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>;expect(i.dxFt).toBeCloseTo((90.25-144)/12,5);expect(i.dyFt).toBeCloseTo((110.5-120)/12,5);await expect(page.getByLabel('Inlay placement surface',{exact:true})).toHaveCount(0);
 await drag(page,page.getByRole('button',{name:'Move inlay 1',exact:true}),15.375,-12.25,touch);const moved=await ready(page),mi=moved.design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>;expect(mi.dxFt).toBeCloseTo(i.dxFt!+15.375/12,5);expect(mi.dyFt).toBeCloseTo(i.dyFt!-12.25/12,5);await activate(page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(placed.design);await activate(page.getByRole('button',{name:'Redo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(moved.design);
 const move=page.getByRole('button',{name:'Move inlay 1',exact:true});await move.focus();await move.press('Shift+ArrowDown');const keyed=await ready(page),ki=keyed.design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>;expect(ki.dyFt).toBeCloseTo(mi.dyFt!+1,5);
 const rotation=controls(page).getByRole('spinbutton',{name:'Inlay 1 rotation',exact:true});await rotation.fill('30');await rotation.press('Enter');await expect.poll(async()=>((await state(page)).design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>).rotationDeg).toBe(30);await controls(page).getByLabel('Inlay 1 frame rows',{exact:true}).selectOption('2');const colour=controls(page).getByLabel('Inlay 1 frame colour',{exact:true});const choice=(await colour.locator('option').nth(1).getAttribute('value'))!;await colour.selectOption(choice);const finished=await ready(page);expect((finished.design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>).frame).toBe(choice);
 await move.focus();await move.press('Delete');await expect.poll(async()=>(await state(page)).design.inlays?.length??0).toBe(0);await activate(page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(finished.design);await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.deck-only.v1')??'{}').configuration?.inlays?.[0]?.rotationDeg)).toBe(30);await page.reload();await ready(page);expect((await state(page)).design.inlays).toEqual(finished.design.inlays);await open(page,touch);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-inlay-placement.png`),fullPage:true});
});
for(const touch of [false,true])test(`${touch?'@phone ':''}compass rose and sunburst have distinct preset previews and retained quote scopes`,async({page})=>{
 await open(page,touch);const rose=controls(page).getByRole('button',{name:'Add compass rose',exact:true}),sun=controls(page).getByRole('button',{name:'Add sunburst',exact:true});expect(await rose.locator('svg polygon').count()).toBeGreaterThan(1);expect(await rose.locator('svg').innerHTML()).not.toBe(await sun.locator('svg').innerHTML());await activate(rose,touch);await point(page,{x:144,y:120},touch);await expect.poll(async()=>(await state(page)).design.inlays?.[0]).toMatchObject({kind:'medallion',style:'compass-rose'});const rosePlaced=(await state(page)).design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>;expect(rosePlaced.dxFt??0).toBeCloseTo(0,5);expect(rosePlaced.dyFt??0).toBeCloseTo(0,5);expect((await state(page)).quotes.some(q=>/medallion|inlay/i.test(q))).toBe(true);const handle=page.getByRole('button',{name:'Move inlay 1',exact:true});await handle.focus();await handle.press('Delete');await activate(sun,touch);await point(page,{x:144,y:120},touch);await expect.poll(async()=>(await state(page)).design.inlays?.[0]).toMatchObject({kind:'medallion',style:'sunburst'});const sunPlaced=(await state(page)).design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>;expect(sunPlaced.dxFt??0).toBeCloseTo(0,5);expect(sunPlaced.dyFt??0).toBeCloseTo(0,5);const input=controls(page).getByRole('spinbutton',{name:'Inlay 1 out from the middle',exact:true});await expect(input).toHaveValue('0');const beforeFocus=await ready(page);await input.focus();await input.press('Tab');const afterBlur=await ready(page);expect(afterBlur.design).toEqual(beforeFocus.design);expect(afterBlur.pricing).toEqual(beforeFocus.pricing);expect(afterBlur.history).toEqual(beforeFocus.history);expect(afterBlur.revision).toBe(beforeFocus.revision);const beforeCapture=await ready(page),inputBefore=await input.inputValue();await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-sunburst-postcapture.png`),fullPage:true});const afterCapture=await ready(page),inputAfter=await input.inputValue();writeFileSync(resolve(proof,`${touch?'phone':'desktop'}-sunburst-postcapture-state.json`),JSON.stringify({beforeCapture,inputBefore,afterCapture,inputAfter},null,2));expect(afterCapture.design).toEqual(beforeCapture.design);expect(inputAfter).toBe('0');
 const typedValue=1.234567891;await input.fill(String(typedValue));await input.press('Enter');await expect.poll(async()=>((await state(page)).design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>).dyFt).toBe(typedValue);await expect(input).toHaveValue('1.23457');const afterTyped=await ready(page);await input.focus();await input.press('Tab');const afterTypedBlur=await ready(page);expect(afterTypedBlur.design).toEqual(afterTyped.design);expect(afterTypedBlur.pricing).toEqual(afterTyped.pricing);expect(afterTypedBlur.history).toEqual(afterTyped.history);expect(afterTypedBlur.revision).toBe(afterTyped.revision);await activate(page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(beforeCapture.design);expect((await state(page)).pricing).toEqual(beforeCapture.pricing);writeFileSync(resolve(proof,`${touch?'phone':'desktop'}-inlay-offset-formatting.json`),JSON.stringify({beforeFocus,afterBlur,displayAtCentre:inputBefore,rawCentreDy:sunPlaced.dyFt??0,typedValue,typedDisplay:'1.23457',savedTypedDy:(afterTyped.design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>).dyFt,afterTypedBlur,undoDesign:(await state(page)).design},null,2));
});
for(const touch of [false,true])test(`${touch?'@phone ':''}existing custom corners remain editable while preserving identity finishes another inlay and one Undo`,async({page})=>{
 await open(page,touch);await activate(controls(page).getByRole('button',{name:'Add hexagon',exact:true}),touch);await point(page,{x:90,y:90},touch);await expect.poll(async()=>(await state(page)).design.inlays?.length).toBe(1);await activate(controls(page).getByRole('button',{name:'Add rectangle',exact:true}),touch);await point(page,{x:210,y:160},touch);await expect.poll(async()=>(await state(page)).design.inlays?.length).toBe(2);const before=await ready(page),custom=before.design.inlays![0] as Extract<DeckInlay,{kind:'custom'}>;await controls(page).getByLabel('Selected inlay',{exact:true}).selectOption(custom.id);await activate(controls(page).getByRole('button',{name:'Edit custom shape',exact:true}),touch);
 const modal=page.getByRole('dialog',{name:'Sketch an inlay',exact:true});await expect(modal.getByLabel('Inlay sketch name',{exact:true})).toHaveValue('Hexagon');await modal.getByRole('button',{name:'Inlay sketch point 1',exact:true}).focus();await modal.getByRole('button',{name:'Inlay sketch point 1',exact:true}).press('ArrowRight');expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);await activate(modal.getByRole('button',{name:'Cancel inlay sketch',exact:true}),touch);expect((await state(page)).history).toEqual(before.history);
 await activate(controls(page).getByRole('button',{name:'Edit custom shape',exact:true}),touch);await modal.getByLabel('Inlay sketch width feet',{exact:true}).fill('8');await modal.getByLabel('Inlay sketch width inches',{exact:true}).fill('0');await modal.getByLabel('Inlay sketch depth feet',{exact:true}).fill('6');await modal.getByLabel('Inlay sketch depth inches',{exact:true}).fill('0');await activate(modal.getByRole('button',{name:'Apply inlay measurements',exact:true}),touch);await modal.getByLabel('Inlay sketch name',{exact:true}).fill('Corner motif');expect((await state(page)).design).toEqual(before.design);await activate(modal.getByRole('button',{name:'Place on deck',exact:true}),touch);await expect(modal).toBeHidden();const edited=await ready(page),next=edited.design.inlays![0] as Extract<DeckInlay,{kind:'custom'}>;expect(next).toMatchObject({id:custom.id,name:'Corner motif',frame:custom.frame,dxFt:custom.dxFt,dyFt:custom.dyFt});expect(next.points).not.toEqual(custom.points);expect(Math.max(...next.points.map(p=>p.x))-Math.min(...next.points.map(p=>p.x))).toBeCloseTo(96,5);expect(edited.design.inlays![1]).toEqual(before.design.inlays![1]);await expect(page.getByText('Choose a position on the deck',{exact:true})).toHaveCount(0);
 await activate(page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);await activate(page.getByRole('button',{name:'Redo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(edited.design);
 const polygon=page.getByRole('button',{name:`Inlay ${custom.id} outline`,exact:true});await polygon.focus();await polygon.press('Delete');await expect.poll(async()=>(await state(page)).design.inlays?.length).toBe(1);expect((await state(page)).design.inlays![0]).toEqual(before.design.inlays![1]);await activate(page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(edited.design);
});

for(const touch of [false,true])test(`${touch?'@phone ':''}materials Add opens an uncommitted plan placement and one Undo restores the original job`,async({page})=>{
 const before=await ready(page);await activate(page.getByRole('button',{name:'Boards & finish',exact:true}),touch);const add=page.getByRole('button',{name:'Add a framed rectangle',exact:true});await expect(add).toBeVisible();await activate(add,touch);await expect(controls(page)).toBeVisible();await expect(page.getByRole('radio',{name:'Inlays',exact:true})).toHaveAttribute('aria-checked','true');await expect(page.getByText('Choose a position on the deck',{exact:true})).toBeVisible();expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);expect((await state(page)).history).toEqual(before.history);
 await point(page,{x:110.125,y:137.75},touch);await expect.poll(async()=>(await state(page)).design.inlays?.length).toBe(1);const placed=await ready(page),inlay=placed.design.inlays![0] as Exclude<DeckInlay,{kind:'band'}>;expect(inlay.dxFt).toBeCloseTo((110.125-144)/12,5);expect(inlay.dyFt).toBeCloseTo((137.75-120)/12,5);expect({...placed.design,inlays:before.design.inlays}).toEqual(before.design);await activate(page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);expect((await state(page)).history.canUndo).toBe(before.history.canUndo);
});
test('compass rose generates real 3D boards without changing the design or estimate',async({page})=>{
 await open(page,false);await controls(page).getByRole('button',{name:'Add compass rose',exact:true}).click();await point(page,{x:144,y:120},false);const before=await ready(page);expect(before.inlayShapes[0].status).toBe('ok');expect(planInlays(before.design.inlays!,{fieldPolygons:[[{x:0,y:0},{x:288,y:0},{x:288,y:240},{x:0,y:240}]],centre:{x:144,y:120},boardWidth:fixture.boardWidth,gap:.1875,stockLength:192,straight:true})[0].boards.length).toBeGreaterThan(20);writeFileSync(resolve(proof,'compass-rose-3d-fixture.json'),JSON.stringify(before.design,null,2));
 await page.getByRole('tab',{name:'3D',exact:true}).click();await page.getByRole('group',{name:'Camera',exact:true}).getByRole('button',{name:'Above',exact:true}).click();const region=page.getByRole('region',{name:'Interactive deck construction model',exact:true}),canvas=region.locator('canvas');await expect(canvas).toBeVisible();await canvas.evaluate(el=>el.scrollIntoView({block:'center'}));await expect.poll(()=>canvas.evaluate(el=>(el as HTMLCanvasElement).width)).toBeGreaterThan(0);await expect(page.getByText('Showing the plan view because 3D graphics are unavailable on this device.',{exact:false})).toBeHidden();
 await expect.poll(async()=>{const stats=await sharp(await canvas.screenshot()).stats();return Math.max(...stats.channels.slice(0,3).map(c=>c.stdev));},{timeout:30000,message:'Rendered inlay scene must contain actual board pixels'}).toBeGreaterThan(10);await region.screenshot({path:resolve(proof,'desktop-compass-rose-3d-above.png')});expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);
});
