import {test,expect} from '@playwright/test';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {showProjectControls} from './nav';
const proof=resolve('../../outputs/workflow-improvements');
for(const phone of [false,true])test.describe(phone?'phone workflow':'desktop workflow',()=>{
 if(phone)test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 test((phone?'@phone ':'')+'estimating, options, readiness, recovery and customer export',async({page,context})=>{
 test.setTimeout(180000);mkdirSync(proof,{recursive:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript('window.__name=(target,value)=>target;');
 await context.addInitScript(data=>localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration:data})),DEFAULT_DECK);
 await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&r.request().method()==='GET'?r.continue():r.fulfill({status:200,body:''}));
 await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft?.read().ready??false)).toBe(true);
 await showProjectControls(page);
 await page.getByRole('button',{name:'Review quote costs',exact:true}).click();const quote=page.getByRole('dialog',{name:'Complete the missing costs'});await expect(quote).toBeVisible();
 await quote.locator('summary').filter({hasText:'Live quantities, costs & margin'}).click();await expect(quote.getByRole('heading',{name:'Waste & ordering'})).toBeVisible();await expect(quote.getByRole('heading',{name:'Material markup & margin'})).toBeVisible();await quote.screenshot({path:proof+'/'+(phone?'phone':'desktop')+'-costs.png'});await quote.getByRole('button',{name:'Close quote cost review'}).click();
 const openJobs=async()=>{await page.getByRole('button',{name:'Jobs & versions',exact:true}).click();await expect(page.getByRole('dialog',{name:'Jobs & options',exact:true})).toBeVisible();};
 const jobs=page.getByRole('dialog',{name:'Jobs & options',exact:true});await openJobs();await jobs.getByRole('textbox',{name:'Job name',exact:true}).fill('Local comparison');await jobs.getByRole('textbox',{name:'Revision name',exact:true}).fill('Essential');await jobs.getByRole('button',{name:'Save revision',exact:true}).click();await expect(jobs.getByRole('heading',{name:'Essential',exact:true})).toBeVisible();await jobs.getByRole('button',{name:'Close',exact:true}).click();
 const change=await page.evaluate(async()=>{const api=(window as any).deckcraft;return api.execute({id:'workflow-widen',expectedRevision:api.read().revision,commands:[{type:'design.patch',patch:{width:24,length:20}}]});});expect(change.error).toBeUndefined();
 await openJobs();await jobs.getByRole('textbox',{name:'Revision name',exact:true}).fill('Premium');await jobs.getByRole('button',{name:'Save revision',exact:true}).click();await jobs.getByRole('combobox',{name:'Compare against',exact:true}).selectOption({label:'Essential'});await jobs.getByRole('button',{name:'Compare designs and prices',exact:true}).click();await expect(jobs.getByRole('region',{name:'What changes between options'})).toBeVisible();
 await jobs.locator('summary').filter({hasText:'Customer presentation'}).click();await expect(jobs.getByRole('article',{name:'Customer design options'})).toBeVisible();const exported=page.waitForEvent('download');await jobs.getByRole('button',{name:'Download customer comparison'}).click();const output=await exported;await output.saveAs(proof+'/'+(phone?'phone':'desktop')+'-customer-options.html');const html=readFileSync(await output.path(),'utf8');expect(html).toContain('Planning allowances');expect(html).toContain('<svg');expect(html).not.toContain('materialMarkup');
 const presentation=await context.newPage();await presentation.setContent(html);await expect(presentation.locator('.option-plan svg')).toHaveCount(2);await presentation.screenshot({path:proof+'/'+(phone?'phone':'desktop')+'-customer-options.png',fullPage:!phone});expect(await presentation.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);await presentation.close();console.log('Customer presentation verified');
 console.log('Opening recovery');await jobs.locator('summary').filter({hasText:'Recovery & private working backup'}).click();const backupEvent=page.waitForEvent('download');await jobs.getByRole('button',{name:'Download private working backup'}).click();const backup=await backupEvent;console.log('Private backup downloaded');const backupText=readFileSync(await backup.path(),'utf8');expect(JSON.parse(backupText).format).toBe('deckcraft-private-project');
 await jobs.getByLabel('Review private working backup',{exact:true}).setInputFiles({name:'working.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...JSON.parse(backupText),configuration:{...JSON.parse(backupText).configuration,width:18,materialMarkup:47,customerName:'Private restore QA'}}))});await expect(jobs.getByRole('region',{name:'Recovery preview'})).toBeVisible();await jobs.getByRole('button',{name:'Restore reviewed backup'}).click();await expect(jobs).toBeHidden();await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft.read().design.width)).toBe(18);await page.getByRole('button',{name:'Review quote costs',exact:true}).click();await quote.locator('summary').filter({hasText:'Live quantities, costs & margin'}).click();await expect(quote.getByText(/^47% material markup equals/)).toBeVisible();await quote.getByRole('button',{name:'Close quote cost review'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).deckcraft.read().design.width)).toBe(24);
 await page.getByRole('button',{name:/Review \d+ issues?/}).click();const issues=page.getByRole('dialog',{name:'Construction readiness'});await expect(issues).toBeVisible();await expect(issues.getByRole('combobox',{name:'Review area'})).toBeVisible();await issues.screenshot({path:proof+'/'+(phone?'phone':'desktop')+'-readiness.png'});await issues.getByRole('button',{name:'Back to design'}).click();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);writeFileSync(proof+'/'+(phone?'phone':'desktop')+'-browser-errors.json',JSON.stringify(errors,null,2));expect(errors).toEqual([]);
 });
});
