import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
const out=resolve(process.cwd(),'../../outputs/deckcraft-assistant-review/browser');mkdirSync(out,{recursive:true});
const read=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const dialog=(page:Page)=>page.getByRole('region',{name:'Design assistant',exact:true});
async function open(page:Page){await page.getByRole('button',{name:'Describe a change',exact:true}).click();await expect(dialog(page)).toBeVisible();}
async function prepare(context:BrowserContext,page:Page,speech=false){
 await context.addInitScript('window.__name=(target,value)=>target;');
 await context.addInitScript(()=>{localStorage.clear();});
 if(speech)await context.addInitScript(()=>{
  const qa={created:0,starts:0,stops:0,aborts:0,current:null as any};
  class FakeRecognition {lang='';continuous=false;interimResults=false;onstart:any=null;onend:any=null;onerror:any=null;onresult:any=null;constructor(){qa.created++;qa.current=this;}start(){qa.starts++;this.onstart?.();}stop(){qa.stops++;}abort(){qa.aborts++;}}
  (window as any).SpeechRecognition=FakeRecognition;(window as any).qaSpeech=qa;
 });
 else await context.addInitScript(()=>{Object.defineProperty(window,'SpeechRecognition',{value:undefined,configurable:true});Object.defineProperty(window,'webkitSpeechRecognition',{value:undefined,configurable:true});});
 await context.route('**/*',r=>{const req=r.request();if(!/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(req.url()))return r.fulfill({status:200,body:''});if(req.url().includes('/.netlify/functions/deck-assistant'))return r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'AI interpretation is not connected in this test.'}})});return req.method()==='GET'||req.method()==='HEAD'?r.continue():r.fulfill({status:403,body:'Blocked test write'});});
 await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);
}
for(const size of [{width:1440,height:1000},{width:768,height:1024},{width:390,height:844}])test.describe(`assistant ${size.width}`,()=>{
 test.use({viewport:size,hasTouch:size.width<1000,isMobile:size.width===390});
 test(`${size.width===390?'@phone ':''}preview first exact fallback, real price parity, single Undo and accessible assistant panel`,async({context,page})=>{
  await prepare(context,page);const before=await read(page);await open(page);const d=dialog(page);
  await expect(d.getByRole('checkbox',{name:'Apply changes automatically',exact:true})).not.toBeChecked();await expect(d.locator('[data-source="exact-only"]')).toContainText('not connected');await expect(d.getByRole('button',{name:'Talk',exact:true})).toHaveCount(0);await expect(d).toContainText('Voice dictation is unavailable');
  const input=d.getByRole('textbox',{name:'What would you like to change?',exact:true});await input.fill('  Make the deck 20 by 14 feet  ');await d.getByRole('button',{name:'Preview edit',exact:true}).click();const preview=d.getByRole('region',{name:'Instruction preview'});await expect(preview).toBeVisible();await expect(preview).toContainText('exact instruction parser');expect((await read(page)).design).toEqual(before.design);
  const price=Number(await preview.locator('[data-exact-total]').nth(1).getAttribute('data-exact-total'));await d.getByRole('button',{name:'Apply reviewed edit',exact:true}).click();await expect(d.getByRole('region',{name:'Applied interpretation'})).toBeVisible();const after=await read(page);expect(after.design.width).toBe(20);expect(after.design.length).toBe(14);expect(after.pricing.total).toBe(price);expect(after.revision).toBeGreaterThan(before.revision);
  const geometry=await d.evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:innerWidth,height:innerHeight,modal:el instanceof HTMLDialogElement,overflow:el.scrollWidth>el.clientWidth+1,buttons:[...el.querySelectorAll('button')].filter(b=>b.getBoundingClientRect().height>0).map(b=>b.getBoundingClientRect().height)};});expect(geometry.left).toBeGreaterThanOrEqual(-1);expect(geometry.right).toBeLessThanOrEqual(geometry.width+1);if(geometry.modal){expect(geometry.top).toBeGreaterThanOrEqual(-1);expect(geometry.bottom).toBeLessThanOrEqual(geometry.height+1);}expect(geometry.overflow).toBe(false);expect(geometry.buttons.every(h=>h>=43.99)).toBe(true);
  await page.screenshot({path:resolve(out,`assistant-exact-${size.width}.png`)});await d.getByRole('button',{name:'Close instruction assistant'}).click();await expect(page.getByRole('button',{name:'Describe a change',exact:true})).toBeFocused();await page.getByRole('button',{name:'Undo',exact:true}).click();const undone=await read(page);expect(undone.design).toEqual(before.design);expect(undone.pricing.total).toBe(before.pricing.total);expect(undone.history.canUndo).toBe(before.history.canUndo);
  await open(page);await dialog(page).getByRole('checkbox',{name:'Apply changes automatically',exact:true}).check();await dialog(page).getByRole('button',{name:'Close instruction assistant'}).click();await open(page);await expect(dialog(page).getByRole('checkbox',{name:'Apply changes automatically',exact:true})).not.toBeChecked();
 });
});
for(const phone of [false,true])test.describe(phone?'phone explicit speech':'desktop explicit speech',()=>{
 test.use({viewport:phone?{width:390,height:844}:{width:1440,height:1000},hasTouch:phone,isMobile:phone});
 test(`${phone?'@phone ':''}explicit Talk, interim not applied, editable final, Stop and close abort; denied permission retry`,async({context,page})=>{
  await prepare(context,page,true);const before=await read(page);await open(page);const d=dialog(page),input=d.getByRole('textbox',{name:'What would you like to change?',exact:true});expect(await page.evaluate(()=>(window as any).qaSpeech.created)).toBe(0);await expect(d).toContainText('may use its speech service');
  const talk=d.getByRole('button',{name:'Talk',exact:true});if(phone)await talk.tap();else await talk.click();await expect(d.getByRole('button',{name:'Stop',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).qaSpeech.starts)).toBe(1);
  await page.evaluate(()=>{(window as any).qaSpeech.current.onresult({resultIndex:0,results:[Object.assign([{transcript:'make the deck twenty feet wide'}],{isFinal:false})]});});await expect(d.getByLabel('Interim speech transcript')).toContainText('Not final and not applied');await expect(input).toHaveValue('');expect((await read(page)).design).toEqual(before.design);await expect(d.getByRole('button',{name:'Preview edit',exact:true})).toBeDisabled();
  await page.evaluate(()=>{(window as any).qaSpeech.current.onresult({resultIndex:0,results:[Object.assign([{transcript:'Make the deck 20 by 14 feet'}],{isFinal:true})]});});await expect(input).toHaveValue('Make the deck 20 by 14 feet');await input.fill('Make the deck 22 by 14 feet');
  await d.getByRole('button',{name:'Stop',exact:true}).click();expect(await page.evaluate(()=>(window as any).qaSpeech.stops)).toBe(1);await page.evaluate(()=>(window as any).qaSpeech.current.onend());await expect(input).toHaveValue('Make the deck 22 by 14 feet');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect(d.getByRole('region',{name:'Instruction preview'})).toBeVisible();expect((await read(page)).design).toEqual(before.design);
  await d.getByRole('button',{name:'Talk',exact:true}).click();await d.getByRole('button',{name:'Close instruction assistant'}).click();expect(await page.evaluate(()=>(window as any).qaSpeech.aborts)).toBeGreaterThanOrEqual(1);expect(await page.evaluate(()=>(window as any).qaSpeech.current.onresult)).toBeNull();expect((await read(page)).design).toEqual(before.design);
  await open(page);await dialog(page).getByRole('button',{name:'Talk',exact:true}).click();await page.evaluate(()=>(window as any).qaSpeech.current.onerror({error:'not-allowed'}));await expect(dialog(page).getByRole('alert')).toContainText('permission was denied');await expect(dialog(page).getByRole('button',{name:'Talk',exact:true})).toBeEnabled();await page.screenshot({path:resolve(out,`assistant-speech-denied-${phone?390:1440}.png`)});
 });
});
const editPlan=(width:number)=>({kind:'edit',message:`Make the main deck ${width} feet wide.`,assumptions:['A little wider means two more feet.'],commands:[{type:'design.patch',patch:{width}}]});
const clarifyPlan={kind:'clarify',message:'Several targets could be moved.',assumptions:[],commands:[],question:'Which part should move?',choices:['Main deck','Stairs']};
test('real client clarification contract, assumptions, opt-in automatic validated edit and one Undo',async({context,page})=>{
 await prepare(context,page);let calls:any[]=[];
 await page.route('**/.netlify/functions/deck-assistant',async route=>{const req=route.request();if(req.method()==='GET')return route.fulfill({contentType:'application/json',body:JSON.stringify({ready:true,source:'local-ai',model:'QA contract fixture'})});const body=req.postDataJSON();calls.push(body);const plan=body.prompt==='Move it over'?clarifyPlan:editPlan(18);return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'local-ai',model:'QA contract fixture',plan})});});
 const before=await read(page);await open(page);const d=dialog(page);await expect(d.locator('[data-source="local-ai"]')).toContainText('QA contract fixture');await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Move it over');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect(d.getByRole('region',{name:'Clarification needed'})).toBeVisible();expect((await read(page)).design).toEqual(before.design);await d.getByRole('button',{name:'Main deck',exact:true}).click();await expect(d.getByRole('region',{name:'Instruction preview'})).toBeVisible();await expect(d.getByRole('region',{name:'Interpretation assumptions'})).toContainText('two more feet');expect((await read(page)).revision).toBe(before.revision);expect(calls[1].conversation).toEqual([{role:'user',content:'Move it over'},{role:'assistant',content:'Which part should move?'}]);
 await d.getByRole('button',{name:'Apply reviewed edit',exact:true}).click();await expect(d.getByRole('region',{name:'Applied interpretation'})).toContainText('two more feet');expect((await read(page)).design.width).toBe(18);await d.getByRole('button',{name:'Close instruction assistant'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await read(page)).design).toEqual(before.design);
 await open(page);await dialog(page).getByRole('checkbox',{name:'Apply changes automatically',exact:true}).check();await dialog(page).getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Move it over');await dialog(page).getByRole('button',{name:'Preview edit',exact:true}).click();await expect(dialog(page).getByRole('region',{name:'Clarification needed'})).toBeVisible();expect((await read(page)).design).toEqual(before.design);await dialog(page).getByRole('textbox',{name:'Your answer',exact:true}).fill('Make the main deck a little wider');await dialog(page).getByRole('button',{name:'Preview edit',exact:true}).click();await expect(dialog(page).getByRole('region',{name:'Applied interpretation'})).toContainText('two more feet');expect((await read(page)).revision).toBeGreaterThan(before.revision);expect((await read(page)).design.width).toBe(18);await page.screenshot({path:resolve(out,'assistant-clarification-auto.png')});await dialog(page).getByRole('button',{name:'Close instruction assistant'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await read(page)).design).toEqual(before.design);
});
test('delayed interpretation invalidates on text, design revision and close; invalid model plan never writes',async({context,page})=>{
 await prepare(context,page);let posts=0,release:(()=>void)|undefined;
 await page.route('**/.netlify/functions/deck-assistant',async route=>{if(route.request().method()==='GET')return route.fulfill({contentType:'application/json',body:JSON.stringify({ready:true,source:'local-ai',model:'QA delayed fixture'})});posts++;await new Promise<void>(r=>release=r);await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'local-ai',model:'QA delayed fixture',plan:editPlan(18)})}).catch(()=>{});});
 const before=await read(page);await open(page);let d=dialog(page);await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Make this a little wider');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect.poll(()=>posts).toBe(1);await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Make the deck 22 by 14 feet');release!();await expect(d.getByRole('button',{name:'Preview edit',exact:true})).toBeEnabled();expect((await read(page)).design).toEqual(before.design);await expect(d.getByRole('region',{name:'Instruction preview'})).toHaveCount(0);
 await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Make this a little wider');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect.poll(()=>posts).toBe(2);await page.evaluate(async()=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;await api.execute({id:'qa-assistant-revision',expectedRevision:api.read().revision,commands:[{type:'design.patch',patch:{width:19}}]});});release!();await expect(d.getByRole('alert')).toContainText('design changed');expect((await read(page)).design.width).toBe(19);await expect(d.getByRole('region',{name:'Instruction preview'})).toHaveCount(0);
 await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Make this a little wider');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect.poll(()=>posts).toBe(3);await d.getByRole('button',{name:'Close instruction assistant'}).click();release!();await open(page);d=dialog(page);expect((await read(page)).design.width).toBe(19);await expect(d.getByRole('textbox',{name:'What would you like to change?',exact:true})).toHaveValue('');await expect(d.getByRole('region',{name:'Instruction preview'})).toHaveCount(0);
 await page.unroute('**/.netlify/functions/deck-assistant');await page.route('**/.netlify/functions/deck-assistant',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'local-ai',plan:{kind:'edit',message:'Illegal pricing override',assumptions:[],commands:[{type:'design.patch',patch:{materialMarkup:0}}]}})}));await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Make it cheaper');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect(d.getByRole('alert')).toContainText('not valid');expect((await read(page)).design.width).toBe(19);await expect(d.getByRole('button',{name:'Apply reviewed edit',exact:true})).toHaveCount(0);
});
test('completed clarification is tied to its design revision and successful Apply clears resolved intent',async({context,page})=>{
 await prepare(context,page);const calls:any[]=[];
 await page.route('**/.netlify/functions/deck-assistant',route=>{if(route.request().method()==='GET')return route.fulfill({contentType:'application/json',body:JSON.stringify({ready:true,source:'local-ai',model:'QA context fixture'})});const body=route.request().postDataJSON();calls.push(body);return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,source:'local-ai',model:'QA context fixture',plan:body.prompt==='Move it over'?clarifyPlan:editPlan(body.prompt==='A little wider again'?21:20)})});});
 await open(page);const d=dialog(page);await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Move it over');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect(d.getByRole('region',{name:'Clarification needed'})).toBeVisible();await expect(d.getByRole('list',{name:'Clarification conversation'})).toBeVisible();
 await page.evaluate(async()=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;await api.execute({id:'qa-completed-question-revision',expectedRevision:api.read().revision,commands:[{type:'design.patch',patch:{width:19}}]});});await expect(d.getByRole('region',{name:'Clarification needed'})).toHaveCount(0);await expect(d.getByRole('list',{name:'Clarification conversation'})).toHaveCount(0);await expect(d.locator('footer')).toContainText('previous question was cleared');
 await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('Move it over');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect(d.getByRole('region',{name:'Clarification needed'})).toBeVisible();expect(calls[1].conversation).toEqual([]);expect(calls[1].context.design.width).toBe(19);await d.getByRole('button',{name:'Main deck',exact:true}).click();await expect(d.getByRole('region',{name:'Instruction preview'})).toBeVisible();expect(calls[2].conversation).toHaveLength(2);await d.getByRole('button',{name:'Apply reviewed edit',exact:true}).click();expect((await read(page)).design.width).toBe(20);
 await d.getByRole('textbox',{name:'What would you like to change?',exact:true}).fill('A little wider again');await d.getByRole('button',{name:'Preview edit',exact:true}).click();await expect(d.getByRole('region',{name:'Instruction preview'})).toBeVisible();expect(calls[3].conversation).toEqual([]);expect((await read(page)).design.width).toBe(20);
});
