import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {getHouseConfig} from '../src/features/deckcraft/houseSettings';
import {withPrivacyProduct} from '../src/features/deckcraft/privacyScreens';
import type {DeckData} from '../src/features/deckcraft/types';
import type {AgentCommand,AgentResponse,DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';

const proof=resolve(process.cwd(),'../../outputs/deckcraft-contractor-review/components');mkdirSync(proof,{recursive:true});
const fixture:DeckData={...DEFAULT_DECK,height:48,houseConfig:{...getHouseConfig(DEFAULT_DECK),widthFt:30,depthFt:18,storeys:2,openings:[{id:'measured-window',type:'Window',facade:'Front',style:'Picture',offsetPct:30,widthIn:60,heightIn:36,bottomIn:108}]},privacyScreens:[{id:'real-screen',side:'Left',lengthFt:6,heightFt:6,offsetPct:50,lights:false}],customerName:'QA Component Customer',projectAddress:'QA fixture address'};
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
let sequence=0;
async function request(page:Page,commands:AgentCommand[],preview=false,revision?:number){return page.evaluate(async({commands,preview,revision,id})=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;return api[preview?'preview':'execute']({commands,id,expectedRevision:revision??api.read().revision});},{commands,preview,revision,id:`component-independent-${++sequence}`});}
function success(response:AgentResponse){if('error'in response)throw new Error(`${response.error.code}: ${response.error.message}`);return response;}
async function selectTool(page:Page){const show=page.getByRole('button',{name:'Show canvas',exact:true});if(await show.isVisible())await show.click();await page.getByRole('radio',{name:'Select parts',exact:true}).click();await expect(page.getByRole('combobox',{name:'Select plan part',exact:true})).toBeVisible();}
async function choose(page:Page,id:string){await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('all');await page.getByRole('searchbox',{name:'Find plan part',exact:true}).fill('');await page.getByRole('combobox',{name:'Select plan part',exact:true}).selectOption(id);}
async function undo(page:Page){await page.getByRole('region',{name:'Save and restore design',exact:true}).getByRole('button',{name:'Undo',exact:true}).click();}
const notice=(page:Page)=>page.locator('.dd-component-notice');
const browserErrors=new WeakMap<Page,string[]>();
test.beforeEach(async({context,page})=>{
 const errors:string[]=[];browserErrors.set(page,errors);page.on('pageerror',error=>errors.push(error.message));
 await context.addInitScript('window.__name=(target,value)=>target;');
 await context.addInitScript(({key,configuration})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},{key:'golden-maple.deck-studio.deck-only.v1',configuration:fixture});
 await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&r.request().method()==='GET'?r.continue():r.fulfill({status:200,body:''}));
 await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);await selectTool(page);
});
test.afterEach(async({page})=>{expect(browserErrors.get(page)??[],'Component editing must not throw an uncaught browser error').toEqual([]);});

for(const configuration of [{name:'desktop',width:1440,height:1000,touch:false},{name:'phone',width:390,height:844,touch:true},{name:'tablet',width:768,height:1024,touch:true}])test.describe(`${configuration.name} real component editing`,()=>{
 test.use({viewport:{width:configuration.width,height:configuration.height},hasTouch:configuration.touch,isMobile:configuration.name==='phone'});
 test(`${configuration.touch?'@phone ':''}selecting actual parts stages edits, applies one undo and routes generated scopes`,async({page})=>{
  const checkpoints:string[]=[];const checked=(name:string)=>checkpoints.push(name),original=await state(page);
  const opening=page.locator('[data-component-id="opening:measured-window"]');await (configuration.touch?opening.tap():opening.click());expect((await state(page)).design).toEqual(original.design);expect((await state(page)).pricing).toEqual(original.pricing);expect((await state(page)).history).toEqual(original.history);checked('Direct opening selection makes no design, price or history write');
  await expect(page.getByRole('spinbutton',{name:'Opening width (in)',exact:true})).toHaveValue('60');await page.getByRole('spinbutton',{name:'Opening width (in)',exact:true}).fill('72');await page.getByRole('spinbutton',{name:'Opening bottom above grade (in)',exact:true}).fill('100');expect((await state(page)).design).toEqual(original.design);checked('Draft opening dimensions remain unapplied');
  await page.getByRole('button',{name:'Apply part changes',exact:true}).click();await expect.poll(async()=>(await state(page)).design.houseConfig?.openings[0].widthIn).toBe(72);const applied=await state(page);expect(applied.design.houseConfig!.openings[0].bottomIn).toBe(100);expect(applied.pricing.total).toBe(original.pricing.total);await expect(notice(page)).toContainText('Actual opening: 72 in');checked('Measured opening Apply reaches real model and preserves total');
  await page.getByRole('region',{name:'Save and restore design',exact:true}).getByRole('button',{name:'Undo',exact:true}).focus();await page.keyboard.press('Enter');expect((await state(page)).design).toEqual(original.design);expect((await state(page)).pricing).toEqual(original.pricing);checked('One keyboard Undo restores the complete pre-Apply design');
  await page.getByRole('region',{name:'Save and restore design',exact:true}).getByRole('button',{name:'Redo',exact:true}).click();expect((await state(page)).design).toEqual(applied.design);
  await page.getByRole('button',{name:'Duplicate part',exact:true}).click();await expect.poll(async()=>(await state(page)).design.houseConfig?.openings.length).toBe(2);expect((await state(page)).parts.filter(p=>p.kind==='opening')).toHaveLength(2);await undo(page);expect((await state(page)).design).toEqual(applied.design);await choose(page,'opening:measured-window');await page.getByRole('button',{name:'Remove part',exact:true}).click();expect((await state(page)).design.houseConfig!.openings).toHaveLength(0);await undo(page);expect((await state(page)).design).toEqual(applied.design);checked('Duplicate/remove act on actual opening records with discrete Undo');
  await choose(page,'house:main');await page.getByRole('spinbutton',{name:'Main house width (ft)',exact:true}).fill('32');await page.getByRole('spinbutton',{name:'House left position (in)',exact:true}).fill('-48');await page.getByRole('button',{name:'Apply part changes',exact:true}).click();const house=await state(page);expect(house.design.houseConfig!.widthFt).toBe(32);expect(house.design.housePlacement).toEqual({anchor:'left',offsetIn:-48});expect(house.parts.find(p=>p.id==='wall:main-front')!.line![0].x).toBe(-48);await undo(page);checked('House size and position move the measured wall geometry');
  await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('screen');const screenTarget=page.locator('[data-component-id="screen:real-screen"]');await (configuration.touch?screenTarget.tap():screenTarget.click());await page.getByRole('spinbutton',{name:'Screen length (ft)',exact:true}).fill('8');await page.getByRole('combobox',{name:'Screen height (ft)',exact:true}).selectOption('5');await page.getByRole('button',{name:'Apply part changes',exact:true}).click();const screen=await state(page);expect(screen.design.privacySqft).toBe(40);expect(screen.pricing.total).not.toBe(applied.pricing.total);checked('Actual privacy-screen length/height update priced face area');
  await page.getByRole('spinbutton',{name:'Screen length (ft)',exact:true}).fill('60');await page.getByRole('button',{name:'Apply part changes',exact:true}).click();await expect(notice(page)).toContainText('does not fit');expect((await state(page)).design).toEqual(screen.design);expect((await state(page)).pricing).toEqual(screen.pricing);await page.getByRole('button',{name:'Cancel changes',exact:true}).click();await expect(page.getByRole('spinbutton',{name:'Screen length (ft)',exact:true})).toHaveValue('8');checked('Oversized screen cannot silently shorten while being priced at full length');
  await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('stairs');const stairTarget=page.locator('[data-component-id="stairs:primary"]');await (configuration.touch?stairTarget.tap():stairTarget.click());await page.getByRole('spinbutton',{name:'Grade stair width (in)',exact:true}).fill('72');await page.getByRole('combobox',{name:'Primary stair side',exact:true}).selectOption('Right');await page.getByRole('spinbutton',{name:'Primary stair offset (%)',exact:true}).fill('35');await page.getByRole('button',{name:'Apply part changes',exact:true}).click();const stair=await state(page);expect(stair.design.stairWidth).toBe(72);expect(stair.design.stairPosition).toBe('Right');expect(stair.parts.find(p=>p.id==='stairs:primary')!.dimensions[0]).toBe('72 in wide');expect(stair.pricing.total).toBeGreaterThan(screen.pricing.total);checked('Primary stairs genuinely widen and move; quantities/pricing refresh');
  await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('beam');const beam=stair.parts.find(p=>p.kind==='beam')!;await page.getByRole('combobox',{name:'Select plan part',exact:true}).selectOption(beam.id);await expect(page.getByLabel('Actual component dimensions')).toContainText(beam.dimensions[0]);await expect(page.locator('.dd-component-scope')).toContainText('all generated framing');await expect(page.getByRole('button',{name:'Apply part changes',exact:true})).toHaveCount(0);checked('Generated beam inspection exposes real dimensions and explicit shared scope');
  await page.getByRole('button',{name:'Edit all generated framing',exact:true}).click();expect((await state(page)).openSections).toContain('site');const site=page.getByRole('region',{name:'Site & foundation',exact:true});await expect(site).toBeVisible();await site.locator('summary').filter({hasText:'Framing & construction preferences'}).click();await expect(site.getByRole('combobox',{name:'Joist size',exact:true})).toBeVisible();await selectTool(page);await choose(page,stair.parts.find(p=>p.kind==='footing')!.id);await expect(page.locator('.dd-component-scope')).toContainText('all footings');await page.getByRole('button',{name:'Edit all footings',exact:true}).click();expect((await state(page)).openSections).toContain('site');await expect(page.getByRole('combobox',{name:'Foundation preference',exact:true})).toBeVisible();await selectTool(page);checked('Generated beam/footing controls route their actual existing framing and foundation settings');
  success(await request(page,[{type:'design.patch',patch:{levels:2,height2:16,width2:10,length2:8}}]));await choose(page,'deck:2');await page.getByRole('button',{name:'Edit level shape',exact:true}).click();await expect(page.getByRole('radio',{name:'Shape & points',exact:true})).toHaveAttribute('aria-checked','true');await expect(page.locator('.dd-boundary-handle[data-level="2"][data-level-selected]')).not.toHaveCount(0);await selectTool(page);await choose(page,'deck:2');await page.getByRole('button',{name:'Edit level boards',exact:true}).click();await expect(page.getByRole('radio',{name:'Board layout',exact:true})).toHaveAttribute('aria-checked','true');await expect(page.getByRole('combobox',{name:'Board layout level',exact:true})).toHaveValue('2');checked('Second-level selection opens the actual shape and board tools for level two');
  await selectTool(page);await choose(page,'opening:measured-window');await page.getByRole('combobox',{name:'Plan component type',exact:true}).selectOption('opening');await page.getByRole('button',{name:'Zoom in',exact:true}).click();await expect(page.getByLabel('Drawing zoom')).toHaveText('125%');const targets=await page.locator('.dd-component-handle').evaluateAll(elements=>elements.map(el=>({id:(el as HTMLElement).dataset.componentId,width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height})));expect(targets.length).toBeGreaterThan(0);expect(targets.every(t=>t.width>=43.99&&t.height>=43.99)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);await expect(page.getByRole('region',{name:'Live price',exact:true})).toBeVisible();await page.getByRole('button',{name:'Fit drawing',exact:true}).click();checked('Component targets remain 44 px at125% zoom and toolbar has no horizontal overflow');
  await page.getByRole('group',{name:'Drawing navigation',exact:true}).scrollIntoViewIfNeeded();const navigation=await page.getByRole('group',{name:'Drawing navigation',exact:true}).boundingBox(),price=await page.getByRole('region',{name:'Live price',exact:true}).boundingBox();expect(navigation!.y+navigation!.height).toBeLessThanOrEqual(price!.y+.5);checked('Drawing navigation remains reachable above live-price footer');
  await page.screenshot({path:resolve(proof,`${configuration.name}-selected-opening.png`)});await page.locator('.dd-component-controls').scrollIntoViewIfNeeded();await page.screenshot({path:resolve(proof,`${configuration.name}-part-toolbar.png`)});writeFileSync(resolve(proof,`${configuration.name}-proof.json`),JSON.stringify({viewport:configuration,checkpoints,targets,finalDesign:(await state(page)).design,price:(await state(page)).pricing.total},null,2));
 });
});

test('stale/disappeared selections refresh safely; validated agent edits preview, save, share and undo',async({page,context})=>{
 const original=await state(page);await choose(page,'opening:measured-window');await page.getByRole('spinbutton',{name:'Opening width (in)',exact:true}).fill('96');
 const patch:AgentCommand={type:'component.edit',id:'opening:measured-window',edit:{action:'update',fields:{widthIn:84,bottomIn:100}}},preview=success(await request(page,[patch],true));expect(preview.snapshot.design.houseConfig!.openings[0].widthIn).toBe(84);expect((await state(page)).design).toEqual(original.design);expect((await state(page)).history).toEqual(original.history);
 success(await request(page,[patch]));await expect(page.getByRole('spinbutton',{name:'Opening width (in)',exact:true})).toHaveValue('84');await expect(page.getByRole('button',{name:'Apply part changes',exact:true})).toBeDisabled();await expect(notice(page)).toContainText('design changed');const current=await state(page);expect(current.pricing.total).toBe(original.pricing.total);
 const rejected=await request(page,[{type:'component.edit',id:'opening:measured-window',edit:{action:'update',fields:{type:'French'}}}]);expect(rejected.ok).toBe(false);expect((await state(page)).design).toEqual(current.design);
 const stale=await request(page,[patch],false,original.revision);expect('error'in stale&&stale.error.code==='stale_revision').toBe(true);expect((await state(page)).design).toEqual(current.design);
 await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.deck-only.v1')??'{}').configuration?.houseConfig?.openings[0]?.widthIn)).toBe(84);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.deck-only.v1')!).configuration);expect(saved.customerName).toBe(fixture.customerName);expect(saved.projectAddress).toBe(fixture.projectAddress);
 await page.reload();await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);expect((await state(page)).design.houseConfig!.openings[0].widthIn).toBe(84);await selectTool(page);await choose(page,'opening:measured-window');
 const shared=success(await request(page,[{type:'action',action:'share.create'}])),other=await context.newPage();await other.goto(shared.result!.url!);await expect.poll(()=>other.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);expect((await state(other)).design.houseConfig!.openings[0].widthIn).toBe(84);expect((await state(other)).pricing.total).toBe(current.pricing.total);await other.close();
 success(await request(page,[{type:'component.edit',id:'opening:measured-window',edit:{action:'remove'}}]));await expect(page.getByRole('combobox',{name:'Select plan part',exact:true})).toHaveValue('');await expect(notice(page)).toContainText('no longer');await expect(page.getByRole('button',{name:'Apply part changes',exact:true})).toHaveCount(0);success(await request(page,[{type:'history.undo'}]));expect((await state(page)).design.houseConfig!.openings[0].widthIn).toBe(84);
 await choose(page,'wall:main-right');await page.locator('.dd-component-add summary').click();await page.getByRole('combobox',{name:'New opening preset',exact:true}).selectOption('Window:Casement');await page.getByRole('combobox',{name:'New opening wall',exact:true}).selectOption('main-right');await page.getByRole('button',{name:'Add opening',exact:true}).click();expect((await state(page)).design.houseConfig!.openings).toHaveLength(2);await expect(page.getByRole('combobox',{name:'Select plan part',exact:true})).toHaveValue('opening:part-opening-1');await undo(page);expect((await state(page)).design.houseConfig!.openings).toHaveLength(1);
 await choose(page,'opening:measured-window');await page.getByRole('spinbutton',{name:'Opening width (in)',exact:true}).fill('');await page.getByRole('button',{name:'Apply part changes',exact:true}).click();await expect(notice(page)).toContainText('Enter a number');expect((await state(page)).design.houseConfig!.openings[0].widthIn).toBe(84);await page.screenshot({path:resolve(proof,'desktop-invalid-edit.png')});
 const manufacturer={...withPrivacyProduct(fixture.privacyScreens![0],'hideaway'),panels:1};success(await request(page,[{type:'design.patch',patch:{privacyScreens:[manufacturer]}}]));await choose(page,'screen:real-screen');await expect(page.getByRole('spinbutton',{name:'Screen length (ft)',exact:true})).toHaveCount(0);await expect(page.getByRole('spinbutton',{name:'Screen stock panels',exact:true})).toHaveValue('1');await page.getByRole('spinbutton',{name:'Screen stock panels',exact:true}).fill('2');await page.getByRole('button',{name:'Apply part changes',exact:true}).click();const stock=await state(page);expect(stock.design.privacyScreens![0].panels).toBe(2);expect(stock.design.privacySqft).toBe(0);const line=stock.parts.find(p=>p.id==='screen:real-screen')!.line!;expect(Math.hypot(line[1].x-line[0].x,line[1].y-line[0].y)).toBeCloseTo(81,6);expect(stock.quotes.some(q=>q.includes('HIDEAWAY'))).toBeTruthy();await page.screenshot({path:resolve(proof,'desktop-stock-screen.png')});
});
