import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckAgentApi,AgentCommand} from '../src/features/deckcraft/designer/deckAgentController';
import type {PresetLibrary} from '../src/features/deckcraft/designer/contractorPresets';
const proof=resolve(process.cwd(),'../../outputs/deckcraft-contractor-review/presets');mkdirSync(proof,{recursive:true});
const modal=(page:Page)=>page.getByRole('dialog',{name:'Contractor presets',exact:true});
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const library=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('golden-maple.deck-studio.contractor-presets.v1')??'null') as PresetLibrary|null);
let sequence=0;
async function command(page:Page,commands:AgentCommand[]){const result=await page.evaluate(async({commands,id})=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;return api.execute({id,expectedRevision:api.read().revision,commands});},{commands,id:`preset-qa-${++sequence}`});if(!result.ok)throw Error(JSON.stringify(result));return result;}
async function open(page:Page){await page.getByRole('button',{name:'Presets',exact:true}).click();await expect(modal(page)).toBeVisible();await expect(modal(page).getByRole('button',{name:'Close contractor presets',exact:true})).toBeFocused();}
async function save(page:Page,name:string,privatePricing=false){await modal(page).getByRole('textbox',{name:'Preset name',exact:true}).fill(name);if(privatePricing)await modal(page).getByRole('checkbox',{name:/^Include contractor pricing/}).check();await modal(page).getByRole('button',{name:'Save preset',exact:true}).click();await expect(modal(page).getByRole('heading',{name,exact:true})).toBeVisible();}
test.beforeEach(async({context,page})=>{await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{localStorage.setItem('golden-maple.deck-studio.deck-only.v1',JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},{...DEFAULT_DECK,customerName:'Preset QA customer',projectAddress:'Preset QA address'});await context.route('**/*',r=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(r.request().url())&&r.request().method()==='GET'?r.continue():r.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);});

for(const phone of [false,true])test.describe(phone?'phone exact preset apply':'desktop exact preset apply',()=>{if(phone)test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});test(`${phone?'@phone ':''}saved specifications preserve job geometry, previews apply exact pricing once and undo restores the job`,async({page})=>{
 await command(page,[{type:'design.patch',patch:{framingSize:'2x12',joistSpacing:12,autoLighting:{posts:true,stairs:true},underDeck:{drainage:'dryspace',ceiling:'none',scope:'main',gravel:true,gravelDepthIn:3,floorMesh:true}}}]);const savedJob=await state(page);await open(page);await save(page,'Composite builder standard');expect((await state(page)).design).toEqual(savedJob.design);const stored=(await library(page))!;expect(stored.presets).toHaveLength(1);for(const key of ['width','length','height','deckOutlines','boardLayout','customerName','lightingSystem','privacyScreens','yardFeatures'])expect(Object.hasOwn(stored.presets[0].settings,key)).toBe(false);await modal(page).getByRole('button',{name:'Close',exact:true}).click();
 await command(page,[{type:'design.patch',patch:{framingSize:'2x8',joistSpacing:16,width:22,length:14,height:42,autoLighting:{posts:false,stairs:false},underDeck:{drainage:'none',ceiling:'none',scope:'main',gravel:false,gravelDepthIn:3,floorMesh:false}}}]);const before=await state(page);await open(page);await modal(page).getByRole('button',{name:'Review on current job',exact:true}).click();await expect(modal(page).getByRole('status',{name:'Preset price comparison'})).toBeVisible();expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);await expect(modal(page).getByRole('region',{name:'Preset setting changes'})).toContainText('Framing lumber');await expect(modal(page).getByRole('heading',{name:'Quote requirements after applying'})).toBeVisible();
 const preview=await modal(page).getByRole('status',{name:'Preset price comparison'}).innerText();const expected=await page.evaluate(async()=>{const api=(window as unknown as {deckcraft:DeckAgentApi}).deckcraft;const {presets}=JSON.parse(localStorage.getItem('golden-maple.deck-studio.contractor-presets.v1')!);const patch=Object.fromEntries(Object.entries(presets[0].settings).filter(([,v])=>v!==null));return api.preview({id:'preset-expected',expectedRevision:api.read().revision,commands:[{type:'design.patch',patch}]});});expect(expected.ok).toBe(true);if(!expected.ok)throw Error(JSON.stringify(expected));expect(preview).toContain(Math.round(expected.snapshot.pricing.total).toLocaleString('en-CA'));await page.screenshot({path:resolve(proof,`${phone?'phone':'desktop'}-preset-price-review.png`)});await modal(page).getByRole('button',{name:'Apply preset',exact:true}).click();await expect(modal(page)).toBeHidden();const after=await state(page);expect(after.design.width).toBe(22);expect(after.design.length).toBe(14);expect(after.design.height).toBe(42);expect(after.design.framingSize).toBe('2x12');expect(after.pricing.total).toBe(expected.snapshot.pricing.total);expect(after.design.lightingSystem.selectedItems).toEqual(expected.snapshot.design.lightingSystem.selectedItems);expect(after.quotes).toEqual(expected.snapshot.quotes);await command(page,[{type:'history.undo'}]);expect((await state(page)).design).toEqual(before.design);expect((await state(page)).pricing).toEqual(before.pricing);writeFileSync(resolve(proof,`${phone?'phone':'desktop'}-preview-apply-price.json`),JSON.stringify({before:before.pricing,expected:expected.snapshot.pricing,after:after.pricing},null,2));
});});

test('local private pricing is opt-in and portable export/import preserves strict library CRUD',async({page})=>{
 const initial=await state(page);await open(page);await save(page,'Owner standard',true);const stored=(await library(page))!;expect(stored.presets[0].pricing).toBeTruthy();await expect(modal(page).getByRole('checkbox',{name:/^Apply saved contractor pricing/})).not.toBeChecked();await modal(page).locator('summary').filter({hasText:'Library files'}).click();const download=page.waitForEvent('download');await modal(page).getByRole('button',{name:'Export portable library',exact:true}).click();const file=await download,stream=await file.createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();const portable=JSON.parse(text);expect(portable.presets[0].pricing).toBeUndefined();expect(text).not.toContain('materialMarkup');expect(text).not.toContain('customOverrides');expect(text).not.toContain('Preset QA customer');
 await modal(page).locator('summary').filter({hasText:'Rename or remove this preset'}).click();await modal(page).getByRole('textbox',{name:'New preset name',exact:true}).fill('Renamed standard');await modal(page).getByRole('button',{name:'Rename preset',exact:true}).click();expect((await library(page))!.presets[0].name).toBe('Renamed standard');await modal(page).getByRole('button',{name:'Delete preset',exact:true}).click();expect((await library(page))!.presets).toHaveLength(0);
 await modal(page).getByLabel('Import contractor preset library',{exact:true}).setInputFiles({name:'portable.json',mimeType:'application/json',buffer:Buffer.from(text)});expect((await library(page))!.presets).toHaveLength(1);expect((await library(page))!.presets[0].pricing).toBeUndefined();await modal(page).getByLabel('Import contractor preset library',{exact:true}).setInputFiles({name:'duplicate.json',mimeType:'application/json',buffer:Buffer.from(text)});await expect(modal(page).getByRole('alert')).toContainText('duplicate');expect((await library(page))!.presets).toHaveLength(1);await modal(page).getByLabel('Import contractor preset library',{exact:true}).setInputFiles({name:'private.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(stored))});await expect(modal(page).getByRole('alert')).toContainText('private contractor pricing');const invalid=structuredClone(portable);invalid.presets[0].settings.width=99;await modal(page).getByLabel('Import contractor preset library',{exact:true}).setInputFiles({name:'unknown-field.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await expect(modal(page).getByRole('alert')).toContainText('unsupported field width');expect((await library(page))!.presets).toHaveLength(1);expect((await state(page)).design).toEqual(initial.design);expect((await state(page)).pricing).toEqual(initial.pricing);await page.keyboard.press('Escape');await expect(modal(page)).toBeHidden();await expect(page.getByRole('button',{name:'Presets',exact:true})).toBeFocused();await page.reload();await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);await open(page);await expect(modal(page).getByRole('button',{name:/^Owner standard/})).toBeVisible();
});

test.describe('phone contractor presets',()=>{test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});test('@phone library controls, stale preview protection and errors fit without overflow',async({page})=>{
 const original=await state(page);await open(page);await save(page,'Phone builder standard');await modal(page).getByRole('button',{name:'Review on current job',exact:true}).click();await expect(modal(page).getByRole('button',{name:'Apply preset',exact:true})).toBeDisabled();await command(page,[{type:'design.patch',patch:{framingSize:'2x12'}}]);await expect(modal(page).getByRole('alert')).toContainText('current job changed');await expect(modal(page).getByRole('button',{name:'Apply preset',exact:true})).toBeDisabled();await modal(page).getByRole('button',{name:'Review again',exact:true}).click();await expect(modal(page).getByRole('button',{name:'Apply preset',exact:true})).toBeEnabled();const priceBounds=await modal(page).getByRole('status',{name:'Preset price comparison'}).boundingBox(),headerBounds=await modal(page).locator('.dd-presets-header').boundingBox(),footerBounds=await modal(page).locator('.dd-presets-footer').boundingBox();expect(priceBounds!.y).toBeGreaterThanOrEqual(headerBounds!.y+headerBounds!.height);expect(priceBounds!.y+priceBounds!.height).toBeLessThanOrEqual(footerBounds!.y);await expect(modal(page).getByRole('heading',{name:'Phone builder standard',exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);expect(await modal(page).evaluate(el=>el.scrollWidth-el.clientWidth)).toBe(0);for(const name of ['Close contractor presets','Save preset','Apply preset']){const b=await modal(page).getByRole('button',{name,exact:true}).boundingBox();expect(b!.width).toBeGreaterThanOrEqual(44);expect(b!.height).toBeGreaterThanOrEqual(44);}await modal(page).getByRole('status',{name:'Preset price comparison'}).scrollIntoViewIfNeeded();await page.screenshot({path:resolve(proof,'phone-preset-review.png')});await modal(page).getByRole('button',{name:'Close',exact:true}).click();await command(page,[{type:'history.undo'}]);expect((await state(page)).design).toEqual(original.design);
});});
