import {test,expect,type Page,type Locator} from '@playwright/test';
import {pickPlanTool,savedConfiguration} from './nav';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {yardShapeWorldPoints,yardShapeRunIn} from '../src/features/deckcraft/yardShapeEditing';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import type {DeckAgentApi} from '../src/features/deckcraft/designer/deckAgentController';
const proof=resolve(process.cwd(),'../../outputs/deckcraft-yard-shape-review');mkdirSync(proof,{recursive:true});
const patio:YardFeature={id:'qa-patio',kind:'patio',name:'QA patio',enabled:true,xFt:6,zFt:26,widthFt:12,depthFt:10,heightIn:0,rotationDeg:0,productId:'permacon-melville',color:'#aaa69b'};
const wall:YardFeature={id:'qa-wall',kind:'retaining-wall',name:'QA wall',enabled:true,xFt:22,zFt:36,widthFt:16,depthFt:1,heightIn:24,rotationDeg:0,productId:'segmental-concrete',color:'#aaa69b'};
const fixture:DeckData={...DEFAULT_DECK,houseVisible:false,deckType:'Freestanding',stairFlights:0,railingType:'None',yardFeatures:[patio,wall],customerName:'Yard shape QA',projectAddress:'Local review fixture'};
const state=(page:Page)=>page.evaluate(()=>(window as unknown as {deckcraft:DeckAgentApi}).deckcraft.read());
const controls=(page:Page)=>page.getByLabel('Patio and wall shape controls',{exact:true});
const feature=(data:Pick<DeckData,'yardFeatures'>,id:string)=>data.yardFeatures!.find(f=>f.id===id)!;
async function ready(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {deckcraft?:DeckAgentApi}).deckcraft?.read().ready??false)).toBe(true);return state(page);}
async function activate(page:Page,el:Locator,touch=false){await el.scrollIntoViewIfNeeded();if(touch){const b=(await el.boundingBox())!;expect(b.width).toBeGreaterThanOrEqual(44);expect(b.height).toBeGreaterThanOrEqual(44);await el.tap();}else await el.click();}
async function open(page:Page,touch=false){await pickPlanTool(page,'Patios & walls');if(touch){const b=await page.getByRole('radio',{name:'Patios & walls',exact:true}).boundingBox();expect(b!.width).toBeGreaterThanOrEqual(44);expect(b!.height).toBeGreaterThanOrEqual(44);}await expect(controls(page)).toBeVisible();}
async function cursor(page:Page,points:{x:number;y:number}[],touch=false){const svg=page.locator('.dd-yard-shape-editor>svg');await svg.scrollIntoViewIfNeeded();for(const p of points){const at=await svg.evaluate((el,p)=>{const matrix=(el as SVGSVGElement).getScreenCTM()!,q=new DOMPoint(p.x,p.y).matrixTransform(matrix);return {x:q.x,y:q.y};},p);if(touch)await page.touchscreen.tap(at.x,at.y);else await page.mouse.click(at.x,at.y);}}
async function drag(page:Page,handle:Locator,dx:number,dy:number,touch=false){const saved=await state(page);await handle.evaluate(el=>el.scrollIntoView({block:'center',inline:'nearest'}));const b=(await handle.boundingBox())!,origin={x:b.x+b.width/2,y:b.y+b.height/2},matrix=await page.locator('.dd-yard-shape-editor>svg').evaluate(el=>{const m=(el as SVGSVGElement).getScreenCTM()!;return {a:m.a,d:m.d};});const target={x:origin.x+dx*matrix.a,y:origin.y+dy*matrix.d};
 if(touch){const hit=await page.evaluate(p=>{const el=document.elementFromPoint(p.x,p.y);return {hit:el?.outerHTML,viewport:{w:innerWidth,h:innerHeight},scroll:scrollY,stack:document.elementsFromPoint(p.x,p.y).slice(0,7).map(el=>({tag:el.tagName,class:el.className,label:el.getAttribute('aria-label')}))};},origin);writeFileSync(resolve(proof,'phone-drag-hit.json'),JSON.stringify({origin,target,box:b,hit},null,2));expect(hit.stack[0]?.label).toBe(await handle.getAttribute('aria-label'));const cdp=await page.context().newCDPSession(page);try{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...origin,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:(origin.x+target.x)/2,y:(origin.y+target.y)/2,id:1}]});expect((await state(page)).design).toEqual(saved.design);expect((await state(page)).pricing).toEqual(saved.pricing);expect((await state(page)).history).toEqual(saved.history);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...target,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}finally{await cdp.detach();}}
 else{await page.mouse.move(origin.x,origin.y);await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:5});expect((await state(page)).design).toEqual(saved.design);expect((await state(page)).pricing).toEqual(saved.pricing);expect((await state(page)).history).toEqual(saved.history);await page.mouse.up();}}
const caught=new WeakMap<Page,string[]>();
test.beforeEach(async({page,context})=>{const errors:string[]=[];caught.set(page,errors);page.on('pageerror',e=>errors.push(e.message));await context.addInitScript('window.__name=(target,value)=>target;');await context.addInitScript(configuration=>{const key='golden-maple.deck-studio.deck-only.v1';if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration}));},fixture);await context.route('**/*',route=>/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(route.request().url())&&['GET','HEAD'].includes(route.request().method())?route.continue():route.fulfill({status:200,body:''}));await page.goto('/deck-designer/');await ready(page);});
test.afterEach(async({page},info)=>{expect(caught.get(page)??[]).toEqual([]);writeFileSync(resolve(proof,`${info.project.name}-${info.title.replace(/[^a-z0-9]+/gi,'-')}-errors.json`),JSON.stringify({status:info.status,errors:caught.get(page)??[]},null,2));});

for(const touch of [false,true])test(`${touch?'@phone ':''}patio point and edge pulls preserve products, commit once, Undo and save exact shape`,async({page})=>{
 await open(page,touch);const initial=await state(page);await drag(page,page.getByRole('button',{name:'QA patio point 3',exact:true}),18.25,12.5,touch);await expect.poll(async()=>feature((await state(page)).design,'qa-patio').outline?.length).toBe(4);const changed=await ready(page),p=feature(changed.design,'qa-patio'),before=yardShapeWorldPoints(patio),after=yardShapeWorldPoints(p);expect(after[2].x).toBeCloseTo(before[2].x+18.25,2);expect(after[2].y).toBeCloseTo(before[2].y+12.5,2);for(const i of [0,1,3]){expect(after[i].x).toBeCloseTo(before[i].x,5);expect(after[i].y).toBeCloseTo(before[i].y,5);}expect(p.productId).toBe(patio.productId);expect(changed.pricing.total).not.toBe(initial.pricing.total);
 await activate(page,page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(initial.design);await activate(page,page.getByRole('button',{name:'Redo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(changed.design);
 const point=page.getByRole('button',{name:'QA patio point 3',exact:true});await point.focus();await point.press('Shift+ArrowRight');const keyboard=await ready(page);expect(yardShapeWorldPoints(feature(keyboard.design,'qa-patio'))[2].x).toBeCloseTo(after[2].x+12,4);await controls(page).getByRole('button',{name:'Add midpoint',exact:true}).click();await expect.poll(async()=>feature((await state(page)).design,'qa-patio').outline?.length).toBe(5);const added=await ready(page);await page.getByRole('button',{name:'QA patio point 4',exact:true}).focus();await page.getByRole('button',{name:'QA patio point 4',exact:true}).press('Delete');await expect.poll(async()=>feature((await state(page)).design,'qa-patio').outline?.length).toBe(4);await activate(page,page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(added.design);
 await expect.poll(async()=>(await savedConfiguration(page))?.yardFeatures?.find((f:{id:string})=>f.id==='qa-patio')?.outline?.length).toBe(5);await page.reload();await ready(page);expect(feature((await state(page)).design,'qa-patio')).toEqual(feature(added.design,'qa-patio'));await open(page,touch);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-editable-patio.png`),fullPage:true});
});

for(const touch of [false,true])test(`${touch?'@phone ':''}draw patio and L wall through real cursor, finish and retain editable dimensions`,async({page})=>{
 await open(page,touch);const initial=await state(page);await activate(page,controls(page).getByRole('button',{name:'Draw patio',exact:true}),touch);await expect(page.locator('.dd-yard-shape-editor')).toHaveAttribute('data-drawing','true');await cursor(page,[{x:192,y:216},{x:300,y:216},{x:300,y:336},{x:192,y:336}],touch);expect((await state(page)).design).toEqual(initial.design);
 if(touch)await activate(page,controls(page).getByRole('button',{name:'Finish shape',exact:true}),true);else{const svg=page.locator('.dd-yard-shape-editor>svg'),b=(await svg.boundingBox())!;await page.mouse.click(b.x+b.width/2,b.y+b.height/2,{button:'right'});}
 await expect.poll(async()=>(await state(page)).design.yardFeatures?.length).toBe(3);const withPatio=await ready(page),drawn=withPatio.design.yardFeatures!.at(-1)!;expect(drawn.kind).toBe('patio');expect(drawn.outline).toHaveLength(4);expect(drawn.widthFt).toBeCloseTo(9,4);expect(drawn.depthFt).toBeCloseTo(10,4);await activate(page,page.getByRole('button',{name:'Undo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(initial.design);await activate(page,page.getByRole('button',{name:'Redo',exact:true}),touch);await expect.poll(async()=>(await state(page)).design).toEqual(withPatio.design);
 await activate(page,controls(page).getByRole('button',{name:'Draw wall path',exact:true}),touch);await cursor(page,[{x:192,y:348},{x:300,y:348},{x:300,y:408}],touch);expect((await state(page)).design).toEqual(withPatio.design);if(touch)await activate(page,controls(page).getByRole('button',{name:'Finish path',exact:true}),true);else{const svg=page.locator('.dd-yard-shape-editor>svg'),b=(await svg.boundingBox())!;await page.mouse.click(b.x+b.width/2,b.y+b.height/2,{button:'right'});}
 await expect.poll(async()=>(await state(page)).design.yardFeatures?.length).toBe(4);const withWall=await ready(page),newWall=withWall.design.yardFeatures!.at(-1)!;expect(newWall.wallPath).toHaveLength(3);expect(newWall.widthFt).toBeCloseTo(14,4);expect(yardShapeRunIn(newWall.wallPath!)/12).toBeCloseTo(14,4);
 await controls(page).getByLabel('Yard measured edge',{exact:true}).selectOption('1');await controls(page).getByLabel('Yard edge length',{exact:true}).fill('7');await activate(page,controls(page).getByRole('button',{name:'Apply edge dimension',exact:true}),touch);await expect.poll(async()=>feature((await state(page)).design,newWall.id).widthFt).toBeCloseTo(16,4);const dimensioned=await ready(page);expect(feature(dimensioned.design,newWall.id).wallPath).toHaveLength(3);
 await controls(page).locator('summary').filter({hasText:'Overall dimensions'}).click();await controls(page).getByLabel('Wall shape total run',{exact:true}).fill('20');await controls(page).getByLabel('Wall shape thickness',{exact:true}).fill('0.25');await activate(page,controls(page).getByRole('button',{name:'Apply overall dimensions',exact:true}),touch);await expect.poll(async()=>feature((await state(page)).design,newWall.id).widthFt).toBeCloseTo(20,4);expect(feature((await state(page)).design,newWall.id).depthFt).toBe(.25);expect(feature((await state(page)).design,newWall.id).wallPath).toHaveLength(3);
 await page.screenshot({path:resolve(proof,`${touch?'phone':'desktop'}-drawn-L-wall.png`),fullPage:true});await controls(page).getByRole('button',{name:'Delete selected feature',exact:true}).click();await expect.poll(async()=>(await state(page)).design.yardFeatures?.length).toBe(3);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(async()=>(await state(page)).design.yardFeatures?.length).toBe(4);
});

test('yard drawing cancellation and invalid crossing never update pricing or history',async({page})=>{
 await open(page);const initial=await state(page);await controls(page).getByRole('button',{name:'Draw patio',exact:true}).click();await cursor(page,[{x:192,y:216},{x:300,y:336},{x:300,y:216},{x:192,y:336}]);await controls(page).getByRole('button',{name:'Finish shape',exact:true}).click();await expect(controls(page).getByRole('status')).toContainText(/cross|clear|outline/i);expect((await state(page)).design).toEqual(initial.design);expect((await state(page)).pricing).toEqual(initial.pricing);expect((await state(page)).history).toEqual(initial.history);await controls(page).getByRole('button',{name:'Cancel drawing',exact:true}).click();
 await controls(page).getByRole('button',{name:'Draw wall path',exact:true}).click();await cursor(page,[{x:192,y:348},{x:300,y:348}]);await controls(page).getByRole('button',{name:'Cancel drawing',exact:true}).click();expect((await state(page)).design).toEqual(initial.design);expect((await state(page)).history).toEqual(initial.history);
});
