import {createRequire} from 'node:module';
import path from 'node:path';
const fs = createRequire(import.meta.url)('node:fs');
const destination = process.env.E2E_OUTPUTS ? path.resolve(process.env.E2E_OUTPUTS) : '';
function rewrite(target){
  if(!destination || typeof target !== 'string') return target;
  const absolute = path.resolve(target);
  if(absolute === destination || absolute.startsWith(destination + path.sep)) return target;
  const parts = absolute.split(path.sep);
  if(parts.includes('test-results')) return target;
  const index = parts.lastIndexOf('outputs');
  if(index < 0) return target;
  return path.join(destination, ...parts.slice(index + 1));
}
function wrap(fn, thisArg){
  return function(first, ...rest){ return fn.call(thisArg, rewrite(first), ...rest); };
}
export const appendFile = wrap(fs.appendFile, fs);
export const appendFileSync = wrap(fs.appendFileSync, fs);
export const access = wrap(fs.access, fs);
export const accessSync = wrap(fs.accessSync, fs);
export const chown = fs.chown;
export const chownSync = fs.chownSync;
export const chmod = fs.chmod;
export const chmodSync = fs.chmodSync;
export const close = fs.close;
export const closeSync = fs.closeSync;
export const copyFile = fs.copyFile;
export const copyFileSync = fs.copyFileSync;
export const cp = fs.cp;
export const cpSync = fs.cpSync;
export const createReadStream = fs.createReadStream;
export const createWriteStream = wrap(fs.createWriteStream, fs);
export const exists = fs.exists;
export const existsSync = wrap(fs.existsSync, fs);
export const fchown = fs.fchown;
export const fchownSync = fs.fchownSync;
export const fchmod = fs.fchmod;
export const fchmodSync = fs.fchmodSync;
export const fdatasync = fs.fdatasync;
export const fdatasyncSync = fs.fdatasyncSync;
export const fstat = fs.fstat;
export const fstatSync = fs.fstatSync;
export const fsync = fs.fsync;
export const fsyncSync = fs.fsyncSync;
export const ftruncate = fs.ftruncate;
export const ftruncateSync = fs.ftruncateSync;
export const futimes = fs.futimes;
export const futimesSync = fs.futimesSync;
export const glob = fs.glob;
export const globSync = fs.globSync;
export const lchown = fs.lchown;
export const lchownSync = fs.lchownSync;
export const lchmod = fs.lchmod;
export const lchmodSync = fs.lchmodSync;
export const link = fs.link;
export const linkSync = fs.linkSync;
export const lstat = wrap(fs.lstat, fs);
export const lstatSync = wrap(fs.lstatSync, fs);
export const lutimes = fs.lutimes;
export const lutimesSync = fs.lutimesSync;
export const mkdir = wrap(fs.mkdir, fs);
export const mkdirSync = wrap(fs.mkdirSync, fs);
export const mkdtemp = fs.mkdtemp;
export const mkdtempSync = fs.mkdtempSync;
export const open = wrap(fs.open, fs);
export const openSync = wrap(fs.openSync, fs);
export const openAsBlob = fs.openAsBlob;
export const readdir = wrap(fs.readdir, fs);
export const readdirSync = wrap(fs.readdirSync, fs);
export const read = fs.read;
export const readSync = fs.readSync;
export const readv = fs.readv;
export const readvSync = fs.readvSync;
export const readFile = wrap(fs.readFile, fs);
export const readFileSync = wrap(fs.readFileSync, fs);
export const readlink = fs.readlink;
export const readlinkSync = fs.readlinkSync;
export const realpath = fs.realpath;
export const realpathSync = fs.realpathSync;
export const rename = fs.rename;
export const renameSync = fs.renameSync;
export const rm = wrap(fs.rm, fs);
export const rmSync = wrap(fs.rmSync, fs);
export const rmdir = wrap(fs.rmdir, fs);
export const rmdirSync = wrap(fs.rmdirSync, fs);
export const stat = wrap(fs.stat, fs);
export const statfs = fs.statfs;
export const statSync = wrap(fs.statSync, fs);
export const statfsSync = fs.statfsSync;
export const symlink = fs.symlink;
export const symlinkSync = fs.symlinkSync;
export const truncate = fs.truncate;
export const truncateSync = fs.truncateSync;
export const unwatchFile = fs.unwatchFile;
export const unlink = wrap(fs.unlink, fs);
export const unlinkSync = wrap(fs.unlinkSync, fs);
export const utimes = fs.utimes;
export const utimesSync = fs.utimesSync;
export const watch = fs.watch;
export const watchFile = fs.watchFile;
export const writeFile = wrap(fs.writeFile, fs);
export const writeFileSync = wrap(fs.writeFileSync, fs);
export const write = fs.write;
export const writeSync = fs.writeSync;
export const writev = fs.writev;
export const writevSync = fs.writevSync;
export const Dirent = fs.Dirent;
export const Stats = fs.Stats;
export const ReadStream = fs.ReadStream;
export const WriteStream = fs.WriteStream;
export const FileReadStream = fs.FileReadStream;
export const FileWriteStream = fs.FileWriteStream;
export const _toUnixTimestamp = fs._toUnixTimestamp;
export const Dir = fs.Dir;
export const opendir = fs.opendir;
export const opendirSync = fs.opendirSync;
export const F_OK = fs.F_OK;
export const R_OK = fs.R_OK;
export const W_OK = fs.W_OK;
export const X_OK = fs.X_OK;
export const constants = fs.constants;
const promiseWrap = new Set(["mkdir","mkdirSync","writeFile","writeFileSync","appendFile","appendFileSync","open","openSync","createWriteStream","rm","rmSync","rmdir","rmdirSync","unlink","unlinkSync","existsSync","stat","statSync","lstat","lstatSync","access","accessSync","readFile","readFileSync","readdir","readdirSync"]);
export const promises = new Proxy(fs.promises, { get(target, prop, receiver){ const value = Reflect.get(target, prop, receiver); if(typeof prop === 'string' && promiseWrap.has(prop) && typeof value === 'function') return wrap(value, target); return value; } });
export default { appendFile, appendFileSync, access, accessSync, chown, chownSync, chmod, chmodSync, close, closeSync, copyFile, copyFileSync, cp, cpSync, createReadStream, createWriteStream, exists, existsSync, fchown, fchownSync, fchmod, fchmodSync, fdatasync, fdatasyncSync, fstat, fstatSync, fsync, fsyncSync, ftruncate, ftruncateSync, futimes, futimesSync, glob, globSync, lchown, lchownSync, lchmod, lchmodSync, link, linkSync, lstat, lstatSync, lutimes, lutimesSync, mkdir, mkdirSync, mkdtemp, mkdtempSync, open, openSync, openAsBlob, readdir, readdirSync, read, readSync, readv, readvSync, readFile, readFileSync, readlink, readlinkSync, realpath, realpathSync, rename, renameSync, rm, rmSync, rmdir, rmdirSync, stat, statfs, statSync, statfsSync, symlink, symlinkSync, truncate, truncateSync, unwatchFile, unlink, unlinkSync, utimes, utimesSync, watch, watchFile, writeFile, writeFileSync, write, writeSync, writev, writevSync, Dirent, Stats, ReadStream, WriteStream, FileReadStream, FileWriteStream, _toUnixTimestamp, Dir, opendir, opendirSync, F_OK, R_OK, W_OK, X_OK, constants, promises };
