import {useEffect,useRef,useState} from 'react';
import './architectWorkspace.css';
import {useArchitectKeys,revealControl} from './architectKeys';
export default function ArchitectShortcuts(){
 const help=useRef<HTMLDialogElement>(null),focusButton=useRef<HTMLButtonElement>(null),[focused,setFocused]=useState(true);
 useEffect(()=>{const root=focusButton.current?.closest('.deck-designer');root?.setAttribute('data-drawing-focus',String(focused));return()=>root?.removeAttribute('data-drawing-focus');},[focused]);
 useArchitectKeys({'f1':()=>{if(!help.current?.open)help.current?.showModal();}},true,true);
 useArchitectKeys({'ctrl+s':()=>document.querySelector<HTMLButtonElement>('[data-architect-save]')?.click(),'ctrl+o':()=>document.querySelector<HTMLButtonElement>('[data-architect-open]')?.click(),'ctrl+n':()=>revealControl(document.querySelector('[data-architect-new]'))});
 return <><button ref={focusButton} type="button" className="dd-secondary dd-drawing-focus-toggle" aria-pressed={focused} aria-label={focused?'Show project controls':'Focus drawing'} onClick={()=>setFocused(v=>!v)}>{focused?'Project controls':'Focus drawing'}</button><button type="button" className="dd-secondary" title="Keyboard shortcuts (F1)" onClick={()=>help.current?.showModal()}>Keyboard shortcuts · F1</button><dialog ref={help} className="dd-properties-sheet dd-workspace-inspector" aria-label="Keyboard shortcuts"><div className="dd-inspector-top"><button type="button" className="dd-inspector-back" onClick={()=>help.current?.close()}>Close shortcuts</button><h2>Realtime Landscaping Architect keys</h2></div><div className="dd-section-body"><p>Only the bindings listed here are active. Shortcuts apply to the active tool. Typing in fields keeps normal text shortcuts.</p><dl>{[
 ['Ctrl+S / Ctrl+O','Save a design file / import a design'],['Ctrl+N','Open the new-design confirmation'],['Ctrl+Z / Ctrl+Shift+Z','Undo / redo'],['Z','Fit the plan or sketch'],['T or M','Move tool (3D or sketch)'],['R / S','Rotate / scale selected objects in 3D'],['E','Point editing (deck, landscape or 3D)'],['A / L / N','Select all / similar / none in Select parts; N also clears the main selection'],['Ctrl+A','Toggle angle snapping while drawing a patio, Designer shape or Sketch'],['Ctrl+G / G','Toggle snapping / open snap settings in Designer tools or 3D'],['Enter','Exact length and angle while drawing'],['O / H / Ctrl+E','Round / bevel / offset settings in Designer shape tools'],['J','Open the selected object’s properties'],['Backspace / Escape','Remove the last drawing point / cancel'],['Delete','Delete the focused point or selected sketch shape'],['Right-click','Finish an outline'],['Shift','Keep the current drawing angle (your custom behavior)'],['Mouse wheel / middle drag','Zoom / pan the plan']
 ].map(([key,text])=><div key={key}><dt><kbd>{key}</kbd></dt><dd>{text}</dd></div>)}</dl><p>Clipboard, render-order, viewpoint and environment shortcuts are not mapped yet. Some browser-reserved keys may be intercepted by the browser; the visible controls remain available.</p><a href="https://ideaspectrum.com/help/realtime/keyboard-shortcuts.html" target="_blank" rel="noreferrer">Official shortcut reference</a></div></dialog></>;
}
