import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {DeckData} from '../types';
import {dollars} from '../designFacts';
import {DECKING_CATALOGUE,RAILING_CATALOGUE} from '../manufacturerRuntimeCatalogue';
import {colourName,parseColourRef} from '../boardFinishes';
import {DRAINAGE_OPTIONS,CEILING_OPTIONS} from '../underDeckOptions';
import {captureContractorPreset,contractorPresetPatch,emptyPresetLibrary,exportPresetLibrary,mergePresetLibraries,parsePresetLibrary,parsePresetText,previewContractorPreset,PRESET_LIMITS,PRESET_STORAGE_KEY,type ContractorPreset,type PresetLibrary} from './contractorPresets';
import './contractorPresets.css';

const stamp=(v:unknown)=>JSON.stringify(v);
const fieldNames:Record<string,string>={framingSize:'Framing lumber',joistSpacing:'Joist spacing',foundation:'Foundation',foundationDepthIn:'Illustrative foundation depth',deckingMaterial:'Decking collection',deckingColor:'Decking colour',boardWidth:'Board width',fasteningSystem:'Fastening',pattern:'Board pattern',pictureFrameRows:'Border rows',borderFinish:'Border finish',pictureFrameOverhangIn:'Border overhang',deckFinishes:'Part finishes',railingType:'Railing',catalogueRailingId:'Railing system',glassMount:'Glass mounting',glassFinish:'Glass hardware finish',skirting:'Skirting specification',autoLighting:'Automatic lighting',lightingZoneEnabled:'Lighting zones',lightingSystem:'Lighting quantities derived for this job',underDeck:'Under-deck work',hasDrainage:'Drainage enabled',materialMarkup:'Private material markup',customLaborCost:'Private labour allowance',customOverrides:'Private line overrides'};
function words(value:unknown,key?:string):string{if(value===null||value===undefined)return 'Default / off';if(typeof value==='boolean')return value?'On':'Off';if(typeof value==='string'){if(parseColourRef(value))return colourName(value);if(key==='deckingMaterial')return DECKING_CATALOGUE.find(m=>m.id===value)?.name??value;if(key==='catalogueRailingId')return RAILING_CATALOGUE.find(m=>m.id===value)?.name??value;if(key==='drainage'&&Object.hasOwn(DRAINAGE_OPTIONS,value))return DRAINAGE_OPTIONS[value as keyof typeof DRAINAGE_OPTIONS];if(key==='ceiling'&&Object.hasOwn(CEILING_OPTIONS,value))return CEILING_OPTIONS[value as keyof typeof CEILING_OPTIONS];return value;}if(typeof value==='number')return `${value}${['joistSpacing','boardWidth','foundationDepthIn','pictureFrameOverhangIn'].includes(key??'')?' in':key==='materialMarkup'?'%':''}`;if(Array.isArray(value))return value.map(v=>words(v)).join('; ')||'None';return Object.entries(value as Record<string,unknown>).map(([k,v])=>`${k.replace(/([A-Z])/g,' $1')}: ${words(v,k)}`).join(' · ')||'Default';}
function loadLibrary(){try{const text=localStorage.getItem(PRESET_STORAGE_KEY);return {library:text?parsePresetText(text,false):emptyPresetLibrary(),error:''};}catch(error){return {library:emptyPresetLibrary(),error:`The saved library could not be opened. ${error instanceof Error?error.message:''} Import a valid backup or save a new library to replace it.`};}}

type Preview=ReturnType<typeof previewContractorPreset>;
/** This library is private and independent from each job. Only Apply changes the host design. */
export default function ContractorPresets({data,onApply,onClose}:{data:DeckData;onApply:(patch:Partial<DeckData>)=>void;onClose:()=>void}){
 const [initial]=useState(loadLibrary),[library,setLibrary]=useState<PresetLibrary>(initial.library),[selected,setSelected]=useState(initial.library.presets[0]?.id??''),[name,setName]=useState(''),[rename,setRename]=useState(initial.library.presets[0]?.name??''),[savePricing,setSavePricing]=useState(false),[applyPricing,setApplyPricing]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(initial.error),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const dialog=useRef<HTMLDivElement>(null),close=useRef<HTMLButtonElement>(null),file=useRef<HTMLInputElement>(null),dataRef=useRef(data),closeRef=useRef(onClose);dataRef.current=data;closeRef.current=onClose;
 const preset=library.presets.find(p=>p.id===selected),stale=!!preview&&preview.stamp!==stamp(data);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeRef.current();return;}if(e.key==='Tab'){const nodes=[...dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),summary,[tabindex="0"]')??[]].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{if(!preview)return;const main=dialog.current?.querySelector<HTMLElement>('.dd-presets-review'),heading=main?.querySelector<HTMLElement>('.dd-presets-review-heading h3');if(main)main.scrollTop=0;heading?.scrollIntoView({block:'start'});heading?.focus({preventScroll:true});},[preview]);
 useEffect(()=>{if(error||stale)dialog.current?.querySelector<HTMLElement>('.dd-presets-error')?.scrollIntoView({block:'nearest'});},[error,stale]);
 const persist=(next:PresetLibrary):boolean=>{try{const checked=parsePresetLibrary(next);localStorage.setItem(PRESET_STORAGE_KEY,JSON.stringify(checked));setLibrary(checked);setError('');return true;}catch(error){setError(`Library not saved. ${error instanceof Error?error.message:'Device storage is unavailable.'} Your current job is unchanged.`);return false;}};
 const choose=(id:string)=>{setSelected(id);setPreview(null);setApplyPricing(false);setRename(library.presets.find(p=>p.id===id)?.name??'');setError('');setNotice('');};
 const save=()=>{setSaving(true);try{const next=captureContractorPreset(dataRef.current,name,savePricing);if(persist({...library,presets:[...library.presets,next]})){setSelected(next.id);setRename(next.name);setName('');setSavePricing(false);setApplyPricing(false);setPreview(null);setNotice(`Saved “${next.name}”. The current job is unchanged.`);}}catch(error){setError(error instanceof Error?error.message:'This specification could not be saved.');}finally{setSaving(false);}};
 const review=()=>{if(!preset)return;try{setPreview(previewContractorPreset(dataRef.current,preset,applyPricing));setError('');setNotice('Review the setting changes and quote requirements before applying.');}catch(error){setPreview(null);setError(error instanceof Error?error.message:'This preset is incompatible with the current job.');}};
 const apply=()=>{if(!preview||preview.stamp!==stamp(dataRef.current)){setError('The current job changed. Review the preset again before applying.');return;}if(!preview.changes.length){setNotice('This job already uses these settings.');return;}try{onApply(preview.patch);}catch(error){setError(error instanceof Error?error.message:'The preset could not be applied. Your library remains saved; review the job and try again.');}};
 const exportLibrary=()=>{try{const text=exportPresetLibrary(library),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Golden-Maple-contractor-presets.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Portable library exported. Private contractor prices are excluded.');}catch(error){setError(error instanceof Error?error.message:'Could not export the library.');}};
 const importLibrary=async(value:File|undefined)=>{if(!value)return;try{if(value.size>PRESET_LIMITS.bytes)throw Error('Choose a preset library smaller than 100 KB.');const imported=parsePresetText(await value.text());if(persist(mergePresetLibraries(library,imported))){setNotice(`Imported ${imported.presets.length} specifications. The current job is unchanged.`);setPreview(null);}}catch(error){setError(error instanceof Error?error.message:'This file is not a supported preset library.');}finally{if(file.current)file.current.value='';}};
 if(typeof document==='undefined')return null;
 return createPortal(<div className="dd-presets-backdrop"><div className="dd-presets" role="dialog" aria-modal="true" aria-labelledby="dd-presets-title" ref={dialog}>
  <header className="dd-presets-header"><div><span>Golden Maple · Build specifications</span><h2 id="dd-presets-title">Contractor presets</h2><p>Keep your preferred build details. Review them on every job.</p></div><button ref={close} type="button" onClick={onClose} aria-label="Close contractor presets">×</button></header>
  <div className="dd-presets-body"><aside className="dd-presets-library" aria-label="Saved contractor presets"><div className="dd-presets-library-title"><h3>Your specifications</h3><span>{library.presets.length} / {PRESET_LIMITS.count}</span></div>{!library.presets.length?<p className="dd-presets-empty">Save this job’s build settings to start your reusable library.</p>:<div className="dd-presets-list">{library.presets.map(p=><button key={p.id} type="button" aria-pressed={selected===p.id} onClick={()=>choose(p.id)}><strong>{p.name}</strong><span>{words(p.settings.deckingMaterial,'deckingMaterial')} · {p.settings.framingSize}</span>{p.pricing&&<small>Private pricing saved</small>}</button>)}</div>}
   <section className="dd-presets-save"><h3>Save current specification</h3><label>Preset name<input value={name} maxLength={PRESET_LIMITS.name} placeholder="e.g. Composite · aluminum rail" onChange={e=>setName(e.target.value)}/></label><label className="dd-presets-check"><input type="checkbox" checked={savePricing} onChange={e=>setSavePricing(e.target.checked)}/><span>Include contractor pricing<small>Optional private markup, labour and line overrides. Saved only on this device; excluded from export.</small></span></label><button type="button" className="dd-presets-primary" disabled={saving||!name.trim()||library.presets.length>=PRESET_LIMITS.count} onClick={save}>Save preset</button><p>Job dimensions, locations, customer details, manually placed lights and board edits are not saved in a preset.</p></section>
   <details className="dd-presets-files"><summary>Library files</summary><button type="button" disabled={!library.presets.length} onClick={exportLibrary}>Export portable library</button><button type="button" onClick={()=>file.current?.click()}>Import preset library</button><input type="file" ref={file} hidden accept=".json,application/json" aria-label="Import contractor preset library" onChange={e=>void importLibrary(e.target.files?.[0])}/><p>Imports add specifications. Duplicate names or identifiers are rejected; your saved library remains intact.</p></details>
  </aside><main className="dd-presets-review" aria-label="Preset review">{preset?<><div className="dd-presets-review-heading"><span>Reusable build specification</span><h3 tabIndex={-1}>{preset.name}</h3><p>The current job keeps its shape, placement, site details and board edits.</p></div><details className="dd-presets-manage"><summary>Rename or remove this preset</summary><label>New preset name<input value={rename} maxLength={PRESET_LIMITS.name} onChange={e=>setRename(e.target.value)}/></label><div><button type="button" onClick={()=>{if(persist({...library,presets:library.presets.map(p=>p.id===preset.id?{...p,name:rename}:p)}))setNotice('Preset renamed.');}}>Rename preset</button><button type="button" className="dd-presets-delete" onClick={()=>{if(persist({...library,presets:library.presets.filter(p=>p.id!==preset.id)})){setSelected('');setPreview(null);setNotice('Preset removed from this device.');}}}>Delete preset</button></div></details>
   {preset.pricing&&<label className="dd-presets-check dd-presets-private"><input type="checkbox" checked={applyPricing} onChange={e=>{setApplyPricing(e.target.checked);setPreview(null);}}/><span>Apply saved contractor pricing<small>Off by default. Review any quantity or line-cost overrides for this job.</small></span></label>}
   {!preview?<><dl className="dd-presets-specs">{Object.entries(preset.settings).filter(([,v])=>v!==null).map(([key,value])=><div key={key}><dt>{fieldNames[key]??key}</dt><dd>{words(value,key)}</dd></div>)}</dl><button type="button" className="dd-presets-primary" onClick={review}>Review on current job</button></>:<><div className="dd-presets-prices" role="status" aria-label="Preset price comparison"><div><span>Current priced portion</span><strong>{dollars(preview.current.total)}</strong><small>{preview.current.quoteRequired.length} quote items</small></div><div><span>With this preset</span><strong>{dollars(preview.estimate.total)}</strong><small>{preview.estimate.quoteRequired.length} quote items · CAD incl. HST</small></div></div><p className="dd-presets-price-note">{preview.estimate.quoteRequired.length?'These totals cover priced work. The listed quote items remain additional.':'Planning estimate; final scope and site conditions still require review.'}</p>
    <section className="dd-presets-changes" aria-label="Preset setting changes"><h4>{preview.changes.length} setting changes</h4>{preview.changes.length?preview.changes.map(c=><div key={c.key}><strong>{fieldNames[c.key]??c.key}</strong><span>Current: {words(c.before,c.key)}</span><span>Preset: {words(c.after,c.key)}</span></div>):<p>This job already uses these settings.</p>}</section>
    <section className="dd-presets-quotes"><h4>Quote requirements after applying</h4>{preview.estimate.quoteRequired.length?<ul>{preview.estimate.quoteRequired.map(q=><li key={q}>{q}</li>)}</ul>:<p>No unpriced quote items in this estimate.</p>}<details><summary>Current quote requirements</summary>{preview.current.quoteRequired.length?<ul>{preview.current.quoteRequired.map(q=><li key={q}>{q}</li>)}</ul>:<p>No unpriced quote items.</p>}</details></section>
    <details className="dd-presets-details"><summary>Construction and site checks</summary><ul>{preview.issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul></details><details className="dd-presets-details"><summary>Full resulting price schedule</summary>{preview.estimate.sections.map(s=><section key={s.title}><h4>{s.title} · {s.quoteRequired&&s.total===0?'Quote required':dollars(s.total)+(s.quoteRequired?' + quote':'')}</h4>{s.items.filter(i=>i.qty!==0).map((i,k)=><p key={k}><span>{i.name}<small>{i.spec} · {i.qty} {i.unit}</small></span><strong>{i.cost===null?'Quote required':dollars(i.cost)}</strong></p>)}</section>)}</details>
   </>}
  </>:<div className="dd-presets-intro"><span>Repeat the specification, keep the job.</span><h3>A consistent starting point.</h3><p>Save your framing, finishes, railing, lighting intent and under-deck preferences. Then choose a saved specification to compare settings and prices on this job.</p><p>Every application keeps the current dimensions, outlines, stairs, customer details, site conditions and yard layout.</p></div>}{error&&<div className="dd-presets-error" role="alert">{error}</div>}{stale&&<div className="dd-presets-error" role="alert">The current job changed. Review this preset again before applying.</div>}</main></div>
  <footer className="dd-presets-footer"><p role="status">{notice||'Your library stays on this device. Only Apply changes the current job.'}</p><div>{preview&&<button type="button" onClick={review}>Review again</button>}<button type="button" onClick={onClose}>Close</button>{preview&&<button type="button" className="dd-presets-primary" disabled={stale||!preview.changes.length} onClick={apply}>Apply preset</button>}</div></footer>
 </div></div>,document.body);
}
