import {useRef,useState} from 'react';
import ConstructionPlan from '../ConstructionPlan';
import {describeDesign,dollars,type DeckEstimate} from '../designFacts';
import type {DeckData} from '../types';
import {priceBookLabel} from '../priceBook';
import {estimateConfidence} from './estimateConfidence';
import {CUSTOMER_COMPARISON_CSS,customerComparisonDocument} from './customerComparisonDocument';
export interface CustomerOption {name:string;data:DeckData;estimate:DeckEstimate}
export function CustomerOptionSheet({left,right}:{left:CustomerOption;right:CustomerOption}){
 const delta=right.estimate.total-left.estimate.total;
 return <article className="customer-options" aria-label="Customer design options"><header><small>DeckCraft · Design comparison</small><h1>Choose the space that fits.</h1><p>Two versions of your project, with their current scope and planning estimates.</p></header><div className="options-grid">{[left,right].map((option,index)=>{const facts=describeDesign(option.data,option.estimate),confidence=estimateConfidence(option.estimate);return <section className="option-card" key={index}><h2>{option.name}</h2><div className="option-plan"><ConstructionPlan model={option.estimate.model} data={option.data} yard={option.estimate.yardModel} variant="site"/></div><strong className="option-price">{dollars(option.estimate.total)}</strong><p>{option.estimate.quoteRequired.length?'Priced portion':'Planning estimate'} · CAD including HST</p><p>{option.estimate.area.toFixed(1)} sq ft of deck</p><h3>Selected design</h3><ul>{facts.proposalFacts.map((fact,i)=><li key={i}>{fact.replace(/\b\d+\.\d{3,}\b/g,n=>String(Math.round(Number(n)*100)/100))}</li>)}</ul><h3>Price basis</h3><p>Confirmed scope: {dollars(confidence.totals.confirmed)}<br/>Planning allowances: {dollars(confidence.totals.allowance)}<br/>Before HST. Allowances require confirmation.</p><h3>Additional scope to confirm</h3>{option.estimate.quoteRequired.length?<ul>{option.estimate.quoteRequired.map(q=><li key={q}>{q}</li>)}</ul>:<p>No unpriced scope is listed. Site review and a written quote are still required.</p>}</section>;})}</div><section className="decision-note"><h2>What the difference means</h2><p>{right.name} is {dollars(Math.abs(delta))} {delta>=0?'more':'less'} than {left.name} for the currently priced portion, including HST. Unpriced work can change this difference.</p><p>Choose a preferred direction, then confirm measurements, product availability, delivery, site conditions and any engineering requirements before a written quote.</p></section><footer>{priceBookLabel()} · Planning estimates only. Not a contract, construction approval or final quotation. Concept layouts show the selected design; colours and materials require sample confirmation.</footer></article>;
}
export default function CustomerOptionPresentation({left,right,stale}:{left:CustomerOption;right:CustomerOption;stale:boolean}){
 const content=useRef<HTMLDivElement>(null),[status,setStatus]=useState('');
 const download=()=>{if(stale||!content.current)return;const url=URL.createObjectURL(new Blob([customerComparisonDocument(content.current.innerHTML)],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='DeckCraft-design-options.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Customer comparison downloaded. Open it in a browser to print or save as PDF.');};
 return <details><summary>Customer presentation</summary><p>Review both options below. The downloaded presentation includes the displayed plans, selections and selling prices. Private cost records, supplier references and margin controls are excluded. Custom design labels remain visible.</p><button type="button" disabled={stale} onClick={download}>Download customer comparison</button>{stale&&<p>Compare again after changes before downloading.</p>}{status&&<p role="status">{status}</p>}<style>{CUSTOMER_COMPARISON_CSS.split('@media print')[0]}</style><div ref={content}><CustomerOptionSheet left={left} right={right}/></div></details>;
}
