import type {ElevationProfile} from '../elevationProfiles';
import {useEffect,useRef,useState} from 'react';
import type {DeckData,YardFeature} from '../types';
import {yardSurfaceIn} from '../yardElevations';
import {editYardFinished,type YardFinishedEdit} from '../yardFinishedEdits';
import {exactWallRunIn} from '../yardFinishedSettings';
function ProfilePreview({before,after}:{before:ElevationProfile;after:ElevationProfile}){const values=[...before.points,...after.points].flatMap(p=>[p.existingIn,p.proposedIn,p.finishedIn,p.formationIn]).filter((v):v is number=>v!==null&&Number.isFinite(v));if(!values.length)return null;const lo=Math.min(...values),hi=Math.max(...values),width=Math.max(1,after.lengthIn),height=Math.max(hi-lo+12,width/3),offset=(height-hi+lo)/2;const segments=(profile:ElevationProfile,key:'finishedIn'|'proposedIn'|'formationIn')=>{const chunks:string[]=[];let points:string[]=[];for(const p of profile.points){const value=p[key];if(value===null){if(points.length)chunks.push(points.join(' '));points=[];}else points.push(`${p.stationIn},${hi-value+offset}`);}if(points.length)chunks.push(points.join(' '));return chunks;};return <figure><figcaption>{after.spec.name} · equal horizontal/vertical inches · dashed = current; red = proposed finished top; green = proposed ground; brown = formation</figcaption><svg role="img" aria-label={`Geometry preview: ${after.spec.name}`} viewBox={`0 0 ${width} ${height}`} style={{width:'100%',maxHeight:160}}>{segments(before,'finishedIn').map((p,i)=><polyline key={`b${i}`} points={p} fill="none" stroke="#64748b" strokeWidth="2" strokeDasharray="5 3" vectorEffect="non-scaling-stroke"/>)}{(['proposedIn','formationIn','finishedIn'] as const).map((key,k)=>segments(after,key).map((p,i)=><polyline key={`${key}${i}`} points={p} fill="none" stroke={['#327044','#9c6d39','#b43c2f'][k]} strokeWidth="2" vectorEffect="non-scaling-stroke"/>))}</svg></figure>;}
const shown=(v:number)=>Number.isFinite(v)?String(Math.round(v*1000)/1000):'';
export default function FinishedLevelEditor({data,feature:f,onChange,disabled=false}:{data:DeckData;feature:YardFeature;onChange:(f:YardFeature)=>void;disabled?:boolean}){
 const [level,setLevel]=useState(shown(yardSurfaceIn(data,f))),[slope,setSlope]=useState(shown(Math.hypot(f.patioSlope?.xPct??0,f.patioSlope?.zPct??0))),[direction,setDirection]=useState(shown(Math.atan2(-(f.patioSlope?.zPct??0),-(f.patioSlope?.xPct??0))*180/Math.PI)),[steps,setSteps]=useState((f.wallTopSteps??[]).map(p=>`${shown(p.stationIn)}, ${shown(p.elevationIn)}`).join('\n')),[candidate,setCandidate]=useState<YardFeature>(),[summary,setSummary]=useState<string[]>([]),[profiles,setProfiles]=useState<{before:ElevationProfile;after:ElevationProfile}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const levelLabel=f.kind==='retaining-wall'?'Reference cap top (first run)':'Finished top at centre';
 const revision=useRef(data);revision.current=data;const candidateRevision=useRef(data),previewIntent=useRef(0);
 const clearPreview=()=>{previewIntent.current++;setCandidate(undefined);setSummary([]);setProfiles([]);setError('');setBusy(false);};
 useEffect(()=>{previewIntent.current++;setLevel(shown(yardSurfaceIn(data,f)));setSlope(shown(Math.hypot(f.patioSlope?.xPct??0,f.patioSlope?.zPct??0)));setDirection(shown(Math.atan2(-(f.patioSlope?.zPct??0),-(f.patioSlope?.xPct??0))*180/Math.PI));setSteps((f.wallTopSteps??[]).map(p=>`${shown(p.stationIn)}, ${shown(p.elevationIn)}`).join('\n'));setCandidate(undefined);setSummary([]);setBusy(false);},[data,f]);
 const preview=async(edit:YardFinishedEdit)=>{const source=data,intent=++previewIntent.current;try{const next=editYardFinished(source,f,edit);setBusy(true);setError('');setCandidate(undefined);const [{buildYardTakeoff},{buildYardModel},{buildDeckTakeoff},{elevationProfileSpecs,buildElevationProfile}]=await Promise.all([import('../yardTakeoff'),import('../yardModel'),import('../deckTakeoff'),import('../elevationProfiles')]);if(revision.current!==source||intent!==previewIntent.current)return;const nextData={...source,yardFeatures:source.yardFeatures?.map(p=>p.id===f.id?next:p)},beforeModel=buildYardModel(source,buildDeckTakeoff(source)),afterModel=buildYardModel(nextData,buildDeckTakeoff(nextData)),before=buildYardTakeoff(source,beforeModel),after=buildYardTakeoff(nextData,afterModel),a=before.quantities,b=after.quantities;const beforeSpecs=elevationProfileSpecs(source);setProfiles(elevationProfileSpecs(nextData).filter(spec=>spec.featureId===f.id).map(spec=>({before:buildElevationProfile(source,beforeSpecs.find(p=>p.id===spec.id)!,beforeModel),after:buildElevationProfile(nextData,spec,afterModel)})));candidateRevision.current=source;setCandidate(next);setSummary([`${f.kind==='retaining-wall'?'Reference cap top (first run)':'Finished centre'}: ${shown(yardSurfaceIn(source,f))} → ${shown(next.finishedElevationIn!)} in · project datum`,...(['excavationYd3','baseYd3','beddingYd3','raisedFillYd3','backfillYd3','geogridPlanningOrderSqft'] as const).map(k=>`${k.replace(/([A-Z])/g,' $1')}: ${shown(a[k]??0)} → ${shown(b[k]??0)} ${k.endsWith('Sqft')?'sq ft':'cu yd'}`),`Known priced scope: $${(before.knownGrandTotalCents/100).toFixed(2)} → $${(after.knownGrandTotalCents/100).toFixed(2)} incl. HST${after.quoteRequired?' · unresolved scope still requires inputs':''}`,...after.warnings]);}catch(e){if(revision.current===source&&intent===previewIntent.current)setError((e as Error).message);}finally{if(revision.current===source&&intent===previewIntent.current)setBusy(false);}};
 return <section aria-label="Fixed finished elevation" className="dd-finished-level"><p><strong>{f.finishedElevationIn===undefined?'Legacy: follows ground':'Fixed finished elevation'}</strong> · all levels in inches from the project datum. Ground changes affect burial and quantities; fixed tops stay in place.</p>
 {f.finishedElevationIn===undefined&&<button type="button" disabled={disabled||busy||!Number.isFinite(yardSurfaceIn(data,f))} onClick={()=>void preview({action:'pin'})}>Preview conversion to fixed level</button>}
 <form onSubmit={e=>{e.preventDefault();void preview({action:'level',elevationIn:Number(level)});}}><label>{levelLabel}<input aria-label="Fixed finished top elevation" required value={level} onChange={e=>{clearPreview();setLevel(e.target.value);}} disabled={disabled} type="number" step="any"/></label><button disabled={disabled||busy}>Preview finished level</button></form>
 {f.kind==='patio'&&<form onSubmit={e=>{e.preventDefault();const pct=Number(slope),a=Number(direction)*Math.PI/180;if(pct<0||pct>30||!Number.isFinite(a)){setError('Enter slope 0–30% and a finite fall direction.');return;}void preview({action:'slope',xPct:-pct*Math.cos(a),zPct:-pct*Math.sin(a)});}}><label>Slope %<input aria-label="Patio slope percent" type="number" required min="0" max="30" step="any" disabled={disabled} value={slope} onChange={e=>{clearPreview();setSlope(e.target.value);}}/></label><label>Fall direction °<input aria-label="Patio fall direction" type="number" required step="any" disabled={disabled} value={direction} onChange={e=>{clearPreview();setDirection(e.target.value);}}/><small>Local axes: 0° across right; 90° out. Rotates with patio.</small></label><button disabled={disabled||busy}>Preview patio slope</button></form>}
 {f.kind==='retaining-wall'&&<p>The reference top is the first wall run. Changing it moves every stepped run by the same amount.</p>}
 {f.kind==='retaining-wall'&&<form onSubmit={e=>{e.preventDefault();try{const parsed=steps.trim()?steps.trim().split('\n').map(line=>{const p=line.split(',').map(t=>t.trim());if(p.length!==2||p.some(t=>!t))throw Error('Use station inches, top elevation inches on each line.');return {stationIn:Number(p[0]),elevationIn:Number(p[1])};}):[];void preview({action:'steps',steps:parsed});}catch(e){setError((e as Error).message);}}}><label>Wall top steps<textarea aria-label="Wall top steps" rows={3} disabled={disabled} value={steps} onChange={e=>{clearPreview();setSteps(e.target.value);}}/><small>Station inches, top elevation inches · path {shown(exactWallRunIn(f))} in. Increasing stations; whole stock course height differences.</small></label><button disabled={disabled||busy}>Preview wall top steps</button></form>}
 {busy&&<p role="status">Calculating geometry and quantities…</p>}{error&&<p role="alert">{error}</p>}{candidate&&<div aria-label="Finished level preview">{profiles.map(p=><ProfilePreview key={p.after.spec.id} before={p.before} after={p.after}/>)}<ul>{summary.map((s,i)=><li key={i}>{s}</li>)}</ul><button type="button" disabled={disabled||busy} onClick={()=>{if(revision.current!==candidateRevision.current){setError('Design changed. Preview this operation again.');setCandidate(undefined);return;}try{onChange(candidate);setCandidate(undefined);}catch(e){setError((e as Error).message);}}}>Apply preview</button><button type="button" onClick={clearPreview}>Discard preview</button></div>}
 </section>;
}
