import {useEffect,useRef,type PointerEvent} from 'react';
import type {PlanFrame} from '../ConstructionPlan';
import {isObjectVisible} from '../editorOrganization';
import type {DeckData} from '../types';
import type {YardModel} from '../yardModel';
import type {HardscapeSelection} from './selectionState';
import {boxSelection,matchesHardscape} from './hardscapeSelection';
export default function HardscapePlanSelection({model,frame,selection,onSelect,inspection=false,organization}:{model:YardModel;frame:PlanFrame;selection?:HardscapeSelection;onSelect:(s:HardscapeSelection)=>void;inspection?:boolean;organization?:DeckData['editorOrganization']}){
 const pointers=useRef(new Set<number>()),tap=useRef<{id:number;x:number;y:number;max:number;target:HardscapeSelection}|null>(null),multiple=useRef(false);
 useEffect(()=>{const down=(e:globalThis.PointerEvent)=>{pointers.current.add(e.pointerId);if(pointers.current.size>1){multiple.current=true;tap.current=null;}else multiple.current=false;};const up=(e:globalThis.PointerEvent)=>pointers.current.delete(e.pointerId);document.addEventListener('pointerdown',down,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',up,true);return ()=>{document.removeEventListener('pointerdown',down,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',up,true);};},[]);
 const down=(e:PointerEvent,target:HardscapeSelection)=>{if(multiple.current)return;tap.current={id:e.pointerId,x:e.clientX,y:e.clientY,max:0,target};};
 const move=(e:PointerEvent)=>{const t=tap.current;if(t?.id===e.pointerId)t.max=Math.max(t.max,Math.hypot(e.clientX-t.x,e.clientY-t.y));};
 const end=(e:PointerEvent)=>{const t=tap.current;pointers.current.delete(e.pointerId);tap.current=null;if(t?.id===e.pointerId&&!multiple.current&&t.max<5&&Math.hypot(e.clientX-t.x,e.clientY-t.y)<5)onSelect(t.target);};
 const solids=model.boxes.filter(b=>isObjectVisible(organization,b.featureId)&&b.polygon&&(['stone-step','wall-cap','wall-block','paver'].includes(b.role)||inspection&&['base','bedding','backfill'].includes(b.role))).sort((a,b)=>a.y+a.h/2-b.y-b.h/2);
 return <svg className="dd-hardscape-plan-picks" viewBox={frame.viewBox} aria-label="Select landscape objects" style={{position:'absolute',inset:0,width:'100%',height:'100%',pointerEvents:'none'}} onPointerMove={move} onPointerUp={end} onPointerCancel={e=>{pointers.current.delete(e.pointerId);tap.current=null;}}>{solids.map(b=>{const pick=boxSelection(b),selected=matchesHardscape(selection,pick);return <polygon key={b.id} points={b.polygon!.map(p=>`${p.x},${p.y}`).join(' ')} fill={selected?'#d9902f':'transparent'} fillOpacity={selected?.2:1} stroke={selected?'#d9902f':'none'} strokeWidth={selected?2:0} vectorEffect="non-scaling-stroke" style={{pointerEvents:'visibleFill'}} onPointerDown={e=>down(e,pick)}><title>{b.stonePart??b.role}{b.stepRow!==undefined?` · row ${b.stepRow+1}`:''}</title></polygon>;})}{(model as YardModel&{pools?:import('../poolModel').PoolFeatureModel[]}).pools?.filter(p=>p.config.enabled&&isObjectVisible(organization,p.config.id)).flatMap(p=>p.openingFootprints.map((opening,index)=><polygon key={p.config.id+index} points={opening.map(v=>`${v.x},${v.y}`).join(' ')} fill="transparent" style={{pointerEvents:'visibleFill'}} onPointerDown={e=>down(e,{kind:'pool',id:p.config.id,part:'basin'})}><title>{p.config.name}</title></polygon>))}</svg>;
}
