import InlayPresetPreview from './InlayPresetPreview';
import {lazy,Suspense,useEffect,useLayoutEffect,useRef,useState,type PointerEvent,type RefObject} from 'react';
import {createPortal} from 'react-dom';
import type {DeckData,DeckInlay} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import type {PlanFrame} from '../ConstructionPlan';
import type {PlanPoint} from '../lib/deckGeometry';
import {contrastColour} from '../boardFinishes';
import {INLAY_PRESETS,createInlayPreset} from '../lib/inlayPresets';
import {nextInlayId,planInlays,levelInlayContext} from '../lib/inlayGeometry';
import {editInlayPatch,inlayCentre,inlayLevelAt,inlayPlanLevel,moveInlayPatch,placeInlayPatch,removeInlayPatch} from './inlayActions';
import type {Update} from './fields';
import InlayEditor from './InlayEditor';
import './inlayPlanEditor.css';
const InlaySketchEditor=lazy(()=>import('../sketch/InlaySketchEditor'));
type Drag={id:string;pointer:number;start:PlanPoint;dx:number;dy:number;patch?:Partial<DeckData>;error:string;moved:boolean};
const xy=(p:PlanPoint[])=>p.map(q=>`${q.x},${q.y}`).join(' ');

export default function InlayPlanEditor({data,model,update,viewportFrame:frame,viewZoom=1,toolbar,pendingInlay,onPendingInlay,onStatus}:{data:DeckData;model:DeckTakeoff;update:Update;viewportFrame:PlanFrame;viewZoom?:number;toolbar?:RefObject<HTMLElement|null>;pendingInlay?:DeckInlay|null;onPendingInlay?:(inlay:DeckInlay|null)=>void;onStatus?:(s:string)=>void}){
 const [localPending,setLocalPending]=useState<DeckInlay|null>(null),[selectedId,setSelectedId]=useState(data.inlays?.[0]?.id??''),[message,setMessage]=useState(''),[bad,setBad]=useState(false),[drawing,setDrawing]=useState(false),[editingCustomId,setEditingCustomId]=useState(''),[live,setLive]=useState<Drag|null>(null),[preview,setPreview]=useState<{points:PlanPoint[][];bad:boolean}|null>(null),[size,setSize]=useState({w:0,h:0});
 const armed=onPendingInlay?pendingInlay??null:localPending,box=useRef<HTMLDivElement>(null),drag=useRef<Drag|null>(null),tap=useRef<{pointer:number;point:PlanPoint;x:number;y:number}|null>(null),pointers=useRef(new Set<number>());
 const selected=data.inlays?.find(i=>i.id===selectedId)??data.inlays?.[0];
 const announce=(s:string,error=false)=>{setMessage(s);setBad(error);onStatus?.(s);};
 const pending=(i:DeckInlay|null)=>{if(onPendingInlay)onPendingInlay(i);else setLocalPending(i);setPreview(null);};
 const cancelDrag=()=>{drag.current=null;tap.current=null;setLive(null);};
 const cancel=()=>{cancelDrag();pending(null);setPreview(null);announce('Inlay placement cancelled. The saved design is unchanged.');};
 useLayoutEffect(()=>{const el=box.current;if(!el)return;const measure=()=>setSize({w:el.clientWidth,h:el.clientHeight});measure();const ro=new ResizeObserver(measure);ro.observe(el);return()=>ro.disconnect();},[]);
 useEffect(()=>{cancelDrag();setPreview(null);},[data]);
 useEffect(()=>{const down=(e:globalThis.PointerEvent)=>{pointers.current.add(e.pointerId);if(pointers.current.size>1)cancelDrag();};const up=(e:globalThis.PointerEvent)=>pointers.current.delete(e.pointerId);document.addEventListener('pointerdown',down,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',up,true);return()=>{document.removeEventListener('pointerdown',down,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',up,true);};},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&(armed||drag.current)){e.preventDefault();cancel();}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[armed]);
 const worldAt=(e:{clientX:number;clientY:number})=>{const matrix=box.current?.querySelector('svg')?.getScreenCTM();if(!matrix)throw Error('Wait for the plan to load.');const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return {x:p.x,y:p.y};};
 const attempt=(fn:()=>void)=>{try{fn();}catch(e){announce(e instanceof Error?e.message:'The inlay edit could not be applied.',true);}};
 const save=(patch:Partial<DeckData>)=>{if(JSON.stringify(patch.inlays)===JSON.stringify(data.inlays))return;update(patch);announce('Inlay updated. Undo restores the previous design.');};
 const arm=(i:DeckInlay)=>{cancelDrag();pending(i);announce('Tap anywhere on a deck level to place this inlay. Escape cancels.');};
 const add=(id:string)=>attempt(()=>{if((data.inlays?.length??0)>=8)throw Error('A design holds up to 8 inlays.');arm(createInlayPreset(id,nextInlayId(data.inlays??[]),contrastColour(data)));});
 const placement=(world:PlanPoint,commit=false)=>{
  if(!armed)return;const hit=inlayLevelAt(model,world),level=inlayPlanLevel(model,hit?.level??armed.level??1);if(!level){setPreview(null);if(commit)announce('Tap an existing deck level. Placement is still active.',true);return;}
  const point=hit?.point??{x:world.x-level.offset.x,y:world.y-level.offset.z},c=inlayCentre(level,{...armed,...(armed.kind==='band'?{atFt:0}:{dxFt:0,dyFt:0})} as DeckInlay),candidate={...armed,level:hit?.level??armed.level??1,...(armed.kind==='band'?{atFt:(armed.direction==='along'?point.x-c.x:point.y-c.y)/12}:{dxFt:(point.x-c.x)/12,dyFt:(point.y-c.y)/12})} as DeckInlay;
  const raw=planInlays([candidate],levelInlayContext(data,level),{boards:false})[0],polys=raw.pieces.map(poly=>poly.map(p=>({x:p.x+level.offset.x,y:p.y+level.offset.z})));
  try{if(!hit)throw Error('Tap inside a deck level.');const patch=placeInlayPatch(data,model,armed,hit.level,hit.point);setPreview({points:polys,bad:false});if(commit){const placed=patch.inlays!.at(-1)!;update(patch);setSelectedId(placed.id);pending(null);announce('Inlay placed where you tapped. Drag it to reposition; Undo removes this placement.');}else if(bad)announce('This position fits. Tap to place the inlay.');}
  catch(e){setPreview({points:polys,bad:true});announce(`${(e as Error).message}${commit?' Placement is still active; choose another position or a smaller size.':''}`,true);}
 };
 const down=(id:string)=>(e:PointerEvent)=>{if(armed||drawing||e.pointerType==='mouse'&&e.button!==0||pointers.current.size>1)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);setSelectedId(id);const g:Drag={id,pointer:e.pointerId,start:worldAt(e),dx:0,dy:0,error:'',moved:false};drag.current=g;setLive(g);};
 const move=(e:PointerEvent)=>{const g=drag.current;if(!g||g.pointer!==e.pointerId)return;e.preventDefault();const p=worldAt(e),dx=p.x-g.start.x,dy=p.y-g.start.y;let patch:Partial<DeckData>|undefined,error='';try{patch=moveInlayPatch(data,model,g.id,dx,dy);}catch(e){error=(e as Error).message;}const next={...g,dx,dy,patch,error,moved:Math.hypot(dx,dy)>.001};drag.current=next;setLive(next);};
 const up=(e:PointerEvent)=>{if(drag.current?.pointer!==e.pointerId)return;move(e);const g=drag.current!;cancelDrag();if(g.error)announce(`${g.error} The saved position is unchanged.`,true);else if(g.moved&&g.patch)save(g.patch);};
 const gesture={onPointerMove:move,onPointerUp:up,onPointerCancel:cancelDrag,onLostPointerCapture:(e:PointerEvent)=>{if(drag.current?.pointer===e.pointerId)cancelDrag();}};
 const keys=(id:string)=>(e:React.KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();cancel();return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();attempt(()=>save(removeInlayPatch(data,id)));return;}const d=({ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]} as Record<string,number[]>)[e.key];if(d){e.preventDefault();e.stopPropagation();attempt(()=>save(moveInlayPatch(data,model,id,d[0]*(e.shiftKey?12:1),d[1]*(e.shiftKey?12:1))));}};
 const scale=Math.min(size.w/frame.w,size.h/frame.h),ox=(size.w-frame.w*scale)/2,oy=(size.h-frame.h*scale)/2,at=(p:PlanPoint,gap=0)=>({left:ox+(p.x-frame.x)*scale,top:oy+(p.y-frame.y)*scale-gap/viewZoom,transform:`translate(-50%,-50%) scale(${1/viewZoom})`});
 const edited=armed?{...data,inlays:[...(data.inlays??[]),armed]}:data;
 const settingsUpdate:Update=patch=>attempt(()=>{if(armed){const next=patch.inlays?.find(i=>i.id===armed.id);if(next)pending(next);return;}if(!selected)return;const next=patch.inlays?.find(i=>i.id===selected.id);save(next?editInlayPatch(data,model,selected.id,next):removeInlayPatch(data,selected.id));});
 const controls=<div className="dd-inlay-plan-controls" aria-label="Inlay plan controls"><div className="dd-inlay-plan-presets">{INLAY_PRESETS.map(p=><button key={p.id} type="button" title={p.description} onClick={()=>add(p.id)}><InlayPresetPreview presetId={p.id}/><span>Add {p.label.toLowerCase()}</span></button>)}<button type="button" onClick={()=>{setEditingCustomId('');setDrawing(true);}}>Draw custom inlay</button></div>{armed?<div className="dd-inlay-placement" role="status"><strong>Choose a position on the deck</strong><span>Click or tap the desired centre. Invalid positions stay uncommitted.</span><button type="button" onClick={cancel}>Cancel placement</button></div>:<><label>Selected inlay<select aria-label="Selected inlay" value={selected?.id??''} onChange={e=>{cancelDrag();setSelectedId(e.target.value);}}><option value="" disabled>Choose an inlay</option>{(data.inlays??[]).map((i,n)=><option key={i.id} value={i.id}>Inlay {n+1} · {i.kind==='custom'?i.name??'custom':i.kind==='medallion'?i.style:i.kind}</option>)}</select></label>{selected?.kind==='custom'&&<button type="button" onClick={()=>{setEditingCustomId(selected.id);setDrawing(true);}}>Edit custom shape</button>}<p>Drag any inlay or its Move handle. Arrows move 1 inch; Shift moves 1 foot. Delete removes only the selected inlay.</p></>}{(armed||selected)&&<InlayEditor data={edited} model={model} update={settingsUpdate} hideAdd onlyId={(armed??selected)!.id} pending={!!armed}/>}<p role="status" data-invalid={bad||undefined}>{message}</p></div>;
 return <div ref={box} className="dd-inlay-plan-editor" data-placement={!!armed||undefined}><svg viewBox={frame.viewBox} data-plan-editor-ui role="group" aria-label={armed?'Inlay placement surface':'Inlay selection surface'} onPointerDown={e=>{if(!armed||e.pointerType==='mouse'&&e.button!==0||pointers.current.size>1)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);tap.current={pointer:e.pointerId,point:worldAt(e),x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(armed&&pointers.current.size<=1)placement(worldAt(e));}} onPointerUp={e=>{const t=tap.current;tap.current=null;if(t&&t.pointer===e.pointerId&&pointers.current.size<=1&&Math.hypot(e.clientX-t.x,e.clientY-t.y)<=8)placement(worldAt(e),true);}} onPointerCancel={cancelDrag} onLostPointerCapture={()=>{tap.current=null;}}>
  {model.levels.filter(l=>(l.kind??'deck')==='deck').flatMap(level=>(level.inlays??[]).map(plan=>{const selected=plan.id===(data.inlays?.find(i=>i.id===selectedId)??data.inlays?.[0])?.id,source=data.inlays?.find(i=>i.id===plan.id),dx=live?.id===plan.id&&(source?.kind!=='band'||source.direction==='along')?live.dx:0,dy=live?.id===plan.id&&(source?.kind!=='band'||source.direction==='across')?live.dy:0;return plan.pieces.map((poly,k)=><polygon key={`${plan.id}-${k}`} className="dd-inlay-plan-shape" data-selected={selected||undefined} data-invalid={plan.status!=='ok'||live?.id===plan.id&&!!live.error||undefined} points={xy(poly.map(p=>({x:p.x+level.offset.x+dx,y:p.y+level.offset.z+dy})))} role="button" aria-label={`Inlay ${plan.id} outline`} tabIndex={armed?-1:0} onFocus={()=>setSelectedId(plan.id)} onPointerDown={down(plan.id)} {...gesture} onKeyDown={keys(plan.id)}/>);} ))}
  {preview?.points.map((p,i)=><polygon key={i} className="dd-inlay-placement-preview" data-invalid={preview.bad||undefined} points={xy(p)}/>)}
 </svg>{!armed&&scale>0&&(data.inlays??[]).map((i,n)=>{const l=inlayPlanLevel(model,i.level??1);if(!l)return null;const p=inlayCentre(l,i),outline=l.inlays?.find(plan=>plan.id===i.id)?.pieces.flat()??[],top=outline.length?Math.min(...outline.map(q=>q.y)):p.y,dx=live?.id===i.id&&(i.kind!=='band'||i.direction==='along')?live.dx:0,dy=live?.id===i.id&&(i.kind!=='band'||i.direction==='across')?live.dy:0;return <button key={i.id} type="button" data-plan-editor-ui className="dd-inlay-plan-handle" data-selected={i.id===selected?.id||undefined} aria-label={`Move inlay ${n+1}`} aria-pressed={i.id===selected?.id} style={at({x:p.x+l.offset.x+dx,y:top+l.offset.z+dy},28)} onFocus={()=>setSelectedId(i.id)} onPointerDown={down(i.id)} {...gesture} onKeyDown={keys(i.id)}>Move</button>;})}{toolbar?.current?createPortal(controls,toolbar.current):controls}
 {drawing&&<Suspense fallback={<p role="status">Loading custom inlay drawing…</p>}><InlaySketchEditor open initialName={editingCustomId?(data.inlays?.find(i=>i.id===editingCustomId) as Extract<DeckInlay,{kind:'custom'}>|undefined)?.name:undefined} initialPoints={editingCustomId?(data.inlays?.find(i=>i.id===editingCustomId) as Extract<DeckInlay,{kind:'custom'}>|undefined)?.points:undefined} onClose={()=>setDrawing(false)} onComplete={(points,name)=>{if(editingCustomId){const original=data.inlays?.find(i=>i.id===editingCustomId);if(!original||original.kind!=='custom')throw Error('That custom inlay is no longer in the design.');save(editInlayPatch(data,model,original.id,{...original,points,...(name?{name}:{})}));setDrawing(false);}else{setDrawing(false);arm({id:nextInlayId(data.inlays??[]),kind:'custom',points,...(name?{name}:{}),...(contrastColour(data)?{frame:contrastColour(data)}:{})});}}}/></Suspense>}
 </div>;
}
