import {parseStepInstruction} from './stepVoiceCommands';
import type {AgentCommand,AgentRequest,AgentSnapshot} from './deckAgentController';
import {DECKING_CATALOGUE} from '../manufacturerRuntimeCatalogue';
import {colourRef} from '../boardFinishes';
import type {ColourRef} from '../types';
import {parseYardInstruction} from './yardVoiceCommands';
import {parsePoolInstruction} from './poolVoiceCommands';
import {parseSiteInstruction} from './siteVoiceCommands';
export interface YardVoiceSelection {id:string;target:'area'|'edge'|'point';index:number}
export interface AssistedSelection {objectIds?:string[];partIds:string[];boards:{level:number;index:number}[];yard?:YardVoiceSelection;poolId?:string;hardscape?:import('./selectionState').HardscapeSelection}
export type InstructionResult={ok:true;request:AgentRequest;summary:string[]}|{ok:false;clarification:string;localOnly?:boolean};
export {INSTRUCTION_EXAMPLES,YARD_INSTRUCTION_EXAMPLES} from './instructionExamples';
const no=(clarification:string,localOnly=false):InstructionResult=>({ok:false,clarification,localOnly});
const short=(s:string)=>s.trim().toLowerCase().replace(/\s+/g,' ').replace(/[.!]+$/,'');
const NUMBER_WORDS:Record<string,number>={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};
const measuredWords=(s:string)=>s.replace(/\b(twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)[ -](one|two|three|four|five|six|seven|eight|nine)\b/g,(_,a,b)=>String(NUMBER_WORDS[a]+NUMBER_WORDS[b])).replace(/\b(zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)\b(?=\s+(?:feet|foot|ft|inches|inch|in|degrees|degree|deg|percent|panels|by|x)\b)/g,w=>String(NUMBER_WORDS[w]));
const finite=(s:string)=>{const n=Number(s);return Number.isFinite(n)?n:NaN;};
function resolveColour(text:string,snapshot:AgentSnapshot):{ref:ColourRef;label:string}|string {
 const query=short(text),hits=DECKING_CATALOGUE.flatMap(m=>m.colors.filter(c=>short(c.name)===query||short(`${m.name} ${c.name}`)===query||short(`${m.id} ${c.name}`)===query).map(c=>({ref:colourRef(m.id,c.name),label:`${m.name} · ${c.name}`,material:m.id}))),own=hits.filter(h=>h.material===snapshot.design.deckingMaterial);
 const options=own.length===1?own:hits;if(options.length===1)return options[0];return options.length?`That colour belongs to several collections. Name the full collection and colour: ${options.map(h=>h.label).join('; ')}.`:'Use an exact catalogue colour name, optionally preceded by its collection. Open Materials to see available colours.';
}
/** Entire clauses must match. Unsupported words never become a guessed edit or an external action. */
export function parseNaturalLanguageCommands(input:unknown,snapshot:AgentSnapshot,selection:AssistedSelection={partIds:[],boards:[]}):InstructionResult {
 if(typeof input!=='string'||!input.trim()||input.length>600||/[\u0000-\u001f]/.test(input.replace(/\n/g,'')))return no('Enter a short instruction, up to 600 characters.');if(!snapshot.ready)return no('Wait until the design has finished restoring.');
 const clauses=input.split(/;|\n/).map(short).filter(Boolean);if(clauses.length>8)return no('Use at most eight short instructions, separated by semicolons.');
 const commands:AgentCommand[]=[],summary:string[]=[];let editsBoards=false;
 for(let raw of clauses){raw=measuredWords(raw.replace(/^(please |can you |could you )/,'').replace(/^(make|set|change) the /,'$1 ').replace(/\b(?:this|these) (?=stairs?\b)/,'')).replace(/([a-z])(?=\d)/g,'$1 ').replace(/(\d)(?=[a-z])/g,'$1 ');let m:RegExpMatchArray|null;
  const step=parseStepInstruction(raw,snapshot,selection);if(step){if('clarification'in step)return no(step.clarification,true);commands.push(step.command);summary.push(...step.summary);continue;}
  const pool=parsePoolInstruction(raw,snapshot,selection);if(pool){if('clarification'in pool)return no(pool.clarification,true);commands.push(pool.command);summary.push(...pool.summary);continue;}
  const site=parseSiteInstruction(raw,snapshot,selection);if(site){if('clarification'in site)return no(site.clarification,true);commands.push(site.command);summary.push(...site.summary);continue;}
  const yard=parseYardInstruction(raw,snapshot,selection);
  if(yard){if('clarification'in yard)return no(yard.clarification,true);if(clauses.length>1)return no('Review one patio or wall change at a time so the selected edge and construction quantities remain current.',true);commands.push(yard.command);summary.push(...yard.summary);continue;}
  if((m=raw.match(/^rotate (?:this|selected) (?:section|deck level)(?: to)? (-?\d+(?:\.\d+)?) (?:degrees|degree|deg)$/))){if(clauses.length>1)return no('Review a section direction as one separate instruction.');const parts=selection.partIds.map(id=>snapshot.parts.find(p=>p.id===id));if(parts.length!==1||parts[0]?.kind!=='deck'||!parts[0].level)return no('Select exactly one deck level in the plan, then say “rotate this section 45 degrees”.');const level=parts[0].level,boundary=snapshot.boundaries.find(b=>b.level===level),angleDeg=finite(m[1]);if(!boundary)return no('That deck level is not currently present.');if(Math.abs(angleDeg)>360)return no('Board direction must be −360 to 360 degrees.');commands.push({type:'layout.region',region:{id:`instruction-section-${snapshot.revision}-${level}`,level,polygon:boundary.points.map(p=>({...p})),angleDeg}});summary.push(`Deck level ${level}: field boards at ${angleDeg}°. Its outline, border and inlays stay in place.`,`Review actual stock cuts, fitting allowances and support/fastening quote requirements.`);continue;}
  if((m=raw.match(/^(?:make|set|change) (?:the )?deck (?:size (?:to )?)?(\d+(?:\.\d+)?) (?:by|x|×) (\d+(?:\.\d+)?) (?:feet|foot|ft)$/))){const width=finite(m[1]),length=finite(m[2]);if(width<4||width>60||length<4||length>60)return no('Deck width and length must each be 4–60 feet.');commands.push({type:'design.patch',patch:{width,length}});summary.push(`Deck: ${width} ft wide × ${length} ft deep.`);continue;}
  if((m=raw.match(/^(?:make|set|change) (?:deck )?(width|length|depth|height)(?: to)? (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in)$/))){const key=m[1]==='depth'?'length':m[1],value=finite(m[2])*(key==='height'?/^(feet|foot|ft)$/.test(m[3])?12:1:/^(inches|inch|in)$/.test(m[3])?1/12:1);if(value<(key==='height'?8:4)||value>(key==='height'?144:60))return no(key==='height'?'Deck height must be 8–144 inches.':'Deck dimensions must be 4–60 feet.');commands.push({type:'design.patch',patch:{[key]:value}});summary.push(`Deck ${key}: ${value} ${key==='height'?'in':'ft'}.`);continue;}
  if((m=raw.match(/^(?:make|set|change) (?:the )?stairs?(?: width)?(?: to)? (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in)(?: wide)?$/))){const stairWidth=finite(m[1])*(/^(feet|foot|ft)$/.test(m[2])?12:1);if(stairWidth<36||stairWidth>120)return no('Stair width must be 3–10 feet (36–120 inches).');commands.push({type:'design.patch',patch:{stairWidth}});summary.push(`All grade stairs: ${stairWidth} in wide. Existing stair position is retained.`);continue;}
  if((m=raw.match(/^(?:set|change|make) selected (window|door|opening|screen|house) (width|height|depth|bottom|offset|panels)(?: to)? (-?\d+(?:\.\d+)?) ?(feet|foot|ft|inches|inch|in|percent|%|panels)?$/))){if(selection.partIds.length!==1)return no('Select exactly one matching part in the plan, then repeat this instruction.');const part=snapshot.parts.find(p=>p.id===selection.partIds[0]),kind=m[1],field=m[2],value=finite(m[3]),unit=m[4];if(!part||!part.editable||!(kind==='window'||kind==='door'||kind==='opening'?part.kind==='opening':part.kind===kind))return no(`Select an editable ${kind} in the plan first.`);if(kind==='window'||kind==='door'){const opening=snapshot.design.houseConfig?.openings.find(o=>`opening:${o.id}`===part.id);if(opening&&opening.type.toLowerCase()!==kind)return no(`The selected opening is a ${opening.type.toLowerCase()}. Select a ${kind} or say “selected opening”.`);}
   let key:string,n=value;if(field==='offset'){if(part.kind==='house'){if(!unit||!/^(feet|foot|ft|inches|inch|in)$/.test(unit))return no('Specify the selected house position in feet or inches.');key='offsetIn';n=value*(/^(feet|foot|ft)$/.test(unit)?12:1);}else{if(unit!=='percent'&&unit!=='%')return no('Specify offset in percent along its wall or edge.');key='offsetPct';}}
   else if(field==='panels'){if(part.kind!=='screen'||unit&&unit!=='panels'||!Number.isInteger(value))return no('Panel count is available only for a selected stock privacy screen; use a whole number.');key='panels';}
   else{if(!unit||!/^(feet|foot|ft|inches|inch|in)$/.test(unit))return no('Specify feet or inches for a measured dimension.');const inches=value*(/^(feet|foot|ft)$/.test(unit)?12:1);if(part.kind==='opening'){if(!['width','height','bottom'].includes(field))return no('Openings support width, height, bottom height and offset.');key=field==='bottom'?'bottomIn':`${field}In`;n=inches;}else if(part.kind==='screen'){if(!['width','height'].includes(field))return no('Screens support width, height, panel count and offset.');key=field==='width'?'lengthFt':'heightFt';n=inches/12;}else{if(!['width','depth'].includes(field))return no('The selected house supports width, depth and offset in inches through House settings.');key=`${field}Ft`;n=inches/12;}}
   commands.push({type:'component.edit',id:part.id,edit:{action:'update',fields:{[key]:n}}});summary.push(`${part.label}: ${field} ${value}${unit?` ${unit}`:''}. The model will check fit and limits.`);continue;}
  if((m=raw.match(/^(?:rotate|set|change) selected boards?(?: (?:angle|direction))?(?: to)? (-?\d+(?:\.\d+)?) (?:degrees|degree|deg)$/))||/^(?:colour|color|paint) selected boards? (?:to )?.+$/.test(raw)){
   if(editsBoards||clauses.length>1)return no('Review board edits as one separate instruction so the selected pieces cannot change during another geometry edit.');editsBoards=true;if(!selection.boards.length||selection.boards.length>64)return no('Select 1–64 boards in the plan first.');const boards=selection.boards.map(s=>snapshot.boards.find(b=>b.modelLevel===s.level&&b.index===s.index));if(boards.some(b=>!b))return no('Some selected boards are no longer present. Select them again.');const angle=m?finite(m[1]):undefined;if(angle!==undefined&&Math.abs(angle)>360)return no('Board direction must be −360 to 360 degrees.');const colorText=m?undefined:raw.replace(/^(?:colour|color|paint) selected boards? (?:to )?/,''),resolved=colorText?resolveColour(colorText,snapshot):undefined;if(typeof resolved==='string')return no(resolved);
   const targets=boards.map(b=>({modelLevel:b!.modelLevel,index:b!.index}));
   commands.push({type:'layout.boards',targets,idPrefix:`instruction-${snapshot.revision}`,...(angle!==undefined?{angleDeg:angle}:{}),...(resolved?{colour:resolved.ref}:{})});
   summary.push(`${boards.length} selected board${boards.length===1?'':'s'}: ${angle!==undefined?`direction ${angle}°`:resolved?.label}.`,`Review actual cuts, purchased stock and any custom-layout installation/support quote items.`);continue;
  }
  return no('I could not match that whole instruction. Specify an exact dimension, selected part or catalogue colour. Requests to add unspecified features, send, publish or choose “the best” need your visual selection and review.');
 }
 if(!commands.length)return no('Enter a concrete change to preview.');return {ok:true,request:{id:`instruction-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,expectedRevision:snapshot.revision,commands},summary};
}
