import './PergolaEditor.css';
import {PERGOLA_SUPPLIERS,PERGOLA_PRODUCTS} from '../pergolaFullCatalog';
import {useState,useRef} from 'react';
import type {DeckData} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import {PERGOLA_CATALOG_VERSION,newPergola,pergolaSize,type PergolaSelection} from '../pergolaCatalog';
import {PERGOLA_SITE_COSTS,pergolaPricing} from '../pergolaPricing';
import {pergolaLayout} from '../pergolaLayout';
import {usePergolaQuote} from './usePergolaQuote';
import {pergolaLightingPatch} from '../pergolaLighting';
import {Field,NumberField,type Update} from './fields';
const pergolaProduct=(s:PergolaSelection)=>PERGOLA_PRODUCTS.find(p=>p.id===s.productId);
const pergolaVariant=(s:PergolaSelection)=>pergolaProduct(s)?.variants.find(v=>v.id===s.variantId);
const cad=(n:number|null)=>n===null?'Quote required':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n);
export default function PergolaEditor({data,update,model}:{data:DeckData;update:Update;model:DeckTakeoff}){
 const [supplier,setSupplier]=useState(''),[size,setSize]=useState(''),[operation,setOperation]=useState(''),[price,setPrice]=useState(''),[compare,setCompare]=useState<string[]>([]);
 const {quote,updateQuote}=usePergolaQuote(data,update),s=data.pergola,p=s&&pergolaProduct(s),v=s&&pergolaVariant(s),layout=s&&pergolaLayout(data,model),pricing=pergolaPricing(data,data.materialMarkup??35,quote);
 const current=useRef(s);current.current=s;
 const write=(patch:Partial<PergolaSelection>|((selection:PergolaSelection)=>Partial<PergolaSelection>))=>{if(!current.current)return;const next={...current.current,...(typeof patch==='function'?patch(current.current):patch)};current.current=next;update({pergola:next});};
 const targetValue=s?(s.target.kind==='deck'?`deck:${s.target.level}`:`patio:${s.target.featureId}`):'';
 const targetMissing=s&&(s.target.kind==='deck'?s.target.level>=data.levels:!data.yardFeatures?.some(f=>f.enabled&&f.kind==='patio'&&f.id===(s.target.kind==='patio'?s.target.featureId:'')));
 const filtered=PERGOLA_PRODUCTS.filter(p=>(!supplier||p.manufacturerId===supplier||p.retailerId===supplier)&&(!operation||p.operation===operation)&&p.variants.some(v=>(!size||v.label===size)&&(!price||(price==='listed'?v.priceCad!==null:v.priceCad===null))));
 const number=(label:string,value:number,change:(n:number)=>void,min:number,max:number,step=1)=><NumberField label={label} value={value} onValue={change} min={min} max={max} increment={step} unit={label.includes('(ft)')?'ft':'°'}/>;
 const cost=(label:string,value:number|null|undefined,change:(n:number|null)=>void,placeholder='Quote required')=><Field label={label}><input aria-label={label} type="number" min={0} max={1000000} step="0.01" placeholder={placeholder} value={value??''} onChange={e=>change(e.target.value===''?null:Math.min(1000000,Math.max(0,Number(e.target.value)||0)))}/></Field>;
 return <section className="dd-pergola" aria-label="Aluminum pergolas"><h3>Aluminum pergolas</h3><p className="dd-note">One louvered pergola per design. CAD listing budgets · reviewed {PERGOLA_CATALOG_VERSION}. Exact kits keep their size. Missing drawings mean a conceptual preview.</p>
 <div className="dd-fields">
 <Field label="Pergola supplier"><select aria-label="Pergola supplier" value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">All suppliers</option>{PERGOLA_SUPPLIERS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
 <Field label="Pergola size"><select aria-label="Pergola size" value={size} onChange={e=>setSize(e.target.value)}><option value="">All sizes</option>{[...new Set(PERGOLA_PRODUCTS.flatMap(p=>p.variants.map(v=>v.label)))].map(label=><option key={label}>{label}</option>)}</select></Field>
 <Field label="Roof operation"><select aria-label="Roof operation" value={operation} onChange={e=>setOperation(e.target.value)}><option value="">All operations</option><option value="manual">Manual</option><option value="motorized">Motorized</option></select></Field>
 <Field label="Pergola price status"><select aria-label="Pergola price status" value={price} onChange={e=>setPrice(e.target.value)}><option value="">All price statuses</option><option value="listed">Listing price available</option><option value="quote">Quote required</option></select></Field></div>
 <details className="dd-advanced" open={!s}><summary>Browse products · {filtered.length}</summary>{!filtered.length&&<p>No products match these filters.</p>}{filtered.map(product=><article key={product.id} style={{padding:'12px 0',borderBottom:'1px solid #d8ddd8'}}><strong>{product.name}</strong><p className="dd-note">{PERGOLA_SUPPLIERS.find(x=>x.id===product.manufacturerId)?.location} · {product.operation} · {product.custom?'Custom dimensions':'Fixed kit'}</p>{product.variants.filter(v=>(!size||v.label===size)&&(!price||(price==='listed'?v.priceCad!==null:v.priceCad===null))).map(variant=><div key={variant.id} style={{display:'flex',flexWrap:'wrap',alignItems:'center',gap:8,marginBottom:8}}><span>{variant.label} · {cad(variant.priceCad)} · {variant.availability}</span><button type="button" className="dd-secondary" onClick={()=>update({pergola:{...newPergola(product.id,variant.id),xFt:data.width/2,zFt:data.length/2}})}>Select {product.name} {variant.label}</button></div>)}<label className="dd-check"><input type="checkbox" checked={compare.includes(product.id)} disabled={!compare.includes(product.id)&&compare.length>=3} onChange={e=>setCompare(e.target.checked?[...compare,product.id]:compare.filter(id=>id!==product.id))}/><span>Compare {product.name}</span></label><a href={product.source.url} target="_blank" rel="noreferrer">Product source ↗</a></article>)}</details>
 {compare.length>0&&<div className="dd-pergola-compare" tabIndex={0} aria-label="Scroll pergola comparison"><table><caption>Pergola comparison · first variant; confirm selected variant separately</caption><thead><tr><th>Product</th><th>Size / envelope</th><th>Operation</th><th>Supply CAD</th><th>Warranty / origin</th></tr></thead><tbody>{compare.map(id=>{const p=PERGOLA_PRODUCTS.find(p=>p.id===id)!,v=p.variants[0];return <tr key={id}><th><a href={v.source.url} target="_blank" rel="noreferrer">{p.name}</a></th><td>{v.label}<br/>{v.dimensions?`${v.dimensions.widthIn.toFixed(1)} × ${v.dimensions.depthIn.toFixed(1)} × ${v.dimensions.heightIn.toFixed(1)} in`:'Exact dimensions unknown'}</td><td>{p.operation}</td><td>{cad(v.priceCad)}<br/>{v.availability}</td><td>{p.warranty??'Warranty unknown'}<br/>{PERGOLA_SUPPLIERS.find(s=>s.id===p.manufacturerId)?.origin??'Manufacturing origin unknown'}</td></tr>;})}</tbody></table></div>}
 {s&&p&&v&&<><h4>{p.name} · {v.label}</h4><button className="dd-secondary" type="button" onClick={()=>update({pergola:undefined})}>Remove aluminum pergola</button><p className="dd-note">{v.dimensionNote} Confirm the selected size, finish, drawings and site requirements before installation.</p>
 <div className="dd-fields"><Field label="Pergola variant"><select aria-label="Pergola variant" value={v.id} onChange={e=>write({variantId:e.target.value})}>{p.variants.map(v=><option value={v.id} key={v.id}>{v.label} · {cad(v.priceCad)}</option>)}</select></Field>
 <Field label="Supply responsibility"><select aria-label="Supply responsibility" value={s.supplyMode} onChange={e=>write({supplyMode:e.target.value as PergolaSelection['supplyMode']})}><option value="supply-install">Contractor supply and installation</option><option value="install-only">Install customer-owned kit</option></select></Field>
 <Field label="Pergola support surface"><select aria-label="Pergola support surface" value={targetValue} onChange={e=>{const [kind,id]=e.target.value.split(':');write({target:kind==='deck'?{kind:'deck',level:Number(id)}:{kind:'patio',featureId:id}});}}>{targetMissing&&<option value={targetValue} disabled>Selected surface unavailable</option>}{Array.from({length:data.levels},(_,i)=><option key={i} value={`deck:${i}`}>Deck level {i+1}</option>)}{data.yardFeatures?.filter(f=>f.enabled&&f.kind==='patio').map(f=><option key={f.id} value={`patio:${f.id}`}>{f.name}</option>)}</select></Field>
 {number('Pergola centre across (ft)',s.xFt,n=>write({xFt:n}),-200,200,.25)}{number('Pergola centre out (ft)',s.zFt,n=>write({zFt:n}),-200,200,.25)}{number('Pergola rotation (degrees)',s.rotationDeg,n=>write({rotationDeg:n}),-180,180)}
 <Field label={`Louver opening · ${s.louverDeg}°`}><input aria-label="Louver opening" type="range" min={0} max={p.maxLouverDeg??90} value={s.louverDeg} onChange={e=>write({louverDeg:Number(e.target.value)})}/></Field>
 {(['frameFinish','roofFinish'] as const).map((key,i)=><Field label={i?'Pergola roof finish':'Pergola frame finish'} key={key}><select aria-label={i?'Pergola roof finish':'Pergola frame finish'} value={s[key]} onChange={e=>write({[key]:e.target.value})}>{(i?p.roofFinishes:p.frameFinishes).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field>)}
 {p.custom&&s.customSize&&(['widthFt','depthFt','heightFt'] as const).map((key,i)=>number(`Custom pergola ${['width','depth','height'][i]} (ft)`,s.customSize![key],n=>write(current=>({customSize:{...current.customSize!,[key]:n}})),i===2?7:4,i===2?14:30,.25))}</div>
 {p.custom&&!p.sizeLimits&&<p className="dd-note">Manufacturer size constraints are unknown. Entered sizes are concepts and require a supplier drawing.</p>}
 <label className="dd-check"><input type="checkbox" checked={!!s.lighting||s.accessories.includes('led')} onChange={e=>write(pergolaLightingPatch(s,e.target.checked))}/><span>Pergola lighting · warm white LEDs</span></label><p className="dd-note">{p.accessories.some(a=>a.kind==='led')?'Uses the listed manufacturer LED accessory.':'Planned perimeter LEDs; quote and manufacturer compatibility required.'} Use Night and Preview lights on to see the light spread.</p>
 {p.accessories.length>0&&<fieldset><legend>Contractor-supplied accessories</legend>{p.accessories.map(a=><label className="dd-check" key={a.id}><input type="checkbox" checked={s.accessories.includes(a.id)} onChange={e=>write({accessories:e.target.checked?[...s.accessories,a.id]:s.accessories.filter(id=>id!==a.id),...(a.kind==='led'?{lighting:undefined}:{})})}/><span>{a.name} · {cad(a.priceCad)}</span></label>)}</fieldset>}
 <details className="dd-advanced"><summary>Specifications & sources</summary><p>{p.drainage}</p><p>{p.warranty??'Warranty unknown; quote required.'}</p>{p.notes.map(n=><p className="dd-note" key={n}>{n}</p>)}<p>Outer envelope: {Object.values(pergolaSize(s)).map(n=>n.toFixed(1)).join(' × ')} in · {layout?.conceptual?'conceptual':'listing dimensions; profiles conceptual'}.</p><a href={v.source.url} target="_blank" rel="noreferrer">Price / dimensions source · {v.source.checkedAt} ↗</a>{v.manualUrls.map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer">Matching product manual ↗</a></p>)}{!v.manualUrls.length&&<p className="dd-note">Matching assembly manual has not been verified.</p>}</details>
 {layout&&<details className="dd-advanced" open><summary>Pergola placement review</summary><ul className="dd-review-flags">{layout.warnings.map(n=><li key={n}>{n}</li>)}</ul></details>}
 <details className="dd-advanced"><summary>Contractor costs · private on this device</summary><p className="dd-note">Costs do not travel in JSON files or share links. Included retailer delivery is not charged automatically; enter any extra site delivery cost. Source prices are provisional supply budgets. Enter supplier costs before confirming; material markup applies once to supply/accessories. Site costs are final amounts before HST. Blank means Quote required; enter 0 for an excluded cost. Changing the product or site starts a separate cost worksheet.</p><div className="dd-fields">{s.supplyMode==='supply-install'&&cost('Pergola kit supply cost (CAD)',quote.supply,n=>updateQuote({supply:n,supplyConfirmed:false}),cad(v.priceCad))}{s.accessories.map(id=>{const a=p.accessories.find(a=>a.id===id)!;return <div key={id}>{cost(`${a.name} cost (CAD)`,quote.accessories?.[id],n=>updateQuote({accessories:{...quote.accessories,[id]:n},supplyConfirmed:false}),cad(a.priceCad))}</div>;})}{s.lighting&&cost('Pergola perimeter LED lighting supply cost (CAD)',quote.accessories?.['perimeter-led'],n=>updateQuote({accessories:{...quote.accessories,'perimeter-led':n},supplyConfirmed:false}))}{PERGOLA_SITE_COSTS.map(([key,label])=><div key={key}>{cost(`${label} cost (CAD)`,quote[key],n=>updateQuote({[key]:n}))}</div>)}</div><label className="dd-check"><input type="checkbox" checked={quote.supplyConfirmed??false} onChange={e=>updateQuote({supplyConfirmed:e.target.checked})}/><span>Supplier / accessory costs confirmed for this scope</span></label><label className="dd-check"><input type="checkbox" checked={quote.availabilityConfirmed??false} onChange={e=>updateQuote({availabilityConfirmed:e.target.checked})}/><span>Availability and kit completeness confirmed</span></label>{pricing?.budget&&<p className="dd-note">{pricing.budget}</p>}{pricing&&<ul>{pricing.outstanding.map(n=><li key={n}>{n}</li>)}</ul>}</details></>}
 </section>;
}
