import {useArchitectKeys} from './architectKeys';
import {useEffect,useLayoutEffect,useMemo,useRef,useState,type RefObject} from 'react';
import {createPortal} from 'react-dom';
import {planFrame,type PlanFrame} from '../ConstructionPlan';
import type {DeckData} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import type {PlanPoint} from '../lib/deckGeometry';
import {getHouseConfig} from '../houseSettings';
import {wallLabel} from '../houseFootprint';
import {OPENING_PRESETS,openableWalls} from '../houseOpenings';
import {availableStairSides,getHouseContact} from '../houseContact';
import {privacySides,screenProduct} from '../privacyScreens';
import {activeWrap} from '../lib/wrapGeometry';
import type {Update} from './fields';
import {applyComponentEdit,applyComponentBatch,componentEditValues,listPlanComponents,type ComponentEdit,type ComponentBatchEdit,type PlanComponentKind} from './componentEditActions';
import './planComponentEditor.css';

export interface PlanComponentEditorProps {
 data:DeckData;model:DeckTakeoff;update:Update;toolbar?:RefObject<HTMLElement|null>;viewportFrame?:PlanFrame;viewZoom?:number;
 onStatus?:(message:string)=>void;onOpenSection?:(section:'House'|'Deck'|'Stairs'|'Lighting'|'Extras'|'Site')=>void;
 onEditBoundary?:(level?:1|2|3)=>void;onEditBoards?:(level?:1|2|3)=>void;
 selection?:string[];onSelectionChange?:(ids:string[])=>void;controlsOnly?:boolean;
}
const kinds:{value:PlanComponentKind;name:string;icon:string}[]=[{value:'house',name:'House blocks',icon:'H'},{value:'wall',name:'House walls',icon:'W'},{value:'opening',name:'Doors & windows',icon:'O'},{value:'deck',name:'Deck levels',icon:'D'},{value:'stairs',name:'Grade stairs',icon:'S'},{value:'screen',name:'Privacy screens',icon:'P'},{value:'beam',name:'Beams',icon:'B'},{value:'post',name:'Support posts',icon:'●'},{value:'footing',name:'Footings',icon:'F'}];
const numericKeys=new Set(['widthFt','depthFt','offsetIn','widthIn','heightIn','bottomIn','offsetPct','stairWidth','stairOffset','lengthFt','heightFt','panels']);

/** Selection is view state. Every supported edit is staged, validated, then sent once to the host. */
export function PlanComponentEditor({data,model,update,toolbar,viewportFrame,viewZoom=1,onStatus,onOpenSection,onEditBoundary,onEditBoards,selection,onSelectionChange,controlsOnly=false}:PlanComponentEditorProps){
 const box=useRef<HTMLDivElement>(null),pendingApply=useRef(false),previousData=useRef(data);
 const [size,setSize]=useState<{w:number;h:number}|null>(null),[selectedId,setSelectedId]=useState(''),[filter,setFilter]=useState('editable'),[search,setSearch]=useState(''),[draft,setDraft]=useState<Record<string,string|boolean>>({}),[dirty,setDirty]=useState(false),[notice,setNotice]=useState(''),[invalid,setInvalid]=useState(false),[preset,setPreset]=useState('Window:'),[addWall,setAddWall]=useState('main-front');
 const [ids,setIds]=useState<string[]>([]),[multi,setMulti]=useState(false),[batchAction,setBatchAction]=useState('move'),[batchValue,setBatchValue]=useState('10');
 const [batchReview,setBatchReview]=useState('');
 const batchKey=JSON.stringify([ids,batchAction,batchValue]),liveBatch=useRef({data,key:batchKey}),reviewedBatch=useRef<{data:DeckData;key:string;result:ReturnType<typeof applyComponentBatch>}|null>(null);liveBatch.current={data,key:batchKey};
 useEffect(()=>setBatchReview(''),[data,ids,batchAction,batchValue]);
 const parts=useMemo(()=>listPlanComponents(data,model),[data,model]),selected=parts.find(p=>p.id===selectedId),house=getHouseConfig(data),walls=openableWalls(data),wrapped=!!activeWrap(data);
 const visibleParts=parts.filter(p=>(filter==='all'||filter==='editable'?!['beam','post','footing'].includes(p.kind)||filter==='all':p.kind===filter)&&`${p.label} ${p.id} ${p.dimensions.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const announce=(message:string,error=false)=>{setNotice(message);setInvalid(error);onStatus?.(message);};
 const replaceSelection=(next:string[])=>{setIds(next);onSelectionChange?.(next);const id=next.at(-1)??'';setSelectedId(id);const part=parts.find(p=>p.id===id);setDraft(part?componentEditValues(data,part):{});setDirty(false);setNotice('');setInvalid(false);if(part?.kind==='wall')setAddWall(part.refId!);};
 useArchitectKeys({a:()=>replaceSelection(visibleParts.map(p=>p.id)),l:()=>{if(!selected)return false;replaceSelection(visibleParts.filter(p=>p.kind===selected.kind).map(p=>p.id));},n:()=>replaceSelection([])});
 const choose=(id:string,toggle=false,range=false)=>{if(!id){replaceSelection([]);return;}if(range&&selectedId){const a=visibleParts.findIndex(p=>p.id===selectedId),b=visibleParts.findIndex(p=>p.id===id);if(a>=0&&b>=0){replaceSelection([...new Set([...ids,...visibleParts.slice(Math.min(a,b),Math.max(a,b)+1).map(p=>p.id)])]);return;}}replaceSelection(toggle||multi?(ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]):[id]);};
 useEffect(()=>{if(!selection||JSON.stringify(selection)===JSON.stringify(ids))return;const next=selection.filter(id=>parts.some(p=>p.id===id));setIds(next);const id=next.at(-1)??'';setSelectedId(id);const part=parts.find(p=>p.id===id);setDraft(part?componentEditValues(data,part):{});setDirty(false);},[selection]);
 useEffect(()=>{
  if(previousData.current===data)return;previousData.current=data;
  const retained=ids.filter(id=>parts.some(p=>p.id===id));if(retained.length!==ids.length)replaceSelection(retained);
  if(selectedId&&!selected){setSelectedId(retained.at(-1)??'');setDraft({});setDirty(false);announce('A selected part is no longer in this design. Select another part.');}
  else if(selected){setDraft(componentEditValues(data,selected));if(dirty&&!pendingApply.current)announce('The design changed. The selected part now shows its current values; enter your change again.');setDirty(false);}
  pendingApply.current=false;
 },[data,selectedId]);
 useLayoutEffect(()=>{const el=box.current;if(!el)return;const measure=()=>setSize({w:el.clientWidth,h:el.clientHeight});measure();const observer=typeof ResizeObserver==='function'?new ResizeObserver(measure):null;observer?.observe(el);return ()=>observer?.disconnect();},[]);
 const frame=viewportFrame??planFrame(model,{data,variant:'site'}),scale=size?Math.min(size.w/frame.w,size.h/frame.h):0,ox=size?(size.w-frame.w*scale)/2:0,oy=size?(size.h-frame.h*scale)/2:0;
 const at=(p:PlanPoint)=>({left:ox+(p.x-frame.x)*scale,top:oy+(p.y-frame.y)*scale});
 const shown=visibleParts.some(p=>p.id===selectedId)?visibleParts:selected?[...visibleParts,selected]:visibleParts;
 const change=(key:string,value:string|boolean)=>{setDraft(old=>({...old,[key]:value}));setDirty(true);setNotice('');setInvalid(false);};
 const commit=(edit:ComponentEdit)=>{if(!selected)return;const result=applyComponentEdit(data,model,selected.id,edit);if('error'in result){announce(result.error,true);return;}if(Object.keys(result.patch).every(key=>JSON.stringify(data[key as keyof DeckData])===JSON.stringify(result.patch[key as keyof DeckData]))){setDirty(false);announce('This part already has those values.');return;}try{pendingApply.current=true;update(result.patch);replaceSelection([result.selectedId]);setDirty(false);announce(result.message);}catch(error){pendingApply.current=false;announce(error instanceof Error?error.message:'The current design constraints do not permit this change.',true);}};
 const batchOperation=():ComponentBatchEdit=>batchAction==='move'?{action:'move',offsetDeltaPct:Number(batchValue)}:['widthIn','bottomIn','heightFt'].includes(batchAction)?{action:'update',fields:{[batchAction]:Number(batchValue)}}:batchAction==='lights-on'||batchAction==='lights-off'?{action:'screen-lights',enabled:batchAction==='lights-on'}:{action:batchAction as 'duplicate'|'remove'|'distribute'};
 const reviewBatch=()=>{const result=applyComponentBatch(data,model,ids,batchOperation());if('error'in result){announce(result.error,true);return;}const key=batchKey;void import('./editPricePreview').then(m=>m.editPricePreview(data,result.patch)).then(message=>{if(liveBatch.current.data===data&&liveBatch.current.key===key){reviewedBatch.current={data,key,result};setBatchReview(message);announce("");}}).catch(e=>announce(e.message,true));};
 const commitBatch=()=>{try{const reviewed=reviewedBatch.current;if(!batchReview||reviewed?.data!==data||reviewed.key!==batchKey)throw new Error('Review the priced portion and outstanding quotes before applying this batch.');const result=reviewed.result;if('error'in result){announce(result.error,true);return;}pendingApply.current=true;update(result.patch);replaceSelection(result.selectedIds);announce(result.message);}catch(error){pendingApply.current=false;announce(error instanceof Error?error.message:'The batch was rejected. Your selection and draft remain.',true);}};
 const apply=()=>{try{const fields:Record<string,unknown>={};for(const [key,value] of Object.entries(draft)){if(wrapped&&selected&&(selected.kind==='house'||selected.kind==='wall')&&['widthFt','depthFt','offsetIn'].includes(key))continue;if(selected?.kind==='screen'&&(stock?['lengthFt','heightFt'].includes(key):key==='panels'))continue;if(numericKeys.has(key)){if(typeof value!=='string'||!value.trim()||!Number.isFinite(Number(value)))throw new Error(`Enter a number for ${key}.`);fields[key]=Number(value);}else fields[key]=value;}commit({action:'update',fields});}catch(error){announce(error instanceof Error?error.message:'Enter valid component values.',true);}};
 const input=(key:string,label:string,min:number,max:number,disabled=false)=><label key={key}>{label}<input aria-label={label} type="number" inputMode="decimal" step="any" min={min} max={max} value={String(draft[key]??'')} disabled={disabled} onChange={e=>change(key,e.target.value)}/></label>;
 const select=(key:string,label:string,options:{value:string;label:string}[])=><label key={key}>{label}<select aria-label={label} value={String(draft[key]??'')} onChange={e=>change(key,e.target.value)}>{!options.some(o=>o.value===draft[key])&&<option value={String(draft[key]??'')}>{String(draft[key]??'')} · current</option>}{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 const simple=(values:readonly string[])=>values.map(value=>({value,label:value}));
 const screen=selected?.kind==='screen'?data.privacyScreens?.find(s=>s.id===selected.refId):undefined,stock=screen?screenProduct(screen).panel:undefined;
 const fp=model.levels.find(l=>l.kind==='deck'&&l.index===0)?.footprint,contact=fp?getHouseContact(data,fp):undefined,edges=fp?.edgeIds?.map((id,index)=>({value:id,label:`${id.replace(/-/g,' ')} · edge ${index+1}`,index})).filter(e=>!contact?.isContactEdge(e.index))??[];
 const scopeSection=selected?.kind==='stairs'?'Stairs':selected?.kind==='screen'?'Extras':['footing','beam','post'].includes(selected?.kind??'')?'Site':['house','wall','opening'].includes(selected?.kind??'')?'House':'Deck';
 const controls=<section className="dd-component-controls" aria-label="Selected plan component controls">
  <div className="dd-component-browser"><label>Find a part<input aria-label="Find plan part" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Window, beam, level…"/></label><label>Show<select aria-label="Plan component type" value={filter} onChange={e=>setFilter(e.target.value)}><option value="editable">House, deck & extras</option><option value="all">All parts</option>{kinds.map(k=><option key={k.value} value={k.value}>{k.name}</option>)}</select></label><label className="dd-component-picker">Part<select aria-label="Select plan part" value={selectedId} onChange={e=>choose(e.target.value)}><option value="">Select on the drawing or choose here</option>{shown.map(p=><option key={p.id} value={p.id}>{p.label}{!p.anchor?' · not drawn':''}</option>)}</select></label></div>
  <div className="dd-component-selection-actions"><label className="dd-component-check"><input type="checkbox" aria-label="Select multiple parts" checked={multi} onChange={e=>setMulti(e.target.checked)}/>Select multiple</label><button type="button" onClick={()=>replaceSelection(visibleParts.map(p=>p.id))}>Select all matching parts</button><span aria-live="polite">{ids.length} selected</span></div>
  {multi&&<div className="dd-component-checklist" role="group" aria-label="Toggle parts in selection">{visibleParts.map(p=><label key={p.id}><input type="checkbox" checked={ids.includes(p.id)} onChange={()=>choose(p.id,true)}/>{p.label}</label>)}</div>}
  {!selected&&<p className="dd-component-help">Select a marked part on the plan or a real object in 3D. Search or filter the list to reach overlapping supports and hidden house parts.</p>}
  {ids.length>1&&<div className="dd-component-batch" aria-label="Batch component edits">{onOpenSection&&ids.every(id=>parts.find(p=>p.id===id)?.kind===selected?.kind)&&["beam","post","footing"].includes(selected?.kind??"")&&<button type="button" onClick={()=>onOpenSection("Site")}>{selected?.kind==="footing"?"Edit all footings":"Edit all generated framing"}</button>}<strong>{ids.length} selected parts</strong><p>Stage one shared operation, then Apply once. Select one kind of part; generated framing uses its shared settings.</p><label>Operation<select aria-label="Batch part operation" value={batchAction} onChange={e=>setBatchAction(e.target.value)}><option value="move">Move along edge / wall (%)</option><option value="duplicate">Duplicate</option><option value="remove">Remove</option><option value="distribute">Distribute screens along edge</option><option value="widthIn">Opening width (in)</option><option value="bottomIn">Opening bottom (in)</option><option value="heightFt">Screen height (ft)</option><option value="lights-on">Enable screen light mounts</option><option value="lights-off">Remove screen light mounts</option></select></label>{['move','widthIn','bottomIn','heightFt'].includes(batchAction)&&<label>Value<input type="number" step="any" aria-label="Batch part value" value={batchValue} onChange={e=>setBatchValue(e.target.value)}/></label>}<button type="button" onClick={reviewBatch}>Review selected part changes</button>{batchReview&&<p role="status">{batchReview}</p>}<button type="button" className="dd-component-apply" onClick={commitBatch}>Apply to selected parts</button><button type="button" onClick={()=>{setBatchValue('10');announce('Batch draft cancelled. Nothing changed.');}}>Cancel batch changes</button></div>}
  {selected&&ids.length===1&&<>
   <div className="dd-component-heading"><strong>{selected.label}</strong><button type="button" aria-label="Clear component selection" onClick={()=>choose('')}>Clear</button></div>
   <p className="dd-component-dimensions" aria-label="Actual component dimensions">{selected.dimensions.join(' · ')}</p>
   <p className="dd-component-scope">{selected.scope}{!selected.anchor?' This saved part is not currently drawn.':''}</p>
   {selected.editable&&<form onSubmit={e=>{e.preventDefault();apply();}}>
    <div className="dd-component-fields">
     {(selected.kind==='house'||selected.kind==='wall')&&<>{input('widthFt','Main house width (ft)',12,100,wrapped)}{input('depthFt','Main house depth (ft)',12,100,wrapped)}{input('offsetIn','House left position (in)',-2400,2400,wrapped)}<label className="dd-component-check"><input type="checkbox" aria-label="Show house" checked={draft.visible===true} onChange={e=>change('visible',e.target.checked)}/>Show house</label>{wrapped&&<p className="dd-component-help">The wrap layout controls house size and position.</p>}</>}
     {selected.kind==='opening'&&<>{select('type','Opening type',simple(['Door','Window','Garage']))}{select('wallId','Opening wall',walls.map(w=>({value:w.id,label:wallLabel(w.id,house)})))}{input('widthIn','Opening width (in)',12,180)}{input('heightIn','Opening height (in)',12,144)}{input('bottomIn','Opening bottom above grade (in)',0,900)}{input('offsetPct','Opening wall offset (%)',0,100)}</>}
     {selected.kind==='stairs'&&<>{input('stairWidth','Grade stair width (in)',36,120)}{select('stairType','Grade stair type',simple(['Straight','Winder','Landing']))}{select('stairPosition','Primary stair side',simple(availableStairSides(data)))}{select('stairEdgeId','Primary stair edge',[{value:'',label:'Use selected side'},...edges])}{input('stairOffset','Primary stair offset (%)',0,100)}</>}
     {selected.kind==='screen'&&<>{select('side','Screen side',simple(privacySides(data)))}{stock?input('panels','Screen stock panels',1,12):<>{input('lengthFt','Screen length (ft)',.01,60)}{select('heightFt','Screen height (ft)',simple(['4','5','6']))}</>}{input('offsetPct','Screen edge offset (%)',0,100)}<label className="dd-component-check"><input type="checkbox" aria-label="Enable screen" checked={draft.enabled===true} onChange={e=>change('enabled',e.target.checked)}/>Enable screen</label></>}
    </div>
    <div className="dd-component-actions"><button type="submit" className="dd-component-apply" disabled={!dirty}>Apply part changes</button><button type="button" disabled={!dirty} onClick={()=>{setDraft(componentEditValues(data,selected));setDirty(false);announce('Draft changes cancelled.');}}>Cancel changes</button>{(selected.kind==='opening'||selected.kind==='screen')&&<><button type="button" onClick={()=>commit({action:'duplicate'})}>Duplicate part</button><button type="button" className="dd-component-remove" onClick={()=>commit({action:'remove'})}>Remove part</button></>}</div>
   </form>}
   {['house','wall'].includes(selected.kind)&&<details className="dd-component-add"><summary>Add a door or window</summary><div className="dd-component-fields"><label>New opening<select aria-label="New opening preset" value={preset} onChange={e=>setPreset(e.target.value)}>{OPENING_PRESETS.map(p=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label><label>Wall<select aria-label="New opening wall" value={walls.some(w=>w.id===addWall)?addWall:walls[0]?.id??''} onChange={e=>setAddWall(e.target.value)}>{walls.map(w=><option key={w.id} value={w.id}>{wallLabel(w.id,house)}</option>)}</select></label></div><button type="button" disabled={!walls.length} onClick={()=>commit({action:'add-opening',presetKey:preset,wallId:walls.some(w=>w.id===addWall)?addWall:walls[0]?.id??''})}>Add opening</button></details>}
   <div className="dd-component-actions">{selected.kind==='deck'&&<><button type="button" onClick={()=>onEditBoundary?.(selected.level)} disabled={!onEditBoundary}>Edit level shape</button><button type="button" onClick={()=>onEditBoards?.(selected.level)} disabled={!onEditBoards}>Edit level boards</button></>}{onOpenSection&&<button type="button" onClick={()=>onOpenSection(scopeSection)}>{selected.kind==='beam'||selected.kind==='post'?'Edit all generated framing':selected.kind==='footing'?'Edit all footings':`Open ${scopeSection.toLowerCase()} settings`}</button>}</div>
  </>}
  {notice&&<p role="status" className="dd-component-notice" data-invalid={invalid||undefined}>{notice}</p>}
 </section>;
 const handleSize=Math.ceil(44/Math.max(.1,viewZoom));
 if(controlsOnly)return controls;
 return <div ref={box} className="dd-component-editor" onKeyDown={e=>{if(e.key==='Escape'){choose('');announce('Selection cleared.');}}}>
  <svg viewBox={frame.viewBox} aria-hidden="true" focusable="false">{parts.filter(p=>ids.includes(p.id)).map(p=><g key={p.id}>{p.polygon&&<polygon className="dd-component-highlight" points={p.polygon.map(p=>`${p.x},${p.y}`).join(' ')}/>} {p.line&&<line className="dd-component-highlight" x1={p.line[0].x} y1={p.line[0].y} x2={p.line[1].x} y2={p.line[1].y}/>}</g>)}</svg>
  {size&&shown.filter(p=>p.anchor&&p.anchor.x>=frame.x&&p.anchor.x<=frame.x+frame.w&&p.anchor.y>=frame.y&&p.anchor.y<=frame.y+frame.h).map(p=><button key={p.id} type="button" className="dd-component-handle" data-component-id={p.id} data-kind={p.kind} data-selected={ids.includes(p.id)||undefined} style={{...at(p.anchor!),width:handleSize,height:handleSize,fontSize:12/Math.max(.1,viewZoom)}} aria-label={`Select ${p.label}`} aria-pressed={ids.includes(p.id)} title={p.label} onClick={e=>choose(p.id,e.ctrlKey||e.metaKey,e.shiftKey)}><span aria-hidden="true">{kinds.find(k=>k.value===p.kind)?.icon}</span></button>)}
  {size&&selected?.anchor&&<div className="dd-component-near" style={{left:Math.min(size.w-130/Math.max(.1,viewZoom),Math.max(130/Math.max(.1,viewZoom),at(selected.anchor).left)),top:Math.max(48,Math.min(size.h-12,at(selected.anchor).top)),transform:`translate(-50%,-100%) scale(${1/Math.max(.1,viewZoom)})`}} role="toolbar" aria-label="Selected object actions"><strong>{ids.length>1?`${ids.length} parts`:selected.label}</strong><button type="button" onClick={()=>{const el=document.querySelector<HTMLElement>('.dd-component-controls');el?.scrollIntoView({block:'nearest'});el?.querySelector<HTMLElement>('input,select,button')?.focus();}}>Edit</button>{ids.length===1&&(selected.kind==='opening'||selected.kind==='screen')&&<button type="button" onClick={()=>commit({action:'duplicate'})}>Duplicate</button>}<button type="button" onClick={()=>choose('')}>Clear</button></div>}
  {toolbar?.current?createPortal(controls,toolbar.current):<div className="dd-component-toolbar">{controls}</div>}
 </div>;
}
export default PlanComponentEditor;
