import {lazy,Suspense} from 'react';
import type {DeckData} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import type {SelectionState} from './selectionState';
import {useHardscapePreview} from './useHardscapePreview';
import EditReview from './EditReview';
import {activeLightingItems} from '../lightingSystem';
import {isObjectLocked} from '../editorOrganization';
import {planFrame} from '../ConstructionPlan';
const Components=lazy(()=>import('./PlanComponentEditor')),Boards=lazy(()=>import('./BoardLayoutEditor')),Pergola=lazy(()=>import('./PergolaEditor'));
export default function PreviewedObjectInspector({data,model,selection,onSelection,onApply,onGeometry,onOpenSection,onEditBoundary,onEditBoards}:{data:DeckData;model:DeckTakeoff;selection:SelectionState;onSelection:(s:SelectionState)=>void;onApply:(p:Partial<DeckData>)=>void;onGeometry:(d:DeckData|null)=>void;onOpenSection:(s:string)=>void;onEditBoundary:(l?:1|2|3)=>void;onEditBoards:(l?:1|2|3)=>void}){
 const flow=useHardscapePreview(data,onApply,onGeometry,next=>{const p:Partial<DeckData>={};for(const k of Object.keys(next) as (keyof DeckData)[])if(JSON.stringify(next[k])!==JSON.stringify(data[k]))(p as Record<string,unknown>)[k]=next[k];return p;});
 const update=(p:Partial<DeckData>)=>{const patch=JSON.parse(JSON.stringify(p)),unset=Object.keys(p).filter(k=>p[k as keyof DeckData]===undefined);void flow.preview([{type:'design.patch',patch,...(unset.length?{unset:unset as (keyof DeckData)[]}: {})}]);};
 const lighting=selection.partIds.find(id=>id.startsWith('lighting:')),light=lighting&&activeLightingItems(data,model).find(i=>lighting===`lighting:${i.zone}:${i.productId}`);
 const locked=selection.partIds.some(id=>isObjectLocked(data.editorOrganization,id)||isObjectLocked(data.editorOrganization,id.startsWith('house:')||id.startsWith('wall:')||id.startsWith('opening:')?'house':id.startsWith('lighting:')?'lighting':id.startsWith('deck:')?'deck':id));
 return <div className="dd-3d-selection-card" aria-label="3D selected object editor"><strong>Selected object settings</strong>{locked&&<p>Locked — unlock its object or layer before editing.</p>}<fieldset disabled={locked}><Suspense fallback={<p role="status">Loading object controls…</p>}>{selection.partIds.includes('pergola:main')?<Pergola data={data} model={model} update={update}/>:lighting?<fieldset><legend>Lighting assembly</legend><p>{light?`${light.name} · ${light.zone} · ${light.qty} fixture(s)`:'Generated fixture. Its position follows the owning mount.'}</p>{light&&<><label>Zone enabled<input type="checkbox" checked={data.lightingZoneEnabled?.[light.zone]!==false} onChange={e=>update({lightingZoneEnabled:{...data.lightingZoneEnabled,[light.zone]:e.target.checked}})}/></label>{data.lightingSystem.selectedItems.some(i=>i.productId===light.productId&&!i.auto)&&<label>Fixture quantity<input type="number" min="0" max="30" defaultValue={light.qty} onBlur={e=>update({lightingSystem:{...data.lightingSystem,selectedItems:data.lightingSystem.selectedItems.map(i=>i.productId===light.productId&&!i.auto?{...i,qty:Number(e.target.value)}:i)}})}/></label>}<p>Stock dimensions and generated mounting locations follow the selected product and installation assembly.</p></>}</fieldset>:selection.boards.length?<Boards controlsOnly viewportFrame={planFrame(model,{data,variant:'site'})} selection={selection.boards} onSelectionChange={boards=>onSelection({partIds:[],boards})} data={data} model={model} update={update}/>:<Components controlsOnly selection={selection.partIds} onSelectionChange={partIds=>onSelection({partIds,boards:[]})} data={data} model={model} update={update} onOpenSection={onOpenSection} onEditBoundary={onEditBoundary} onEditBoards={onEditBoards}/>}</Suspense></fieldset><EditReview flow={flow} data={data} label="object settings"/></div>;
}
