import {useRef,useState} from 'react';
import type {DeckData} from '../types';
import {readProjectValue,preserveRecoveryText} from '../projectStorage';
import {ensureLiveDesignExtensions} from '../designExtensions';
import {parseDeckReleaseDesign} from '../deckRelease';
import {parsePrivateProject,serializePrivateProject,stabilizeJobDesign,jobDesignStamp} from './jobRevisionLibrary';
import {dollars} from '../designFacts';
export default function ProjectRecovery({data,onRestore}:{data:DeckData;onRestore:(data:DeckData)=>void}){
 const latest=useRef(data);latest.current=data;const file=useRef<HTMLInputElement>(null);
 const [candidate,setCandidate]=useState<{data:DeckData;stamp:string;total:number;label:string}|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const download=(text:string,name:string)=>{const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const preview=async(text:string,label:string,privateOnly=false)=>{if(new TextEncoder().encode(text).length>1_000_000)throw Error('Choose a backup smaller than 1 MB.');const stamp=jobDesignStamp(latest.current),raw=JSON.parse(text);await ensureLiveDesignExtensions(raw);const next=raw?.format==='deckcraft-private-project'?parsePrivateProject(text):privateOnly?(()=>{throw Error('Choose a DeckCraft private working backup.');})():parseDeckReleaseDesign(text);await ensureLiveDesignExtensions(next);if(stamp!==jobDesignStamp(latest.current))throw Error('The design changed. Review the backup again.');const ready=stabilizeJobDesign(next);setCandidate({data:ready.data,total:ready.estimate.total,stamp,label});setStatus('Review only. The open design has not changed.');};
 const perform=async(action:()=>Promise<void>)=>{setBusy(true);setStatus('');setCandidate(null);try{await action();}catch(e){setStatus(e instanceof Error?e.message:'Recovery is unavailable.');}finally{setBusy(false);}};
 const restore=async()=>{if(!candidate||candidate.stamp!==jobDesignStamp(latest.current)){setStatus('The design changed. Review the backup again.');return;}setBusy(true);try{await preserveRecoveryText('current',serializePrivateProject(latest.current),'Working design preserved before explicit recovery.');if(candidate.stamp!==jobDesignStamp(latest.current))throw Error('The design changed while preserving it. Review again.');onRestore(candidate.data);setCandidate(null);setStatus('Recovered design applied. Undo returns to the previous open design.');}catch(e){setStatus(e instanceof Error?e.message:'Recovery could not be applied.');}finally{setBusy(false);}};
 return <details><summary>Recovery &amp; private working backup</summary><p>Private backups include customer details and contractor prices. Keep them private. Survey attachment files and the supplier ratebook are stored separately; use the project ZIP for survey files.</p>
 <button type="button" disabled={busy} onClick={()=>void perform(async()=>{download(serializePrivateProject(latest.current),'DeckCraft-private-working-backup.json');setStatus('Private working backup downloaded.');})}>Download private working backup</button>
 <button type="button" disabled={busy} onClick={()=>file.current?.click()}>Review private backup</button>
 <input ref={file} hidden type="file" accept=".json,application/json" aria-label="Review private working backup" onChange={e=>{const f=e.target.files?.[0];if(f)void perform(async()=>{if(f.size>1_000_000)throw Error('Choose a backup smaller than 1 MB.');await preview(await f.text(),f.name,true);});e.target.value='';}}/>
 <button type="button" disabled={busy} onClick={()=>void perform(async()=>{const previous=await readProjectValue<{value?:{json?:string;savedAt?:string}}>('recovery','current-previous');if(typeof previous?.value?.json!=='string')throw Error('No previous autosave is available yet.');await preview(previous.value.json,'Previous autosave'+(previous.value.savedAt?' · '+new Date(previous.value.savedAt).toLocaleString():''));})}>Review previous autosave</button>
 {candidate&&<section aria-label="Recovery preview"><h4>{candidate.label}</h4><p>{candidate.data.width} × {candidate.data.length} ft · {dollars(candidate.total)} priced portion including HST. Replaces geometry, customer details and saved private pricing. Reconfirm inactive quotes after changes.</p><button type="button" disabled={busy||candidate.stamp!==jobDesignStamp(data)} onClick={()=>void restore()}>Restore reviewed backup</button><button type="button" disabled={busy} onClick={()=>setCandidate(null)}>Cancel recovery</button></section>}
 {status&&<p role="status">{status}</p>}</details>;
}
