import {pergolaLayout} from '../pergolaLayout';
import {pergolaSize} from '../pergolaValidation';
import {extrasLayout} from '../extrasLayout';
import {editableBoundaries,moveBoundary,boundaryPatch} from './boundaryEditMath';
import {curveYardEdge} from '../yardDesignTools';
import type {DeckData} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import type {SelectionState} from './selectionState';
import type {AgentCommand} from './deckAgentController';
import type {SceneDragTarget,SceneDragValue,SceneEditMode} from './sceneEditTypes';
import {applyLandscapeEdit} from '../landscapeEdits';
import {landscapeWorld,convertLandscapeOutline,resizeLandscape} from '../landscapeOutline';
import {editObjects} from '../professionalEdits';
import {yardShapeWorldPoints,yardShapeResize,yardShapePull} from '../yardShapeEditing';
import {applyPoolCommand,poolPointCommand,poolControlWorld} from '../poolEdits';
import {listPlanComponents,componentEditValues,applyComponentEdit} from './componentEditActions';
import {getHouseConfig} from '../houseSettings';
import {getHouseWalls,openingWallId} from '../houseFootprint';
import {sampleSiteHeight} from '../siteSurface';
import {landscapeSurfaceDepth} from '../landscapeSurfaces';
import {arcGeometry} from '../circularArcs';
import {isObjectLocked} from '../editorOrganization';
export const sceneObjectIds=(s:SelectionState)=>[...new Set(s.objectIds?.length?s.objectIds:s.hardscape?[s.hardscape.id]:[])];
export function sceneEditTarget(data:DeckData,model:DeckTakeoff,s:SelectionState){
 const ids=sceneObjectIds(s),id=s.hardscape?.id??ids[0],o=data.landscapeObjects?.find(o=>o.id===id),f=data.yardFeatures?.find(o=>o.id===id),pool=data.pools?.find(o=>o.id===id),part=listPlanComponents(data,model).find(p=>s.partIds.includes(p.id));
 let x=o?.xIn??(f?f.xFt*12:pool?.xIn)??part?.anchor?.x??0,z=o?.zIn??(f?f.zFt*12:pool?.zIn)??part?.anchor?.y??0,y=o?(sampleSiteHeight(data,x,z)??0)+(o.kind==='bed'?landscapeSurfaceDepth(o):0):pool?.copingTopElevationIn??f?.finishedElevationIn??(sampleSiteHeight(data,x,z)??0)+(f?.heightIn??0);
 if(ids.length>1){const points=ids.flatMap(id=>{const o=data.landscapeObjects?.find(o=>o.id===id)??data.pools?.find(o=>o.id===id),f=data.yardFeatures?.find(o=>o.id===id),t=data.siteModel?.transitions?.find(o=>o.id===id);return o?[{x:o.xIn,z:o.zIn}]:f?[{x:f.xFt*12,z:f.zFt*12}]:t?[{x:t.a.points[0].x,z:t.a.points[0].y}]:[];});if(points.length){x=points.reduce((n,p)=>n+p.x,0)/points.length;z=points.reduce((n,p)=>n+p.z,0)/points.length;}y=sampleSiteHeight(data,x,z)??y;}

 const pergola=s.partIds.includes('pergola:main')?data.pergola:undefined,layout=pergola?pergolaLayout(data,model,[],false):null;
 if(pergola){x=pergola.xFt*12;z=pergola.zFt*12;y=layout?.base??0;}
 const locked=ids.some(id=>isObjectLocked(data.editorOrganization,id))||s.partIds.some(id=>isObjectLocked(data.editorOrganization,id))||!!part&&isObjectLocked(data.editorOrganization,part.kind==='deck'?'deck':['house','wall','opening'].includes(part.kind)?'house':'')||!!pergola&&isObjectLocked(data.editorOrganization,'pergola:main');
 const modes:SceneEditMode[]=pergola?['move','rotate']:ids.length>1?['move','rotate']:o?['move','rotate','resize',...(o.kind==='bed'?['shape' as const]:[])]:f?['move','rotate','resize',...(!f.stepAssembly&&!f.stoneSteps&&f.kind!=='water-feature'&&f.kind!=='fire-feature'?['shape' as const]:[]),...(f.finishedElevationIn!==undefined?['elevation' as const]:[])]:pool?['move','rotate','shape','elevation']:part?.kind==='deck'?['resize','shape','elevation']:part&&['house','wall','opening','screen'].includes(part.kind)?['move',...(part.kind==='opening'?['elevation' as const]:[])]:[];
 const points=o?.kind==='bed'?convertLandscapeOutline(o).outline!.outer.points.map(p=>{const v=landscapeWorld(o,p);return {x:v.x,z:v.z};}):f&&!f.stoneSteps&&!f.stepAssembly?yardShapeWorldPoints(f).map(p=>({x:p.x,z:p.y})):pool?poolControlWorld(pool).map(p=>({x:p.x,z:p.y})):part?.kind==='deck'?part.polygon?.map(p=>({x:p.x,z:p.y}))??[]:[];
 return {ids,id,o,f,pool,part,pergola,x,z,y,modes:locked?[]:modes,points,locked,label:pergola?'Aluminum pergola':ids.length>1?`${ids.length} selected objects`:o?.name??f?.name??pool?.name??part?.label??'Select an object',width:pergola?pergolaSize(pergola).widthIn:o?.widthIn??(f?f.widthFt*12:pool?Math.max(...points.map(p=>p.x))-Math.min(...points.map(p=>p.x)):part?.kind==='deck'?Number(part.level===2?data.width2:part.level===3?data.level3?.widthFt:data.width)*12:0),depth:pergola?pergolaSize(pergola).depthIn:o?.depthIn??(f?f.depthFt*12:pool?Math.max(...points.map(p=>p.z))-Math.min(...points.map(p=>p.z)):part?.kind==='deck'?Number(part.level===2?data.length2:part.level===3?data.level3?.lengthFt:data.length)*12:0)};
}
export function sceneEditCommands(data:DeckData,model:DeckTakeoff,selection:SelectionState,h:SceneDragTarget,v:SceneDragValue):AgentCommand[]{
 const t=sceneEditTarget(data,model,selection);if(t.locked)throw Error('Unlock all selected objects or layers before editing.');const rotation=(t.o?.rotationDeg??t.f?.rotationDeg??0)*Math.PI/180,x=h.part==='resize'?Math.cos(rotation)*v.dxIn+Math.sin(rotation)*v.dzIn:v.dxIn,z=h.part==='resize'?-Math.sin(rotation)*v.dxIn+Math.cos(rotation)*v.dzIn:v.dzIn;
 if(t.pergola){const next={...t.pergola,...(h.part==='move'?{xFt:t.pergola.xFt+x/12,zFt:t.pergola.zFt+z/12}:{rotationDeg:((t.pergola.rotationDeg+v.angleDeg+540)%360)-180})},warnings=pergolaLayout({...data,pergola:next},model)?.warnings.filter(w=>/conflicts|missing or disabled|extends beyond/.test(w))??[];if(warnings.length)throw Error(warnings.join(' '));return [{type:'design.patch',patch:{pergola:next}}];}
 if(t.ids.length>1){if(h.part!=='move'&&h.part!=='rotate')throw Error('Group transforms support move and rotation.');return [{type:'objects.edit',ids:t.ids,edit:h.part==='move'?{action:'move',dxIn:x,dzIn:z}:{action:'rotate',angleDeg:v.angleDeg,pivotXIn:t.x,pivotZIn:t.z}}];}
 if(t.o){if(h.part==='move'||h.part==='rotate')return [{type:'objects.edit',ids:[t.o.id],edit:h.part==='move'?{action:'move',dxIn:x,dzIn:z}:{action:'rotate',angleDeg:v.angleDeg,pivotXIn:t.x,pivotZIn:t.z}}];if(h.part==='resize'){const width=Math.max(.1,t.width+2*x),depth=Math.max(.1,t.depth+2*z);return [{type:'landscape.edit',id:t.o.id,edit:t.o.kind==='bed'?{action:'resize',widthIn:width,depthIn:depth}:{action:'patch',patch:{widthIn:width,depthIn:depth}}}];}return [{type:'landscape.edit',id:t.o.id,edit:{action:'handle',handle:{part:h.part as 'point'|'bend'|'c1'|'c2'|'cup',ring:h.ring??0,index:h.index??0},point:v.world}}];}
 if(t.f){const f=t.f;if(h.part==='move'||h.part==='rotate')return [{type:'objects.edit',ids:[f.id],edit:h.part==='move'?{action:'move',dxIn:x,dzIn:z}:{action:'rotate',angleDeg:v.angleDeg,pivotXIn:t.x,pivotZIn:t.z}}];if(h.part==='elevation')return [{type:'yard.finished',id:f.id,edit:{action:'level',elevationIn:f.finishedElevationIn!+v.dyIn}}];if(h.part==='resize'){const sx=(t.width+2*x)/t.width,sy=(t.depth+2*z)/t.depth,next=yardShapeResize(f,(t.width+2*x)/12,(t.depth+2*z)/12);void sx;void sy;return [{type:'design.patch',patch:{yardFeatures:data.yardFeatures!.map(p=>p.id===f.id?next:p)}}];}if(h.part==='bend'){const a=t.points[h.index??0],b=t.points[((h.index??0)+1)%t.points.length],len=Math.hypot(b.x-a.x,b.z-a.z);return [{type:'yard.curve',id:f.id,index:h.index??0,bulgeIn:((v.world.x-(a.x+b.x)/2)*-(b.z-a.z)+(v.world.z-(a.z+b.z)/2)*(b.x-a.x))/len}];}const a=t.points[h.index??0];return [{type:'yard.move',id:f.id,target:'point',index:h.index??0,dxIn:v.world.x-a.x,dyIn:v.world.z-a.z}];}
 if(t.pool){const p=t.pool;if(h.part==='move')return [{type:'pool.move',id:p.id,dxIn:x,dzIn:z}];if(h.part==='rotate')return [{type:'pool.rotate',id:p.id,rotationDeg:((p.rotationDeg+v.angleDeg+540)%360)-180}];if(h.part==='elevation')return [{type:'pool.edit',id:p.id,patch:{copingTopElevationIn:p.copingTopElevationIn+v.dyIn}}];if(h.part==='point'){const a=t.points[h.index??0];return [poolPointCommand(p,h.index??0,v.world.x-a.x,v.world.z-a.z)];}}
 if(t.part){const p=t.part,values=componentEditValues(data,p);
  if(p.kind==='deck'){const level=p.level??1;if(h.part==='point'){const a=t.points[h.index??0];return [{type:'boundary.move',level,target:'point',index:h.index??0,dxIn:v.world.x-a.x,dyIn:v.world.z-a.z}];}if(h.part==='elevation'){return [{type:'design.patch',patch:level===1?{height:data.height+v.dyIn}:level===2?{height2:data.height2+v.dyIn}:{level3:{...data.level3!,heightIn:data.level3!.heightIn+v.dyIn}}}];}if(h.part==='resize')return [{type:'design.patch',patch:level===1?{width:(t.width+2*x)/12,length:(t.depth+2*z)/12}:level===2?{width2:(t.width+2*x)/12,length2:(t.depth+2*z)/12}:{level3:{...data.level3!,widthFt:(t.width+2*x)/12,lengthFt:(t.depth+2*z)/12}}}];}
  if(p.kind==='house'||p.kind==='wall')return [{type:'component.edit',id:p.id,edit:{action:'update',fields:{offsetIn:Number(values.offsetIn)+x}}}];
  if(p.kind==='opening'){const house=getHouseConfig(data),opening=house.openings.find(o=>o.id===p.refId)!,wall=getHouseWalls(data).find(w=>w.id===openingWallId(opening,house))!;const delta=((wall.b.x-wall.a.x)*x+(wall.b.y-wall.a.y)*z)/(wall.lengthIn**2)*100;return [{type:'component.edit',id:p.id,edit:{action:'update',fields:h.part==='elevation'?{bottomIn:opening.bottomIn+v.dyIn}:{offsetPct:opening.offsetPct+delta}}}];}
  if(p.kind==='screen'){const edge=extrasLayout(data,model).screenHandles.find(s=>s.id===p.refId)?.edge;if(!edge||edge.available-edge.len<.01)throw Error('This screen has no clear travel along its edge.');const delta=(edge.dx*x+edge.dz*z)*(edge.reversed?-1:1)/(edge.available-edge.len)*100;return [{type:'component.edit',id:p.id,edit:{action:'update',fields:{offsetPct:Number(values.offsetPct)+delta}}}];}
 }
 throw Error('This part follows its owning assembly. Use the selected part’s inspector for its shared settings.');
}
/** Cheap live geometry uses the same pure operations; final preview also runs strict import and full estimate validation. */
export function sceneDraft(data:DeckData,model:DeckTakeoff,commands:AgentCommand[]):DeckData{
 let next=data;for(const c of commands){if(c.type==='objects.edit')next={...next,...editObjects(next,c.ids,c.edit)};else if(c.type==='landscape.edit')next={...next,...applyLandscapeEdit(next,c.id,c.edit)};else if(c.type.startsWith('pool.'))next={...next,...applyPoolCommand(next,c as Extract<AgentCommand,{type:`pool.${string}`}>) };else if(c.type==='yard.move'){next={...next,yardFeatures:next.yardFeatures?.map(f=>f.id===c.id?yardShapePull(f,c.target,c.index??0,c.dxIn,c.dyIn):f)};}else if(c.type==='yard.curve'){next={...next,yardFeatures:next.yardFeatures?.map(f=>f.id===c.id?curveYardEdge(f,c.index,c.bulgeIn):f)};}else if(c.type==='boundary.move'){const b=editableBoundaries(next,model).find(b=>b.level===c.level);if(!b)throw Error('Choose a current deck boundary.');const p=moveBoundary(b.points,c.target,c.index??0,c.dxIn,c.dyIn),patch=boundaryPatch(next,c.level,p,b.offset,model);if(!patch)throw Error('Boundary edit conflicts with geometry or locks.');next={...next,...patch};}else if(c.type==='yard.finished'){if(c.edit.action!=='level')throw Error('Unsupported live elevation edit.');const elevation=c.edit.elevationIn;next={...next,yardFeatures:next.yardFeatures?.map(f=>f.id===c.id?{...f,finishedElevationIn:elevation,wallTopSteps:f.wallTopSteps?.map(s=>({...s,elevationIn:s.elevationIn+elevation-f.finishedElevationIn!}))}:f)};}else if(c.type==='component.edit'){const result=applyComponentEdit(next,model,c.id,c.edit);if('error'in result)throw Error(result.error);next={...next,...result.patch};}else if(c.type==='design.patch')next={...next,...c.patch};}
 return next;
}
