import {useArchitectKeys,revealControl} from './architectKeys';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {DeckData} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import type {SelectionState} from './selectionState';
import {sceneEditTarget,sceneEditCommands,sceneDraft} from './sceneEditCommands';
import type {SceneDragTarget,SceneDragValue,SceneEditInteraction,SceneEditMode} from './sceneEditTypes';
import {useHardscapePreview} from './useHardscapePreview';
import EditReview from './EditReview';
import './landscapeEditing.css';
export default function SceneEditingWorkspace({data,model,selection,onSelection,onApply,onGeometry,children}:{data:DeckData;model:DeckTakeoff;selection:SelectionState;onSelection:(s:SelectionState)=>void;onApply:(patch:Partial<DeckData>)=>void;onGeometry:(d:DeckData|null)=>void;children:(interaction:SceneEditInteraction)=>ReactNode}){
 const [mode,setMode]=useState<SceneEditMode>('move'),[snapIn,setSnap]=useState(1),[error,setError]=useState(''),[dx,setDx]=useState(0),[dz,setDz]=useState(0),[dy,setDy]=useState(0),[angle,setAngle]=useState(0),target=sceneEditTarget(data,model,selection),effective=target.modes.includes(mode)?mode:target.modes[0]??'move';
 const flow=useHardscapePreview(data,onApply,onGeometry,next=>{const patch:Partial<DeckData>={};for(const key of Object.keys(next) as (keyof DeckData)[])if(JSON.stringify(next[key])!==JSON.stringify(data[key]))(patch as Record<string,unknown>)[key]=next[key];return patch;});
 const generation=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const cancel=()=>{generation.current++;if(timer.current)clearTimeout(timer.current);timer.current=null;flow.cancel();onGeometry(null);setError('');};
 useEffect(()=>{cancel();},[data,JSON.stringify(selection)]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);if(timer.current)clearTimeout(timer.current);onGeometry(null);};},[]);
 const activate=(next:SceneEditMode)=>{if(!target.modes.includes(next)||target.locked)return false;cancel();setMode(next);};
 useArchitectKeys({t:()=>activate('move'),m:()=>activate('move'),r:()=>activate('rotate'),s:()=>activate('resize'),e:()=>activate('shape'),'ctrl+g':()=>setSnap(v=>v?0:1),g:()=>revealControl(document.querySelector('.dd-scene-edit-toolbar input')),enter:()=>revealControl(document.querySelector('.dd-scene-edit-toolbar input'))});
 const commands=(h:SceneDragTarget,v:SceneDragValue)=>sceneEditCommands(data,model,selection,h,v);
 const interaction:SceneEditInteraction={mode:effective,snapIn,onDraft:(h,v)=>{if(timer.current)clearTimeout(timer.current);const revision=++generation.current;timer.current=setTimeout(()=>{if(revision!==generation.current)return;try{const next=sceneDraft(data,model,commands(h,v));onGeometry(next);setError('');}catch(e){onGeometry(null);setError((e as Error).message);}},35);},onFinish:(h,v)=>{generation.current++;if(timer.current)clearTimeout(timer.current);timer.current=null;try{setError('');void flow.preview(commands(h,v));}catch(e){onGeometry(null);setError((e as Error).message);}},onCancel:cancel};
 return <>{(selection.hardscape||selection.partIds.length>0||!!selection.objectIds?.length)&&<div className="dd-scene-edit-toolbar" aria-label="3D edit controls"><strong>{target.label}</strong><div className="dd-area-actions">{target.modes.map(m=><button type="button" key={m} aria-pressed={effective===m} onClick={()=>{cancel();setMode(m);}}>{m[0].toUpperCase()+m.slice(1)}</button>)}{target.ids.length>0&&data.editorOrganization?.groups.filter(g=>g.objectIds.some(id=>target.ids.includes(id))).map(g=><button type="button" key={g.id} onClick={()=>onSelection({...selection,objectIds:g.objectIds})}>Select group: {g.name}</button>)}</div>{target.locked?<p>Locked — unlock the object, group members or layer before editing.</p>:target.modes.length?<><p className="dd-area-hint">Select an object, then drag its handle. Drag elsewhere to orbit. Release to review; Apply creates one undo step.</p><details><summary>Numeric adjustments and snapping</summary><div className="dd-area-fields"><label>Snap (in)<input type="number" min="0" max="120" step=".125" value={snapIn} onChange={e=>setSnap(Math.max(0,Math.min(120,Number(e.target.value))))}/></label><label>Across Δ (in)<input type="number" value={dx} onChange={e=>setDx(Number(e.target.value))}/></label><label>Out Δ (in)<input type="number" value={dz} onChange={e=>setDz(Number(e.target.value))}/></label>{target.modes.includes('elevation')&&<label>Elevation Δ (in)<input type="number" value={dy} onChange={e=>setDy(Number(e.target.value))}/></label>}{target.modes.includes('rotate')&&<label>Rotation Δ (°)<input type="number" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label>}</div>{effective!=='shape'&&<button type="button" disabled={flow.busy} onClick={()=>interaction.onFinish({part:effective},{dxIn:dx,dzIn:dz,dyIn:dy,angleDeg:angle,world:{x:target.x+dx,z:target.z+dz}})}>Preview numeric {effective}</button>}</details></>:<p>Inspect this generated part through its owning assembly settings.</p>}{error&&<p role="alert" className="dd-area-error">{error}</p>}<EditReview flow={flow} data={data} label="3D edit"/></div>}{children(interaction)}</>;
}
