import type {AssistedSelection} from './naturalLanguageCommands';
import {LANDSCAPE_SURFACES,landscapeSurface} from '../landscapeSurfaces';
import {arcGeometry} from '../circularArcs';
import type {AgentSnapshot,AgentCommand} from './deckAgentController';
export function parseSiteInstruction(text:string,snapshot:AgentSnapshot,selection?:AssistedSelection):{command:AgentCommand;summary:string[]}|{clarification:string}|null{
 let m:RegExpMatchArray|null;
 const selectedIds=selection?.objectIds?.length?selection.objectIds:selection?.hardscape?[selection.hardscape.id]:[],groupTarget=(name:string)=>{if(/^(selected|this)( objects| group| selection)?$/.test(name))return selectedIds;return snapshot.design.editorOrganization?.groups.find(g=>g.name.toLowerCase()===name||g.id.toLowerCase()===name)?.objectIds??[];};
 if((m=text.match(/^move (.+?) (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in) (left|right|out|toward house)$/))){const ids=groupTarget(m[1]);if(ids.length){const n=Number(m[2])*(/^(feet|foot|ft)$/.test(m[3])?12:1);return {command:{type:'objects.edit',ids,edit:{action:'move',dxIn:m[4]==='left'?-n:m[4]==='right'?n:0,dzIn:m[4]==='toward house'?-n:m[4]==='out'?n:0}},summary:[`Preview moving ${ids.length} selected objects ${m[2]} ${m[3]} ${m[4]}.`]};}}
 if((m=text.match(/^rotate (.+?) (-?\d+(?:\.\d+)?) (degrees|degree|deg)$/))){const ids=groupTarget(m[1]);if(ids.length){const points=ids.flatMap(id=>{const o=snapshot.design.landscapeObjects?.find(o=>o.id===id)??snapshot.design.pools?.find(o=>o.id===id),f=snapshot.design.yardFeatures?.find(o=>o.id===id),t=snapshot.design.siteModel?.transitions?.find(o=>o.id===id);return o?[{x:o.xIn,z:o.zIn}]:f?[{x:f.xFt*12,z:f.zFt*12}]:t?[{x:t.a.points[0].x,z:t.a.points[0].y}]:[];});if(points.length!==ids.length)return {clarification:'A selected group member is missing. Select the current objects again.'};return {command:{type:'objects.edit',ids,edit:{action:'rotate',angleDeg:Number(m[2]),pivotXIn:points.reduce((n,p)=>n+p.x,0)/points.length,pivotZIn:points.reduce((n,p)=>n+p.z,0)/points.length}},summary:[`Preview rotating ${ids.length} selected objects ${m[2]} degrees about their shared centre.`]};}}
 const target=(name:string)=>{const areas=snapshot.design.landscapeObjects?.filter(o=>o.kind==='bed')??[];return /^(this|selected)( area| garden| green)?$/.test(name)?areas.filter(o=>o.id===selection?.hardscape?.id):areas.filter(o=>o.name.toLowerCase()===name||o.id.toLowerCase()===name);};
 if((m=text.match(/^(?:make|set|change) (.+?)(?: shape)?(?: to)? (rectangle|circle|oval|rounded rectangle|kidney)$/))){const hits=target(m[1]);if(hits.length!==1)return {clarification:'Select one landscape area or name it exactly.'};return {command:{type:'landscape.edit',id:hits[0].id,edit:{action:'preset',preset:(m[2]==='rounded rectangle'?'rounded':m[2]) as 'rectangle'|'circle'|'oval'|'rounded'|'kidney'}},summary:[`Preview ${hits[0].name} as ${m[2]}; cup positions remain unchanged.`]};}
 if((m=text.match(/^(?:resize|set) (.+?)(?: size)?(?: to)? (\d+(?:\.\d+)?) by (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in)$/))){const hits=target(m[1]);if(hits.length){if(hits.length!==1)return {clarification:'Select one landscape area or name it exactly.'};const scale=/^(feet|foot|ft)$/.test(m[4])?12:1;return {command:{type:'landscape.edit',id:hits[0].id,edit:{action:'resize',widthIn:Number(m[2])*scale,depthIn:Number(m[3])*scale}},summary:[`Preview ${hits[0].name} at ${m[2]} by ${m[3]} ${m[4]}. Circular arcs require uniform scaling.`]};}}
 if((m=text.match(/^(?:set|change) (.+?) edge (\d+) radius(?: to)? (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in)$/))){const hits=target(m[1]);if(hits.length){if(hits.length!==1)return {clarification:'Select one landscape area or name it exactly.'};return {command:{type:'landscape.edit',id:hits[0].id,edit:{action:'radius',ring:0,index:Number(m[2])-1,radiusIn:Number(m[3])*(/^(feet|foot|ft)$/.test(m[4])?12:1)}},summary:[`Preview ${hits[0].name} edge ${m[2]} radius.`]};}}

 if((m=text.match(/^(?:set|change) (.+?) (?:surface|material)(?: to)? (.+)$/))){const hits=snapshot.design.landscapeObjects?.filter(o=>o.kind==='bed'&&(o.name.toLowerCase()===m![1]||o.id.toLowerCase()===m![1]))??[],finish=LANDSCAPE_SURFACES.find(s=>s.name.toLowerCase()===m![2]);if(!hits.length||!finish)return null;if(hits.length!==1)return {clarification:'Use an exact unique landscape area name.'};const objects=snapshot.design.landscapeObjects!.map(o=>{if(o.id!==hits[0].id)return o;const {mulchDepthIn,puttingCups,...rest}=o;return {...rest,assetId:finish.id,surfaceDepthIn:finish.defaultDepthIn,...finish.id==='putting-green'?{puttingCups:puttingCups??[]}:{}};});return {command:{type:'design.patch',patch:{landscapeObjects:objects}},summary:[`Set ${hits[0].name} to ${landscapeSurface(finish.id)!.name}; review finish depth and quantities before applying.`]};}

 const transitions=snapshot.design.siteModel?.transitions??[];
 const transitionLength=(b:typeof transitions[number]['a'])=>b.points.slice(0,-1).reduce((n,p,i)=>{const q=b.points[i+1],arc=b.curves?.find(c=>c.edge===i);return n+(arc?arcGeometry(p,q,arc.bulgeIn).lengthIn:Math.hypot(q.x-p.x,q.y-p.y));},0);
 if((m=text.match(/^(?:delete|remove) grading transition (.+)$/))){const hits=transitions.filter(t=>t.id.toLowerCase()===m![1]||t.name.toLowerCase()===m![1]);if(hits.length!==1)return {clarification:'Name one current grading transition exactly.'};return {command:{type:'site.transition.remove',id:hits[0].id},summary:[`Remove ${hits[0].name}; review restored ground and quantities.`]};}
 if((m=text.match(/^(?:set|change) grading transition (.+?) boundary (a|b) elevation(?: to)? (-?\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in)$/))){const hits=transitions.filter(t=>t.id.toLowerCase()===m![1]||t.name.toLowerCase()===m![1]);if(hits.length!==1)return {clarification:'Name one current grading transition exactly.'};const t=structuredClone(hits[0]),side=m[2] as 'a'|'b',elevationIn=Number(m[3])*(/^(feet|foot|ft)$/.test(m[4])?12:1);t[side]={...t[side],elevationSource:'specified',levels:[{stationIn:0,elevationIn},{stationIn:transitionLength(t[side]),elevationIn}]};return {command:{type:'site.transition',transition:t},summary:[`${t.name} boundary ${side.toUpperCase()}: fixed elevation ${elevationIn} inches on the project datum.`]};}
 if((m=text.match(/^create grading transition ([\w-]+) from grading (.+?) edge (\d+) offset (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in) (left|right)$/))){const hits=snapshot.design.siteModel?.grading.filter(g=>g.id.toLowerCase()===m![2]||g.name.toLowerCase()===m![2])??[];if(hits.length!==1)return {clarification:'Name a current proposed grading region and its exact edge index.'};const g=hits[0],i=Number(m[3]),a=g.boundary[i],b=g.boundary[(i+1)%g.boundary.length];if(!a||!b)return {clarification:'Choose an existing grading edge index.'};const run=Math.hypot(b.x-a.x,b.y-a.y),amount=Number(m[4])*(/^(feet|foot|ft)$/.test(m[5])?12:1)*(m[6]==='left'?1:-1);if(!run||!amount)return {clarification:'Enter a positive transition width and a nonzero grading edge.'};const dx=-(b.y-a.y)/run*amount,dz=(b.x-a.x)/run*amount;return {command:{type:'site.transition',transition:{id:m[1],name:m[1],enabled:true,a:{points:[a,b],elevationSource:'proposed'},b:{points:[{x:a.x+dx,y:a.y+dz},{x:b.x+dx,y:b.y+dz}],elevationSource:'existing'}}},summary:[`Create ${m[1]}: proposed grading edge to existing ground, ${Math.abs(amount)} inches ${m[6]} of the directed edge. Missing survey coverage stays pending.`]};}

 if((m=text.match(/^(?:set|change) (?:site|elevation) point ([\w-]+)(?: elevation)?(?: to)? (-?\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in|metres|meters|m)$/))){const p=snapshot.design.siteModel?.points.find(p=>p.id.toLowerCase()===m![1]);if(!p)return {clarification:'Use a current measured point ID from the site workspace.'};const elevationIn=Number(m[2])*(/^(feet|foot|ft)$/.test(m[3])?12:/^(metres|meters|m)$/.test(m[3])?1000/25.4:1);return {command:{type:'site.point',id:p.id,xIn:p.xIn,zIn:p.zIn,elevationIn},summary:[`${p.id}: elevation ${elevationIn.toFixed(2)} inches on the existing site datum.`]};}
 if((m=text.match(/^move (.+?) (-?\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in) (left|right|toward house|out)$/))){const all=[...(snapshot.design.landscapeObjects??[]),...(snapshot.design.yardFeatures??[]),...transitions],hits=all.filter(o=>o.name.toLowerCase()===m![1]||o.id.toLowerCase()===m![1]);if(!hits.length)return null;if(hits.length!==1)return {clarification:'Use an exact unique object name or ID.'};const amount=Number(m[2])*(/^(feet|foot|ft)$/.test(m[3])?12:1),direction=m[4],dxIn=direction==='left'?-amount:direction==='right'?amount:0,dzIn=direction==='toward house'?-amount:direction==='out'?amount:0;return {command:{type:'objects.edit',ids:[hits[0].id],edit:{action:'move',dxIn,dzIn}},summary:[`Move ${hits[0].name}: ${amount} inches ${direction}.`]};}
 if((m=text.match(/^(lock|unlock) (.+)$/))){const all=[...(snapshot.design.landscapeObjects??[]),...(snapshot.design.yardFeatures??[]),...transitions],hits=all.filter(o=>o.name.toLowerCase()===m![2]||o.id.toLowerCase()===m![2]);if(hits.length===1)return {command:{type:'objects.edit',ids:[hits[0].id],edit:{action:'lock',locked:m[1]==='lock'}},summary:[`${m[1]} ${hits[0].name}.`]};if(hits.length>1)return {clarification:'Use a unique object name or ID.'};}
 if((m=text.match(/^(?:set|change) (.+?) radius(?: to)? (\d+(?:\.\d+)?) (feet|foot|ft|inches|inch|in)$/))){const hits=snapshot.design.yardFeatures?.filter(o=>o.kind!=='water-feature'&&(o.name.toLowerCase()===m![1]||o.id.toLowerCase()===m![1]))??[];if(hits.length!==1)return {clarification:'Use an exact patio or wall name for its first control edge radius.'};return {command:{type:'yard.radius',id:hits[0].id,index:0,radiusIn:Number(m[2])*(/^(feet|foot|ft)$/.test(m[3])?12:1)},summary:[`Set ${hits[0].name} first control edge radius to ${m[2]} ${m[3]}.`]};}
 return null;
}

