import type {DeckTakeoff} from '../deckTakeoff';
import RefitGeometry from './StairRefitGeometry';
import './yardElevationEditor.css';
import {useEffect,useRef,useState} from 'react';
import type {DeckData} from '../types';
import type {Update} from './fields';
export default function StairRefitEditor({data,update}:{data:DeckData;update:Update}){
 const [support,setSupport]=useState('terrain'),[patch,setPatch]=useState<Partial<DeckData>>(),[summary,setSummary]=useState<string[]>([]),[geometry,setGeometry]=useState<{before:DeckTakeoff;after:DeckTakeoff}>(),[busy,setBusy]=useState(false),[error,setError]=useState('');const current=useRef(data),source=useRef(data),previewIntent=useRef(0);current.current=data;
 useEffect(()=>{previewIntent.current++;setPatch(undefined);setSummary([]);setError('');setBusy(false);},[data]);
 const preview=async()=>{const snapshot=data,intent=++previewIntent.current;setBusy(true);setError('');setPatch(undefined);try{const [{prepareStairRefitPreview},{calculateDeckReleaseEstimate}]=await Promise.all([import('./stairRefitPreview'),import('../deckRelease')]);if(current.current!==snapshot||intent!==previewIntent.current)return;const result=await prepareStairRefitPreview(snapshot,{surface:support==='terrain'?'terrain':'patio',...(support==='terrain'?{}:{patioId:support})});if(current.current!==snapshot||intent!==previewIntent.current)return;source.current=snapshot;setSummary([...result.summary,...result.warnings]);if(result.status==='ready'){const before=calculateDeckReleaseEstimate(snapshot),after=calculateDeckReleaseEstimate({...snapshot,...result.patch});setPatch(result.patch);setGeometry({before:before.model,after:after.model});setSummary([...result.summary,...result.warnings,`Known priced scope including HST: $${before.total.toFixed(2)} → $${after.total.toFixed(2)}${after.quoteRequired.length?' · unresolved construction inputs remain':''}`,`Stair treads: ${before.model.quantities.stairTreads} → ${after.model.quantities.stairTreads}`]);}}catch(e){if(current.current===snapshot&&intent===previewIntent.current)setError((e as Error).message);}finally{if(current.current===snapshot&&intent===previewIntent.current)setBusy(false);}};
 return <section className="dd-finished-level" aria-label="Stair elevation refit"><h4>Fit stairs to the measured landing</h4><p>Upper deck stays fixed. Preview checks the full bottom landing footprint and proposes equal risers. Applying does not change ground.</p><label>Bottom support<select aria-label="Stair bottom support" value={support} onChange={e=>{previewIntent.current++;setBusy(false);setSupport(e.target.value);setPatch(undefined);setSummary([]);}}><option value="terrain">Proposed ground</option>{data.yardFeatures?.filter(f=>f.enabled&&f.kind==='patio').map(f=><option key={f.id} value={f.id}>{f.name} · finished patio surface</option>)}</select></label><button type="button" disabled={busy||data.stairFlights===0} onClick={()=>void preview()}>{busy?'Checking landing…':'Preview stair refit'}</button>{summary.length>0&&<ul>{summary.map((s,i)=><li key={i}>{s}</li>)}</ul>}{error&&<p role="alert">{error}</p>}{patch&&<>{geometry&&<RefitGeometry before={geometry.before} after={geometry.after}/>}<button type="button" onClick={()=>{if(current.current!==source.current){setError('Design changed. Preview the stairs again.');setPatch(undefined);return;}try{update(patch);setPatch(undefined);}catch(e){setError((e as Error).message);}}}>Apply stair refit</button><button type="button" onClick={()=>setPatch(undefined)}>Discard stair preview</button></>}</section>;
}
