import {useEffect,useRef,useState,type PointerEvent,type RefObject} from 'react';
import {createPortal} from 'react-dom';
import type {DeckData} from '../types';
import type {DeckTakeoff} from '../deckTakeoff';
import type {PlanFrame} from '../ConstructionPlan';
import {stairPathOffset} from '../lib/stairPath';
import {stairShapeContext,resizeStairPoint,extendStairPoints,stairShapePolygon} from './stairShapeEdits';
import type {Update} from './fields';
export default function StairShapeEditor({data,model,frame,update,toolbar}:{data:DeckData;model:DeckTakeoff;frame:PlanFrame;update:Update;toolbar?:RefObject<HTMLElement|null>}){
 const c=stairShapeContext(data,model),svg=useRef<SVGSVGElement>(null),[scale,setScale]=useState(1),[draft,setDraft]=useState<Partial<DeckData>|null>(null),[error,setError]=useState('');
 const drag=useRef<{id:number;index:number;matrix:DOMMatrix;patch:Partial<DeckData>|null;capture:Element;x:number;y:number}|null>(null);
 const cancel=()=>{const d=drag.current;drag.current=null;setDraft(null);if(d?.capture.hasPointerCapture(d.id))d.capture.releasePointerCapture(d.id);};
 useEffect(()=>{cancel();},[data]);
 useEffect(()=>{const stop=()=>cancel(),key=(e:KeyboardEvent)=>{if(e.key==='Escape'){cancel();setError('');}},hidden=()=>{if(document.hidden)cancel();};window.addEventListener('blur',stop);window.addEventListener('keydown',key);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('blur',stop);window.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',hidden);};},[]);
 useEffect(()=>{const el=svg.current;if(!el)return;const measure=()=>{const m=el.getScreenCTM();if(m)setScale(Math.hypot(m.a,m.b));};measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect();},[frame]);
 const resolved=c.resolve(c.points);if(!data.stairFlights||!resolved.segments.length)return null;
 const points=draft?.stairPath?.points??c.points,tread=draft?.stairTreadDepthIn??c.tread;
 const shown=draft&&!data.stairPath&&draft.stairWidth?(()=>{const p=c.primary!,w=Number(draft.stairWidth),t=(p.len-w)*Number(draft.stairOffset)/100;return [{x:p.a.x+p.dir.x*t-c.shift.x,y:p.a.y+p.dir.y*t-c.shift.y},{x:p.a.x+p.dir.x*(t+w)-c.shift.x,y:p.a.y+p.dir.y*(t+w)-c.shift.y}];})():points;
 const outer=stairPathOffset(c.resolve(shown).segments,Math.max(1,c.risers-1)*tread),depthPoint={x:(outer[0].x+outer[1].x)/2,y:(outer[0].y+outer[1].y)/2};
 const apply=(patch:Partial<DeckData>)=>{if(Object.entries(patch).some(([k,v])=>JSON.stringify(data[k as keyof DeckData])!==JSON.stringify(v)))update(patch);};
 const down=(index:number)=>(e:PointerEvent<SVGCircleElement>)=>{if(e.button!==0||drag.current)return;const matrix=svg.current?.getScreenCTM()?.inverse();if(!matrix)return;e.preventDefault();e.stopPropagation();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);setError('');drag.current={id:e.pointerId,index,matrix,patch:null,capture:e.currentTarget,x:e.clientX,y:e.clientY};};
 const move=(e:PointerEvent)=>{const d=drag.current;if(!d||d.id!==e.pointerId||Math.hypot(e.clientX-d.x,e.clientY-d.y)<2)return;e.stopPropagation();const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(d.matrix),local={x:p.x-c.shift.x,y:p.y-c.shift.y};try{let patch:Partial<DeckData>;
 if(d.index===-1){const s=resolved.segments[0],distance=(local.x-s.origin.x)*s.outward.x+(local.y-s.origin.y)*s.outward.y;patch={stairTreadDepthIn:Math.max(10,Math.min(24,Math.round(distance/Math.max(1,c.risers-1)*4)/4))};if(data.stairTargets?.some(t=>t.treadDepthIn!==undefined))throw Error('This flight has a custom elevation target. Edit its tread depth in Stairs & railings.');}
 else patch=resizeStairPoint(data,c,d.index,local);d.patch=patch;setDraft(patch);setError('');}catch(e){d.patch=null;setDraft(null);setError((e as Error).message);}};
 const up=(e:PointerEvent)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;move(e);const p=d.patch;cancel();if(p)apply(p);};
 const add=(start:boolean)=>{try{apply(extendStairPoints(c,start));setError('');}catch(e){setError((e as Error).message);}};
 const handles=[...shown.map((p,i)=>({p,index:i,label:'Stair point '+(i+1),editable:i===0||i===shown.length-1})),{p:depthPoint,index:-1,label:'Stair run depth',editable:true}];
 return <><svg ref={svg} viewBox={frame.viewBox} style={{position:'absolute',inset:0,width:'100%',height:'100%',overflow:'visible',pointerEvents:'none'}} aria-label="Stair size and shape controls">
 {draft&&<polygon className="dd-plan-ghost" points={stairShapePolygon(c,shown,tread).map(p=>p.x+','+p.y).join(' ')}/>}
 {handles.map(({p,index,label,editable})=><circle key={index} cx={p.x+c.shift.x} cy={p.y+c.shift.y} r={(editable?9:5)/scale} fill={index===-1?'#d296dc':'#fff9ed'} stroke="#9b613b" strokeWidth={2/scale} style={{pointerEvents:editable?'all':'none',cursor:'ew-resize',touchAction:'none'}} role="button" aria-label={label} tabIndex={editable?0:-1} onPointerDown={down(index)} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel} onLostPointerCapture={cancel} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();try{const step=e.shiftKey?12:1;if(index===-1)apply({stairTreadDepthIn:Math.max(10,Math.min(24,c.tread+(e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1)*.25))});else apply(resizeStairPoint(data,c,index,{x:p.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),y:p.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)}));}catch(e){setError((e as Error).message);}}}><title>{label}</title></circle>)}
 </svg>{toolbar?.current&&createPortal(<section aria-label="Stair shape tools" style={{display:'grid',gap:8}}><p className="dd-note">Pull the cream end points to resize the opening. Pull the purple point to lengthen the run (10–24 in treads).</p><button type="button" className="dd-secondary" style={{minHeight:44}} onClick={()=>add(true)}>Add stair point at start</button><button type="button" className="dd-secondary" style={{minHeight:44}} onClick={()=>add(false)}>Add stair point at end</button>{data.stairPath&&c.points.length>2&&<button type="button" className="dd-secondary" style={{minHeight:44}} onClick={()=>apply({stairPath:{points:c.points.slice(0,-1)}})}>Remove last stair point</button>}<p className="dd-note">Added points wrap the stairs around exposed deck corners. Corner points stay attached to those corners. Each release saves one Undo step.</p>{draft&&<p role="status">Release to save stair size.</p>}{error&&<p role="alert">{error}</p>}</section>,toolbar.current)}</>;
}
