import type {AgentSnapshot,AgentCommand} from './deckAgentController';
import type {AssistedSelection} from './naturalLanguageCommands';
export function parseStepInstruction(text:string,snapshot:AgentSnapshot,selection:AssistedSelection):{command:AgentCommand;summary:string[]}|{clarification:string}|null{
 const target=selection.hardscape;if(!target||target.kind!=='yard')return null;const feature=snapshot.design.yardFeatures?.find(f=>f.id===target.id);if(!feature?.stepAssembly&&!feature?.stoneSteps)return null;
 if(/^(convert|upgrade) (?:these |this |selected )?(?:stone )?(?:steps|stairs)(?: to advanced(?: steps)?)?$/.test(text))return {command:{type:'yard.stepConvert',id:feature.id},summary:['Preview conversion without moving finished levels or changing stock.']};
 const course=text.match(/^(?:set|change) (?:this |selected |row )?(support|riser)(?: supporting)? courses?(?: to)? (\d+)$/),dimension=text.match(/^(?:set|change) (?:this |selected )?(tread|riser|support) (width|depth|thickness|joint)(?: to)? (\d+(?:\.\d+)?) (inches|inch|in|feet|foot|ft)$/),layout=text.match(/^(?:make|set) (?:this |selected )?(?:flight|steps|stairs)(?: layout)?(?: to)? (straight|flared|curved|wraparound)$/),width=text.match(/^(?:set|change) (?:this |selected )?flight (width|run|radius)(?: to)? (\d+(?:\.\d+)?) (inches|inch|in|feet|foot|ft)$/);
 if(!course&&!dimension&&!layout&&!width)return null;if(!feature.stepAssembly)return {clarification:'Preview and apply advanced conversion before editing flight or row assemblies.'};const a=structuredClone(feature.stepAssembly),flight=a.flights.find(f=>f.id===target.flightId)??(a.flights.length===1?a.flights[0]:undefined);if(!flight)return {clarification:'Select a flight first.'};
 if(course){if(target.row===undefined)return {clarification:'Select the row whose course count you want to change.'};return {command:{type:'yard.stepRow',id:feature.id,flightId:flight.id,row:target.row,edit:{[course[1]==='support'?'courses':'riserCourses']:Number(course[2])}},summary:[`Row ${target.row+1}: ${course[1]} courses ${course[2]}.`]};}
 if(dimension){const part=dimension[1] as 'tread'|'riser'|'support',o=flight.rowOverrides.find(o=>o.row===target.row),stock=structuredClone(o?.[part]??flight[part]??a[part]??a.tread),key=dimension[2]+'In';stock[key as 'widthIn']=Number(dimension[3])*(/^(feet|foot|ft)$/.test(dimension[4])?12:1);delete stock.productId;delete stock.finishId;delete stock.unitId;delete stock.installationNote;if(target.row!==undefined)return {command:{type:'yard.stepRow',id:feature.id,flightId:flight.id,row:target.row,edit:{[part]:stock}},summary:[`Preview ${part} ${dimension[2]} for row ${target.row+1}; finished levels stay fixed.`]};flight[part]=stock;}
 if(layout)flight.layout=layout[1] as typeof flight.layout;if(width)flight[width[1]==='width'?'widthIn':width[1]==='run'?'runIn':'radiusIn']=Number(width[2])*(/^(feet|foot|ft)$/.test(width[3])?12:1);
 return {command:{type:'yard.stepAssembly',id:feature.id,assembly:a},summary:[`Preview ${flight.name} assembly edit; stock and site compatibility will be checked.`]};
}
