'use client';
import {useEffect,useState} from 'react';
import {SUPPLIER_UNITS,emptySupplierRateBook,readSupplierRateBook,previewSupplierRateImport,applySupplierRateImport,saveSupplierRateBook,type SupplierRateBook,type SupplierRatePreview,type SupplierRate} from '../supplierRateBook';
export default function SupplierRateBookEditor({onClose,onChanged}:{onClose?:()=>void;onChanged?:(book:SupplierRateBook)=>void}){
 const [book,setBook]=useState(emptySupplierRateBook),[source,setSource]=useState(''),[preview,setPreview]=useState<SupplierRatePreview|null>(null),[error,setError]=useState(''),[status,setStatus]=useState('Loading device ratebook…'),[busy,setBusy]=useState(true),[edit,setEdit]=useState<SupplierRate|null>(null),[editIndex,setEditIndex]=useState(-1);
 const loaded=(value:SupplierRateBook)=>{setBook(value);setPreview(null);setError('');setStatus(`${value.rates.length} private rates saved on this device.`);onChanged?.(value);};
 useEffect(()=>{let active=true;void readSupplierRateBook().then(value=>{if(active){loaded(value);setBusy(false);}},e=>{if(active){setError(e.message);setStatus('Not saved. Device storage is unavailable or the saved file is invalid.');setBusy(false);}});return ()=>{active=false;};},[]);
 async function perform(action:()=>Promise<SupplierRateBook>){setBusy(true);setError('');try{loaded(await action());setEdit(null);}catch(e){setError(e instanceof Error?e.message:'The ratebook was not saved.');setStatus('Not saved. The previous ratebook is preserved.');}finally{setBusy(false);}}
 const previewCsv=()=>{try{setPreview(previewSupplierRateImport(source,book));setError('');setStatus('Import preview only. Nothing has been saved.');}catch(e){setPreview(null);setError(e instanceof Error?e.message:'Invalid CSV.');}};
 return <section aria-label="Private supplier ratebook" className="dd-advanced">
  <div style={{display:'flex',justifyContent:'space-between',gap:16}}><h3>Private supplier ratebook</h3>{onClose&&<button type="button" onClick={onClose}>Close</button>}</div>
  <p>Use supplier quotes in CAD before HST. Supply price is per pack; delivery is per order; labour and equipment are per installed unit. Rates stay on this device and are excluded from public exports.</p>
  <p role="status">{status}</p>{error&&<p role="alert">{error}</p>}
  <label>Import supplier CSV <input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file){if(file.size>1_000_000){setError('Choose a CSV smaller than 1 MB.');return;}void file.text().then(text=>{setSource(text);setPreview(null);setStatus('CSV loaded. Preview it before applying.');},()=>setError('The CSV could not be read.'));}e.target.value='';}}/></label>
  <label style={{display:'block'}}>CSV content<textarea value={source} onChange={e=>{setSource(e.target.value);setPreview(null);}} rows={5} style={{width:'100%'}} placeholder="SKU,manufacturer,unit,packQuantity,price,currency,effectiveDate,delivery,labour,equipment"/></label>
  <p>Units: {SUPPLIER_UNITS.join(', ')}. Effective date: YYYY-MM-DD. Enter every fee, including explicit 0 where quoted.</p>
  <button type="button" disabled={busy||!source.trim()} onClick={previewCsv}>Preview import</button>
  {preview&&<><p>{preview.additions} additions, {preview.replacements} replacements; {preview.total} total rates after import.</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Manufacturer / SKU</th><th>Unit / pack</th><th>Supply CAD</th><th>Effective date</th></tr></thead><tbody>{preview.incoming.slice(0,20).map(rate=><tr key={`${rate.manufacturer}/${rate.sku}`}><td>{rate.manufacturer} / {rate.sku}</td><td>{rate.unit} / {rate.packQuantity}</td><td>{rate.price.toFixed(2)}</td><td>{rate.effectiveDate}</td></tr>)}</tbody></table></div>{preview.incoming.length>20&&<p>Showing the first 20 of {preview.incoming.length} validated rows.</p>}<button type="button" disabled={busy} onClick={()=>void perform(()=>applySupplierRateImport(preview))}>Apply validated import</button></>}
  <details><summary>Saved rates ({book.rates.length})</summary>{book.rates.slice(0,100).map((rate,index)=><p key={`${rate.manufacturer}/${rate.sku}`}>{rate.manufacturer} / {rate.sku} · ${rate.price.toFixed(2)} per {rate.packQuantity} {rate.unit} <button type="button" disabled={busy} onClick={()=>{setEdit({...rate});setEditIndex(index);}}>Edit</button></p>)}{book.rates.length>100&&<p>Showing the first 100. Update other SKUs through a validated CSV import.</p>}</details>
  {edit&&<fieldset><legend>Edit {edit.manufacturer} / {edit.sku}</legend>{(['packQuantity','price','delivery','labour','equipment'] as const).map(key=><label key={key} style={{display:'block'}}>{key==='price'?'Supply CAD per pack':key==='delivery'?'Delivery CAD per order':key==='labour'?'Labour CAD per installed unit':key==='equipment'?'Equipment CAD per installed unit':'Units per pack'}<input type="number" min={key==='packQuantity'?0.000001:0} step={key==='packQuantity'?'any':0.01} value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value===''?NaN:Number(e.target.value)})}/></label>)}<label>Effective date<input type="date" value={edit.effectiveDate} onChange={e=>setEdit({...edit,effectiveDate:e.target.value})}/></label><button type="button" disabled={busy} onClick={()=>void perform(()=>saveSupplierRateBook(book.rates.map((r,i)=>i===editIndex?edit:r),book.revision))}>Save quoted rate</button><button type="button" onClick={()=>setEdit(null)}>Cancel edit</button></fieldset>}
  <button type="button" disabled={busy||!book.rates.length} onClick={()=>void perform(()=>saveSupplierRateBook([],book.revision))}>Clear private ratebook</button>
 </section>;
}
