import {Field,type Update} from './fields';
import type {DeckData,UnderDeckConfig} from '../types';
import type {DeckEstimate} from '../designFacts';
import {CEILING_OPTIONS,DRAINAGE_OPTIONS,RETIRED_DRAINAGE,normalizeUnderDeck,underDeckConfig} from '../underDeckOptions';
import {dollars} from '../designFacts';

/** Lazy extras panel; configuration and the shared estimate ledger remain available in saved designs. */
export default function UnderDeckEditor({data,update,estimate}:{data:DeckData;update:Update;estimate:DeckEstimate}){
  const c=underDeckConfig(data),integrated=c.drainage==='dryspace'||c.drainage==='zipup';
  const write=(patch:Partial<UnderDeckConfig>)=>{const next=normalizeUnderDeck({...c,...patch});update({underDeck:next,hasDrainage:next.drainage!=='none'});};
  const pricing=estimate.sections.find(s=>s.title==='Under-deck options'),labour=pricing?.items.find(i=>i.name==='Under-deck installation planning allowance');
  return <section aria-label="Under-deck options"><h3>Under-deck options</h3><p className="dd-note">Plan a dry underside, a finished ceiling, or ground protection. Supply, ordering waste, delivery and installation allowances appear separately in the estimate. These options are recorded in the proposal; finish textures and mesh are not drawn in the 3D preview.</p><div className="dd-fields">
    <Field label="Under-deck drainage" hint="DrySpace and Zip-UP fit below the joists and include their finished ceiling."><select aria-label="Under-deck drainage" value={c.drainage} onChange={e=>write({drainage:e.target.value as UnderDeckConfig['drainage'],...(e.target.value==='none'?{ceiling:'none'}:{})})}>{c.drainage==='rainescape'&&<option value="rainescape" disabled>{RETIRED_DRAINAGE.rainescape}</option>}{Object.entries(DRAINAGE_OPTIONS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>
    <Field label="Under-deck ceiling finish" hint={integrated?'Your drainage system already includes the ceiling. It is charged once.':'A decorative ceiling is not waterproofing. Choose DrySpace or Zip-UP for a dry underside.'}><select aria-label="Under-deck ceiling finish" disabled={integrated} value={c.ceiling} onChange={e=>write({ceiling:e.target.value as UnderDeckConfig['ceiling']})}>{Object.entries(CEILING_OPTIONS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>
    {data.levels>1&&<Field label="Under-deck platform scope" hint="Drainage, ceiling and floor mesh apply to this selection. Gravel and fabric always use the combined ground footprint once."><select aria-label="Under-deck platform scope" value={c.scope} onChange={e=>write({scope:e.target.value as UnderDeckConfig['scope']})}><option value="main">Main deck only</option><option value="all">All deck platforms</option></select></Field>}
  </div><label className="dd-check"><input type="checkbox" checked={c.gravel} onChange={e=>write({gravel:e.target.checked})}/><span>Clear stone over weed fabric beneath the deck</span></label>{c.gravel&&<div className="dd-fields"><Field label="Under-deck gravel depth" hint="3/4 in clear stone, whole tonne caddy bags. Includes overlapping fabric and hand-spreading; major excavation and grading need a site quote."><input aria-label="Under-deck gravel depth" type="number" min={2} max={6} step={.5} value={c.gravelDepthIn} onChange={e=>write({gravelDepthIn:Number(e.target.value)})}/><small>inches</small></Field></div>}
    <label className="dd-check"><input type="checkbox" checked={c.floorMesh} onChange={e=>write({floorMesh:e.target.checked})}/><span>Insect mesh beneath deck-board gaps</span></label><p className="dd-note">Floor mesh blocks bugs coming through floor gaps. It does not screen open sides or create a mosquito-proof enclosure. A full enclosure needs separate side screens, a door, roof seals and suitable clear height. Weed fabric and gravel are ground protection, not an insect barrier.</p>
    {pricing&&<p className="dd-note">Under-deck planning allowance: {dollars(pricing.total)} before HST · {labour?.qty} crew-days budgeted. Confirm product availability, access, waterproof details and discharge before a fixed quote.</p>}
  </section>;
}
