import {useEffect,useRef,useState} from 'react';
import type {DeckData} from '../types';
import type {AgentCommand,AgentRequest,AgentSnapshot,DeckAgentController} from './deckAgentController';

/** Uses the same guarded operations as voice. The displayed candidate never enters history. */
export function useHardscapePreview(data:DeckData,apply:(patch:Partial<DeckData>)=>void,onGeometry?:(data:DeckData|null)=>void,commitFields?:(next:DeckData)=>Partial<DeckData>){
 const latest=useRef({data,apply,onGeometry,commitFields});latest.current={data,apply,onGeometry,commitFields};
 const owner=useRef(Symbol('edit-preview'));
 const controller=useRef<DeckAgentController|null>(null),generation=useRef(0),alive=useRef(true);
 const [candidate,setCandidate]=useState<{request:AgentRequest;before:AgentSnapshot;after:AgentSnapshot}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const cancel=()=>{generation.current++;setCandidate(null);setBusy(false);setError('');latest.current.onGeometry?.(null);};
 useEffect(()=>{cancel();},[data]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();},hidden=()=>{if(document.hidden)cancel();};window.addEventListener('keydown',key);window.addEventListener('blur',cancel);window.addEventListener('pointercancel',cancel,true);window.addEventListener('webglcontextlost',cancel,true);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('blur',cancel);window.removeEventListener('pointercancel',cancel,true);window.removeEventListener('webglcontextlost',cancel,true);document.removeEventListener('visibilitychange',hidden);};},[]);
 useEffect(()=>{const other=(e:Event)=>{if((e as CustomEvent).detail!==owner.current)cancel();};window.addEventListener('deckcraft-edit-preview',other);return()=>window.removeEventListener('deckcraft-edit-preview',other);},[]);
 useEffect(()=>{alive.current=true;return ()=>{alive.current=false;generation.current++;controller.current?.dispose();latest.current.onGeometry?.(null);};},[]);
 const getController=async()=>{if(controller.current)return controller.current;const {createDeckAgentController}=await import('./deckAgentController');if(!alive.current)throw Error('Inspector closed.');if(controller.current)return controller.current;controller.current=createDeckAgentController({getState:()=>({data:latest.current.data,view:'plan',openSections:[],canUndo:true,canRedo:false,ready:true}),commitDesign:next=>latest.current.apply(latest.current.commitFields?.(next)??{yardFeatures:next.yardFeatures,pools:next.pools}),undo:()=>{},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async predicate=>{const started=Date.now();while(alive.current&&!predicate({data:latest.current.data,view:'plan',openSections:[],canUndo:true,canRedo:false,ready:true})){if(Date.now()-started>15000)throw Error('Design did not acknowledge the edit.');await new Promise(resolve=>setTimeout(resolve,25));}if(!alive.current)throw Error('Inspector closed.');}});return controller.current;};
 const preview=async(commands:AgentCommand[])=>{window.dispatchEvent(new CustomEvent('deckcraft-edit-preview',{detail:owner.current}));const token=++generation.current,source=latest.current.data;setBusy(true);setError('');setCandidate(null);latest.current.onGeometry?.(null);try{const api=await getController(),before=api.read(),request:AgentRequest={id:crypto.randomUUID(),expectedRevision:before.revision,commands},answer=await api.preview(request);if(!alive.current||token!==generation.current||source!==latest.current.data)return;if(answer.ok===false)throw Error(answer.error.message);setCandidate({request,before,after:answer.snapshot});latest.current.onGeometry?.({...source,...answer.snapshot.design});}catch(e){if(alive.current&&token===generation.current)setError((e as Error).message);}finally{if(alive.current&&token===generation.current)setBusy(false);}};
 const commit=async()=>{if(!candidate)return;setBusy(true);setError('');try{const api=await getController(),answer=await api.execute({...candidate.request,id:crypto.randomUUID()});if(answer.ok===false)throw Error(answer.error.message);cancel();}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy(false);}};
 const differences=candidate?Object.entries(candidate.after.yardQuantities).filter(([k,v])=>typeof v==='number'&&Math.abs(v-Number(candidate.before.yardQuantities[k as keyof typeof candidate.before.yardQuantities]??0))>1e-7).map(([key,value])=>({key,before:Number(candidate.before.yardQuantities[key as keyof typeof candidate.before.yardQuantities]??0),after:Number(value)})):[];
 return {candidate,busy,error,cancel,preview,commit,differences};
}
