import {SECTION_BY_ID,type SectionId} from './sections';
export const WORKSPACE_TASKS:{title:string;items:{id:SectionId;label:string}[]}[]=[
  {title:'Design',items:[{id:'deck',label:'Shape & size'},{id:'house',label:'House'},{id:'boards',label:'Materials'},{id:'stairs',label:'Stairs & rails'},{id:'lighting',label:'Outdoor lighting'}]},
  {title:'Build & landscape',items:[{id:'extras',label:'Privacy & extras'},{id:'site',label:'Site & foundation'},{id:'backyard',label:'Backyard'}]},
  {title:'Your project',items:[{id:'proposal',label:'Proposal & files'}]},
];
const paths:Record<SectionId,string>={deck:'M4 4h11l5 5v11H4z M15 4v5h5',house:'m3 10 9-7 9 7 M5 9v12h14V9 M10 21v-7h4v7',boards:'M4 4h16v16H4z M4 9h16 M4 15h16 M10 4v5 M15 9v6 M8 15v5',stairs:'M3 20h6v-6h6V8h6V3 M3 3v17h18',lighting:'M9 18h6 M10 21h4 M8 14a6 6 0 1 1 8 0l-1 2H9z',extras:'M4 5v16 M10 5v16 M16 5v16 M22 5v16 M4 9h18 M4 17h18',site:'M3 18h18 M6 18v-5h12v5 M9 13V7h6v6 M3 7h18 M12 3v4',backyard:'M12 21v-6 M12 3 5 12h4l-5 5h16l-5-5h4z',proposal:'M5 3h10l4 4v14H5z M15 3v5h4 M8 12h8 M8 16h6'};
export function WorkspaceIcon({id}:{id:SectionId}){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[id]}/></svg>;}
export default function WorkspaceNavigation({active,onSelect,inspectorVisible=true,onCanvas}:{active:SectionId;onSelect:(id:SectionId)=>void;inspectorVisible?:boolean;onCanvas?:()=>void}){
  return <nav className="dd-workspace-nav" aria-label="Design tasks"><button type="button" className="dd-nav-canvas" aria-label="Show canvas" onClick={onCanvas}><span aria-hidden="true">←</span><span>Canvas</span></button>{WORKSPACE_TASKS.map(group=><details className="dd-nav-group" key={group.title} onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary')?.focus();}}}><summary>{group.title}</summary><div className="dd-nav-menu">{group.items.map(({id,label})=><button type="button" key={id} aria-label={SECTION_BY_ID[id].name} aria-current={active===id?'page':undefined} aria-expanded={active===id&&inspectorVisible} aria-controls={active===id?`dd-section-${id}-body`:undefined} onClick={e=>{onSelect(id);const menu=e.currentTarget.closest('details');if(menu)menu.open=false;}}><WorkspaceIcon id={id}/><span>{label}</span><span className="dd-nav-dot" aria-hidden="true"/></button>)}</div></details>)}</nav>;
}
