import {useEffect,useRef} from 'react';
import ShareDesignLink from '../ShareDesignLink';
import type {DeckData} from '../types';
interface Props{data:DeckData;linkBackup:boolean;designStatus:string;designError:string;onSave:()=>void;onImport:(file?:File)=>Promise<void>;onRestoreOwn:()=>void;onStartOver:()=>void;onUndo:()=>void;onRedo:()=>void;canUndo:boolean;canRedo:boolean}
export default function WorkspaceTools(p:Props){
  const file=useRef<HTMLInputElement>(null),menu=useRef<HTMLDetailsElement>(null);
  useEffect(()=>{const close=(e:globalThis.PointerEvent)=>{if(menu.current?.open&&!menu.current.contains(e.target as Node))menu.current.open=false;};const key=(e:globalThis.KeyboardEvent)=>{if(e.key==='Escape'&&menu.current?.open){menu.current.open=false;menu.current.querySelector('summary')?.focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[]);
  return <section className="dd-workspace-tools" aria-label="Save and restore design">
    <div className="dd-undo-actions"><button type="button" aria-label="Undo" title="Undo (Ctrl / Cmd + Z)" disabled={!p.canUndo} onClick={p.onUndo} aria-keyshortcuts="Control+Z Meta+Z"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m9 5-5 5 5 5 M4 10h10a6 6 0 0 1 0 12"/></svg></button><button type="button" aria-label="Redo" title="Redo (Ctrl / Cmd + Shift + Z)" disabled={!p.canRedo} onClick={p.onRedo} aria-keyshortcuts="Control+Shift+Z Meta+Shift+Z Control+Y"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m15 5 5 5-5 5 M20 10H10a6 6 0 0 0 0 12"/></svg></button></div>
    <details ref={menu} className="dd-workspace-files"><summary>Files <span aria-hidden="true">⌄</span></summary><div className="dd-files-popover"><strong>Your design files</strong><p className="dd-note">Automatically saved on this device. Save a file to continue elsewhere.</p><div className="dd-files-actions"><button type="button" className="dd-secondary" onClick={p.onSave}>Save JSON</button><button type="button" className="dd-secondary" onClick={()=>file.current?.click()}>Import design</button><ShareDesignLink data={p.data}/></div><input ref={file} type="file" hidden accept=".json,application/json" aria-label="Import Golden Maple design JSON" onChange={e=>void p.onImport(e.target.files?.[0]).finally(()=>{if(file.current)file.current.value='';})}/>{p.linkBackup&&<button type="button" className="dd-secondary" onClick={p.onRestoreOwn}>Go back to my own design</button>}<details className="dd-reset"><summary>Start over</summary><p>Replace this device’s current design with the default deck.</p><button type="button" className="dd-secondary" onClick={p.onStartOver}>Start a new design</button></details>{p.designStatus&&<p role="status">{p.designStatus}</p>}</div></details>
    {p.designError&&<p role="alert" className="dd-workspace-error">{p.designError}</p>}
  </section>;
}
