import {useEffect,useLayoutEffect,useRef,useState,type KeyboardEvent,type PointerEvent,type RefObject} from 'react';
import {createPortal} from 'react-dom';
import type {DeckData,YardFeature} from '../types';
import type {PlanPoint} from '../lib/deckGeometry';
import type {PlanFrame} from '../ConstructionPlan';
import type {Update} from './fields';
import {newYardFeature} from '../yardSettings';
import {parseContractorLength} from './boundaryDimensions';
import {yardShapeDimension,yardShapeEdit,yardShapeInsert,yardShapeLocalPoints,yardShapePull,yardShapeRemove,yardShapeResize,yardShapeRunIn,yardShapeSignedArea,yardShapeWorldPoints,type YardPullKind,type YardShapeKind} from '../yardShapeEditing';
import './yardShapeEditor.css';

interface Selection {id:string;kind:YardPullKind;index:number}
interface Gesture {pointer:number;feature:YardFeature;selection:Selection;x:number;y:number;scale:number;points:PlanPoint[];next?:YardFeature;problem:string;moved:boolean}
interface Drawing {feature:YardFeature;points:PlanPoint[];replaces:boolean}
const ft=(inches:number)=>String(Math.round(inches/12*10000)/10000);
const angle=(n:number)=>String(Math.round(n*1000)/1000);
const xy=(points:PlanPoint[])=>points.map(p=>`${p.x},${p.y}`).join(' ');
const label=(s:Selection)=>s.kind==='point'?`Point ${s.index+1}`:s.kind==='edge'?`Edge ${s.index+1}`:'Whole feature';
const edgeCount=(f:YardFeature,p:PlanPoint[])=>p.length-(f.kind==='patio'?0:1);
const midpoint=(a:PlanPoint,b:PlanPoint)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});

export interface YardShapeEditorProps {data:DeckData;update:Update;viewportFrame:PlanFrame;viewZoom?:number;toolbar?:RefObject<HTMLElement|null>;onStatus?:(message:string)=>void;onOpenSettings?:()=>void}

/** Pointer previews stay local. Only pointer release, a completed drawing or explicit Apply reaches atomic history. */
export default function YardShapeEditor({data,update,viewportFrame:frame,viewZoom=1,toolbar,onStatus,onOpenSettings}:YardShapeEditorProps){
 const features=(data.yardFeatures??[]).filter(f=>f.kind==='patio'||f.kind==='retaining-wall');
 const [selection,setSelection]=useState<Selection>({id:features[0]?.id??'',kind:'area',index:0}),[notice,setNotice]=useState(''),[invalid,setInvalid]=useState(false);
 const [addArmed,setAddArmed]=useState(false),[drawing,setDrawing]=useState<Drawing|null>(null),[cursor,setCursor]=useState<PlanPoint|null>(null),[live,setLive]=useState<Gesture|null>(null);
 const box=useRef<HTMLDivElement>(null),gesture=useRef<Gesture|null>(null),tap=useRef<{pointer:number;x:number;y:number}|null>(null),active=useRef(new Set<number>());
 const insertion=useRef<{feature:YardFeature;index:number;pointer:number;x:number;y:number;cancelled:boolean}|null>(null);
 const [size,setSize]=useState({w:0,h:0}),[length,setLength]=useState(''),[bearing,setBearing]=useState('');
 const [width,setWidth]=useState(''),[depth,setDepth]=useState(''),[pointX,setPointX]=useState(''),[pointY,setPointY]=useState('');
 const handles=useRef<Record<string,HTMLButtonElement|null>>({}),focusNext=useRef<string|null>(null);
 const selected=features.find(f=>f.id===selection.id)??features[0],points=selected?yardShapeWorldPoints(selected):[];
 const current:Selection=selected?{...selection,id:selected.id,index:Math.min(selection.index,Math.max(0,points.length-(selection.kind==='edge'&&selected.kind!=='patio'?2:1)))}:selection;
 const point=points[current.index],edgeIndex=selected?Math.min(current.index,edgeCount(selected,points)-1):0,edgeStart=points[edgeIndex],end=points[(edgeIndex+1)%points.length],edgeLength=edgeStart&&end?Math.hypot(end.x-edgeStart.x,end.y-edgeStart.y):0,edgeAngle=edgeStart&&end?Math.atan2(end.y-edgeStart.y,end.x-edgeStart.x)*180/Math.PI:0;
 const announce=(text:string,bad=false)=>{setNotice(text);setInvalid(bad);onStatus?.(text);};
 const cancelMove=()=>{gesture.current=null;tap.current=null;insertion.current=null;setLive(null);};
 const cancel=()=>{cancelMove();setDrawing(null);setCursor(null);setAddArmed(false);announce('Yard edit cancelled. The saved design is unchanged.');};
 const choose=(next:Selection)=>{cancelMove();setSelection(next);setNotice('');setInvalid(false);};
 const keyId=(s:Selection)=>`${s.id}-${s.kind}-${s.index}`;
 useLayoutEffect(()=>{const el=box.current;if(!el)return;const measure=()=>setSize(v=>v.w===el.clientWidth&&v.h===el.clientHeight?v:{w:el.clientWidth,h:el.clientHeight});measure();const ro=new ResizeObserver(measure);ro.observe(el);return()=>ro.disconnect();},[]);
 useEffect(()=>{cancelMove();setDrawing(null);setCursor(null);},[data]);
 useEffect(()=>{setLength(ft(edgeLength));setBearing(angle(edgeAngle));},[selected?.id,current.index,edgeLength,edgeAngle]);
 useEffect(()=>{setWidth(String(selected?.widthFt??''));setDepth(String(selected?.depthFt??''));},[selected?.id,selected?.widthFt,selected?.depthFt]);
 useEffect(()=>{setPointX(point?ft(point.x):'');setPointY(point?ft(point.y):'');},[selected?.id,current.index,point?.x,point?.y]);
 useLayoutEffect(()=>{const key=focusNext.current;if(key&&handles.current[key]){handles.current[key]!.focus({preventScroll:true});focusNext.current=null;}});
 useEffect(()=>{const down=(e:globalThis.PointerEvent)=>{active.current.add(e.pointerId);if(active.current.size>1)cancelMove();};const up=(e:globalThis.PointerEvent)=>active.current.delete(e.pointerId);document.addEventListener('pointerdown',down,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',up,true);return()=>{document.removeEventListener('pointerdown',down,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',up,true);};},[]);
 const scale=Math.min(size.w/frame.w,size.h/frame.h),ox=(size.w-frame.w*scale)/2,oy=(size.h-frame.h*scale)/2;
 const at=(p:PlanPoint)=>({left:ox+(p.x-frame.x)*scale,top:oy+(p.y-frame.y)*scale,transform:`translate(-50%,-50%) scale(${1/viewZoom})`});
 const worldAt=(e:{clientX:number;clientY:number})=>{const matrix=box.current?.querySelector('svg')?.getScreenCTM();if(!matrix)throw Error('Wait for the plan drawing to finish loading.');const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return {x:p.x,y:p.y};};
 const commit=(before:YardFeature,next:YardFeature,nextSelection=current)=>{
  if(JSON.stringify(before)===JSON.stringify(next))return false;
  update({yardFeatures:(data.yardFeatures??[]).map(f=>f.id===before.id?next:f)});setSelection(nextSelection);announce(`${next.name} updated. Undo restores the previous shape.`);return true;
 };
 const attempt=(fn:()=>void)=>{try{fn();}catch(e){announce(e instanceof Error?e.message:'This yard edit could not be applied.',true);}};
 const removePoint=(f:YardFeature,index:number)=>attempt(()=>{const next=yardShapeRemove(f,index),s={id:f.id,kind:'point' as const,index:Math.min(index,yardShapeLocalPoints(next).length-1)};if(commit(f,next,s))focusNext.current=keyId(s);});
 const removeFeature=(f:YardFeature)=>{update({yardFeatures:(data.yardFeatures??[]).filter(q=>q.id!==f.id)});setSelection({id:'',kind:'area',index:0});announce(`${f.name} removed. Undo restores it.`);};
 const insert=(f:YardFeature,index:number,cursor?:PlanPoint)=>attempt(()=>{const s={id:f.id,kind:'point' as const,index:index+1};if(commit(f,yardShapeInsert(f,index,cursor),s)){setAddArmed(false);focusNext.current=keyId(s);}});
 const beginInsert=(feature:YardFeature,index:number,e:PointerEvent)=>{if(!addArmed||e.pointerType==='mouse'&&e.button!==0||active.current.size>1)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);insertion.current={feature,index,pointer:e.pointerId,x:e.clientX,y:e.clientY,cancelled:false};};
 const down=(f:YardFeature,kind:YardPullKind,index:number)=>(e:PointerEvent<HTMLButtonElement>)=>{
  if(e.pointerType==='mouse'&&e.button!==0||drawing||gesture.current||active.current.size>1)return;e.preventDefault();e.stopPropagation();
  if(addArmed){if(kind==='edge')beginInsert(f,index,e);else announce('Tap any patio or wall edge to add a pull point.');return;}
  e.currentTarget.focus({preventScroll:true});e.currentTarget.setPointerCapture(e.pointerId);const target={id:f.id,kind,index};choose(target);
  const rendered=box.current?.getBoundingClientRect(),screenScale=rendered?Math.min(rendered.width/frame.w,rendered.height/frame.h):scale*viewZoom;
  const g:Gesture={pointer:e.pointerId,feature:f,selection:target,x:e.clientX,y:e.clientY,scale:screenScale,points:yardShapeWorldPoints(f),problem:'',moved:false};gesture.current=g;setLive(g);
 };
 const move=(e:PointerEvent)=>{
  const t=insertion.current;if(t){if(t.pointer===e.pointerId&&Math.hypot(e.clientX-t.x,e.clientY-t.y)>8)t.cancelled=true;return;}
  const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;e.preventDefault();const dx=(e.clientX-g.x)/g.scale,dy=(e.clientY-g.y)/g.scale,p=yardShapeWorldPoints(g.feature),kind=g.selection.kind,index=g.selection.index;
  const raw=p.map((q,i)=>kind==='area'||i===index||kind==='edge'&&i===(index+1)%p.length?{x:q.x+dx,y:q.y+dy}:q);let next:YardFeature|undefined,problem='';
  try{next=yardShapePull(g.feature,kind,index,dx,dy);}catch(error){problem=(error as Error).message;}
  const updated={...g,points:raw,next,problem,moved:Math.hypot(dx,dy)>1e-7};gesture.current=updated;setLive(updated);
 };
 const up=(e:PointerEvent)=>{const t=insertion.current;if(t&&t.pointer===e.pointerId){insertion.current=null;if(!t.cancelled&&Math.hypot(e.clientX-t.x,e.clientY-t.y)<=8)attempt(()=>insert(t.feature,t.index,worldAt(e)));return;}const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;move(e);const final=gesture.current!;cancelMove();if(final.problem){announce(final.problem,true);return;}if(final.moved&&final.next)commit(final.feature,final.next,final.selection);};
 const keys=(f:YardFeature,kind:YardPullKind,index:number)=>(e:KeyboardEvent)=>{
  if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancel();return;}if(drawing)return;
  if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(kind==='point')removePoint(f,index);else if(kind==='area')removeFeature(f);else announce('Select a pull point to remove it, or select Move to delete the whole feature.');return;}
  const delta=({ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]} as Record<string,number[]>)[e.key];if(delta){e.preventDefault();e.stopPropagation();const n=e.shiftKey?12:1;attempt(()=>commit(f,yardShapePull(f,kind,index,delta[0]*n,delta[1]*n),{id:f.id,kind,index}));}
 };
 const startDrawing=(kind:YardShapeKind,replaces=false)=>{cancelMove();setAddArmed(false);if(!replaces&&(data.yardFeatures?.length??0)>=20){announce('This design supports up to 20 yard features.',true);return;}const f=replaces?selected!:newYardFeature(kind,data);setDrawing({feature:f,points:[],replaces});setCursor(null);announce(`Tap the ${kind==='patio'?'patio corners':'wall turns'}. Right-click or choose Finish to complete it.`);};
 const finishDrawing=()=>attempt(()=>{if(!drawing)return;let p=drawing.points;if(drawing.feature.kind==='patio'&&yardShapeSignedArea(p)<0)p=[...p].reverse();const next=yardShapeEdit(drawing.feature,p);if(drawing.replaces)commit(drawing.feature,next,{id:next.id,kind:'point',index:0});else{update({yardFeatures:[...(data.yardFeatures??[]),next]});setSelection({id:next.id,kind:'point',index:0});announce(`${next.name} drawn. Every point and edge is editable.`);}setDrawing(null);setCursor(null);});
 const drawDown=(e:PointerEvent<SVGSVGElement>)=>{if(!drawing||e.pointerType==='mouse'&&e.button!==0||active.current.size>1)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);tap.current={pointer:e.pointerId,x:e.clientX,y:e.clientY};};
 const drawUp=(e:PointerEvent<SVGSVGElement>)=>{const t=tap.current;tap.current=null;if(!drawing||!t||t.pointer!==e.pointerId||Math.hypot(e.clientX-t.x,e.clientY-t.y)>8||active.current.size>1)return;attempt(()=>{const p=worldAt(e);if(drawing.points.length>=64)throw Error('Finish this shape before adding more than 64 points.');if(drawing.points.length&&Math.hypot(p.x-drawing.points.at(-1)!.x,p.y-drawing.points.at(-1)!.y)<1)throw Error('Place the next point at least 1 inch away.');setDrawing({...drawing,points:[...drawing.points,p]});setCursor(p);});};
 const controls=<div className="dd-yard-shape-controls" aria-label="Patio and wall shape controls" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancel();}else if(drawing&&e.key==='Enter'&&!['INPUT','SELECT','BUTTON'].includes((e.target as HTMLElement).tagName)){e.preventDefault();finishDrawing();}}}>
  <div className="dd-yard-shape-actions"><button type="button" disabled={!!live} onClick={()=>startDrawing('patio')}>Draw patio</button><button type="button" disabled={!!live} onClick={()=>startDrawing('retaining-wall')}>Draw wall path</button>{onOpenSettings&&<button type="button" onClick={onOpenSettings}>Products &amp; costs</button>}</div>
  {drawing?<section className="dd-yard-shape-drawing" aria-label="Draw yard shape"><strong>{drawing.feature.kind==='patio'?'Patio outline':'Retaining wall path'} · {drawing.points.length} points</strong><p>Tap straight segments with your mouse, finger or stylus. A wall stays open; a patio closes when finished.</p><div className="dd-yard-shape-actions"><button type="button" disabled={drawing.points.length<(drawing.feature.kind==='patio'?3:2)} onClick={finishDrawing}>Finish {drawing.feature.kind==='patio'?'shape':'path'}</button><button type="button" disabled={!drawing.points.length} onClick={()=>setDrawing({...drawing,points:drawing.points.slice(0,-1)})}>Undo last point</button><button type="button" onClick={cancel}>Cancel drawing</button></div></section>:selected?<>
   <label className="dd-yard-shape-select">Selected patio or wall<select aria-label="Selected patio or wall" value={selected.id} onChange={e=>{setAddArmed(false);choose({id:e.target.value,kind:'area',index:0});}}>{features.map(f=><option key={f.id} value={f.id}>{f.name}{!f.enabled?' (excluded)':''}</option>)}</select></label>
   <div className="dd-yard-shape-actions"><strong>{label(current)}</strong><button type="button" aria-pressed={addArmed} disabled={!!live} onClick={()=>{cancelMove();setAddArmed(!addArmed);announce(addArmed?'Adding a point cancelled.':'Tap an edge to place a pull point, then pull it in any direction.');}}>Add pull point</button><button type="button" disabled={!!live||current.kind!=='point'||points.length<=(selected.kind==='patio'?3:2)} onClick={()=>removePoint(selected,current.index)}>Remove point</button><button type="button" disabled={!!live} onClick={()=>{const index=Math.min(current.index,edgeCount(selected,points)-1);insert(selected,index);}}>Add midpoint</button><button type="button" disabled={!!live} onClick={()=>startDrawing(selected.kind as YardShapeKind,true)}>Redraw selected shape</button><button type="button" disabled={!!live} onClick={()=>removeFeature(selected)}>Delete selected feature</button></div>
   <p>Pull any point or edge freely. Drag Move to place the whole feature. Arrows move 1 inch; Shift moves 1 foot. Delete removes a selected point or whole feature. Undo is available above the drawing.</p>
   <form className="dd-yard-shape-form" onSubmit={e=>{e.preventDefault();attempt(()=>{const n=length===ft(edgeLength)?edgeLength:parseContractorLength(length),a=bearing===angle(edgeAngle)?edgeAngle:Number(bearing);if(!bearing.trim())throw Error('Enter the edge angle.');commit(selected,yardShapeDimension(selected,edgeIndex,n,a),{...current,index:edgeIndex,kind:'edge'});});}}><label>Measured edge<select aria-label="Yard measured edge" value={Math.min(current.index,edgeCount(selected,points)-1)} onChange={e=>choose({id:selected.id,kind:'edge',index:Number(e.target.value)})}>{points.slice(0,edgeCount(selected,points)).map((_,i)=><option key={i} value={i}>Edge {i+1}</option>)}</select></label><label>Length (ft / in)<input aria-label="Yard edge length" value={length} onChange={e=>setLength(e.target.value)} disabled={!!live}/></label><label>Direction (°)<input aria-label="Yard edge angle" inputMode="decimal" value={bearing} onChange={e=>setBearing(e.target.value)} disabled={!!live}/></label><button type="submit" disabled={!!live}>Apply edge dimension</button></form>
   <details><summary>Overall dimensions &amp; exact point</summary><form className="dd-yard-shape-form" onSubmit={e=>{e.preventDefault();attempt(()=>{if(!width.trim()||!depth.trim())throw Error('Enter both dimensions.');commit(selected,yardShapeResize(selected,Number(width),Number(depth)));});}}><label>{selected.kind==='patio'?'Width':'Total wall run'} (ft)<input aria-label={selected.kind==='patio'?'Patio shape width':'Wall shape total run'} inputMode="decimal" value={width} onChange={e=>setWidth(e.target.value)}/></label><label>{selected.kind==='patio'?'Depth':'Thickness'} (ft)<input aria-label={selected.kind==='patio'?'Patio shape depth':'Wall shape thickness'} inputMode="decimal" value={depth} disabled={selected.kind==='retaining-wall'&&!!selected.hardscape} title={selected.kind==='retaining-wall'&&selected.hardscape?'Thickness follows the selected supplier stock unit. Change it in Products & costs.':undefined} onChange={e=>setDepth(e.target.value)}/></label><button type="submit">Apply overall dimensions</button></form>
   <form className="dd-yard-shape-form" onSubmit={e=>{e.preventDefault();attempt(()=>{if(!pointX.trim()||!pointY.trim())throw Error('Enter both point coordinates.');const x=pointX===ft(point.x)?point.x:Number(pointX)*12,y=pointY===ft(point.y)?point.y:Number(pointY)*12;if(!Number.isFinite(x)||!Number.isFinite(y))throw Error('Enter finite point coordinates.');commit(selected,yardShapePull(selected,'point',current.index,x-point.x,y-point.y),{...current,kind:'point'});});}}><label>Point<select aria-label="Selected yard point" value={current.index} onChange={e=>choose({id:selected.id,kind:'point',index:Number(e.target.value)})}>{points.map((_,i)=><option key={i} value={i}>Point {i+1}</option>)}</select></label><label>Across yard (ft)<input aria-label="Yard point X in feet" inputMode="decimal" value={pointX} onChange={e=>setPointX(e.target.value)}/></label><label>Out into yard (ft)<input aria-label="Yard point Y in feet" inputMode="decimal" value={pointY} onChange={e=>setPointY(e.target.value)}/></label><button type="submit">Apply point position</button></form></details>
   <p className="dd-yard-shape-size">{selected.kind==='patio'?`${ft(selected.widthFt*12)} × ${ft(selected.depthFt*12)} ft`:`${ft(yardShapeRunIn(points))} ft total path · ${selected.depthFt} ft thickness`} · {points.length} pull points{!selected.enabled?' · excluded from estimate':''}</p>
  </>:<p>Draw a patio outline or retaining wall path. Existing rectangles and straight walls become editable shapes when you pull a point.</p>}
  {notice&&<p role="status" className="dd-yard-shape-notice" data-invalid={invalid||undefined}>{notice}</p>}
 </div>;
 return <div ref={box} className="dd-yard-shape-editor" data-drawing={!!drawing||undefined} data-add-pull={addArmed||undefined} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancel();}else if(e.key==='Enter'&&drawing){e.preventDefault();finishDrawing();}}}>
  <svg viewBox={frame.viewBox} aria-label={drawing?'Yard shape drawing surface':undefined} aria-hidden={!drawing} tabIndex={drawing?0:undefined} className={drawing?'dd-yard-shape-draw-surface':undefined} data-plan-editor-ui onPointerDown={drawDown} onPointerUp={drawUp} onPointerCancel={cancelMove} onLostPointerCapture={()=>{tap.current=null;}} onPointerMove={e=>{if(drawing)attempt(()=>setCursor(worldAt(e)));}} onContextMenu={e=>{if(drawing){e.preventDefault();e.stopPropagation();finishDrawing();}}}>
   {features.map(f=>{const p=live?.feature.id===f.id?live.points:yardShapeWorldPoints(f),selected=f.id===current.id,props={className:'dd-yard-shape-outline','data-selected':selected||undefined,'data-excluded':!f.enabled||undefined,'data-invalid':live?.feature.id===f.id&&!!live.problem||undefined,points:xy(p),onClick:()=>{if(!drawing&&!gesture.current)choose({id:f.id,kind:'area',index:0});}};return f.kind==='patio'?<polygon key={f.id} {...props}/>:<polyline key={f.id} {...props}/>;})}
   {addArmed&&!drawing&&features.flatMap(f=>{const p=yardShapeWorldPoints(f);return p.slice(0,edgeCount(f,p)).map((a,i)=>{const b=p[(i+1)%p.length];return <line key={`${f.id}-${i}`} className="dd-yard-shape-insert-target" data-feature-id={f.id} data-edge={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} style={{strokeWidth:44/viewZoom}} onPointerDown={e=>beginInsert(f,i,e)} onPointerMove={move} onPointerUp={up} onPointerCancel={cancelMove} onLostPointerCapture={()=>{insertion.current=null;}}/>;});})}
   {drawing&&<><polyline className="dd-yard-shape-draft" points={xy([...drawing.points,...(cursor&&drawing.points.length?[cursor]:[])])}/>{drawing.points.map((p,i)=><circle key={i} className="dd-yard-shape-draft-point" cx={p.x} cy={p.y} r={5/Math.max(.01,scale*viewZoom)}/>)}</>}
  </svg>
  {!drawing&&scale>0&&features.flatMap(f=>{if(f.id!==current.id)return [];const p=live?.feature.id===f.id?live.points:yardShapeWorldPoints(f),n=edgeCount(f,p),centre={x:f.xFt*12,y:f.zFt*12};if(live?.feature.id===f.id&&live.next){centre.x=live.next.xFt*12;centre.y=live.next.zFt*12;}const list=[...p.map((q,i)=>({kind:'point' as const,index:i,point:q})),...p.slice(0,n).map((q,i)=>({kind:'edge' as const,index:i,point:midpoint(q,p[(i+1)%p.length])})),{kind:'area' as const,index:0,point:centre}];return list.map(h=>{const s={id:f.id,kind:h.kind,index:h.index},key=keyId(s),chosen=keyId(current)===key;return <button ref={el=>{handles.current[key]=el;}} key={key} type="button" data-plan-editor-ui className={`dd-yard-shape-handle dd-yard-shape-${h.kind}`} data-feature-selected={f.id===current.id||undefined} data-selected={chosen||undefined} data-invalid={live?.feature.id===f.id&&!!live.problem||undefined} aria-label={`${f.name} ${h.kind==='area'?'move whole feature':h.kind==='point'?`point ${h.index+1}`:`edge ${h.index+1}`}`} aria-pressed={chosen} style={at(h.point)} onFocus={()=>{if(!chosen)choose(s);}} onPointerDown={down(f,h.kind,h.index)} onPointerMove={move} onPointerUp={up} onPointerCancel={cancelMove} onLostPointerCapture={e=>{if(gesture.current?.pointer===e.pointerId)cancelMove();}} onKeyDown={keys(f,h.kind,h.index)} onDoubleClick={e=>{if(h.kind==='edge'){e.preventDefault();insert(f,h.index);}}}><span aria-hidden="true">{h.kind==='area'?'Move':h.kind==='edge'?'↔':''}</span></button>;});})}
  {toolbar?.current?createPortal(controls,toolbar.current):<div className="dd-yard-shape-toolbar">{controls}</div>}
 </div>;
}
