/** Additional scope guidance is loaded only by the private contractor quote workflow. */
const DETAILS:Record<string,string>={
 'Wall body stock supply':'Includes buried courses and full blanks used for cuts. Fragments are not extra full units. Confirm end/corner stock, breakage, bundles and order rounding.',
 'Selected cap stock supply':'Confirm cap colour, end pieces, curve/mitre cuts and procurement waste separately from body units.',
 'Wall body and cap installation':'Body/cap placement, cuts and finish labour. Buried stock is included in supply; base, grid, drainage and fill operations are separate. Share equipment once.',
 'Geogrid stock supply':'Supply includes gross strips/turn overlaps plus 10% cutting. The modeled count can have partial planes across stepped benches. Grid product strength, connection and structural layout remain unconfirmed.',
 'Geogrid installation':'Net installed union area excludes procurement waste. Quote placement, tensioning, cuts/connections and approved corner/curve details.',
 'Compacted leveling aggregate and placement':'Confirm aggregate, density, delivered conversion, freight and lift compaction. Compacted cu yd cannot use a tonnes rate without conversion. Excavation/equipment is separate.',
 'Drainage stone and placement':'Confirm clean stone, delivered density/volume, placing and freight. Core fill is separate.',
 'Reinforced backfill and compaction':'Fill demand is before suitable-soil reuse. Reconcile reused bank soil once across all yard fill demand; confirm structural fill compatibility, imported volume, freight and compaction.',
 'Wall separator fabric and installation':'Envelope excludes product laps, fastening and roll waste. Separator fabric is separate from geogrid.',
 'Main perforated drain and installation':'Main collection run only. Confirm diameter, gradient, cleanouts and fittings; outlet extension/termination is separate.',
 'Drain outlet extension and installation':'Entered outlet run adds to the collection pipe. Confirm route, invert/slope, trench/restoration and lawful discharge; no blank outlet length is invented.',
 'Drain outlet fittings and termination':'Planning count; confirm outlets, fittings/screens, erosion protection and permissions.',
 'Cap adhesive and installation':'Bond length only; confirm approved adhesive, bead coverage, preparation and cartridge/pack count. No cartridge count or consumption rate is assumed.',
 'Core-fill stone, connectors and special stock':'Confirm hollow-core stone, pins/backers/connectors and special end/corner stock from the complete assembly. No void percentage or connection count is assumed.',
 'Wall packaging, freight and order adjustments':'Confirm bundles/split fees, pallets/waste, zone/fuel/access and unloading. Reconcile freight already quoted in other scopes.',
 'Wall survey/design services':'Quote survey, geotechnical/structural services, permits and inspections. A service fee cannot approve the design.',
 'Preliminary manufacturer assembly survey and quote':'Quote a complete backing/base/middle/top assembly and order schedule. Modeled face/run is preliminary; repeated envelope counts cannot be used as a supply order. Assembly confirmation remains pending independently of any cost.'
};
const GENERAL:readonly [string,string][]=[["paving supply and installation","Product-specific stock, cuts, packaging, installation and freight require a current quote. Where the parent patio has a priced standard assembly, its shared base, excavation and ordinary setting are already included; quote additional product/fabrication work only. Otherwise base and excavation also require a quote. The selected product does not inherit a different supplier’s material price."],["custom inlay cutting and setting","Inlay supply is listed with its own selected paving material. Custom cuts, setting, waste, template/fabrication and transitions need a builder quote. Shared patio base is counted once."],["elevation grading and containment","Moving the wall base changes excavation or engineered fill, compaction, containment and drainage. Coordinate shared site work; these additional operations require a site quote."],["Additional engineered fill and containment","Elevation-derived fill below the standard patio base; supplier and installation quote required."],["Paver packaging, colour and freight adjustments (supplier quote)","The published standard-colour supply and Zone 1 delivery benchmark are included. The selected manufacturer colour, bundle size, split fees, fuel and actual delivery address can change the final order price."],["Hauling and disposal price adjustments","The existing disposal benchmark is included once below. Quote the confirmed additional charges for the actual loose spoil volume/mass, bin payload, hauling distance, access, tipping/classification and reuse handling. Enter only the difference above included benchmark costs; the current planning floor remains. Actual rates and supplier/hauler references belong in the private quote controls."],["Shared excavation, access and equipment installation","Supplier-only layouts do not inherit another patio/wall assembly labour rate. Quote excavation, equipment, mobilization, shared base preparation, access and restoration once for the entire yard; reconcile deck/site operations. Disposal and measured material placement are listed separately."]];
export function yardQuoteDescription(name:string){const label=Object.keys(DETAILS).find(label=>name.endsWith(`: ${label}`));return label?DETAILS[label]:GENERAL.find(([label])=>name===label||name.endsWith(`: ${label}`)||name.endsWith(` ${label}`))?.[1]??'';}
