/** Opt-in real local model verification. Synthetic jobs only; no browser, customer service or cloud. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {createDeckAssistantService,DECK_ASSISTANT_PATH} from '../server/deckAssistantBackend';
import {assistantPlanRequest,buildAssistantContext} from '../src/features/deckcraft/designer/assistantPlan';
import {createDeckAgentController,type AgentSnapshot,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import type {AssistedSelection} from '../src/features/deckcraft/designer/naturalLanguageCommands';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {DECKING_CATALOGUE} from '../src/features/deckcraft/manufacturerCatalog';
import {deckReleaseData,calculateDeckReleaseEstimate,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {getHouseConfig} from '../src/features/deckcraft/houseSettings';
import type {DeckData} from '../src/features/deckcraft/types';
const dir=resolve(process.cwd(),'../../outputs/deckcraft-contractor-ready-review');mkdirSync(dir,{recursive:true});
const run=process.argv.find(s=>s.startsWith('--run='))?.slice(6)??new Date().toISOString().replace(/[:.]/g,'-');
const only=process.argv.find(s=>s.startsWith('--cases='))?.slice(8).split(',');
const records:any[]=[];let assertions=0,rawModel:unknown,modelOptions:unknown;
const sourceHashes=Object.fromEntries(['src/features/deckcraft/designer/assistantPlan.ts','src/features/deckcraft/designer/assistantContracts.ts','src/features/deckcraft/designer/deckAssistantClient.ts','server/deckAssistantBackend.ts'].map(path=>[path,createHash('sha256').update(readFileSync(path)).digest('hex')]));
const service=createDeckAssistantService({ollamaUrl:'http://127.0.0.1:11434',model:'qwen3:14b',fetch:async(input,init)=>{const chat=String(input).endsWith('/api/chat');if(chat)modelOptions=JSON.parse(String(init?.body)).options;const r=await fetch(input,init);if(chat)rawModel=await r.clone().json();return r;}});
const check=(v:unknown,message:string)=>{assert.ok(v,message);assertions++;};
function persist(){writeFileSync(resolve(dir,`ai-editing-real-${run}.json`),JSON.stringify({model:'qwen3:14b',localOnly:true,synthetic:true,mocked:false,sourceHashes,assertions,records},null,2)+'\n');}
function fixture(extra:Partial<DeckData>={}){let data=deckReleaseData({...structuredClone(DEFAULT_DECK),deckingMaterial:'tt_reserve',deckingColor:'Antique Leather',height:72,customerName:'SYNTHETIC-PRIVATE-CLIENT',projectAddress:'SYNTHETIC-PRIVATE-ADDRESS',scopeOfWork:'SYNTHETIC-PRIVATE-SCOPE',materialMarkup:43,...extra});const history:DeckData[]=[];let commits=0;
 const state=():DeckAgentHostState=>({data,estimate:calculateDeckReleaseEstimate(data),view:'plan',openSections:[],canUndo:!!history.length,canRedo:false,ready:true});
 const api=createDeckAgentController({getState:state,commitDesign:next=>{commits++;history.push(data);data=next;},undo:()=>{data=history.pop()!;},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async predicate=>assert.ok(predicate(state()))});
 return {api,get data(){return data;},get commits(){return commits;},history};
}
type Case={id:string;prompt:string;extra?:Partial<DeckData>;selection?:(s:AgentSnapshot)=>AssistedSelection;clarify?:boolean;verify?:(before:AgentSnapshot,after:AgentSnapshot)=>void};
const reserve=DECKING_CATALOGUE.find(m=>m.id==='tt_reserve')!,accent=reserve.colors.find(c=>c.name!=='Antique Leather')!.name;
// Actual saved/imported measured-house fixture; strict preview also refuses tiny canonicalization drift in a raw host.
const measuredHouse=parseDeckReleaseDesign(JSON.stringify({format:'golden-maple-deck-design',version:1,units:'inches-and-feet',configuration:{...DEFAULT_DECK,height:72,houseConfig:{...getHouseConfig({...DEFAULT_DECK,height:72}),roofFinish:'Metal',cladding:'Brick'}}})).houseConfig;
const cases:Case[]=[
 {id:'board-angle-colour',prompt:`Give these selected boards a 45-degree diagonal and the ${accent} colour from TimberTech Reserve. Leave the main material and other boards alone.`,selection:s=>({partIds:[],boards:s.boards.slice(8,10).map(b=>({level:b.modelLevel,index:b.index}))}),verify:(b,a)=>{check(a.design.deckingMaterial===b.design.deckingMaterial&&a.design.deckingColor===b.design.deckingColor,'Board override preserves main material/colour');const pieces=a.design.boardLayout?.pieces??[];check(pieces.length===2&&pieces.every(p=>p.angleDeg===45&&p.colour===`tt_reserve:${accent}`),'Two actual selected stock pieces rotate and recolour');for(const target of b.boards.slice(8,10))check(pieces.some(p=>Math.abs(p.cx-target.cx)<1e-8&&Math.abs(p.cy-target.cy)<1e-8),'Physical piece uses actual selected board centre');check(a.boards.some(x=>x.angleDeg===45&&x.colour===`tt_reserve:${accent}`),'Rendered inventory reflects physical rotation and catalogue accent');check(a.boards.filter(x=>x.layoutKind!=='piece').every(x=>x.angleDeg===b.boards[0].angleDeg&&x.colour===b.boards[0].colour),'Unselected courses retain angle and colour while cuts adapt to physical inserts');check(a.design.width===b.design.width&&a.design.length===b.design.length,'Board edit preserves outline dimensions');}},
 {id:'selected-second-width',prompt:'Make this selected deck section two feet wider, keeping its depth, elevation and the main deck unchanged.',extra:{levels:2},selection:s=>({partIds:[s.parts.find(p=>p.kind==='deck'&&p.level===2)!.id],boards:[]}),verify:(b,a)=>{check(a.design.width2===b.design.width2+2,'Selected second width changes exactly2ft');check(a.design.width===b.design.width&&a.design.length===b.design.length&&a.design.length2===b.design.length2&&a.design.height2===b.design.height2,'Main/depth/elevation unchanged');}},
 {id:'selected-area-direction',prompt:'Lay the boards across this selected deck section at 30 degrees, keeping its outline and the other level unchanged.',extra:{levels:2},selection:s=>({partIds:[s.parts.find(p=>p.kind==='deck'&&p.level===2)!.id],boards:[]}),verify:(b,a)=>{const regions=a.design.boardLayout?.regions??[];check(regions.length===1&&regions[0].level===2&&regions[0].angleDeg===30,'Selected level2 field receives actual30degree region');check(JSON.stringify(regions[0].polygon)===JSON.stringify(b.boundaries.find(x=>x.level===2)!.points),'Actual selected local outline copied');check(a.design.width===b.design.width&&a.design.width2===b.design.width2,'No fake outline size change');check(a.boards.filter(x=>x.level===1).every(x=>x.angleDeg===b.boards.find(y=>y.level===1&&y.index===x.index)!.angleDeg),'Main board angles unchanged');}},
 {id:'stairs-width',prompt:'The stairs need more room for two people. Make them six feet wide and keep their current position and style.',verify:(b,a)=>{check(a.design.stairWidth===72,'Stairs actual72in width');check(a.design.stairPosition===b.design.stairPosition&&a.design.stairType===b.design.stairType&&a.design.stairOffset===b.design.stairOffset,'Stair placement/style retained');check(a.design.width===b.design.width&&a.design.length===b.design.length,'Deck unchanged');}},
 {id:'underdeck-drainage',prompt:'Add TimberTech DrySpace underneath the deck, but keep my existing gravel, mesh and coverage choices.',extra:{underDeck:{drainage:'none',ceiling:'none',scope:'all',gravel:true,gravelDepthIn:4,floorMesh:true}},verify:(b,a)=>{check(a.design.underDeck?.drainage==='dryspace'&&a.design.hasDrainage,'Actual drainage selected');for(const key of ['ceiling','scope','gravel','gravelDepthIn','floorMesh'] as const)check(a.design.underDeck?.[key]===b.design.underDeck?.[key],`Unrelated underDeck.${key} retained`);check(a.design.deckingMaterial===b.design.deckingMaterial,'Drainage preserves decking');}},
 {id:'two-intents',prompt:'Please widen the main deck by two feet and make the stairs six feet wide. Keep the depth, height and stair position as they are.',verify:(b,a)=>{check(a.design.width===b.design.width+2&&a.design.stairWidth===72,'Both width and stair intents actually applied');check(a.design.length===b.design.length&&a.design.height===b.design.height&&a.design.stairPosition===b.design.stairPosition,'Unrelated dimensions retained');}},
 {id:'generated-post-clarify',prompt:'Move this selected support post two feet to the left.',selection:s=>({partIds:[s.parts.find(p=>p.kind==='post')!.id],boards:[]}),clarify:true},
 {id:'ambiguous-target',prompt:'Make it taller and move it over a bit.',clarify:true},
 {id:'main-vague-width',prompt:'Give the main deck a little more width, keeping everything else the same.',verify:(b,a)=>{check(Math.abs(a.design.width-(b.design.width+Math.max(b.design.width*.1,1)))<1e-9,'Vague main width uses exposed10%min1ft assumption');check(a.design.length===b.design.length&&a.design.levels===b.design.levels,'No invented level/depth changes');}},
 {id:'house-preservation',prompt:'Change the house roof colour to #233544 without changing its roof shape, finish, walls or openings.',extra:{houseConfig:measuredHouse},verify:(b,a)=>{check(a.design.houseConfig?.roofColor==='#233544','Requested house roof colour applied');const old={...b.design.houseConfig},next={...a.design.houseConfig};delete old.roofColor;delete next.roofColor;check(JSON.stringify(next)===JSON.stringify(old),'All unrelated measured house settings preserved');}},
 {id:'main-width-post-selected',prompt:'Make the main deck two feet wider, keeping everything else the same.',selection:s=>({partIds:[s.parts.find(p=>p.kind==='post')!.id],boards:[]}),verify:(b,a)=>{check(a.design.width===b.design.width+2,'Unrelated main width works even when a post is selected');check(a.design.length===b.design.length&&a.design.height===b.design.height,'Unrelated main dimensions preserved');}},
];
for(const c of cases.filter(c=>!only||only.includes(c.id))){const f=fixture(c.extra),before=f.api.read(),saved=JSON.stringify(f.data),selection=c.selection?.(before)??{partIds:[],boards:[]};let record:any={id:c.id,prompt:c.prompt,selection,context:null,status:0,durationMs:0,result:null,modelReply:null,preview:null,passed:false,error:null};records.push(record);try{
 const context=buildAssistantContext(before,selection);record.context=context;check(!JSON.stringify(context).includes('SYNTHETIC-PRIVATE'),'Real model never receives private job fields');rawModel=null;modelOptions=null;const started=Date.now();const response=await service.handle(new Request('http://127.0.0.1:4319'+DECK_ASSISTANT_PATH,{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://127.0.0.1:4319'},body:JSON.stringify({prompt:c.prompt,context})}));record.durationMs=Date.now()-started;record.status=response.status;record.result=await response.json();record.modelReply=rawModel;record.modelOptions=modelOptions;persist();check(response.status===200,`Actual model returns valid plan: ${JSON.stringify(record.result)}`);check(JSON.stringify(f.data)===saved&&f.commits===0,'Model inference has no writes');const plan=record.result.plan;
 if(c.clarify){check(plan.kind==='clarify'&&plan.commands.length===0&&!!plan.question,'Unsafe/ambiguous request returns a meaningful no-edit question');check(JSON.stringify(f.data)===saved,'Clarification leaves design unchanged');}
 else{check(plan.kind==='edit','Actual model resolves requested edit');const request=assistantPlanRequest(plan,{id:`real-${run}-${c.id}`,expectedRevision:before.revision,snapshot:before,selection,requestText:c.prompt});record.compiled=request;const preview=await f.api.preview(request);record.preview=preview.ok?{design:preview.snapshot.design,pricing:preview.snapshot.pricing.total}:preview;persist();check(preview.ok,`Real controller accepts intended physical edit: ${JSON.stringify(preview)}`);if(!preview.ok)throw Error('Preview failed');c.verify?.(before,preview.snapshot);check(JSON.stringify(f.data)===saved&&f.commits===0,'Preview remains read-only');const applied=await f.api.execute(request);check(applied.ok&&f.commits===1&&f.history.length===1,'Actual edits commit atomically once');if(!applied.ok)throw Error('Apply failed');check(applied.snapshot.pricing.total===preview.snapshot.pricing.total,'Exact preview/apply customer total matches');c.verify?.(before,applied.snapshot);check(f.data.customerName==='SYNTHETIC-PRIVATE-CLIENT'&&f.data.materialMarkup===43&&f.data.projectAddress==='SYNTHETIC-PRIVATE-ADDRESS','Apply preserves customer/pricing fields');await f.api.execute({id:`undo-${run}-${c.id}`,commands:[{type:'history.undo'}]});check(JSON.stringify(f.data)===saved&&f.history.length===0,'One Undo restores complete original job');}
 record.passed=true;console.log(`PASS ${c.id} ${record.durationMs}ms`);
 }catch(error){record.error=error instanceof Error?error.message:String(error);console.log(`FAIL ${c.id} ${record.durationMs}ms: ${record.error}`);}finally{persist();f.api.dispose();}}
const failed=records.filter(r=>!r.passed);console.log(`${records.length-failed.length}/${records.length} actual qwen3:14b cases, ${assertions} assertions. Proof ai-editing-real-${run}.json`);if(failed.length)process.exitCode=1;
