import '../src/features/deckcraft/yardModelAdvancedRuntime';
import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {HARDSCAPE_PRODUCTS,hardscapeBody,hardscapeSelection} from '../src/features/deckcraft/hardscapeCatalogue';
import {buildYardModel,yardClip,yardArea} from '../src/features/deckcraft/yardModel';
import {manufacturerWallSetback,wallConstructionProblem} from '../src/features/deckcraft/wallConstruction';
import {wallConstructionForPath} from '../src/features/deckcraft/wallFoundation';
import {yardWallPath} from '../src/features/deckcraft/yardPathGeometry';
import {serializeDesign,parseDesign,validateDesign} from '../src/features/deckcraft/designPersistence';
let checks=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},near=(a:number,b:number,m:string,tolerance=1e-4)=>ok(Math.abs(a-b)<tolerance,`${m}: ${a} vs ${b}`);
const p=HARDSCAPE_PRODUCTS.find(p=>p.id==='techo-raffinato-wall')!,finish=p.finishes.find(f=>f.units.some(u=>hardscapeBody(u.role)))!,unit=finish.units.find(u=>hardscapeBody(u.role))!,color=finish.colors.find(c=>!unit.colorIds||unit.colorIds.includes(c.id))!;
const base:YardFeature={id:'wall-build',name:'Stepped Raffinato wall',kind:'retaining-wall',enabled:true,xFt:14,zFt:28,widthFt:24,depthFt:unit.lengthMm/304.8,heightIn:48,rotationDeg:90,productId:p.id,color:color.hex??'#aaa69b',hardscape:{finishId:finish.id,colorId:color.id,unitId:unit.id,patternId:'running-bond',angleDeg:0,jointMm:0}};
const sel=hardscapeSelection(base)!,cap=sel.caps.find(c=>c.sourceColorId==='greyed-nickel')!,wall={...base,hardscape:{...base.hardscape!,capUnitId:cap.id},wallConstruction:{foundationMode:'stepped' as const,setbackPerCourseIn:manufacturerWallSetback(base)!.perCourseIn,geogridEveryCourses:2,drainOutletCount:2,drainOutletLengthFt:24}};
const data=(f:YardFeature,slopePct:number):DeckData=>({...structuredClone(DEFAULT_DECK),houseVisible:false,yardFeatures:[f],terrainConfig:{widthFt:100,depthFt:100,elevationIn:0,slopePct}});
const fixture=data(wall,5),stepped=buildYardModel(fixture),level=buildYardModel(data({...wall,wallConstruction:{...wall.wallConstruction,foundationMode:'level'}},5)),sf=stepped.features[0],q=sf.quantities,plan=wallConstructionForPath(wall,28*12*.05,yardWallPath(wall),z=>z*.05);
ok(q.wallFoundationSteps>0,'Sloping grade produces whole-course benches');ok(q.minWallBurialIn>=plan.minimumBurialIn-1e-4,'Stepped complete envelope retains minimum burial');ok(q.wallBlocks<level.features[0].quantities.wallBlocks,'Steps remove unnecessary buried blocks');ok(stepped.quantities.excavationYd3<level.quantities.excavationYd3,'Steps reduce measured bank excavation');ok(q.drainageYd3<level.features[0].quantities.drainageYd3,'Drainage stone follows local bench height');near(q.wallBatterAngleDeg,4.4,'Manufacturer documented setback');near(q.wallSetbackIn,plan.maxSetbackIn,'Actual cap/body setback matches plan');ok(sf.boxes.filter(b=>b.role==='wall-block').every(b=>Math.abs(b.h-plan.course)<1e-6),'Full stock body heights');ok(sf.boxes.filter(b=>b.role==='wall-cap').every(b=>Math.abs(b.y+b.h/2-plan.top)<1e-6),'Caps preserve requested level top');
const contains=(poly:{x:number;y:number}[],x:number,y:number)=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;};
for(const pipe of sf.members.filter(m=>m.role==='drain-pipe')){const x=(pipe.a.x+pipe.b.x)/2,z=(pipe.a.z+pipe.b.z)/2;ok(sf.boxes.some(b=>b.role==='geogrid'&&b.y>pipe.a.y-2&&contains(b.polygon!,x,z)),'Every stepped bench has reinforcement above its own foundation');}
const benchTops=[...new Set(sf.boxes.filter(b=>b.role==='base').map(b=>b.y+b.h/2))].sort((a,b)=>a-b);for(let i=1;i<benchTops.length;i++)near(benchTops[i]-benchTops[i-1],plan.course,'Foundation increments one exact stock course');ok(sf.members.filter(m=>m.role==='drain-pipe').every(m=>m.a.y===m.b.y),'Toe drains remain horizontal on benches');near(q.drainPipeLf,wall.widthFt+q.wallFoundationSteps*plan.course/12,'Pipe supply includes step junction drops');near(q.drainOutletPipeLf,24,'Entered outlet route is a separate quantity');near(q.drainOutletCount,2,'Outlet hardware count retained');near(q.wallCapBondLf,24,'Adhesive bond run is measured, cartridges remain specification-based');
assert.deepEqual(parseDesign(serializeDesign(fixture)).yardFeatures?.[0].wallConstruction,wall.wallConstruction);checks++;
for(const patch of [{foundationMode:'sloped'},{setbackPerCourseIn:-1},{setbackPerCourseIn:Infinity},{drainOutletCount:0},{drainOutletCount:1.5},{drainOutletLengthFt:201},{unknown:2}]){ok(!!wallConstructionProblem({...wall,wallConstruction:patch as any}),'Unsafe construction inputs rejected');assert.throws(()=>validateDesign(data({...wall,wallConstruction:patch as any},0)));checks++;}
const paths=[undefined,[{x:-120,y:-72},{x:0,y:-72},{x:0,y:72}],[{x:-120,y:-40},{x:-60,y:-10},{x:0,y:0},{x:60,y:-10},{x:120,y:-40}]];
let scenarios=0;for(const slope of [-15,-5,0,5,15])for(const rotation of [0,30,90,180,270])for(const path of paths){const f={...wall,rotationDeg:rotation,...(path?{wallPath:path,widthFt:path.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-path[i].x,p.y-path[i].y),0)/12}:{})},m=buildYardModel(data(f,slope)),feature=m.features[0],q=feature.quantities;ok(!feature.excluded,'Supported fixture stays active');const plan=wallConstructionForPath(f,f.zFt*12*slope/100,yardWallPath(f),z=>z*slope/100);ok(q.minWallBurialIn>=plan.minimumBurialIn-1e-4,`Minimum burial at ${slope}% ${rotation}° ${path?.length??2} points`);ok(q.geogridOrderSqft>=q.geogridSqft*1.1-1e-5,'Turns never underorder union reinforcement');near(q.geogridOrderSqft,q.geogridGrossSqft*1.1,'Procurement uses gross material plus explicit cutting allowance');near(q.geogridCornerOverlapSqft,Math.max(0,q.geogridGrossSqft-q.geogridSqft),'Turn overlap is explicit');for(const role of ['base','wall-drainage','backfill'] as const){const boxes=feature.boxes.filter(b=>b.role===role);near(boxes.reduce((n,b)=>n+yardArea([b.polygon!])*b.h/324,0),q[role==='base'?'wallBaseYd3':role==='wall-drainage'?'drainageYd3':'backfillYd3'],'Construction mesh volume equals quantity');}ok(Object.values(q).every(Number.isFinite),'No nonfinite quantities');scenarios++;}
const overlapWall={...base,xFt:0,zFt:0,widthFt:20+Math.hypot(18,3),heightIn:36,wallPath:[{x:-240,y:360},{x:0,y:360},{x:-216,y:396}]},overlap=buildYardModel(data(overlapWall,0)).features[0].quantities;ok(overlap.geogridGrossSqft>=overlap.geogridSqft,'Acute strips preserve gross supply');
for(const id of ['techo-sandstonethinsetveneer-wall','techo-skyscraper-wall','oaks-modeco-one']){const product=HARDSCAPE_PRODUCTS.find(p=>p.id===id)!,finish=product.finishes.find(f=>f.units.some(u=>hardscapeBody(u.role)))!,unit=finish.units.find(u=>hardscapeBody(u.role))!,color=finish.colors.find(c=>!unit.colorIds||unit.colorIds.includes(c.id))!,f={...base,productId:id,depthFt:unit.lengthMm/304.8,hardscape:{finishId:finish.id,colorId:color.id,unitId:unit.id,patternId:'running-bond',angleDeg:0,jointMm:0}},model=buildYardModel(data(f,0)),feature=model.features[0];ok(feature.quantities.wallAssemblyPending===1&&feature.quoteRequired,'Incomplete assembly stays pending');ok(!feature.stockSchedule&&feature.quantities.wallBlocks===0&&feature.quantities.wallCaps===0,'Conceptual stock is not published as executable material count');ok(feature.quantities.wallConceptualBlocks>0,'Visualization envelope retained separately');ok(model.quoteRequired,'Project carries unresolved assembly scope');if(id==='oaks-modeco-one'){ok(feature.quantities.wallTopCourseNative===1,'Modeco keeps native top course');ok(feature.warnings.some(w=>w.includes('445 mm')),'Manufacturer total-height boundary explicit');}}
if(process.env.WALL_EXECUTION_PROOF){const out=process.env.WALL_EXECUTION_PROOF;mkdirSync(out,{recursive:true});writeFileSync(`${out}/construction-browser.json`,serializeDesign(fixture));writeFileSync(`${out}/construction-checks.json`,JSON.stringify({checks,scenarios,stepped:sf.quantities,level:level.features[0].quantities,foundationTops:benchTops,sources:{setback:manufacturerWallSetback(wall)?.sourceUrl,foundation:'https://www.techo-bloc.com/assets/1f/a6/1fa6d9e2-1be1-4550-8d88-46bfdeceb120/WALLS_Installation-guide-EN.pdf'}},null,2));}
console.log(`Wall execution: ${checks} checks across ${scenarios} slope/path/batter scenarios passed.`);
