import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate,serializeDeckReleaseDesign,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {quoteScopeReview} from '../src/features/deckcraft/designer/quoteReviewModel';
import {quoteCostFromUnitRates,quoteUnitBasis} from '../src/features/deckcraft/designer/quoteQuantityPricing';
import {confirmQuoteScope,validateQuoteResolutions,QUOTE_RESOLUTION_LIMITS} from '../src/features/deckcraft/quoteResolutionValidation';
import {splitSubtotal} from '../src/features/deckcraft/backyard';
import {emptyJobLibrary,saveJobRevision,revisionRestoreDesign,exportJobLibrary} from '../src/features/deckcraft/designer/jobRevisionLibrary';
import {earthworkMissingInputs} from '../src/features/deckcraft/yardEarthwork';
import {wallQuoteScopes} from '../src/features/deckcraft/yardQuoteScopes';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
let checks=0;const check=(v:unknown,msg:string)=>{assert.ok(v,msg);checks++;},near=(a:number,b:number,msg:string)=>check(Math.abs(a-b)<1e-7,msg),reject=(f:()=>unknown)=>{assert.throws(f);checks++;};
const fixture=JSON.parse(readFileSync(new URL('./fixtures/yard-quote-costs.json',import.meta.url),'utf8'));
const original=fixture.wall as YardFeature;
const wall:YardFeature={...original,id:'quote-wall',name:'QA wall',xFt:0,zFt:0};
const data:DeckData={...structuredClone(DEFAULT_DECK),...fixture.base,materialMarkup:20,customerName:'TEST QUOTES ONLY',yardFeatures:[wall]};
const before=calculateDeckReleaseEstimate(data),review=quoteScopeReview(data,before),yard=before.yardModel.features.find(f=>f.config.id===wall.id)!;
const find=(word:string)=>review.scopes.find(s=>s.name===`QA wall: ${word}`)!;
for(const name of ['Wall body stock supply','Selected cap stock supply','Wall body and cap installation','Geogrid stock supply','Geogrid installation','Compacted leveling aggregate and placement','Drainage stone and placement','Reinforced backfill and compaction','Wall separator fabric and installation','Main perforated drain and installation','Drain outlet fittings and termination','Cap adhesive and installation','Core-fill stone, connectors and special stock','Wall packaging, freight and order adjustments'])check(!!find(name),`Independent measured scope exists: ${name}`);
near(Number(find('Wall body stock supply').rows[0].qty),yard.quantities.wallBlocks,'Body supply uses full stock blank count including buried courses');
near(Number(find('Selected cap stock supply').rows[0].qty),yard.quantities.wallCaps,'Cap supply uses independent stock count');
near(Number(find('Geogrid stock supply').rows[0].qty),yard.quantities.geogridOrderSqft,'Grid supply has procurement allowance');
near(Number(find('Geogrid installation').rows[0].qty),yard.quantities.geogridSqft,'Grid install has net union area');
check(review.requirements.includes('QA wall: selected wall system and site design confirmation'),'Cost entry cannot approve wall system');
check(review.requirements.includes('QA wall: drain outlet route and length confirmation'),'Missing outlet route remains physical input');
check(review.requirements.includes('Soil reuse, loose spoil and hauling confirmation'),'Missing soil/bin values remain physical input');
check(!review.scopes.some(s=>review.requirements.includes(s.name)),'Physical statuses have no payable resolution scope');
const unresolved=wallQuoteScopes({...yard,quantities:{...yard.quantities,wallAssemblyPending:1}},false);
check(!unresolved.some(s=>/Wall body stock supply|Selected cap stock supply/.test(s.label)),'Incomplete assembly exposes no executable body or cap stock order');
check(unresolved.some(s=>s.label.includes('manufacturer backing and top-course assembly confirmation')),'Incomplete assembly has a persistent prerequisite');
check(!!before.yardTakeoff.sections.find(s=>s.id==='yard-excavation-equipment'),'Supplier-only wall has explicit shared excavation labour/equipment scope');
const body=find('Wall body stock supply'),costs=quoteCostFromUnitRates(body,'12.34','1.25'),qty=yard.quantities.wallBlocks;
near(costs.supplyCost,Math.round(qty*12.34*100)/100,'Measured supply rate rounded once to CAD cents');near(costs.installationCost,Math.round(qty*1.25*100)/100,'Measured install rate rounded once to CAD cents');
check(quoteUnitBasis(body)?.unit==='stock units','Unit entry uses original measured unit');check(!quoteUnitBasis(find('Core-fill stone, connectors and special stock')),'Uncounted accessories require a scope total');
for(const rate of ['NaN','Infinity','-1','.001','1000001'])reject(()=>quoteCostFromUnitRates(body,rate,'0'));reject(()=>quoteCostFromUnitRates(find('Core-fill stone, connectors and special stock'),'1','1'));
const record=confirmQuoteScope(body,{supplyCost:costs.supplyCost,installationCost:costs.installationCost,confirmedOn:'2026-09-30',source:'QA ONLY · no actual supplier price',note:'TEST ONLY: body stock supply and body placement; exclude caps and other measured scopes.'}),priced={...data,quoteResolutions:[record]},after=calculateDeckReleaseEstimate(priced),increment=costs.supplyCost*1.2+costs.installationCost;
near(after.subtotal-before.subtotal,increment,'Marked supply plus unmarked installation counted once');near(after.hst-before.hst,increment*.13,'HST applied once');near(splitSubtotal(after).backyard-splitSubtotal(before).backyard,increment,'All wall quote amount belongs to backyard');near(splitSubtotal(after).deck,splitSubtotal(before).deck,'Deck subtotal unchanged by wall quote');near(after.yardTakeoff.knownSubtotalCents-before.yardTakeoff.knownSubtotalCents,Math.round(increment*100),'Yard public summary tracks confirmed wall cost');
check(after.quoteRequired.includes('QA wall: selected wall system and site design confirmation'),'Design status still pending after body quote');check(after.quoteResolutionReview?.active.includes(body.key),'Exact geometry quote active');check(!after.sections.some(s=>s.title==='Confirmed additional quote costs'),'Yard quote does not create deck addition bucket');
check(!JSON.stringify(after.sections).includes(record.source)&&!JSON.stringify(after.sections).includes(record.note),'Private quote provenance excluded from public sections');
const reopened=quoteScopeReview(priced,after).scopes.find(s=>s.key===body.key)!;check(reopened.known.some(i=>i.name==='Shared excavation disposal'),'Yard scope exposes already-priced disposal benchmark');check(!reopened.known.some(i=>i.name===body.name),'Added resolution does not become included base-work quote');
const moved={...priced,yardFeatures:[{...wall,heightIn:wall.heightIn+6}]},changed=calculateDeckReleaseEstimate(moved);check(changed.quoteResolutionReview?.inactive===1,'Changed wall quantities make prior quote inactive');near(changed.total,calculateDeckReleaseEstimate({...moved,quoteResolutions:undefined}).total,'Stale quote never included');
const earthwork={soilReusePct:20,spoilSwellPct:25,looseSpoilTonnesPerYd3:1.2,binVolumeYd3:8,binPayloadTonnes:6};check(earthworkMissingInputs().length===4,'Blank physical fields named');check(!earthworkMissingInputs(earthwork).length,'Complete hauling fields detected');
const supplied={...priced,yardEarthwork:earthwork},publicText=serializeDeckReleaseDesign(supplied),parsed=parseDeckReleaseDesign(publicText);assert.deepEqual(parsed.yardEarthwork,earthwork);checks++;check(!publicText.includes('quoteResolutions'),'Public design excludes private supplier amounts');
const library=saveJobRevision(emptyJobLibrary(),supplied,'QA yard quote job','Soil values and wall quote'),revision=library.jobs[0].revisions[0],restored=revisionRestoreDesign(revision,supplied);assert.deepEqual(restored.yardEarthwork,earthwork);checks++;assert.deepEqual(restored.quoteResolutions,[record]);checks++;check(!exportJobLibrary(library).includes('QA ONLY'),'Portable jobs omit private quote evidence');
const fullyConfirmed={...supplied,quoteResolutions:quoteScopeReview(supplied,calculateDeckReleaseEstimate(supplied)).scopes.filter(s=>s.rows.some(r=>r.sectionTitle.startsWith('Yard ·'))).map(s=>confirmQuoteScope(s,{supplyCost:1,installationCost:1,confirmedOn:'2026-09-30',source:'QA',note:'QA only.'}))},allPriced=calculateDeckReleaseEstimate(fullyConfirmed);
check(allPriced.quoteRequired.includes('QA wall: selected wall system and site design confirmation'),'Confirming every priced yard scope still cannot approve structural design');
check(!allPriced.quoteRequired.includes('Soil reuse, loose spoil and hauling confirmation'),'Entered physical hauling values remove their missing-input requirement');
check(quoteScopeReview(fullyConfirmed,allPriced).requirements.includes('QA wall: drain outlet route and length confirmation'),'Costs do not invent an outlet route');
const records=Array.from({length:320},(_,i)=>({...record,scopeKey:`quote-${i.toString(16).padStart(16,'0')}`,note:'QA',source:'QA'}));check(validateQuoteResolutions(records).length===320,'Twenty walls can retain hundreds of independent scope records within bytes limit');reject(()=>validateQuoteResolutions(Array.from({length:QUOTE_RESOLUTION_LIMITS.count+1},(_,i)=>({...record,scopeKey:`quote-${i.toString(16).padStart(16,'0')}`,note:'QA',source:'QA'}))));
if(process.env.YARD_QUOTE_PROOF){mkdirSync(process.env.YARD_QUOTE_PROOF,{recursive:true});writeFileSync(`${process.env.YARD_QUOTE_PROOF}/browser-fixture.json`,JSON.stringify({patch:{...fixture.base,yardFeatures:[wall],yardEarthwork:earthwork},scopeName:body.name,unitSupply:'12.34',unitInstallation:'1.25',quantity:qty,expectedDeltaAt20PctMarkup:increment,testOnly:true},null,2));writeFileSync(`${process.env.YARD_QUOTE_PROOF}/checks.json`,JSON.stringify({checks,wallQuantities:yard.quantities,quoteScopes:review.scopes.map(s=>s.name),requirements:review.requirements},null,2));}
console.log(`Yard quote costs: ${checks} checks passed.`);
