import '../src/features/deckcraft/stairTargetsRuntime';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {newYardFeature} from '../src/features/deckcraft/yardSettings';
import {yardSurfaceIn} from '../src/features/deckcraft/yardElevations';
import {editYardFinished} from '../src/features/deckcraft/yardFinishedEdits';
import {validateYardFinishedSettings} from '../src/features/deckcraft/yardFinishedSettings';
import {yardShapeResize,yardShapeMove,yardShapeEdit,yardShapeWorldPoints} from '../src/features/deckcraft/yardShapeEditing';
import {curveYardEdge} from '../src/features/deckcraft/yardDesignTools';
import {serializeDeckReleaseDesign,parseDeckReleaseDesign,deckReleaseData} from '../src/features/deckcraft/deckRelease';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {parseNaturalLanguageCommands} from '../src/features/deckcraft/designer/naturalLanguageCommands';
import {parseAssistantPlan} from '../src/features/deckcraft/designer/assistantPlan';
import {emptyOrganization} from '../src/features/deckcraft/editorOrganization';
let checks=0;const check=(name:string,work:()=>void)=>{work();checks++;};
async function main(){
 const d=structuredClone(DEFAULT_DECK),patio={...newYardFeature('patio',d),id:'fixed-patio',name:'Fixed patio'},wall={...newYardFeature('retaining-wall',d),id:'fixed-wall',name:'Stepped wall'};
 check('New objects pin centre top',()=>{assert.equal(patio.finishedElevationIn,0);assert.equal(wall.finishedElevationIn,24);assert.deepEqual(patio.patioSlope,{xPct:0,zPct:0});});
 check('Ground and move preserve fixed tops',()=>{const raised={...d,terrainConfig:{widthFt:80,depthFt:80,elevationIn:12,slopePct:4}};assert.equal(yardSurfaceIn(raised,patio),0);assert.equal(yardSurfaceIn(raised,yardShapeMove(wall,12,24)),24);});
 const {finishedElevationIn:_top,patioSlope:_slope,...legacy}=patio,raised={...d,terrainConfig:{widthFt:80,depthFt:80,elevationIn:8,slopePct:2}};
 check('Legacy follows grade and explicit conversion preserves current world top',()=>{const before=yardSurfaceIn(raised,legacy),pin=editYardFinished(raised,legacy,{action:'pin'});assert.equal(pin.finishedElevationIn,before);assert.equal(yardSurfaceIn({...raised,terrainConfig:{...raised.terrainConfig,elevationIn:42}},pin),before);assert.ok(!("finishedElevationIn" in legacy));});
 check('Slope survives canonical recentring without moving the world plane',()=>{const f=editYardFinished(d,patio,{action:'slope',xPct:2,zPct:-1}),p=yardShapeWorldPoints(f);p[1]={x:p[1].x+24,y:p[1].y};p[2]={x:p[2].x+24,y:p[2].y};const reshaped=yardShapeEdit(f,p);assert.equal(reshaped.finishedElevationIn,.24);assert.equal(reshaped.patioSlope?.xPct,2);assert.equal(yardShapeMove(f,24,0).finishedElevationIn,0);});
 const sloped=editYardFinished(d,patio,{action:'slope',xPct:2,zPct:-1}),stepped=editYardFinished(d,wall,{action:'steps',steps:[{stationIn:96,elevationIn:30},{stationIn:144,elevationIn:18}]});
 check('Whole course wall steps and level translation',()=>{assert.equal(stepped.wallTopSteps?.length,2);const moved=editYardFinished(d,stepped,{action:'level',elevationIn:36});assert.deepEqual(moved.wallTopSteps,[{stationIn:96,elevationIn:42},{stationIn:144,elevationIn:30}]);assert.throws(()=>editYardFinished(d,wall,{action:'steps',steps:[{stationIn:96,elevationIn:29}]}));});
 check('Shortened path rejects out-of-range stations atomically',()=>{assert.throws(()=>yardShapeResize(stepped,8));assert.equal(stepped.widthFt,16);const curved=curveYardEdge(stepped,0,36);assert.equal(curved.wallTopSteps?.[0].stationIn,96);assert.throws(()=>validateYardFinishedSettings({...stepped,wallTopSteps:[{stationIn:192,elevationIn:30}]}));});
 check('Unsafe settings reject without executing getter',()=>{let calls=0;const hostile={...patio};Object.defineProperty(hostile,'patioSlope',{get:()=>{calls++;return {xPct:0,zPct:0};},enumerable:true});assert.throws(()=>validateYardFinishedSettings(hostile));assert.equal(calls,0);assert.throws(()=>validateYardFinishedSettings({...wall,patioSlope:{xPct:0,zPct:0}}));assert.throws(()=>validateYardFinishedSettings({...patio,patioSlope:{xPct:Infinity,zPct:0}}));});
 const saved={...d,yardFeatures:[sloped,stepped],stairTargets:[{flightId:'grade-0',elevationIn:3,riserCount:5,treadDepthIn:11,surface:'terrain' as const}]};
 check('Public project serialization preserves optional settings and legacy absence',()=>{const round=parseDeckReleaseDesign(serializeDeckReleaseDesign(saved));assert.deepEqual(round.yardFeatures,saved.yardFeatures);assert.deepEqual(round.stairTargets,saved.stairTargets);const old=parseDeckReleaseDesign(serializeDeckReleaseDesign({...d,yardFeatures:[legacy]}));assert.equal(old.yardFeatures?.[0].finishedElevationIn,undefined);assert.equal(old.yardFeatures?.[0].patioSlope,undefined);});
 let state:DeckAgentHostState={data:deckReleaseData({...d,yardFeatures:[patio,wall]}),ready:true,view:'plan',openSections:[],canUndo:false,canRedo:false},previous=state.data,commits=0;
 const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{previous=state.data;state={...state,data:next,canUndo:true};commits++;},undo:()=>{state={...state,data:previous,canUndo:false,canRedo:true};},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:test=>{assert.ok(test(state));return Promise.resolve();}});
 const snapshot=api.read(),request={id:'fixed-editor-preview',expectedRevision:snapshot.revision,commands:[{type:'yard.finished' as const,id:patio.id,edit:{action:'level' as const,elevationIn:6}}]};
 const preview=await api.preview(request);assert.ok(!('error'in preview),JSON.stringify(preview));checks++;assert.equal(commits,0);checks++;
 const applied=await api.execute(request);assert.ok(!('error'in applied),JSON.stringify(applied));checks++;assert.equal(commits,1);checks++;assert.equal(state.data.yardFeatures?.[0].finishedElevationIn,6);checks++;
 const stale=await api.execute({...request,id:'fixed-editor-stale'});assert.ok('error'in stale);checks++;
 const undo=await api.execute({id:'fixed-editor-undo',expectedRevision:api.read().revision,commands:[{type:'history.undo'}]});assert.ok(!('error'in undo));checks++;assert.equal(state.data.yardFeatures?.[0].finishedElevationIn,0);checks++;
 const o=emptyOrganization();o.objects.push({id:patio.id,layerId:o.layers[0].id,locked:true});state={...state,data:{...state.data,editorOrganization:o}};api.notify();const locked=await api.execute({...request,id:'fixed-editor-locked',expectedRevision:api.read().revision});assert.ok('error'in locked);checks++;
 const selection={partIds:[],boards:[],yard:{id:wall.id,target:'area' as const,index:0}};
 check('Voice lowering uses a negative absolute delta on fixed tops',()=>{const p=parseNaturalLanguageCommands('lower this wall six inches',api.read(),selection);assert.ok(!('clarification'in p));if('request'in p)assert.deepEqual(p.request.commands[0],{type:'yard.finished',id:wall.id,edit:{action:'level',elevationIn:18}});else assert.fail('Voice must produce an edit');});
 check('Voice slopes and top-step station commands retain exact targets',()=>{const s=parseNaturalLanguageCommands('slope this patio two percent out into the yard',api.read(),{partIds:[],boards:[],yard:{id:patio.id,target:'area',index:0}});assert.ok('request'in s);if('request'in s)assert.equal(s.request.commands[0].type,'yard.finished');const w=parseNaturalLanguageCommands('step this wall at eight feet to eighteen inches',api.read(),selection);assert.ok('request'in w);if('request'in w)assert.deepEqual(w.request.commands[0],{type:'yard.finished',id:wall.id,edit:{action:'steps',steps:[{stationIn:96,elevationIn:18}]}});});
 check('Assistant accepts finished operations and excludes unsupported fields',()=>{assert.ok(parseAssistantPlan({kind:'edit',message:'Set finished level.',assumptions:[],commands:[{type:'yard.finished',id:wall.id,edit:{action:'level',elevationIn:36}}]}).ok);assert.ok(!parseAssistantPlan({kind:'edit',message:'Bad setting.',assumptions:[],commands:[{type:'yard.finished',id:wall.id,edit:{action:'level',elevationIn:36,price:4}}]}).ok);});
 console.log(`Fixed elevation editor: ${checks} checks passed.`);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
