import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {emptyHistory,recordChange,undoChange} from '../src/features/deckcraft/designer/designHistory';
import {encodeDesignLink,decodeDesignLink} from '../src/features/deckcraft/designLink';
import {exportProjectBundle,importProjectBundle} from '../src/features/deckcraft/projectBundle';
import {saveStoredProject,readProjectValue,closeProjectStorage} from '../src/features/deckcraft/projectStorage';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {deckExportMeshes} from '../src/features/deckcraft/designExports';
import {exportDeckGlb} from '../src/features/deckcraft/cadExports';
import {objectPick} from '../src/features/deckcraft/components/viewer3d/SelectionBridge';
import {boxSelection,matchesHardscape} from '../src/features/deckcraft/designer/hardscapeSelection';
import {buildAssistantContext,parseAssistantPlan,assistantPlanRequest} from '../src/features/deckcraft/designer/assistantPlan';
import {parseNaturalLanguageCommands} from '../src/features/deckcraft/designer/naturalLanguageCommands';
import {HARDSCAPE_PRODUCTS,rectangularUnit} from '../src/features/deckcraft/hardscapeCatalogue';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {buildYardModel,yardArea,yardClip} from '../src/features/deckcraft/yardModel';
import {convertStoneSteps,stepAssemblyPatch,buildStepAssemblyModel,validateStepAssembly,stepPresets} from '../src/features/deckcraft/stepAssemblyRuntime';
import {serializeDesign,parseDesign} from '../src/features/deckcraft/designPersistence';
let checks=0;const equal=(a:unknown,b:unknown)=>{assert.deepEqual(a,b);checks++;};const ok=(v:unknown)=>{assert.ok(v);checks++;};const near=(a:number,b:number)=>ok(Math.abs(a-b)<Math.max(1e-8,Math.abs(b)*.001));
const f:YardFeature={id:'steps',name:'Steps',kind:'patio',enabled:true,xFt:60,zFt:60,widthFt:8,depthFt:8,heightIn:0,rotationDeg:0,productId:'permacon-mondrian-plus',color:'#b8b5ae',finishedElevationIn:24,stoneSteps:{lowerElevationIn:0,riserCount:4,treadRunIn:24,stockWidthIn:48,stockDepthIn:24,stockThicknessIn:6,baseDepthIn:6,settingBedIn:1,jointIn:.125,productName:'Recorded step stock',support:{kind:'full-step',courses:[0,1,2,3]}}};
const make=(f:YardFeature,ground=0):DeckData=>({...structuredClone(DEFAULT_DECK),houseVisible:false,stairFlights:0,railingType:'None',yardFeatures:[f],terrainConfig:{widthFt:250,depthFt:250,elevationIn:ground,slopePct:0}});
await ensureLiveDesignExtensions(make(f));const converted=convertStoneSteps(f);await ensureLiveDesignExtensions(make(converted));
const legacy=buildYardModel(make(f)),advanced=buildYardModel(make(converted)),q=advanced.features[0].quantities;
equal(q.stoneStepPieces,8);equal(q.stoneSupportStepPieces,12);equal(q.stoneStepCuts,4);equal(q.stoneSupportStepCuts,6);
for(const key of ['baseYd3','beddingYd3','raisedFillYd3','stoneSupportVolumeYd3'] as const)near(q[key]!,legacy.features[0].quantities[key]!);
near(advanced.quantities.sharedExcavationYd3,legacy.quantities.sharedExcavationYd3);
const solids=(m:typeof advanced)=>m.features[0].boxes.filter(b=>b.role==='stone-step').map(b=>[b.x,b.z,b.y,b.w,b.d,b.h]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));
equal(solids(advanced),solids(legacy));
equal(parseDesign(serializeDesign(make(converted))).yardFeatures?.[0].stepAssembly,converted.stepAssembly);
const a=structuredClone(converted.stepAssembly!);a.flights[0].layout='flared';a.flights[0].wideningIn=12;const flared=buildStepAssemblyModel(stepAssemblyPatch(converted,a),undefined,{x:0,z:0,constant:0});equal(flared.quantities.stoneStepPieces,11);ok(flared.boxes.every(b=>b.role!=='stone-step'||b.h===6));
const curve=structuredClone(a);curve.flights[0].layout='curved';curve.flights[0].sweepDeg=90;curve.tread.jointIn=0;const curved=buildStepAssemblyModel(stepAssemblyPatch(converted,curve),undefined,{x:0,z:0,constant:0});
const expected=Math.PI/4*((96+4*24)**2-96**2)/144;near(curved.quantities.stoneStepAreaSqft,expected);near(curved.quantities.baseYd3,expected*6/324);ok(curved.quantities.stoneStepCuts>0);
for(const angle of [0,37,90]){const model=buildStepAssemblyModel({...converted,rotationDeg:angle},undefined,{x:0,z:0,constant:0});equal(model.quantities.stoneStepPieces,8);near(model.quantities.baseYd3,64*6/324);}
const wrap=structuredClone(a);wrap.flights[0].layout='wraparound';wrap.flights[0].wrapSides=['front','left','right','back'];wrap.tread.jointIn=0;const wrapped=buildStepAssemblyModel(stepAssemblyPatch(converted,wrap),undefined,{x:0,z:0,constant:0});near(wrapped.quantities.stoneStepAreaSqft,((96+192)*(48+192)-96*48)/144);
const cap=structuredClone(a);cap.family='cap-block';cap.tread={...cap.tread,thicknessIn:2};cap.riser={...cap.tread,depthIn:8,thicknessIn:4};cap.support=cap.riser;cap.supportMode='wall-block';cap.flights[0].layout='straight';cap.flights[0].riserCourses=[1,1,1,1];cap.flights[0].courses=[0,1,2,3];const capModel=buildStepAssemblyModel(stepAssemblyPatch(converted,cap),undefined,{x:0,z:0,constant:0});ok(capModel.quantities.stepRiserBlocks>0);ok(capModel.quantities.stepSupportBlocks>0);ok(capModel.quantities.stepEngineeredFillYd3>0);ok(capModel.boxes.filter(b=>b.stonePart==='tread').every(b=>b.h===2));
const stone=structuredClone(a);stone.family='natural-stone';stone.supportMode='filler';stone.support={...stone.tread,widthIn:24,depthIn:12,thicknessIn:3};stone.flights[0].layout='straight';stone.flights[0].courses=[0,2,4,6];const natural=buildStepAssemblyModel(stepAssemblyPatch(converted,stone),undefined,{x:0,z:0,constant:0});equal(natural.quantities.stoneFillerPieces,96);near(natural.quantities.baseYd3,64*6/324);
const raised=buildYardModel(make(converted,2));equal(raised.features[0].boxes.filter(b=>b.role==='stone-step').map(b=>b.y),advanced.features[0].boxes.filter(b=>b.role==='stone-step').map(b=>b.y));near(raised.quantities.sharedExcavationYd3,64*9/324);
assert.throws(()=>validateStepAssembly({...converted,stoneSteps:f.stoneSteps},a));checks++;
const bad=structuredClone(a);bad.flights[0].rowOverrides=[{row:20,courses:1}];assert.throws(()=>stepAssemblyPatch(converted,bad));checks++;
for(const family of ['manufactured','cap-block','natural-stone'] as const)for(const layout of ['straight','flared','curved','wraparound'] as const){const source=family==='cap-block'?cap:family==='natural-stone'?stone:a,assembly=structuredClone(source);assembly.flights[0].layout=layout;const model=buildStepAssemblyModel(stepAssemblyPatch({...converted,rotationDeg:37},assembly),undefined,{x:.01,z:.02,constant:0});ok(!model.conflicts.length);ok(model.boxes.filter(b=>b.stonePart==='tread').every(b=>b.h===assembly.tread.thicknessIn));}
const turn=structuredClone(converted.stepAssembly!),first=turn.flights[0];first.upperLandingId='landing';turn.landings=[{id:'landing',name:'Turning landing',xIn:0,zIn:96,rotationDeg:0,widthIn:96,depthIn:96,elevationIn:24,courses:4}];turn.flights.push({...structuredClone(first),id:'flight-2',name:'Flight 2',xIn:96,zIn:96,rotationDeg:-90,lowerElevationIn:24,upperElevationIn:48,upperLandingId:undefined,lowerLandingId:'landing'});const turning=stepAssemblyPatch(converted,turn),turnModel=buildStepAssemblyModel(turning,undefined,{x:0,z:0,constant:0});ok(!turnModel.conflicts.length);ok(!turnModel.warnings.some(w=>w.includes('does not meet')));ok(turnModel.quantities.stepLandingPieces>0);
const colliding=structuredClone(turn);colliding.flights[1].xIn=0;colliding.flights[1].zIn=0;colliding.flights[1].lowerElevationIn=0;colliding.flights[1].upperElevationIn=24;delete colliding.flights[1].lowerLandingId;assert.throws(()=>stepAssemblyPatch(converted,colliding));checks++;
const overriding=structuredClone(turn);overriding.flights[1].tread={...turn.tread,thicknessIn:4};overriding.flights[1].rowOverrides=[{row:2,tread:{...turn.tread,thicknessIn:3},courses:1}];const overrides=buildStepAssemblyModel(stepAssemblyPatch(converted,overriding),undefined,{x:0,z:0,constant:0});ok(overrides.boxes.filter(b=>b.stepFlightId==='flight-1'&&b.stonePart==='tread').every(b=>b.h===6));ok(overrides.boxes.filter(b=>b.stepFlightId==='flight-2'&&b.stepRow===2&&b.stonePart==='tread').every(b=>b.h===3));
const pick=boxSelection(advanced.features[0].boxes.find(b=>b.stonePart==='support-step')!),geometry=new THREE.BufferGeometry();geometry.userData.hardscapeRanges=[{start:0,end:12,pick}];const mesh=new THREE.Mesh(geometry);equal(objectPick(mesh,undefined,11),{hardscape:pick});equal(objectPick(mesh,undefined,12),null);ok(matchesHardscape({kind:'yard',id:converted.id},pick));ok(!matchesHardscape({...pick,row:19},pick));geometry.dispose();
let state:DeckAgentHostState={data:make(f),view:'3d',openSections:[],canUndo:false,canRedo:false,ready:true},history=emptyHistory<DeckData>(),commits=0;
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{history=recordChange(history,state.data,'advanced',++commits);state={...state,data:next,canUndo:true,canRedo:false};},undo:()=>{const u=undoChange(history,state.data);history=u.history;state={...state,data:u.design,canUndo:false,canRedo:true};},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:()=>Promise.resolve()});
const request={id:'convert-preview',expectedRevision:api.read().revision,commands:[{type:'yard.stepConvert' as const,id:f.id}]};const preview=await api.preview(request);ok(preview.ok);equal(commits,0);equal(state.data.yardFeatures?.[0].stoneSteps,f.stoneSteps);ok((await api.execute({...request,id:'convert-apply'})).ok);equal(commits,1);equal(state.data.yardFeatures?.[0].finishedElevationIn,24);const revision=api.read().revision;ok(!(await api.execute({...request,id:'stale-convert'})).ok);
const selection={partIds:[],boards:[],hardscape:{kind:'yard' as const,id:f.id,flightId:'flight-1',row:2,part:'support-step'}},context=buildAssistantContext(api.read(),selection);equal(context.selection.hardscape,selection.hardscape);const voice=parseNaturalLanguageCommands('Set selected support courses to 1',api.read(),selection);ok(voice.ok);if(voice.ok){const v=await api.preview(voice.request);ok(v.ok);equal(commits,1);ok((await api.execute(voice.request)).ok);equal(commits,2);equal(state.data.yardFeatures![0].stepAssembly!.flights[0].rowOverrides[0].courses,1);}
const ai=parseAssistantPlan({kind:'edit',message:'Adjust row support',assumptions:[],commands:[{type:'yard.stepRow',id:f.id,flightId:'flight-1',row:2,edit:{courses:2}}]});ok(ai.ok);if(ai.ok){const translated=assistantPlanRequest(ai.plan,{id:'assistant-row',expectedRevision:api.read().revision,snapshot:api.read(),selection,requestText:'Set these supports to two courses'});ok(translated.commands.length===1);}
ok((await api.execute({id:'undo-row',commands:[{type:'history.undo'}],expectedRevision:api.read().revision})).ok);equal(state.data.yardFeatures![0].stepAssembly?.flights[0].rowOverrides,[]);
state={...state,data:{...state.data,editorOrganization:{layers:[{id:'locked',name:'Locked',visible:true,locked:true}],groups:[],objects:[{id:f.id,layerId:'locked',locked:false}]}}};const locked=await api.preview({id:'locked-row',expectedRevision:api.read().revision,commands:[{type:'yard.stepRow',id:f.id,flightId:'flight-1',row:0,edit:{courses:1}}]});ok(!locked.ok);api.dispose();
const roundTrip=make(turning);const canonicalAssembly=JSON.parse(JSON.stringify(turning.stepAssembly));await ensureLiveDesignExtensions(roundTrip);const link=await encodeDesignLink(roundTrip,'https://example.com');equal((await decodeDesignLink(new URL(link).hash.slice(3))).yardFeatures?.[0].stepAssembly,canonicalAssembly);
const bundle=await exportProjectBundle(roundTrip);const imported=await importProjectBundle(bundle);equal(imported.yardFeatures?.[0].stepAssembly,canonicalAssembly);
await saveStoredProject('current',serializeDesign(roundTrip));equal(parseDesign((await readProjectValue<{json:string}>('projects','current'))!.json).yardFeatures?.[0].stepAssembly,canonicalAssembly);closeProjectStorage();
const separated=structuredClone(turn);separated.landings[0].zIn+=.5;ok(buildStepAssemblyModel(stepAssemblyPatch(converted,separated),undefined,{x:0,z:0,constant:0}).warnings.some(w=>w.includes('does not meet')));
const openRun=structuredClone(converted.stepAssembly!);openRun.flights[0].runIn=30;ok(buildStepAssemblyModel(stepAssemblyPatch(converted,openRun),undefined,{x:0,z:0,constant:0}).warnings.some(w=>w.includes('open walking gap')));
const verifiedStock=structuredClone(converted.stepAssembly!);const catalogueProduct=HARDSCAPE_PRODUCTS.find(p=>p.finishes.some(f=>f.units.some(rectangularUnit)))!,catalogueFinish=catalogueProduct.finishes.find(f=>f.units.some(rectangularUnit))!,catalogueUnit=catalogueFinish.units.find(rectangularUnit)!;verifiedStock.tread={...verifiedStock.tread,productId:catalogueProduct.id,finishId:catalogueFinish.id,unitId:catalogueUnit.id,widthIn:catalogueUnit.widthMm/25.4+1,depthIn:catalogueUnit.lengthMm/25.4,thicknessIn:catalogueUnit.heightMm/25.4};assert.throws(()=>stepAssemblyPatch(converted,verifiedStock));checks++;
equal(new Set(capModel.boxes.map(b=>b.id)).size,capModel.boxes.length);
for(const unit of capModel.boxes.filter(b=>b.role==='stone-step'&&b.stonePart!=='tread')){const under=unit.y-unit.h/2,beds=capModel.boxes.filter(b=>(b.role==='bedding'||b.role==='stone-step'&&b.stonePart!=='tread')&&b.stepFlightId===unit.stepFlightId&&b.stepRow===unit.stepRow&&Math.abs(b.y+b.h/2-under)<1e-7);near(yardArea(yardClip([unit.polygon!],beds.map(b=>b.polygon!),'intersection')),yardArea([unit.polygon!]));}
const nosed=structuredClone(converted.stepAssembly!);nosed.tread.jointIn=0;nosed.overhangIn=.75;const nosedModel=buildStepAssemblyModel(stepAssemblyPatch(converted,nosed),undefined,{x:0,z:0,constant:0});near(nosedModel.quantities.stoneStepAreaSqft,64);equal(nosedModel.quantities.stoneStepPieces,8);
for(const assembly of [converted.stepAssembly!,cap,stone]){const feature=stepAssemblyPatch(converted,assembly),design=make(feature);await ensureLiveDesignExtensions(design);const deck=buildDeckTakeoff(design),physical=buildYardModel(design,deck),exported=deckExportMeshes(design,deck);for(const unit of physical.boxes.filter(b=>b.role==='stone-step')){const mesh=exported.find(m=>m.name==='yard_'+unit.id)!;ok(!!mesh);near(Math.max(...mesh.vertices.map(v=>v.y))-Math.min(...mesh.vertices.map(v=>v.y)),unit.h);ok(mesh.vertices.every(v=>unit.polygon!.some(p=>Math.hypot(v.x-p.x,v.z-p.y)<.00001)));}const buffer=exportDeckGlb(design,deck);equal(new DataView(buffer).getUint32(0,true),0x46546c67);}
equal(stepPresets().length,3);console.log(`Advanced step assemblies: ${checks} checks passed`);
