import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {validateDesign,serializeDesign,parseDesign} from '../src/features/deckcraft/designPersistence';
import {validateYardFinishedSettings} from '../src/features/deckcraft/yardFinishedSettings';
import {buildYardModel} from '../src/features/deckcraft/yardModel';
import {buildYardTakeoff} from '../src/features/deckcraft/yardTakeoff';
import {encodeDesignLink,decodeDesignLink} from '../src/features/deckcraft/designLink';
import {exportProjectBundle,importProjectBundle} from '../src/features/deckcraft/projectBundle';
import {saveStoredProject,readProjectValue,closeProjectStorage} from '../src/features/deckcraft/projectStorage';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {emptyHistory,recordChange,undoChange} from '../src/features/deckcraft/designer/designHistory';
import {buildAssistantContext,assistantPlanSchemaForContext,parseAssistantPlan,assistantPlanRequest} from '../src/features/deckcraft/designer/assistantPlan';

let checks=0;
const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;};
const equal=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);checks++;};
const near=(actual:number,expected:number,m:string)=>ok(Math.abs(actual-expected)<Math.max(1e-8,Math.abs(expected)*.001),`${m}: ${actual} versus ${expected}`);
const invalid=(action:()=>unknown,m:string)=>{assert.throws(action,undefined,m);checks++;};
const legacyFlight:YardFeature={id:'stone-flight',name:'Solid stairs',kind:'patio',enabled:true,xFt:60,zFt:60,widthFt:8,depthFt:8,heightIn:0,rotationDeg:0,productId:'permacon-mondrian-plus',color:'#b8b5ae',finishedElevationIn:24,stoneSteps:{lowerElevationIn:0,riserCount:4,treadRunIn:24,stockWidthIn:48,stockDepthIn:24,stockThicknessIn:6,baseDepthIn:6,settingBedIn:1,jointIn:.125,productName:'Entered custom planning stock'}};
const fullSupport={kind:'full-step' as const,courses:[0,1,2,3]};
const supportedFlight:YardFeature={...legacyFlight,stoneSteps:{...legacyFlight.stoneSteps!,support:fullSupport}};
const make=(flight:YardFeature,elevationIn=0):DeckData=>({...structuredClone(DEFAULT_DECK),houseVisible:false,stairFlights:0,railingType:'None',yardFeatures:[flight],terrainConfig:{widthFt:250,depthFt:250,elevationIn,slopePct:0}});
const design=make(supportedFlight);await ensureLiveDesignExtensions(design);
const model=buildYardModel(design),flight=model.features[0],q=flight.quantities;
ok(!flight.excluded,'Supported flight stays renderable');
equal(q.stoneStepPieces,8,'Visible tread supply remains eight units');
equal(q.stoneStepCuts,4,'Visible treads keep their width cuts');
equal(q.stoneSupportStepPieces,12,'Four-row two-wide flight needs twelve full-step supporting units');
equal(q.stoneSupportStepCuts,6,'Supporting rows record their six last-slot width cuts');
equal(q.stoneFillerPieces,0,'Full-step assembly does not order filler blocks');
near(q.stoneSupportVolumeYd3,6*(96-.125)*24*6/46656,'Support volume uses installed stock solids excluding joints');
near(q.baseYd3,64*6/324,'Base remains continuous beneath stock joints');
near(q.beddingYd3,64/324,'Setting bed covers the complete column bearing footprint');
near(q.raisedFillYd3,0,'Full support columns replace the former raised fill');
near(model.quantities.sharedExcavationYd3,64*7/324,'All supporting columns bear at zero with formation seven inches below grade');
const treads=flight.boxes.filter(b=>b.role==='stone-step'&&b.stonePart==='tread'),supports=flight.boxes.filter(b=>b.role==='stone-step'&&b.stonePart==='support-step');
equal(treads.length,8,'Physical tread solids are separately identified');
equal(supports.length,12,'Physical full-step supports are rendered');
ok([...treads,...supports].every(b=>b.h===6),'Stock thickness is rigid for both kinds of unit');
ok(supports.every(b=>[...treads,...supports].some(other=>other!==b&&JSON.stringify(other.polygon)===JSON.stringify(b.polygon)&&Math.abs((other.y-other.h/2)-(b.y+b.h/2))<1e-8)),'Every solid support has full aligned contact with a tread or higher support');
const supportSchedule=flight.stockSchedule?.filter(s=>s.assemblyPart==='support-step')??[];
equal(supportSchedule.reduce((n,s)=>n+s.pieces,0),12,'Stock schedule distinguishes supporting full-size units');

const legacy=buildYardModel(make(legacyFlight));
equal(legacy.features[0].quantities.stoneStepPieces,8,'Legacy treads are unchanged');
near(legacy.quantities.sharedExcavationYd3,16*8/324,'Absent support retains legacy stepped excavation');
near(legacy.features[0].quantities.raisedFillYd3,16*16/324,'Absent support retains legacy aggregate-supported fill');
ok(!legacy.features[0].boxes.some(b=>b.stonePart==='support-step'||b.stonePart==='filler'),'Existing projects do not silently gain supports');
const rotated=buildYardModel(make({...supportedFlight,rotationDeg:37}));
near(rotated.quantities.sharedExcavationYd3,model.quantities.sharedExcavationYd3,'Rotation preserves excavation volume on flat ground');
near(rotated.features[0].quantities.stoneSupportVolumeYd3,q.stoneSupportVolumeYd3,'Rotation preserves stock volume');
const surveyed:DeckData={...make(supportedFlight),siteModel:{version:1,points:[{id:'a',xIn:0,zIn:0,elevationIn:-21.6},{id:'b',xIn:1440,zIn:0,elevationIn:-7.2},{id:'c',xIn:1440,zIn:1440,elevationIn:21.6},{id:'d',xIn:0,zIn:1440,elevationIn:7.2}],boundary:[{x:0,y:0},{x:1440,y:0},{x:1440,y:1440},{x:0,y:1440}],grading:[]}};
await ensureLiveDesignExtensions(surveyed);const compound=buildYardModel(surveyed);
near(compound.quantities.sharedExcavationYd3,64*7/324,'Compound triangulated slopes integrate to their centre elevation analytically');
ok(compound.features.every(f=>!f.excluded),'Surveyed support formation has complete coverage');
const raisedGround=buildYardModel(make(supportedFlight,2));
near(raisedGround.features[0].topIn,24,'Ground changes preserve the fixed upper tread');
near(raisedGround.quantities.sharedExcavationYd3,64*9/324,'Ground changes update the complete foundation excavation');
equal(raisedGround.features[0].boxes.filter(b=>b.role==='stone-step').map(b=>b.y),flight.boxes.filter(b=>b.role==='stone-step').map(b=>b.y),'Ground changes preserve every stock elevation');
const lowGround=buildYardModel(make(supportedFlight,-10));
near(lowGround.features[0].quantities.raisedFillYd3,64*3/324,'Remaining support fill is measured below the complete column formation');
near(lowGround.quantities.sharedExcavationYd3,0,'Low ground does not invent negative excavation');
const custom=buildYardModel(make({...supportedFlight,stoneSteps:{...supportedFlight.stoneSteps!,support:{kind:'full-step',courses:[0,0,1,2]}}}));
equal(custom.features[0].quantities.stoneSupportStepPieces,6,'Explicit custom courses control stock ordering');
near(custom.quantities.sharedExcavationYd3,16*10/324,'Custom courses derive each foundation level separately');

const fillerSupport={kind:'filler' as const,courses:[0,2,4,6],stockWidthIn:24,stockDepthIn:12,stockThicknessIn:3,jointIn:.125,productName:'Entered rectangular planning filler',sourceURL:'https://example.com/filler-specification'};
const fillerFlight={...legacyFlight,stoneSteps:{...legacyFlight.stoneSteps!,support:fillerSupport}};
const filler=buildYardModel(make(fillerFlight)),fq=filler.features[0].quantities;
equal(fq.stoneStepPieces,8,'Filler support preserves the tread quantity');
equal(fq.stoneSupportStepPieces,0,'Fillers do not count as full-size step supports');
equal(fq.stoneFillerPieces,96,'Twelve filler courses use eight tiles per course');
equal(fq.stoneFillerCuts,60,'Rear and final-width tiles retain their stock cuts');
near(fq.stoneSupportVolumeYd3,12*(96-3*.125)*(24-.125)*3/46656,'Filler volume excludes the recorded tile joints');
near(filler.quantities.sharedExcavationYd3,64*7/324,'Two half-height filler courses replace one full-step course');
ok(filler.features[0].boxes.filter(b=>b.stonePart==='filler').every(b=>b.h===3),'Filler height remains the entered stock thickness');
ok(fq.unsupportedBearingAreaSqft>0&&filler.warnings.some(w=>w.includes('bearing lies over filler joints or gaps')),'Filler joint bearing gaps remain measured and visibly unresolved');

for(const support of [{kind:'full-step',courses:[0,1,2]},{kind:'full-step',courses:[0,1,2,2.5]},{kind:'full-step',courses:[0,1,2,21]},{kind:'full-step',courses:[0,1,2,3],price:100},{...fillerSupport,productName:''},{...fillerSupport,sourceURL:'http://example.com/specification'}])invalid(()=>validateYardFinishedSettings({...legacyFlight,stoneSteps:{...legacyFlight.stoneSteps!,support}} as YardFeature),'Invalid support inputs remain unresolved');
let getterInvoked=false;const accessorSupport=Object.defineProperty({kind:'full-step'},'courses',{enumerable:true,get(){getterInvoked=true;return [0,1,2,3];}});
invalid(()=>validateYardFinishedSettings({...legacyFlight,stoneSteps:{...legacyFlight.stoneSteps!,support:accessorSupport}} as YardFeature),'Support getters are rejected');
ok(!getterInvoked,'Support validation never invokes an accessor');
const decoratedCourses=[0,1,2,3] as number[]&{price?:number};decoratedCourses.price=100;
invalid(()=>validateYardFinishedSettings({...legacyFlight,stoneSteps:{...legacyFlight.stoneSteps!,support:{kind:'full-step',courses:decoratedCourses}}} as YardFeature),'Decorated course arrays are rejected');
const collision={...supportedFlight,depthFt:10,stoneSteps:{...supportedFlight.stoneSteps!,stockDepthIn:48}};
invalid(()=>validateYardFinishedSettings(collision),'Support columns crossing a lower tread cannot silently overlap');

equal(parseDesign(serializeDesign(validateDesign(design))).yardFeatures![0].stoneSteps,supportedFlight.stoneSteps,'Design JSON round-trips support settings');
equal((await importProjectBundle(await exportProjectBundle(design))).yardFeatures![0].stoneSteps,supportedFlight.stoneSteps,'Portable project retains support settings');
const link=await encodeDesignLink({...design,customerName:'Private support customer'},'http://127.0.0.1:4326');
const linked=await decodeDesignLink(new URL(link).hash.slice(3));
equal(linked.yardFeatures![0].stoneSteps,supportedFlight.stoneSteps,'Public links retain support settings');
ok(linked.customerName!=='Private support customer','Support links keep customer details private');
await saveStoredProject('current',serializeDesign(design));
equal(parseDesign((await readProjectValue<{json:string}>('projects','current'))!.json).yardFeatures![0].stoneSteps,supportedFlight.stoneSteps,'IndexedDB project text retains support settings');
const takeoff=buildYardTakeoff(design,model);
ok(takeoff.sections.some(s=>s.quantity===12&&s.unit==='units'&&/support/i.test(s.label)),'Supporting step supply has a distinct scope');
ok(takeoff.sections.filter(s=>/support.*supply/i.test(s.label)).every(s=>s.amountCents===null),'Unpriced supporting stock stays pending');
ok(!takeoff.materials.some(s=>s.installedAreaSqft>0),'Solid supports do not add a paver supply charge');

let state:DeckAgentHostState={data:validateDesign(make(legacyFlight)),view:'3d',openSections:[],canUndo:false,canRedo:false,ready:true},history=emptyHistory<DeckData>(),commits=0;
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{history=recordChange(history,state.data,'support',++commits);state={...state,data:next,canUndo:true,canRedo:false};},undo:()=>{const result=undoChange(history,state.data)!;history=result.history;state={...state,data:result.design,canUndo:false,canRedo:true};},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:()=>Promise.resolve(),actions:{}});
const original=JSON.stringify(state.data),snapshot=api.read(),revision=snapshot.revision;
const plan=parseAssistantPlan({kind:'edit',message:'Preview stacked full-size supports beneath these stairs.',assumptions:[],commands:[{type:'yard.stoneSupport',id:legacyFlight.id,support:fullSupport}]});
ok(plan.ok,'Assistant accepts the targeted stone-support command');
if('error'in plan)throw Error(plan.error);
const request=assistantPlanRequest(plan.plan,{id:'stone-support-preview',expectedRevision:revision,snapshot,selection:{partIds:[],boards:[],yard:{id:legacyFlight.id,target:'area',index:0}},requestText:'Add full-size support steps beneath the selected stairs'});
const preview=await api.preview(request);
ok(preview.ok&&preview.changed,`Preview includes the support change${'error'in preview?`: ${preview.error.message}`:''}`);
equal(commits,0,'Preview never commits');equal(JSON.stringify(state.data),original,'Preview preserves the host data');
if(preview.ok){equal(preview.snapshot.yardQuantities.stoneSupportStepPieces,12,'Preview reports added supporting stock');ok(preview.snapshot.yardQuantities.sharedExcavationYd3>snapshot.yardQuantities.sharedExcavationYd3,'Preview shows the excavation increase');}
const applied=await api.execute({...request,id:'stone-support-apply'});ok(applied.ok,'Support apply succeeds');equal(commits,1,'Support apply commits once');
equal(state.data.yardFeatures![0].stoneSteps!.support,fullSupport,'Applied support record is authoritative');
ok(!(await api.execute({...request,id:'stone-support-stale'})).ok,'Stale support apply is rejected');
ok((await api.execute({id:'stone-support-undo',expectedRevision:api.read().revision,commands:[{type:'history.undo'}]})).ok,'Support change is undoable');
equal(JSON.stringify(state.data),original,'One undo restores all previous fields');
state={...state,data:validateDesign(design)};api.notify();
const supportedSnapshot=api.read(),context=buildAssistantContext(supportedSnapshot,{partIds:[],boards:[],yard:{id:legacyFlight.id,target:'area',index:0}});
equal((context.design.yardFeatures as {stoneSteps:{support:unknown}}[])[0].stoneSteps.support,fullSupport,'Assistant receives the current support input');
const contextual=assistantPlanSchemaForContext(context);
ok(contextual.anyOf![0].properties!.commands.items!.anyOf!.some(s=>s.properties!.type.const==='yard.stoneSupport'&&s.properties!.id.const===legacyFlight.id),'Assistant support targets are restricted to visible stone flights');
const removed=await api.preview({id:'stone-support-remove',expectedRevision:api.read().revision,commands:[{type:'yard.stoneSupport',id:legacyFlight.id,support:null}]});
ok(removed.ok,'Removing optional supports has an explicit preview');
if(removed.ok)ok(!removed.snapshot.design.yardFeatures![0].stoneSteps!.support,'Removal preview returns to the legacy assembly');
const badPlan=parseAssistantPlan({kind:'edit',message:'Invalid support input',assumptions:[],commands:[{type:'yard.stoneSupport',id:legacyFlight.id,support:{...fullSupport,price:100}}]});
ok(!badPlan.ok,'Assistant rejects unsupported/private support fields');
state={...state,data:{...state.data,editorOrganization:{layers:[{id:'design',name:'Design',visible:true,locked:false}],groups:[],objects:[{id:legacyFlight.id,layerId:'design',locked:true}]}}};api.notify();
ok(!(await api.preview({id:'stone-support-locked',expectedRevision:api.read().revision,commands:[{type:'yard.stoneSupport',id:legacyFlight.id,support:null}]})).ok,'Locks protect support changes through voice/controller');
api.dispose();closeProjectStorage();
console.log(`STONE STEP SUPPORTS OK — ${checks} stock, contact, analytic earthwork, legacy, validation, persistence, assistant and atomic edit checks.`);
