import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {interpretAssistantRequest,checkAssistantAvailability} from '../src/features/deckcraft/designer/deckAssistantClient';
import type {DeckData} from '../src/features/deckcraft/types';
let count=0;const check=(v:unknown,message:string)=>{assert.ok(v,message);count++;};
let data:DeckData={...structuredClone(DEFAULT_DECK),customerName:'Private client',projectAddress:'Private address',scopeOfWork:'Private scope',materialMarkup:47};const history:DeckData[]=[];
const state=()=>({data,estimate:calculateDeckReleaseEstimate(data),view:'plan',openSections:['deck'],canUndo:history.length>0,canRedo:false,ready:true} as DeckAgentHostState);
const controller=createDeckAgentController({getState:state,commitDesign:next=>{history.push(data);data=next;},undo:()=>{data=history.pop()!;},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async test=>{assert.ok(test(state()));}});
const originalFetch=globalThis.fetch,selection={partIds:[],boards:[]};let calls=0,payload:any;
const modelPlan={kind:'edit',message:'Make the deck slightly wider.',assumptions:['A little wider means two additional feet.'],commands:[{type:'design.patch',patch:{width:18}}]};
const respond=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
try{
 globalThis.fetch=async(_url,init)=>{calls++;payload=init?.body?JSON.parse(String(init.body)):null;return respond(init?.method==='GET'?{ready:true,source:'local-ai',model:'local-model'}:{ok:true,source:'local-ai',model:'local-model',plan:modelPlan});};
 const availability=await checkAssistantAvailability();check(availability.ready&&availability.source==='local-ai','Readiness reflects configured local model');
 let snapshot=controller.read();const before=JSON.stringify(data),callCount=calls;
 const exact=await interpretAssistantRequest('Make the deck 20 by 14 feet',snapshot,selection);check(exact.kind==='edit'&&exact.source==='exact','Measured instructions keep a labeled fast path');check(calls===callCount,'Exact instructions work without a model call');check(JSON.stringify(data)===before,'Interpretation does not write');
 const vague=await interpretAssistantRequest('Give the deck a little more width',snapshot,selection);check(vague.kind==='edit'&&vague.source==='local-ai','Vague request uses actual AI endpoint contract');check(payload.prompt==='Give the deck a little more width'&&payload.context.revision===snapshot.revision,'Current context and revision sent');
 const publicPayload=JSON.stringify(payload.context);for(const secret of ['Private client','Private address','Private scope','materialMarkup','customOverrides','customLaborCost','pricing'])check(!publicPayload.includes(secret),`${secret} excluded from model context`);
 assert.equal(vague.kind,'edit');if(vague.kind==='edit'){
  check(vague.assumptions.length===1&&vague.request.expectedRevision===snapshot.revision,'Assumptions and exact revision retained');const preview=await controller.preview(vague.request);check(preview.ok&&JSON.stringify(data)===before,'AI commands preview through actual controller without writes');const applied=await controller.execute(vague.request);check(applied.ok&&data.width===18,'Validated model command actually changes deck');if(preview.ok&&applied.ok)check(preview.snapshot.pricing.total===applied.snapshot.pricing.total,'Reviewed price exactly equals applied price');check(history.length===1&&data.customerName==='Private client'&&data.materialMarkup===47,'One history entry preserves private pricing and client fields');check(!(await controller.execute({...vague.request,id:'stale-assistant'})).ok,'Changed design rejects stale AI proposal');await controller.execute({id:'undo-assistant',commands:[{type:'history.undo'}]});check(JSON.stringify(data)===before,'Undo restores all geometry and private prices');
 }
 globalThis.fetch=async(_url,init)=>{payload=JSON.parse(String(init?.body));return respond({ok:true,source:'local-ai',model:'local-model',plan:{kind:'clarify',message:'Several areas could be changed.',assumptions:[],commands:[],question:'Which area should be wider?',choices:['Main deck','Landing']}});};
 snapshot=controller.read();const clarification=await interpretAssistantRequest('Make this wider',snapshot,selection,[{role:'user',content:'Change a section'},{role:'assistant',content:'Which section?'}]);check(clarification.kind==='clarify'&&clarification.choices.length===2,'Unclear target returns a question and choices');check(payload.conversation.length===2&&JSON.stringify(data)===before,'Clarification thread retained without applying');
 for(const commands of [[{type:'action',name:'submit'}],[{type:'design.patch',patch:{materialMarkup:1}}],[{type:'history.undo'}],[{type:'design.replace',design:{width:99}}]]){
  globalThis.fetch=async()=>respond({ok:true,source:'local-ai',plan:{...modelPlan,commands}});await assert.rejects(interpretAssistantRequest('Please change the deck',snapshot,selection));count++;check(JSON.stringify(data)===before,'Unsupported model plan never mutates design');
 }
 data={...data,underDeck:{drainage:'none',ceiling:'pvc',scope:'all',gravel:true,gravelDepthIn:4,floorMesh:true}};controller.notify();snapshot=controller.read();const nestedBefore=JSON.stringify(data);
 globalThis.fetch=async()=>respond({ok:true,source:'local-ai',model:'local-model',plan:{...modelPlan,message:'Add RainEscape while preserving other options.',commands:[{type:'design.patch',patch:{underDeck:{drainage:'rainescape'}}}]}});
 const drainage=await interpretAssistantRequest('Add Trex RainEscape under the deck and retain the rest',snapshot,selection);check(drainage.kind==='edit','Partial nested model plan compiled through real client');if(drainage.kind==='edit'){const p=await controller.preview(drainage.request);check(p.ok,'Preservation-compiled nested plan passes real controller preview');if(p.ok){check(p.snapshot.design.underDeck?.drainage==='rainescape','Actual drainage changed');for(const key of ['ceiling','scope','gravel','gravelDepthIn','floorMesh'] as const)check(p.snapshot.design.underDeck?.[key]===snapshot.design.underDeck?.[key],`Client compiler preserves underDeck.${key}`);}check(JSON.stringify(data)===nestedBefore,'Client nested compilation/preview does not write');const a=await controller.execute(drainage.request);check(a.ok,'Nested plan applies');if(a.ok&&p.ok)check(a.snapshot.pricing.total===p.snapshot.pricing.total,'Nested preview/apply total exact');await controller.execute({id:'undo-nested-client',commands:[{type:'history.undo'}]});check(JSON.stringify(data)===nestedBefore,'Nested edit Undo restores every unrelated option');}
 data={...data,height:72};controller.notify();snapshot=controller.read();const post=snapshot.parts.find(p=>p.kind==='post')!,postSelection={partIds:[post.id],boards:[]},structureBefore=JSON.stringify(data);
 globalThis.fetch=async()=>respond({ok:true,source:'local-ai',model:'local-model',plan:{...modelPlan,commands:[{type:'boundary.move',level:1,target:'point',index:0,dxIn:-24,dyIn:0}]}});await assert.rejects(interpretAssistantRequest('Move this selected support post two feet left',snapshot,postSelection),/Individual generated/);count++;check(JSON.stringify(data)===structureBefore,'Invented structural workaround leaves all real geometry unchanged');
 globalThis.fetch=async()=>respond({ok:true,source:'local-ai',model:'local-model',plan:modelPlan});const unrelated=await interpretAssistantRequest('Give the main deck a little more width',snapshot,postSelection);check(unrelated.kind==='edit','Selected post does not block unrelated explicit main width request');
 globalThis.fetch=async()=>respond({ok:true,source:'local-ai',plan:{...modelPlan,commands:[{type:'design.patch',patch:{quoteResolutions:[{id:'secret',price:1}]}}]}});await assert.rejects(interpretAssistantRequest('Please update the quote settings',snapshot,selection),/not valid/);count++;check(JSON.stringify(data)===structureBefore,'New private quote resolutions are rejected from model edits');
 globalThis.fetch=async()=>respond({ok:false,error:{message:'Local model is unavailable.'}},503);check(!(await checkAssistantAvailability()).ready,'Unavailable model is reported truthfully');await assert.rejects(interpretAssistantRequest('Make it more open',snapshot,selection),/unavailable/);count++;
 globalThis.fetch=async()=>new Response('not JSON');await assert.rejects(interpretAssistantRequest('Make it more open',snapshot,selection),/not connected/);count++;
 globalThis.fetch=async()=>respond({ok:true,source:'local-ai',plan:modelPlan,padding:'x'.repeat(65537)});await assert.rejects(interpretAssistantRequest('Make it more open',snapshot,selection),/oversized/);count++;
 globalThis.fetch=async(_url,init)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(init.signal!.reason),{once:true}));const abort=new AbortController(),pending=interpretAssistantRequest('Make it more open',snapshot,selection,[],abort.signal);abort.abort(new DOMException('Closed','AbortError'));await assert.rejects(pending,/Closed/);count++;
 await assert.rejects(interpretAssistantRequest('Make it more open',{...snapshot,ready:false},selection),/restoring/);count++;await assert.rejects(interpretAssistantRequest('x'.repeat(1201),snapshot,selection),/1,200/);count++;
}finally{globalThis.fetch=originalFetch;controller.dispose();}
console.log(`Deck assistant client: ${count} checks passed.`);
