import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {createQuoteAwarePricingReceiver} from '../src/features/deckcraft/designer/quoteAwarePricingReceiver';
import type {PricingRequest} from '../src/features/deckcraft/designer/optionPricing';
const data={...structuredClone(DEFAULT_DECK),quoteResolutions:[{scopeKey:'quote-0000000000000000',fingerprint:'scope-0000000000000000',supplyCost:100,installationCost:200,confirmedOn:'2026-09-26',source:'Synthetic',note:'Synthetic additional costs',additionalScope:true as const}]};
let count=0;const check=(v:unknown,s:string)=>{assert(v,s);count++;};
check(calculateDeckReleaseEstimate(DEFAULT_DECK).total>0,'Public pricing works without loading optional private quote costing');
assert.throws(()=>calculateDeckReleaseEstimate(data),/Load the private quote-cost review/);count++;
const job=(id:number):Extract<PricingRequest,{job:number}>=>({job:id,data,items:[{key:`option-${id}`,patch:{width:18}}]});
const received:PricingRequest[]=[],failed:number[]=[];let release!:()=>void,loads=0;
const receive=createQuoteAwarePricingReceiver(r=>received.push(r),()=>{loads++;return new Promise<void>(resolve=>release=resolve);},j=>failed.push(j.job));
receive({...job(0),data:DEFAULT_DECK});check(loads===0&&received.length===1,'Public option pricing does not fetch private extension');
receive(job(1));receive(job(2));check(loads===1&&received.length===1,'Concurrent private options share one bounded extension load');
receive({cancel:1});release();await Promise.resolve();await Promise.resolve();
check(received.some(r=>'job'in r&&r.job===2)&&!received.some(r=>'job'in r&&r.job===1),'A cancelled private job cannot resume when extension finishes');
receive(job(3));check(received.some(r=>'job'in r&&r.job===3),'Later private options use ready extension immediately');
let reject!:()=>void;const errors=createQuoteAwarePricingReceiver(r=>received.push(r),()=>new Promise<void>((_,no)=>reject=()=>no(Error('Unavailable'))),j=>failed.push(j.job));
errors(job(4));reject();await Promise.resolve();await Promise.resolve();check(failed.join()==='4'&&!received.some(r=>'job'in r&&r.job===4),'Missing extension returns unavailable figures rather than pricing missing costs at zero');
let open!:()=>void;const supersede=createQuoteAwarePricingReceiver(r=>received.push(r),()=>new Promise<void>(resolve=>open=resolve),j=>failed.push(j.job));
const old=job(5),latest={...job(5),items:[{key:'latest-option',patch:{length:16}}]};supersede(old);supersede(latest);open();await Promise.resolve();await Promise.resolve();check(received.includes(latest)&&!received.includes(old),'A replacement job supersedes its stale pending request');
await import('../src/features/deckcraft/quoteResolutions');check(calculateDeckReleaseEstimate(data).total===calculateDeckReleaseEstimate(DEFAULT_DECK).total,'Loaded extension never activates unbound synthetic costs');
console.log(`${count} quote-loader and cancellation checks passed`);
