import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {HARDSCAPE_PRODUCTS,hardscapeBody,hardscapeProblem,hardscapeSelection,rectangularUnit} from '../src/features/deckcraft/hardscapeCatalogue';
import {hardscapeBlanks} from '../src/features/deckcraft/hardscapeLayout';
import {buildYardModel,yardArea,yardClip,yardSolidCells,projectedYardPavers} from '../src/features/deckcraft/yardModel';
import {buildYardTakeoff} from '../src/features/deckcraft/yardTakeoff';
import {yardShapeEdit,yardShapePull,yardShapeResize,yardShapeWorldPoints} from '../src/features/deckcraft/yardShapeEditing';
import {validateDesign,serializeDesign,parseDesign} from '../src/features/deckcraft/designPersistence';
import {buildQuoteScopes} from '../src/features/deckcraft/quoteResolutions';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {yardPreviewBoxes,hasSimplifiedPaving} from '../src/features/deckcraft/components/viewer3d/yardPreview';
import {parseAssistantPlan} from '../src/features/deckcraft/designer/assistantPlan';

let checks=0,variants=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},eq=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);checks++;},near=(a:number,b:number,m:string)=>ok(Math.abs(a-b)<1e-5,`${m}: ${a} vs ${b} (difference ${a-b})`);
const base:YardFeature={id:'patio-catalogue',kind:'patio',name:'Courtyard',enabled:true,xFt:60,zFt:60,widthFt:6,depthFt:4,heightIn:3,rotationDeg:0,productId:'permacon-melville',color:'#aaa69b'};
const data=(f:YardFeature[]):DeckData=>({...structuredClone(DEFAULT_DECK),houseVisible:false,deckType:'Freestanding',municipality:'Barrie',soilCondition:'Sandy',siteType:'Standard',yardFeatures:f,terrainConfig:{widthFt:250,depthFt:250,elevationIn:0,slopePct:0}});
const publicLibrary=JSON.parse(readFileSync(new URL('../public/deckcraft/hardscape-catalogue.json',import.meta.url),'utf8'));
eq(new Set(publicLibrary.products.map((p:any)=>p.id)),new Set(HARDSCAPE_PRODUCTS.map(p=>p.id)),'Picker and engineering inventory are identical');
ok(['Techo-Bloc','Unilock','Permacon','Oaks'].every(brand=>HARDSCAPE_PRODUCTS.some(p=>p.brand===brand)),'All four Ontario suppliers are present');
eq(new Set(HARDSCAPE_PRODUCTS.map(p=>p.id)).size,HARDSCAPE_PRODUCTS.length,'Catalogue IDs are unique');
for(const p of HARDSCAPE_PRODUCTS)for(const f of p.finishes){eq(new Set(f.units.map(u=>u.id)).size,f.units.length,`${p.id} ${f.id}: unit IDs unique`);eq(new Set(f.colors.map(c=>c.id)).size,f.colors.length,`${p.id} ${f.id}: colour IDs unique`);for(const color of f.colors)if(color.imageUrl)ok(existsSync(new URL('../public'+color.imageUrl,import.meta.url)),`${p.id}: supplier swatch exists locally`);
 const source=publicLibrary.products.find((product:any)=>product.id===p.id).finishes.find((finish:any)=>finish.id===f.id);
 const physicalPatterns=(patterns:any[])=>patterns.filter(pattern=>pattern.layout?.cells?.length).map(pattern=>[pattern.id,pattern.name,pattern.sourceUrl,pattern.layout.widthMm,pattern.layout.depthMm,pattern.layout.jointMm??0,pattern.layout.angleDeg??0,pattern.layout.repeatBasisMm??null,pattern.layout.cells]);
 eq(physicalPatterns(f.patterns),physicalPatterns(source.patterns),`${p.id} ${f.id}: compact stock indices decode to the source's exact cells, joints and repeat basis`);
 eq(f.units.map(unit=>[unit.id,unit.widthMm,unit.lengthMm,unit.heightMm,unit.colorIds??null]),source.units.filter((unit:any)=>[unit.widthMm,unit.lengthMm,unit.heightMm].every(n=>typeof n==='number'&&n>0)).map((unit:any)=>[unit.id,unit.widthMm,unit.lengthMm,unit.heightMm,unit.colorIds??null]),`${p.id} ${f.id}: engineering stock dimensions and allowed colours match the source library`);
 for(const unit of f.units.filter(u=>hardscapeBody(u.role))){const color=f.colors.find(c=>!unit.colorIds||unit.colorIds.includes(c.id));if(!color)continue;
  const feature:YardFeature={...base,id:`test-${variants++}`,kind:p.category==='wall'?'retaining-wall':'patio',productId:p.id,...(p.category==='wall'?{depthFt:unit.lengthMm/304.8,heightIn:24}:{}),hardscape:{finishId:f.id,colorId:color.id,unitId:unit.id,patternId:'running-bond',angleDeg:0,jointMm:p.category==='wall'?0:3}};
  if(feature.depthFt<1/12||feature.depthFt>8&&p.category==='wall')continue;
  eq(hardscapeProblem(feature),'',`${p.id} ${unit.id}: documented variant accepted`);eq(parseDesign(serializeDesign(data([feature]))).yardFeatures,[feature],`${p.id}: saved variant survives exact round trip`);
  const model=buildYardModel(data([feature]));ok(!model.features[0].excluded,`${p.id}: stock creates geometry`);ok(model.boxes.every(b=>[b.x,b.y,b.z,b.w,b.h,b.d].every(Number.isFinite)&&b.w>0&&b.h>0&&b.d>0),`${p.id}: finite positive geometry`);
  if(feature.kind==='patio'){near(model.features[0].quantities.paverAreaSqft,24,'Patio area follows its perimeter');near(model.boxes.find(b=>b.role==='paver')!.h,unit.heightMm/25.4,'Supplier thickness is converted exactly');ok(projectedYardPavers(feature)>=model.quantities.paverPieces,'Budget counts conservatively before clipping');}
  else{near(model.quantities.wallLengthLf,6,'Straight wall measured centreline');ok(model.quantities.wallBlocks>0,'Supplier wall course quantity exists');eq(model.quantities.wallCaps,0,'No generic cap substituted for a selected wall system');}
  const quote=buildYardTakeoff(data([feature]),model);ok(quote.quoteRequired&&quote.subtotalCents===null,'A supplier product never inherits an unrelated price');ok(quote.sections.some(s=>s.amountCents===null&&s.featureIds?.includes(feature.id)),'Outstanding assembly remains visible');
 }
}
const p=HARDSCAPE_PRODUCTS.find(p=>p.category!=='wall'&&p.finishes.some(f=>f.units.some(u=>rectangularUnit(u)&&hardscapeBody(u.role)&&u.widthMm!==u.lengthMm)))!,f=p.finishes.find(f=>f.units.some(u=>rectangularUnit(u)&&hardscapeBody(u.role)&&u.widthMm!==u.lengthMm))!,unit=f.units.find(u=>rectangularUnit(u)&&hardscapeBody(u.role)&&u.widthMm!==u.lengthMm)!,color=f.colors.find(c=>!unit.colorIds||unit.colorIds.includes(c.id))!;
// Stock clipping and the comparison union each round coordinates at 1e-5 inch.
// Bound area drift by total edge length times the two-pass maximum vertex displacement,
// in square feet. This scales with actual geometry rather than assuming equal-sized fragments.
const rotatedClipAreaTolerance=(polys:{x:number;y:number}[][])=>Math.max(1e-4,polys.reduce((n,p)=>n+p.reduce((m,a,i)=>{const b=p[(i+1)%p.length];return m+Math.hypot(b.x-a.x,b.y-a.y);},0),0)*Math.SQRT2*1e-5/144);
let recipes=0;for(const product of HARDSCAPE_PRODUCTS)for(const finish of product.finishes)for(const recipe of finish.patterns){const unit=finish.units.find(u=>u.id===recipe.layout.cells[0].unitId)!,color=finish.colors.find(c=>recipe.layout.cells.every(cell=>{const u=finish.units.find(u=>u.id===cell.unitId)!;return !u.colorIds||u.colorIds.includes(c.id);}))!;if(!color)continue;for(const angleDeg of [0,37,90]){const feature:YardFeature={...base,widthFt:20,depthFt:20,productId:product.id,hardscape:{finishId:finish.id,colorId:color.id,unitId:unit.id,patternId:recipe.id,angleDeg,jointMm:recipe.layout.jointMm??0}};eq(hardscapeProblem(feature),'','Source recipe resolves exact unit bindings');const model=buildYardModel(data([feature])),stones=model.boxes.filter(b=>b.role==='paver');ok(stones.length>0,'Documented source pattern produces stock');ok(Math.abs(yardArea(yardClip(stones.map(b=>b.polygon!)))-yardArea(stones.map(b=>b.polygon!)))<rotatedClipAreaTolerance(stones.map(b=>b.polygon!)),`${product.id} ${recipe.id} ${angleDeg}: delta ${yardArea(yardClip(stones.map(b=>b.polygon!)))-yardArea(stones.map(b=>b.polygon!))}, pieces ${stones.length}: repeat overlap stays below the per-fragment Clipper rotation/quantization bound`);eq(model.features[0].stockSchedule!.reduce((n,u)=>n+u.pieces,0),model.quantities.paverPieces,'Stock schedule sums to physical pieces, not fragment count');near(model.features[0].stockSchedule!.reduce((n,u)=>n+u.pieces*u.widthMm*u.lengthMm/(304.8*304.8),0),model.features[0].quantities.paverStockAreaSqft,'Mixed-unit order area uses every real stock size');near(buildYardTakeoff(data([feature]),model).materials[0].orderAreaSqft,model.features[0].quantities.paverStockAreaSqft,'Public quote preserves full-stock mixed-size order area');eq(parseDesign(serializeDesign(data([feature]))).yardFeatures,[feature],'Named supplier pattern survives exact persistence');}recipes++;}ok(recipes>0,'Digitized manufacturer recipes are available');
const selected:YardFeature={...base,productId:p.id,hardscape:{finishId:f.id,colorId:color.id,unitId:unit.id,patternId:'running-bond',angleDeg:0,jointMm:3}};
for(const patternId of ['running-bond','stack-bond','herringbone'])for(const angleDeg of [0,17,45,90,213]){const feature={...selected,hardscape:{...selected.hardscape!,patternId,angleDeg}},blanks=hardscapeBlanks(feature),model=buildYardModel(data([feature])),stones=model.boxes.filter(b=>b.role==='paver');ok(stones.length>0,`${patternId} ${angleDeg}: visible stock pieces`);near(yardArea(yardClip(stones.map(b=>b.polygon!))),yardArea(stones.map(b=>b.polygon!)),`${patternId}: stones do not overlap`);const rotations=new Set(blanks.map(b=>Number((b.angle*180/Math.PI).toFixed(3))));eq(rotations.size,patternId==='herringbone'?2:1,'Pattern orientation remains physical');near(blanks[0].length,unit.lengthMm/25.4,'Stock length is not shrunk to create joints');near(blanks[0].width,unit.widthMm/25.4,'Stock width is not shrunk to create joints');}
const concave=yardShapeEdit(selected,[{x:600,y:600},{x:720,y:600},{x:720,y:660},{x:660,y:660},{x:660,y:720},{x:600,y:720}]),concaveModel=buildYardModel(data([concave]));near(concaveModel.quantities.patioAreaSqft,75,'Concave patio measures actual shape, not its bounding box');for(const b of concaveModel.boxes.filter(b=>b.role==='paver'))near(yardArea(yardClip([b.polygon!],concaveModel.features[0].footprints,'difference')),0,'Every stock fragment stays inside the pulled patio');
const wallBase:YardFeature={...base,id:'corner-wall',kind:'retaining-wall',productId:'segmental-concrete',depthFt:1,heightIn:30},wall=yardShapeEdit(wallBase,[{x:600,y:600},{x:720,y:600},{x:720,y:720}]),wallModel=buildYardModel(data([wall]));near(wallModel.quantities.wallLengthLf,20,'L wall charges the whole path');near(wallModel.quantities.wallFaceSqft,50,'L wall face quantity uses path × height');eq(wallModel.members.filter(m=>m.role==='drain-pipe').length,2,'Drainage follows both wall legs');ok(wallModel.quantities.wallBlocks>0&&wallModel.quantities.wallCaps>0,'Legacy generic L wall retains body and cap envelopes');
for(const role of ['base','wall-drainage','backfill']){const pieces=wallModel.boxes.filter(b=>b.role===role);near(yardArea(yardClip(pieces.map(b=>b.polygon!))),yardArea(pieces.map(b=>b.polygon!)),`${role}: corner earthwork not double-counted`);}
const resized=yardShapeResize(concave,12,12),pulled=yardShapePull(concave,'point',2,12,0);eq(resized.hardscape,selected.hardscape,'Numeric shape resize preserves selected product configuration');eq(pulled.hardscape,selected.hardscape,'Point pull preserves supplier selection');eq(validateDesign(data([wall])).yardFeatures,[wall],'Open wall path survives strict persistence');
let capCases=0;for(const product of HARDSCAPE_PRODUCTS.filter(p=>p.category==='wall'))for(const finish of product.finishes){const body=finish.units.find(u=>hardscapeBody(u.role)&&finish.units.some(cap=>/(^|[- ])(cap|coping)([- ]|$)/.test(cap.role)&&cap.lengthMm>=u.lengthMm&&cap.lengthMm<=u.lengthMm+304.8&&cap.heightMm<=24*25.4));if(!body)continue;const cap=finish.units.find(cap=>/(^|[- ])(cap|coping)([- ]|$)/.test(cap.role)&&cap.lengthMm>=body.lengthMm&&cap.lengthMm<=body.lengthMm+304.8&&cap.heightMm<=24*25.4)!;const color=finish.colors.find(c=>(!body.colorIds||body.colorIds.includes(c.id))&&(!cap.colorIds||cap.colorIds.includes(c.id)));if(!color)continue;const configured:YardFeature={...wallBase,productId:product.id,depthFt:body.lengthMm/304.8,hardscape:{finishId:finish.id,colorId:color.id,unitId:body.id,patternId:'running-bond',angleDeg:0,jointMm:0,capUnitId:cap.id}};eq(hardscapeProblem(configured),'','Compatible supplier wall cap accepted');eq(parseDesign(serializeDesign(data([configured]))).yardFeatures,[configured],'Supplier wall cap survives persistence');for(const shaped of [configured,yardShapeEdit(configured,[{x:600,y:600},{x:720,y:600},{x:720,y:720}])]){const model=buildYardModel(data([shaped]));ok(model.quantities.wallCaps>0,'Selected supplier cap creates physical quantities');for(const b of model.boxes.filter(b=>b.role==='wall-cap'))near(b.h,cap.heightMm/25.4,'Selected cap stock height is exact');}capCases++;}ok(capCases>0,'Supplier cap geometry exercised across documented products');
let getterCalls=0;const unsafeVariant={...selected.hardscape};Object.defineProperty(unsafeVariant,'unitId',{enumerable:true,get:()=>{getterCalls++;return unit.id;}});assert.throws(()=>validateDesign(data([{...selected,hardscape:unsafeVariant as YardFeature['hardscape']}])));checks++;eq(getterCalls,0,'Variant validation does not invoke getters');
for(const bad of [{...selected,hardscape:{...selected.hardscape!,unitId:'invented'}},{...selected,hardscape:{...selected.hardscape!,colorId:'invented'}},{...selected,kind:'retaining-wall' as const},{...selected,hardscape:{...selected.hardscape!,patternId:'invented'}},{...selected,hardscape:{...selected.hardscape!,jointMm:NaN}}]){assert.throws(()=>validateDesign(data([bad])));checks++;ok(buildYardModel(data([bad])).features[0].excluded,'Raw invalid supplier selection is excluded on engine path');}
const supplierPreview=buildYardModel(data([selected]));supplierPreview.quantities.paverPieces=6001;ok(!hasSimplifiedPaving(supplierPreview),'Supplier layouts never become a fake generic preview above6000 pieces');eq(yardPreviewBoxes(supplierPreview),supplierPreview.boxes,'Supplier stock geometry and UVs survive the detailed-preview threshold');
const e=calculateDeckReleaseEstimate(data([selected])),scopes=buildQuoteScopes(data([selected]),e.sections,e.quoteRequired),altered=yardShapePull(selected,'point',2,12,0),changed=calculateDeckReleaseEstimate(data([altered]));ok(scopes.length>0,'Supplier quote scopes exist');ok(scopes.every(scope=>!buildQuoteScopes(data([altered]),changed.sections,changed.quoteRequired).some(next=>next.key===scope.key&&next.fingerprint===scope.fingerprint)),'Shape change invalidates previous quote fingerprints');
let state:DeckAgentHostState={data:data([selected]),ready:true,view:'plan',openSections:[],canUndo:false,canRedo:false},commits=0;const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{state={...state,data:next,canUndo:true,canRedo:false};commits++;},undo:()=>{},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:test=>{assert(test(state));return Promise.resolve();}}),before=serializeDesign(state.data),request={id:'yard-batch',expectedRevision:api.read().revision,commands:[{type:'yard.add',id:selected.id,index:0},{type:'yard.move',id:selected.id,target:'point',index:1,dxIn:0,dyIn:-12}]};
const preview=await api.preview(request);ok(preview.ok,'Agents can preview the same yard gestures');eq(serializeDesign(state.data),before,'Agent preview writes nothing');eq(commits,0,'Agent preview adds no history');const applied=await api.execute(request);ok(applied.ok,'Agent gesture batch applies');eq(commits,1,'Agent gesture batch creates one commit');eq(state.data.yardFeatures![0].hardscape,selected.hardscape,'Agent edits preserve supplier selection');ok(api.describe().catalogue.hardscape.length===HARDSCAPE_PRODUCTS.length,'Agent can inspect documented catalogue IDs and units');ok(api.read().yardBoundaries[0].coordinateSpace==='world-inches','Agent yard geometry declares its coordinate space');
ok(parseAssistantPlan({kind:'edit',message:'Pull courtyard corner.',assumptions:[],commands:[{type:'yard.move',id:selected.id,target:'point',index:0,dxIn:12,dyIn:0}]}).ok,'Natural-language plans support yard gestures');
console.log(`Landscape catalogue / geometry / costing / persistence / agent checks passed: ${checks} checks across ${HARDSCAPE_PRODUCTS.length} products and ${variants} documented unit variants.`);
