import {writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {createSiteSurface,integrateSiteExcavation,integrateSiteFeatureFill} from '../src/features/deckcraft/siteSurfaceEngine';
import {buildYardModel,yardArea,loadAdvancedYardRuntime} from '../src/features/deckcraft/yardModel';
import {patioTopPlane,planeNormalScale,tiltStockPoint,yardBoxRings,planeAt} from '../src/features/deckcraft/yardElevationGeometry';
import {yardWallStationPath} from '../src/features/deckcraft/yardPathGeometry';
import {validateYardFinishedSettings} from '../src/features/deckcraft/yardFinishedSettings';
import {HARDSCAPE_PRODUCTS,hardscapeBody,hardscapeSelection} from '../src/features/deckcraft/hardscapeCatalogue';
import {yardPreviewBoxes} from '../src/features/deckcraft/components/viewer3d/yardPreview';
import {yardFinishGeometry} from '../src/features/deckcraft/components/viewer3d/yardFinishGeometry';
import type {SiteModel} from '../src/features/deckcraft/siteModel';
const accuracy:{label:string;actual:number;expected:number;absoluteError:number;relativeErrorPct:number|null}[]=[];
let checks=0;const near=(a:number,b:number,label:string,tolerance=1e-6)=>{accuracy.push({label,actual:a,expected:b,absoluteError:Math.abs(a-b),relativeErrorPct:b?Math.abs((a-b)/b)*100:null});assert.ok(Math.abs(a-b)<=Math.max(tolerance,Math.abs(b)*.00001),`${label}: ${a} vs ${b}`);checks++;},ok=(value:unknown,label:string)=>{assert.ok(value,label);checks++;};
const rect=(x0:number,z0:number,x1:number,z1:number)=>[{x:x0,y:z0},{x:x1,y:z0},{x:x1,y:z1},{x:x0,y:z1}];
const terrain={widthFt:100,depthFt:100,elevationIn:0,slopePct:0};
const legacyCold={...DEFAULT_DECK,yardFeatures:[]},legacyColdResult=JSON.stringify(buildYardModel(legacyCold));
assert.throws(()=>buildYardModel({...DEFAULT_DECK,terrainConfig:{...terrain,slopePct:1}}),'Unprepared optional geometry must fail explicitly');checks++;
await loadAdvancedYardRuntime();
assert.equal(JSON.stringify(buildYardModel(legacyCold)),legacyColdResult,'Loading advanced geometry must not change legacy results');checks++;
const survey=(h:(x:number,z:number)=>number):SiteModel=>({version:1,points:[-600,600].flatMap(x=>[-600,600].map(z=>({id:`${x}/${z}`,xIn:x,zIn:z,elevationIn:h(x,z)}))),grading:[]});
const surface=createSiteSurface(survey(()=>20),terrain),zone=rect(-60,-60,60,60),formations=[{featureId:'a',polygons:[zone],bottomIn:0,formationPlane:{x:.1,z:0,constant:0}},{featureId:'b',polygons:[zone],bottomIn:0,formationPlane:{x:-.1,z:0,constant:0}}];
const cut=integrateSiteExcavation(surface,formations);
near(cut.excavationYd3,14400*23/46656,'Crossing construction planes choose deepest plane exactly once');
near(cut.regions.filter(r=>r.featureId==='a').reduce((n,r)=>n+r.volumeYd3,0),7200*23/46656,'First slope owns correct half');
near(cut.regions.filter(r=>r.featureId==='b').reduce((n,r)=>n+r.volumeYd3,0),7200*23/46656,'Second slope owns correct half');
near(integrateSiteExcavation(surface,[...formations].reverse()).excavationYd3,cut.excavationYd3,'Plane crossing ownership volume independent of order');
near(integrateSiteFeatureFill(createSiteSurface(survey(()=>0),terrain),[zone],{x:.1,z:0,constant:0}),7200*3/46656,'Sloped engineered fill splits zero crossing');
const lshape=rect(-60,-60,60,60),notch=rect(0,0,60,60).reverse(),concave=integrateSiteExcavation(surface,formations.map(f=>({...f,polygons:[lshape,notch]})));near(concave.excavationYd3,248400/46656,'Crossing planes integrate concave boundary and holes exactly');
const patio:YardFeature={id:'slope',kind:'patio',name:'Sloped patio',enabled:true,xFt:20,zFt:20,widthFt:12,depthFt:12,heightIn:0,finishedElevationIn:18,patioSlope:{xPct:20,zPct:15},rotationDeg:33,productId:'permacon-melville',color:'#aaa'};
const data:DeckData={...structuredClone(DEFAULT_DECK),houseVisible:false,terrainConfig:terrain,siteModel:survey(()=>0),yardFeatures:[patio]},model=buildYardModel(data),feature=model.features[0],plane=patioTopPlane(patio,0),scale=planeNormalScale(plane);
ok(!feature.excluded,'Sloped patio complete measured footprint');near(feature.topIn,18,'Absolute centre finished elevation');near(feature.quantities.surfaceAreaSqft,144*scale,'True surface area');near(feature.quantities.planAreaSqft,144,'Separate plan area');near(feature.quantities.baseYd3,feature.quantities.surfaceAreaSqft*12/324,'Normal aggregate thickness quantity');
const legacyPlane=buildYardModel({...data,siteModel:undefined});near(legacyPlane.quantities.excavationYd3,model.quantities.excavationYd3,'Sloped formation excavation agrees between legacy-plane and measured-ground engines');near(legacyPlane.quantities.raisedFillYd3,model.quantities.raisedFillYd3,'Sloped engineered fill agrees between legacy-plane and measured-ground engines');
const compound=integrateSiteExcavation(surface,formations.map((f,i)=>({...f,formationPlane:{x:i?-.1:.1,z:i?-.1:.1,constant:0}})));near(compound.excavationYd3,14400*24/46656,'Compound crossing planes integrate diagonal wedge exactly');
const moved=buildYardModel({...data,siteModel:survey(()=>8)}).features[0];near(moved.topIn,feature.topIn,'Ground edit preserves finished datum');ok(moved.quantities.raisedFillYd3<feature.quantities.raisedFillYd3,'Ground edit recomputes engineered fill');
const raisedFormation=buildYardModel({...data,siteModel:survey(()=>0),yardFeatures:[{...patio,finishedElevationIn:30,patioSlope:{xPct:0,zPct:0}}]});
ok(raisedFormation.excavationRegions.length===0,'Raised patio has no ground excavation');
ok(raisedFormation.formationRegions.some(r=>r.featureId===patio.id&&r.bottomIn>0&&r.polygon.length>=3),'Raised patio still exposes its physical formation above existing ground');
const legacy={...patio,finishedElevationIn:undefined,patioSlope:undefined};near(buildYardModel({...data,yardFeatures:[legacy],siteModel:survey(()=>8)}).features[0].topIn,8,'Legacy relative top behavior preserved');
const origin={x:240,y:240},stock=rect(230,230,250,250).map(p=>tiltStockPoint(p,plane,origin)),rings=yardBoxRings({y:0,h:2,normalThicknessIn:2,topPlane:plane},stock),length=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number})=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
for(let i=0;i<4;i++){near(length(rings.top[i],rings.top[(i+1)%4]),20,'Orthogonal stock tilt preserves face edges');near(length(rings.top[i],rings.bottom[i]),2,'Rigid stock normal thickness');near(planeAt(plane,rings.top[i].x,rings.top[i].z),rings.top[i].y,'Top vertex lies on finish plane');}
near(yardArea([stock])*scale,400/144,'Physical stock surface area preserved');
for(const box of feature.boxes.filter(b=>b.role==='base'||b.role==='bedding')){const g=yardFinishGeometry(box),p=g.getAttribute('position');let volume=0;for(let i=0;i<p.count;i+=3){const a={x:p.getX(i)-box.x,y:p.getY(i)-box.y,z:p.getZ(i)-box.z},b={x:p.getX(i+1)-box.x,y:p.getY(i+1)-box.y,z:p.getZ(i+1)-box.z},c={x:p.getX(i+2)-box.x,y:p.getY(i+2)-box.y,z:p.getZ(i+2)-box.z};volume+=(a.x*(b.y*c.z-b.z*c.y)+a.y*(b.z*c.x-b.x*c.z)+a.z*(b.x*c.y-b.y*c.x))/6;}near(Math.abs(volume)/46656,yardArea([box.polygon!])*scale*box.h/324,'Rendered physical layer volume matches stock normal thickness',1e-5);g.dispose();}
const simplified=yardPreviewBoxes({...model,quantities:{...model.quantities,paverPieces:6001}});for(const box of simplified.filter(b=>b.role==='paver')){ok(!!box.topPlane&&box.normalThicknessIn===model.boxes.find(b=>b.role==='paver')!.h,'Adaptive simplified paving retains top plane and physical stock thickness');for(const p of yardBoxRings(box,box.polygon!).top)near(p.y,planeAt(plane,p.x,p.z),'Simplified paving meets the same finished plane');}
const pp=HARDSCAPE_PRODUCTS.find(p=>p.category!=='wall'&&p.finishes.some(f=>f.units.some(u=>hardscapeBody(u.role)&&u.heightMm===60)))!,pf=pp.finishes.find(f=>f.units.some(u=>hardscapeBody(u.role)&&u.heightMm===60))!,pu=pf.units.find(u=>hardscapeBody(u.role)&&u.heightMm===60)!,pc=pf.colors.find(c=>!pu.colorIds||pu.colorIds.includes(c.id))!;
const supplierPatio={...patio,productId:pp.id,hardscape:{finishId:pf.id,colorId:pc.id,unitId:pu.id,patternId:'running-bond',angleDeg:73,jointMm:0}};const supplierModel=buildYardModel({...data,yardFeatures:[supplierPatio]}).features[0];ok(!supplierModel.excluded&&supplierModel.stockSchedule!.reduce((n,row)=>n+row.pieces,0)===supplierModel.quantities.paverPieces,'Sloped supplier stock ordering reconciles unique physical pieces');near(supplierModel.pavingZones![0].areaSqft,supplierModel.quantities.surfaceAreaSqft,'Supplier installed quote area uses true inclined area');for(const box of supplierModel.boxes.filter(b=>b.role==='paver')){near(box.normalThicknessIn!,pu.heightMm/25.4,'Supplier normal physical height preserved');near(box.stockAreaSqft!,pu.lengthMm*pu.widthMm/(25.4*25.4*144),'Supplier purchased full-stock face area preserved');}
const product=HARDSCAPE_PRODUCTS.find(p=>p.id==='techo-raffinato-wall')!,finish=product.finishes.find(f=>f.units.some(u=>hardscapeBody(u.role)))!,unit=finish.units.find(u=>hardscapeBody(u.role))!,color=finish.colors.find(c=>!unit.colorIds||unit.colorIds.includes(c.id))!,course=unit.heightMm/25.4;
const wall:YardFeature={id:'stepped',kind:'retaining-wall',name:'Stepped curved wall',enabled:true,xFt:20,zFt:20,widthFt:24,depthFt:unit.lengthMm/304.8,heightIn:36,finishedElevationIn:48,wallTopSteps:[{stationIn:150,elevationIn:48-2*course},{stationIn:300,elevationIn:48-course}],wallPath:[{x:-144,y:0},{x:144,y:0}],curves:[{edge:0,bulgeIn:100}],rotationDeg:12,productId:product.id,color:color.hex??'#aaa',hardscape:{finishId:finish.id,colorId:color.id,unitId:unit.id,patternId:'running-bond',angleDeg:0,jointMm:0}};
wall.hardscape!.capUnitId=hardscapeSelection(wall)!.caps[0].id;await ensureLiveDesignExtensions({...data,yardFeatures:[wall]});validateYardFinishedSettings(wall);
const path=yardWallStationPath(wall);ok(path.stations.some(v=>Math.abs(v-150)<1e-8)&&path.stations.some(v=>Math.abs(v-300)<1e-8),'Top steps retained at exact analytical arc stations');
const wm=buildYardModel({...data,yardFeatures:[wall]}).features[0];ok(!wm.excluded,'Curved stepped wall retained');ok(wm.quantities.wallTopTransitionPending===1&&wm.quoteRequired,'Unverified step returns visibly pending');ok(wm.boxes.filter(b=>b.role==='wall-block').every(b=>Math.abs(b.h-course)<1e-8),'Full stock courses remain physical');
const capTops=[...new Set(wm.boxes.filter(b=>b.role==='wall-cap').map(b=>Math.round((b.y+b.h/2)*1e6)/1e6))];for(const elevation of [48,48-2*course,48-course])ok(capTops.some(v=>Math.abs(v-elevation)<1e-5),'Each explicit top run has matching caps');
const raisedWall=buildYardModel({...data,siteModel:survey(()=>6),yardFeatures:[wall]}).features[0];for(const top of capTops)ok(raisedWall.boxes.some(b=>b.role==='wall-cap'&&Math.abs(b.y+b.h/2-top)<1e-5),'Changing ground preserves all stepped cap levels');
ok(raisedWall.quantities.wallBlocks<wm.quantities.wallBlocks,'Changing ground revises buried courses');
const buried=buildYardModel({...data,yardFeatures:[{...wall,wallTopSteps:[{stationIn:150,elevationIn:48-20*course}]}]}).features[0];ok(!buried.excluded&&buried.quoteRequired,'Below-ground stepped cap remains safe and visibly pending');ok(buried.boxes.every(b=>Number.isFinite(b.x+b.y+b.z+b.h)),'Below-ground step never creates undefined course paths');
const extreme=buildYardModel({...data,yardFeatures:[{...wall,wallTopSteps:undefined,finishedElevationIn:120000}]}).features[0];ok(extreme.excluded&&extreme.quantities.wallGeometryPending===1,'Unbuildable elevation span is atomically excluded before stock allocation');
assert.throws(()=>validateYardFinishedSettings({...wall,widthFt:2,wallPath:undefined,curves:undefined}));checks++;
const foundationData:DeckData={...structuredClone(DEFAULT_DECK),height:72,houseVisible:false,siteModel:survey(()=>20),yardFeatures:[]},foundationDeck=buildDeckTakeoff(foundationData),datum=foundationDeck.foundationSupports.find(p=>p.status==='modeled')!;ok(!!datum,'Measured foundation datum fixture');const oneFoundation={...foundationDeck,foundationSupports:[datum]},foundationYard=buildYardModel(foundationData,oneFoundation),pierAnalytic=Math.PI*36*datum.depthIn/46656;near(foundationYard.sharedExcavationYd3,pierAnalytic,'Minimum physical concrete pier excavation within analytic 0.1 percent',pierAnalytic*.001);near(foundationYard.quantities.excavationYd3,0,'Foundation bank volume is excluded from priced yard excavation');near(foundationYard.deckFoundationExcavationYd3,foundationYard.sharedExcavationYd3,'Foundation-owned physical bank reconciles shared total');ok(foundationYard.foundationExcavationPending,'Foundation overdig/disposal allowance reconciliation remains pending');const duplicateFoundation=buildYardModel(foundationData,{...foundationDeck,foundationSupports:[datum,{...datum,id:'overlapping-foundation'}]});near(duplicateFoundation.sharedExcavationYd3,foundationYard.sharedExcavationYd3,'Coincident foundation excavations count once');
console.log(`Elevation geometry checks passed: ${checks}; analytical crossings, fixed elevations, rigid slope stock, normal layer volume, curved stepped wall tops.`);


if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify({checks,maxRelativeErrorPct:Math.max(...accuracy.map(v=>v.relativeErrorPct??0)),fixtures:accuracy},null,2));
