import assert from 'node:assert/strict';
import * as THREE from 'three';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {validateDesign,parseDesign,serializeDesign} from '../src/features/deckcraft/designPersistence';
import {getHouseConfig} from '../src/features/deckcraft/houseSettings';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {calculateEstimate} from '../src/features/deckcraft/calculations';
import {extrasLayout} from '../src/features/deckcraft/extrasLayout';
import {deckColourRef} from '../src/features/deckcraft/boardFinishes';
import {selectableBoards} from '../src/features/deckcraft/designer/boardLayoutActions';
import {editBoardBatch} from '../src/features/deckcraft/designer/boardBatchActions';
import {applyComponentBatch} from '../src/features/deckcraft/designer/componentEditActions';
import {objectPick} from '../src/features/deckcraft/components/viewer3d/SelectionBridge';
import {editPricePreview} from '../src/features/deckcraft/designer/editPricePreview';
let checks=0;const check=(yes:unknown,message:string)=>{assert.ok(yes,message);checks++;};
const base={...validateDesign({...DEFAULT_DECK,width:20,length:20,height:48,stairFlights:0,houseConfig:{...getHouseConfig(DEFAULT_DECK),widthFt:30,depthFt:20,storeys:2,openings:[{id:'a',type:'Window',facade:'Front',widthIn:48,heightIn:36,bottomIn:100,offsetPct:25},{id:'b',type:'Window',facade:'Front',widthIn:48,heightIn:36,bottomIn:100,offsetPct:75}]},privacyScreens:[{id:'left-a',side:'Left',lengthFt:4,heightFt:6,offsetPct:20,lights:false},{id:'left-b',side:'Left',lengthFt:4,heightFt:6,offsetPct:60,lights:false}]}),customerName:'QA',materialMarkup:23.5};
const model=buildDeckTakeoff(base),original=JSON.stringify(base),targets=selectableBoards(base,model).filter(b=>b.run.role==='field'&&b.run.length>24).slice(3,6).map(b=>({level:b.modelLevel,index:b.index}));
check(targets.length===3,'Three actual field stock targets are available');
let n=0;const patch=editBoardBatch(base,model,targets,{angleDeg:33,colour:deckColourRef(base)},()=>`batch-independent-${++n}`),next={...base,...patch};
check(next.boardLayout?.pieces.length===3,'Three original physical stocks rotated in one returned patch');
for(const [i,piece] of next.boardLayout!.pieces.entries()){
 const before=model.levels[targets[i].level].boards[targets[i].index];
 check(piece.cx===before.cx&&piece.cy===before.cy,'Original-model board centres remain stable after earlier rotations');
 check(piece.angleDeg===33&&piece.colour===deckColourRef(base),'Every selected physical stock uses the requested direction and colour');
 check(piece.polygon!.length>=3,'Each board retains its real cut silhouette');
}
check(!('customerName'in patch)&&!('materialMarkup'in patch),'Batch patch does not replace job/private pricing fields');
check(next.customerName===base.customerName&&next.materialMarkup===23.5,'Merging a batch preserves private live settings');
check(parseDesign(serializeDesign(next)).boardLayout?.pieces.length===3,'Complete physical board batch round-trips in saved design');
const reused=buildDeckTakeoff(next),fragments=selectableBoards(next,reused).filter(b=>b.run.layoutId===next.boardLayout!.pieces[0].id);
if(fragments.length){const dup=editBoardBatch(next,reused,[{level:fragments[0].modelLevel,index:fragments[0].index},{level:fragments[0].modelLevel,index:fragments[0].index}],{angleDeg:70},()=>`duplicate-${++n}`);check(dup.boardLayout?.pieces.length===3,'Duplicate selection does not create duplicate physical stock');}
for(const values of [[],[{level:99,index:0}],targets]){let failed=false;try{editBoardBatch(base,model,values,{angleDeg:NaN},()=>`bad-${++n}`);}catch{failed=true;}check(failed,'Empty, stale and nonfinite batch input reject');}
let collision=false;try{editBoardBatch({...base,boardLayout:next.boardLayout},model,[targets[0]],{angleDeg:19},()=>next.boardLayout!.pieces[1].id);}catch{collision=true;}check(collision,'A generated batch ID cannot replace unrelated saved stock');
const opening=applyComponentBatch(base,model,['opening:a','opening:b'],{action:'update',fields:{widthIn:60,bottomIn:108}});if('error'in opening)throw new Error(opening.error);
check(opening.patch.houseConfig?.openings.every(o=>o.widthIn===60&&o.bottomIn===108),'Opening batch changes both actual measured openings');
check(Object.keys(opening.patch).length===1,'Opening batch is one narrow house patch');
const invalid=applyComponentBatch(base,model,['opening:a','screen:left-a'],{action:'remove'});check('error'in invalid,'Mixed kinds reject without a partial removal');
check('error'in applyComponentBatch(base,model,['opening:a','opening:absent'],{action:'remove'}),'Missing target rejects entire batch');
check('error'in applyComponentBatch(base,model,['beam:0:0','beam:0:1'],{action:'update',fields:{widthFt:30}}),'Generated beams cannot acquire fake local overrides');
const distributed=applyComponentBatch(base,model,['screen:left-a','screen:left-b'],{action:'distribute'});if('error'in distributed)throw new Error(distributed.error);
const dd={...base,...distributed.patch},handles=extrasLayout(dd,buildDeckTakeoff(dd)).screenHandles;
check(handles.length===2&&Math.hypot(handles[0].x-handles[1].x,handles[0].z-handles[1].z)>48,'Actual four-foot screens distribute without overlap');
check(dd.privacyScreens!.every(s=>s.lengthFt===4&&s.heightFt===6),'Distribution preserves purchased dimensions');
const move=applyComponentBatch(base,model,['screen:left-a','screen:left-b'],{action:'move',offsetDeltaPct:10});if('error'in move)throw new Error(move.error);
check(move.patch.privacyScreens?.[0].offsetPct===30&&move.patch.privacyScreens[1].offsetPct===70,'Relative screen movement preserves spacing');
check('error'in applyComponentBatch(base,model,['screen:left-a','screen:left-b'],{action:'move',offsetDeltaPct:50}),'One out-of-range screen rejects the whole movement');
const crowded={...base,deckType:'Freestanding' as const,houseVisible:false,privacyScreens:(['Left','Right','Front','Back'] as const).map((side,i)=>({id:`crowded-${i}`,side,lengthFt:8,heightFt:6 as const,offsetPct:50,lights:false}))};
check('error'in applyComponentBatch(crowded,buildDeckTakeoff(crowded),['screen:crowded-0','screen:crowded-1'],{action:'duplicate'}),'Duplicate batch rejects actual eight-foot screens only sixty inches apart, including collision with unselected originals');
const lit=applyComponentBatch(base,model,['screen:left-a','screen:left-b'],{action:'screen-lights',enabled:true});if('error'in lit)throw new Error(lit.error);
const ld={...base,...lit.patch},layout=extrasLayout(ld,buildDeckTakeoff(ld)),blink=ld.lightingSystem.selectedItems.find(i=>i.zone==='privacy');
check(blink?.qty===layout.privacyMounts.length&&blink.qty===4,'Screen light purchase count matches four actual post mounts');
check(layout.fixtures.filter(f=>f.zone==='privacy').length===4,'All purchased screen lights have an actual displayed mount');
check(calculateEstimate(ld).total>calculateEstimate(base).total,'Actual mounted light supply increases the priced portion');
const review=await editPricePreview(base,lit.patch);check(review.includes('including HST')&&review.includes('Outstanding quotes:'),'Pre-Apply price review discloses priced total and missing installation quotes');
const removed=applyComponentBatch(ld,buildDeckTakeoff(ld),['screen:left-a','screen:left-b'],{action:'remove'});if('error'in removed)throw new Error(removed.error);
check(removed.patch.privacyScreens?.length===0&&!removed.patch.lightingSystem?.selectedItems.some(i=>i.zone==='privacy'),'Removing lit screens removes only their auto-mounted light quantity');
const actualBoxes=layout.wood.filter(b=>b.screenId==='left-a');check(actualBoxes.length===12,'Twelve actual six-foot-screen slats carry their saved screen identity');
check(layout.metal.filter(b=>b.screenId==='left-a').length===2,'Two actual screen posts share that screen identity');
const wall=new THREE.Group();wall.userData.pickPartId='wall:main-front';const window=new THREE.Group();window.userData.pickPartId='opening:a';const glass=new THREE.Mesh();wall.add(window);window.add(glass);check(objectPick(glass)?.partId==='opening:a','Actual opening mesh resolves the opening, not its parent wall');
const mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial(),2);mesh.userData.pickBoards=[{level:0,index:8},{level:1,index:3}];check(objectPick(mesh,1)?.board?.level===1&&objectPick(mesh,1)?.board?.index===3,'Actual rendered instance resolves exact model level/index');check(objectPick(mesh,8)===null,'Out-of-range instances cannot fabricate a board');
const ghost=new THREE.Group();ghost.name='privacy-screen-drag-handles';ghost.add(new THREE.Mesh());check(objectPick(ghost.children[0])===null,'Invisible drag proxy is not an object-selection target');
check(JSON.stringify(base)===original,'All previews, successful batches and rejections leave the input untouched');
console.log(`${checks} independent selection and atomic batch checks passed.`);
