import * as THREE from 'three';
import {createFixtureLighting,litMaterial} from '../src/features/deckcraft/components/viewer3d/fixtureLighting';
import {materialPatchKeys} from '../src/features/deckcraft/components/viewer3d/materialPatches';
import {exportDeckGlb,exportDeckCollada} from '../src/features/deckcraft/cadExports';
import {elevationProfileSpecs,buildElevationProfile} from '../src/features/deckcraft/elevationProfiles';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData} from '../src/features/deckcraft/types';
import type {PoolFeature} from '../src/features/deckcraft/poolTypes';
import type {LandscapeObject} from '../src/features/deckcraft/landscapeTypes';
import {createPlanningPool} from '../src/features/deckcraft/poolAssembly';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {buildYardModel,yardClip,yardSolidCells} from '../src/features/deckcraft/yardModel';
import {getPoolModels} from '../src/features/deckcraft/poolModel';
import {poolRenderMeshes,poolMeshSection} from '../src/features/deckcraft/poolRenderMeshes';
import {poolBufferGeometry,poolMaterial} from '../src/features/deckcraft/components/viewer3d/Pool3D';
import {deckExportMeshes} from '../src/features/deckcraft/designExports';
import {poolPlanDrawingItems,poolSectionDrawingItems} from '../src/features/deckcraft/poolDrawings';
import {buildPermitSet} from '../src/features/deckcraft/drawings/permitSheets';
import {buildPermitDxf} from '../src/features/deckcraft/drawings/renderDxf';
import {landscapeTakeoff,landscapePlacement,landscapeBedAreas} from '../src/features/deckcraft/landscapeModel';
import {previewStairRefit} from '../src/features/deckcraft/stairRefit';
import {stairLandingPolygons} from '../src/features/deckcraft/stairLandingGeometry';
import {poolWorldPoint,poolLocalBounds} from '../src/features/deckcraft/poolGeometry';
import {groundGeometry} from '../src/features/deckcraft/components/viewer3d/lawnSurface';
let checks=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},near=(a:number,b:number,m:string,tolerance=1e-4)=>ok(Math.abs(a-b)<=tolerance,`${m}: ${a}/${b}`);
const base:DeckData={...structuredClone(DEFAULT_DECK),height:48,stairFlights:0,railingType:'None',terrainConfig:{widthFt:180,depthFt:180,elevationIn:0,slopePct:0}};
for(const type of ['fiberglass','vinyl-liner','concrete'] as const)for(const rotation of [0,31,90]){
 const p:PoolFeature={...createPlanningPool({id:`pool-${type}-${rotation}`,type,xIn:600,zIn:600,copingTopElevationIn:9,shape:rotation===31?'rounded-rectangle':'rectangle'}),rotationDeg:rotation,depthProfile:[{stationIn:0,depthIn:36},{stationIn:144,depthIn:36},{stationIn:384,depthIn:72}]},data={...base,pools:[p]};await ensureLiveDesignExtensions(data);const deck=buildDeckTakeoff(data),pool=getPoolModels(data,deck)[0],meshes=poolRenderMeshes(pool),exported=deckExportMeshes(data,deck).filter(m=>m.name.startsWith('pool_'));
 assert.deepEqual(exported,meshes);checks++;ok(meshes.length>0,'Physical pool mesh is exported');
 for(const mesh of meshes){const g=poolBufferGeometry(mesh),positions=g.getAttribute('position');ok(Array.from(positions.array).every(Number.isFinite),'Pool renderer has finite coordinates');for(let k=0;k<Math.min(positions.count,12);k++){const match=mesh.vertices.some(v=>Math.hypot(v.x-positions.getX(k),v.y-positions.getY(k),v.z-positions.getZ(k))<.0002);if(mesh.role!=='coping')ok(match,'Renderer positions come from export vertices');else{const v={x:positions.getX(k),y:positions.getY(k),z:positions.getZ(k)};ok((['x','y','z'] as const).every(axis=>v[axis]>=Math.min(...mesh.vertices.map(p=>p[axis]))-.001&&v[axis]<=Math.max(...mesh.vertices.map(p=>p[axis]))+.001),'Coping relief stays inside exported stock bounds');}}g.dispose();}
 if(rotation===0){const glb=exportDeckGlb(data,deck),view=new DataView(glb),jsonLength=view.getUint32(12,true),json=JSON.parse(new TextDecoder().decode(new Uint8Array(glb,20,jsonLength))),binStart=20+jsonLength+8;ok(json.materials.some((m:any)=>m.extras?.poolRole==='water'&&m.alphaMode==='BLEND'),'GLB water is transparent and identified');for(const [index,mesh] of exported.entries()){const node=json.meshes.find((m:any)=>m.name===mesh.name),a=json.accessors[node.primitives[0].attributes.POSITION],bv=json.bufferViews[a.bufferView],positions=new Float32Array(glb,binStart+bv.byteOffset,a.count*3);for(let i=0;i<Math.min(positions.length,36);i+=3)ok(mesh.vertices.some(v=>Math.hypot(v.x*.0254-positions[i],v.y*.0254-positions[i+1],v.z*.0254-positions[i+2])<.0001),'GLB uses identical physical vertices in metres');}const dae=exportDeckCollada(data,deck);ok(dae.includes('<unit name="inch" meter="0.0254"/>'),'Collada unit retained');ok(dae.includes('Pool water')&&dae.includes('A_ONE'),'Collada distinguishes pool water/transparency');}
 const water=meshes.filter(m=>m.role==='water');for(const m of water){near(Math.max(...m.vertices.map(v=>v.y)),p.copingTopElevationIn-p.waterOffsetIn,'Water top matches recorded absolute level');ok(m.faces.every(f=>f.every(i=>Math.abs(m.vertices[i].y-pool.waterElevationIn)<1e-7)),'Water exposes its level surface without internal depth-station walls');}
 const b=poolLocalBounds(p),a=poolWorldPoint(p,{x:0,y:b.minZ-24}),z=poolWorldPoint(p,{x:0,y:b.maxZ+24}),sections=meshes.flatMap(m=>poolMeshSection(m,a,z));ok(sections.length>0,'Physical section intersects the basin');ok(sections.every(s=>[s.a.stationIn,s.b.stationIn,s.a.elevationIn,s.b.elevationIn].every(Number.isFinite)),'Section has finite true elevations');
 const specs=elevationProfileSpecs(data,deck),floorSpec=specs.find(s=>s.id===`pool-${p.id}-longitudinal-floor`)!,waterSpec=specs.find(s=>s.id===`pool-${p.id}-longitudinal-water`)!;ok(!!floorSpec&&!!waterSpec,'Pool has interactive profile choices');const profileYard=buildYardModel(data,deck),floorProfile=buildElevationProfile(data,floorSpec,profileYard),waterProfile=buildElevationProfile(data,waterSpec,profileYard);for(const q of waterProfile.points.filter(q=>q.finishedIn!==null))near(q.finishedIn!,pool.waterElevationIn,'Interactive profile water agrees with shared mesh');const floorValues=floorProfile.points.flatMap(q=>q.finishedIn===null?[]:[q.finishedIn]);near(Math.max(...floorValues),pool.waterElevationIn-36,'Interactive floor shows shallow depth');near(Math.min(...floorValues),pool.waterElevationIn-72,'Interactive floor shows deep depth');
 const plan=poolPlanDrawingItems(data,deck),section=poolSectionDrawingItems(data,deck,{x:0,y:0});ok(plan.some(i=>i.kind==='text'&&i.text.includes('coping +9.00 in')),'Plan shows absolute coping level');ok(section.some(i=>i.kind==='text'&&i.text.includes('water +3.00 in')),'Section shows identical absolute water level');ok(section.some(i=>i.kind==='text'&&i.text.includes('BELOW WATER')),'Depth datum is explicit');
 const set=buildPermitSet({data,model:deck,date:'QA',priceBook:'QA',materialName:'Wood',railingName:'None',reviewItems:[]});ok(set.sheets.some(s=>s.id==='A-2'),'Pool-only design receives section sheet');ok(buildPermitDxf(set).includes('water +3.00 in'),'DXF uses the same water labels');ok(set.reviewItems.some(s=>/unverified|planning|pool/i.test(s)),'Planning pool remains pending in drawings');
 const changed={...data,terrainConfig:{...data.terrainConfig,elevationIn:24,slopePct:2}},again=getPoolModels(changed,buildDeckTakeoff(changed))[0];near(again.waterElevationIn,pool.waterElevationIn,'Ground edits keep fixed pool water');near(again.copingTopElevationIn,pool.copingTopElevationIn,'Ground edits keep rim');
}
const bedPool=createPlanningPool({id:'setting-bed-pool',xIn:600,zIn:600,copingTopElevationIn:9}),bedData={...base,pools:[{...bedPool,coping:{...bedPool.coping!,settingBedThicknessIn:.5,settingBedMaterial:'mortar' as const}}]};await ensureLiveDesignExtensions(bedData);const settingModel=getPoolModels(bedData)[0],settingMeshes=poolRenderMeshes(settingModel);ok(settingMeshes.some(m=>m.role==='setting-bed'),'Recorded coping setting bed is physical mesh');for(const m of settingMeshes.filter(m=>m.role==='setting-bed'))near(Math.max(...m.vertices.map(v=>v.y))-Math.min(...m.vertices.map(v=>v.y)),.5,'Setting-bed stock thickness matches recorded input');
const unknown={...createPlanningPool({id:'minimum',xIn:600,zIn:600,copingTopElevationIn:6}),assembly:undefined,coping:undefined},unknownData={...base,pools:[unknown]};await ensureLiveDesignExtensions(unknownData);const unknownModel=getPoolModels(unknownData)[0],unknownMeshes=poolRenderMeshes(unknownModel);ok(unknownMeshes.some(m=>m.role==='floor'&&m.planning),'Unknown assembly displays unpriced zero-thickness floor finish');ok(unknownMeshes.some(m=>m.role==='wall'&&m.planning),'Unknown assembly displays unpriced vertical interior');ok(unknownModel.pending.length>0,'Missing assembly is explicit pending');near(unknownModel.quantities.structureYd3,0,'No fabricated shell volume');
const furniture:LandscapeObject={id:'chair',name:'Chair',enabled:true,kind:'furniture',assetId:'outdoor-chair',xIn:600,zIn:600,rotationDeg:0,widthIn:24,depthIn:24,heightIn:36},bed:LandscapeObject={...furniture,id:'bed',name:'Pool-side bed',kind:'bed',assetId:'mulch-bed',widthIn:240,depthIn:432,mulchDepthIn:3,edging:true},landscapeData={...unknownData,landscapeObjects:[furniture,bed]};await ensureLiveDesignExtensions(landscapeData);ok(landscapePlacement(landscapeData,furniture).pendingReason?.includes('opening'),'Furniture cannot occupy pool hole');const plants={...furniture,id:'tree',name:'Tree',kind:'plant' as const,assetId:'deciduous-tree' as const};ok(landscapePlacement(landscapeData,plants).pendingReason?.includes('opening'),'Plants cannot occupy pool hole');const takeoff=landscapeTakeoff([bed],landscapeData),legacyTakeoff=landscapeTakeoff([bed]);ok(takeoff.bedAreaSqft<legacyTakeoff.bedAreaSqft,'Pool hole reduces measured bed area');near(takeoff.mulchYd3,takeoff.bedAreaSqft*3/324,'Mulch follows clipped physical bed area');ok(takeoff.warnings.some(s=>/pool|opening/i.test(s)),'Bed clipping emits explicit conflict warning');ok(landscapeBedAreas([bed],landscapeData).get(bed.id)!.length>0,'Outside bed coverage remains');
const renderFirstData={...landscapeData,yardFeatures:[{id:'support-patio',kind:'patio' as const,name:'Surround',enabled:true,xFt:50,zFt:50,widthFt:40,depthFt:50,heightIn:0,finishedElevationIn:0,rotationDeg:0,productId:'generic-paver',color:'#aaa'}]},renderFirstDeck=buildDeckTakeoff(renderFirstData);await ensureLiveDesignExtensions(renderFirstData);const firstPool=getPoolModels(renderFirstData)[0],firstMeshes=poolRenderMeshes(firstPool),firstSnapshot=JSON.stringify(firstMeshes);buildYardModel(renderFirstData,renderFirstDeck);assert.equal(JSON.stringify(firstMeshes),firstSnapshot,'Material reconciliation never mutates already returned render meshes');checks++;assert.deepEqual(deckExportMeshes(renderFirstData,renderFirstDeck).filter(m=>m.name.startsWith('pool_')),firstMeshes);checks++;
const yard=buildYardModel(unknownData,buildDeckTakeoff(unknownData)),before=JSON.stringify(yard.siteSurface),pool=getPoolModels(unknownData)[0],bounds={minX:0,minZ:0,width:1200,depth:1200},ground=groundGeometry(yard,pool.permanentExclusionFootprints,192,192,bounds),position=ground.getAttribute('position');
for(let i=0;i+2<position.count;i+=3){const x=(position.getX(i)+position.getX(i+1)+position.getX(i+2))/3,z=(position.getZ(i)+position.getZ(i+1)+position.getZ(i+2))/3;ok(!(x>504.001&&x<695.999&&z>408.001&&z<791.999),'Visual ground triangles do not cover pool opening');}ground.dispose();ok(before===JSON.stringify(yard.siteSurface),'Display hole leaves calculation terrain snapshot unchanged');
const stairData={...base,stairFlights:1},stairDeck=buildDeckTakeoff(stairData),flight=stairDeck.flights.find(f=>f.kind==='grade')!;ok(!!flight,'Stair fixture has terminal flight');const landing=stairLandingPolygons(stairDeck,flight.id,36).flat(),cx=landing.reduce((n,p)=>n+p.x,0)/landing.length,cz=landing.reduce((n,p)=>n+p.y,0)/landing.length,stairPool=createPlanningPool({id:'stair-conflict',xIn:cx,zIn:cz,copingTopElevationIn:0}),collisionData={...stairData,pools:[stairPool]};await ensureLiveDesignExtensions(collisionData);const refit=previewStairRefit(collisionData);ok(refit.status==='pending'&&refit.warnings.some(s=>/pool/i.test(s)),'Stair refit refuses pool-overlapping landing');
const fixtureLighting=createFixtureLighting();for(const role of ['coping','collar','water'] as const){const material=poolMaterial({role,color:'#b6ad99'});litMaterial(material,fixtureLighting);const shader={vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader,uniforms:{}};material.onBeforeCompile(shader as unknown as THREE.WebGLProgramParametersWithUniforms,{} as THREE.WebGLRenderer);ok(shader.fragmentShader.includes('fxCount'),'Pool material retains fixture lighting shader');if(role==='water'){ok(shader.vertexShader.includes('vPoolPosition'),'Water highlight is fixed in design coordinates');ok(!shader.vertexShader.includes('position.y+='),'Water highlight never moves fixed elevations');}else{ok(materialPatchKeys(material).includes('hardscape-mineral-roughness-v1'),'Coping and collar reuse existing mineral finish');ok(shader.fragmentShader.includes('poolGrainWeight'),'Mineral detail fades below a pixel');ok(shader.fragmentShader.includes('poolDet'),'Mineral finish adds bounded normal grain');}material.dispose();}fixtureLighting.dispose();
const empty={...structuredClone(DEFAULT_DECK),pools:[]};ok(poolPlanDrawingItems(empty,buildDeckTakeoff(empty)).length===0,'Empty pool drawings no-op');assert.deepEqual(deckExportMeshes(empty,buildDeckTakeoff(empty)),deckExportMeshes(DEFAULT_DECK,buildDeckTakeoff(DEFAULT_DECK)));checks++;console.log(`Pool display/export: ${checks} checks passed.`);


