import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {previewStairRefit} from '../src/features/deckcraft/stairRefit';
import {validateStairTargets,stairTargetId} from '../src/features/deckcraft/stairTargets';
import {foundationSolids} from '../src/features/deckcraft/foundationDatums';
import {getHardwareLayout} from '../src/features/deckcraft/hardwareLayout';
import {deckExportMeshes,type ExportMesh} from '../src/features/deckcraft/designExports';
import {buildYardModel} from '../src/features/deckcraft/yardModel';
import {newYardFeature} from '../src/features/deckcraft/yardSettings';
import {yardBoxRings,tiltStockPoint} from '../src/features/deckcraft/yardElevationGeometry';
import {validateSiteModel} from '../src/features/deckcraft/siteModelRuntime';
import '../src/features/deckcraft/siteSurfaceEngine';
import type {DeckData} from '../src/features/deckcraft/types';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {deckReleaseData,serializeDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {emptyHistory,recordChange,undoChange} from '../src/features/deckcraft/designer/designHistory';
let checks=0;
const ok=(condition:unknown,message:string)=>{assert.ok(condition,message);checks++;};
const near=(actual:number,expected:number,message:string,tolerance=1e-6)=>{assert.ok(Math.abs(actual-expected)<=tolerance,`${message}: ${actual} vs ${expected}`);checks++;};
const meshVolume=(m:ExportMesh)=>Math.abs(m.faces.reduce((sum,face)=>sum+face.slice(1,-1).reduce((s,_,i)=>{const a=m.vertices[face[0]],b=m.vertices[face[i+1]],c=m.vertices[face[i+2]];return s+(a.x*(b.y*c.z-b.z*c.y)+a.y*(b.z*c.x-b.x*c.z)+a.z*(b.x*c.y-b.y*c.x))/6;},0),0));
const survey=(height:number,slopeX=0,slopeZ=0,size=2000)=>validateSiteModel({version:1,points:[[-size,-size],[size,-size],[size,size],[-size,size]].map(([xIn,zIn],i)=>({id:`p${i}`,xIn,zIn,elevationIn:height+xIn*slopeX+zIn*slopeZ})),grading:[]});
const base:DeckData={...structuredClone(DEFAULT_DECK),houseVisible:false,deckType:'Freestanding',soilCondition:'Sandy'};
await ensureLiveDesignExtensions({...base,siteModel:survey(0)});
const legacy=buildDeckTakeoff(base),baseline=JSON.stringify(base);
ok(!base.stairTargets,'Legacy target setting remains absent');near(legacy.flights.find(f=>f.kind==='grade')!.end.y,0,'Absent target retains legacy zero landing');
const legacyRefit=previewStairRefit(base);ok(legacyRefit.status==='ready','Flat legacy refit feasible');ok(JSON.stringify(base)===baseline,'Refit preview has no writes');near(legacyRefit.proposals[0].target.elevationIn,0,'Legacy proposed landing stays zero');
for(const grade of [12,-12]){
 const data={...base,siteModel:survey(grade)},before=buildDeckTakeoff(data),preview=previewStairRefit(data);ok(preview.status==='ready',`Flat measured ${grade} landing fits`);near(before.flights[0].end.y,0,'Terrain edit never automatically moves existing stairs');const next={...data,...preview.patch},model=buildDeckTakeoff(next),target=preview.proposals[0].target;near(model.levels[0].top,data.height,'Refit keeps upper deck fixed');near(model.flights.filter(f=>f.kind==='grade').at(-1)!.end.y,grade,'Refit lands on measured datum');ok(model.flights.filter(f=>f.kind==='grade').every(f=>Math.abs(f.rise-preview.proposals[0].riseIn)<1e-6),'Refitted flight equal rises');near(preview.proposals[0].riseIn,(data.height-grade)/target.riserCount,'Riser proposal uses actual height delta');const changed=buildDeckTakeoff({...next,siteModel:survey(grade+7)});near(changed.flights.filter(f=>f.kind==='grade').at(-1)!.end.y,grade,'Saved termination stays fixed after new terrain');ok(changed.foundationSupports.every(f=>f.gradeElevationIn===grade+7),'Foundation datums respond to new proposed ground');
}
ok(previewStairRefit({...base,siteModel:survey(0,0,.02)}).status==='pending','Conflicting complete landing slope stays pending');ok(previewStairRefit({...base,siteModel:survey(0,0,0,100)}).status==='pending','Partial landing coverage stays pending');ok(previewStairRefit({...base,siteModel:survey(40)}).status==='pending','Ground above fixed upper deck is infeasible');ok(previewStairRefit(base,{flightId:'grade-9'}).status==='pending','Vanished target does not fabricate a flight');
for(const stairType of ['Straight','Landing','Winder'] as const){const data={...base,height:72,stairType,siteModel:survey(6)},preview=previewStairRefit(data);ok(preview.status==='ready',`${stairType} refit feasible`);const model=buildDeckTakeoff({...data,...preview.patch}),flights=model.flights.filter(f=>f.kind==='grade');ok(flights.every(f=>Math.abs(f.rise-preview.proposals[0].riseIn)<1e-6),`${stairType} common rise across flights`);near(Math.min(...flights.map(f=>f.end.y)),6,`${stairType} final target matches`);}
const wrapped={...base,stairPath:{points:[{x:0,y:144},{x:192,y:144},{x:192,y:0}]},stairRiserCount:5,stairTreadDepthIn:12,siteModel:survey(6)},wrapPreview=previewStairRefit(wrapped);ok(wrapPreview.status==='ready','Wrapped perimeter refit feasible');const wrapModel=buildDeckTakeoff({...wrapped,...wrapPreview.patch});ok(wrapModel.flights.filter(f=>f.kind==='grade').every(f=>stairTargetId(f.id)==='grade-path'&&Math.abs(f.end.y-6)<1e-6),'Wrapped segments share one fixed termination');ok(wrapPreview.proposals[0].landingOutlines.length===2,'Wrapped refit evaluates both complete bottom landing faces');
const inline={...base,height:144,siteModel:survey(0)},inlinePreview=previewStairRefit(inline);ok(inlinePreview.status==='ready','Long straight refit retains reviewed inline landing');ok(buildDeckTakeoff({...inline,...inlinePreview.patch}).levels.some(l=>l.kind==='landing'),'Long straight candidate contains intermediate landing');
const patio={...newYardFeature('patio',base),id:'landing',xFt:8,zFt:19,widthFt:12,depthFt:12,finishedElevationIn:12,patioSlope:{xPct:0,zPct:0}},patioData={...base,yardFeatures:[patio]},patioPreview=previewStairRefit(patioData,{surface:'patio',patioId:'landing'});ok(patioPreview.status==='ready','Explicit finished patio landing feasible');near(patioPreview.proposals[0].target.elevationIn,12,'Patio target uses finished elevation, not soil');ok(patioPreview.proposals[0].target.patioId==='landing','Patio target persists surface identity');ok(previewStairRefit({...patioData,yardFeatures:[{...patio,widthFt:2,depthFt:2}]},{surface:'patio',patioId:'landing'}).status==='pending','Partial patio landing coverage pending');ok(previewStairRefit({...patioData,yardFeatures:[{...patio,patioSlope:{xPct:2,zPct:0}}]},{surface:'patio',patioId:'landing'}).status==='pending','Cross-slope patio equal-rise conflict pending');
for(const foundation of ['Concrete Piers','Helical Piles','Deck Blocks'] as const){const data={...base,foundation,siteModel:survey(-8,.04,.01)},model=buildDeckTakeoff(data),meshes=deckExportMeshes(data,model);for(const datum of model.foundationSupports){const ground=-8+datum.x*.04+datum.z*.01;near(datum.gradeElevationIn!,ground,'Foundation uses exact local proposed grade');near(datum.bottomElevationIn!,ground-datum.depthIn,'Foundation bottom keeps entered below-grade depth');near(datum.postBaseElevationIn!,ground+(foundation==='Deck Blocks'?6.5:4.5),'Saddle keeps local datum');const solids=foundationSolids(datum),post=solids.boxes.find(p=>p.part==='post');if(post){near(post.y-post.h/2,datum.postBaseElevationIn!,'Post bottom matches saddle');near(post.y+post.h/2,datum.bearingElevationIn,'Post top matches framing bearing');}for(const solid of solids.cylinders){const mesh=meshes.find(m=>m.name===`level_${datum.levelIndex+1}_${solid.part.replaceAll('-','_')}_${datum.supportIndex}`)!;ok(!!mesh,'Foundation cylinder exported');near(Math.min(...mesh.vertices.map(v=>v.y)),solid.bottom,'Export foundation bottom equals displayed solid');near(Math.max(...mesh.vertices.map(v=>v.y)),solid.top,'Export foundation top equals displayed solid');}}
 near(model.foundationQuantities.supportPostLf,model.foundationSupports.reduce((n,d)=>n+(d.postHeightIn??0)/12,0),'Post quantity reconciles exact shown heights');near(model.quantities.supportPosts,model.foundationSupports.filter(d=>d.postHeightIn!>0).length,'Count uses actual positive post heights');if(foundation==='Concrete Piers'){const exported=meshes.filter(m=>m.name.includes('concrete_pier')).reduce((n,m)=>n+meshVolume(m)/46656,0);ok(Math.abs(exported-model.foundationQuantities.concretePierYd3)/model.foundationQuantities.concretePierYd3<.001,'Measured cylindrical concrete takeoff/export volume error below 0.1%');}
}
const uncoveredData={...base,siteModel:survey(0,0,0,20)},uncovered=buildDeckTakeoff(uncoveredData);ok(uncovered.foundationSupports.every(d=>d.status==='coverage-pending'&&d.gradeElevationIn===null&&d.postHeightIn===null),'Uncovered foundation datums stay null');near(uncovered.quantities.footings,0,'Uncovered quantities excluded');ok(!deckExportMeshes(uncoveredData,uncovered).some(m=>/concrete_pier|_post_base_/.test(m.name)),'Uncovered foundation solids are not exported at fake zero');near(getHardwareLayout(uncoveredData,uncovered).postCaps.length,0,'Uncovered post caps suppressed');near(getHardwareLayout(uncoveredData,uncovered).postAnchors,0,'Uncovered post anchors excluded');const high=buildDeckTakeoff({...base,siteModel:survey(35)});ok(high.foundationSupports.some(d=>d.status==='clearance-pending'),'Insufficient local saddle clearance stays pending');ok(high.issues.some(v=>v.includes('saddle')),'Insufficient saddle warning visible');near(getHardwareLayout(base,legacy).postCaps.length,legacy.quantities.supportPosts,'Legacy cap count retained');
for(const malformed of [[{flightId:'grade-0',elevationIn:0,riserCount:0,treadDepthIn:12,surface:'terrain'}],[{flightId:'grade-0',elevationIn:Infinity,riserCount:5,treadDepthIn:12,surface:'terrain'}],[{flightId:'grade-0',elevationIn:0,riserCount:5,treadDepthIn:12,surface:'patio'}]]){assert.throws(()=>validateStairTargets(malformed));checks++;}const getter=Object.defineProperty({},'flightId',{get(){throw Error('must not invoke');},enumerable:true});assert.throws(()=>validateStairTargets([getter]),/field/);checks++;
const slopePlane={x:.04,z:.03,constant:12},stock=[{x:0,y:0},{x:16,y:0},{x:16,y:8},{x:0,y:8}].map(p=>tiltStockPoint(p,slopePlane,{x:0,y:0})),rings=yardBoxRings({y:12,h:2,topPlane:slopePlane,normalThicknessIn:2},stock);for(let i=0;i<stock.length;i++){near(Math.hypot(rings.top[i].x-rings.bottom[i].x,rings.top[i].y-rings.bottom[i].y,rings.top[i].z-rings.bottom[i].z),2,'Rigid stock thickness preserved normally');const j=(i+1)%stock.length;near(Math.hypot(rings.top[i].x-rings.top[j].x,rings.top[i].y-rings.top[j].y,rings.top[i].z-rings.top[j].z),i%2?8:16,'Rigid stock face edge length preserved');}
const slopedData={...base,stairFlights:0,yardFeatures:[{...patio,finishedElevationIn:4,patioSlope:{xPct:3,zPct:2}}]},yard=buildYardModel(slopedData,buildDeckTakeoff(slopedData)),slopedMeshes=deckExportMeshes(slopedData,buildDeckTakeoff(slopedData)),piece=yard.boxes.find(b=>b.topPlane&&b.normalThicknessIn!==undefined&&b.polygon?.length)!;ok(!!piece,'Sloped patio exposes actual rigid stock');const pieceMesh=slopedMeshes.find(m=>m.name===`yard_${piece.id}`)!,pieceRings=yardBoxRings(piece,piece.polygon!);for(const v of [...pieceRings.top,...pieceRings.bottom])ok(pieceMesh.vertices.some(p=>Math.hypot(p.x-v.x,p.y-v.y,p.z-v.z)<1e-6),'Export uses shared exact stock rings');
const ridgeSite=survey(0);ridgeSite.grading=[{id:'tread-ridge',name:'Tread collision',boundary:[{x:50,y:144},{x:140,y:144},{x:140,y:160},{x:50,y:160}],originXIn:50,originZIn:144,elevationIn:35,slopeXPct:0,slopeZPct:0}];const ridgePreview=previewStairRefit({...base,siteModel:ridgeSite});ok(ridgePreview.status==='pending'&&ridgePreview.warnings.some(v=>v.includes('collide')),'Flat landing alone cannot approve treads intersecting a local terrain ridge');ok(previewStairRefit({...patioData,yardFeatures:[{...patio,curves:[{edge:0,bulgeIn:40}]}]},{surface:'patio',patioId:'landing'}).status==='pending','Curved inward patio uses actual support footprint, not control polygon');ok(deckExportMeshes(base,legacy).filter(m=>m.name.includes('concrete_pier')).every(m=>m.vertices.length===32),'Legacy cylinder facet parity preserved');
async function controllerChecks(){
 let state:DeckAgentHostState={data:deckReleaseData({...base,siteModel:survey(12)}),view:'plan',openSections:[],canUndo:false,canRedo:false,ready:true},commits=0,history=emptyHistory<DeckData>();
 const api=createDeckAgentController({getState:()=>state,commitDesign:data=>{commits++;history=recordChange(history,state.data,`edit-${commits}`,commits*1000);state={...state,data,canUndo:true};},undo:()=>{const old=undoChange(history,state.data);assert.ok(old);history=old.history;state={...state,data:old.design,canUndo:history.past.length>0,canRedo:true};},redo:()=>{},setView:view=>{state={...state,view};},openSection:section=>{state={...state,openSections:[...state.openSections,section]};},waitForRender:async predicate=>{assert.ok(predicate(state));}});
 const before=serializeDeckReleaseDesign(state.data),revision=api.read().revision,request={id:'stair-refit-preview',expectedRevision:revision,commands:[{type:'stair.refit' as const,flightId:'grade-0'}]},preview=await api.preview(request);ok(preview.ok&&commits===0&&serializeDeckReleaseDesign(state.data)===before,'Controller refit preview has no persistence or history writes');ok((await api.execute({id:'stair-width-change',commands:[{type:'design.patch',patch:{width:18}}]})).ok,'Intervening real edit succeeds');const stale=await api.execute(request);ok('error' in stale&&stale.error.code==='stale_revision','Refit apply rejects stale preview revision');near(commits,1,'Stale refit causes no commit');
 const org={layers:[{id:'design',name:'Design',visible:true,locked:false}],groups:[],objects:[{id:'deck',layerId:'design',locked:true}]};ok((await api.execute({id:'stair-lock',commands:[{type:'design.patch',patch:{editorOrganization:org}}]})).ok,'Deck metadata lock applied');const locked=serializeDeckReleaseDesign(state.data),lockCommits=commits;ok(!(await api.execute({id:'stair-locked-refit',commands:[{type:'stair.refit',flightId:'grade-0'}]})).ok,'Locked deck rejects refit target mutation');ok(!(await api.execute({id:'stair-locked-target',commands:[{type:'design.patch',patch:{stairTargets:[{flightId:'grade-0',elevationIn:12,riserCount:4,treadDepthIn:12,surface:'terrain'}]}}]})).ok,'Locked deck rejects direct target patch');ok(commits===lockCommits&&serializeDeckReleaseDesign(state.data)===locked,'Rejected lock edits preserve exact live state');
 org.objects[0].locked=false;ok((await api.execute({id:'stair-unlock',commands:[{type:'design.patch',patch:{editorOrganization:org}}]})).ok,'Deck unlock commits');const unlocked=serializeDeckReleaseDesign(state.data),oldCommits=commits;const applied=await api.execute({id:'stair-apply',expectedRevision:api.read().revision,commands:[{type:'stair.refit',flightId:'grade-0'}]});ok(applied.ok,`Revision-guarded refit executes: ${'error' in applied?applied.error.message:''}`);near(commits,oldCommits+1,'Refit applies in one commit');near(state.data.stairTargets![0].elevationIn,12,'Applied refit saves explicit target');ok((await api.execute({id:'stair-undo',commands:[{type:'history.undo'}]})).ok,'Refit undo succeeds');ok(serializeDeckReleaseDesign(state.data)===unlocked,'One undo restores exact pre-refit design');
 console.log(`Elevation stairs/foundations/stock export: ${checks} checks passed`);
}
controllerChecks().catch(error=>{console.error(error);process.exitCode=1;});
