import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,PrivacyScreen,RailSection} from '../src/features/deckcraft/types';
import {applyRailSections,edgeSectionId,validateRailSections} from '../src/features/deckcraft/lib/edgeSections';
import {getFootprint,getRailingSegments,type FootprintPlan,type RailSegment} from '../src/features/deckcraft/lib/deckGeometry';
import {buildDeckTakeoff,guardRuns} from '../src/features/deckcraft/deckTakeoff';
import {calculateEstimate} from '../src/features/deckcraft/calculations';
import {extrasLayout,screenOffsetFromPoint} from '../src/features/deckcraft/extrasLayout';
import {parseDesign,serializeDesign,validateDesign} from '../src/features/deckcraft/designPersistence';
import {PRIVACY_PRODUCTS} from '../src/features/deckcraft/privacyScreens';
import {decodeDesignLink,encodeDesignLink,designLinkFromHash} from '../src/features/deckcraft/designLink';
async function main(){
let checks=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},eq=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);checks++;},near=(a:number,b:number,m:string)=>ok(Math.abs(a-b)<1e-7,m),bad=(fn:()=>unknown,m:string)=>{assert.throws(fn,undefined,m);checks++;};
const length=(s:RailSegment)=>Math.hypot(s.b.x-s.a.x,s.b.y-s.a.y),total=(s:RailSegment[])=>s.reduce((n,r)=>n+length(r),0);
const base:DeckData={...structuredClone(DEFAULT_DECK),width:16,length:12,deckType:'Freestanding',houseVisible:false,stairFlights:0,railingType:'Aluminum',railingLf:0};
const fp=getFootprint(base),segments=getRailingSegments(base,fp,null),section=(edge:number,start=25,end=75,enabled=false):RailSection=>({id:'test',level:1,edgeId:edgeSectionId(fp,edge),startPct:start,endPct:end,enabled});
eq(applyRailSections(base,fp,1,segments),segments,'Absent options preserve the exact baseline guard array');ok(applyRailSections(base,fp,1,segments)===segments,'Absent overrides are a zero-change path');
eq(applyRailSections({...base,railSections:[]},fp,1,segments),segments,'Empty overrides preserve baseline');eq(serializeDesign({...base,railSections:[]}),serializeDesign(base),'Clearing the section array restores exact legacy serialization');
eq(buildDeckTakeoff({...base,railDefault:true,railSections:[]}),buildDeckTakeoff(base),'Explicit default-on reproduces complete legacy model');
const outlines:FootprintPlan[]=[fp,{outline:[{x:-24,y:-12},{x:200,y:20},{x:180,y:180},{x:60,y:120},{x:-24,y:180}],bounds:{w:224,h:192},isCurved:false}];
for(const polygon of outlines){const original=getRailingSegments(base,polygon,null);for(let edge=0;edge<polygon.outline.length;edge++)for(let i=1;i<=20;i++){
  const a=polygon.outline[edge],b=polygon.outline[(edge+1)%polygon.outline.length],len=Math.hypot(b.x-a.x,b.y-a.y),start=i,end=100-i,off={...section(0,start,end),edgeId:edgeSectionId(polygon,edge)};
  const edited=applyRailSections({...base,railSections:[off]},polygon,1,original);near(total(edited),total(original)-len*(end-start)/100,'Partial removal follows actual arbitrary-angle edge length');
  const on=applyRailSections({...base,railDefault:false,railSections:[{...off,enabled:true}]},polygon,1,original);near(total(on),len*(end-start)/100,'Explicit-only addition follows selected actual interval');
  for(const r of on){near((r.b.x-r.a.x)*(b.y-a.y)-(r.b.y-r.a.y)*(b.x-a.x),0,'Every generated piece is physically collinear with its selected edge');}
  eq(applyRailSections({...base,railDefault:false,railSections:[{...off,level:2,enabled:true}]},polygon,1,original),[],'Overrides never bleed across levels');
}}
const edge=fp.outline[1],end=fp.outline[2],at=(t:number)=>({x:edge.x+(end.x-edge.x)*t,y:edge.y+(end.y-edge.y)*t});
const eligible:RailSegment[]=[{a:at(0),b:at(.2),edge:'Right'},{a:at(.6),b:at(1),edge:'Right'}];
const clipped=applyRailSections({...base,railDefault:false,railSections:[section(1,10,90,true)]},fp,1,eligible);near(total(clipped),144*.4,'Enabled interval intersects eligible guards and cannot bridge an actual opening');eq(clipped.length,2,'Opening remains a real gap');
const joined=applyRailSections({...base,railDefault:false,railSections:[{...section(1,0,50,true),id:'a'},{...section(1,50,100,true),id:'b'}]},fp,1,segments);eq(joined.length,1,'Touching enabled spans merge without an artificial post seam');near(total(joined),144,'Merged range retains full edge length');
eq(applyRailSections({...base,railingType:'None',railDefault:false,railSections:[section(1,0,100,true)]},fp,1,segments),[],'None never gains guards without the explicit product action');
const priced=calculateEstimate({...base,railSections:[section(1)]}),baseline=calculateEstimate(base);near(priced.calculatedRailingLf,50,'Removal prices the actual six-foot gap');near(priced.model.quantities.railingLf,50,'Installed rail takeoff follows the same cut');eq(priced.model.quantities.railingPosts,priced.model.railing.posts.length,'Priced post count is the actual installed geometry');near(priced.total,priced.subtotal+priced.hst,'Edited guard accounting reconciles');ok(priced.total<baseline.total,'Real removal changes estimate rather than appearance only');
for(const extra of [{railSections:[section(1)]},{railSections:[]},{railDefault:true},{railDefault:false}]){const auto=calculateEstimate({...base,...extra,railingLf:0}),manual=calculateEstimate({...base,...extra,railingLf:100});eq(manual.total,auto.total,'Any section/default field makes direct material pricing follow actual guard LF');eq(manual.manHours,auto.manHours,'Any section/default field makes direct crew labour follow actual guard LF');eq(manual.sections,auto.sections,'No legacy manual LF can remain hidden in priced rows');}
const legacyOverride=calculateEstimate({...base,railingLf:100});ok(legacyOverride.total!==baseline.total,'Legacy designs retain their manual quantity price behavior');ok(legacyOverride.manHours!==baseline.manHours,'Legacy designs retain their manual quantity crew behavior');
const orphanRail=calculateEstimate({...base,railDefault:false,railSections:[{...section(1),edgeId:'edge:missing',enabled:true}]});eq(orphanRail.model.quantities.railingLf,0,'Orphan rail definition adds no invisible installed scope');ok(orphanRail.flags.some(f=>f.includes('saved rail section')&&f.includes('retained but inactive')),'Changed/missing rail edge is visible in estimate/API flags');
const withStairs={...base,stairFlights:1 as const,height:36},off=buildDeckTakeoff({...withStairs,railDefault:false}),one=buildDeckTakeoff({...withStairs,railDefault:false,railSections:[section(1,0,50,true)]});eq(off.quantities.railingLf,0,'Explicit-only with no sections produces no automatic deck/stair guard');eq(off.railing.posts.length,0,'Explicit-only has no hidden automatic stair posts');eq(one.quantities.stairRailingLf,0,'One selected perimeter section does not invent stair rails');near(one.quantities.railingLf,6,'Only requested section is installed');
for(const stairType of ['Straight','Landing','Winder'] as const){const m=buildDeckTakeoff({...withStairs,stairType,height:60,railDefault:false});eq(m.quantities.railingLf,0,'Explicit-only suppresses automatic rails for every stair/landing type');eq(m.railing.posts.length,0,'No hidden automatic posts for any stair type');}
const attached:DeckData={...base,deckType:'Attached',houseVisible:true},attachedFp=getFootprint(attached),houseOnly=buildDeckTakeoff({...attached,railDefault:false,railSections:[{...section(0,0,100,true),edgeId:edgeSectionId(attachedFp,0)}]});eq(houseOnly.quantities.railingLf,0,'An explicit enabled house-edge override cannot restore an ineligible ledger guard');
const multi:DeckData={...base,levels:3,width2:8,length2:8,height2:24,level3:{widthFt:6,lengthFt:6,heightIn:12,parent:2,position:'Front',offsetPct:50}};
for(const level of [1,2,3] as const){const model=buildDeckTakeoff(multi),l=model.levels.find(l=>l.kind==='deck'&&l.index===level-1)!;const edge=l.footprint.outline.findIndex((a,i)=>{const b=l.footprint.outline[(i+1)%l.footprint.outline.length];return a.x===b.x&&a.x===l.footprint.bounds.w;});const edited=buildDeckTakeoff({...multi,railDefault:false,railSections:[{id:'only',level,edgeId:edgeSectionId(l.footprint,edge),startPct:0,endPct:100,enabled:true}]});ok(guardRuns(edited).every(r=>r.a.y===l.top&&r.b.y===l.top),'Section stays on the selected level elevation');ok(edited.quantities.railingLf>0,'Selected lower-level rail has physical geometry');}
const valid=[section(1)];eq(validateRailSections(valid),valid,'Valid section schema survives exactly');eq(parseDesign(serializeDesign({...base,railDefault:false,railSections:valid})).railSections,valid,'JSON retains section identities and fractional intervals');eq((await decodeDesignLink(designLinkFromHash(new URL(await encodeDesignLink({...base,railDefault:false,railSections:valid})).hash)!)).railSections,valid,'Public share retains section overrides');
for(const patch of [{startPct:NaN},{endPct:Infinity},{startPct:-1},{startPct:80,endPct:20},{endPct:101},{level:4},{id:'bad space'},{edgeId:'x'.repeat(161)},{enabled:1},{unknown:1}])bad(()=>validateRailSections([{...section(1),...patch}]),'Malformed section rejects');bad(()=>validateRailSections([section(1),{...section(1),id:'overlap',startPct:50,endPct:90}]),'Overlapping same-edge overrides reject');bad(()=>validateRailSections([section(1),section(1)]),'Duplicate IDs reject');bad(()=>validateRailSections(Array.from({length:65},(_,i)=>({...section(1),id:String(i),level:1,edgeId:String(i)}))),'Section budget is bounded');bad(()=>validateDesign({...base,railDefault:'no'}),'Invalid default toggle rejects');
let getterCalls=0;const getter={...section(1)};Object.defineProperty(getter,'startPct',{enumerable:true,get(){getterCalls++;return 25;}});bad(()=>validateRailSections([getter]),'Getter entry rejects before evaluation');eq(getterCalls,0,'Validator never executes supplied getters');bad(()=>validateRailSections([Object.assign(Object.create({unexpected:true}),section(1))]),'Prototype fields reject');const hidden={...section(1)};Object.defineProperty(hidden,'extra',{value:1});bad(()=>validateRailSections([hidden]),'Hidden fields reject');bad(()=>validateRailSections(new Array(1)),'Sparse arrays reject');
const screen=(edgeId:string,level:1|2|3=1):PrivacyScreen=>({id:'screen',side:'Right',level,edgeId,lengthFt:4,heightFt:6,offsetPct:0,lights:true});
for(const level of [1,2,3] as const){const model=buildDeckTakeoff(multi),l=model.levels.find(l=>l.kind==='deck'&&l.index===level-1)!,i=l.footprint.outline.findIndex((a,i)=>{const b=l.footprint.outline[(i+1)%l.footprint.outline.length];return a.x===b.x&&a.x===l.footprint.bounds.w;}),s=screen(edgeSectionId(l.footprint,i),level),data={...multi,privacyScreens:[s]},drawn=extrasLayout(data,buildDeckTakeoff(data)),h=drawn.screenHandles[0];ok(!!h,'Exact-edge screen draws on each real level');near(h.y,l.top+36,'Screen elevation follows selected deck top');near(h.edge.x,l.footprint.outline[i].x+l.offset.x,'Screen edge origin follows actual world X');near(h.edge.z,l.footprint.outline[i].y+l.offset.z,'Screen edge origin follows actual world Z');eq(h.edge.clearanceIn,0,'Explicit edge has no legacy end clearance');near(screenOffsetFromPoint(h,h.x,h.z)!,0,'Exact-edge drag inverse retains start position');eq(parseDesign(serializeDesign(data)).privacyScreens![0],s,'Exact screen level/edge fields persist');}
const angled:DeckData={...base,deckOutlines:{main:[{x:-2,y:0},{x:12,y:0},{x:16,y:12},{x:0,y:12}]}},am=buildDeckTakeoff(angled),af=am.levels[0].footprint,as=screen(edgeSectionId(af,1)),ad={...angled,privacyScreens:[as]},ah=extrasLayout(ad,buildDeckTakeoff(ad)).screenHandles[0];near(ah.angle,-Math.atan2(144,48),'Screen follows arbitrary physical edge angle');near(screenOffsetFromPoint(ah,ah.x+ah.edge.dx*20,ah.z+ah.edge.dz*20)!,Math.round(20/(ah.edge.available-ah.w)*100),'Diagonal screen inverse follows its actual axis');
const missing={...base,privacyScreens:[screen('edge:missing')]},mx=extrasLayout(missing,buildDeckTakeoff(missing));eq(mx.screenHandles.length,0,'Stale screen ID never falls back to a longest side');ok(mx.warnings.some(w=>w.includes('matching exposed saved edge')),'Missing exact edge is visible as an actionable warning');
const stairData={...withStairs,privacyScreens:[{...screen(edgeSectionId(fp,2)),lengthFt:16}]},sx=extrasLayout(stairData,buildDeckTakeoff(stairData));eq(sx.screenHandles.length,0,'Exact screen cannot cover a real stair opening');ok(sx.warnings.some(w=>w.includes('opening')),'Actual stair obstruction is reported');
const mainMulti=buildDeckTakeoff(multi),second=mainMulti.levels.find(l=>l.kind==='deck'&&l.index===1)!,connectionScreen={...multi,privacyScreens:[{...screen(edgeSectionId(second.footprint,0),2),lengthFt:8}]},connectionDraw=extrasLayout(connectionScreen,buildDeckTakeoff(connectionScreen));eq(connectionDraw.screenHandles.length,0,'Lower-level screen cannot cover its actual incoming connection opening');ok(connectionDraw.warnings.some(w=>w.includes('opening')),'Incoming connection is reported explicitly');
const collision={...base,privacyScreens:[screen(edgeSectionId(fp,1)),{...screen(edgeSectionId(fp,1)),id:'other'}]},cx=extrasLayout(collision,buildDeckTakeoff(collision));eq(cx.screenHandles.length,1,'Colliding exact screens do not double-draw');ok(cx.warnings.some(w=>w.includes('another screen')),'Screen collision is visible');
const privacyItem=(p:ReturnType<typeof calculateEstimate>)=>p.sections.flatMap(s=>s.items).find(i=>i.name==='Privacy Screen')??{qty:0,cost:0};
const removedRequest={...screen(edgeSectionId(second.footprint,1),2),lengthFt:1},inactive:DeckData={...base,privacySqft:6,privacyScreens:[removedRequest],lightingSystem:{wireDistance:40,selectedItems:[{productId:'blink',qty:2,zone:'privacy',auto:true},{productId:'hub100',qty:1,auto:true}]}},inactiveBefore=JSON.stringify(inactive),inactivePrice=calculateEstimate(inactive);
eq(privacyItem(inactivePrice).qty,0,'Removed-level exact screen contributes zero priced face area');eq(privacyItem(inactivePrice).cost,0,'Removed-level exact screen has no invisible material charge');eq(inactivePrice.total,calculateEstimate({...base,privacySqft:0,lightingSystem:{wireDistance:0,selectedItems:[]}}).total,'Inactive lit screen has no hidden fixture/transformer/wire cost');ok(inactivePrice.flags.some(f=>f.includes('inactive')&&f.includes('excluded')),'Estimate visibly reports retained inactive settings');eq(JSON.stringify(inactive),inactiveBefore,'Costing does not mutate requested screen/lighting settings');
const restored={...multi,privacySqft:6,privacyScreens:[removedRequest]},restoredPrice=calculateEstimate(restored);eq(privacyItem(restoredPrice).qty,6,'Restoring the exact level restores its requested face area');ok(privacyItem(restoredPrice).cost!>0,'Restored screen receives its unchanged existing allowance');eq(extrasLayout(restored,buildDeckTakeoff(restored)).screenHandles.length,1,'Restore returns physical screen placement');
for(const d of [missing,{...base,privacyScreens:[{...screen(edgeSectionId(fp,1)),lengthFt:20}]},collision,stairData,connectionScreen]){const p=calculateEstimate(d),drawn=extrasLayout(d,p.model),actual=d.privacyScreens.filter(s=>drawn.screenHandles.some(h=>h.id===s.id)).reduce((n,s)=>n+s.lengthFt*s.heightFt,0);eq(privacyItem(p).qty,actual,'Missing, oversized, colliding or blocked exact screens price only actual handles');ok(p.flags.some(f=>f.includes('inactive')&&f.includes('excluded')),'Each rejected exact placement surfaces in estimate flags');}
const manufacturer=PRIVACY_PRODUCTS.find(p=>p.id==='hideaway')!,panel:PrivacyScreen={...removedRequest,product:'hideaway',panels:1,design:manufacturer.designs[0],finish:'Black'},panelInactive={...base,privacyScreens:[panel]},panelPrice=calculateEstimate(panelInactive);ok(!panelPrice.quoteRequired.some(q=>q.includes(manufacturer.name)),'Unavailable exact manufacturer screen adds no supplier-quote scope');ok(!panelPrice.sections.flatMap(s=>s.items).some(i=>i.name==='Manufacturer privacy screen'),'Inactive stock screen has no hidden quote row');ok(calculateEstimate({...multi,privacyScreens:[panel]}).quoteRequired.some(q=>q.includes(manufacturer.name)),'Restoring the level restores its exact manufacturer quote request');
const manualLight=calculateEstimate({...inactive,lightingSystem:{wireDistance:40,selectedItems:[{productId:'blink',qty:2,zone:'privacy'}]}});eq(manualLight.total,calculateEstimate({...base,privacySqft:0,lightingSystem:{wireDistance:0,selectedItems:[]}}).total,'Manual privacy fixtures with no actual mounts are excluded while settings remain available for restore');
const legacy:PrivacyScreen={id:'legacy',side:'Right',lengthFt:4,heightFt:6,offsetPct:30,lights:true},ld={...base,privacyScreens:[legacy]},lx=extrasLayout(ld,buildDeckTakeoff(ld)),legacyLevel={...ld,privacyScreens:[{...legacy,level:1 as const}]};eq(extrasLayout(legacyLevel,buildDeckTakeoff(legacyLevel)),lx,'Legacy side placement is unchanged by explicit main-level default');eq(lx.screenHandles[0].edge.clearanceIn,undefined,'Legacy handles retain their exact schema');eq(screenOffsetFromPoint(lx.screenHandles[0],lx.screenHandles[0].x,lx.screenHandles[0].z),30,'Legacy reversed-side drag retains the original clearance/inverse');
console.log(`Deck edge sections: ${checks} geometry, eligible-opening, levels, posts, prices, persistence and strict-input assertions passed.`);
}
main().catch(error=>{console.error(error);process.exit(1);});
