import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {DESIGN_STORAGE_KEY,serializeDesign} from '../src/features/deckcraft/designPersistence';
import {DECK_RELEASE_STORAGE_KEY,deckReleaseData,parseDeckReleaseDesign,serializeDeckReleaseDesign,calculateDeckReleaseEstimate,exportDeckReleaseDXF,exportDeckReleaseOBJ} from '../src/features/deckcraft/deckRelease';
import type {DeckData} from '../src/features/deckcraft/types';
const combined:DeckData={...structuredClone(DEFAULT_DECK),terrainConfig:{widthFt:80,depthFt:80,elevationIn:10,slopePct:5},yardFeatures:[{id:'old-patio',kind:'patio',name:'Deferred patio',enabled:true,xFt:10,zFt:30,widthFt:20,depthFt:20,heightIn:0,rotationDeg:0,productId:'permacon-melville',color:'#aaaaaa'}]};
const snapshot=structuredClone(combined),clean=deckReleaseData(combined),base=calculateDeckReleaseEstimate(DEFAULT_DECK),released=calculateDeckReleaseEstimate(combined);
assert.deepEqual(combined,snapshot,'Source combined design is preserved without mutation');
assert(!('yardFeatures' in clean)&&!('terrainConfig' in clean));
assert.notEqual(DECK_RELEASE_STORAGE_KEY,DESIGN_STORAGE_KEY,'New autosave cannot overwrite preserved combined autosave');
assert.equal(released.total,base.total,'Deferred hardscape and terrain never affect release pricing');
assert.equal(released.yardModel.features.length,0);
assert(!released.sections.some(s=>s.title.startsWith('Yard')));
assert.deepEqual(parseDeckReleaseDesign(serializeDesign(combined)),clean,'Older combined files import deck-only');
assert.equal(deckReleaseData({...combined,projectKind:'hardscape',hsProduct:'old-paver'}).projectKind,'deck');
assert(!('hsProduct' in deckReleaseData({...combined,hsProduct:'old-paver'})));
assert(!serializeDeckReleaseDesign(combined).includes('yardFeatures'));
for(const text of [exportDeckReleaseOBJ(combined,released.model),exportDeckReleaseDXF(combined,released.model)])assert(!text.includes('yard_'),'Released exports exclude deferred yard meshes');
const page=readFileSync(new URL('../src/pages/DeckDesigner.tsx',import.meta.url),'utf8');
assert(page.includes('deckRelease'),'Public page uses the release boundary');
assert(!page.includes('<YardEditor'),'Deferred authoring is absent from the public workflow');
console.log('Deck-only release: preserved legacy designs, isolated pricing/terrain, clean import/save/exports and public workflow checks passed.');
