import {createQuoteAwarePricingReceiver} from '../src/features/deckcraft/designer/quoteAwarePricingReceiver';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateEstimate} from '../src/features/deckcraft/calculations';
import {designExtensionsReady,ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {inlayGeometryReady,validateCustomInlayPoints,validateDeckInlay} from '../src/features/deckcraft/lib/inlayGeometry';
import {parseDeckReleaseDesign,serializeDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {priceOption} from '../src/features/deckcraft/designer/optionPricing';
import type {DeckData} from '../src/features/deckcraft/types';
let checks=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;};
const base={...DEFAULT_DECK,width:20,length:16},inlay={id:'rug-1',kind:'rug' as const,widthFt:6,depthFt:4},design:DeckData={...base,inlays:[inlay]};
ok(!inlayGeometryReady(),'Cold process has no decorative geometry runtime');
ok(designExtensionsReady(base)&&Number.isFinite(calculateEstimate(base).total),'Plain initial estimate is synchronous and complete');
await ensureLiveDesignExtensions(base);ok(!inlayGeometryReady(),'Preparing a plain design never loads decorative engine');
assert.deepEqual(validateDeckInlay(inlay),inlay);checks++;
ok(validateCustomInlayPoints([{x:0,y:0},{x:12,y:0},{x:12,y:12}]).length===3,'Patio polygon validation remains eager');
assert.throws(()=>calculateEstimate(design),/inlay geometry is not loaded/);checks++;
let reads=0;const guarded={};Object.defineProperty(guarded,'inlays',{get(){reads++;return [inlay];}});await ensureLiveDesignExtensions(guarded);ok(!reads&&!inlayGeometryReady(),'Presence detection never invokes an accessor');
const saved=serializeDeckReleaseDesign(design);
let delivered=0,loads=0;const receiver=createQuoteAwarePricingReceiver(()=>{delivered++;},async data=>{loads++;await ensureLiveDesignExtensions(JSON.parse(serializeDeckReleaseDesign(data)));},()=>assert.fail('Inlay preparation unexpectedly failed'));
receiver({job:1,data:base,items:[{key:'base',patch:{}}]});ok(delivered===1&&loads===0,'Worker prices plain design without optional loading');
receiver({job:2,data:design,items:[{key:'inlay',patch:{}}]});ok(delivered===1&&loads===1,'Worker delays inlay estimate until runtime is ready');
await ensureLiveDesignExtensions(JSON.parse(saved));await new Promise(r=>setTimeout(r,0));ok(delivered===2,'Worker resumes after inlay preparation');
ok(inlayGeometryReady()&&designExtensionsReady(design),'Saved inlay prepares before synchronous calculation');
const restored=parseDeckReleaseDesign(saved),estimate=calculateEstimate(restored);
ok(estimate.model.levels.some(l=>l.inlays?.some(p=>p.id===inlay.id&&p.status==='ok'&&p.boards.length>0)),'Restored inlay generates actual framed boards');
const worker=priceOption(restored,{});ok(Math.abs(worker.total-estimate.total)<.01,'Prepared worker pricing agrees with main estimate');
console.log(`${checks} cold inlay runtime checks passed.`);
