import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import sharp from 'sharp';
import * as THREE from 'three';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {LANDSCAPE_ASSETS,LANDSCAPE_SPECIES,newLandscapeObject,landscapeAsset} from '../src/features/deckcraft/landscapeCatalogue';
import {validateLandscapeObjects,validLandscapePolygon,validateLandscapeSpecies,type LandscapeObject} from '../src/features/deckcraft/landscapeTypesRuntime';
import {landscapeTakeoff,landscapeBedAreas,landscapePlacement,landscapeRenderLods,matureSpreadConflicts} from '../src/features/deckcraft/landscapeModelRuntime';
import {landscapeBedGeometry,landscapeInstanceMatrix} from '../src/features/deckcraft/components/viewer3d/Landscape3D';
import {stillSize,captureSceneStill} from '../src/features/deckcraft/components/viewer3d/SceneStillExport';
import type {DeckData} from '../src/features/deckcraft/types';
let checks=0;const check=(v:unknown,label?:string)=>{assert.ok(v,label);checks++;},close=(a:number,b:number)=>check(Math.abs(a-b)<1e-5,`${a} ≈ ${b}`);
const all=LANDSCAPE_ASSETS.map((a,i)=>newLandscapeObject(a.id,'object-'+i));check(validateLandscapeObjects(all));check(validateLandscapeObjects([]));check(!validateLandscapeObjects(undefined));
for(const invalid of [[...all,all[0]],Array(2),[{...all[0],xIn:NaN}],[{...all[0],widthIn:0}],[{...all[0],assetId:'unknown'}],[{...all[0],kind:'bed'}],[{...all[0],cost:1}],[{...all[0],name:' '}],[{...all[0],edging:true}],[{...all[0],speciesRecord:{...LANDSCAPE_SPECIES[0],sourceURL:'javascript:alert(1)'}}]])check(!validateLandscapeObjects(invalid));
let getterRead=false;const getter={...all[0]};Object.defineProperty(getter,'xIn',{enumerable:true,get(){getterRead=true;return 0;}});check(!validateLandscapeObjects([getter])&&!getterRead);
check(!validateLandscapeObjects([Object.create(all[0])]));const symbolObject={...all[0],[Symbol('secret')]:1};check(!validateLandscapeObjects([symbolObject]));
for(const s of LANDSCAPE_SPECIES){check(validateLandscapeSpecies(s));check(!s.spacingIn,'Mature spread is not inferred planting spacing');}
check(!validateLandscapeSpecies({...LANDSCAPE_SPECIES[0],spacingIn:36}));check(validateLandscapeSpecies({...LANDSCAPE_SPECIES[0],spacingIn:36,spacingSourceURL:'https://example.org/source'}));
const square=[{x:0,z:0},{x:120,z:0},{x:120,z:120},{x:0,z:120}];check(validLandscapePolygon(square));check(validLandscapePolygon([...square].reverse()));check(!validLandscapePolygon([square[0],square[2],square[1],square[3]]));check(!validLandscapePolygon([...square,square[0]]));
const a={...newLandscapeObject('mulch-bed','a',0,0),widthIn:120,depthIn:120,mulchDepthIn:2,edging:true},b={...a,id:'b',xIn:60,mulchDepthIn:4};
const overlap=landscapeTakeoff([a,b]);close(overlap.bedAreaSqft,150);close(overlap.mulchYd3,(50*2+100*4)/324);close(overlap.edgingLf,60);close(overlap.items.reduce((n,i)=>n+i.edgingLf,0),overlap.edgingLf);check(overlap.warnings.length===1);
const nested=landscapeTakeoff([{...a,widthIn:240,depthIn:240},{...b,xIn:0}]);close(nested.bedAreaSqft,400);close(nested.edgingLf,120);
const adjacent=landscapeTakeoff([a,{...b,xIn:120}]);close(adjacent.bedAreaSqft,200);close(adjacent.edgingLf,70);
const disabled=landscapeTakeoff([a,{...b,enabled:false},...all.filter(o=>o.kind!=='bed')]);close(disabled.bedAreaSqft,100);check(disabled.plantCount===5&&disabled.boulderCount===1&&disabled.furnitureCount===LANDSCAPE_ASSETS.filter(a=>a.kind==='furniture').length);check(disabled.items.every(i=>i.quoteRequired));
const custom={...a,polygon:[...square].reverse()},saved=JSON.stringify(custom);landscapeBedAreas([custom]);landscapeTakeoff([custom]);check(JSON.stringify(custom)===saved,'Takeoff does not reverse or mutate canonical points');
const data={...DEFAULT_DECK,terrainConfig:{widthFt:80,depthFt:80,elevationIn:12,slopePct:10}} as DeckData,p={...all[0],xIn:60,zIn:120};const legacy=landscapePlacement(data,p);close(legacy.y,2);check(!legacy.measured);
const measured={...data,siteModel:{version:1,points:[{id:'p0',xIn:0,zIn:0,elevationIn:0},{id:'p1',xIn:240,zIn:0,elevationIn:24},{id:'p2',xIn:0,zIn:240,elevationIn:48},{id:'p3',xIn:240,zIn:240,elevationIn:72}],grading:[]}} as DeckData;
const placement=landscapePlacement(measured,p);close(placement.y,2.5);check(placement.measured);check(!landscapePlacement(measured,{...p,xIn:1000}).measured);
const bed={...a,xIn:120,zIn:120,widthIn:120,depthIn:120},geometry=landscapeBedGeometry(measured,landscapeBedAreas([bed]).get(bed.id)!,3),pos=geometry.getAttribute('position');check(pos.count>0);
for(let i=0;i<pos.count;i++){close(pos.getY(i),(pos.getX(i)*12*.1+pos.getZ(i)*12*.2+3.05)/12);check(geometry.getAttribute('normal').getY(i)>0);}geometry.dispose();
const norm=new THREE.Matrix4().makeScale(.5,.25,1/6),matrix=landscapeInstanceMatrix(measured,{...p,heightIn:48,widthIn:24,depthIn:72,rotationDeg:0},norm,new THREE.Matrix4()),low=new THREE.Vector3(-1,0,-3).applyMatrix4(matrix),high=new THREE.Vector3(1,4,3).applyMatrix4(matrix);close(high.x-low.x,2);close(high.y-low.y,4);close(high.z-low.z,6);close(low.y,placement.y);
const plants=[{...p,id:'m0',speciesRecord:LANDSCAPE_SPECIES[0]},{...p,id:'m1',xIn:p.xIn+120,speciesRecord:LANDSCAPE_SPECIES[0]}];check(matureSpreadConflicts(plants).length===1);check(matureSpreadConflicts(plants.map((o,i)=>i?{...o,xIn:2000}:o)).length===0);
const dense=Array.from({length:300},(_,i)=>({...newLandscapeObject('deciduous-tree','tree-'+i),xIn:(i%20)*120,zIn:Math.floor(i/20)*120}));
for(const tier of ['high','balanced','constrained'] as const){const lods=landscapeRenderLods(dense,{x:0,y:4,z:0},900,tier);check(lods.size===300);const base=300*landscapeAsset('deciduous-tree').triangleCounts![2],total=dense.reduce((n,o)=>n+landscapeAsset(o.assetId).triangleCounts![lods.get(o.id)!],0);check(total<=base+(tier==='high'?800000:tier==='balanced'?120000:0));if(tier==='constrained')check([...lods.values()].every(lod=>lod===2));}
assert.deepEqual(stillSize(2048,{x:1500,y:900},8192),{width:2048,height:1229});checks++;assert.deepEqual(stillSize(4096,{x:390,y:390},8192),{width:4096,height:4096});checks++;assert.deepEqual(stillSize(4096,{x:100,y:400},8192),{width:1024,height:4096});checks++;assert.deepEqual(stillSize(4096,{x:400,y:100},8192),{width:4096,height:1024});checks++;assert.throws(()=>stillSize(4096,{x:100,y:400},2048));checks++;assert.throws(()=>stillSize(4096,{x:NaN,y:400},8192));checks++;
// Deliberate PNG failure after resizing must restore renderer/camera/selection.
const scene=new THREE.Scene(),outline=new THREE.Object3D();outline.name='picked-wall-outline';scene.add(outline);const camera=new THREE.PerspectiveCamera(38,1.5,.1,1000);let pixelRatio=1.5,size=new THREE.Vector2(600,400),scissorTest=true,rendered=0;
const gl={capabilities:{maxTextureSize:8192},getContext:()=>({MAX_RENDERBUFFER_SIZE:1,getParameter:()=>8192}),getSize:(v:THREE.Vector2)=>v.copy(size),getDrawingBufferSize:(v:THREE.Vector2)=>v.set(size.x*pixelRatio,size.y*pixelRatio),getPixelRatio:()=>pixelRatio,getViewport:(v:THREE.Vector4)=>v.set(1,2,3,4),getScissor:(v:THREE.Vector4)=>v.set(5,6,7,8),getScissorTest:()=>scissorTest,getRenderTarget:()=>null,getClearColor:(c:THREE.Color)=>c.set('#abc'),getClearAlpha:()=>1,autoClear:true,toneMapping:THREE.NeutralToneMapping,toneMappingExposure:1,shadowMap:{autoUpdate:false},setPixelRatio:(n:number)=>{pixelRatio=n;},setSize:(x:number,y:number)=>{size.set(x,y);},setScissorTest:(n:boolean)=>{scissorTest=n;},setRenderTarget:()=>{},setViewport:()=>{},setScissor:()=>{},setClearColor:()=>{},render:()=>{rendered++;},domElement:{toBlob:(fn:(b:null)=>void)=>fn(null)}} as unknown as THREE.WebGLRenderer;
await assert.rejects(()=>captureSceneStill(gl,scene,camera,2048));checks++;close(pixelRatio,1.5);close(size.x,600);close(size.y,400);close(camera.aspect,1.5);check(outline.visible&&scissorTest&&rendered===2);
const manifest=JSON.parse(readFileSync('public/deckcraft/landscape/manifest.json','utf8'));check(manifest.assets.length===7);const furnitureManifest=JSON.parse(readFileSync('public/deckcraft/landscape/original-furniture-manifest.json','utf8'));check(furnitureManifest.assets.length===3);let bytes=0,alphaTextures=0;
for(const asset of manifest.assets){check(asset.license==='CC0-1.0'&&asset.sourceURL.startsWith('https://polyhaven.com/a/'));check(asset.lods.length===3);
 for(const lod of asset.lods){const binary=readFileSync('public/deckcraft/landscape/'+lod.uri);bytes+=binary.length;check(createHash('sha256').update(binary).digest('hex')===lod.sha256);check(binary.readUInt32LE(0)===0x46546c67&&binary.readUInt32LE(4)===2&&binary.readUInt32LE(8)===binary.length);const jsonLength=binary.readUInt32LE(12),json=JSON.parse(binary.subarray(20,20+jsonLength).toString('utf8')),bin=binary.subarray(28+jsonLength);check((json.extensionsRequired??[]).every((x:string)=>x==='KHR_mesh_quantization'||x==='KHR_texture_transform'||x==='EXT_meshopt_compression'));
  const tris=json.meshes.reduce((n:number,m:{primitives:{indices:number}[]})=>n+m.primitives.reduce((s,p)=>s+json.accessors[p.indices].count/3,0),0);close(tris,lod.triangles);
  if(asset.id==='deciduous-tree'){check(lod.foliage[0].originalIslands===30250);check(lod.foliage[0].retainedIslands>=[30000,15000,3700][asset.lods.indexOf(lod)],'Deciduous canopy islands remain distributed at every LOD');}
  if(asset.id==='conifer-tree'){check(asset.selectedSourceNode===1,'Fuller original fir B selected');check(lod.foliage[0].canopyClusters>=[1900,780,270][asset.lods.indexOf(lod)],'Original needle cells preserve canopy volume');check(lod.foliage[0].photographedTwigSprites.length===6,'Twig cutouts use six source photograph regions');}
  for(const img of json.images){const v=json.bufferViews[img.bufferView],image=bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength),meta=await sharp(image).metadata();check(meta.width!<=lod.textureLimit&&meta.height!<=lod.textureLimit);}
  for(const material of json.materials.filter((m:{alphaMode?:string})=>m.alphaMode==='MASK')){const img=json.images[json.textures[material.pbrMetallicRoughness.baseColorTexture.index].source],v=json.bufferViews[img.bufferView],image=bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength),meta=await sharp(image).metadata();check(meta.hasAlpha);const stats=await sharp(image).extractChannel('alpha').stats();check(stats.channels[0].min<30&&stats.channels[0].max>240);alphaTextures++;}
 }
}
for(const asset of furnitureManifest.assets){for(const lod of asset.lods){const binary=readFileSync('public/deckcraft/landscape/'+lod.uri);check(createHash('sha256').update(binary).digest('hex')===lod.sha256);const json=JSON.parse(binary.subarray(20,20+binary.readUInt32LE(12)).toString('utf8'));close(json.meshes.reduce((n:number,m:{primitives:{indices?:number;attributes:{POSITION:number}}[]})=>n+m.primitives.reduce((t,p)=>t+json.accessors[p.indices??p.attributes.POSITION].count/3,0),0),lod.triangles);}}
check(bytes<14000000);check(alphaTextures>=12);
for(const asset of LANDSCAPE_ASSETS.filter(a=>a.modelURL)){const found=[...manifest.assets,...furnitureManifest.assets].find((x:{id:string})=>x.id===(asset.id==='hedge-shrub'?'rounded-shrub':asset.id));check(!!found);for(let i=0;i<3;i++)close(found.lods[i].triangles,asset.triangleCounts![i]);}
let verifiedOriginals=0;for(const record of manifest.originalDownloads){const file=resolve('../..',record.file);if(existsSync(file)){check(createHash('sha256').update(readFileSync(file)).digest('hex')===record.sha256);verifiedOriginals++;}}
console.log(JSON.stringify({checks,assets:manifest.assets.length,lods:manifest.assets.length*3,glbBytes:bytes,alphaTextures,verifiedOriginals,maxObjects:300,bedOverlap:'last enabled bed; shared edging counted once',stillFailureRestored:true},null,2));
