/** Explicit local-only integration check: invokes the installed model; never sends a customer design. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {buildAssistantContext,assistantPlanRequest} from '../src/features/deckcraft/designer/assistantPlan';
import {createDeckAssistantService,DECK_ASSISTANT_PATH} from '../server/deckAssistantBackend';
import type {DeckData} from '../src/features/deckcraft/types';
const model=process.argv.find(v=>v.startsWith('--model='))?.slice(8)??'qwen3:14b';
let lastModelReply:unknown=null;
const service=createDeckAssistantService({ollamaUrl:'http://127.0.0.1:11434',model,fetch:async(input,init)=>{const response=await fetch(input,init);if(String(input).endsWith('/api/chat'))lastModelReply=await response.clone().json();return response;}});
let data:DeckData=structuredClone(DEFAULT_DECK);const history:DeckData[]=[];
const state=()=>({data,estimate:calculateDeckReleaseEstimate(data),view:'plan',openSections:['deck'],canUndo:history.length>0,canRedo:false,ready:true} as DeckAgentHostState);
const controller=createDeckAgentController({getState:state,commitDesign:next=>{history.push(data);data=next;},undo:()=>{data=history.pop()!;},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async test=>assert.ok(test(state()))});
const records:any[]=[];
async function ask(prompt:string,conversation:{role:'user'|'assistant';content:string}[]=[]){const before=JSON.stringify(data),started=Date.now(),snapshot=controller.read();lastModelReply=null;const response=await service.handle(new Request('http://127.0.0.1:4319'+DECK_ASSISTANT_PATH,{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://127.0.0.1:4319'},body:JSON.stringify({prompt,context:buildAssistantContext(snapshot),conversation})}));const result=await response.json() as any;const record={prompt,conversation,model,status:response.status,durationMs:Date.now()-started,result,modelReply:lastModelReply,preview:null as unknown};records.push(record);persist();assert.equal(response.status,200,JSON.stringify(result));assert.equal(result.source,'local-ai');assert.equal(JSON.stringify(data),before,'Actual model inference has no design writes');return {result,snapshot,record};}
function persist(){const dir=resolve(process.cwd(),'../../outputs');mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,'deckcraft-assistant-real-model.json'),JSON.stringify({model,localOnly:true,mocked:false,records},null,2)+'\n');}
try{
 const wider=await ask('Give the main deck a little more width, keeping the depth the same.');assert.equal(wider.result.plan.kind,'edit');assert.ok(wider.result.plan.assumptions.length>0,'Vague magnitude must be explained');const request=assistantPlanRequest(wider.result.plan,{id:'local-ai-width',expectedRevision:wider.snapshot.revision});const preview=await controller.preview(request);wider.record.preview=preview;persist();assert.ok(preview.ok,JSON.stringify(preview));if(preview.ok){assert.ok(preview.snapshot.design.width>wider.snapshot.design.width&&preview.snapshot.design.width<=wider.snapshot.design.width*1.5,'Little wider yields modest real width change');assert.equal(preview.snapshot.design.length,wider.snapshot.design.length,'Keeps requested depth');const applied=await controller.execute(request);assert.ok(applied.ok);if(applied.ok)assert.equal(applied.snapshot.pricing.total,preview.snapshot.pricing.total);assert.equal(history.length,1);await controller.execute({id:'local-ai-undo',commands:[{type:'history.undo'}]});assert.equal(data.width,DEFAULT_DECK.width);}
 const ambiguous=await ask('Move it to the other side.');assert.equal(ambiguous.result.plan.kind,'clarify','No selected object or destination must ask for a target');assert.equal(ambiguous.result.plan.commands.length,0);
 const privacyPrompt='I want more privacy along the left side of my main deck. Add a screen there.';let privacy=await ask(privacyPrompt);if(privacy.result.plan.kind==='clarify')privacy=await ask('Use a five-foot-high screen along the entire left edge.',[{role:'user',content:privacyPrompt},{role:'assistant',content:privacy.result.plan.question}]);assert.equal(privacy.result.plan.kind,'edit','Concrete clarification must resolve to an edit');const p=await controller.preview(assistantPlanRequest(privacy.result.plan,{id:'local-ai-privacy',expectedRevision:privacy.snapshot.revision}));privacy.record.preview=p;persist();assert.ok(p.ok,JSON.stringify(p));if(p.ok)assert.ok((p.snapshot.design.privacyScreens?.length??0)>(privacy.snapshot.design.privacyScreens?.length??0)||p.snapshot.design.privacySqft>privacy.snapshot.design.privacySqft,'Model actually adds a screen');
 const unspecified='Add a privacy screen somewhere on the deck.';const question=await ask(unspecified);assert.equal(question.result.plan.kind,'clarify','Unspecified screen target must ask');const followup=await ask('Along the entire left edge of the main deck, five feet tall.',[{role:'user',content:unspecified},{role:'assistant',content:question.result.plan.question}]);assert.equal(followup.result.plan.kind,'edit','Real follow-up resolves into a concrete screen plan');const resolved=await controller.preview(assistantPlanRequest(followup.result.plan,{id:'local-ai-followup',expectedRevision:followup.snapshot.revision}));followup.record.preview=resolved;persist();assert.ok(resolved.ok,JSON.stringify(resolved));if(resolved.ok)assert.ok((resolved.snapshot.design.privacyScreens?.length??0)>(followup.snapshot.design.privacyScreens?.length??0),'Resolved conversation adds actual screen geometry');
 console.log(`Real local model ${model}: width edit and exact priced Apply/Undo, ambiguous clarification, and privacy screen preview passed (${records.length} requests; no cloud calls).`);
}finally{persist();controller.dispose();}
