import {quoteScopeReview} from '../src/features/deckcraft/designer/quoteReviewModel';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {jsPDF} from 'jspdf';
import {mkdirSync,writeFileSync} from 'node:fs';
import {buildProposalPdf} from '../src/features/deckcraft/proposalPdf';
import {ProposalSheet} from '../src/features/deckcraft/ProposalSheet';
import {describeDesign} from '../src/features/deckcraft/designFacts';
import {estimateKeyOf} from '../src/features/deckcraft/designer/useDeckEstimate';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {confirmQuoteScope,validateQuoteResolutions} from '../src/features/deckcraft/quoteResolutionValidation';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate,deckReleaseData,serializeDeckReleaseDesign,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {buildQuoteScopes} from '../src/features/deckcraft/quoteResolutions';
import {emptyJobLibrary,saveJobRevision,exportJobLibrary,parseJobText,revisionRestoreDesign,cleanJobDesign} from '../src/features/deckcraft/designer/jobRevisionLibrary';
import {DECKING_CATALOGUE,RAILING_CATALOGUE} from '../src/features/deckcraft/manufacturerCatalog';
import {LIGHTING_CATALOGUE} from '../src/features/deckcraft/lightingCatalogue';
import {priceLedger} from '../src/features/deckcraft/designer/priceLedgerModel';
import type {DeckData} from '../src/features/deckcraft/types';
let count=0;const check=(v:unknown,s:string)=>{assert.ok(v,s);count++;};const reject=(f:()=>unknown)=>{assert.throws(f);count++;};const near=(a:number,b:number,s:string)=>check(Math.abs(a-b)<1e-7,s);
const base=deckReleaseData({...structuredClone(DEFAULT_DECK),materialMarkup:20,customerName:'TEST AMOUNTS ONLY',deckOutlines:{main:[{x:0,y:0},{x:16,y:0},{x:16,y:12},{x:0,y:12}]}});
const e=calculateDeckReleaseEstimate(base),scopes=quoteScopeReview(base,e).scopes;check(scopes.length>0,'Actual custom outline has builder scope');const scope=scopes.find(s=>s.name==='Custom outline construction')!;check(!!scope,'Explicit construction row binds one scope');const entry=confirmQuoteScope(scope,{supplyCost:100,installationCost:250,confirmedOn:'2026-09-26',source:'Private Builder Q-123',note:'Additional angled support only; base framing excluded.'}),priced={...base,quoteResolutions:[entry]},p=calculateDeckReleaseEstimate(priced);
near(p.subtotal-e.subtotal,370,'Supply markup20% plus unmarked installation exactly once');near(p.hst-e.hst,48.1,'HST once on actual additional subtotal');near(p.total-e.total,418.1,'Exact total difference');check(!p.quoteRequired.includes(scope.labels[0]),'Only covered quote removed');check(p.quoteResolutionReview?.active.includes(scope.key),'Current fingerprint is active');check(p.sections.some(s=>s.title==='Confirmed additional quote costs'&&s.total===370),'Single priced ledger scope');check(p.sections.flatMap(s=>s.items).some(i=>i.quoteResolved&&i.cost===null),'Preserves null quantities without fake zero');check(priceLedger(p).lines.find(l=>l.title==='Custom outline construction')?.text==='Included in confirmed scope','Proposal ledger identifies coverage');check(!priceLedger(p).quotes.some(q=>scope.labels.includes(q.label)),'Proposal quotes exactly reflect resolution');check(JSON.stringify(p.sections).indexOf('Private Builder')<0,'Supplier source absent public customer ledger');check(JSON.stringify(p.sections).indexOf('Additional angled support only')<0,'Private note absent customer ledger');
check(JSON.stringify(calculateDeckReleaseEstimate({...base,quoteResolutions:[]}))===JSON.stringify(e),'Absent/empty records unchanged legacy output');check(JSON.stringify(calculateDeckReleaseEstimate(priced))===JSON.stringify(p),'Calculation deterministic; no mutation');check(!Object.hasOwn(base,'quoteResolutions'),'Original design untouched');
for(const change of [{width:18,deckOutlines:undefined},{height:72},{deckingMaterial:'cedar'},{materialMarkup:30},{stairWidth:72},{foundation:'Helical Piles'}]){const next={...priced,...change} as DeckData,result=calculateDeckReleaseEstimate(next),without=calculateDeckReleaseEstimate({...next,quoteResolutions:undefined});near(result.total,without.total,'Changed geometry/product/cost basis excludes record');check(result.quoteResolutionReview?.inactive===1,'Retains inactive confirmation');check(result.flags.some(f=>f.includes('inactive')),'Inactive warning visible');}
const personal=calculateDeckReleaseEstimate({...priced,customerName:'New private name',projectAddress:'New site'});near(personal.total,e.total,'Different job/contact invalidates private quote');const view=calculateDeckReleaseEstimate({...priced,sceneLighting:'Evening'});near(view.total,p.total,'View changes do not invalidate scope');near(calculateDeckReleaseEstimate(priced).total,p.total,'Undo to exact design reactivates saved scoped cost');check(!JSON.stringify(p.sections).includes('1.200'),'Private markup factor absent customer ledger');
reject(()=>validateQuoteResolutions([entry,entry]));for(const patch of [{supplyCost:NaN},{installationCost:Infinity},{supplyCost:-1},{supplyCost:0.001},{supplyCost:1_000_001},{supplyCost:0,installationCost:0},{confirmedOn:'2026-02-30'},{source:''},{note:''},{additionalScope:false},{unknown:1},{scopeKey:'constructor'},{fingerprint:'oops'}])reject(()=>validateQuoteResolutions([{...entry,...patch}]));let read=false;const getter={...entry};Object.defineProperty(getter,'source',{get(){read=true;return 'source';},enumerable:true});reject(()=>validateQuoteResolutions([getter]));check(!read,'Accessor is not executed');const sparse=[entry];delete sparse[0];reject(()=>validateQuoteResolutions(sparse));reject(()=>validateQuoteResolutions([Object.assign(Object.create({bad:1}),entry)]));reject(()=>validateQuoteResolutions(Array(101).fill(entry)));reject(()=>validateQuoteResolutions([{...entry,source:'a'.repeat(161)}]));reject(()=>validateQuoteResolutions([{...entry,note:'a'.repeat(1001)}]));
const publicText=serializeDeckReleaseDesign(priced);check(!publicText.includes('quoteResolutions')&&!publicText.includes('Private Builder'),'Public file/autosave excludes private records');const attack=JSON.parse(publicText);attack.configuration.quoteResolutions=[entry];reject(()=>parseDeckReleaseDesign(JSON.stringify(attack)));
const library=saveJobRevision(emptyJobLibrary(),priced,'Private job','Confirmed'),rev=library.jobs[0].revisions[0];check(rev.data.quoteResolutions?.[0].source==='Private Builder Q-123','Private job revision preserves evidence');const restored=revisionRestoreDesign(rev,{...structuredClone(DEFAULT_DECK),materialMarkup:20});check(restored.quoteResolutions?.[0].source===entry.source,'Restores selected job scoped records independently of saved rates');near(calculateDeckReleaseEstimate(restored).total,p.total,'Exact restored estimate with same rates');const portable=exportJobLibrary(library);check(!portable.includes('quoteResolutions')&&!portable.includes('Private Builder'),'Portable job excludes private evidence');check(!parseJobText(portable).jobs[0].revisions[0].data.quoteResolutions,'Imported portable has no records');reject(()=>cleanJobDesign({...base,quoteResolutions:[{...entry,unknown:1}]}));
// Every row group charges one bundle; multiple quote labels never create duplicate scope charges.
const samples:DeckData[]=[...DECKING_CATALOGUE.filter(m=>m.costPerSqft===null).map(m=>({...base,deckingMaterial:m.id,deckingColor:m.colors[0].name})),...RAILING_CATALOGUE.map(r=>({...base,catalogueRailingId:r.id,railingType:r.baseType})),...LIGHTING_CATALOGUE.filter(p=>p.supported&&p.cost!==null&&p.laborCost===null).slice(0,4).map(p=>({...base,lightingSystem:{...base.lightingSystem,selectedItems:[{productId:p.id,qty:2,zone:'deck' as const}]}})),{...base,railingType:'Frameless Glass'}, {...base,skirting:{style:'Horizontal boards',accessPanels:1} as any}, {...base,deckFinishes:{fascia:'tt_terrain:Brown Oak'}}, {...base,boardWidth:3.5}, {...base,deckType:'Add-on',catalogueAccessories:['tt_protac_flashing']},{...base,privacyScreens:[{id:'manufacturer',side:'Left',lengthFt:7,heightFt:6,offsetPct:50,lights:false,product:'hideaway',panels:2,design:'Hexx',finish:'Black'}]}, {...base,privacyScreens:[{id:'manufacturer',side:'Left',lengthFt:7,heightFt:6,offsetPct:50,lights:false,product:'oasis',panels:2,design:'Bamboo'}]}, {...base,catalogueAccessories:['tt_concealoc']}, {...base,levels:2,width2:10,length2:8,height2:24}];
for(const d of samples){const normalized=deckReleaseData(d),before=calculateDeckReleaseEstimate(normalized),ss=quoteScopeReview(normalized,before).scopes,records=ss.map(s=>confirmQuoteScope(s,{supplyCost:50,installationCost:25,confirmedOn:'2026-09-26',source:'Sourced scope reference',note:'Only outstanding scope; all existing priced work remains.'})),after=calculateDeckReleaseEstimate({...normalized,quoteResolutions:records});near(after.total-before.total,ss.length*85*1.13,`Every unique scope charged exactly once: ${normalized.catalogueAccessories}/${normalized.privacyScreens?.[0]?.product} active ${after.quoteResolutionReview?.active.length}/${ss.length} delta ${after.total-before.total}`);check(after.quoteRequired.length===0,'Every identified outstanding label resolved');check(after.quoteResolutionReview?.inactive===0,'All current scope fingerprints bind');check(!priceLedger(after).lines.some(l=>l.quotes.length),'No resolved null row masquerades as pending');check(ss.filter(s=>!s.rows.length).every(s=>s.name==='Custom-width decking fabrication'),`No quote label duplicates null-cost ledger scope: ${normalized.deckingMaterial}/${normalized.catalogueRailingId}: ${ss.filter(s=>!s.rows.length).map(s=>s.name).join('; ')}`);if(normalized.catalogueAccessories?.includes('tt_protac_flashing'))check(ss.some(s=>s.rows.some(r=>r.name==='Ledger Flashing')&&s.rows.some(r=>r.sectionTitle==='Manufacturer deck accessories')),'Replacement ledger flashing has one bundle');check(new Set(ss.flatMap(s=>s.rows.map(r=>`${r.section}:${r.item}`))).size===ss.flatMap(s=>s.rows).length,'No ledger row is covered by two scopes');}
// Reopening an active scope enriches known prices by stable section title, never the raw numeric index.
// 2026-10 prices cladding finish; legacy keeps install as a quote so known-supply enrichment still has a scope.
const claddingFixture={...base,buildRules:'legacy' as const},claddingEstimateBase=calculateDeckReleaseEstimate(claddingFixture);
const claddingScope=quoteScopeReview(claddingFixture,claddingEstimateBase).scopes.find(s=>s.name==='Stair and level cladding')!,claddingSupply=claddingEstimateBase.sections.find(s=>s.title==='Stair and level cladding')!.items.find(i=>i.name==='Stair and level cladding supply')!;
check(!!claddingScope&&claddingSupply.cost!==null&&claddingSupply.cost!>0,'Legacy cladding fixture has already-priced fascia supply with install still quoted');
const claddingRecord=confirmQuoteScope(claddingScope,{supplyCost:40,installationCost:200,confirmedOn:'2026-09-26',source:'Fixture cladding builder',note:'Additional installation and fixings only; existing fascia supply excluded.'}),claddingData={...claddingFixture,quoteResolutions:[claddingRecord]},claddingEstimate=calculateDeckReleaseEstimate(claddingData),reopened=quoteScopeReview(claddingData,claddingEstimate).scopes.find(s=>s.key===claddingScope.key)!;
check(claddingEstimate.quoteResolutionReview!.active.includes(reopened.key),'Reopened cladding remains active');
check(reopened.rows.some(r=>r.section!==claddingEstimate.sections.findIndex(s=>s.title===r.sectionTitle)),'Fixture exercises raw-vs-filtered index shift');
const knownSupply=reopened.known.find(i=>i.name==='Stair and level cladding supply')!;check(!!knownSupply&&knownSupply.section==='Stair and level cladding','Reopened scope correctly identifies fascia supply section');near(knownSupply.cost,claddingSupply.cost!,'Reopened known supply cost stays exact');check(knownSupply.qty===claddingSupply.qty&&knownSupply.unit===claddingSupply.unit,'Reopened known supply quantity stays exact');check(!reopened.rows.some(r=>r.name===claddingSupply.name),'Already-priced fascia cannot become missing scope');check(!reopened.known.some(i=>i.section==='Confirmed additional quote costs'),'Known base work excludes added resolution line');
const reconfirmed=confirmQuoteScope(reopened,{supplyCost:40,installationCost:200,confirmedOn:'2026-09-26',source:'Fixture re-confirmation',note:'Additional installation and fixings only.'});near(calculateDeckReleaseEstimate({...claddingData,quoteResolutions:[reconfirmed]}).total,claddingEstimate.total,'Reconfirming replaces one scope without charging fascia twice');
// The actual public controller must preserve private confirmations while making a guarded edit.
let state:DeckAgentHostState={data:priced,view:'plan',openSections:[],canUndo:false,canRedo:false,ready:true},past:DeckData|undefined;
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{past=state.data;state={...state,data:next,canUndo:true};},undo:()=>{state={...state,data:past!,canUndo:false,canRedo:true};},redo:()=>{},setView:view=>{state={...state,view};},openSection:()=>{},waitForRender:async()=>{},actions:{},shareOrigin:'http://localhost:4187'});
const snapshot=api.read();check(!Object.hasOwn(snapshot.design,'quoteResolutions'),'window.deckcraft excludes private records');check(!JSON.stringify(snapshot).includes('Private Builder Q-123'),'Public controller excludes source');const request={id:'quote-width-change',expectedRevision:snapshot.revision,commands:[{type:'design.patch',patch:{height:72}}]};const dry=await api.preview(request);check(dry.ok,'Controller preview accepts a design with private costs');check(state.data.quoteResolutions?.[0].source===entry.source,'Preview preserves original evidence');const applied=await api.execute(request);check(applied.ok,'Controller edit succeeds with records present');check(state.data.quoteResolutions?.[0].source===entry.source,'Controller edit preserves inactive record');near(calculateDeckReleaseEstimate(state.data).total,calculateDeckReleaseEstimate({...state.data,quoteResolutions:undefined}).total,'Controller geometry edit invalidates inclusion');check((await api.execute({id:'quote-undo',commands:[{type:'history.undo'}]})).ok,'Atomic Undo succeeds');near(calculateDeckReleaseEstimate(state.data).total,p.total,'Controller Undo restores active confirmation');check(!(await api.preview({id:'quote-private-attack',commands:[{type:'design.patch',patch:{quoteResolutions:[entry]}}]})).ok,'Controller cannot add private quote evidence');
check(estimateKeyOf(priced)!==estimateKeyOf({...priced,customerName:'Different job'}),'Live pricing cache reacts to private job binding');check(estimateKeyOf(priced)!==estimateKeyOf({...priced,houseConfig:{widthFt:40,depthFt:30} as any}),'Live pricing cache reacts to full scope binding');check(estimateKeyOf(priced)===estimateKeyOf({...priced,sceneLighting:'Evening'}),'View-only live cache remains stable');
const facts=describeDesign(priced,p).facts,pdf=Buffer.from(buildProposalPdf(jsPDF,{data:priced,estimate:p,facts,reviewItems:p.flags,date:'September 26, 2026'},{compress:false})),pdfText=[...pdf.toString('latin1').matchAll(/\(((?:\\.|[^\\)])*)\)\s*Tj/g)].map(m=>m[1].replace(/\\([()\\])/g,'$1')).join(' ').replace(/\s+/g,' ');check(pdfText.includes('Covered by confirmed additional scope'),'PDF appendix identifies covered quantities');check(pdfText.includes('Included in confirmed scope'),'PDF schedule identifies coverage');check(!pdfText.includes('Private Builder')&&!pdfText.includes(entry.note),'PDF excludes private supplier references and notes');check(pdfText.includes('Confirmed additional quote costs'),'PDF includes exact confirmed cost section');const html=renderToStaticMarkup(createElement(ProposalSheet,{data:priced,estimate:p,facts,reviewItems:p.flags,image:null,date:'September 26, 2026'}));check(html.includes('Included in confirmed scope')&&html.includes('Covered by confirmed additional scope'),'Web proposal identifies scope coverage');check(!html.includes(entry.source)&&!html.includes(entry.note),'Web proposal excludes private source and note');
if(process.env.QUOTE_REVIEW_PROOF){mkdirSync(process.env.QUOTE_REVIEW_PROOF,{recursive:true});writeFileSync(process.env.QUOTE_REVIEW_PROOF+'/Confirmed-scope-proof.pdf',pdf);writeFileSync(process.env.QUOTE_REVIEW_PROOF+'/Confirmed-scope-proof.html',html);}
console.log(`Quote resolutions: ${count} checks passed.`);
