import {snapScenePoint,sceneSnapGeometry} from '../src/features/deckcraft/designer/sceneSnapping';
import {exportProjectBundle,importProjectBundle} from '../src/features/deckcraft/projectBundle';
import {saveStoredProject,readProjectValue,closeProjectStorage} from '../src/features/deckcraft/projectStorage';
import {landscapeSurfaceCells,landscapeCellTriangles} from '../src/features/deckcraft/landscapeSurfaceGeometry';
import {parseNaturalLanguageCommands} from '../src/features/deckcraft/designer/naturalLanguageCommands';
import {buildAssistantContext} from '../src/features/deckcraft/designer/assistantPlan';
import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {newLandscapeObject} from '../src/features/deckcraft/landscapeCatalogue';
import {validateLandscapeObjects} from '../src/features/deckcraft/landscapeTypesRuntime';
import {ensureDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {landscapeTakeoff,landscapeBedAreas} from '../src/features/deckcraft/landscapeModelRuntime';
import {presetLandscapeOutline,landscapeOutlinePaths,landscapeSignedArea,validateLandscapeOutline,convertLandscapeOutline,splitLandscapeSegment,resizeLandscape,landscapeWorld,editLandscapeHandle,simplifyLandscapeStroke} from '../src/features/deckcraft/landscapeOutline';
import {applyLandscapeEdit} from '../src/features/deckcraft/landscapeEdits';
import {editObjects} from '../src/features/deckcraft/professionalEdits';
import {arcGeometry} from '../src/features/deckcraft/circularArcs';
import {createDeckAgentController} from '../src/features/deckcraft/designer/deckAgentController';
import {serializeDeckReleaseDesign,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {encodeDesignLink,decodeDesignLink,designLinkFromHash} from '../src/features/deckcraft/designLink';
import {objectPick} from '../src/features/deckcraft/components/viewer3d/SelectionBridge';
import {sceneEditCommands,sceneDraft} from '../src/features/deckcraft/designer/sceneEditCommands';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import * as THREE from 'three';
let checks=0;const ok=(value:unknown,label='')=>{assert.ok(value,label);checks++;},near=(a:number,b:number,tolerance=.001)=>ok(Math.abs(a-b)<=Math.max(1e-7,Math.abs(b)*tolerance),`${a} ≈ ${b}`);
const ringArea=(o:ReturnType<typeof newLandscapeObject>)=>Math.abs(landscapeOutlinePaths(o).reduce((n,p)=>n+landscapeSignedArea(p),0));
async function main(){
 const basic=newLandscapeObject('putting-green','green',1200,1200),data={...DEFAULT_DECK,houseVisible:false,landscapeObjects:[basic]};await ensureDesignExtensions(data);
 for(const preset of ['rectangle','circle','oval','rounded','kidney'] as const){const outline=presetLandscapeOutline(preset,240,preset==='circle'?240:120),o={...basic,widthIn:240,depthIn:preset==='circle'?240:120,outline,puttingCups:[]};ok(validateLandscapeOutline(outline),preset);ok(validateLandscapeObjects([o]),preset);if(preset==='circle')near(ringArea(o),Math.PI*120**2);if(preset==='oval')near(ringArea(o),Math.PI*120*60);if(preset==='rectangle')near(ringArea(o),240*120);const area=landscapeTakeoff([o]).bedAreaSqft;near(area,ringArea(o)/144,1e-6);near(landscapeTakeoff([{...o,surfaceDepthIn:3,baseDepthIn:6}]).baseYd3!,area*6/324,1e-8);}
 const circle={...basic,widthIn:240,depthIn:240,outline:presetLandscapeOutline('circle',240,240),puttingCups:[]};
 const perimeter=landscapeOutlinePaths(circle)[0].reduce((n,a,i,p)=>n+Math.hypot(a.x-p[(i+1)%p.length].x,a.z-p[(i+1)%p.length].z),0);near(perimeter,2*Math.PI*120);
 const split={...circle,outline:{...circle.outline,outer:splitLandscapeSegment(circle.outline.outer,0)}};ok(validateLandscapeObjects([split]));near(ringArea(split),ringArea(circle),.0001);
 assert.throws(()=>resizeLandscape(circle,300,240),/uniform/);checks++;const oval=resizeLandscape(circle,300,240,true);ok(validateLandscapeObjects([oval]));near(ringArea(oval),Math.PI*150*120);
 const moved=editLandscapeHandle(circle,{ring:0,index:0,part:'point'},landscapeWorld(circle,{x:115,z:0}));ok(validateLandscapeObjects([moved]));const s=moved.outline!.outer.segments[0];ok(s.kind==='arc');if(s.kind==='arc'){const a=moved.outline!.outer.points[0],b=moved.outline!.outer.points[1];near(arcGeometry({x:a.x,y:a.z},{x:b.x,y:b.z},s.bulgeIn).radius,120,1e-8);}
 const outer=presetLandscapeOutline('rectangle',240,240).outer,hole=presetLandscapeOutline('circle',60,60).outer,o={...basic,widthIn:240,depthIn:240,outline:{outer,holes:[hole]},puttingCups:[]};ok(validateLandscapeObjects([o]));near(ringArea(o),240**2-Math.PI*30**2);near(landscapeTakeoff([o]).bedAreaSqft,ringArea(o)/144,1e-6);
 ok(!validateLandscapeObjects([{...o,puttingCups:[{x:0,z:0}]}]));ok(!validateLandscapeObjects([{...o,puttingCups:[{x:31,z:0}]}]));ok(!validateLandscapeOutline({...o.outline,holes:[outer]}));
 const malicious={...o.outline,outer:{...outer,points:outer.points.map(p=>({...p}))}};Object.defineProperty(malicious.outer.points[0],'x',{get(){throw Error('Getter invoked');},enumerable:true});ok(!validateLandscapeOutline(malicious));
 const legacy={...basic,polygon:[{x:1080,z:1080},{x:1320,z:1080},{x:1280,z:1320},{x:1100,z:1280}],puttingCups:[]},converted=convertLandscapeOutline(legacy);ok(!converted.polygon);near(ringArea(legacy),ringArea(converted),1e-9);ok(validateLandscapeObjects([converted]));
 const stroke=Array.from({length:600},(_,i)=>({x:100*Math.cos(i*Math.PI/300),z:60*Math.sin(i*Math.PI/300)})),smooth=simplifyLandscapeStroke(stroke,1);ok(smooth.points.length<=64);ok(validateLandscapeOutline({outer:smooth,holes:[]}));
 const locked={...data,editorOrganization:{layers:[{id:'main',name:'Main',visible:true,locked:false}],groups:[],objects:[{id:'green',layerId:'main',locked:true}]}};assert.throws(()=>applyLandscapeEdit(locked,'green',{action:'preset',preset:'circle'}),/locked/);checks++;
 const rotated={...data,landscapeObjects:[circle]},patch=editObjects(rotated,['green'],{action:'rotate',angleDeg:45,pivotXIn:0,pivotZIn:0});near(ringArea(patch.landscapeObjects![0]),ringArea(circle),1e-9);near(patch.landscapeObjects![0].rotationDeg,45,1e-9);
 const empty={...DEFAULT_DECK,houseVisible:false,landscapeObjects:[{...basic,xIn:1200,zIn:1200,puttingCups:[]}]};await ensureDesignExtensions(empty);
 const fill=applyLandscapeEdit(empty,'green',{action:'fill',point:{x:1200,z:1200},container:[{x:1080,z:1080},{x:1320,z:1080},{x:1320,z:1320},{x:1080,z:1320}]}),filled={...empty,...fill};near(landscapeTakeoff(fill.landscapeObjects!,filled).bedAreaSqft,400);
 const later={...newLandscapeObject('white-stone-bed','island',1200,1200),widthIn:60,depthIn:60};const shared={...filled,landscapeObjects:[...filled.landscapeObjects!,later]};near(landscapeTakeoff(shared.landscapeObjects,shared).bedAreaSqft,400);near(landscapeTakeoff(shared.landscapeObjects,shared).items.find(i=>i.objectId==='green')!.areaSqft,375);near(landscapeTakeoff(filled.landscapeObjects!,filled).bedAreaSqft,400);
 const stock={...newLandscapeObject('outdoor-chair','chair',1200,1200),supportFeatureId:'missing'};assert.throws(()=>applyLandscapeEdit({...empty,landscapeObjects:[stock]},'chair',{action:'patch',patch:{xIn:1210}}),/support/);checks++;
 const scene=sceneEditCommands(rotated,buildDeckTakeoff(rotated),{partIds:[],boards:[],hardscape:{kind:'landscape',id:'green'}},{part:'move'},{dxIn:24,dzIn:12,dyIn:0,angleDeg:0,world:{x:1224,z:1212}}),draft=sceneDraft(rotated,buildDeckTakeoff(rotated),scene);near(draft.landscapeObjects![0].xIn,1224);near(ringArea(draft.landscapeObjects![0]),ringArea(circle),1e-9);
 const mesh=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial());mesh.userData.pickPartIds=['landscape/green'];ok(objectPick(mesh,0)?.hardscape?.kind==='landscape');ok(objectPick(mesh,0)?.hardscape?.id==='green');mesh.geometry.dispose();(mesh.material as THREE.Material).dispose();
 let current={...data,landscapeObjects:[circle]},history:typeof current[]=[];const controller=createDeckAgentController({getState:()=>({data:current,view:'3d',openSections:[],canUndo:history.length>0,canRedo:false,ready:true}),commitDesign:next=>{history.push(current);current=next as typeof current;},undo:()=>{},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async p=>{ok(p({data:current,view:'3d',openSections:[],canUndo:true,canRedo:false,ready:true}));}}),before=controller.read(),request={id:'curve-preview',expectedRevision:before.revision,commands:[{type:'landscape.edit' as const,id:'green',edit:{action:'preset' as const,preset:'kidney' as const}}]};const preview=await controller.preview(request);ok(preview.ok);ok(!history.length);ok(current.landscapeObjects[0].outline===circle.outline);const apply=await controller.execute({...request,id:'curve-apply'});ok(apply.ok);ok(history.length===1);const stale=await controller.execute({...request,id:'curve-stale'});ok(stale.ok===false&&stale.error.code==='stale_revision');
 const restored=parseDeckReleaseDesign(serializeDeckReleaseDesign(current));ok(restored.landscapeObjects?.[0].outline);near(ringArea(restored.landscapeObjects![0]),ringArea(current.landscapeObjects[0]),1e-9);const url=await encodeDesignLink(current,'https://example.test'),link=await decodeDesignLink(designLinkFromHash(new URL(url).hash)!);ok(link.landscapeObjects?.[0].outline);ok(!('quoteResolutions'in link));
 const withCups={...circle,puttingCups:[{x:30,z:10}]},resized=resizeLandscape(withCups,300,300);ok(JSON.stringify(resized.puttingCups)===JSON.stringify(withCups.puttingCups),'Resize preserves cups');
 const handleSource={...data,landscapeObjects:[withCups]},beforeCup=landscapeWorld(withCups,withCups.puttingCups[0]),reshaped=applyLandscapeEdit(handleSource,'green',{action:'handle',handle:{ring:0,index:0,part:'point'},point:landscapeWorld(withCups,{x:115,z:0})}).landscapeObjects![0],afterCup=landscapeWorld(reshaped,reshaped.puttingCups![0]);near(afterCup.x,beforeCup.x,1e-9);near(afterCup.z,beforeCup.z,1e-9);ok(reshaped.widthIn!==withCups.widthIn);
 const bundle=await exportProjectBundle({...current,landscapeObjects:[o]}),portable=await importProjectBundle(bundle);ok(JSON.stringify(portable.landscapeObjects?.[0].outline)===JSON.stringify(o.outline));
 const json=serializeDeckReleaseDesign(portable);await saveStoredProject('current',json);const saved=await readProjectValue<{json:string}>('projects','current');ok(saved?.json===json);closeProjectStorage();
 const cells=landscapeSurfaceCells({...DEFAULT_DECK,terrainConfig:{slopePct:10,elevationIn:7,widthFt:100,depthFt:100}},landscapeOutlinePaths(o)),vertices=landscapeCellTriangles(cells,3).positions;let meshArea=0;for(let i=0;i<vertices.length;i+=9){const [ax,ay,az,bx,by,bz,cx,cy,cz]=vertices.slice(i,i+9);near(ay*12,7+az*12*.1+3.05,1e-8);meshArea+=Math.abs((bx-ax)*(cz-az)-(bz-az)*(cx-ax))/2;}near(meshArea,ringArea(o)/144);
 const voice=parseNaturalLanguageCommands('make selected area kidney',controller.read(),{partIds:[],boards:[],hardscape:{kind:'landscape',id:'green'}});ok(voice.ok,'Selected landscape voice target');
 const context=buildAssistantContext(controller.read(),{partIds:[],boards:[],hardscape:{kind:'landscape',id:'green'}});ok(context.selection.hardscape?.kind==='landscape');
 const prior={...later,xIn:1150},preFill={...empty,landscapeObjects:[prior,{...basic,puttingCups:[]}]},fillAround=applyLandscapeEdit(preFill,'green',{action:'fill',point:{x:1250,z:1200},container:[{x:1080,z:1080},{x:1320,z:1080},{x:1320,z:1320},{x:1080,z:1320}]}),filledAround={...preFill,...fillAround};near(landscapeTakeoff(fillAround.landscapeObjects!,filledAround).items.find(i=>i.objectId==='green')!.areaSqft,375);near(landscapeTakeoff(fillAround.landscapeObjects!,filledAround).items.find(i=>i.objectId==='island')!.areaSqft,25);near(landscapeTakeoff(fillAround.landscapeObjects!.filter(o=>o.id!=='island'),{...filledAround,landscapeObjects:fillAround.landscapeObjects!.filter(o=>o.id!=='island')}).bedAreaSqft,400);
 const snapped=snapScenePoint({x:119,z:119},[[{x:120,z:120},{x:240,z:120},{x:240,z:240},{x:120,z:240}]],3);near(snapped.x,120,1e-9);near(snapped.z,120,1e-9);
 const aligned=snapScenePoint({x:118,z:300},[[{x:120,z:120},{x:240,z:120},{x:240,z:240},{x:120,z:240}]],3);near(aligned.x,120,1e-9);near(aligned.z,300,1e-9);
 const groupVoice=parseNaturalLanguageCommands('move selected objects 12 inches right',controller.read(),{partIds:[],boards:[],objectIds:['green']});ok(groupVoice.ok&&groupVoice.request.commands[0].type==='objects.edit');
 const rotateVoice=parseNaturalLanguageCommands('rotate selected group 30 degrees',controller.read(),{partIds:[],boards:[],objectIds:['green']});ok(rotateVoice.ok&&rotateVoice.request.commands[0].type==='objects.edit');
 const groupContext=buildAssistantContext(controller.read(),{partIds:[],boards:[],objectIds:['green']});ok(groupContext.selection.objectIds?.[0]==='green',JSON.stringify(groupContext.selection));
 controller.dispose();
 console.log(`CURVED LANDSCAPE EDITING OK — ${checks} checks.`);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
