import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData} from '../src/features/deckcraft/types';
import {DECKING_CATALOGUE} from '../src/features/deckcraft/manufacturerCatalog';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {houseRailingReviewFlags} from '../src/features/deckcraft/houseRailingClearance';
import {captureContractorPreset,contractorPresetPatch,emptyPresetLibrary,exportPresetLibrary,mergePresetLibraries,parsePresetLibrary,parsePresetText,previewContractorPreset,PRESET_FIELDS,PRESET_LIMITS,type ContractorPreset} from '../src/features/deckcraft/designer/contractorPresets';

let assertions=0;const equal=(actual:unknown,expected:unknown)=>{assert.deepEqual(actual,expected);assertions++;};const rejects=(fn:()=>unknown,pattern?:RegExp)=>{assert.throws(fn,pattern);assertions++;};
const base=()=>structuredClone(DEFAULT_DECK),preset=(data:DeckData=base())=>captureContractorPreset(data,'Preferred specification',false,'preferred');
const library=(p:ContractorPreset=preset())=>({...emptyPresetLibrary(),presets:[p]});
equal(parsePresetText(exportPresetLibrary(emptyPresetLibrary())),emptyPresetLibrary());
const first=preset(),captured=library(first);equal(parsePresetLibrary(captured),captured);equal(previewContractorPreset(base(),first).changes,[]);equal(Object.keys(first.settings).sort(),[...PRESET_FIELDS].sort());
for(const key of ['width','length','height','deckOutlines','boardLayout','boardColours','customerName','projectAddress','privacyScreens','lightingSystem','wireDistance','stairFlights','siteType','soilCondition','yardFeatures','scopeOfWork'])equal(Object.hasOwn(first.settings,key),false);
const source={...base(),materialMarkup:71,customLaborCost:12345,customOverrides:{'Existing fixture row':{qty:4,cost:321}},customerName:'Private customer',projectAddress:'Private address'};
equal(preset(source).pricing,undefined);const privatePreset=captureContractorPreset(source,'Owner pricing',true,'private');equal(privatePreset.pricing,{materialMarkup:71,customLaborCost:12345,customOverrides:{'Existing fixture row':{qty:4,cost:321}}});
const portable=exportPresetLibrary(library(privatePreset));equal(/"pricing"|"materialMarkup"|"customLaborCost"|"customOverrides"|Private customer|Private address/.test(portable),false);equal(parsePresetText(portable).presets[0].pricing,undefined);rejects(()=>parsePresetText(JSON.stringify(library(privatePreset))),/private contractor pricing/);
const job:DeckData={...base(),width:24,length:16,height:42,levels:2,width2:10,length2:8,height2:18,customerName:'Keep me',projectAddress:'Keep address',materialMarkup:22,customLaborCost:9000,customOverrides:{'Old line':{qty:2}},siteType:'Hillside',soilCondition:'Clay',deckOutlines:{main:[{x:0,y:0},{x:24,y:0},{x:24,y:16},{x:0,y:16}]},deckOutlineOffsets:{second:{x:3,y:16}},stairPosition:'Right',stairOffset:22,privacyScreens:[{id:'private1',side:'Left',lengthFt:4,heightFt:6,offsetPct:40,lights:false}],skirting:{style:'Vertical boards',clearanceIn:3,accessPanels:2,openEdges:['deck1-back']}};
const spec:DeckData={...base(),framingSize:'2x12',joistSpacing:12,foundation:'Helical Piles',pattern:'Diagonal',pictureFrameRows:2,autoLighting:{posts:true,stairs:true},underDeck:{drainage:'none',ceiling:'pvc',scope:'main',gravel:true,gravelDepthIn:4,floorMesh:true},skirting:{style:'Horizontal boards',clearanceIn:4,accessPanels:4,openEdges:['deck1-front']}};
const saved=captureContractorPreset(spec,'Detailed composite',true,'detailed'),before=structuredClone(job),patch=contractorPresetPatch(job,saved),next={...job,...patch};
equal(job,before);equal(next.framingSize,'2x12');equal(next.foundation,'Helical Piles');equal(next.skirting?.openEdges,['deck1-back']);equal(next.skirting?.accessPanels,2);equal(Object.hasOwn(saved.settings.skirting!,'openEdges'),false);equal(Object.hasOwn(saved.settings.skirting!,'accessPanels'),false);
for(const key of Object.keys(job).filter(k=>!PRESET_FIELDS.includes(k as never)&&k!=='hasDrainage'))equal((next as unknown as Record<string,unknown>)[key],(job as unknown as Record<string,unknown>)[key]);
equal(next.materialMarkup,22);equal(next.customLaborCost,9000);equal(next.customOverrides,job.customOverrides);const privatePatch=contractorPresetPatch(job,privatePreset,true);equal(privatePatch.materialMarkup,71);equal(privatePatch.customLaborCost,12345);equal(privatePatch.customOverrides,privatePreset.pricing?.customOverrides);
const preview=previewContractorPreset(job,saved);equal(job,before);equal(preview.estimate.total,calculateDeckReleaseEstimate(preview.next).total);equal(preview.current.total,calculateDeckReleaseEstimate(job).total);equal(preview.estimate.model.quantities,calculateDeckReleaseEstimate(preview.next).model.quantities);equal(preview.next.lightingSystem.wireDistance,job.lightingSystem.wireDistance);equal(preview.next.deckOutlines,job.deckOutlines);equal(preview.next.privacyScreens,job.privacyScreens);
const postItem=preview.next.lightingSystem.selectedItems.find(i=>i.auto&&i.zone==='posts'),stairs=preview.next.lightingSystem.selectedItems.find(i=>i.auto&&i.zone==='stairs');equal(postItem?.qty,Math.min(30,preview.estimate.model.railing.posts.length));equal(stairs?.qty,Math.min(30,preview.estimate.model.treads.length));assert(preview.estimate.quoteRequired.length>0);assertions++;
const openingJob:DeckData={...base(),houseConfig:{widthFt:30,depthFt:20,storeys:1,storeyHeightIn:120,roofShape:'Gable',roofFinish:'Shingles',roofColor:'#444444',cladding:'Siding',claddingColor:'#bbbbbb',trimColor:'#ffffff',openings:[{id:'measured-clash',type:'Window',facade:'Front',offsetPct:23.3333333333,bottomIn:36,widthIn:72,heightIn:48}]}};
const openingPreview=previewContractorPreset(openingJob,first),hostIssues=houseRailingReviewFlags(openingPreview.next,openingPreview.estimate.model,openingPreview.estimate.flags);assert(hostIssues.some(issue=>issue.includes('measured-clash')));assertions++;for(const issue of hostIssues){assert(openingPreview.issues.includes(issue));assertions++;}equal(openingPreview.next.houseConfig,openingJob.houseConfig);
const accentJob={...base(),boardColours:[{lv:1 as const,role:'field' as const,scope:'course' as const,course:'f:1',colour:'tt_prime_plus:Coconut Husk'}],boardLayout:{regions:[],breakers:[],pieces:[{id:'wide',level:1 as const,cx:60,cy:60,lengthIn:24,widthIn:5.5,angleDeg:30,colour:'tt_prime_plus:Coconut Husk'}]}};
const wood=DECKING_CATALOGUE.find(m=>m.id==='pressure_treated')!;rejects(()=>contractorPresetPatch(accentJob,captureContractorPreset({...base(),deckingMaterial:wood.id,deckingColor:wood.colors[0].name},'Wood',false,'wood')),/incompatible/);rejects(()=>contractorPresetPatch(accentJob,preset({...base(),boardWidth:3.5})),/narrower/);equal(contractorPresetPatch(accentJob,first).boardLayout,undefined);equal(accentJob.boardLayout.pieces.length,1);
for(const material of DECKING_CATALOGUE.filter(m=>!m.isHidden)){const p=captureContractorPreset({...base(),deckingMaterial:material.id,deckingColor:material.colors[0].name},material.name,false,material.id);equal(parsePresetLibrary(library(p)).presets[0].settings.deckingMaterial,material.id);equal(contractorPresetPatch(base(),p).deckingColor,material.colors[0].name);}
const invalid=(mutate:(v:ReturnType<typeof library>)=>void)=>{const value=structuredClone(captured);mutate(value);rejects(()=>parsePresetLibrary(value));};
invalid(v=>{(v as unknown as Record<string,unknown>).customerName='No';});invalid(v=>{v.version=2 as 1;});invalid(v=>{v.presets[0].name='';});invalid(v=>{v.presets[0].name='x'.repeat(81);});invalid(v=>{v.presets[0].name='Control\u0001';});invalid(v=>{v.presets[0].id='constructor';(v.presets[0] as unknown as Record<string,unknown>).prototype={};});invalid(v=>{(v.presets[0].settings as unknown as Record<string,unknown>).width=40;});invalid(v=>{v.presets[0].settings.foundation='Bogus' as never;});invalid(v=>{v.presets[0].settings.boardWidth=NaN as never;});invalid(v=>{v.presets[0].settings.foundationDepthIn=Infinity;});invalid(v=>{v.presets[0].settings.deckingColor='Nonexistent colour';});invalid(v=>{v.presets[0].settings.autoLighting={posts:1 as never};});invalid(v=>{v.presets[0].settings.autoLighting={posts:true,quantity:8} as never;});invalid(v=>{v.presets[0].settings.skirting={style:'Lattice',clearanceIn:3,openEdges:['deck1-front']} as never;});invalid(v=>{v.presets[0].settings.underDeck={drainage:'dryspace',ceiling:'cedar',scope:'all',gravel:true,gravelDepthIn:3,floorMesh:false};});invalid(v=>{v.presets[0].settings.underDeck!.gravelDepthIn=7;});invalid(v=>{v.presets[0].settings.underDeck!.floorMesh='yes' as never;});invalid(v=>{v.presets[0].settings.lightingZoneEnabled={deck:true,unknown:false} as never;});invalid(v=>{v.presets[0].settings.deckFinishes={border:'pressure_treated:Natural'};});invalid(v=>{delete (v.presets[0].settings as Partial<typeof first.settings>).foundation;});invalid(v=>{v.presets.push({...first,id:'other',name:first.name.toUpperCase()});});invalid(v=>{v.presets.push({...first,name:'Other'});});invalid(v=>{v.presets=Array.from({length:41},(_,i)=>({...first,id:`p${i}`,name:`Preset ${i}`}));});
for(const value of [NaN,Infinity,-1,501]){const p=structuredClone(privatePreset);p.pricing!.materialMarkup=value;rejects(()=>parsePresetLibrary(library(p)));}
for(const overrides of [{row:{qty:-1}},{row:{cost:Infinity}},{row:{unit:'invented'}},{row:{}},{constructor:{qty:1}}]){const p=structuredClone(privatePreset);p.pricing!.customOverrides=overrides as never;rejects(()=>parsePresetLibrary(library(p)));}
let accessorCalls=0;const access=structuredClone(captured);Object.defineProperty(access.presets[0],'name',{enumerable:true,get(){accessorCalls++;return 'Should not execute';}});rejects(()=>parsePresetLibrary(access));equal(accessorCalls,0);
const sparse=structuredClone(captured);sparse.presets.length=2;rejects(()=>parsePresetLibrary(sparse),/Sparse/);const arrayExtra=structuredClone(captured);Object.defineProperty(arrayExtra.presets,'extra',{value:'no',enumerable:true});rejects(()=>parsePresetLibrary(arrayExtra));
const proto=structuredClone(captured);Object.setPrototypeOf(proto.presets[0],{sneaky:true});rejects(()=>parsePresetLibrary(proto),/plain object/);const hidden=structuredClone(captured);Object.defineProperty(hidden,'hidden',{value:true,enumerable:false});rejects(()=>parsePresetLibrary(hidden));
rejects(()=>parsePresetText(' '.repeat(PRESET_LIMITS.bytes+1)),/100 KB/);rejects(()=>parsePresetText('{bad}'));rejects(()=>mergePresetLibraries(captured,captured),/duplicate/);equal(captured.presets.length,1);
const parsed=parsePresetLibrary(captured);parsed.presets[0].settings.framingSize='2x8';equal(captured.presets[0].settings.framingSize,'2x10');
// Trex RainEscape is retired (2026-10-04): capturing a job that still has it, or loading an older preset with it, stores no drainage.
const retiredJob:DeckData={...base(),underDeck:{drainage:'rainescape',ceiling:'none',scope:'main',gravel:false,gravelDepthIn:3,floorMesh:false}};
equal(captureContractorPreset(retiredJob,'Older job').settings.underDeck?.drainage,'none');
const olderLibrary=structuredClone(parsePresetLibrary(library(captureContractorPreset(base(),'Older preset',false,'older'))));(olderLibrary.presets[0].settings.underDeck as {drainage:string}).drainage='rainescape';
equal(parsePresetLibrary(olderLibrary).presets[0].settings.underDeck?.drainage,'none');
console.log(`Contractor presets: ${assertions} validation, privacy, compatibility, geometry preservation and exact managed-lighting price checks passed.`);
