import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {DECKING_CATALOGUE} from '../src/features/deckcraft/manufacturerCatalog';
import {buildInstallationPlan,exportInstallationHTML,validateInstallation,installationFamily,DEFAULT_INSTALLATION,FRAMING_OPTIONS} from '../src/features/deckcraft/installationSystem';
import {parseDesign,serializeDesign} from '../src/features/deckcraft/designPersistence';
import {exportDeckReleaseDXF,exportDeckReleaseOBJ} from '../src/features/deckcraft/deckRelease';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import type {DeckData} from '../src/features/deckcraft/types';
let passed=0;
function check(name:string,fn:()=>void){fn();passed++;console.log(`PASS ${name}`);}
const base=()=>structuredClone(DEFAULT_DECK);
const fixture=(patch:Partial<DeckData>={})=>({...base(),...patch});
check('legacy designs retain timber default',()=>assert.equal(buildInstallationPlan(base()).selection.framing,'Pressure-treated lumber'));
check('all catalogue collections mapped explicitly',()=>{for(const m of DECKING_CATALOGUE)assert.notEqual(installationFamily(m.id),'unknown',m.id);});
check('unknown products fail closed',()=>assert.ok(buildInstallationPlan(fixture({deckingMaterial:'tt_future'})).issues.some(i=>i.id==='unknown-product'&&i.severity==='blocker')));
check('composite / PVC / mineral systems stay distinct',()=>{assert.equal(installationFamily('tt_harvest'),'tt-pvc');assert.equal(installationFamily('tt_terrain'),'tt-composite');assert.equal(installationFamily('deck_voyage'),'surestone');assert.equal(installationFamily('deck_vista'),'deckorators-wpc');});
for(const framing of FRAMING_OPTIONS)check(`${framing}: never approved by selections`,()=>{const p=buildInstallationPlan(fixture({installation:{...DEFAULT_INSTALLATION,framing,boardSku:'Known',fastenerProduct:'Known',thicknessMm:25,temperatureC:20,edge:'Grooved',profile:'Solid'}}));assert.equal(p.constructionReady,false);assert.equal(p.permitReady,false);assert.equal(p.status,'review-required');assert.equal(p.timberModel,framing==='Pressure-treated lumber');});
check('zero Celsius and zero gaps are retained',()=>{const s=validateInstallation({...DEFAULT_INSTALLATION,temperatureC:0,endGapMm:0,sideGapMm:0,ventilationMm:0});assert.equal(s.temperatureC,0);assert.equal(s.endGapMm,0);});
check('finite/range validation',()=>{for(const n of [NaN,Infinity,-100,100])assert.throws(()=>validateInstallation({...DEFAULT_INSTALLATION,temperatureC:n}));assert.throws(()=>validateInstallation({...DEFAULT_INSTALLATION,thicknessMm:0}));assert.throws(()=>validateInstallation({...DEFAULT_INSTALLATION,endGapMm:'5'}));});
check('invalid objects and unknown enum values rejected',()=>{for(const v of [null,[],3,'x',{framing:'Plastic'}])assert.throws(()=>validateInstallation(v));});
check('untrusted approval keys are discarded',()=>{const result=validateInstallation({...DEFAULT_INSTALLATION,approved:true,permitReady:true,sourceUrl:'javascript:alert(1)'});assert.ok(!('approved' in result));assert.ok(!('sourceUrl' in result));});
check('unknown / undefined optional number remains unknown',()=>assert.equal(validateInstallation({...DEFAULT_INSTALLATION,temperatureC:undefined}).temperatureC,undefined));
check('text length guard',()=>assert.throws(()=>validateInstallation({...DEFAULT_INSTALLATION,boardSku:'x'.repeat(161)})));
check('selection round trips through public JSON',()=>{const data=fixture({installation:{...DEFAULT_INSTALLATION,framing:'Aluminum',framingSystem:'TimberTech',boardSku:'Example',temperatureC:0,endGapMm:0}});assert.deepEqual(parseDesign(serializeDesign(data)).installation,data.installation);});
check('old JSON files still load',()=>assert.equal(parseDesign(serializeDesign(base())).installation,undefined));
check('square edge hidden fastening is blocked for review',()=>assert.ok(buildInstallationPlan(fixture({fasteningSystem:'Hidden',installation:{...DEFAULT_INSTALLATION,edge:'Square'}})).issues.some(i=>i.id==='square-hidden'&&i.severity==='blocker')));
check('wood clip does not become metal approved',()=>assert.ok(buildInstallationPlan(fixture({catalogueAccessories:['dk_stealthlock'],installation:{...DEFAULT_INSTALLATION,framing:'Steel'}})).issues.some(i=>i.id==='wood-clips')));
check('cross-family clips remain on hold, including imported designs',()=>{for(const [deckingMaterial,clip,id] of [['deck_voyage','tt_concealoc','cross-brand-tt-clip'],['tt_vintage','dk_stealthlock','cross-brand-dk-clip']])assert.ok(buildInstallationPlan(fixture({deckingMaterial,catalogueAccessories:[clip]})).issues.some(i=>i.id===id&&i.severity==='blocker'));});
check('pattern / borders / stairs / drainage branch',()=>{const ids=buildInstallationPlan(fixture({pattern:'Diagonal',pictureFrameRows:1,borderFinish:'Dark Slate',stairFlights:1,hasDrainage:true})).issues.map(i=>i.id);for(const id of ['angled-support','border-blocking','mixed-border','stair-assembly','drainage'])assert.ok(ids.includes(id),id);});
check('manufacturer notes do not share generic end gaps',()=>{assert.match(buildInstallationPlan(fixture({deckingMaterial:'tt_terrain'})).familyNotes.join(' '),/temperature-based/);assert.match(buildInstallationPlan(fixture({deckingMaterial:'tt_vintage'})).familyNotes.join(' '),/tight PVC-to-PVC/);});
check('export escapes every user text field',()=>{const html=exportInstallationHTML(fixture({projectAddress:'<script>alert(1)</script>',installation:{...DEFAULT_INSTALLATION,boardSku:'"><img src=x onerror=alert(1)>'}}));assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img'));assert.ok(html.includes('&lt;script&gt;'));assert.match(html,/NOT FOR CONSTRUCTION/);});
check('non-timber CAD and OBJ exports refuse timber model',()=>{const d=fixture({installation:{...DEFAULT_INSTALLATION,framing:'Steel'}}),model=buildDeckTakeoff(d);assert.throws(()=>exportDeckReleaseDXF(d,model),/planning-only/);assert.throws(()=>exportDeckReleaseOBJ(d,model),/planning-only/);});
check('planning report contains sequence, gaps and source provenance',()=>{const html=exportInstallationHTML(fixture({deckingMaterial:'tt_vintage'}));for(const expected of ['Manufacturer references','2026-09-21','Inspection','REVIEW REQUIRED','not a complete installation manual'])assert.ok(html.toLowerCase().includes(expected.toLowerCase()),expected);});
if(process.argv.includes('--sample'))writeFileSync('../../outputs/deckcraft-installation-planning-sample.html',exportInstallationHTML(fixture({deckingMaterial:'tt_vintage',projectAddress:'Illustrative project - site not supplied',pattern:'Picture Frame',pictureFrameRows:1,installation:{...DEFAULT_INSTALLATION,framing:'Aluminum',framingSystem:'TimberTech Aluminum - specification pending',temperatureC:20}})));
console.log(`${passed} installation checks passed.`);
