import {loadAdvancedYardRuntime} from '../src/features/deckcraft/yardModel';
await loadAdvancedYardRuntime();
import '../src/features/deckcraft/editorOrganizationRuntime';
import '../src/features/deckcraft/landscapeTypesRuntime';
import '../src/features/deckcraft/landscapeModelRuntime';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {arcGeometry} from '../src/features/deckcraft/circularArcs';
import {applyYardStarter,curveYardEdge} from '../src/features/deckcraft/yardDesignTools';
import {yardShapeLocalPoints,yardShapePull,yardShapeInsert,yardShapeRemove,yardShapeResize} from '../src/features/deckcraft/yardShapeEditing';
import {offsetYardFeature,editObjects} from '../src/features/deckcraft/professionalEdits';
import {validateEditorOrganization,assertUnlockedChanges,emptyOrganization} from '../src/features/deckcraft/editorOrganization';
import {portableReplacement} from '../src/features/deckcraft/ProjectFileTools';
import {serializeDeckReleaseDesign,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {createDeckAgentController,type DeckAgentHostState,type AgentCommand} from '../src/features/deckcraft/designer/deckAgentController';
import {emptyHistory,recordChange,undoChange,redoChange} from '../src/features/deckcraft/designer/designHistory';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {buildYardTakeoff} from '../src/features/deckcraft/yardTakeoff';
let checks=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},near=(a:number,b:number,m:string)=>ok(Math.abs(a-b)<1e-6,m),reject=(fn:()=>unknown,m:string)=>{assert.throws(fn,undefined,m);checks++;};
const wall:YardFeature={id:'curve-wall',name:'Curved wall',enabled:true,kind:'retaining-wall',productId:'segmental-concrete',color:'#8c8175',xFt:50,zFt:50,widthFt:20,depthFt:1,heightIn:24,rotationDeg:0};
const radius=(f:YardFeature)=>{const c=f.curves![0],p=yardShapeLocalPoints(f);return arcGeometry(p[c.edge],p[(c.edge+1)%p.length],c.bulgeIn).radius;};
const starter=applyYardStarter(wall,'arc');ok(starter.wallPath?.length===2&&starter.curves?.length===1,'Circular starter retains two controls and an analytic arc');near(starter.widthFt,wall.widthFt,'Starter preserves analytic run');
const circle=curveYardEdge(wall,0,24),r=radius(circle);near(radius(yardShapePull(circle,'point',1,-12,4)),r,'Pointer endpoint editing retains exact radius');near(radius(offsetYardFeature(circle,6)),r+6,'Parallel positive curve offset preserves concentric radius');near(radius(yardShapeResize(circle,circle.widthFt*1.1)),r*1.1,'Uniform numeric resizing scales circle exactly');
const multiline={...wall,wallPath:[{x:-100,y:-40},{x:0,y:-40},{x:100,y:-40},{x:150,y:80}],widthFt:(200+130)/12},multi=curveYardEdge(multiline,2,10),insert=yardShapeInsert(multi,0);ok(insert.curves?.[0].edge===3,'Inserting another straight edge reindexes the retained arc');near(radius(insert),radius(multi),'Insertion leaves circular radius unchanged');const remove=yardShapeRemove(insert,1);ok(remove.curves?.[0].edge===2,'Removing another straight endpoint reindexes arc');near(radius(remove),radius(multi),'Removing straight point retains circle');
const withArc={...structuredClone(DEFAULT_DECK),yardFeatures:[circle]},saved=parseDeckReleaseDesign(serializeDeckReleaseDesign(withArc));near(radius(saved.yardFeatures![0]),r,'Save/load retains exact radius and control points');
const bed={id:'bed-1',name:'Bed',enabled:true,kind:'bed' as const,assetId:'mulch-bed' as const,xIn:60,zIn:60,heightIn:3,widthIn:120,depthIn:120,rotationDeg:0,mulchDepthIn:3,polygon:[{x:0,z:0},{x:120,z:0},{x:120,z:120},{x:0,z:120}]};
const objects={...structuredClone(DEFAULT_DECK),landscapeObjects:[bed]},moved=editObjects(objects,['bed-1'],{action:'move',dxIn:24,dzIn:-12});near(moved.landscapeObjects![0].polygon![0].x,24,'Bed moves its authoritative polygon');near(moved.landscapeObjects![0].polygon![0].z,-12,'Bed polygon moves with centre');
const o=emptyOrganization();o.objects=[{id:circle.id,layerId:'design',locked:true},{id:'bed-1',layerId:'design',locked:true},{id:'deck',layerId:'design',locked:true}];const locked={...withArc,landscapeObjects:[bed],editorOrganization:o};reject(()=>editObjects(locked,['bed-1'],{action:'move',dxIn:1,dzIn:0}),'Locked beds resist pointer/numeric operations');reject(()=>assertUnlockedChanges(locked,{...locked,stairRiserCount:4}),'Deck lock includes physical stair inputs');reject(()=>assertUnlockedChanges(locked,{...locked,yardFeatures:[]}),'Locked curves resist deletion');reject(()=>editObjects(objects,['bed-1'],{action:'invalid'} as never),'Unknown operation rejects atomically');
let calls=0;const unsafe={get layers(){calls++;return [];},groups:[],objects:[]};reject(()=>validateEditorOrganization(unsafe),'Organization rejects getters before reading');ok(calls===0,'Unsafe getters were never called');reject(()=>validateEditorOrganization({...o,unknown:true}),'Unknown organization fields rejected');
const privateDesign={...objects,siteModel:{version:1 as const,points:[{id:'a',xIn:0,zIn:0,elevationIn:0},{id:'b',xIn:120,zIn:0,elevationIn:0},{id:'c',xIn:0,zIn:120,elevationIn:0}],grading:[]},customerName:'Private',materialMarkup:42};const imported={...privateDesign,...portableReplacement(privateDesign,structuredClone(DEFAULT_DECK))};ok(imported.siteModel===undefined&&imported.landscapeObjects===undefined,'Portable replacement clears absent optional fields');ok(imported.customerName==='Private'&&imported.materialMarkup===42,'Portable replacement retains current private inputs');
// The asynchronous controller is the same path used by natural language preview/apply.
let state:DeckAgentHostState={data:withArc,view:'plan',openSections:[],canUndo:false,canRedo:false,ready:true},history=emptyHistory<DeckData>(),commits=0;
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{history=recordChange(history,state.data,'controller',Date.now());state={...state,data:next,canUndo:true};commits++;},undo:()=>{const result=undoChange(history,state.data)!;history=result.history;state={...state,data:result.design,canUndo:!!history.past.length,canRedo:true};},redo:()=>{const result=redoChange(history,state.data)!;history=result.history;state={...state,data:result.design,canUndo:true,canRedo:!!history.future.length};},setView:view=>{state={...state,view};},openSection:section=>{state={...state,openSections:[section]};},waitForRender:()=>Promise.resolve(),actions:{},shareOrigin:'http://localhost:4320'});
const command:AgentCommand={type:'yard.radius',id:circle.id,index:0,radiusIn:r+20},before=serializeDeckReleaseDesign(state.data),preview=await api.preview({id:'arc-preview',commands:[command],expectedRevision:api.read().revision});ok(preview.ok&&commits===0&&serializeDeckReleaseDesign(state.data)===before,'Preview computes exact edits without writes');const revision=api.read().revision,applied=await api.execute({id:'arc-apply',commands:[command],expectedRevision:revision});ok(applied.ok&&commits===1,'Apply is one commit');near(radius(state.data.yardFeatures![0]),r+20,'Applied exact radius');const stale=await api.execute({id:'arc-stale',commands:[command],expectedRevision:revision});ok(!stale.ok&&commits===1,'Stale revision cannot overwrite newer geometry');await api.execute({id:'arc-undo',commands:[{type:'history.undo'}]});near(radius(state.data.yardFeatures![0]),r,'Undo restores radius');
const {loadSiteEngine}=await import('../src/features/deckcraft/siteSurface');await loadSiteEngine();
const site={version:1 as const,points:[{id:'a',xIn:500,zIn:500,elevationIn:0},{id:'b',xIn:740,zIn:500,elevationIn:0},{id:'c',xIn:740,zIn:740,elevationIn:0},{id:'d',xIn:500,zIn:740,elevationIn:0}],grading:[{id:'g',name:'Grade',boundary:[{x:500,y:500},{x:740,y:500},{x:740,y:740},{x:500,y:740}],originXIn:500,originZIn:500,elevationIn:12,slopeXPct:0,slopeZPct:0}]};const graded=buildYardTakeoff({...DEFAULT_DECK,siteModel:site,yardFeatures:[]});near(graded.quantities.siteEarthworkFillYd3,400/27,'Grading-only earthwork measured analytically');ok(graded.sections.some(s=>s.id==='site-grading-fill'&&s.amountCents===null),'Grading-only fill remains explicitly unpriced');ok(graded.sections.some(s=>s.id==='yard-excavation-equipment'),'Grading-only site crew/equipment remains visible');const painted=buildYardTakeoff({...DEFAULT_DECK,siteModel:site,landscapeObjects:[{...bed,kind:'plant',assetId:'deciduous-tree',polygon:undefined}]});near(painted.quantities.siteEarthworkFillYd3,graded.quantities.siteEarthworkFillYd3,'Visual plant proxies do not alter excavation');
const bedQuote=buildYardTakeoff({...DEFAULT_DECK,landscapeObjects:[{...bed,edging:true}]});
near(bedQuote.sections.find(s=>s.id==='landscape-mulch-bed-1')!.quantity!,100*3/324,'Mulch uses cubic yards, separate from preparation');
near(bedQuote.sections.find(s=>s.id==='landscape-edging-bed-1')!.quantity!,40,'Edging uses unique feet, separate from bed area');
const {buildAssistantContext,assistantPlanSchemaForContext}=await import('../src/features/deckcraft/designer/assistantPlan');
const snapshot=api.read(),largeSite={...site,points:Array.from({length:2000},(_,i)=>({id:`survey-${i}`,xIn:(i%50)*12,zIn:Math.floor(i/50)*12,elevationIn:i/100}))};
const extendedSnapshot={...snapshot,design:{...snapshot.design,siteModel:largeSite,landscapeObjects:Array.from({length:80},(_,i)=>({...bed,id:`bed-${i}`,name:`Landscape ${i}`})),customerName:'PRIVATE-CUSTOMER',deckPriceBook:{private:'PRIVATE-PRICE'} as never}};const context=buildAssistantContext(extendedSnapshot);
ok(Buffer.byteLength(JSON.stringify(context))<=20000&&context.siteDataOmitted&&context.truncated,'Oversized measured context remains bounded and discloses omission');
ok((context.design.yardFeatures as {id:string}[]).some(f=>f.id===circle.id),'Large survey does not hide the selected yard inventory first');
ok(!JSON.stringify(context).includes('PRIVATE-CUSTOMER')&&!JSON.stringify(context).includes('PRIVATE-PRICE'),'Assistant context never includes customer/rate fields');
const contextChoices=assistantPlanSchemaForContext(context).anyOf![0].properties!.commands.items!.anyOf!;
ok(!contextChoices.some(c=>String(c.properties!.type.const).startsWith('site.')),'Omitted survey cannot generate invisible point edits');
reject(()=>parseDeckReleaseDesign(serializeDeckReleaseDesign({...withArc,landscapeObjects:[{...bed,id:circle.id}]})),'Yard and landscape IDs cannot alias');
reject(()=>editObjects({...withArc,landscapeObjects:[{...bed,id:circle.id}]},[circle.id],{action:'move',dxIn:12,dzIn:0}),'Invalid shared IDs cannot move or teleport two objects');
reject(()=>serializeDeckReleaseDesign({...objects,landscapeObjects:[{...bed,id:'site'}]}),'Reserved terrain identity cannot be assigned to landscape');
reject(()=>curveYardEdge({...wall,kind:'patio',widthFt:20,depthFt:10,wallPath:undefined,outline:[{x:0,y:0},{x:240,y:0},{x:240,y:120},{x:0,y:120}]},0,120),'Exact semicircle tangent to opposite edge is rejected');
const {yardGradeIn,yardSurfaceIn,yardElevationEdit}=await import('../src/features/deckcraft/yardElevations');
const surveyPatio={...wall,id:'survey-patio',kind:'patio' as const,xFt:620/12,zFt:620/12,heightIn:5},surveyData={...DEFAULT_DECK,siteModel:site};
near(yardGradeIn(surveyData,surveyPatio),12,'Elevation controls use proposed surveyed datum');
near(yardSurfaceIn(surveyData,surveyPatio),17,'Displayed patio top agrees with shared terrain');
const slopedData={...surveyData,siteModel:{...site,grading:[{...site.grading[0],slopeXPct:2.5,slopeZPct:-1}]}};
near(yardGradeIn(slopedData,surveyPatio),13.8,'Elevation controls use both across and out proposed slopes');
near(yardSurfaceIn(slopedData,{...surveyPatio,kind:'retaining-wall',baseElevationIn:2,heightIn:24}),39.8,'Wall top control shares measured datum');
const matched=yardElevationEdit(surveyPatio,'heightIn',36-yardGradeIn(slopedData,surveyPatio));near(yardSurfaceIn(slopedData,matched),36,'Numeric top matching lands exactly on requested site elevation');
ok(Number.isNaN(yardGradeIn(surveyData,{...surveyPatio,xFt:200})),'Unknown elevation coverage does not silently use legacy grade');
const legacyData={...DEFAULT_DECK,terrainConfig:{elevationIn:4,slopePct:2,widthFt:80,depthFt:80}};near(yardGradeIn(legacyData,surveyPatio),16.4,'Legacy single slope elevation controls remain unchanged');
console.log(`${checks} site workflow checks passed.`);

