import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {validateDesign,serializeDesign,parseDesign} from '../src/features/deckcraft/designPersistence';
import {validateYardFinishedSettings} from '../src/features/deckcraft/yardFinishedSettings';
import {stoneStepBlanks} from '../src/features/deckcraft/stoneSteps';
import {buildYardModel} from '../src/features/deckcraft/yardModel';
import {buildYardTakeoff} from '../src/features/deckcraft/yardTakeoff';
import {lowerPrisms,prismVolume} from '../src/features/deckcraft/materialPrisms';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {emptyHistory,recordChange,undoChange} from '../src/features/deckcraft/designer/designHistory';
let checks=0;
const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;};
const near=(v:number,expected:number,m:string)=>ok(Math.abs(v-expected)<Math.max(1e-8,Math.abs(expected)*.001),`${m}: ${v} versus ${expected}`);
const flight:YardFeature={id:'stone-flight',name:'Solid stairs',kind:'patio',enabled:true,xFt:60,zFt:60,widthFt:8,depthFt:8,heightIn:0,rotationDeg:0,productId:'permacon-mondrian-plus',color:'#b8b5ae',finishedElevationIn:24,stoneSteps:{lowerElevationIn:0,riserCount:4,treadRunIn:24,stockWidthIn:48,stockDepthIn:24,stockThicknessIn:6,baseDepthIn:6,settingBedIn:1,jointIn:.125,productName:'Entered custom cut-stone planning stock'}};
const make=(features:YardFeature[]):DeckData=>({...structuredClone(DEFAULT_DECK),houseVisible:false,stairFlights:0,railingType:'None',yardFeatures:features,terrainConfig:{widthFt:250,depthFt:250,elevationIn:0,slopePct:0}});
const d=make([flight]);await ensureLiveDesignExtensions(d);
const m=buildYardModel(d),f=m.features[0],area=4*96*(96-.125)/144/4;
ok(!f.excluded,'Complete flight rendered');ok(f.quantities.stoneStepPieces===8,'Two stock units per tread');ok(f.quantities.stoneStepCuts===4,'Last unit cut for the recorded joint');
near(f.quantities.stoneStepAreaSqft,area,'True stock face area');near(f.quantities.baseYd3,64*6/324,'Continuous compacted base under joints');near(f.quantities.beddingYd3,64/324,'Continuous setting bed under joints');near(m.quantities.sharedExcavationYd3,16*8/324,'Stepped formation analytic excavation');
near(f.quantities.raisedFillYd3,16*16/324,'Stepped formation analytic fill');
ok(f.boxes.filter(b=>b.role==='stone-step').every(b=>b.h===6),'Rigid stock thickness preserved');ok(f.quantities.paverPieces===0,'Step units are separate from paving');
const rotated=buildYardModel(make([{...flight,rotationDeg:37}]));near(rotated.quantities.sharedExcavationYd3,m.quantities.sharedExcavationYd3,'Rotation preserves flat-site volume');
const elevated=buildYardModel({...d,terrainConfig:{...d.terrainConfig!,elevationIn:2}});near(elevated.features[0].topIn,24,'Ground edits preserve fixed upper level');ok(elevated.quantities.sharedExcavationYd3>m.quantities.sharedExcavationYd3,'Ground edits update excavation');
const buried=buildYardModel({...d,terrainConfig:{...d.terrainConfig!,elevationIn:28}});near(buried.features[0].quantities.buriedTreadAreaSqft,area,'Covered treads are measured against ground');ok(buried.warnings.some(w=>w.includes('exposed stone treads intersect')),'Ground intersections stay visible and require an explicit adjustment');
const catalogue={...flight,widthFt:(2*1067/25.4+.125)/12,depthFt:(4*368/25.4)/12,finishedElevationIn:4*180/25.4,stoneSteps:{...flight.stoneSteps!,stockWidthIn:1067/25.4,stockDepthIn:368/25.4,stockThicknessIn:180/25.4,treadRunIn:368/25.4,productName:'Raffinato nominal stock',sourceURL:'https://www.techo-bloc.com/shop/steps/raffinato-step'}};
near(stoneStepBlanks(catalogue).rise,180/25.4,'Manufacturer stock rise retained');
assert.throws(()=>validateYardFinishedSettings({...flight,stoneSteps:{...flight.stoneSteps!,stockDepthIn:25}}));checks++;
assert.throws(()=>validateYardFinishedSettings({...flight,stoneSteps:{...flight.stoneSteps!,riserCount:2.5}}));checks++;
assert.throws(()=>validateYardFinishedSettings({...flight,finishedElevationIn:30}));checks++;
let invoked=false;const hostile={...flight};Object.defineProperty(hostile,'stoneSteps',{enumerable:true,get(){invoked=true;return flight.stoneSteps;}});assert.throws(()=>validateYardFinishedSettings(hostile));ok(!invoked,'Assembly getters rejected before invocation');
const wall:YardFeature={id:'wall-connection',name:'Retaining wall',kind:'retaining-wall',enabled:true,xFt:60,zFt:60,widthFt:20,depthFt:1,heightIn:24,finishedElevationIn:24,rotationDeg:0,productId:'segmental-concrete',color:'#aaa69b'};
const longWall={...wall,widthFt:130,wallPath:[{x:72,y:-210},{x:-204,y:-210},{x:-204,y:210},{x:204,y:210},{x:204,y:-210},{x:168,y:-210}]};ok(validateDesign(make([longWall])).yardFeatures![0].widthFt===130,'Continuous 130 ft wall path round-trips');ok(!buildYardModel(make([longWall])).features[0].excluded,'Continuous enclosure stays inside the stock budget');assert.throws(()=>validateDesign(make([{...wall,widthFt:81}])));checks++;assert.throws(()=>validateDesign(make([{...longWall,widthFt:241}])));checks++;
const patio:YardFeature={...flight,id:'paving',name:'Paving',zFt:65,widthFt:16,depthFt:10,stoneSteps:undefined};
const legacy=buildYardModel(make([wall,patio])),connected=buildYardModel(make([{...wall,pavingInterface:{jointIn:.375}},patio]));
ok(connected.features[1].quantities.paverAreaSqft>legacy.features[1].quantities.paverAreaSqft,'Explicit interface restores paving over working space');
ok(connected.features[0].quantities.pavingSupportPartitionYd3>0,'Wall fill is partitioned below paving formation');ok(connected.features[0].quantities.backfillYd3<legacy.features[0].quantities.backfillYd3,'Overlapping backfill removed from quantities');
ok(connected.features[0].quoteRequired,'Support connection remains an explicit unresolved scope');
const planes=[{polygon:[{x:0,y:0},{x:120,y:0},{x:120,y:120},{x:0,y:120}],topPlane:{x:0,z:0,constant:12},bottomPlane:{x:0,z:0,constant:0}}];
const split=lowerPrisms(planes,[planes[0].polygon],{x:.1,z:0,constant:0});near(split.reduce((n,p)=>n+prismVolume(p),0),120*120*6/46656,'Crossing support plane integrates analytically');
const restored=parseDesign(serializeDesign(validateDesign(d)));assert.deepEqual(restored.yardFeatures?.[0].stoneSteps,flight.stoneSteps);checks++;
const t=buildYardTakeoff(d,m);ok(t.sections.some(s=>s.id.endsWith('-supply')&&s.quantity===8),'Unpriced stone supply uses units');ok(t.sections.some(s=>s.id.endsWith('-install')&&s.quantity===4),'Installation uses risers');ok(!t.materials.some(s=>s.installedAreaSqft>0),'Stone stairs do not charge paver supply');
let state:DeckAgentHostState={data:validateDesign(d),view:'3d',openSections:[],canUndo:false,canRedo:false,ready:true},history=emptyHistory<DeckData>(),commits=0;
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{history=recordChange(history,state.data,'stairs',++commits);state={...state,data:next,canUndo:true};},undo:()=>{const undo=undoChange(history,state.data)!;history=undo.history;state={...state,data:undo.design,canUndo:false,canRedo:true};},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:()=>Promise.resolve(),actions:{}});
const revision=api.read().revision,next={...flight,widthFt:9};
const request={id:'stone-preview',expectedRevision:revision,commands:[{type:'design.patch' as const,patch:{yardFeatures:[next]}}]};
const preview=await api.preview(request);ok(preview.ok&&commits===0,'Stair preview is atomic and leaves host unchanged');
ok((await api.execute({...request,id:'stone-apply'})).ok&&commits===1,'Stair apply commits once');ok(!(await api.execute({...request,id:'stone-stale'})).ok,'Stale stair revision rejected');
ok((await api.execute({id:'stone-undo',expectedRevision:api.read().revision,commands:[{type:'history.undo'}]})).ok,'Stair undo succeeds');near(state.data.yardFeatures![0].widthFt,8,'Undo restores complete stair input');
state={...state,data:{...state.data,editorOrganization:{layers:[{id:'design',name:'Design',visible:true,locked:false}],groups:[],objects:[{id:flight.id,layerId:'design',locked:true}]}}};api.notify();ok(!(await api.preview({...request,id:'stone-locked',expectedRevision:api.read().revision})).ok,'Locks reject voice/controller stair changes');
for(const name of process.argv[2]?['modern-pool-lounge','ivory-plunge-garden']:[]){const file=JSON.parse(readFileSync(resolve(process.argv[2],`${name}.json`),'utf8'));await ensureLiveDesignExtensions(file.configuration);const scene=validateDesign(file.configuration),model=buildYardModel(scene);ok(model.features.every(f=>!f.excluded),'No reference wall or patio is excluded');ok(model.features.filter(f=>f.config.stoneSteps).every(f=>!f.excluded&&f.quantities.stoneStepPieces===8),'Example flight complete');}
console.log(`HARDSCAPE FINISH OK — ${checks} analytic, stock, interface, quote, persistence, controller, stale and lock checks.`);
