import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {parseNaturalLanguageCommands} from '../src/features/deckcraft/designer/naturalLanguageCommands';
import type {DeckData} from '../src/features/deckcraft/types';
let checks=0;const check=(v:unknown,msg:string)=>{assert.ok(v,msg);checks++;};let data:DeckData=structuredClone(DEFAULT_DECK),history:DeckData[]=[];let state=()=>({data,estimate:calculateDeckReleaseEstimate(data),view:'plan',openSections:['deck'],canUndo:history.length>0,canRedo:false,ready:true} as DeckAgentHostState);
const controller=createDeckAgentController({getState:state,commitDesign:next=>{history.push(data);data=next;},undo:()=>{data=history.pop()!;},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async test=>{assert.ok(test(state()));}});
let snapshot=controller.read();
for(const [text,field,value] of [['Make the deck 20 by 14 feet','width',20],['Set deck width to 22 feet','width',22],['Change length to 168 inches','length',14],['Set deck height to 4 feet','height',48],['Set stairs width to 6 feet','stairWidth',72]] as const){const parsed=parseNaturalLanguageCommands(text,snapshot);check(parsed.ok,`Recognizes ${text}`);if(parsed.ok){const c=parsed.request.commands[0];check(c.type==='design.patch'&&c.patch[field]===value,'Exact unit conversion');check(parsed.request.expectedRevision===snapshot.revision,'Revision pinned');}}
const spoken=parseNaturalLanguageCommands('Make these stairs six feet wide',snapshot);check(spoken.ok&&spoken.request.commands[0].type==='design.patch'&&spoken.request.commands[0].patch.stairWidth===72,'Spoken demonstrative and bounded number word');
const section=parseNaturalLanguageCommands('rotate this section45degrees',snapshot,{partIds:['deck:1'],boards:[]});check(section.ok&&section.request.commands[0].type==='layout.region','Whole selected section direction');if(section.ok)check((await controller.preview(section.request)).ok,'Real whole-section geometry validates');check(!parseNaturalLanguageCommands('rotate this section45degrees',snapshot).ok,'Unselected section requests clarification');check(!parseNaturalLanguageCommands('Make these rockets six feet wide',snapshot).ok,'Unknown noun never guessed');
for(const text of ['Make it nicer','Deploy this','Send the quote','Set width to 20 feet and delete customer','Set deck width to 20','Set width to 0 feet','Set height to 900 inches','Set stairs width to 2 feet','Rotate selected boards to Infinity degrees','Set selected window width to 48 inches','Set width to 22 feet; rotate selected board to 45 degrees','x'.repeat(601)])check(!parseNaturalLanguageCommands(text,snapshot).ok,`Clarifies ${text.slice(0,45)}`);
let instruction=parseNaturalLanguageCommands('Make the deck 20 by 14 feet',snapshot);assert.ok(instruction.ok);if(instruction.ok){const original=JSON.stringify(data),preview=await controller.preview(instruction.request);check(preview.ok,'Real controller preview validates');check(JSON.stringify(data)===original&&history.length===0,'Preview has no writes/history');const execute=await controller.execute(instruction.request);check(execute.ok&&data.width===20&&data.length===14,'Actual reviewed command applies');check(history.length===1,'One atomic history edit');if(preview.ok&&execute.ok)check(preview.snapshot.pricing.total===execute.snapshot.pricing.total,'Preview and execute exact price');check(!(await controller.execute({...instruction.request,id:'stale-retry'})).ok,'Stale revision rejected');}
snapshot=controller.read();const board=snapshot.boards[8],next=snapshot.boards[10];assert.ok(board&&next);const selected={partIds:[],boards:[{level:board.modelLevel,index:board.index},{level:next.modelLevel,index:next.index}]};instruction=parseNaturalLanguageCommands('Rotate selected boards to 45 degrees',snapshot,selected);check(instruction.ok,'Plural board rotation recognized');if(instruction.ok){check(instruction.request.commands[0].type==='layout.boards','Single inventory-safe board batch');const before=JSON.stringify(data),response=await controller.preview(instruction.request);check(response.ok,'Batch validated against actual geometry');check(JSON.stringify(data)===before,'Board preview no write');if(response.ok){check(response.snapshot.design.boardLayout!.pieces.length===2,'Both original boards captured');const applied=await controller.execute(instruction.request);check(applied.ok,'Batch applies once');if(applied.ok)check(response.snapshot.pricing.total===applied.snapshot.pricing.total,'Batch exact material/labour price');}}
snapshot=controller.read();const colour=parseNaturalLanguageCommands('Colour selected boards Brown',snapshot,{partIds:[],boards:[{level:0,index:1}]});check(!colour.ok||colour.request.commands.length===1,'Colour match exact or clarification');const opening=snapshot.parts.find(p=>p.kind==='opening');if(opening){const parsed=parseNaturalLanguageCommands('Set selected opening width to 48 inches',snapshot,{partIds:[opening.id],boards:[]});check(parsed.ok,'Actual selected opening recognized');if(parsed.ok){check(parsed.request.commands[0].type==='component.edit','Shared component command');check((await controller.preview(parsed.request)).ok,'Opening model preview validates');}}
check(!parseNaturalLanguageCommands('Set selected screen height to 6 feet',snapshot,{partIds:['not-present'],boards:[]}).ok,'Missing part not guessed');check(!parseNaturalLanguageCommands('Rotate selected boards to 45 degrees',{...snapshot,ready:false},selected).ok,'Restoring design not edited');check(!parseNaturalLanguageCommands({toString:()=>{throw Error('should not execute');}},snapshot).ok,'Nontext instructions rejected');controller.dispose();console.log(`Local instructions: ${checks} checks passed.`);
