import {readFileSync} from 'node:fs';
import {PERGOLA_PRODUCTS} from '../src/features/deckcraft/pergolaFullCatalog';
import {PERGOLA_COST_PRODUCTS} from '../src/features/deckcraft/pergolaCostCatalog';
import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {newPergola} from '../src/features/deckcraft/pergolaCatalog';
import {cleanPergolaQuote,pergolaQuoteKey} from '../src/features/deckcraft/pergolaPricing';
import {calculateDeckReleaseEstimate,serializeDeckReleaseDesign,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {designLinkJson} from '../src/features/deckcraft/designLink';
import {captureJobRevision,emptyJobLibrary,saveJobRevision,exportJobLibrary,revisionRestoreDesign,cleanJobDesign} from '../src/features/deckcraft/designer/jobRevisionLibrary';
import {createDeckAgentController,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {buildAssistantContext} from '../src/features/deckcraft/designer/assistantPlan';
assert.deepEqual(PERGOLA_PRODUCTS,JSON.parse(readFileSync(new URL('../e2e/fixtures/pergola-catalog.json',import.meta.url),'utf8')),'Complete catalog preserves every price, source URL, finish, SKU, drawing and availability field after runtime split');
assert(!JSON.stringify(PERGOLA_COST_PRODUCTS).includes('https://'));
for(const p of PERGOLA_COST_PRODUCTS){const full=PERGOLA_PRODUCTS.find(f=>f.id===p.id)!;for(const v of p.variants){const f=full.variants.find(f=>f.id===v.id)!;assert.equal(v.priceCad,f.priceCad);assert.deepEqual(v.dimensions,f.dimensions);assert.equal(v.source.checkedAt,f.source.checkedAt);}assert.deepEqual(p.accessories.map(a=>a.priceCad),full.accessories.map(a=>a.priceCad));}
const design={...structuredClone(DEFAULT_DECK),width:24,length:24,pergola:{...newPergola('costco-mirador'),xFt:12,zFt:12}};
const quote=cleanPergolaQuote({supply:2345,labour:987,delivery:0,anchoring:0,structural:0,electrical:0,supplyConfirmed:true,availabilityConfirmed:true});
const data={...design,pergolaQuoteCosts:{key:pergolaQuoteKey(design),quote}};
const total=calculateDeckReleaseEstimate(data).sections.find(s=>s.title==='Aluminum pergola')!.total;
assert.equal(total,2345*1.35+987);
const revision=captureJobRevision(data,'Pergola option');assert.deepEqual(revision.data.pergola,data.pergola);assert.deepEqual(revision.data.pergolaQuoteCosts,data.pergolaQuoteCosts);
assert.deepEqual(cleanJobDesign(revision.data).pergolaQuoteCosts,data.pergolaQuoteCosts);
assert.deepEqual(revisionRestoreDesign(revision,design,true).pergolaQuoteCosts,data.pergolaQuoteCosts);
const restored=revisionRestoreDesign(revision,design,true);assert.equal(calculateDeckReleaseEstimate(restored).sections.find(s=>s.title==='Aluminum pergola')!.total,total);
const library=saveJobRevision(emptyJobLibrary(),data,'Garden','Pergola');
for(const text of [serializeDeckReleaseDesign(data),designLinkJson(data),exportJobLibrary(library)]){assert(!text.includes('pergolaQuoteCosts'));assert(!text.includes('supplyConfirmed'));assert(!text.includes('2345'));assert(!text.includes('987'));assert(text.includes('costco-mirador'));}
assert.deepEqual(parseDeckReleaseDesign(serializeDeckReleaseDesign(data)).pergola,data.pergola);
assert.throws(()=>cleanJobDesign(data,true));
const outline={...data,deckOutlines:{main:[{x:0,y:0},{x:288,y:0},{x:288,y:288},{x:0,y:270}]}};
assert.notEqual(pergolaQuoteKey(outline),data.pergolaQuoteCosts.key);
assert(calculateDeckReleaseEstimate(outline).quoteRequired.some(q=>q.includes('confirmation')));
assert.equal(pergolaQuoteKey({...data,pergola:{...data.pergola,louverDeg:30}}),data.pergolaQuoteCosts.key);
for(const patch of [{customerName:'Different customer'},{projectAddress:'Different job address'},{municipality:'Toronto'===data.municipality?'Vaughan':'Toronto'},{siteType:'Changed access'}])assert.notEqual(pergolaQuoteKey({...data,...patch} as typeof data),data.pergolaQuoteCosts.key);
assert.equal(pergolaQuoteKey({...data,deckingColor:'A different appearance'}),data.pergolaQuoteCosts.key);
let state:DeckAgentHostState={data,view:'3d',openSections:['extras'],canUndo:false,canRedo:false,ready:true};
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{state={...state,data:next};},undo:()=>{},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:async()=>{}});
const publicSnapshot=api.read();assert(!('pergolaQuoteCosts' in publicSnapshot.design));assert.deepEqual(publicSnapshot.design.pergola,data.pergola);
const context=JSON.stringify(buildAssistantContext(publicSnapshot));assert(!context.includes('pergolaQuoteCosts'));assert(!context.includes('2345'));assert(!context.includes('987'));assert(!context.includes('supplyConfirmed'));
const good=await api.preview({id:'pergola-move',commands:[{type:'design.patch',patch:{pergola:{...data.pergola,xFt:13,rotationDeg:30,lighting:'perimeter-led'}}}]});assert(good.ok);if(good.ok)assert.equal(good.snapshot.design.pergola!.rotationDeg,30);
for(const patch of [{pergola:{...data.pergola,supply:2345}},{pergolaQuoteCosts:data.pergolaQuoteCosts}])assert(!(await api.preview({id:Math.random().toString(),commands:[{type:'design.patch',patch}]})).ok);
api.dispose();console.log('PERGOLA CONSOLIDATION OK — private revision pricing restored; public JSON, links, portable jobs, agent snapshots and AI context exclude private fields; scope changes invalidate quotes; public agent edits validate nested selection.');
