import assert from 'node:assert/strict';
import {insertBoundaryPointAt,moveBoundary,boundaryPatch,editableBoundaries,boundaryProblem} from '../src/features/deckcraft/designer/boundaryEditMath';
import {projectBoundaryPull,keyboardBoundaryPull} from '../src/features/deckcraft/designer/boundaryPullDirection';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {buildDeckTakeoff} from '../src/features/deckcraft/deckTakeoff';
import {calculateDeckReleaseEstimate,parseDeckReleaseDesign,serializeDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {savedBoundary} from '../src/features/deckcraft/lib/freeOutline';
import type {PlanPoint} from '../src/features/deckcraft/lib/deckGeometry';
import type {DeckData} from '../src/features/deckcraft/types';
let checks=0;const ok=(v:unknown,s:string)=>{assert.ok(v,s);checks++;},eq=(a:unknown,b:unknown,s:string)=>{assert.deepEqual(a,b,s);checks++;},near=(a:number,b:number,s:string)=>ok(Math.abs(a-b)<1e-7,s),throws=(f:()=>unknown,s:string)=>{assert.throws(f);checks++;};
const area=(p:PlanPoint[])=>p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+a.x*b.y-b.x*a.y;},0)/2;
const perimeter=(p:PlanPoint[])=>p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+Math.hypot(a.x-b.x,a.y-b.y);},0);
const rect=[{x:-24,y:-12},{x:192,y:-12},{x:192,y:144},{x:-24,y:144}],before=JSON.stringify(rect);
eq(insertBoundaryPointAt(rect,0,{x:30,y:50})[1],{x:30,y:-12},'Off-edge tap projects to chosen actual segment at an off-midpoint position');
throws(()=>insertBoundaryPointAt(rect,0,{x:900,y:0}),'Beyond finite end rejects duplicate endpoint');throws(()=>insertBoundaryPointAt(rect,0,{x:-23.5,y:4}),'Near endpoint rejects sub-inch split');throws(()=>insertBoundaryPointAt(rect,9,{x:30,y:0}),'Invalid edge rejected');throws(()=>insertBoundaryPointAt(rect,0,{x:NaN,y:0}),'Nonfinite position rejected');
const polygon64=Array.from({length:64},(_,i)=>({x:120*Math.cos(i*Math.PI/32),y:120*Math.sin(i*Math.PI/32)}));ok(!boundaryProblem(polygon64),'64-point budget fixture is a valid deck');throws(()=>insertBoundaryPointAt(polygon64,0,{x:119,y:8}),'64-point budget refuses insertion');
for(let index=0;index<4;index++)for(let n=1;n<40;n++){const a=rect[index],b=rect[(index+1)%4],t=n/40,p={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},inserted=insertBoundaryPointAt(rect,index,p);near(inserted[index+1].x,p.x,'Exact off-midpoint X');near(inserted[index+1].y,p.y,'Exact off-midpoint Y');near(area(inserted),area(rect),'Insertion preserves actual area');near(perimeter(inserted),perimeter(rect),'Insertion preserves real fascia/rail perimeter');eq(inserted.filter((_,i)=>i!==index+1),rect,'All original endpoints remain unchanged');}
eq(JSON.stringify(rect),before,'Insertion never mutates source vertices');
eq(projectBoundaryPull(12,18,'x',45),{x:12,y:0},'X pull cannot drift out');eq(projectBoundaryPull(12,18,'y',45),{x:0,y:18},'Y pull cannot drift across');eq(projectBoundaryPull(12,18,'any',NaN),{x:12,y:18},'Any movement remains exact and does not depend on stale custom angle');
const diagonal=projectBoundaryPull(12,0,'custom',45);near(diagonal.x,6,'45-degree projection true X displacement');near(diagonal.y,6,'45-degree projection true Y displacement');
for(const angle of [-360,-123,-45,0,30,90,135,360])for(let n=0;n<40;n++){const dx=n*.37-9,dy=n*.73-17,result=projectBoundaryPull(dx,dy,'custom',angle),r=angle*Math.PI/180,u={x:Math.cos(r),y:Math.sin(r)};near(result.x*u.y-result.y*u.x,0,'Projected pull remains on the chosen angle');near((dx-result.x)*u.x+(dy-result.y)*u.y,0,'Discarded movement is perpendicular to chosen angle');ok(Math.hypot(result.x,result.y)<=Math.hypot(dx,dy)+1e-7,'Projection never invents movement');}
const step=keyboardBoundaryPull('ArrowRight',12,'custom',45)!;near(Math.hypot(step.x,step.y),12,'Custom Shift arrow moves exactly one foot along direction');near(step.x-step.y,0,'Keyboard shares custom direction');eq(keyboardBoundaryPull('ArrowUp',1,'x',45),{x:0,y:0},'Orthogonal arrow cannot violate fixed X axis');eq(keyboardBoundaryPull('Tab',1,'custom',NaN),null,'Ordinary focus keys are not trapped by invalid draft');throws(()=>projectBoundaryPull(1,2,'custom',361),'Out-of-range custom angle rejected');throws(()=>projectBoundaryPull(1,2,'custom',NaN),'Nonfinite custom angle rejected');
const data:DeckData={...structuredClone(DEFAULT_DECK),deckType:'Freestanding',houseVisible:false,stairFlights:0,levels:3,width2:8,length2:8,height2:24,level3:{widthFt:6,lengthFt:6,heightIn:12,parent:2,position:'Front',offsetPct:50},deckOutlines:{main:savedBoundary(rect),second:[{x:0,y:0},{x:8,y:0},{x:8,y:8},{x:0,y:8}],third:[{x:0,y:0},{x:6,y:0},{x:6,y:6},{x:0,y:6}]}};
const model=buildDeckTakeoff(data),estimate=calculateDeckReleaseEstimate(data),immutable=JSON.stringify(data);
for(const boundary of editableBoundaries(data,model)){const p=boundary.points,a=p[0],b=p[1],inserted=insertBoundaryPointAt(p,0,{x:a.x+(b.x-a.x)*.3,y:a.y+(b.y-a.y)*.3}),patch=boundaryPatch(data,boundary.level,inserted,boundary.offset,model)!;ok(!!patch,`Actual level${boundary.level} insertion builds a valid patch`);const next={...data,...patch},priced=calculateDeckReleaseEstimate(next);eq(priced.model.quantities,estimate.model.quantities,'Collinear insertion does not invent installed quantities');eq(priced.total,estimate.total,'Insertion does not invent a priced difference');const parsed=parseDeckReleaseDesign(serializeDeckReleaseDesign(next));eq(parsed.deckOutlines,next.deckOutlines,'Actual added point persists without loss');near(priced.total,priced.subtotal+priced.hst,'Accounting remains reconciled');}
eq(JSON.stringify(data),immutable,'Preview/patch does not mutate design');
const locked={...data,boundaryLocks:[{level:1 as const,edge:0,dxIn:216,dyIn:0}]};eq(boundaryPatch(locked,1,insertBoundaryPointAt(rect,0,{x:30,y:0}),{x:0,y:0},buildDeckTakeoff(locked)),null,'Splitting a locked edge is rejected before any history mutation');
const reindexed={...data,boundaryLocks:[{level:1 as const,edge:3,dxIn:0,dyIn:-156}]},reindexPatch=boundaryPatch(reindexed,1,insertBoundaryPointAt(rect,0,{x:30,y:0}),{x:0,y:0},buildDeckTakeoff(reindexed))!;eq(reindexPatch.boundaryLocks,[{level:1,edge:4,dxIn:0,dyIn:-156}],'Unchanged distant lock reindexes safely');
const added=insertBoundaryPointAt(rect,1,{x:200,y:30}),pulled=moveBoundary(added,'point',2,24,12);ok(!boundaryProblem(pulled),'Actual diagonal pull produces a valid reshaped polygon');ok(area(pulled)>area(added),'Pull changes physical area rather than a decorative handle');
console.log(`Deck pull points: ${checks} finite-edge, physical projection, keyboard, lock, persistence and accounting assertions passed.`);
