import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {deckReleaseData,calculateDeckReleaseEstimate,serializeDeckReleaseDesign,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {boundaryPatch,editableBoundaries,moveBoundary} from '../src/features/deckcraft/designer/boundaryEditMath';
import {prepareDesignUpdate} from '../src/features/deckcraft/designer/designUpdate';
import {createDeckAgentController,type AgentCommand,type DeckAgentHostState} from '../src/features/deckcraft/designer/deckAgentController';
import {encodeDesignLink,decodeDesignLink,designLinkFromHash} from '../src/features/deckcraft/designLink';
import {editKey,emptyHistory,recordChange,undoChange} from '../src/features/deckcraft/designer/designHistory';
import {generateSketchDesign} from '../src/features/deckcraft/sketch/sketchToDesign';
import type {DeckData} from '../src/features/deckcraft/types';

let checks=0;
const check=(value:unknown,message:string)=>{assert.ok(value,message);checks++;};
const base=deckReleaseData(structuredClone(DEFAULT_DECK)),model=calculateDeckReleaseEstimate(base).model,boundary=editableBoundaries(base,model)[0];
const edge=boundary.points.findIndex((a,i)=>Math.abs(boundary.points[(i+1)%boundary.points.length].x-a.x)>1),a=boundary.points[edge],b=boundary.points[(edge+1)%boundary.points.length];
const initialPatch=boundaryPatch(base,1,boundary.points,boundary.offset,model)!;
const locked:DeckData={...base,...initialPatch,boundaryLocks:[{level:1,edge,dxIn:b.x-a.x,dyIn:b.y-a.y}],customerName:'Local private job',materialMarkup:.17};
check(prepareDesignUpdate(locked,{sceneLighting:'Evening'}).boundaryLocks?.length===1,'Appearance changes retain locks');
assert.throws(()=>prepareDesignUpdate(locked,{width:base.width+2}));checks++;
check(boundaryPatch(locked,1,moveBoundary(boundary.points,'point',edge,12,0),boundary.offset,model)===null,'Single locked endpoint movement is rejected');
const moved=boundaryPatch(locked,1,moveBoundary(boundary.points,'area',0,12,24),boundary.offset,model)!;
check(!!moved&&moved.boundaryLocks?.[0].dxIn===b.x-a.x,'Whole-level translation retains vector');
check(prepareDesignUpdate(locked,moved).customerName===locked.customerName,'Guard preserves job/private data');
check(editKey(moved).startsWith('apply:'),'Boundary constraint changes use discrete history');
const saved=serializeDeckReleaseDesign(locked),restored=parseDeckReleaseDesign(saved);
check(JSON.stringify(restored.boundaryLocks)===JSON.stringify(locked.boundaryLocks),'Locks survive JSON round-trip');
check(restored.customerName===locked.customerName,'Saved job JSON retains customer details');
const share=await encodeDesignLink(locked,'http://localhost:4187'),shared=await decodeDesignLink(designLinkFromHash(new URL(share).hash)!);
check(JSON.stringify(shared.boundaryLocks)===JSON.stringify(locked.boundaryLocks)&&shared.customerName==='','Share keeps measured locks and excludes customer details');
const invalidSaved=JSON.parse(saved);invalidSaved.configuration.boundaryLocks[0].dxIn++;assert.throws(()=>parseDeckReleaseDesign(JSON.stringify(invalidSaved)));checks++;
check(prepareDesignUpdate(locked,{boundaryLocks:undefined,width:base.width+2}).boundaryLocks===undefined,'Explicit unlock permits deliberate geometry change');
const h1=recordChange(emptyHistory<DeckData>(),locked,'replace:1',1000),h2=recordChange(h1,{...locked,sceneLighting:'Evening'},'replace:2',1050);
check(h2.past.length===2&&undoChange(h2,{...locked,sceneLighting:'Daylight'})?.design.sceneLighting==='Evening','Two rapid confirmed applications remain separate undo steps');

let state:DeckAgentHostState={data:locked,view:'plan',openSections:[],canUndo:false,canRedo:false,ready:true},commits=0,id=0;
const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{commits++;state={...state,data:next,canUndo:true,canRedo:false};},undo:()=>{},redo:()=>{},setView:view=>{state={...state,view};},openSection:section=>{state={...state,openSections:[section]};},waitForRender:predicate=>{assert.ok(predicate(state));return Promise.resolve();}});
const req=(commands:AgentCommand[])=>({id:`contractor-${++id}`,expectedRevision:api.read().revision,commands});
check(api.describe().commands.includes('boundary.dimension')&&api.describe().commands.includes('component.edit'),'Agent descriptor advertises measured edits and components');
check(api.read().parts.some(p=>p.kind==='opening')&&!('customerName' in api.read().design),'Agent parts inventory is public and real');
const before=serializeDeckReleaseDesign(state.data);
check(!(await api.execute(req([{type:'boundary.dimension',level:1,index:edge,lengthIn:Math.hypot(b.x-a.x,b.y-a.y)+12}]))).ok,'Agent dimension cannot break a lock');
check(!(await api.execute(req([{type:'design.patch',patch:{width:base.width+2}}]))).ok,'Agent generic resize cannot break a lock');
check(before===serializeDeckReleaseDesign(state.data)&&commits===0,'Rejected agent edits have no writes');
const preview=await api.preview(req([{type:'boundary.move',level:1,target:'area',dxIn:12,dyIn:0}]));
check(preview.ok&&commits===0&&before===serializeDeckReleaseDesign(state.data),'Translation preview is read-only');
check((await api.execute(req([{type:'boundary.lock',level:1,index:edge,locked:false},{type:'boundary.dimension',level:1,index:edge,lengthIn:Math.hypot(b.x-a.x,b.y-a.y)+12}]))).ok,'Explicit unlock and dimension batch succeeds');
check(commits===1&&state.data.customerName===locked.customerName&&state.data.materialMarkup===.17,'Batch commits once and preserves private job rates');
const openingCount=api.read().parts.filter(p=>p.kind==='opening').length,opening=api.read().parts.find(p=>p.kind==='opening')!;
check((await api.execute(req([{type:'component.edit',id:opening.id,edit:{action:'duplicate'}}]))).ok,'Agent duplicates a real opening');
check(api.read().parts.filter(p=>p.kind==='opening').length===openingCount+1,'Opening inventory follows actual model after apply');
check(!(await api.execute(req([{type:'component.edit',id:opening.id,edit:{action:'update',fields:{customerName:'Leak'}}}]))).ok,'Component command refuses private fields');
check(!(await api.execute(req([{type:'component.edit',id:'footing:0:0',edit:{action:'update',fields:{offsetIn:99}}}]))).ok,'Generated support locations cannot be fake-edited');
const sketch=generateSketchDesign({version:1,shapes:[{id:'main',kind:'deck',label:'Deck',widthFt:20,depthFt:16,points:[{x:0,y:0},{x:20,y:0},{x:20,y:16},{x:0,y:16}]}]},locked);
check(sketch.ok&&sketch.patch?.boundaryLocks===undefined&&Object.hasOwn(sketch.patch!,'boundaryLocks')&&sketch.warnings.some(w=>w.includes('locks are cleared')),'Sketch replacement explicitly clears locks with warning');
api.dispose();
console.log(`Contractor integration: ${checks} checks passed.`);
