import assert from 'node:assert/strict';
import {browserSpeechFactory,createVoiceDictation,type RecognitionLike,type DictationEvent,type DictationUpdate} from '../src/features/deckcraft/designer/voiceDictation';
let checks=0;const check=(v:unknown,message:string)=>{assert.ok(v,message);checks++;};
class Recognition implements RecognitionLike {
 lang='';continuous=false;interimResults=false;onstart:RecognitionLike['onstart']=null;onend:RecognitionLike['onend']=null;onerror:RecognitionLike['onerror']=null;onresult:RecognitionLike['onresult']=null;starts=0;stops=0;aborts=0;failStart=false;
 start(){this.starts++;if(this.failStart)throw Error('Start failed');}stop(){this.stops++;}abort(){this.aborts++;}
 result(values:{text:string;final:boolean}[],resultIndex=0){this.onresult?.({resultIndex,results:Object.assign(values.map(v=>Object.assign([{transcript:v.text}],{isFinal:v.final})),{length:values.length})} as DictationEvent);}
}
let constructed=0;class BrowserRecognition extends Recognition{constructor(){super();constructed++;}}
check(browserSpeechFactory({})===null,'Unsupported browser detected');check(browserSpeechFactory(null)===null,'No browser surface supported');const factory=browserSpeechFactory({webkitSpeechRecognition:BrowserRecognition});check(typeof factory==='function'&&constructed===0,'Support detection never requests microphone or constructs recognition');factory!();check(constructed===1,'Recognition constructed only explicitly');
const sessions:Recognition[]=[],updates:DictationUpdate[]=[];const voice=createVoiceDictation(()=>{const r=new Recognition();sessions.push(r);return r;},u=>updates.push(u));check(sessions.length===0&&voice.read().state==='idle','Adapter construction is silent');check(voice.start(),'Explicit start succeeds');const first=sessions[0];check(first.starts===1&&voice.read().state==='starting','Permission-pending state');check(first.lang==='en-CA'&&first.continuous&&first.interimResults,'Real browser configured for Canadian editable dictation');check(!voice.start()&&sessions.length===1,'Repeated active start cannot record twice');first.onstart?.();check(voice.read().state==='listening','Native started event changes state');
first.result([{text:'make this bigger',final:false}]);check(voice.read().interimText==='make this bigger'&&voice.read().finalText==='','Interim is separate from final');first.result([{text:'make the deck twenty feet wide',final:true}]);check(voice.read().finalText==='make the deck twenty feet wide'&&voice.read().interimText==='','Final replaces interim');first.result([{text:'make the deck twenty feet wide',final:true}]);check(voice.read().finalText==='make the deck twenty feet wide','Repeated final result never duplicates');first.result([{text:'make the deck twenty feet wide',final:true},{text:'and add',final:false}],1);check(voice.read().finalText==='make the deck twenty feet wide'&&voice.read().interimText==='and add','Ordered final and interim segments kept apart');
voice.stop();voice.stop();check(first.stops===1&&voice.read().state==='stopping','Stop called once while native final result remains possible');first.onstart?.();check(voice.read().state==='stopping','Late start cannot undo Stop');first.result([{text:'make the deck twenty feet wide',final:true},{text:'and add a screen',final:true}],1);check(voice.read().finalText==='make the deck twenty feet wide and add a screen','Stop retains final native result before end');const lateResult=first.onresult,lateError=first.onerror;first.onend?.();check(voice.read().state==='idle'&&voice.read().interimText==='','End returns editable final text to idle');check(first.onresult===null&&first.onend===null&&first.onerror===null,'End detaches browser handlers');const ended=JSON.stringify(voice.read());lateResult?.({resultIndex:0,results:[Object.assign([{transcript:'wrong'}],{isFinal:true})]} as DictationEvent);lateError?.({error:'network'});check(JSON.stringify(voice.read())===ended,'Callbacks captured before end are inert');
check(voice.start(),'Restart permitted');const second=sessions[1];check(voice.read().finalText===''&&second.starts===1,'New session never repeats old text');const oldResult=second.onresult;voice.abort();check(second.aborts===1&&voice.read().state==='idle','Close aborts permission-pending recognition');check(second.onresult===null&&second.onstart===null,'Abort detaches all handlers');oldResult?.({resultIndex:0,results:[Object.assign([{transcript:'late secret text'}],{isFinal:true})]} as DictationEvent);check(voice.read().finalText===''&&voice.read().interimText==='','Aborted speech never reappears');
for(const [code,word] of [['not-allowed','permission was denied'],['service-not-allowed','service is unavailable'],['audio-capture','No microphone'],['network','could not connect'],['no-speech','No speech']] as const){voice.start();const active=sessions.at(-1)!;active.onerror?.({error:code});check(voice.read().state==='error'&&voice.read().error.includes(word),`${code} gives useful type/retry option`);check(active.aborts===1&&active.onresult===null,`${code} releases microphone handlers`);}
const failed=new Recognition();failed.failStart=true;const failing=createVoiceDictation(()=>failed,()=>{});check(!failing.start()&&failing.read().state==='error','Synchronous permission/service start failure handled');check(failed.aborts===1&&failed.onresult===null,'Failed start cleans session');
let cancellable:ReturnType<typeof createVoiceDictation>;const cancelled=new Recognition();cancellable=createVoiceDictation(()=>cancelled,u=>{if(u.state==='starting')cancellable.abort();});check(!cancellable.start()&&cancelled.starts===0,'Synchronous close during starting cannot start recording afterward');
const isolated=voice.read();isolated.error='mutated';check(voice.read().error!=='mutated','Caller cannot mutate adapter state');check(updates.length>10,'Meaningful browser lifecycle emitted');
console.log(`Voice dictation: ${checks} focused lifecycle checks passed.`);
