import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {createPlanningPool} from '../src/features/deckcraft/poolAssembly';
import {buildYardModel} from '../src/features/deckcraft/yardModel';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import type {DeckData} from '../src/features/deckcraft/types';
const data:DeckData={...structuredClone(DEFAULT_DECK),houseVisible:false,terrainConfig:{widthFt:100,depthFt:100,elevationIn:0,slopePct:0},pools:[createPlanningPool({id:'p',type:'concrete',xIn:300,zIn:400,copingTopElevationIn:0})]};
await ensureLiveDesignExtensions(data);
const original=buildYardModel(data);
assert.equal(buildYardModel(structuredClone(data)),original,'Equivalent cloned commits reuse the physical model');
assert.equal(buildYardModel({...data,editorOrganization:{layers:[],groups:[],objects:[{id:'p',layerId:'design',locked:true}]}}),original,'Locks do not rebuild physical geometry');
assert.equal(buildYardModel({...data,poolQuoteInputs:{version:1,scopes:[],packages:[]}}),original,'Private prices do not rebuild physical geometry');
const moved={...data,pools:[{...data.pools![0],xIn:320}]};
assert.notEqual(buildYardModel(moved),original,'Moving a pool derives new geometry');
assert.equal(buildYardModel(data),original,'Undo reuses its matching geometry');
assert.notEqual(buildYardModel({...data,terrainConfig:{...data.terrainConfig!,elevationIn:12}}),original,'Ground edits derive new excavation');
assert.notEqual(buildYardModel({...data,pools:[{...data.pools![0],copingTopElevationIn:6}]}),original,'Finished levels derive new geometry');
for(let i=0;i<4;i++)buildYardModel({...data,pools:[{...data.pools![0],xIn:350+i}]});
assert.notEqual(buildYardModel(data),original,'Old heavy models are evicted from the bounded cache');
console.log('8 pool geometry reuse and invalidation checks passed.');
