import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import type {DeckData,YardFeature} from '../src/features/deckcraft/types';
import {buildYardModel,yardArea,yardClip} from '../src/features/deckcraft/yardModel';
import {buildYardTakeoff} from '../src/features/deckcraft/yardTakeoff';
import {hardscapeSelection,HARDSCAPE_PRODUCTS,hardscapeBody,hardscapeProblem} from '../src/features/deckcraft/hardscapeCatalogue';
import {wallConstructionPlan} from '../src/features/deckcraft/wallConstruction';
import {yardEarthworkPlan,earthworkProblem} from '../src/features/deckcraft/yardEarthwork';
import {parseDesign,serializeDesign,validateDesign} from '../src/features/deckcraft/designPersistence';
let checks=0;const ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},near=(a:number,b:number,m:string)=>ok(Math.abs(a-b)<1e-5,`${m}: ${a} vs ${b}`);
const wall:YardFeature={id:'wall',kind:'retaining-wall',name:'QA wall',enabled:true,xFt:40,zFt:45,widthFt:20,depthFt:1,heightIn:24,rotationDeg:0,productId:'segmental-concrete',color:'#aaa69b'};
const data=(f:YardFeature[],extra:Partial<DeckData>={}):DeckData=>({...structuredClone(DEFAULT_DECK),houseVisible:false,yardFeatures:f,terrainConfig:{widthFt:250,depthFt:250,elevationIn:0,slopePct:0},...extra});
function stock(id:string):YardFeature{const p=HARDSCAPE_PRODUCTS.find(p=>p.id===id)!;const finish=p.finishes.find(f=>f.units.some(u=>hardscapeBody(u.role)))!,u=finish.units.find(u=>hardscapeBody(u.role))!,c=finish.colors.find(c=>!u.colorIds||u.colorIds.includes(c.id))!;return {...wall,productId:id,depthFt:u.lengthMm/304.8,hardscape:{finishId:finish.id,colorId:c.id,unitId:u.id,patternId:'running-bond',angleDeg:0,jointMm:0}};}
for(const h of [6,18,30,72]){const f={...wall,heightIn:h},m=buildYardModel(data([f])),q=m.features[0].quantities;ok(q.geogridLayers>=1,'Every wall carries reinforcement');ok(q.geogridSqft>0&&q.geogridOrderSqft>q.geogridSqft,'Measured grid and order allowance');near(q.geogridOrderSqft,q.geogridSqft*1.1,'Explicit 10% procurement assumption');ok(m.boxes.some(b=>b.role==='geogrid'),'Construction model includes reinforcement');const t=buildYardTakeoff(data([f]),m);ok(t.sections.some(s=>s.id==='geogrid-wall'&&s.amountCents===null&&s.quantity===q.geogridOrderSqft),'Supply/install quote has measured scope');ok(t.grandTotalCents===null,'Missing supplier rates do not become zero');}
const a=buildYardModel(data([wall])),long={...wall,wallConstruction:{geogridLengthIn:96,geogridEveryCourses:1}},b=buildYardModel(data([long]));ok(b.quantities.geogridSqft>a.quantities.geogridSqft,'Longer closer grid increases material');ok(b.quantities.excavationYd3>a.quantities.excavationYd3,'Grid length expands earthwork');ok(b.quantities.backfillYd3>a.quantities.backfillYd3,'Reinforced backfill grows with length');near(b.quantities.wallBaseYd3,a.quantities.wallBaseYd3,'Base pad does not grow to the whole reinforcement area');
const parsed=parseDesign(serializeDesign(data([long])));assert.deepEqual(parsed.yardFeatures?.[0].wallConstruction,long.wallConstruction);checks++;for(const patch of [{geogridLengthIn:0},{geogridLengthIn:Infinity},{geogridEveryCourses:0},{geogridEveryCourses:1.2},{evil:1}]){assert.throws(()=>validateDesign(data([{...wall,wallConstruction:patch as any}])));checks++;}
const duplicate=buildYardModel(data([wall,{...wall,id:'duplicate'}]));near(duplicate.quantities.excavationYd3,a.quantities.excavationYd3,'Conflicting duplicate cannot double-count excavation');ok(duplicate.features[1].excluded,'Conflicting wall is excluded');
const curve={...stock('techo-raffinato-wall'),xFt:0,zFt:0,widthFt:20,wallPath:[{x:360,y:480},{x:600,y:480}],rotationDeg:0};const p=wallConstructionPlan(curve,0);const m=buildYardModel(data([curve])),q=m.features[0].quantities;near(p.drainageDepthIn,Math.max(12,24-curve.depthFt*12),'Techo front and rear drainage minima');near(q.drainageYd3,20*p.drainageDepthIn*p.totalBodyHeightIn/3888,'Drainage actual dimensions');
const sloped=data([{...curve,widthFt:Math.hypot(240,240)/12,wallPath:[{x:360,y:360},{x:600,y:600}]}],{terrainConfig:{widthFt:250,depthFt:250,elevationIn:0,slopePct:5}}),sm=buildYardModel(sloped),sf=sm.features[0];ok(sf.quantities.minWallBurialIn>=6,'Full path retains minimum burial');ok(sf.warnings.some(w=>w.includes('stepped foundations')),'Slope requires foundation review');
const urbano=stock('permacon-urbano-wall'),up=wallConstructionPlan(urbano,0),um=buildYardModel(data([urbano]));near(up.baseDepthIn,12,'Urbano verified 12in foundation');ok(um.boxes.filter(b=>b.role==='base').every(b=>b.h===12),'Urbano geometry matches base takeoff');
const capsAudit:any[]=[];
for(const id of ['techo-raffinato-wall','techo-brandon-wall','techo-systema-wall','techo-iconic-wall','techo-rosemont-wall','permacon-keystone-wall','permacon-melville-tandem-wall','permacon-lafitt-tandem-wall','permacon-rb-wall','permacon-vario-wall','permacon-urbano-wall','oaks-nueva-75-wall','oaks-nueva-150-wall','oaks-rialto-wall','oaks-modan','oaks-gardenia-linear','oaks-laredo','unilock-lineo-dimensional-stone','unilock-rivercrest-wall','unilock-brussels-dimensional-stone','unilock-u-cara']){
 const f=stock(id),s=hardscapeSelection(f)!;ok(s.caps.length>0,`${id}: documented cap selectable`);const cap=s.caps[0],selected={...f,hardscape:{...f.hardscape!,capUnitId:cap.id}};ok(!hardscapeProblem(selected),`${id}: cap validates`);assert.deepEqual(parseDesign(serializeDesign(data([selected]))).yardFeatures?.[0].hardscape,selected.hardscape);checks++;const mm=buildYardModel(data([selected])),cc=mm.boxes.filter(b=>b.role==='wall-cap');ok(cc.length>0,'Selected cap rendered');for(const c of cc){near(c.h,cap.heightMm/25.4,'Cap full stock thickness');ok(c.stockUnitId===cap.stockUnitId,'Schedule retains factory stock ID');if(!cap.swatchKey)ok(!c.surface,'Cap never inherits body photo');}capsAudit.push({wall:id,options:s.caps.length,cap:{name:cap.name,dimensions:[cap.widthMm,cap.lengthMm,cap.heightMm],source:cap.sourceUrl}});
}
const melville=hardscapeSelection(stock('permacon-melville-tandem-wall'))!;ok(!melville.caps.some(c=>c.stockUnitId==='melville-plus-cap90'&&/margaux|shaded/.test(c.sourceColorId)),'Restricted 90mm cap colours not offered');
const keystone=hardscapeSelection(stock('permacon-keystone-wall'))!;ok(keystone.caps.some(c=>c.lengthMm<keystone.unit.lengthMm),'Narrower factory Keystone cap retained');
for(const id of ['techo-borealis-wall','techo-rocka-wall','permacon-orion-wall'])ok(hardscapeSelection(stock(id))!.caps.length===0,'Documented cap-free system');
const hairpin={...stock('techo-raffinato-wall'),xFt:0,zFt:0,widthFt:(20+Math.hypot(18,3)),wallPath:[{x:-240,y:360},{x:0,y:360},{x:-216,y:396}],heightIn:36};const hm=buildYardModel(data([hairpin])),hf=hm.features[0],first=hf.boxes.find(b=>b.role==='wall-block')!,row=hf.boxes.filter(b=>b.role==='wall-block'&&Math.abs(b.y-first.y)<.001);near(yardArea(yardClip(hf.footprints,yardClip(row.map(b=>b.polygon!)),'difference')),0,'Acute supplier course has no missing patch');near(row.reduce((n,b)=>n+yardArea([b.polygon!]),0),yardArea(hf.footprints),'Acute course does not double-fill corners');
const hauling=yardEarthworkPlan(20,5,{soilReusePct:50,spoilSwellPct:100,looseSpoilTonnesPerYd3:.8,binPayloadTonnes:5,binVolumeYd3:14});near(hauling.reusedYd3,5,'Reuse cannot exceed fill demand');near(hauling.exportBankYd3,15,'Export bank soil subtracts reuse once');near(hauling.looseSpoilYd3!,30,'Swell changes loose volume');near(hauling.spoilTonnes!,24,'Mass uses loose density');near(hauling.bins,5,'Payload can govern the bin count');ok(hauling.haulingInputsComplete,'Explicit hauling inputs recognized');ok(yardEarthworkPlan(20,5).looseSpoilYd3===null,'Unknown swell is pending rather than invented');near(yardEarthworkPlan(0,0).bins,0,'No excavation needs no bin');for(const bad of [{soilReusePct:101},{spoilSwellPct:-1},{binVolumeYd3:0},{binPayloadTonnes:Infinity},{looseSpoilTonnesPerYd3:NaN},{junk:0}])ok(!!earthworkProblem(bad),'Invalid hauling input rejected');const earthData={...data([wall]),yardEarthwork:hauling.inputs};assert.deepEqual(parseDesign(serializeDesign(earthData)).yardEarthwork,hauling.inputs);checks++;const explicit=buildYardTakeoff(earthData);near(explicit.quantities.bins,explicit.earthwork.bins,'Displayed bins and disposal calculation agree');
const all=HARDSCAPE_PRODUCTS.filter(p=>p.category==='wall').flatMap(p=>{const fs=p.finishes.find(f=>f.units.some(u=>hardscapeBody(u.role)));if(!fs)return [{wall:p.id,status:'accessory only'}];const s=hardscapeSelection(stock(p.id))!;return [{wall:p.id,status:s.caps.length?'documented cap options':['techo-borealis-wall','techo-rocka-wall','permacon-orion-wall'].includes(p.id)?'cap-free':'assembly/top-course review',options:s.caps.length}];});
writeFileSync('../wall-cap-audit.json',JSON.stringify({verifiedCaps:capsAudit,allWalls:all},null,2));console.log(`Wall construction/cap integration: ${checks} checks passed.`);
