import assert from 'node:assert/strict';
import {ASSISTANT_PLAN_SCHEMA,ASSISTANT_SYSTEM_PROMPT,assistantPlanRequest,assistantPlanSchemaForContext,buildAssistantContext,parseAssistantPlan,validateAssistantContext} from '../src/features/deckcraft/designer/assistantPlan';
import type {AssistantPlan} from '../src/features/deckcraft/designer/assistantContracts';
import {createDeckAgentController,type DeckAgentHostState,type AgentCommand} from '../src/features/deckcraft/designer/deckAgentController';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {deckReleaseData,parseDeckReleaseDesign} from '../src/features/deckcraft/deckRelease';
import {getHouseConfig} from '../src/features/deckcraft/houseSettings';
import type {DeckData} from '../src/features/deckcraft/types';
let checks=0;
const check=(condition:unknown,message:string)=>{assert.ok(condition,message);checks++;};
const edit=(commands:unknown[])=>({kind:'edit',message:'Proposed measured change for review.',assumptions:[],commands});
const clarify={kind:'clarify',message:'I need a target before changing the design.',assumptions:[],commands:[],question:'Which part should be taller?',choices:['Main deck','Selected screen']};
const accepted=(value:unknown)=>{const r=parseAssistantPlan(value);if('error'in r)throw Error(r.error);check(r.ok,'Valid structured plan accepted');return r.plan;};
const rejected=(value:unknown,message:string)=>check(!parseAssistantPlan(value).ok,message);
function fixture(extra:Partial<DeckData>={}){let state:DeckAgentHostState={data:deckReleaseData({...structuredClone(DEFAULT_DECK),customerName:'PRIVATE-CUSTOMER-781',projectAddress:'PRIVATE-ADDRESS-549',scopeOfWork:'PRIVATE-SCOPE-463',materialMarkup:37,customLaborCost:123456,...extra}),ready:true,view:'plan',openSections:[],canUndo:false,canRedo:false},commits=0;
 const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{commits++;state={...state,data:next,canUndo:true};},undo:()=>{},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:test=>{if(!test(state))throw Error('Missing synchronous host acknowledgement.');return Promise.resolve();}});
 return {api,get state(){return state;},get commits(){return commits;},change:()=>{state={...state,data:{...state.data,height:state.data.height+1}};api.notify();}};
}
async function main(){
 const f=fixture(),snapshot=f.api.read(),context=buildAssistantContext(snapshot),text=JSON.stringify(context);
 check(new TextEncoder().encode(text).length<=20000,'Model context stays within 20KB');
 check(context.revision===snapshot.revision&&context.boundaries.length===snapshot.boundaries.length,'Context retains revision and real levels');
 check(JSON.stringify(context.boundaries[0].points)===JSON.stringify(snapshot.boundaries[0].points),'Every actual measured outline vertex retained');
 for(const privateToken of ['PRIVATE-CUSTOMER','PRIVATE-ADDRESS','PRIVATE-SCOPE','customLaborCost','materialMarkup','customOverrides','priceBook','costPerSqft','priceRange','rateSource','quoteRequired','123456'])check(!text.includes(privateToken),`Context excludes ${privateToken}`);
 // Wave 2 (AI Site Designer): the model sees only a price summary, never the price book, sections or rates.
 check(JSON.stringify(context.price)===JSON.stringify({subtotal:Math.round(snapshot.pricing.subtotal),quoteItems:snapshot.quotes.length})&&!text.includes('"sections"')&&!text.includes('"hst"'),'Context carries only the subtotal and quoted-line count');
 check(context.catalogue.decking.some(m=>m.id===snapshot.design.deckingMaterial),'Current material is a real catalogue option');
 check(context.catalogue.options.railingType.includes('Glass Panels')&&!context.catalogue.options.railingType.includes('Glass'),'Actual railing names, no invented family shorthand');
 const selected=buildAssistantContext(snapshot,{partIds:snapshot.parts.slice(0,2).map(p=>p.id),boards:snapshot.boards.slice(0,2).map(b=>({level:b.modelLevel,index:b.index}))});
 check(selected.selection.boards.length===2&&selected.selection.parts.length===2,'Selected parts and current indexed board records included');
 check(selected.selection.boards[0].modelLevel===snapshot.boards[0].modelLevel,'Model-level board address does not confuse display level');
 const choices=(c:ReturnType<typeof buildAssistantContext>)=>assistantPlanSchemaForContext(c).anyOf![0].properties!.commands!.items!.anyOf!,plainChoices=choices(context),boardChoices=choices(selected);check(!plainChoices.some(s=>['layout.board','layout.boards','layout.deleteBoard'].includes(String(s.properties!.type.const))),'Without selected board inventory grammar forbids fabricated indexed board edits');const exactBatch=boardChoices.find(s=>s.properties!.type.const==='layout.boards')!;check(JSON.stringify(exactBatch.properties!.targets.const)===JSON.stringify(selected.selection.boardEdit!.targets),'Generation grammar constrains exact selected board batch addresses');check(!boardChoices.some(s=>s.properties!.type.const==='layout.board'),'Multi-board selection uses one atomic batch, no per-board index drift');check(!plainChoices.some(s=>s.properties!.type.const==='component.edit'),'No editable part selection means no invented component IDs');const allowedComponents=boardChoices.find(s=>s.properties!.type.const==='component.edit')!.properties!.id.enum!;check(allowedComponents.every(id=>selected.selection.parts.some(p=>p.id===id&&p.editable===true)),'Component generation IDs refer to actual editable selected parts');check(plainChoices.filter(s=>String(s.properties!.type.const).startsWith('boundary.')).every(s=>s.properties!.level.const===snapshot.boundaries[0].level),'Boundary grammar uses actual active level');check(!JSON.stringify(assistantPlanSchemaForContext(context)).includes('PRIVATE-CUSTOMER'),'Dynamic grammar contains no private fields');
 check(!JSON.stringify(selected).includes('layoutStockSource'),'Full stock source not sent');
 const missing=buildAssistantContext(snapshot,{partIds:['absent-part'],boards:[{level:999,index:999}]});check(missing.selection.missing.length===2&&missing.selection.truncated,'Unavailable selection explicitly disclosed');
 const leaked=structuredClone(snapshot) as any;leaked.design.quoteResolutions={privateSupplier:'SECRET-QUOTE-SUPPLIER',price:919191};const protectedContext=JSON.stringify(buildAssistantContext(leaked));check(!protectedContext.includes('quoteResolutions')&&!protectedContext.includes('SECRET-QUOTE-SUPPLIER')&&!protectedContext.includes('919191'),'New private quote resolutions never enter model context');
 const second=fixture({levels:2}),secondSnapshot=second.api.read(),deckPart=secondSnapshot.parts.find(p=>p.kind==='deck'&&p.level===2)!;const secondContext=buildAssistantContext(secondSnapshot,{partIds:[deckPart.id],boards:[]});check(secondContext.selection.parts[0].coordinateSpace==='level-local-inches'&&JSON.stringify(secondContext.selection.parts[0].localOutline)===JSON.stringify(secondSnapshot.boundaries[1].points),'Selected lower deck provides actual local outline, never world polygon');check(!('polygon'in secondContext.selection.parts[0]),'World deck polygon cannot be mistaken for local region');second.api.dispose();
 const huge=structuredClone(snapshot);huge.edgeSections=Array.from({length:100},(_,i)=>({...snapshot.edgeSections[0],edgeId:`edge-${i}`,label:`Real edge ${i}`}));
 const capped=buildAssistantContext(huge,{partIds:Array(24).fill(snapshot.parts[0].id),boards:Array(24).fill({level:snapshot.boards[0].modelLevel,index:0})});check(capped.edgeSections.length<=32&&capped.truncated&&capped.selection.truncated,'Oversized inventory/selection capped truthfully');
 check(new TextEncoder().encode(JSON.stringify(capped)).length<=20000,'Large public context remains bounded');
 const clone=validateAssistantContext(context);clone.design.width=999;check(context.design.width!==999,'Validated context is a detached copy');
 for(const [target,key,value] of [['top','customerName','secret'],['design','customLaborCost',9],['design','materialMarkup',9],['design','railingLf',99],['catalogue','priceBook',{}],['selection','pricing',{}]] as const){const bad=structuredClone(context) as any;(target==='top'?bad:bad[target])[key]=value;assert.throws(()=>validateAssistantContext(bad));checks++;}
 const badPart=structuredClone(selected) as any;badPart.selection.parts[0].customerName='private';assert.throws(()=>validateAssistantContext(badPart));checks++;
 const width=accepted(edit([{type:'design.patch',patch:{width:20}}]));check(width.kind==='edit','Measured edit plan accepted');
 accepted(clarify);rejected({...clarify,commands:[{type:'design.patch',patch:{width:20}}]},'Clarification cannot contain edits');rejected({...clarify,question:' '},'Question must be meaningful text');rejected({...edit([{type:'design.patch',patch:{width:20}}]),question:'What?'},'Edit cannot hide pending clarification');
 for(const command of [{type:'action',action:'review.open'},{type:'action',action:'share.create'},{type:'action',action:'send'},{type:'view.set',view:'3d'},{type:'history.undo'},{type:'design.replace',design:{}},{type:'eval',code:'alert(1)'},{type:'fetch',url:'http://example.com'}])rejected(edit([command]),`${command.type} cannot enter assistant edit path`);
 for(const key of ['customerName','projectAddress','scopeOfWork','customLaborCost','materialMarkup','customOverrides','addOnHardwareCost','generatedImageUrl','isGeneratingImage','railingLf','unknown','__proto__']){const patch=JSON.parse(`{"${key}":1}`);rejected(edit([{type:'design.patch',patch}]),`Unknown/private/derived ${key} rejected`);}
 rejected(edit([{type:'design.patch',patch:{houseConfig:{openings:[{id:'x',execute:'evil'}]}}}]),'Nested patch field injection rejected');
 rejected(edit([{type:'design.patch',patch:{deckingMaterial:'invented-product'}}]),'Unknown catalogue material rejected');
 rejected(edit([{type:'design.patch',patch:{railingType:'Screen'}}]),'Privacy cannot invent a railing product');rejected(edit([{type:'design.patch',patch:{width:20}},{patch:{width:20},type:'design.patch'}]),'Duplicate commands rejected independent of key order');
 rejected(edit([{type:'layout.region',region:{id:'region:bad',level:1,polygon:[{x:0,y:0},{x:120,y:0},{x:120,y:120}],angleDeg:30}}]),'Layout ID conforms to actual64character identifier grammar');rejected(edit([{type:'layout.board',modelLevel:0,index:0,pieceId:'piece',colour:'fake:Invented'}]),'Invented catalogue colour reference rejected');
 rejected(edit([{type:'design.patch',patch:{width:NaN}}]),'NaN rejected');rejected(edit([{type:'design.patch',patch:{width:Infinity}}]),'Infinity rejected');rejected(edit([{type:'design.patch',patch:{width:'20'}}]),'Numeric dimension string rejected');rejected(edit([{type:'design.patch',patch:{houseVisible:1}}]),'Boolean switch is strict');rejected(edit([{type:'design.patch',patch:{}}]),'No-op empty patch rejected');
 rejected(edit([{type:'design.patch',patch:{width:20},unset:['width']}]),'Contradictory patch and unset rejected');rejected(edit([{type:'design.patch',patch:{width:20},unset:['wrap','wrap']}]),'Duplicate unset rejected');
 rejected(edit([]),'Empty edit rejected');rejected(edit(Array(9).fill({type:'design.patch',patch:{width:20}})),'Maximum eight atomic edits');rejected('```json\n'+JSON.stringify(edit([{type:'design.patch',patch:{width:20}}]))+'\n```','Markdown fences are not JSON');rejected('{"kind":','Malformed JSON rejected');
 const sparse:any[]=[];sparse.length=1;rejected(edit(sparse),'Sparse command array rejected');const decorated:any[]=[{type:'design.patch',patch:{width:20}}];(decorated as any).sideEffect=true;rejected(edit(decorated),'Decorated array rejected');const symbols=edit([{type:'design.patch',patch:{width:20}}]) as any;symbols[Symbol('hidden')]=true;rejected(symbols,'Symbol keys rejected');
 let getters=0;const getter=edit([{type:'design.patch',patch:{}}]) as any;Object.defineProperty(getter.commands[0].patch,'width',{enumerable:true,get:()=>{getters++;return 20;}});rejected(getter,'Accessor payload rejected');check(getters===0,'Untrusted getters never execute');
 const hidden=edit([{type:'design.patch',patch:{width:20}}]);Object.defineProperty(hidden,'hidden',{value:1});rejected(hidden,'Non-enumerable payload rejected');const proto=Object.create({unsafe:true});Object.assign(proto,edit([{type:'design.patch',patch:{width:20}}]));rejected(proto,'Custom prototype rejected');
 const examples:unknown[]=[{type:'boundary.move',level:2,target:'area',dxIn:12,dyIn:-4},{type:'boundary.add',level:3,index:1},{type:'boundary.remove',level:1,index:2},{type:'boundary.set',level:1,points:[{x:0,y:0},{x:120,y:0},{x:120,y:120}]},{type:'boundary.dimension',level:1,index:0,lengthIn:192,angleDeg:22},{type:'boundary.lock',level:1,index:0,locked:true},{type:'edge.edit',edit:{action:'rail',level:1,edgeId:'actual-edge',startPct:10,endPct:40,enabled:false}},{type:'component.edit',id:'opening:existing',edit:{action:'update',fields:{widthIn:48}}},{type:'component.batch',ids:['opening:a','opening:b'],edit:{action:'distribute'}},{type:'layout.region',region:{id:'region',level:1,polygon:[{x:0,y:0},{x:120,y:0},{x:120,y:120}],angleDeg:33}},{type:'layout.breaker',breaker:{id:'break',level:2,start:{x:0,y:0},end:{x:120,y:0}}},{type:'layout.board',modelLevel:0,index:0,pieceId:'piece',angleDeg:90},{type:'layout.boards',targets:[{modelLevel:0,index:0}],idPrefix:'set',angleDeg:45},{type:'layout.remove',id:'region'},{type:'layout.deleteBoard',modelLevel:0,index:0,replacementId:'delete'},{type:'sketch.generate',document:{version:1,shapes:[{id:'main',kind:'deck',label:'Deck',points:[{x:0,y:0},{x:200,y:0},{x:200,y:100}],widthFt:20,depthFt:10}]}}];
 for(const command of examples){accepted(edit([command]));rejected(edit([{...(command as object),exec:'unsafe'}]),'Extra command keys rejected');}
 rejected(edit([{type:'boundary.move',level:1,target:'point',dxIn:1,dyIn:1}]),'Point movement requires actual index');rejected(edit([{type:'component.edit',id:'a',edit:{action:'update',fields:{pricing:1}}}]),'Component private/unknown field rejected');
 rejected(edit([{type:'design.patch',patch:{width:20}},{type:'layout.board',modelLevel:0,index:1,pieceId:'a',angleDeg:45}]),'Geometry and indexed-board edits cannot silently target different boards');
 const translated=assistantPlanRequest(width,{id:'plan-check',expectedRevision:snapshot.revision});check(translated.expectedRevision===snapshot.revision&&translated.commands.length===1,'Translator always supplies revision');assert.throws(()=>assistantPlanRequest(clarify as AssistantPlan,{id:'x',expectedRevision:0}));checks++;assert.throws(()=>assistantPlanRequest(width,{id:'x',expectedRevision:NaN}));checks++;assert.throws(()=>assistantPlanRequest(width,{id:'x'} as any));checks++;
 const nested=fixture({underDeck:{drainage:'none',ceiling:'pvc',scope:'all',gravel:true,gravelDepthIn:4,floorMesh:true}}),nestedSnapshot=nested.api.read(),partial=accepted(edit([{type:'design.patch',patch:{underDeck:{drainage:'rainescape'}}}]));assert.throws(()=>assistantPlanRequest(partial,{id:'no-snapshot',expectedRevision:0}),/snapshot/);checks++;const safeNested=assistantPlanRequest(partial,{id:'nested',expectedRevision:nestedSnapshot.revision,snapshot:nestedSnapshot});const nestedPreview=await nested.api.preview(safeNested);check(nestedPreview.ok,'Preserved nested config passes actual strict preview');if(nestedPreview.ok){check(nestedPreview.snapshot.design.underDeck?.drainage==='rainescape','Drainage request changes actual option');for(const key of ['ceiling','scope','gravel','gravelDepthIn','floorMesh'] as const)check(nestedPreview.snapshot.design.underDeck?.[key]===nestedSnapshot.design.underDeck?.[key],`Partial patch retains actual underDeck.${key}`);}check(nested.commits===0,'Preservation compile/preview has no writes');check(buildAssistantContext(nestedSnapshot).design.underDeck!==undefined,'Model sees current underDeck choices');assert.throws(()=>assistantPlanRequest(partial,{id:'stale',expectedRevision:1,snapshot:nestedSnapshot}),/current/);checks++;nested.api.dispose();
 const measured=parseDeckReleaseDesign(JSON.stringify({configuration:{...DEFAULT_DECK,houseConfig:{...getHouseConfig(DEFAULT_DECK),roofFinish:'Metal',cladding:'Brick'}},format:'golden-maple-deck-design',version:1,units:'inches-and-feet'})),houseFixture=fixture({houseConfig:measured.houseConfig}),houseSnapshot=houseFixture.api.read(),roofPlan=accepted(edit([{type:'design.patch',patch:{houseConfig:{roofColor:'#233544'}}}])),roofRequest=assistantPlanRequest(roofPlan,{id:'roof',expectedRevision:houseSnapshot.revision,snapshot:houseSnapshot}),roofPreview=await houseFixture.api.preview(roofRequest);check(roofPreview.ok,'Canonical measured house colour edit passes strict preview');if(roofPreview.ok){const b={...houseSnapshot.design.houseConfig},a={...roofPreview.snapshot.design.houseConfig};delete a.roofColor;delete b.roofColor;check(JSON.stringify(a)===JSON.stringify(b),'Nested appearance patch retains all measured openings/walls/roof options exactly');}houseFixture.api.dispose();
 const structure=fixture({height:72}),structureSnapshot=structure.api.read(),post=structureSnapshot.parts.find(p=>p.kind==='post')!,postSelection={partIds:[post.id],boards:[]},workaround=accepted(edit([{type:'boundary.move',level:1,target:'point',index:0,dxIn:-24,dyIn:0}]));assert.throws(()=>assistantPlanRequest(workaround,{id:'workaround',expectedRevision:0,snapshot:structureSnapshot,selection:postSelection,requestText:'Move this selected support post two feet left.'}),/Individual generated/);checks++;const unrelated=assistantPlanRequest(width,{id:'unrelated',expectedRevision:0,snapshot:structureSnapshot,selection:postSelection,requestText:'Make the main deck20feet wide.'});check((await structure.api.preview(unrelated)).ok,'Selected post does not block unrelated explicit main width edit');structure.api.dispose();
 const before=JSON.stringify(f.state.data),dry=await f.api.preview(translated);check(dry.ok&&dry.snapshot.design.width===20,'Real controller previews inferred edit');check(f.commits===0&&JSON.stringify(f.state.data)===before,'Planner and preview do not mutate/autosave');
 const multi=accepted(edit([{type:'design.patch',patch:{width:20}},{type:'design.patch',patch:{length:14}}]));const applied=await f.api.execute(assistantPlanRequest(multi,{id:'multi-check',expectedRevision:snapshot.revision}));check(applied.ok&&applied.snapshot.design.width===20&&applied.snapshot.design.length===14&&f.commits===1,'Two intents commit atomically once');check(f.state.data.customerName==='PRIVATE-CUSTOMER-781'&&f.state.data.materialMarkup===37,'Real edit preserves private job fields');
 const stale=await f.api.preview(translated);check('error'in stale&&stale.error.code==='stale_revision','Context revision protects against stale model responses');
 const invalidGeometry=accepted(edit([{type:'design.patch',patch:{width:1}}]));const invalid=await f.api.preview(assistantPlanRequest(invalidGeometry,{id:'invalid-size',expectedRevision:f.api.read().revision}));check(!invalid.ok&&f.commits===1,'Release preview remains final geometry validator');
  check(JSON.stringify(ASSISTANT_PLAN_SCHEMA).includes('additionalProperties'),'Response format exports strict schema for actual Ollama grammar');check(ASSISTANT_SYSTEM_PROMPT.includes('max(10%')&&/one specific (TARGET )?question/.test(ASSISTANT_SYSTEM_PROMPT)&&ASSISTANT_SYSTEM_PROMPT.includes('never an already applied')&&ASSISTANT_SYSTEM_PROMPT.includes('kind "advice"'),'System prompt exposes proportional assumption, advice kind and honest target clarification');
  const advice=accepted({kind:'advice',message:'Keep the border matching the field for a quieter look.',assumptions:[],commands:[],question:'Preview a matching border?',choices:['Yes','No']});check(advice.kind==='advice'&&advice.commands.length===0,'Advice plans are accepted without commands');assert.throws(()=>assistantPlanRequest(advice,{id:'advice',expectedRevision:0}),/Advice does not change/);checks++;
 f.api.dispose();console.log(`PASS ${checks} assistant plan checks; real controller preview/atomic commit/privacy/revision and strict local context.`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
