import {poolDraftKey} from '../src/features/deckcraft/designer/poolDraftState';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {ensureLiveDesignExtensions} from '../src/features/deckcraft/designExtensions';
import {createPlanningPool} from '../src/features/deckcraft/poolAssembly';
import {poolShapeSignature,poolLocalBounds} from '../src/features/deckcraft/poolGeometry';
import {applyPoolCommand,poolPointCommand} from '../src/features/deckcraft/poolEdits';
import {validatePoolFeature} from '../src/features/deckcraft/poolTypes';
import {createDeckAgentController,type DeckAgentHostState,type AgentCommand} from '../src/features/deckcraft/designer/deckAgentController';
import {parseNaturalLanguageCommands} from '../src/features/deckcraft/designer/naturalLanguageCommands';
import {buildAssistantContext,assistantPlanRequest,parseAssistantPlan,assistantPlanSchemaForContext} from '../src/features/deckcraft/designer/assistantPlan';
import {serializeDesign,parseDesign,validateDesign} from '../src/features/deckcraft/designPersistence';
import {designLinkJson,decodeDesignLinkFile} from '../src/features/deckcraft/designLink';
import {exportProjectBundle,importProjectBundle} from '../src/features/deckcraft/projectBundle';
import {serializePrivateProject,parsePrivateProject} from '../src/features/deckcraft/designer/jobRevisionLibrary';
import {saveStoredProject,readProjectValue,closeProjectStorage} from '../src/features/deckcraft/projectStorage';
import {editObjects} from '../src/features/deckcraft/professionalEdits';
const require=createRequire(import.meta.url);require('fake-indexeddb/auto');
let checks=0;const eq=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);checks++;},ok=(v:unknown,m:string)=>{assert.ok(v,m);checks++;},reject=(fn:()=>unknown,m:string)=>{assert.throws(fn,undefined,m);checks++;};
async function main(){
 const pool=createPlanningPool({id:'pool-test',name:'Test pool',xIn:600,zIn:600,copingTopElevationIn:3});
 const data={...structuredClone(DEFAULT_DECK),stairFlights:0 as const,pools:[pool],poolQuoteInputs:{version:1 as const,scopes:[],packages:[]}};await ensureLiveDesignExtensions(data);
 eq(poolDraftKey(structuredClone(pool)),poolDraftKey(pool),'Equivalent host clones retain input draft key');eq(poolDraftKey({...pool,product:undefined}),poolDraftKey(pool),'Absent optional defaults do not reset drafts');ok(poolDraftKey({...pool,rotationDeg:93})!==poolDraftKey(pool),'Changed authoritative rotation refreshes drafts');
 ok(validatePoolFeature(pool),'Planning pool validates');eq(poolLocalBounds(pool).lengthIn,384,'Default opening length');eq(pool.depthProfile,[{stationIn:0,depthIn:48},{stationIn:384,depthIn:48}],'Water depth defaults');
 const moved=applyPoolCommand(data,{type:'pool.move',id:pool.id,dxIn:24,dzIn:-12}).pools![0];eq(moved.copingTopElevationIn,3,'Move preserves fixed rim');eq(moved.depthProfile,pool.depthProfile,'Move preserves depth stations');
 const gradeChanged={...data,terrainConfig:{widthFt:80,depthFt:80,elevationIn:12,slopePct:2}};await ensureLiveDesignExtensions(gradeChanged);eq(gradeChanged.pools[0].copingTopElevationIn,3,'Ground changes preserve fixed pool rim');
 const product={manufacturer:'Example supplier',model:'Recorded model',sourceUrl:'https://example.com/model',shapeSignature:poolShapeSignature(pool)},matched={...data,pools:[{...pool,product}]};
 eq(applyPoolCommand(matched,{type:'pool.rotate',id:pool.id,rotationDeg:45}).pools![0].product,product,'Rotation preserves pinned SKU');
 ok(!applyPoolCommand(matched,{type:'pool.depth',id:pool.id,profile:[{stationIn:0,depthIn:48},{stationIn:384,depthIn:72}]}).pools![0].product,'Depth edit invalidates manufacturer match');
 const shaped=applyPoolCommand(matched,poolPointCommand(matched.pools[0],0,-12,0)).pools![0];ok(!shaped.product,'Shape edit invalidates manufacturer match');
 reject(()=>applyPoolCommand(data,{type:'pool.shape',id:pool.id,outline:[{x:0,y:0},{x:96,y:96},{x:0,y:96},{x:96,y:0}]}),'Crossing outline rejected');
 let reads=0;const accessor=Object.defineProperty({...data},'pools',{enumerable:true,get(){reads++;return data.pools;}});reject(()=>parseDesign(JSON.stringify({format:'invalid'})),'Unsupported public file rejected');reject(()=>{validateDesign(accessor);},'Pool field accessor rejected');eq(reads,0,'Pool validation never invokes an imported getter');
 reject(()=>applyPoolCommand(data,{type:'pool.depth',id:pool.id,profile:[{stationIn:20,depthIn:48},{stationIn:384,depthIn:48}]}),'Incomplete depth span rejected');
 const locked={...data,editorOrganization:{layers:[{id:'pool-layer',name:'Pools',visible:true,locked:true}],groups:[],objects:[{id:pool.id,layerId:'pool-layer',locked:false}]}};await ensureLiveDesignExtensions(locked);reject(()=>applyPoolCommand(locked,{type:'pool.delete',id:pool.id}),'Locked layer protects pool deletion');reject(()=>applyPoolCommand(locked,{type:'pool.edit',id:pool.id,patch:{copingTopElevationIn:10}}),'Locks protect finished settings');
 const organization=editObjects(data,[pool.id],{action:'move',dxIn:12,dzIn:24});eq(organization.pools![0].xIn,612,'Groups use same pool centre geometry');eq(organization.pools![0].copingTopElevationIn,3,'Object edits retain pool datum');
 let state:DeckAgentHostState={data,ready:true,view:'plan',openSections:[],canUndo:false,canRedo:false},previous=data,commits=0;
 const api=createDeckAgentController({getState:()=>state,commitDesign:next=>{previous=state.data as typeof data;state={...state,data:next,canUndo:true,canRedo:false};commits++;},undo:()=>{state={...state,data:previous,canUndo:false,canRedo:true};},redo:()=>{},setView:()=>{},openSection:()=>{},waitForRender:test=>{assert.ok(test(state));return Promise.resolve();}});
 const snapshot=api.read();ok(!JSON.stringify(snapshot).includes('poolQuoteInputs'),'Private pool quote inputs omitted from public controller');
 const request={id:'pool-editor-batch',expectedRevision:snapshot.revision,commands:[{type:'pool.move',id:pool.id,dxIn:12,dzIn:0},{type:'pool.rotate',id:pool.id,rotationDeg:30}] as AgentCommand[]};
 const preview=await api.preview(request);if('error'in preview)throw Error(preview.error.message);eq(state.data,data,'Pool preview leaves live project unchanged');eq(commits,0,'Pool preview has no history mutation');eq(preview.snapshot.design.pools![0].copingTopElevationIn,3,'Controller preview preserves datum');
 const applied=await api.execute(request);if('error'in applied)throw Error(applied.error.message);eq(commits,1,'Batch commits once');eq(state.data.poolQuoteInputs,data.poolQuoteInputs,'Public edit preserves private costs');
 const stale=await api.execute({...request,id:'pool-editor-stale'});ok('error'in stale&&stale.error.code==='stale_revision','Stale edits rejected');
 const undone=await api.execute({id:'pool-editor-undo',expectedRevision:applied.revision,commands:[{type:'history.undo'}]});if('error'in undone)throw Error(undone.error.message);eq(state.data.pools,data.pools,'One undo restores both pool edits');
 const spoken=parseNaturalLanguageCommands('move selected pool two feet right',api.read(),{partIds:[],boards:[],poolId:pool.id});if('clarification'in spoken)throw Error(spoken.clarification);eq(spoken.request.commands[0],{type:'pool.move',id:pool.id,dxIn:24,dzIn:0},'Voice targets exact selected pool');
 const context=buildAssistantContext(api.read(),{partIds:[],boards:[],poolId:pool.id});eq(context.selection.poolId,pool.id,'Assistant selection identifies current pool');ok(!JSON.stringify(context).includes('poolQuoteInputs'),'Assistant context omits prices');
 const plan=parseAssistantPlan({kind:'edit',message:'Move pool.',assumptions:[],commands:[{type:'pool.move',id:pool.id,dxIn:24,dzIn:0}]});if('error'in plan)throw Error(plan.error);eq(assistantPlanRequest(plan.plan,{id:'pool-assistant',expectedRevision:api.read().revision,snapshot:api.read(),selection:{partIds:[],boards:[],poolId:pool.id},requestText:'move this pool 2 feet right'}).commands.length,1,'AI proposed operation compiles against current visible pool');
 reject(()=>assistantPlanRequest(plan.plan,{id:'pool-assistant-wrong',expectedRevision:api.read().revision,snapshot:api.read(),selection:{partIds:[],boards:[]},requestText:'move this pool'}),'AI selected pool cannot be guessed');ok(JSON.stringify(assistantPlanSchemaForContext(context)).includes('pool.move'),'Context permits supported pool commands');
 const publicJson=serializeDesign(data);eq(parseDesign(publicJson).pools,data.pools,'Public design roundtrip preserves pools');ok(!publicJson.includes('poolQuoteInputs'),'JSON omits private pool pricing');
 const linked=await decodeDesignLinkFile('1j'+Buffer.from(designLinkJson(data)).toString('base64url'));eq(linked.design.pools,data.pools,'Public link roundtrip preserves pool fields');ok(!('poolQuoteInputs'in linked.design),'Link strips private pool inputs');
 const forbidden=JSON.parse(publicJson);forbidden.configuration.poolQuoteInputs=data.poolQuoteInputs;reject(()=>parseDesign(JSON.stringify(forbidden)),'Public files reject supplied private pool prices');
 const portable=await importProjectBundle(await exportProjectBundle(data));eq(portable.pools,data.pools,'Portable project preserves pool geometry');ok(!('poolQuoteInputs'in portable),'Portable project excludes private pool inputs');
 const privateText=serializePrivateProject(data),restored=parsePrivateProject(privateText);eq(restored.pools,data.pools,'Private project preserves pool shape/depth');eq(restored.poolQuoteInputs,data.poolQuoteInputs,'Private project preserves validated prices');
 await saveStoredProject('current',privateText);eq((await readProjectValue<{json:string}>('projects','current'))?.json,privateText,'IndexedDB stores complete private pool project');
 const create=await api.preview({id:'pool-create',expectedRevision:api.read().revision,commands:[{type:'pool.create',id:'second-pool',poolType:'concrete',shape:'rounded-rectangle',xIn:1100,zIn:600,copingTopElevationIn:2}]});if('error'in create)throw Error(create.error.message);eq(create.snapshot.design.pools?.length,2,'Concrete rounded pool can be created through controller');eq(create.snapshot.design.pools?.[1].copingTopElevationIn,2,'Explicit coping target retained');
 closeProjectStorage();console.log(`Pool editor/controller/voice/persistence: ${checks} checks passed.`);
}
main().catch(e=>{closeProjectStorage();console.error(e);process.exitCode=1;});
