import assert from 'node:assert/strict';
import '../src/features/deckcraft/siteModelRuntime';
import '../src/features/deckcraft/siteSurfaceEngine';
import {createSiteSurface,integrateSiteExcavation,siteSurfaceSnapshot,siteElevationWarnings} from '../src/features/deckcraft/siteSurface';
import {validateSiteModel} from '../src/features/deckcraft/siteModel';
import type {SiteModel,SiteGradingTransition,TransitionBoundary} from '../src/features/deckcraft/siteModel';
import {transitionBoundaryLength,transitionBoundaryPoint} from '../src/features/deckcraft/gradingTransitionGeometry';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
let checks=0,worstErrorPct=0;function ok(v:unknown,m:string){assert.ok(v,m);checks++;}function near(actual:number,expected:number,m:string){const error=Math.abs(actual-expected)/Math.max(1e-8,Math.abs(expected))*100;worstErrorPct=Math.max(worstErrorPct,error);ok(error<.1,`${m}: ${actual} vs ${expected} (${error}%)`);}function exact(actual:unknown,expected:unknown,m:string){assert.deepEqual(actual,expected,m);checks++;}function reject(fn:()=>unknown,m:string){assert.throws(fn,undefined,m);checks++;}
const terrain={widthFt:100,depthFt:100,elevationIn:0,slopePct:0};const square=(x:number,y:number,w:number,d:number)=>[{x,y},{x:x+w,y},{x:x+w,y:y+d},{x,y:y+d}];
function site(h:(x:number,z:number)=>number=()=>0):SiteModel{return {version:1,points:[[-120,-120],[360,-120],[360,360],[-120,360]].map(([xIn,zIn],i)=>({id:String(i),xIn,zIn,elevationIn:h(xIn,zIn)})),grading:[]};}
function boundary(x:number,z:number,length:number,h0:number,h1=h0):TransitionBoundary{return {points:[{x,y:z},{x:x+length,y:z}],elevationSource:'specified',levels:[{stationIn:0,elevationIn:h0},{stationIn:length,elevationIn:h1}]};}
function transition(a=boundary(0,0,240,0),b=boundary(0,120,240,12)):SiteGradingTransition{return {id:'ramp',name:'Ramp',enabled:true,a,b};}
const t=transition(),s=createSiteSurface({...site(),transitions:[t]},terrain);exact(s.transitionModels?.[0].status,'ready','Measured straight transition ready');near(s.cutFill.fillYd3,240*120*6/46656,'Straight triangular fill exact');near(s.cutFill.cutYd3,0,'No cut on positive ramp');near(s.sample(120,60)!,6,'Sampler agrees with actual triangle');near(s.sample(120,60,'existing')!,0,'Existing ground preserved');near(s.transitionModels![0].maxSlopePct!,10,'Slope uses fitted plane');near(s.transitionModels![0].areaSqft,200,'Plan area');exact(siteSurfaceSnapshot(s).transitionModels,s.transitionModels,'Derived transition models exposed in snapshot');exact(s.cutFill.complete,true,'Coverage complete');
const cross=transition(boundary(0,0,240,-6,18),boundary(0,120,240,6,30)),cs=createSiteSurface({...site(),transitions:[cross]},terrain);near(cs.sample(120,60)!,12,'Compound longitudinal and cross slope sampler');near(cs.cutFill.cutYd3,3600/46656,'Compound exact cut crossing zero');near(cs.cutFill.fillYd3,(240*120*12+3600)/46656,'Compound exact fill crossing zero');near(cs.transitionModels![0].maxSlopePct!,Math.sqrt(2)*10,'Compound plane slope');
const survey=site((x,z)=>.03*x-.02*z+2),measured=transition({...boundary(0,0,240,0),elevationSource:'existing',levels:undefined},{...boundary(0,120,240,0),elevationSource:'existing',levels:undefined}),ms=createSiteSurface({...survey,transitions:[measured]},terrain);near(ms.sample(111,73)!,.03*111-.02*73+2,'Measured source retains compound TIN');near(ms.cutFill.cutYd3,0,'Measured identical strip no excavation');near(ms.cutFill.fillYd3,0,'Measured identical strip no fill');
const grade={id:'g',name:'Terrace',boundary:square(-120,-120,480,480),originXIn:0,originZIn:0,elevationIn:12,slopeXPct:0,slopeZPct:0},gs=createSiteSurface({...site(),grading:[grade],transitions:[t]},terrain);near(gs.cutFill.fillYd3,(480*480*12-240*120*6)/46656,'Transition replaces grading once');const ps=createSiteSurface({...site(),grading:[grade],transitions:[transition({...boundary(0,0,240,0),elevationSource:'proposed',levels:undefined},{...boundary(0,120,240,0),elevationSource:'proposed',levels:undefined})]},terrain);near(ps.sample(120,60)!,12,'Proposed boundary captured before transition');near(ps.cutFill.fillYd3,480*480*12/46656,'Source proposed does not duplicate grading fill');
const earth=integrateSiteExcavation(cs,[{featureId:'foundation',polygons:[square(0,0,240,120)],bottomIn:-12,formationPlane:{x:0,z:0,constant:-12}}]);near(earth.excavationYd3,240*120*12/46656,'Formation below ramp counted deepest once');near(earth.fillYd3,0,'Formation removes overlapping ramp fill');const eq=integrateSiteExcavation(cs,[]);near(eq.excavationYd3,cs.cutFill.cutYd3,'Whole earthwork uses transitioned cut');near(eq.fillYd3,cs.cutFill.fillYd3,'Whole earthwork uses transitioned fill');ok(eq.regions.every(r=>r.featureId==='site-grading:transition:ramp'),'Exact transition excavation attributed');
const arcA:TransitionBoundary={points:[{x:100,y:0},{x:0,y:100}],curves:[{edge:0,bulgeIn:-(100-100/Math.sqrt(2))}],elevationSource:'specified',levels:[{stationIn:0,elevationIn:0},{stationIn:Math.PI*50,elevationIn:0}]},arcB:TransitionBoundary={points:[{x:200,y:0},{x:0,y:200}],curves:[{edge:0,bulgeIn:-(200-200/Math.sqrt(2))}],elevationSource:'specified',levels:[{stationIn:0,elevationIn:12},{stationIn:Math.PI*100,elevationIn:12}]};
const curve=transition(arcA,arcB),curveSurface=createSiteSurface({...site(),transitions:[curve]},terrain);near(transitionBoundaryLength(arcA),Math.PI*50,'Authoritative circular length retained');near(Math.hypot(transitionBoundaryPoint(arcB,.4).x,transitionBoundaryPoint(arcB,.4).y),200,'Authoritative circle radius retained');near(curveSurface.transitionModels![0].areaSqft,Math.PI*(200**2-100**2)/4/144,'Curved strip area analytic');near(curveSurface.cutFill.fillYd3,(Math.PI/2)*12/100*((200**3-100**3)/3-100*(200**2-100**2)/2)/46656,'Concentric ramp fill analytic below0.1%');
const outside=createSiteSurface({...site(),transitions:[transition(boundary(300,0,240,0),boundary(300,120,240,12))]},terrain);exact(outside.transitionModels![0].status,'pending','Outside survey pending');near(outside.sample(320,60)!,0,'Missing footprint leaves base ground unchanged');exact(outside.cutFill.complete,false,'Partial quantity unresolved');exact(outside.transitionModels![0].triangles.length,0,'No partial fake patch');near(outside.transitionModels![0].missingAreaSqft,150,'Full footprint uncovered area counted');
const concave={...site(),boundary:[{x:-120,y:-120},{x:360,y:-120},{x:360,y:360},{x:150,y:360},{x:150,y:40},{x:50,y:40},{x:50,y:360},{x:-120,y:360}],transitions:[t]},concaveSurface=createSiteSurface(concave,terrain);exact(concaveSurface.transitionModels![0].status,'pending','Interior concave uncovered strip unresolved');near(concaveSurface.transitionModels![0].missingAreaSqft,100*80/144,'Interior full footprint coverage checked');
const overlap=createSiteSurface({...site(),transitions:[t,{...t,id:'other',name:'Other',a:boundary(120,0,240,0),b:boundary(120,120,240,24)}]},terrain);ok(overlap.transitionModels!.every(m=>m.status==='pending'&&m.triangles.length===0),'Overlapping strips both excluded');near(overlap.sample(150,60)!,0,'Overlap does not invent priority');exact(overlap.cutFill.complete,false,'Overlapping transition takeoff pending');
const disabled=createSiteSurface({...site(),transitions:[{...t,enabled:false}]},terrain);exact(disabled.transitionModels,undefined,'Disabled transitions preserve baseline surface');
for(const bad of [ {...t,b:{...t.b,points:[...t.b.points].reverse()}}, {...t,a:{...t.a,levels:[{stationIn:0,elevationIn:0},{stationIn:239,elevationIn:0}]}}, {...t,a:{...t.a,levels:[{stationIn:0,elevationIn:0},{stationIn:120,elevationIn:0},{stationIn:120,elevationIn:1},{stationIn:240,elevationIn:0}]}}, {...t,a:{...t.a,points:[{x:0,y:0},{x:100,y:100},{x:0,y:100},{x:100,y:0}],levels:undefined,elevationSource:'existing' as const}}, {...t,b:t.a} ])reject(()=>validateSiteModel({...site(),transitions:[bad]}),'Invalid stations/crossings/foldovers rejected');
const sparse=[t];sparse.length=2;reject(()=>validateSiteModel({...site(),transitions:sparse}),'Sparse transitions rejected');const extra=[t];Object.defineProperty(extra,'01',{value:t,enumerable:true});reject(()=>validateSiteModel({...site(),transitions:extra}),'Noncanonical array fields rejected');let getterCalls=0;const unsafe={...t};Object.defineProperty(unsafe,'a',{get(){getterCalls++;return t.a;},enumerable:true});reject(()=>validateSiteModel({...site(),transitions:[unsafe]}),'Accessor rejected before use');exact(getterCalls,0,'No unsafe getter invoked');reject(()=>validateSiteModel({...site(),transitions:[t,t]}),'Duplicate IDs rejected');
const warnings=siteElevationWarnings({...DEFAULT_DECK,siteModel:{...site(),transitions:[t]},yardFeatures:[{id:'patio',name:'Fixed patio',kind:'patio',enabled:true,productId:'concrete-paver',color:'#777777',xFt:10,zFt:5,widthFt:5,depthFt:5,heightIn:3,rotationDeg:0,finishedElevationIn:30} as never]},s);ok(warnings.some(w=>w.includes('Fixed patio')&&w.includes('no object elevation')),'Structure conflict explicit');ok(warnings.some(w=>w.includes('abruptly')),'Mismatched specified source seam explicit');const pendingWarnings=siteElevationWarnings(DEFAULT_DECK,outside);ok(pendingWarnings.some(w=>w.includes('coverage is incomplete')),'Pending footprint warning visible');
const old=site();exact(Object.hasOwn(validateSiteModel(old),'transitions'),false,'Legacy saved model unchanged');

for(const peak of [24,-24]){const ridge={...site(),points:[[-120,-120,0],[120,-120,peak],[360,-120,0],[360,360,0],[120,360,peak],[-120,360,0]].map(([xIn,zIn,elevationIn],i)=>({id:String(i),xIn,zIn,elevationIn}))},rs=createSiteSurface({...ridge,transitions:[measured]},terrain);near(rs.sample(120,60)!,peak,'Measured ridge/valley station retained');near(rs.sample(60,60)!,peak*.75,'Ridge/valley pieces follow source plane');near(rs.cutFill.cutYd3,0,'Existing ridge/valley no cut');near(rs.cutFill.fillYd3,0,'Existing ridge/valley no fill');}
const abrupt={...grade,boundary:square(120,-120,240,480)},jump=createSiteSurface({...site(),grading:[abrupt],transitions:[transition({...boundary(0,0,240,0),elevationSource:'proposed',levels:undefined},{...boundary(0,120,240,0),elevationSource:'proposed',levels:undefined})]},terrain);exact(jump.transitionModels![0].status,'pending','Discontinuous proposed source boundary rejected');ok(jump.transitionModels![0].warnings.some(w=>w.includes('source boundary')),'Source discontinuity reason visible');near(jump.sample(30,60)!,0,'Source jump never invented smoothing');near(jump.sample(150,60)!,12,'Original source step preserved while pending');
const {loadAdvancedYardRuntime,buildYardModel}=await import('../src/features/deckcraft/yardModel');await loadAdvancedYardRuntime();const yard=buildYardModel({...DEFAULT_DECK,siteModel:{...site(),transitions:[t]},yardFeatures:[]});near(yard.quantities.siteEarthworkFillYd3,s.cutFill.fillYd3,'Whole yard takeoff uses transition fill');exact(yard.siteSurface?.transitionModels?.[0].status,'ready','Whole yard snapshot carries transitions');
console.log(`${checks} grading transition checks passed; worst analytic error ${worstErrorPct.toFixed(6)}%.`);
