import assert from 'node:assert/strict';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {assistantTargets} from '../src/features/deckcraft/designer/AssistantTargets';
import {selectableBoards} from '../src/features/deckcraft/designer/boardLayoutActions';
import {listEdgeSections} from '../src/features/deckcraft/designer/edgeSectionActions';
import type {DeckData} from '../src/features/deckcraft/types';
import type {AgentCommand} from '../src/features/deckcraft/designer/deckAgentController';
const data:DeckData={...structuredClone(DEFAULT_DECK),levels:2,stairFlights:1,customerName:'Private synthetic client'},model=calculateDeckReleaseEstimate(data).model;
const targets=(commands:AgentCommand[])=>assistantTargets({id:'target-check',commands},data,model);
let checks=0;const ok=(value:unknown,label:string)=>{assert(value,label);checks++;};
const before=JSON.stringify(data),second=selectableBoards(data,model).find(b=>b.level===2)!;
ok(second,'Second-level fixture has actual stock');
const board=targets([{type:'layout.board',modelLevel:second.modelLevel,index:second.index,pieceId:'target',angleDeg:45}]);
ok(board.length===1&&board[0].id===`board:${second.modelLevel}:${second.index}`,'Only the requested actual board is highlighted');
assert.deepEqual(board[0].polygon,second.polygon.map(p=>({x:p.x+second.offset.x,y:p.y+second.offset.y})));checks++;
ok(targets([{type:'design.patch',patch:{width2:8}}]).map(t=>t.id).join()==='deck:2','Second-level sizing never highlights main deck');
ok(targets([{type:'design.patch',patch:{stairWidth:60}}]).map(t=>t.id).join()==='stairs:primary','Stair sizing highlights actual stair polygon');
ok(targets([{type:'component.edit',id:'missing:part',edit:{action:'remove'}}]).length===0,'No invented target for missing part');
const edge=listEdgeSections(data,model).find(e=>e.eligible.length)!;
const result=targets([{type:'edge.edit',edit:{action:'rail',level:edge.level,edgeId:edge.edgeId,startPct:25,endPct:75,enabled:false}}])[0];
assert.deepEqual(result.line,[.25,.75].map(t=>({x:edge.a.x+(edge.b.x-edge.a.x)*t,y:edge.a.y+(edge.b.y-edge.a.y)*t})));checks++;
ok(targets([{type:'design.patch',patch:{width:18}},{type:'design.patch',patch:{length:16}}]).length===1,'Duplicate physical targets collapse');
ok(!JSON.stringify(board).includes('Private synthetic client'),'Highlights contain no customer identity');
ok(JSON.stringify(data)===before,'Preview targets do not mutate design or cursor selection');
console.log(`${checks} assistant target geometry checks passed`);
