import {createHash} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateEstimate} from '../src/features/deckcraft/calculations';
import {deckExportMeshes} from '../src/features/deckcraft/designExports';
import {legacyScenarios} from './deck-legacy-scenarios';
const source='file:///C:/Users/yorki/Desktop/Goldenmaplelandscaping.ca/golden-maple-landscaping/.claude/worktrees/estimator-deckcraft';
const [oldCalc,oldExport,oldDefaults,oldScenarios]=await Promise.all([import(`${source}/src/features/deckcraft/calculations.ts`),import(`${source}/src/features/deckcraft/designExports.ts`),import(`${source}/src/features/deckcraft/defaults.ts`),import(`${source}/scripts/deck-legacy-scenarios.ts`)]);
const stable=(v:unknown)=>JSON.stringify(v,(_k,n)=>typeof n==='number'?(Math.abs(n)<5e-7?0:Math.round(n*1e6)/1e6):n),digest=(v:unknown)=>createHash('sha256').update(stable(v)).digest('hex');
const differences=(old:unknown,next:unknown,path=''):unknown[]=>{
 if(stable(old)===stable(next))return [];if(old===undefined||next===undefined)return [{path,before:old,after:next}];
 if(old&&next&&typeof old==='object'&&typeof next==='object'&&Array.isArray(old)===Array.isArray(next))return [...new Set([...Object.keys(old),...Object.keys(next)])].flatMap(key=>differences((old as Record<string,unknown>)[key],(next as Record<string,unknown>)[key],path?`${path}.${key}`:key));
 return [{path,before:old,after:next}];
};
const scenarios=legacyScenarios();if(stable(scenarios)!==stable(oldScenarios.legacyScenarios()))throw Error('Source/mirror scenario definitions differ');if(stable(DEFAULT_DECK)!==stable(oldDefaults.DEFAULT_DECK))throw Error('Source/mirror defaults differ');
const rows=[],categories:Record<string,{scenarios:number;example:unknown}>={};
for(const [name,patch] of Object.entries(scenarios)){
 const d={...structuredClone(DEFAULT_DECK),...patch},before=oldCalc.calculateEstimate(d),after=calculateEstimate(d),oldMeshes=oldExport.deckExportMeshes(d,before.model),nextMeshes=deckExportMeshes(d,after.model),oldMap=new Map<string,any>(oldMeshes.map((m:any)=>[m.name,m])),nextMap=new Map(nextMeshes.map(m=>[m.name,m])),names=[...new Set([...oldMap.keys(),...nextMap.keys()])],meshDrift=names.filter(n=>digest(oldMap.get(n))!==digest(nextMap.get(n))),modelDiff=differences(before.model,after.model),priceDiff=differences({...before,model:undefined,flags:undefined},{...after,model:undefined,flags:undefined});
 for(const diff of [...modelDiff,...priceDiff] as {path:string;before:unknown;after:unknown}[]){const key=diff.path.replace(/\.\d+(?=\.|$)/g,'.*');const item=categories[key]??={scenarios:0,example:diff};item.scenarios++;}
 rows.push({name,physicalMeshesEqual:meshDrift.length===0,meshOrderEqual:stable(oldMeshes.map((m:any)=>m.name))===stable(nextMeshes.map(m=>m.name)),meshDrift,oldMeshCount:oldMeshes.length,nextMeshCount:nextMeshes.length,totalBefore:before.total,totalAfter:after.total,pricedSectionsEqual:digest(before.sections)===digest(after.sections),connectorScheduleEqual:digest(before.connectorSchedule)===digest(after.connectorSchedule),stockScheduleEqual:digest(before.stockSchedule)===digest(after.stockSchedule),quantitiesEqual:digest(before.model.quantities)===digest(after.model.quantities),issuesEqual:digest(before.model.issues)===digest(after.model.issues),flagsEqual:digest(before.flags)===digest(after.flags),modelDiff,priceDiff});
}
const phase=process.argv[2]??'before';if(!['before','after'].includes(phase))throw Error('Expected before or after');const path=resolve('../../outputs/elevation-phase',`legacy-physical-comparison-${phase}.json`);mkdirSync(resolve('../../outputs/elevation-phase'),{recursive:true});writeFileSync(path,JSON.stringify({sourceReference:source,scenarioCount:rows.length,summary:{physicalMeshesEqual:rows.filter(r=>r.physicalMeshesEqual).length,meshOrderEqual:rows.filter(r=>r.meshOrderEqual).length,totalEqual:rows.filter(r=>r.totalBefore===r.totalAfter).length,pricedSectionsEqual:rows.filter(r=>r.pricedSectionsEqual).length,connectorScheduleEqual:rows.filter(r=>r.connectorScheduleEqual).length,stockScheduleEqual:rows.filter(r=>r.stockScheduleEqual).length,quantitiesEqual:rows.filter(r=>r.quantitiesEqual).length,issuesEqual:rows.filter(r=>r.issuesEqual).length,flagsEqual:rows.filter(r=>r.flagsEqual).length},categories,rows},null,2));console.log(path);console.log(JSON.stringify({scenarios:rows.length,physicalMeshesEqual:rows.filter(r=>r.physicalMeshesEqual).length,meshOrderEqual:rows.filter(r=>r.meshOrderEqual).length,totalEqual:rows.filter(r=>r.totalBefore===r.totalAfter).length,pricedSectionsEqual:rows.filter(r=>r.pricedSectionsEqual).length,quantitiesEqual:rows.filter(r=>r.quantitiesEqual).length,issuesEqual:rows.filter(r=>r.issuesEqual).length}));console.log('Changed paths:',Object.keys(categories).join(', '));
