import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {jsPDF} from 'jspdf';
import sharp from 'sharp';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {serializeDesign} from '../src/features/deckcraft/designPersistence';
import {describeDesign} from '../src/features/deckcraft/designFacts';
import {ProposalSheet} from '../src/features/deckcraft/ProposalSheet';
import ConstructionPlan from '../src/features/deckcraft/ConstructionPlan';
import {buildProposalPdf} from '../src/features/deckcraft/proposalPdf';
import {buildUnderDeckPricing,UNDER_DECK_RATES,UNDER_DECK_POLICY} from '../src/features/deckcraft/underDeckPricing';
import type {UnderDeckConfig} from '../src/features/deckcraft/types';
const out=new URL('../../../outputs/deckcraft-under-deck-review/',import.meta.url);mkdirSync(out,{recursive:true});
const config:UnderDeckConfig={drainage:'rainescape',ceiling:'pvc',scope:'main',gravel:true,gravelDepthIn:3,floorMesh:true};
const data={...structuredClone(DEFAULT_DECK),height:108,hasDrainage:true,underDeck:config},estimate=calculateDeckReleaseEstimate(data),facts=describeDesign(data,estimate).proposalFacts,date='September 26, 2026';
writeFileSync(new URL('../../under-deck-design.json',import.meta.url),serializeDesign(data));
const cases=[];
for(const drainage of ['rainescape','dryspace','zipup'] as const){const d={...data,underDeck:{...config,drainage,ceiling:drainage==='rainescape'?'pvc' as const:'none' as const}},e=calculateDeckReleaseEstimate(d),p=buildUnderDeckPricing(d,e.model,1+d.materialMarkup/100);cases.push({name:drainage,totalBeforeHst:p.sections[0].total,crewDays:p.crewDays,area:p.area,groundArea:p.groundArea,rows:p.sections[0].items,quoteRequired:p.quoteRequired});}
writeFileSync(new URL('pricing-proof.json',out),JSON.stringify({rates:UNDER_DECK_RATES,policy:UNDER_DECK_POLICY,sampleDesign:config,projectSubtotal:estimate.subtotal,hst:estimate.hst,projectTotal:estimate.total,cases},null,2));
if(process.argv.includes('--seed-only'))process.exit(0);
const sceneFile=new URL('../../under-deck-scene.json',import.meta.url),shots=existsSync(sceneFile)?[JSON.parse(readFileSync(sceneFile,'utf8'))]:[];
const logo='data:image/png;base64,'+readFileSync(new URL('../public/logo-mark.png',import.meta.url)).toString('base64');
const plan=async(variant:'site'|'contractor')=>{let svg=renderToStaticMarkup(createElement(ConstructionPlan,{model:estimate.model,data,variant})).match(/<svg[\s\S]*<\/svg>/)?.[0];if(!svg)throw Error('Missing plan');if(variant==='site')svg=svg.replace(/<rect class="dd-plan-grid"[^>]*(?:\/>|><\/rect>)/g,'');return 'data:image/png;base64,'+(await sharp(Buffer.from(svg)).resize({width:1600}).png().toBuffer()).toString('base64');};
writeFileSync(new URL('../DeckCraft-under-deck-proposal.pdf',out),Buffer.from(buildProposalPdf(jsPDF,{data,estimate,facts,reviewItems:estimate.flags,date,logo,shots,sitePlan:await plan('site'),plan:await plan('contractor')})));
const css=readFileSync(new URL('../src/features/deckcraft/proposal.css',import.meta.url),'utf8');
const sheet=renderToStaticMarkup(createElement(ProposalSheet,{data,estimate,facts,reviewItems:estimate.flags,date,image:shots[0]?.src??null})).replaceAll('src="/logo-mark.png"',`src="${logo}"`);
writeFileSync(new URL('proposal-preview.html',out),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Under-deck planning proposal review</title><style>body{margin:0;background:#0c120e;font-family:Arial,sans-serif}*{box-sizing:border-box}:root{--dc-body:Arial,sans-serif;--dc-sheet:#fbfbf8;--font-display:Georgia,serif}${css}</style></head><body><main class="dd-proposal-root">${sheet}</main></body></html>`);
console.log(JSON.stringify({projectTotal:estimate.total,underDeck:cases[0].totalBeforeHst,proof:'DeckCraft-under-deck-proposal.pdf'}));
