import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {jsPDF} from 'jspdf';
import sharp from 'sharp';
import {DEFAULT_DECK} from '../src/features/deckcraft/defaults';
import {deckReleaseData,calculateDeckReleaseEstimate} from '../src/features/deckcraft/deckRelease';
import {describeDesign} from '../src/features/deckcraft/designFacts';
import {ProposalSheet} from '../src/features/deckcraft/ProposalSheet';
import ConstructionPlan from '../src/features/deckcraft/ConstructionPlan';
import {buildProposalPdf} from '../src/features/deckcraft/proposalPdf';
import {proposalFinishes} from '../src/features/deckcraft/proposalModel';
import {serializeDesign} from '../src/features/deckcraft/designPersistence';
const output=new URL('../../../outputs/deckcraft-board-layout-review/',import.meta.url);mkdirSync(output,{recursive:true});
const proof=JSON.parse(readFileSync(new URL('../../layout-proposal-scene.json',import.meta.url),'utf8'));
const data=deckReleaseData({...structuredClone(DEFAULT_DECK),...proof.state.design}),estimate=calculateDeckReleaseEstimate(data),facts=describeDesign(data,estimate).proposalFacts,date='September 26, 2026';
if(Math.abs(estimate.total-proof.state.pricing.total)>1e-7)throw Error('Browser and exported proposal prices differ.');
const logo='data:image/png;base64,'+readFileSync(new URL('../public/logo-mark.png',import.meta.url)).toString('base64');
const swatches:Record<string,string>={};
for(const tile of proposalFinishes(data,estimate.model))if(tile.swatch){const file=new URL('../src/features/deckcraft/assets/swatches/'+tile.swatch,import.meta.url);swatches[tile.swatch]='data:image/jpeg;base64,'+(await sharp(readFileSync(file)).resize(320,320).jpeg().toBuffer()).toString('base64');}
const plan=async(variant:'site'|'contractor')=>{const markup=renderToStaticMarkup(createElement(ConstructionPlan,{model:estimate.model,data,variant}));let svg=markup.match(/<svg[\s\S]*<\/svg>/)?.[0];if(!svg)throw Error('Plan missing');if(variant==='site')svg=svg.replace(/<rect class="dd-plan-grid"[^>]*(?:\/>|><\/rect>)/g,'');const image=await sharp(Buffer.from(svg)).resize({width:1600}).png().toBuffer();writeFileSync(new URL(`${variant}-plan.png`,output),image);return 'data:image/png;base64,'+image.toString('base64');};
const sitePlan=await plan('site'),constructionPlan=await plan('contractor');
writeFileSync(new URL('DeckCraft-custom-board-layout-proposal.pdf',output),Buffer.from(buildProposalPdf(jsPDF,{data,estimate,facts,reviewItems:estimate.flags,date,shots:[proof.shot],logo,sitePlan,plan:constructionPlan,swatches})));
writeFileSync(new URL('review-design.json',output),serializeDesign(data));
const css=readFileSync(new URL('../src/features/deckcraft/proposal.css',import.meta.url),'utf8');
const sheet=renderToStaticMarkup(createElement(ProposalSheet,{data,estimate,facts,reviewItems:estimate.flags,date,image:proof.shot.src,swatchSrc:(s:string)=>swatches[s]??''})).replaceAll('src="/logo-mark.png"',`src="${logo}"`);
writeFileSync(new URL('proposal-preview.html',output),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Custom board-layout proposal review</title><style>body{margin:0;background:#0c120e;font-family:Arial,sans-serif}*{box-sizing:border-box}:root{--dc-body:Arial,sans-serif;--dc-sheet:#fbfbf8;--font-display:Georgia,serif}${css}</style></head><body><main class="dd-proposal-root">${sheet}</main></body></html>`);
writeFileSync(new URL('pricing-proof.json',output),JSON.stringify({total:estimate.total,subtotal:estimate.subtotal,hst:estimate.hst,sections:estimate.sections,quotes:estimate.quoteRequired,stockSchedule:estimate.stockSchedule,facts,priceBook:proof.state.pricing.priceBook},null,2));
console.log(JSON.stringify({pdf:'DeckCraft-custom-board-layout-proposal.pdf',total:estimate.total,quoteItems:estimate.quoteRequired.length,physicalBoards:estimate.model.quantities.installedBoardPieces}));
